mutaborGUI::MutTag
bool mutaborGUI::MutTag::IsLogic
Referenced by GetIsLogic.
int mutaborGUI::MutTag::Key
Referenced by GetKey, OnDraw.
wxIcon mutaborGUI::MutTag::Icon
Referenced by GetMutIcon.
wxString mutaborGUI::MutTag::Text
int mutaborGUI::MutTag::TPos
mutaborGUI::MutTag::MutTag(wxWindow *parent, const wxPoint &pos, int isLogic, int isOpen, int key)
wxIcon& mutaborGUI::MutTag::GetMutIcon()
Calculates the Icon to be used.
References Icon.
int mutaborGUI::MutTag::GetKey()
References Key.
Referenced by mutaborGUI::MutLogicWnd::CmMutTag.
bool mutaborGUI::MutTag::GetIsLogic()
References IsLogic.
Referenced by mutaborGUI::MutLogicWnd::CmMutTag.
void mutaborGUI::MutTag::OnDraw(wxDC &dc)
References Key, MutIconShapeClass< T >::OnDraw, PaintCenteredText.
void mutaborGUI::MutTag::OnChar(wxKeyEvent &event)
void mutaborGUI::MutTag::OnLeftDown(wxMouseEvent &event)
References mutaborGUI::CM_MUTTAG.
void mutaborGUI::MutTag::OnGetFocus(wxFocusEvent &event)
void mutaborGUI::MutTag::PaintCenteredText(wxDC &dc, wxString s, int y)
References MutIconShapeClass< T >::GetIconRect, h.
Referenced by OnDraw.