mutabor::midi
midi_command
midi_meta_types
midi_controller_indices
non_midi_controllers
midi_controller_values
midi_registered_parameters
midi_channel_constants
int mutabor::midi::get_data_size(uint8_t status_byte)
Referenced by mutabor::Track::ReadMessage.
bool mutabor::midi::is_system_exclusive(uint8_t status)
References SYSEX_START.
Referenced by reset_running_status.
bool mutabor::midi::is_system_common(uint8_t status)
References QUARTER_FRAME, SONG_POSITION, SONG_SELECT, SYSEX_END, TUNE_REQUEST.
Referenced by reset_running_status.
bool mutabor::midi::is_system_realtime(uint8_t status)
bool mutabor::midi::is_channel_message(uint8_t status)
Referenced by store_running_status.
bool mutabor::midi::reset_running_status(uint8_t status)
References is_system_common, is_system_exclusive.
Referenced by mutabor::Track::ReadMessage.
bool mutabor::midi::store_running_status(uint8_t status)
References is_channel_message.
Referenced by mutabor::Track::ReadMessage.
bool mutabor::midi::is_hold(int controller)
Check whether a given controller is one of the hold switches.
controller controller to be checked true if it is a holding controller false if it is not a holding controller mutabor::ChannelData::get_hold()
References HOLD_2_PEDAL_ON_OFF, HOLD_PEDAL_ON_OFF, LEGATO_PEDAL_ON_OFF, SOSTENUTO_ON_OFF.
Referenced by mutabor::CommonMidiOutput< T, D >::do_Controller.
const int* mutabor::midi::get_holds()
Return a list of hold controllers.
This function returns an integer array of controllers that keep notes sounding after their regular end.list of hold controller ids.
References HOLD_2_PEDAL_ON_OFF, HOLD_PEDAL_ON_OFF, LEGATO_PEDAL_ON_OFF, SOSTENUTO_ON_OFF.
Referenced by mutabor::CommonMidiOutput< T, D >::do_NoteOn, mutabor::CommonMidiOutput< T, D >::do_UpdateTones, mutabor::InputDeviceClass::DoSilenceKeys, mutabor::InputDeviceClass::Panic, mutabor::InputDeviceClass::ResumeKeys.
int mutabor::midi::get_default_controller_value(int ctrl)
References ALL_CONTROLLERS_OFF, ALL_NOTES_OFF, ALL_SOUND_OFF, BALANCE_COARSE, BANK_COARSE, BANK_FINE, CELESTE_LEVEL, CHORUS_LEVEL, CONTROLLER_CENTRE, CONTROLLER_MAX, CONTROLLER_UNKNOWN, CONTROLLER_UNKNOWN_NOSEND, DATA_BUTTON_DECREMENT, DATA_BUTTON_INCREMENT, DATA_ENTRY_COARSE, DATA_ENTRY_FINE, EFFECTS_LEVEL, EXPRESSION_COARSE, EXPRESSION_FINE, FIRST_NRPN, FIRST_RPN, LAST_NRPN, LAST_RPN, LOCAL_ON_OFF, MODULATION_WHEEL_COARSE, MODULATION_WHEEL_FINE, MONO_ON, NON_REGISTERED_PARAMETER_COARSE, NON_REGISTERED_PARAMETER_FINE, OMNI_OFF, OMNI_ON, PAN_POSITION_COARSE, PHASER_LEVEL, POLY_ON, REGISTERED_PARAMETER_COARSE, REGISTERED_PARAMETER_FINE, SOUND_10, SOUND_ATTACK_TIME, SOUND_BRIGHTNESS, SOUND_DECAY_TIME, SOUND_RELEASE_TIME, SOUND_TIMBRE, SOUND_VARIATION, SOUND_VIBRATO_DELAY, SOUND_VIBRATO_DEPTH, SOUND_VIBRATO_RATE, TREMULO_LEVEL, VOLUME_COARSE.
Referenced by mutabor::ChannelData::MidiReset.