mutaborGUI::GUIRouteBase
MutBoxChannelShapeList mutaborGUI::GUIRouteBase::shapes
Referenced by Add, GetBoxChannelShapes, GetShape, Remove, Replace.
mutaborGUI::GUIRouteBase::GUIRouteBase()
virtual mutaborGUI::GUIRouteBase::~GUIRouteBase()
References TRACEC.
void mutaborGUI::GUIRouteBase::Add(mutabor::OutputDevice &dev)
add a new output device
References mutaborGUI::MutDeviceShape< T >::Add, mutaborGUI::GUIOutputDeviceBase::GetShape, shapes, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::GUIfiedRoute< T >::Add, mutaborGUI::connect.
void mutaborGUI::GUIRouteBase::Add(mutabor::InputDevice &dev)
add a new input device
References mutaborGUI::MutDeviceShape< T >::Add, mutaborGUI::GUIInputDeviceBase::GetShape, shapes, mutaborGUI::ToGUIBase.
void mutaborGUI::GUIRouteBase::Add(mutabor::Box &b)
add a new box
References mutaborGUI::MutBoxShape::Add, DEBUGLOG, GetRoute, intrusive_ptr_get_refcount, mutabor::MIN_BOX, mutASSERT, shapes, mutaborGUI::ToGUIBase.
bool mutaborGUI::GUIRouteBase::Replace(mutabor::OutputDevice &olddev, mutabor::OutputDevice &newdev)
replace an existing output device
References DEBUGLOG, GetRoute, mutaborGUI::GUIOutputDeviceBase::GetShape, intrusive_ptr_get_refcount, mutASSERT, Remove, shapes, mutaborGUI::ToGUIBase, UNREACHABLEC.
Referenced by Replace, mutaborGUI::GUIfiedRoute< T >::Replace.
bool mutaborGUI::GUIRouteBase::Replace(mutabor::InputDevice &olddev, mutabor::InputDevice &newdev)
replace an existing input device
References DEBUGLOG, GetRoute, mutaborGUI::GUIInputDeviceBase::GetShape, intrusive_ptr_get_refcount, mutASSERT, Remove, Replace, shapes, mutaborGUI::ToGUIBase, UNREACHABLEC.
bool mutaborGUI::GUIRouteBase::Replace(mutabor::Box &oldbox, mutabor::Box &newbox)
replace an existing box
References mutaborGUI::BoxData::GetShapes, Remove, Replace, shapes, mutaborGUI::ToGUIBase.
bool mutaborGUI::GUIRouteBase::Remove(mutabor::OutputDevice &out)
remove an existing output device
References DEBUGLOG, GetRoute, mutaborGUI::GUIOutputDeviceBase::GetShape, intrusive_ptr_get_refcount, mutASSERT, mutaborGUI::MutDeviceShape< T >::Remove, shapes, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::disconnect, mutaborGUI::GUIfiedRoute< T >::Remove, Replace.
bool mutaborGUI::GUIRouteBase::Remove(mutabor::InputDevice &in)
remove an existing input device
References DEBUGLOG, GetRoute, mutaborGUI::GUIInputDeviceBase::GetShape, intrusive_ptr_get_refcount, mutASSERT, mutaborGUI::MutDeviceShape< T >::Remove, shapes, mutaborGUI::ToGUIBase.
bool mutaborGUI::GUIRouteBase::Remove(mutabor::Box &b)
remov an existing box
References DEBUGLOG, GetRoute, mutaborGUI::BoxData::GetShapes, intrusive_ptr_get_refcount, mutabor::MIN_BOX, mutASSERT, shapes, mutaborGUI::ToGUIBase.
const MutBoxChannelShapeList& mutaborGUI::GUIRouteBase::GetBoxChannelShapes() const
References shapes.
Referenced by mutaborGUI::MakeTopLevelsRoutes.
void mutaborGUI::GUIRouteBase::Add(MutBoxChannelShape *shape)
References shapes, UNREACHABLEC.
bool mutaborGUI::GUIRouteBase::Remove(MutBoxChannelShape *shape)
References mutASSERT, shapes, UNREACHABLEC.
virtual mutabor::RouteClass* mutaborGUI::GUIRouteBase::GetRoute()=0
Referenced by Add, Remove, Replace.
void mutaborGUI::GUIRouteBase::Destroy()
References DEBUGLOG, mutabor::disconnect, intrusive_ptr_get_refcount.
MutBoxChannelShape * mutaborGUI::GUIRouteBase::GetShape(wxWindow *parent)
return the shape that corresponds to the current window
To use common naming the window is named parent though it is actually the grandparent of the returned channel shape parent wxWindow* window which shall contain the searched shape shape displaying this on window parent.
References shapes.
Referenced by mutaborGUI::GUIOutputDeviceBase::Add, mutaborGUI::GUIInputDeviceBase::Add, mutaborGUI::Check, mutaborGUI::GUIOutputDeviceBase::Remove, mutaborGUI::GUIInputDeviceBase::Remove, mutaborGUI::GUIOutputDeviceBase::Replace, mutaborGUI::GUIInputDeviceBase::Replace.
void mutaborGUI::GUIRouteBase::runtime_error(int type, const mutString &message, va_list &args)
References mutaborGUI::CM_PRINT_ERROR, mutabor::hidden::internal_error, mutabor::to_string.
Referenced by mutaborGUI::GUIfiedRoute< T >::runtime_error.
static GUIRouteBase* mutaborGUI::GUIRouteBase::GetGUIRoute(mutabor::Route &r)