mutabor::CommonTypedDeviceAPI
typedef T mutabor::CommonTypedDeviceAPI< T, P, L >::thistype
typedef P mutabor::CommonTypedDeviceAPI< T, P, L >::DevicePtr
typedef L mutabor::CommonTypedDeviceAPI< T, P, L >::listtype
mutabor::CommonTypedDeviceAPI< T, P, L >::REFPTR_INTERFACE
CommonTypedDeviceAPI< T, P, L >::listtype mutabor::CommonTypedDeviceAPI< T, P, L >::deviceList
Referenced by mutabor::CommonTypedDeviceAPI< InputDeviceClass >::ClearDeviceList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::FindInDeviceList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::IsInDeviceList.
mutabor::CommonTypedDeviceAPI< T, P, L >::CommonTypedDeviceAPI()
mutabor::CommonTypedDeviceAPI< T, P, L >::CommonTypedDeviceAPI(const std::string &name, int id=-1)
mutabor::CommonTypedDeviceAPI< T, P, L >::~CommonTypedDeviceAPI()
References debug_destruct_class, DEBUGLOG, TRACEC, UNREACHABLEC.
void mutabor::CommonTypedDeviceAPI< T, P, L >::Destroy()
Destroy the current object.
This function is called when an object shall be deleted. It clears up all references to itself so that it will be deleted if it is not needed anymore.This functions detatches the device from all routes and calls DoDestroy() afterwards. Finally the Device is going to removed from the device list.
References debug_destroy_class, mutaborGUI::IsOpen, TRACEC.
Referenced by CommonMidiInputTest::tearDown.
void mutabor::CommonTypedDeviceAPI< T, P, L >::DisconnectFromAll()
Disconnect the device from all pairings with routes GUI data or something else.
This function should be extended in subclasses so that after calling it only temporary pointers (variables in functions or temporary objects) point to the object.
References mutabor::disconnect, TRACEC.
void mutabor::CommonTypedDeviceAPI< T, P, L >::Add(Route &route)
add a route
References DEBUGLOG, mutASSERT, TRACEC.
Referenced by mutabor::CommonTypedDeviceAPI< T, P, L >::Replace.
bool mutabor::CommonTypedDeviceAPI< T, P, L >::Replace(Route &oldroute, Route &newroute)
replace a route
References mutabor::CommonTypedDeviceAPI< T, P, L >::Add, DEBUGLOG, mutASSERT, mutabor::CommonTypedDeviceAPI< T, P, L >::Remove.
bool mutabor::CommonTypedDeviceAPI< T, P, L >::Remove(Route &route)
remove a route
References DEBUGLOG, intrusive_ptr_get_refcount, mutASSERT.
Referenced by mutabor::CommonTypedDeviceAPI< T, P, L >::Replace.
bool mutabor::CommonTypedDeviceAPI< T, P, L >::MoveRoutes(DevicePtr &newclass)
Move routes to another device.
References mutaborGUI::IsOpen, mutabor::reconnect, TRACEC, UNREACHABLEC.
size_t mutabor::CommonTypedDeviceAPI< T, P, L >::nRoutes()
const routeListType& mutabor::CommonTypedDeviceAPI< T, P, L >::GetRoutes() const
Referenced by mutaborGUI::Check.
routeListType& mutabor::CommonTypedDeviceAPI< T, P, L >::GetRoutes()
mutabor::CommonTypedDeviceAPI< T, P, L >::operator const thistype &() const
mutabor::CommonTypedDeviceAPI< T, P, L >::operator thistype &()
thistype* mutabor::CommonTypedDeviceAPI< T, P, L >::thisptr()
const thistype* mutabor::CommonTypedDeviceAPI< T, P, L >::thisptr() const
int mutabor::CommonTypedDeviceAPI< T, P, L >::MoveInList(int count)
Move the device in the device list.
count Number of places the device should be moved up. Negative values indicate downwards direction. new position in the device list.
mutabor::CommonTypedDeviceAPI< T, P, L >::operator std::string() const
References intrusive_ptr_get_refcount, mutabor::str.
static const listtype& mutabor::CommonTypedDeviceAPI< T, P, L >::GetDeviceList()
void mutabor::CommonTypedDeviceAPI< T, P, L >::InitializeIds()
Initialize the internal device identifiers.
This function sets the internal device ids of all output devices, starting from 0 and incrementing by 1
References TRACET.
CommonTypedDeviceAPI< T, P, L >::DevicePtr mutabor::CommonTypedDeviceAPI< T, P, L >::GetDevice(int id, devidtype kind)
Scan the list of input devices for a given id.
id (int) id to scan for (OutputDevice) pointer to the input device with the given id if found, NULL else.
References UNREACHABLECT.
static void mutabor::CommonTypedDeviceAPI< T, P, L >::ClearDeviceList()
void mutabor::CommonTypedDeviceAPI< T, P, L >::AppendToDeviceList(DevicePtr dev)
References UNREACHABLECT.
Referenced by mutabor::CommonTypedDeviceAPI< InputDeviceClass >::CommonTypedDeviceAPI.
void mutabor::CommonTypedDeviceAPI< T, P, L >::RemoveFromDeviceList(DevicePtr dev)
References UNREACHABLECT.
static listtype::iterator mutabor::CommonTypedDeviceAPI< T, P, L >::FindInDeviceList(DevicePtr dev)
Referenced by mutabor::CommonTypedDeviceAPI< InputDeviceClass >::IsInDeviceList.
static bool mutabor::CommonTypedDeviceAPI< T, P, L >::IsInDeviceList(const DevicePtr dev)
void mutabor::CommonTypedDeviceAPI< T, P, L >::TruncateDeviceList(DevicePtr dev)
References STUB.