GIS_Head.cpp
muT
Referenced by mutabor::OutputMidiPort::Load, mutabor::InputMidiPort::Load, MutTextBox::NewText, mutaborGUI::MutFrame::RaiseLogic, mutabor::OutputMidiPort::SetDevId, mutabor::InputMidiPort::SetDevId, wxwidgets_gettext.
ZIFFER
Referenced by GetTheSpeedFactor.
TAG
Referenced by GisReadArtHead::Read.
TAGEND
Referenced by GisReadArtHead::Read.
NOTE1
Referenced by CmpNote.
NOTE2
Referenced by CmpNote.
NOTE
Referenced by ChordNote::SetNoteOn.
WTAG
Referenced by GisWriteHead::ProceedGis.
WTAGEND
Referenced by GisWriteHead::ProceedGis.
char ArticulationHold[5][5]
Referenced by GisReadArtHead::Read.
char ArticulationOff[5][5]
double GetReal(GisToken *token)
References GetGisType, GTParaInt, GTParaReal.
Referenced by GisReadArtHead::Read.
char GetMidiInstrument(GisToken *token)
References DEBUGLOG2, GetGisType, GTParaStr, mutString, mutT.
Referenced by GisReadArtHead::Read.
mutint64 GetTheSpeedFactor(GisToken *token)
This function returns the speed factor that must be multiplied to the duration value in order to get a delta timestamp in μs.
token Token to be parsed in the form numerator/denominator = bpm. fraction in μs for 1/1 duration.
References DEBUGLOG2, GetGisType, GTParaStr, mutString, mutT, ZIFFER.
Referenced by GisReadArtHead::Read.
frac GisReadHeadOn(GisReadHead **Head, frac dTime, GisReadProceed *proceed)
References GisReadHead::Boss, GisReadHead::Cursor, GisReadHead::CursorNext, GisReadHead::CutOut, h, GisReadHead::Next, GisReadHead::nSub, GisReadHead::Read, GisReadHead::Time.
TagList * Copy(TagList *list)
References TagListData::Data, TagListData::Next, TagListData::Tag.
Referenced by GisReadArtHead::GisReadArtHead, mutaborGUI::MutEditFile::OnEditCopy.
void Erase(TagList *list)
References TagListData::Next.
Referenced by GisReadArtHead::~GisReadArtHead, GisWriteHead::~GisWriteHead.
TagList* RemoveTag(TagList **list)
References TagListData::Next.
Referenced by AddTag, EndTag.
TagList* AddTag(TagList **list, GisTag *tag)
References GTTag, TagListData::Next, RemoveTag, TagListData::Tag, GisTag::Type.
Referenced by GisWriteHead::ProceedGis, GisReadArtHead::Read.
TagList* EndTag(TagList **list, GisTagEnd *tagEnd)
References GisTagEnd::Begin, GTTag, if, TagListData::Next, RemoveTag, TagListData::Tag, GisTag::Type.
Referenced by GisWriteHead::ProceedGis, GisReadArtHead::Read.
void GisReadArtDummy(GisReadArtHead *, char)
frac GisReadArtHeadOn(GisReadArtHead **Head, frac dTime, GisReadArtProceed *proceed)
References GisReadHead::Boss, GisReadHead::Cursor, GisReadHead::CursorNext, GisReadHead::CutOut, DEBUGLOG2, h, GisReadHead::Next, GisReadHead::nSub, GisReadArtHead::Read, GisReadHead::Time, GisReadArtHead::Time2, TRACE, GisReadHead::Turn.
Referenced by main.
char StrCmp(const char *s1, const char *s2)
Referenced by CmpNote.
int CmpNote(GisToken *note1, GisToken *note2)
References GTNote, NOTE1, NOTE2, StrCmp, GisToken::Type.
Referenced by ChordNote::SetNoteOff.
GisWriteHead * GetMatchingHeader(GisWriteHead **head, const mutString id)
References GisReadHead::Boss, h, GisWriteHead::Id, GisWriteHead::InsertAfter, mutStrCmp, GisWriteHead::Next, GisWriteHead::Prev.
Referenced by GisWriteHeadGis.
int GisWriteHeadGis(GisWriteHead **head, mutString id, GisToken *token, char turn)
References GetMatchingHeader, GisWriteHead::ProceedGis.
Referenced by mutabor::OutputGis::do_Gis.
void CloseAllSubs(GisWriteHead *head)
References GisReadHead::Boss, GisWriteHead::CloseSubs, GisWriteHead::CommaAtEnd, GisWriteHead::Cursor, GisWriteHead::CutOut, GisWriteHead::Data, GetGisType, GTSegment, h, mutT, GisReadHead::Next, GisWriteHead::Next, GisWriteHead::nSub, GisWriteHead::RemoveComma.
Referenced by mutabor::OutputGis::Close.