harmonie.c
struct harmonie* list_of_harmonien
Wurzel der Harmonien.
Referenced by check_ausloeser, mutabor_programm_einlesen.
struct harmonie* get_harmonie(char *name, struct harmonie *liste)
Sucht eine Harmonie in einer Harmonieliste.
name Name der gesuchten Harmonie liste Liste der Harmodien, in der gesucht wird NULL falls Harmonie nicht in liste Harmonie sonst.
References get_harmonie, harmonie::name, harmonie::next.
Referenced by check_ausloeser, expand_pattern, get_harmonie.
void drucke_harmonie(struct harmonie *this_)
Gibt eine Harmonie auf der Standardausgabe aus.
this_ Harmonie
References harmonie::bezugstaste, harmonie::name, taste::next, taste::stern, taste::taste, harmonie::tastenliste.
Referenced by mutabor_programm_einlesen.
void get_new_harmonie(char *name, int bezugstaste)
Fügt eine Harmonie ans Ende von list_of_harmonien an.
Dabei wird die letzte eingelesene Tastenliste (tmp_tastenliste) verwendet. name Name der Harmonie bezugstaste Bezugstaste für die Harmonie (Schlüssel-C = 60) Es wird immer die gesamte Liste durchsucht. Effektivität?
References harmonie::bezugstaste, fatal_error, mutabor_debug_level, name, harmonie::next, harmonie::tastenliste, tmp_tastenliste, xmalloc.
Referenced by switch, yyparse.
void get_harmoniebezeichner(int vor_taste, char *name, int nach_taste)
Sichert die Daten eines Harmoniebezeichners im globalen Zwischenspeicher.
vor_taste Tiefste Taste beim Anschlagen der Harmonie name Name der Harmonie(-form) nach_taste Höchste Teste beim Anschlagen der Harmonie
References name, tmp_nach_taste, tmp_name, tmp_vor_taste.
Referenced by switch, yyparse.
PATTERNN* expand_pattern(char *harmonie_name)
Erzeugt eine Suchmaske für die Suche nach Harmonien.
harmonie_name Name der Harmonie, für die die Maske erzeugt werden soll. Ganzzahlenfeld, das die Harmonie-Suchmaske symbolisiert
References fatal_error, for, get_harmonie, MAX_BREITE, taste::stern, taste::taste, harmonie::tastenliste, PTRN::tonigkeit, xmalloc.
Referenced by insert_in_globale_liste, insert_in_lokale_liste.