GisReadHead
GisReadHead* GisReadHead::Next
Referenced by GisWriteHead::AddTime, ChordNote::ChordNote, CloseAllSubs, GisWriteHead::CloseSubs, ChordNote::CountOnTime, CutOut, GisWriteHead::CutOut, GisReadArtHeadOn, GisReadHead, GisReadHeadOn, GisWriteHead::InsertAfter, InsertInfrontOf, mutabor::InputGis::ReadOn, ChordNote::SetNoteOff, ~GisReadHead.
GisReadHead ** GisReadHead::PrevPtr
Referenced by CutOut, GisReadHead, InsertInfrontOf, mutabor::InputGis::Stop.
GisReadHead * GisReadHead::Prev
Referenced by CutOut, GisWriteHead::CutOut, GisReadHead, GisWriteHead::InsertAfter, InsertInfrontOf, main.
GisReadHead* GisReadHead::Boss
Referenced by ChordNote::ChordNote, CloseAllSubs, GetMatchingHeader, GisReadArtHeadOn, GisReadHead, GisReadHeadOn, ChordNote::MutNoteOff, ChordNote::MutNoteOn, mutabor::InputGis::ReadOn, ChordNote::SetNoteOff, ChordNote::SetNoteOn.
int GisReadHead::nSub
Referenced by GisWriteHead::CloseSubs, CreateSegmentSubs, CreateSequenzSubs, GisReadArtHeadOn, GisReadHead, GisReadHeadOn, mutabor::InputGis::ReadOn.
GisToken* GisReadHead::Cursor
Referenced by ChordNote::AddGis, ChordNote::CheckCloseTie, ChordNote::ChordNote, GisWriteHead::CloseCurrentToken, GisWriteHead::CloseSubs, CreateSegmentSubs, CreateSequenzSubs, CursorNext, GisReadArtHeadOn, GisReadHead, GisReadHeadOn, ChordNote::MutNoteOff, ChordNote::MutNoteOn, mutabor::InputGis::Proceed, GisWriteHead::ProceedGis, mutabor::InputGis::ProceedRoute, Read, GisReadArtHead::Read, mutabor::InputGis::ReadOn, GisWriteHead::ReadyForBoss, GisWriteHead::RemoveComma, ChordNote::SetNoteOff, ChordNote::SetNoteOn, Write, GisWriteHead::WriteChord.
frac GisReadHead::Time
Referenced by GisReadArtHeadOn, GisReadHead, GisReadHeadOn, Read, GisReadArtHead::Read, mutabor::InputGis::ReadOn.
mutString GisReadHead::Id
Referenced by CreateSegmentSubs, CreateSequenzSubs, GisReadHead, mutabor::InputGis::Proceed, GisWriteHead::ProceedGis, mutabor::InputGis::ProceedRoute, GisReadArtHead::Read, ~GisReadHead.
char GisReadHead::Turn
Referenced by CursorNext, GisReadArtHead::GisReadArtHead, GisReadArtHeadOn, GisReadArtHead::Read, mutabor::InputGis::ReadOn.
bool GisReadHead::SingleToken
Referenced by CursorNext, GisReadHead, GisWriteHead::ReadyForBoss.
GisReadHead::GisReadHead(GisReadHead *boss, GisToken *cursor, const mutString &id, bool singleToken=false)
References Boss, Cursor, DEBUGLOG, Id, InsertInfrontOf, mutCopyString, Next, nSub, Prev, PrevPtr, SingleToken, Time.
Referenced by Build.
virtual GisReadHead::~GisReadHead()
References Id, mutFreeString, Next.
virtual GisReadHead* GisReadHead::Build(GisReadHead *boss, GisToken *cursor, const mutString &id, bool singleToken=false)
References GisReadHead.
Referenced by CreateSegmentSubs, CreateSequenzSubs.
GisReadHead * GisReadHead::InsertInfrontOf(GisReadHead *position)
References DEBUGLOG, mutASSERT, Next, Prev, PrevPtr.
Referenced by GisReadHead.
GisReadHead * GisReadHead::CutOut()
References mutASSERT, Next, Prev, PrevPtr.
Referenced by GisReadArtHeadOn, GisReadHeadOn, mutabor::InputGis::ReadOn.
GisToken* GisReadHead::CursorNext()
References Cursor, GTComma, GisToken::Next, SingleToken, Turn, GisToken::Type.
Referenced by GisReadArtHeadOn, GisReadHeadOn, mutabor::InputGis::ReadOn.
void GisReadHead::CreateSegmentSubs()
References Build, GisSegment::Contents, Cursor, DEBUGLOG, GTComma, Id, mutString, mutT, GisToken::Next, nSub, GisToken::Type.
Referenced by Read, GisReadArtHead::Read.
void GisReadHead::CreateSequenzSubs()
References Build, GisSegment::Contents, Cursor, Id, mutString, mutT, nSub.
Referenced by Read, GisReadArtHead::Read.
void GisReadHead::Read()
References CreateSegmentSubs, CreateSequenzSubs, Cursor, DEBUGLOG, GTComma, GTNote, GTNull, GTParaInt, GTParaReal, GTParaStr, GTSegment, GTSequenz, GTTag, GTTagBegin, GTTagEnd, GTUnknown, Time, GisToken::Type.
Referenced by GisReadHeadOn.