mutaborGUI::xmltree
typedef wxXmlNode mutaborGUI::xmltree::node_type
typedef wxXmlProperty mutaborGUI::xmltree::prop_type
typedef wxXmlDocument mutaborGUI::xmltree::doc
configuration object
std::stack<state> mutaborGUI::xmltree::states
Referenced by Load, toLeaf, toNextLeaf, toParent, xmltree.
bool mutaborGUI::xmltree::create_tree
Referenced by DeleteGroup, HasGroup, SetPath, toLeaf.
node_type* mutaborGUI::xmltree::current_node
Referenced by DeleteEntry, DeleteGroup, GetProperty, GetwxPath, HasGroup, Load, Read, SetPath, SetProperty, toFirstLeaf, toLeaf, toNextLeaf, toParent, Write.
mutaborGUI::xmltree::xmltree(wxString rootname, bool create=true)
References states, toLeaf.
virtual mutaborGUI::xmltree::~xmltree()
bool mutaborGUI::xmltree::Load(const wxString &filename, const wxString &encoding=wxT("UTF-8"), int flags=wxXMLDOC_NONE)
References current_node, states, toLeaf.
Referenced by mutaborGUI::MutRouteWnd::CmRouteLoad.
virtual long mutaborGUI::xmltree::Read(const std::string &key, long defval)
Reads a long integer value.
key (std::string&) Name of the desired leaf in the tree defval (long) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
Referenced by Read.
virtual double mutaborGUI::xmltree::Read(const std::string &key, double defval)
Reads a double value.
key (std::string&) Name of the desired leaf in the tree defval (double) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
References Read.
virtual int mutaborGUI::xmltree::Read(const std::string &key, int defval)
Reads an integer value.
key (std::string&) Name of the desired leaf in the tree defval (int) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
References Read.
virtual bool mutaborGUI::xmltree::Read(const std::string &key, bool defval)
Reads a boolean value.
key (std::string&) Name of the desired leaf in the tree defval (bool) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
References Read.
long mutaborGUI::xmltree::Read(const wxString &key, long defval)
References GetProperty.
double mutaborGUI::xmltree::Read(const wxString &key, double defval)
References GetProperty.
int mutaborGUI::xmltree::Read(const wxString &key, int defval)
References GetProperty.
bool mutaborGUI::xmltree::Read(const wxString &key, bool defval)
References GetProperty, mutASSERT.
virtual std::string mutaborGUI::xmltree::Read(const std::string &key, const std::string &defval)
Reads a string value.
key (std::string&) Name of the desired leaf in the tree defval (std::string&) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
References Read.
wxString mutaborGUI::xmltree::Read(const wxString &key, const wxString &defval)
References current_node, GetProperty, NormalizeName.
virtual void mutaborGUI::xmltree::Write(const std::string &key, long value)
Writes a long integer value.
key (std::string&) Name of the desired leaf in the tree value (long) value, to be written
Referenced by toLeaf, Write.
virtual void mutaborGUI::xmltree::Write(const std::string &key, double value)
Writes a double value.
key (std::string&) Name of the desired leaf in the tree value (double) value, to be written
References Write.
virtual void mutaborGUI::xmltree::Write(const std::string &key, int value)
Writes an integer value.
key (std::string&) Name of the desired leaf in the tree value (int) value, to be written
References Write.
virtual void mutaborGUI::xmltree::Write(const std::string &key, bool value)
Writes a boolean value.
key (std::string&) Name of the desired leaf in the tree value (bool) value, to be written
References Write.
void mutaborGUI::xmltree::Write(const wxString &key, long value)
References GetProperty.
void mutaborGUI::xmltree::Write(const wxString &key, double value)
References GetProperty.
void mutaborGUI::xmltree::Write(const wxString &key, int value)
References GetProperty.
void mutaborGUI::xmltree::Write(const wxString &key, bool value)
References GetProperty.
virtual void mutaborGUI::xmltree::Write(const std::string &key, const std::string &value)
Writes a string value.
key (std::string&) Name of the desired leaf in the tree value (std::string&) value, to be written
References Write.
void mutaborGUI::xmltree::Write(const wxString &key, const wxString &value)
References current_node, GetProperty, NormalizeName.
virtual bool mutaborGUI::xmltree::HasGroup(const std::string &subdir) const
Checks if the tree has a branch with the given name.
subdir (std::string&) subdirectory to check for. true if the current node has a leaf with the given name which is a node itself.
Referenced by HasGroup.
virtual bool mutaborGUI::xmltree::HasGroup(const wxString &subdir) const
References HasGroup.
virtual bool mutaborGUI::xmltree::HasGroup(const std::string &subdir)
References HasGroup.
bool mutaborGUI::xmltree::HasGroup(const wxString &subdir)
References create_tree, current_node, NormalizeName, SetPath.
virtual void mutaborGUI::xmltree::toLeaf(const std::string &subdir)
Changes the current node downwards.
this function can be used to navigate towards the leaves in the tree. The argument can be considered like a subdirectory in a file system. subdir (std::string&) subdirectory to be written to.
Referenced by Load, toFirstLeaf, toLeaf, xmltree.
virtual void mutaborGUI::xmltree::toLeaf(const std::string &name, int id)
Changes the current node downwards.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. if the id is negative, it will create a new item. subdir (std::string&) name of the entity to be written to. id (int) id of the current object
References toLeaf.
void mutaborGUI::xmltree::toLeaf(const wxString &subdir)
References _, current_node, DEBUGLOG, GetPath, mutASSERT, mutaborGUI::xmltree::state::node, NormalizeName, SetPath, states, UNREACHABLEC.
void mutaborGUI::xmltree::toLeaf(const wxString &name, int id)
References create_tree, current_node, DEBUGLOG, GetPath, NormalizeName, SetPath, states, toLeaf, Write.
virtual int mutaborGUI::xmltree::toFirstLeaf(const std::string &name)
Changes the current node downdwards to the first leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (std::string&) name of the entity to be read from. (int) id of the selected item toNextLeaf
Referenced by toFirstLeaf.
virtual int mutaborGUI::xmltree::toFirstLeaf(const wxString &name)
References toFirstLeaf.
virtual int mutaborGUI::xmltree::toFirstLeaf(const std::string &name, std::string &id)
Changes the current node downdwards to the first leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (std::string&) name of the entity to be read from. id (std::string&) reference to a String where the id of the leaf will be stored (int) id of the selected item toNextLeaf
References toFirstLeaf.
int mutaborGUI::xmltree::toFirstLeaf(const wxString &name, wxString &id)
References current_node, DEBUGLOG, NormalizeName, toLeaf.
virtual int mutaborGUI::xmltree::toNextLeaf(const std::string &name)
Changes the current node downdwards to the next leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (std::string&) name of the entity to be read from. (int) id of the selected item toFirstLeaf
Referenced by toNextLeaf.
virtual int mutaborGUI::xmltree::toNextLeaf(const wxString &name)
References toNextLeaf.
virtual int mutaborGUI::xmltree::toNextLeaf(const std::string &name, std::string &id)
Changes the current node downdwards to the next leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (std::string&) name of the entity to be read from. id (std::string&) reference to a String where the id of the leaf will be stored (int) id of the selected item toFirstLeaf
References toNextLeaf.
int mutaborGUI::xmltree::toNextLeaf(const wxString &name, wxString &id)
References current_node, mutaborGUI::xmltree::state::node, NormalizeName, states.
void mutaborGUI::xmltree::toParent(unsigned int count=1)
This function jumps up in the tree (i.e. towards the root).
count (int) number of nodes to go upward. Default: 1.
References current_node, DEBUGLOG, mutASSERT, mutaborGUI::xmltree::state::node, states, UNREACHABLEC.
virtual std::string mutaborGUI::xmltree::GetPath()
Return a string representation of the position in the current tree.
This function can be used to store the current position in the tree. std::string String representation of the current path. The concrete representation is implementation dependent and can vary for different tree types.
References GetwxPath.
Referenced by toLeaf.
wxString mutaborGUI::xmltree::GetwxPath()
References current_node.
Referenced by GetPath.
virtual void mutaborGUI::xmltree::SetPath(const std::string &path)
Set the current pointer in the tree.
This function can be used to store the current position in the tree. path (std::string) String representation of the new path as returned by GetPath(). The concrete representation is implementation dependent and can vary for different tree types.
Referenced by DeleteEntry, DeleteGroup, HasGroup, toLeaf.
void mutaborGUI::xmltree::SetPath(const wxString &path)
References create_tree, current_node.
virtual void mutaborGUI::xmltree::DeleteEntry(const std::string &path)
Delete an entry.
entry path to the entry that shall be deleted
void mutaborGUI::xmltree::DeleteEntry(const wxString &path)
References current_node, SetPath.
virtual void mutaborGUI::xmltree::DeleteGroup(const std::string &path)
Delete an entire group with all childs.
group path to the entry that shall be deleted
void mutaborGUI::xmltree::DeleteGroup(const wxString &path)
References create_tree, current_node, SetPath.
wxXmlProperty * mutaborGUI::xmltree::GetProperty(wxString name, bool create)
Get an XML attribute name of the node.
name name of the property. create shall it be created? a pointer to the corresponding object. as we normalize the name anyway, we copy the object during the call.
References current_node, NormalizeName.
Referenced by Read, Write.
wxXmlProperty * mutaborGUI::xmltree::SetProperty(wxString name, const wxString &value)
Set an XML attribute of the node.
name name of the property. value new value a pointer to the corresponding object. as we normalize the name anyway, we copy the object during the call.
References current_node, NormalizeName.
void mutaborGUI::xmltree::NormalizeName(wxString &name)
Referenced by GetProperty, HasGroup, Read, SetProperty, toFirstLeaf, toLeaf, toNextLeaf, Write.