midicmnOutputDevice
typedef mutabor::CommonMidiOutput<mutabor::DebugMidiOutputProvider, mutabor::OutputDeviceClass> midicmnOutputDevice::base
midicmnOutputDevice::midicmnOutputDevice(std::string name, int id=-1, int bendingRange=2)
midicmnOutputDevice::~midicmnOutputDevice()
mutabor::DebugMidiOutputProvider& midicmnOutputDevice::getOut()
References mutabor::CommonMidiOutput< mutabor::DebugMidiOutputProvider, mutabor::OutputDeviceClass >::Out.
Referenced by CommonMidiInputTest::testGlobalPanic, CommonMidiOutputTest::testNoteOnOff, CommonMidiInputTest::testPanic.
void midicmnOutputDevice::Save(mutabor::tree_storage &)
Save current device settings in a tree storage.
config (tree_storage) storage class, where the data will be saved.
void midicmnOutputDevice::Save(mutabor::tree_storage &, const mutabor::RouteClass *)
Save route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route) Route whos data shall be saved.
void midicmnOutputDevice::Load(mutabor::tree_storage &)
Load current device settings from a tree storage.
config (tree_storage) storage class, where the data will be loaded from.
void midicmnOutputDevice::Load(mutabor::tree_storage &, mutabor::RouteClass *)
Load route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route) Route whos data shall be loaded.
void midicmnOutputDevice::do_AddTime(mutabor::frac time)
int midicmnOutputDevice::GetMaxChannel() const
int midicmnOutputDevice::GetMinChannel() const
bool midicmnOutputDevice::Check(std::string s, int line=-1, std::string filename=(__FILE__))
References mutabor::DebugMidiOutputProvider::ClearData, DEBUGLOG, mutabor::CommonMidiOutput< mutabor::DebugMidiOutputProvider, mutabor::OutputDeviceClass >::Out.
Referenced by InputMidiFileTest::testAfterTouch, InputMidiFileTest::testAllControllerOff, InputMidiFileTest::testBankSelect, InputMidiFileTest::testBatchPlay1, InputMidiFileTest::testBoxMidiIn, InputMidiFileTest::testBug019010, InputMidiFileTest::testBug019010_2, InputMidiFileTest::testControllerPlay, CommonMidiInputTest::testGlobalPanic, CommonMidiOutputTest::testMoreNotesThanChannels, CommonMidiOutputTest::testNoteOnOff, CommonMidiInputTest::testPanic, InputMidiFileTest::testRpnNrpn, InputMidiFileTest::testSysEx.