case_liste.c
struct case_liste* tmp_umstimmungs_case_liste
Referenced by get_umstimmung_umstimm_case_parameter, get_umstimmung_umstimm_case_zahl.
void get_umstimmungs_case_zahl_element(int konstante)
Fügt einen Fall ans Ende von tmp_umstimmungs_case_liste an.
Der Aufruf erhält die letzte eingelesene Argumentliste. konstante Bezeichnung der Konstante für Fall, der angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References case_liste::case_aktion, case_liste::case_label, get_last_aktions_liste, case_liste::is_default, case_liste::next, xmalloc.
Referenced by switch, yyparse.
void get_umstimmungs_case_default_element(void)
Fügt einen Standardfall ans Ende von tmp_umstimmungs_case_liste an.
Der Aufruf erhält die letzte eingelesene Argumentliste. Es wird immer die gesamte Liste durchsucht. Effektivität? Noch zu erledigenTypkonvertierung von doube nach int prüfen.
References case_liste::case_aktion, case_liste::case_label, get_last_aktions_liste, case_liste::is_default, case_liste::next, xmalloc.
Referenced by switch, yyparse.
void init_umstimmungs_case_liste(void)
Setzt tmp_umstimmungs_case_liste auf NULL.
Die Liste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_umstimmung_umstimm_case_zahl(int selector)
Baut tmp_umstimmung zu einer Zahlgesteuerten Case-Umstimmung aus.
Dabei wird die letzte eingelesene Umstimmungs-Case-Liste verwendet. Falls darin ein unbekannter Parameter gefunden wird, wird ein fataler Fehler ausgelöst. selector Wert für die Case-Anweisung
References aktion_aufruf, aktions_liste::aktion_aufruf, argument_liste::argument, argument::argument_typ, fatal_error, name, case_liste::next, argument_liste::next, aktions_liste::next, parameter, argument::parameter, parameter_nummer, tmp_umstimmung, tmp_umstimmungs_case_liste, argument::u, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case, zahl.
Referenced by yyparse.
void get_umstimmung_umstimm_case_parameter(char *selector)
Baut tmp_umstimmung zu einer Parametergesteuerten Case-Umstimmung aus.
Dabei wird die letzte eingelesene Umstimmungs-Case-Liste verwendet. Falls darin ein unbekannter Parameter gefunden wird, wird ein fataler Fehler ausgelöst. Dies geschieht auch, falls selector nicht definiert ist. selector Parameter für die Case-Anweisung
References aktion_aufruf, aktions_liste::aktion_aufruf, argument_liste::argument, argument::argument_typ, fatal_error, name, umstimmung::name, case_liste::next, argument_liste::next, aktions_liste::next, parameter, argument::parameter, parameter_nummer, tmp_umstimmung, tmp_umstimmungs_case_liste, argument::u, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case.
Referenced by yyparse.
int case_label_enthalten_in_case_liste(double case_label, struct case_liste *lauf)
Sucht ein Case-Label in einer entsprechenden Liste.
case_label Zu suchendes Label lauf Liste, in der gesucht wird 1 Label wurde gefunden 0 Label wurde nicht gefunden
References case_label_enthalten_in_case_liste, argument_liste::next.
Referenced by case_label_enthalten_in_case_liste, check_konsistenz, check_umstimmungs_konsistenz.
struct case_element* expand_case_liste(struct case_liste *the_liste, struct interpreter_parameter_liste *aktuelle_parameter)
Sortiert die Default-Zweige von Case-Listen ans Ende und expandiert die Paramater der einzelnen Aktionen.
the_liste Case-Liste, die bearbeitet werden soll. aktuelle_parameter Aktuelle Parameter, die ersetzt werden können. Noch zu erledigenVereinigen beider Schleifen duch hinzufügen einer neuen temporären default-ende-liste.
References case_element::case_aktion, case_element::case_wert, expand_aktions_liste, case_liste::is_default, case_element::is_default, case_liste::next, case_element::next, xmalloc.
Referenced by expandiere_umstimmung.