GisToken
GisToken* GisToken::Next
Referenced by BeginRange, CopyPara, GisReadHead::CreateSegmentSubs, GisReadHead::CursorNext, EndRange, EndSegment, EndSequenz, GisTag::GetPara, GisTag::GetParaType, GisToken, mutabor::MutaborTag, Note, operator std::string, GisWriteHead::ReadyForBoss, GisWriteHead::RemoveComma, TagParaInt, TagParaReal, TagParaStr, UnRavel, ~GisToken.
std::string GisToken::Sep
Referenced by ChordNote::AddGis, BeginRange, Copy, GisTag::Copy, GisTagBegin::Copy, GisParaInt::Copy, GisParaReal::Copy, GisParaStr::Copy, EndParameter, GisToken, ChordNote::MutNoteOn, mutabor::InputGis::Proceed, GisWriteHead::ProceedGis, ToString.
GisToken::GisToken(const std::string &sep="", GisToken *next=0)
References CHECKDUP, DEBUGLOG, Next, Sep.
Referenced by Copy.
virtual GisToken::~GisToken()
References Next.
virtual GisType GisToken::Type() const
References GTUnknown.
Referenced by CmpNote, GisReadHead::CreateSegmentSubs, GisReadHead::CursorNext, GetGisType, GisTag::GetParaType, mutabor::MutaborTag, GisWriteHead::ProceedGis, GisWriteHead::ReadyForBoss.
virtual GisToken* GisToken::Copy()
References GisToken, Sep.
Referenced by CopyPara, GisWriteHead::ProceedGis.
virtual GisToken::operator std::string() const
References Next, ToString.
virtual std::string GisToken::ToString() const
References Sep.
Referenced by operator std::string, GisSequenz::ToString, GisSegment::ToString, GisTag::ToString, GisTagEnd::ToString, GisNote::ToString, GisParaInt::ToString, GisParaReal::ToString, GisParaStr::ToString, GisComma::ToString.