mutaborGUI::BoxDlg
wxChoice* mutaborGUI::BoxDlg::boxTypeChoice
NoBoxSettings* mutaborGUI::BoxDlg::noBoxPanel
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON
MutaborBoxSettings* mutaborGUI::BoxDlg::mutaborBoxPanel
GuidoFileBoxSettings* mutaborGUI::BoxDlg::guidoFileBoxPanel
mutaborGUI::BoxDlg::BoxDlg()
mutaborGUI::BoxDlg::BoxDlg(wxWindow *parent)
void mutaborGUI::BoxDlg::InitializeBoxTypes()
References _, mutASSERT.
wxWindow* mutaborGUI::BoxDlg::GetRouteWindow()
Referenced by mutaborGUI::MutBoxShape::readDialog, mutaborGUI::MutBoxShape::ShowBoxDialog.
wxSize mutaborGUI::BoxDlg::DoGetBestSize() const
int mutaborGUI::BoxDlg::GetBoxType() const
References mutabor::Box0, mutabor::GmnBox, mutabor::NoBox, UNREACHABLEC.
Referenced by mutaborGUI::MutBoxShape::DoLeftDblClick, mutaborGUI::MutBoxShape::readDialog.
bool mutaborGUI::BoxDlg::SetBoxType(int type)
References mutabor::Box0, DEBUGLOG, mutabor::GmnBox, mutASSERT, mutabor::NewBox, mutabor::NoBox.
Referenced by mutaborGUI::NewMutBoxShape::InitializeDialog, mutaborGUI::MutBoxShape::InitializeDialog.
void mutaborGUI::BoxDlg::SetBoxNumber(int nr)
References mutASSERT.
Referenced by mutaborGUI::NewMutBoxShape::InitializeDialog, mutaborGUI::MutBoxShape::InitializeDialog.
int mutaborGUI::BoxDlg::GetBoxNumber() const
References mutASSERT.
Referenced by mutaborGUI::MutBoxShape::DoLeftDblClick, mutaborGUI::MutBoxShape::readDialog.
void mutaborGUI::BoxDlg::DisableRemove(bool disable=true)
References UNREACHABLEC.
Referenced by mutaborGUI::NewMutBoxShape::InitializeDialog.
void mutaborGUI::BoxDlg::OnRemoveClick(wxCommandEvent &event)
References mutUnused.
void mutaborGUI::BoxDlg::AddButtonPressed(wxCommandEvent &event)
References box, mutabor::Box0, mutabor::BoxClass::GetBox, mutabor::BoxClass::IDTypeFile, mutUnused, UNREACHABLEC.