taste.h
struct taste* tmp_tastenliste
Referenced by get_new_harmonie.
void init_tastenliste(void)
Setzt die temporäre Tastenliste auf NULL.
Die Argumentliste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_new_taste(int taste, char stern)
Fügt eine Taste ans Ende von tmp_tastenliste an.
taste Tastennummer (Schlüssel-C = 60) stern Stern zur Taste (TRUE oder FALSE) Es wird immer die gesamte Liste durchsucht. Effektivität?
References mutabor_debug_level, taste::next, taste::stern, taste::taste, xmalloc.
Referenced by switch, yyparse.
int enthalten_in_tastenliste(int taste, struct taste *lauf)
Prüft ob eine Taste in einer Liste von Tasten enthalten ist.
taste Taste, die gesucht wird lauf Tastenliste, in der gesucht wird 1 Taste wurde gefunden 0 Taste wurde nicht gefunden
References TRACE, logik::next, taste::next.
Referenced by check_ausloeser.