mutabor::OutputMidiPort
typedef CommonMidiOutput<MidiPortOutputProvider, OutputDeviceClass> mutabor::OutputMidiPort::base
friend class MidiPortFactory
int mutabor::OutputMidiPort::DevId
Referenced by do_Open, GetDevId, SetDevId.
mutabor::OutputMidiPort::~OutputMidiPort()
void mutabor::OutputMidiPort::Save(tree_storage &config)
Save current device settings in a tree storage.
config (tree_storage) storage class, where the data will be saved.
References mutabor::tree_storage::Write.
void mutabor::OutputMidiPort::Save(tree_storage &config, const RouteClass *route)
Save route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route ) Route whos data shall be saved.
References mutabor::TRouteClass< I, O, B >::GetOutputFrom, mutabor::TRouteClass< I, O, B >::GetOutputTo, mutabor::tree_storage::GetPath, mutASSERT, mutabor::TRouteClass< I, O, B >::OutputAvoidDrumChannel, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent, mutabor::tree_storage::Write.
void mutabor::OutputMidiPort::Load(tree_storage &config)
Load current device settings from a tree storage.
config (tree_storage) storage class, where the data will be loaded from.
References _mut, DEFAULT_BENDING_RANGE, mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::Read, mutabor::rtmidiout.
void mutabor::OutputMidiPort::Load(tree_storage &config, RouteClass *route)
Loade route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route ) Route whos data shall be loaded.Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route) Route whos data shall be loaded.
References mutabor::tree_storage::GetPath, mutASSERT, mutabor::TRouteClass< I, O, B >::OutputAvoidDrumChannel, mutabor::tree_storage::Read, mutabor::hidden::runtime_error, mutabor::TRouteClass< I, O, B >::SetOutputFrom, mutabor::TRouteClass< I, O, B >::SetOutputTo, mutabor::str, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent, mutabor::hidden::warning.
virtual bool mutabor::OutputMidiPort::NeedsRealTime()
virtual void mutabor::OutputMidiPort::SetDevId(int id)
References _mut, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::Close, DevId, mutabor::hidden::error, mutabor::Device::IsOpen, mutabor::Device::Name, mutabor::OutputDeviceClass::Open, mutabor::rtmidiout, mutabor::Device::runtime_error, mutabor::str.
Referenced by mutaborGUI::MutOutputMidiDeviceShape::readDialog.
int mutabor::OutputMidiPort::GetDevId()
References DevId.
Referenced by mutaborGUI::MutOutputMidiDeviceShape::InitializeDialog.
virtual DevType mutabor::OutputMidiPort::GetType() const
References mutabor::DTMidiPort.
virtual std::string mutabor::OutputMidiPort::GetTypeName() const
References _mutN.
mutabor::OutputMidiPort::operator std::string() const
References mutabor::str.
virtual int mutabor::OutputMidiPort::GetMaxChannel() const
Referenced by mutaborGUI::MutOutputMidiDeviceShape::GetFilterPanel.
virtual int mutabor::OutputMidiPort::GetMinChannel() const
Referenced by mutaborGUI::MutOutputMidiDeviceShape::GetFilterPanel.
mutabor::OutputMidiPort::OutputMidiPort(std::string name="", int id=-1, int bendingRange=2)
References TRACEC.
bool mutabor::OutputMidiPort::do_Open()
References DevId, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::do_Open, mutabor::Device::Name, mutabor::MidiPortOutputProvider::Open, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::Out.
void mutabor::OutputMidiPort::do_Gis(GisToken *token, char turn)
void mutabor::OutputMidiPort::do_AddTime(frac time)