templates
typedef wxMBConv muConvAuto
wxMBConv* muConvAutoFallback
wxMBConv* muConvAutoFallback
MutFileDataType FileNameDialog(wxWindow *parent, int Command, wxString Filename)
References _, MutFileDataType::Canceled, mutaborGUI::CM_EXECUTE, CM_FILEOPEN, CM_FILESAVEAS, mutaborGUI::CM_ROUTELOAD, mutaborGUI::CM_ROUTESAVE, mutaborGUI::CM_ROUTESAVEAS, DEBUGLOG2, MutFileDataType::LogicSource, name, MutFileDataType::name, MutFileDataType::type, MutFileDataType::Unknown, MutFileDataType::UTF8TextRoute, MutFileDataType::XMLRoute1.
Referenced by mutaborGUI::MutFrame::CmFileOpen, mutaborGUI::MutEditFile::CmFileSaveAs, mutaborGUI::MutRouteWnd::CmRouteLoad, mutaborGUI::MutRouteWnd::CmRouteSaveAs, IMPLEMENT_APP.
void PRINTWINDOW(wxWindow *window, const wxString &offset=_T(""))
References DEBUGLOG2, mutUnused.