Interval.cpp
_
Referenced by berechne_intervall_endgueltig, mutabor::hidden::berechne_intervalle_absolut, mutabor::hidden::check_komplex_intervall, get_intervall_wert, mutabor::hidden::get_wert_komplex_intervall, intervall_nummer, test_zyklen.
adjazent
Referenced by mutabor::hidden::berechne_intervalle_absolut, test_zyklen.
int anzahl_intervalle
Referenced by mutabor::hidden::berechne_intervalle_absolut, intervall_nummer, test_zyklen.
struct intervall** intervalle
char* visited
char* matrix
static double get_intervall_wert(mutabor_box_type *box, const char *name)
References _, mutabor::hidden::compiler_error, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::get_wert_komplex_intervall, mutabor::hidden::intervall_absolut, mutabor::hidden::intervall::intervall_absolut, mutabor::hidden::intervall_komplex, mutabor::hidden::intervall::intervall_komplex, mutabor::hidden::intervall::intervall_typ, mutabor::hidden::mutabor_logic_parsed::list_of_intervalle, mutabor::hidden::mutabor_error_message, mutabor::hidden::intervall::name, mutabor::hidden::intervall::u.
Referenced by mutabor::hidden::get_wert_komplex_intervall.
double get_wert_komplex_intervall(mutabor_box_type *box, struct komplex_intervall *intervall)
References _, mutabor::hidden::compiler_error, get_intervall_wert, mutabor::hidden::mutabor_error_message.
Referenced by berechne_intervall_endgueltig, mutabor::hidden::berechne_ton_endgueltig, mutabor::hidden::expandiere_tonsystem, mutabor::hidden::expandiere_umstimmung, get_intervall_wert.
int intervall_list_laenge(struct intervall *list)
Referenced by mutabor::hidden::berechne_intervalle_absolut, mutabor::BoxClass::Compile.
static void belege_intervalle(struct intervall **intervalle, struct intervall *liste)
References mutabor::hidden::intervall::next.
Referenced by mutabor::hidden::berechne_intervalle_absolut.
static int intervall_nummer(mutabor_box_type *box, const char *name)
References _, anzahl_intervalle, mutabor::hidden::compiler_error, mutabor::hidden::mutabor_error_message.
Referenced by berechne_intervall_endgueltig, mutabor::hidden::berechne_intervalle_absolut.
static void test_zyklen(mutabor_box_type *box, int startknoten)
References _, adjazent, anzahl_intervalle, mutabor::hidden::compiler_error, mutabor::hidden::mutabor_error_message, mutabor::hidden::test_zyklen.
static void berechne_intervall_endgueltig(mutabor_box_type *box, int k)
References _, mutabor::hidden::get_wert_komplex_intervall, mutabor::hidden::internal_error, mutabor::hidden::intervall_absolut, mutabor::hidden::intervall::intervall_absolut, mutabor::hidden::intervall_komplex, mutabor::hidden::intervall::intervall_komplex, intervall_nummer, mutabor::hidden::intervall::intervall_typ, mutabor::hidden::mutabor_error_message, mutabor::hidden::intervall::u.
Referenced by mutabor::hidden::berechne_intervalle_absolut.
void berechne_intervalle_absolut(mutabor_box_type *box, struct intervall *list_of_intervalle)
References _, adjazent, anzahl_intervalle, belege_intervalle, berechne_intervall_endgueltig, mutabor::hidden::internal_error, mutabor::hidden::intervall_absolut, mutabor::hidden::intervall_komplex, mutabor::hidden::intervall::intervall_komplex, mutabor::hidden::intervall_list_laenge, intervall_nummer, mutabor::hidden::mutabor_error_message, mutabor::hidden::test_zyklen, mutabor::hidden::xalloca, mutabor::hidden::xde_alloca.
Referenced by mutabor::hidden::mutabor_programm_einlesen.
void check_komplex_intervall(mutabor_box_type *box, struct komplex_intervall *liste, const char *konstrukt_name)
References _, mutabor::hidden::compiler_error, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::get_intervall, mutabor::hidden::internal_error, mutabor::hidden::intervall_absolut, mutabor::hidden::intervall::intervall_typ, mutabor::hidden::mutabor_logic_parsed::list_of_intervalle, mutabor::hidden::mutabor_error_message.
Referenced by mutabor::hidden::check_konsistenz.