(TeX-add-style-hook
 "reference"
 (lambda ()
   (TeX-run-style-hooks
    "preamble"
    "syn1"
    "syn2"
    "syn3"
    "syn5"
    "syn4"
    "syn6"
    "syn8"
    "syn7"
    "syn9"
    "syn26"
    "syn10"
    "syn11"
    "syn12"
    "syn13"
    "syn14"
    "syn28"
    "syn23"
    "syn17"
    "syn16"
    "syn22"
    "syn15"
    "syn24"
    "syn27"
    "syn18"
    "syn19"
    "syn20"
    "syn21"
    "syn25")
   (TeX-add-symbols
    "dq"
    "bi"
    "ei")
   (LaTeX-add-labels
    "cha:sprachreferenz"
    "eins"
    "cha:lexik-konv"
    "zwei"
    "sec:eingabesymbole"
    "zweieins"
    "sec:kommentare"
    "zweizwei"
    "sec:namen"
    "zweidrei"
    "sec:reservierte-worte"
    "zweivier"
    "sec:zahlen"
    "zweifuenf"
    "cha:syntax-schreibweise"
    "drei"
    "cha:das-logikprogramm"
    "cha:intervall"
    "cha:ton"
    "cha:tonsystem"
    "period interval"
    "Periodenintervall"
    "cha:umstimmung"
    "cha:harmonie"
    "cha:logik"
    "sec:ausloser"
    "sec:tasten"
    "sec:harmonien"
    "sec:midi-ereignisse"
    "sec:aktionen"
    "sec:midi-ausgaben"
    "cha:midi-kanale"
    "MIDICHANNEL"
    "sec:worterklarungen")
   (LaTeX-add-index-entries
    "input symbols"
    "word class"
    "Name"
    "word!reserved"
    "space"
    "line feed"
    "page feed"
    "comments"
    "comment"
    "*''@\\dq (double quote)"
    "name"
    "*_@\\_ (underscore)"
    "*'@\\textapostrophe\\ (apostrophe)"
    "significance"
    "Namen"
    "\\_ (Unterstrich)"
    "#' (Apostroph)"
    "Signifikanz"
    "identifier"
    "Bezeichner"
    "Worte!reservierte"
    "number"
    "*#@\\#"
    "hex digit"
    "Zahlen"
    "Hex-Ziffern"
    "declaration"
    "12tet"
    "Deklarationen"
    "Interval"
    "root"
    "Wurzel"
    "factor"
    "Faktor"
    "Tone"
    "tone!reference tone"
    "frequency"
    "Bezugston"
    "Frequenz"
    "frequency!absolute"
    "Frequenz!absolute"
    "tone system"
    "anchor
  key"
    "interval!period interval"
    "*[]@[] (brackets)"
    "MIDI!number"
    "Verankerungstaste"
    "Periodenintervall"
    "[ ] (eckige Klammern)"
    "MIDI!Nummer"
    "fundamental scale"
    "Fundamentaltonleiter"
    "retuning"
    "tuning!current"
    "*A@\\textat\\ (at)"
    "Stimmung!aktuelle"
    "at@\\textat\\ (at)"
    "parameter"
    "parameter!symbolic name"
    "Parameter"
    "Parameter!symbolischer Name"
    "retuning!anchor"
    "Umstimmung!Verankerung"
    "Intervallstruktur"
    "retuning!width"
    "Umstimmung!Breite"
    "Fundamentaltonleiter!Breite der"
    "retuning!tones"
    "Umstimmung!Töne"
    "{\\@ (at)}"
    "retuning!period"
    "period
        interval"
    "Umstimmung!Periode"
    "retuning!bundle"
    "action"
    "Umstimmung!Bund"
    "Aktionen"
    "retuning!alternative"
    "selector"
    "else"
    "Umstimmung!Alternative"
    "Selektor"
    "Ansonsten"
    "action!MIDI out"
    "MIDIOUT"
    "Aktion!MIDI-Out"
    "harmony"
    "key!number"
    "projection
  scale"
    "chroma"
    "#*@*
  (asterisk)"
    "key!reference
  key"
    "reference key"
    "chroma!reference chroma"
    "DISTANCE"
    "Tasten!Nummer"
    "Projektionstonleiter"
    "Tonigkeit"
    "**@*"
    "Bezugstaste"
    "Tasten!Bezugs-"
    "Bezugstonigkeit"
    "ABSTAND"
    "logic"
    "trigger"
    "tuning!initial"
    "initial tuning"
    "instruction!set of"
    "Auslöser"
    "Einstimmung"
    "Anweisung!Menge von"
    "trigger!global"
    "trigger!local"
    "Auslöser!globale"
    "Auslöser!lokale"
    "ansonsten"
    "ASCII"
    "key"
    "trigger!key"
    "Auslöser!Taste"
    "Tasten"
    "Harmonies"
    "trigger!harmony"
    "trigger!pattern"
    "trigger!harmonic form"
    "trigger!shifted pattern"
    "**@* (asterisk)"
    "pre-key"
    "trigger!impossible"
    "Auslöser!Harmonie"
    "Auslöser!Harmonie-Form"
    "Vortaste"
    "Nachtaste"
    "Auslöser!unmögliche"
    "harmonic form"
    "Harmonieform"
    "ELSE"
    "trigger!MIDI
  event"
    "MIDIIN"
    "status byte"
    "Status-Byte"
    "Note-On"
    "Note-Off"
    "System-Byte"
    "Actions"
    "HARMONY\\_ANALYSIS"
    "MIDI!output"
    "action!MIDI output"
    "MIDI!channel"
    "multi 16 processing"
    "Multi-16-Verfahren"
    "FB-01")))

