mutabor::timing_params
bool mutabor::timing_params::is_fixed_ticks
Referenced by get_delta_exact, get_delta_midi, get_MIDI_tick_signature, get_time_exact, get_time_midi, reset, set_MIDI_tick_signature, TowxString, update_duration_exact, update_duration_midi.
int mutabor::timing_params::fps
Referenced by get_MIDI_tick_signature, reset, set_MIDI_tick_signature, TowxString.
mutint64 mutabor::timing_params::quarter_duration
Referenced by get_delta_exact, get_delta_midi, get_quarter_duration, get_time_exact, get_time_midi, reset, set_quarter_duration, TowxString, update_duration_exact, update_duration_midi.
mutint64 mutabor::timing_params::quarter_divisions
Referenced by get_delta_exact, get_delta_midi, get_MIDI_tick_signature, get_ticks, get_time_exact, get_time_midi, reset, set_MIDI_tick_signature, TowxString, update_duration_exact, update_duration_midi.
mutabor::timing_params::timing_params()
Default Constructor.
The default constructor sets the timing parametes as follows: Fixed step durations on a 1ms grid at 120 bpm.
mutabor::timing_params::timing_params(const timing_params &o)
Copy constructor.
o the timing params that should be copied.
void mutabor::timing_params::reset()
Reset the parameters to the default values.
Fixed step durations on a 1ms grid at 120 bpm.
References fps, is_fixed_ticks, quarter_divisions, quarter_duration.
void mutabor::timing_params::set_quarter_duration(mutint64 d)
Set the quarter duration parameter.
d duration of a quarter note in microseconds.
References quarter_duration.
Referenced by mutabor::Track::ResetPosition, mutabor::Track::SetQuarterDuration.
mutint64 mutabor::timing_params::get_quarter_duration()
Get the quarter duration.
quarter duration in microseconds.
References quarter_duration.
Referenced by TimingParamsTest::testExactTicks, TimingParamsTest::testMIDITicks.
mutint64 mutabor::timing_params::get_ticks()
Get the number of ticks per time interval.
in fixed time mode return the ticks per second otherwise the number of divisions of a quarter note.
References quarter_divisions.
Referenced by TimingParamsTest::testExactTicks, TimingParamsTest::testMIDITicks.
mutint64 mutabor::timing_params::get_time_midi(mutint64 d)
Translates a given number of MIDI quarter ticks into microseconds.
Rounding is done according to the formula given in the midi standard: time = ticks * (quarter_duration / ticks per quarter) d time in quarter divisions time in microseconds.
References is_fixed_ticks, quarter_divisions, quarter_duration.
Referenced by TimingParamsTest::testMIDITicks.
mutint64 mutabor::timing_params::get_time_exact(mutint64 d)
Translates a given number of quarter ticks into microseconds using more exact rounding.
Rounding is done according to the following formula (in integer arithmetic): time = round ((ticks * (quarter_duration )) / ticks per quarter) d time in quarter divisions time in microseconds.
References is_fixed_ticks, quarter_divisions, quarter_duration.
Referenced by TimingParamsTest::testExactTicks.
mutint64 mutabor::timing_params::get_delta_midi(mutint64 time)
Translates a given time in microseconds into the corresponding number of MIDI.
Rounding is done to meet the formula given in the midi standard: time = ticks * (quarter_duration / ticks per quarter) time time in microseconds. time in quarter divisions
References is_fixed_ticks, quarter_divisions, quarter_duration.
Referenced by TimingParamsTest::testMIDITicks.
mutint64 mutabor::timing_params::get_delta_exact(mutint64 time)
Translates a given time in microseconds into number of quarter ticks using more exact rounding.
Rounding is done to meet following formula (in integer arithmetic): time = round ((ticks * (quarter_duration )) / ticks per quarter) time time in microseconds. time in quarter divisions
References is_fixed_ticks, quarter_divisions, quarter_duration.
Referenced by TimingParamsTest::testExactTicks.
std::pair< uint8_t, uint8_t > mutabor::timing_params::get_MIDI_tick_signature()
Calculate the two bytes indicating the ticks per divisions field in a MIDI file.
The return value can be read as -fps and ticks per frame in fixed timing mode and as a 15 bit number in quarter relative timeing mode.pair of bytes that can be directly copied into the Standard MIDI File header.
References DEBUGLOG, fps, gettext_noop, is_fixed_ticks, quarter_divisions.
Referenced by mutabor::Track::getMidiIickSignature, TimingParamsTest::testExactTicks, TimingParamsTest::testMIDITicks.
void mutabor::timing_params::set_MIDI_tick_signature(uint8_t fps, uint8_t count)
Calculate timing mode and timing parameters from the corresponding bytes in the MIDI file header.
fps first byte of the signature denating MSB or negative frame rate. count second byte of the signature denoting LSB or ticks per frame.
References fps, gettext_noop, is_fixed_ticks, quarter_divisions.
Referenced by TimingParamsTest::testExactTicks, TimingParamsTest::testMIDITicks.
wxString mutabor::timing_params::TowxString()
References fps, is_fixed_ticks, quarter_divisions, quarter_duration.
Referenced by c_str.
const mutChar* mutabor::timing_params::c_str()
References TowxString.
static mutint64 mutabor::timing_params::update_duration_midi(mutint64 duration, const timing_params &oldd, const timing_params &newd)
Update the a duration when the parameters change.
In Type 1 MIDI files the first track contains timing parameters for all tracks. This function can be used to update time stamps that are stored in microseconds.This function assumes that the change should take after an offset of 0 μs. Thus, offsets must be honoured in the calling code. duration time to be recalculated oldd old timing object. newd now timing object. recalculated duration according to the two passed timing objects.
References duration, is_fixed_ticks, MUTABOR_NO_DELTA, quarter_divisions, quarter_duration.
Referenced by mutabor::Track::SetQuarterDuration.
static mutint64 mutabor::timing_params::update_duration_exact(mutint64 duration, const timing_params &oldd, const timing_params &newd)
Update the a duration when the parameters change.
In Type 1 MIDI files the first track contains timing parameters for all tracks. This function can be used to update time stamps that are stored in microseconds.This version tries to be more exact than the MIDI standard. For decoding standard MIDI files update_duration_midi is recommended.This function assumes that the change should take after an offset of 0 μs. Thus, offsets must be honoured in the calling code. duration time to be recalculated oldd old timing object. newd now timing object. recalculated duration according to the two passed timing objects.
References duration, is_fixed_ticks, MUTABOR_NO_DELTA, quarter_divisions, quarter_duration.