testCommonFileDeviceTimer
long testCommonFileDeviceTimer::i
Referenced by Play, PrepareNextEvent, Stop.
long testCommonFileDeviceTimer::max
Referenced by Play, PrepareNextEvent.
long testCommonFileDeviceTimer::min
Referenced by Play, PrepareNextEvent.
mutint64 testCommonFileDeviceTimer::lasttime
Referenced by Open, Play, PrepareNextEvent.
mutint64 testCommonFileDeviceTimer::firsttime
Referenced by Open, Play, Stop.
mutint64 testCommonFileDeviceTimer::pausetime
Referenced by Open, Pause, Play.
const mutabor::ChannelData testCommonFileDeviceTimer::Cd
Referenced by GetChannelData.
wxStopWatch testCommonFileDeviceTimer::sw
Referenced by Open, Play, Stop.
testCommonFileDeviceTimer::testCommonFileDeviceTimer()
virtual testCommonFileDeviceTimer::~testCommonFileDeviceTimer()
void testCommonFileDeviceTimer::Play()
Command the device to play music.
This function starts playing the music of the device at the curren position.
References mutabor::CurrentTime, DEBUGLOG, firsttime, mutabor::CurrentTimer::Get, i, lasttime, max, min, pausetime, mutabor::CommonFileInputDevice::timer, mutabor::CurrentTimer::UseRealtime.
Referenced by CommonFileDeviceTest::testTimer.
void testCommonFileDeviceTimer::Pause()
Pause playback or recording of the device.
References mutabor::CurrentTime, mutabor::CurrentTimer::Get, pausetime.
Referenced by CommonFileDeviceTest::testTimer.
bool testCommonFileDeviceTimer::Open()
References mutabor::CurrentTime, firsttime, mutabor::CurrentTimer::Get, lasttime, pausetime.
Referenced by CommonFileDeviceTest::testTimer.
void testCommonFileDeviceTimer::Stop()
Stop playback or recording of the device.
References mutabor::CurrentTime, DEBUGLOG, firsttime, mutabor::CurrentTimer::Get, i, mutint64, mutabor::CommonFileInputDevice::timer.
mutint64 testCommonFileDeviceTimer::PrepareNextEvent()
Go on to the next event.
This function must be provided by the device. It is asked to prepare the next event and return the time to wait in microseconds from the start of the piece. Though the timer has only milliseconds resolution, the errors will sum up so that we need a much higher resolution, here.Here, we use the measure that is used in the SMF standard. It has been designed to reduce the deviation of a 4 minutes piece at 120 bpm to 500μs. If it were 500ms it would be unusable.uint_fast64_t Absolute temporal position of the next event in the piece in μs.
References mutabor::CurrentTime, DEBUGLOG, mutabor::DevicePause, mutabor::DevicePlay, mutabor::DeviceStop, mutabor::CurrentTimer::Get, mutabor::InputDeviceClass::GetNO_DELTA, i, lasttime, max, min, mutabor::Device::Mode, mutint64, mutabor::CommonFileInputDevice::timer.
void testCommonFileDeviceTimer::Save(mutabor::tree_storage &, const mutabor::RouteClass *)
Save route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route) Route whos data shall be saved.
void testCommonFileDeviceTimer::Load(mutabor::tree_storage &, mutabor::RouteClass *)
Load route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route) Route whos data shall be loaded.
virtual mutabor::ChannelData& testCommonFileDeviceTimer::GetChannelData(const mutabor::InputDeviceClass::current_keys_type::entry &key) const
References Cd.
testCommonFileDeviceTimer::testCommonFileDeviceTimer()
virtual testCommonFileDeviceTimer::~testCommonFileDeviceTimer()
void testCommonFileDeviceTimer::Play()
Command the device to play music.
This function starts playing the music of the device at the curren position.
References mutabor::CurrentTime, i, lasttime, max, min, sw, mutabor::CurrentTimer::UseRealtime.
bool testCommonFileDeviceTimer::Open()
References lasttime, sw.
void testCommonFileDeviceTimer::Stop()
Stop playback or recording of the device.
References i, sw.
mutint64 testCommonFileDeviceTimer::PrepareNextEvent()
Go on to the next event.
This function must be provided by the device. It is asked to prepare the next event and return the time to wait in microseconds from the start of the piece. Though the timer has only milliseconds resolution, the errors will sum up so that we need a much higher resolution, here.Here, we use the measure that is used in the SMF standard. It has been designed to reduce the deviation of a 4 minutes piece at 120 bpm to 500μs. If it were 500ms it would be unusable.uint_fast64_t Absolute temporal position of the next event in the piece in μs.
References mutabor::InputDeviceClass::GetNO_DELTA, i, lasttime, max, min, mutint64.
virtual void testCommonFileDeviceTimer::Save(mutabor::tree_storage &config, const mutabor::RouteClass *route)
Save route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route) Route whos data shall be saved.
virtual void testCommonFileDeviceTimer::Load(mutabor::tree_storage &config, mutabor::RouteClass *route)
Load route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route) Route whos data shall be loaded.
virtual mutabor::ChannelData& testCommonFileDeviceTimer::GetChannelData(const mutabor::InputDeviceClass::current_keys_type::entry &key) const
References Cd.