GisReadArtHead
frac GisReadArtHead::Time2
Referenced by GisReadArtHead, GisReadArtHeadOn, Read, mutabor::InputGis::ReadOn.
mutint64 GisReadArtHead::Delta
Referenced by GisReadArtHead, mutabor::InputGis::ReadOn.
mutabor::Box GisReadArtHead::Box
Referenced by GisReadArtHead, mutabor::MutaborTag, mutabor::InputGis::Proceed, mutabor::InputGis::ProceedRoute, mutabor::InputGis::Stop.
TagList* GisReadArtHead::Intensity
Referenced by GetIntensity, GisReadArtHead, Read, ~GisReadArtHead.
TagList* GisReadArtHead::Articulation
Referenced by GetArticulation, GisReadArtHead, Read, ~GisReadArtHead.
TagList* GisReadArtHead::Octave
Referenced by GetOctave, GisReadArtHead, Read, ~GisReadArtHead.
TagList* GisReadArtHead::Alter
Referenced by GetAlter, GisReadArtHead, Read, ~GisReadArtHead.
TagList* GisReadArtHead::Instr
Referenced by GetInstr, GisReadArtHead, Read, ~GisReadArtHead.
TagList* GisReadArtHead::Tempo
Referenced by GetSpeedFactor, GisReadArtHead, Read, ~GisReadArtHead.
GisReadArtHead::GisReadArtHead(GisReadArtHead *boss, GisToken *cursor, const mutString id, bool singleToken=false)
References Alter, Articulation, Box, Copy, DEBUGLOG, Delta, Instr, Intensity, Octave, Tempo, Time2, GisReadHead::Turn.
Referenced by Build.
GisReadArtHead::~GisReadArtHead()
References Alter, Articulation, Erase, Instr, Intensity, Octave, Tempo.
virtual GisReadHead* GisReadArtHead::Build(GisReadHead *boss, GisToken *cursor, const mutString &id, bool singleToken=false)
References GisReadArtHead.
void GisReadArtHead::Read()
References AddTag, Alter, ARStaccatto, ARTenuto, Articulation, ArticulationHold, TagListData::data::ch, char, GisReadHead::CreateSegmentSubs, GisReadHead::CreateSequenzSubs, GisReadHead::Cursor, TagListData::Data, DEBUGLOG, frac::denominator, EndTag, GetArticulation, GetMidiInstrument, GetReal, GetTheSpeedFactor, GTComma, GTNote, GTNull, GTParaInt, GTParaReal, GTParaStr, GTSegment, GTSequenz, GTTag, GTTagBegin, GTTagEnd, GTUnknown, TagListData::data::i, GisReadHead::Id, Instr, Intensity, frac::numerator, Octave, TAG, TAGEND, Tempo, GisReadHead::Time, Time2, TTaccent, TTalter, TTinstr, TTintens, TToct, TTstacc, TTtempo, TTten, GisReadHead::Turn, GisToken::Type.
Referenced by GisReadArtHeadOn, IMPLEMENT_APP, mutabor::InputGis::ReadOn.
ARType GisReadArtHead::GetArticulation()
References ARNormal, Articulation, TagListData::data::ch, TagListData::Data.
Referenced by GetIntensity, Read.
char GisReadArtHead::GetIntensity(char noteOff=0)
References ARPortato, TagListData::data::ch, TagListData::Data, GetArticulation, Intensity.
Referenced by mutabor::InputGis::Proceed, MisFile::WriteGis.
int GisReadArtHead::GetOctave()
References TagListData::Data, TagListData::data::i, Octave.
Referenced by mutabor::InputGis::Proceed, MisFile::WriteGis.
int GisReadArtHead::GetAlter()
References Alter, TagListData::Data, TagListData::data::i.
Referenced by MisFile::WriteGis.
int GisReadArtHead::GetInstr()
References TagListData::data::ch, TagListData::Data, Instr.
Referenced by mutabor::InputGis::Proceed.
int GisReadArtHead::GetSpeedFactor()
References TagListData::Data, DEBUGLOG, TagListData::data::i, Tempo.
Referenced by mutabor::InputGis::ReadOn.