ext.cpp
char sHelp[120][120]
return value for ExtCheck and ExtChange functions
Referenced by ExtChange, ExtCheck.
char* ExtCheck(char *fileName, char *extension)
Append a extension to a file name if it does not exist.
fileName Filename the extension has to be added to extension Extension which should be added Fehlerpossible buffer overflow for sHelp (no length check)
References sHelp.
Referenced by GetInFile, GetOutFile, main.
char* ExtChange(char *fileName, char *extension)
Exchanges the extension of a file name.
fileName Filename the extension has to be added to extension Extension which should be added Fehlerpossible buffer overflow for sHelp (no length check) first dot in filename used to detect extension, but not last one.
References sHelp.
Referenced by main.