mutaborGUI::GUIOutputDeviceBase
MutOutputDeviceShapeList mutaborGUI::GUIOutputDeviceBase::shapes
Referenced by Add, GetShape, MoveToInList, Remove, Replace.
const MutOutputDeviceShapeList& mutaborGUI::GUIOutputDeviceBase::GetShapes() const
Referenced by mutaborGUI::MakeTopLevelsOutput.
MutOutputDeviceShapeList& mutaborGUI::GUIOutputDeviceBase::GetShapes()
void mutaborGUI::GUIOutputDeviceBase::Add(mutabor::Route &route)
add a route
References mutaborGUI::MutBoxChannelShape::Add, DEBUGLOG, GetDevice, mutaborGUI::GUIRouteBase::GetShape, intrusive_ptr_get_refcount, mutASSERT, shapes, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::GUIfiedOutputDevice< T >::Add.
bool mutaborGUI::GUIOutputDeviceBase::Replace(mutabor::Route &oldroute, mutabor::Route &newroute)
replace a route
References mutaborGUI::GUIRouteBase::GetShape, mutASSERT, Remove, shapes, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::GUIfiedOutputDevice< T >::Replace.
bool mutaborGUI::GUIOutputDeviceBase::Remove(mutabor::Route &route)
remove a route
References DEBUGLOG, GetDevice, mutaborGUI::GUIRouteBase::GetShape, intrusive_ptr_get_refcount, mutASSERT, mutaborGUI::MutBoxChannelShape::Remove, shapes, mutaborGUI::ToGUIBase, UNREACHABLEC.
Referenced by mutaborGUI::GUIfiedOutputDevice< T >::Remove, Replace.
void mutaborGUI::GUIOutputDeviceBase::Add(MutOutputDeviceShape *shape)
Move routes to another device.
References shapes, UNREACHABLEC.
bool mutaborGUI::GUIOutputDeviceBase::Remove(MutOutputDeviceShape *shape)
References mutASSERT, shapes, UNREACHABLEC.
MutOutputDeviceShape * mutaborGUI::GUIOutputDeviceBase::GetShape(wxWindow *parent)
References shapes.
Referenced by mutaborGUI::GUIRouteBase::Add, mutaborGUI::Check, mutaborGUI::GUIRouteBase::Remove, mutaborGUI::GUIRouteBase::Replace.
virtual mutabor::OutputDeviceClass* mutaborGUI::GUIOutputDeviceBase::GetDevice()=0
Referenced by Add, Remove.
void mutaborGUI::GUIOutputDeviceBase::MoveToInList(int newpos)
Move the associated device shape to a given position.
This function handles the GUI part of GUIfiedOutputDevice::MoveInList(). newpos New position of the shape in the list. This parameter should reflect the actual position of the device in the (non GUI) output device list.
References shapes.
Referenced by mutaborGUI::GUIfiedOutputDevice< T >::MoveInList.
void mutaborGUI::GUIOutputDeviceBase::Destroy()
References mutabor::disconnect, TRACEC.
void mutaborGUI::GUIOutputDeviceBase::runtime_error(int type, const mutStringRef message, va_list &args)
References mutaborGUI::CM_PRINT_ERROR, mutabor::hidden::internal_error, mutabor::to_string.
Referenced by mutaborGUI::GUIfiedOutputDevice< T >::runtime_error.
static GUIOutputDeviceBase* mutaborGUI::GUIOutputDeviceBase::GetGUIOutputDevice(mutabor::OutputDeviceClass *d)
References mutabor::Device::getUserData.
Referenced by mutaborGUI::ToGUIBase.
static const GUIOutputDeviceBase* mutaborGUI::GUIOutputDeviceBase::GetGUIOutputDevice(const mutabor::OutputDeviceClass *d)
References mutabor::Device::getUserData.