mutabor::InputDeviceClass::current_keys_type
typedef boost::unordered_multiset<entry, hash_type> mutabor::InputDeviceClass::current_keys_type::map_type
typedef map_type::iterator mutabor::InputDeviceClass::current_keys_type::iterator
typedef map_type::const_iterator mutabor::InputDeviceClass::current_keys_type::const_iterator
map_type mutabor::InputDeviceClass::current_keys_type::map
Referenced by add, begin, clear, end, rehash, remove.
void mutabor::InputDeviceClass::current_keys_type::add(int key, int velocity, int unique_id, Route &R, InputDevice i, const ChannelData &c, void *userdata)
References DEBUGLOG, map.
Referenced by mutabor::InputDeviceClass::NoteOn, mutabor::InputDeviceClass::Panic.
void mutabor::InputDeviceClass::current_keys_type::add(entry e)
References map.
void mutabor::InputDeviceClass::current_keys_type::remove(int key, int velocity, int unique_id, Route &R)
References DEBUGLOG, map.
Referenced by mutabor::InputDeviceClass::DoNoteOff, mutabor::InputDeviceClass::Panic.
void mutabor::InputDeviceClass::current_keys_type::remove(iterator i)
References map.
void mutabor::InputDeviceClass::current_keys_type::clear()
References map.
Referenced by mutabor::InputDeviceClass::DoSilenceKeys.
void mutabor::InputDeviceClass::current_keys_type::rehash(size_t n)
References map.
Referenced by midicmnInputDevice::midicmnInputDevice.
iterator mutabor::InputDeviceClass::current_keys_type::begin()
References map.
Referenced by mutabor::InputDeviceClass::DoSilenceKeys, mutabor::InputDeviceClass::Panic, mutabor::InputDeviceClass::ResumeKeys.
const_iterator mutabor::InputDeviceClass::current_keys_type::begin() const
References map.
iterator mutabor::InputDeviceClass::current_keys_type::end()
References map.
Referenced by mutabor::InputDeviceClass::DoSilenceKeys, mutabor::InputDeviceClass::Panic, mutabor::InputDeviceClass::ResumeKeys.
const_iterator mutabor::InputDeviceClass::current_keys_type::end() const
References map.