TabGen.cpp
_
typedef int* intptr
long anzahl_eingelesene_zeichen
Referenced by init_yylex, yylex.
static struct do_aktion * expandiere_name(mutabor_box_type *box, const char *name, struct argument_list *parameter, struct interpreter_argument_list *bezugs_liste)
References _, compiler_error, expandiere_logik, expandiere_tonsystem, expandiere_umstimmung, mutabor_box_type::file, generate_argument_list, get_logik, get_umstimmung, mutabor_logic_parsed::list_of_logiken, mutabor_logic_parsed::list_of_tonsysteme, mutabor_logic_parsed::list_of_umstimmungen, mutabor_error_message, parser_get_tonsystem, TRACE.
Referenced by expand_aktions_liste.
static struct do_aktion * expandiere_umstimmung(mutabor_box_type *box, struct umstimmung *the_umstimmung, struct interpreter_argument_list *aktuelle_parameter)
References _, umstimmung::argument_liste, do_aktion::arguments, aufruf_midi_out, aufruf_umst_breite_abs, aufruf_umst_breite_rel, aufruf_umst_taste_abs, aufruf_umst_taste_rel, aufruf_umst_toene_veraendert, aufruf_umst_umst_bund, aufruf_umst_umst_case, aufruf_umst_wiederholung_abs, aufruf_umst_wiederholung_rel, do_aktion::calling, expand_aktions_liste, expand_case_liste, expand_tonliste, generate_argument_list, get_wert_komplex_intervall, internal_error, mutabor_convert_factor_to_pitch, mutabor_convert_pitch_to_interval, mutabor_error_message, do_aktion::name, do_aktion::next, resolve_parameters, do_aktion::secondary_arguments, TRACE, umstimmung::u, do_aktion::u, umstimmung_breite_abs, umstimmung_breite_rel, umstimmung::umstimmung_breite_rel, umstimmung_midi_out, umstimmung::umstimmung_midi_out, umstimmung_taste_abs, umstimmung_taste_rel, umstimmung::umstimmung_taste_rel, umstimmung_toene_veraendert, umstimmung::umstimmung_toene_veraendert, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, xfree, xmalloc.
Referenced by expandiere_logik, expandiere_name.
static struct do_aktion * expandiere_midi(mutabor_box_type *box, struct midiliste *liste)
References _, do_aktion::arguments, aufruf_midi_out, do_aktion::name, do_aktion::next, do_aktion::secondary_arguments, TRACE, do_aktion::u, xmalloc.
Referenced by expand_aktions_liste.
static struct do_aktion * expand_harmony_analysis(mutabor_box_type *box)
References _, do_aktion::arguments, aufruf_harmony_analysis, do_aktion::name, do_aktion::next, do_aktion::secondary_arguments, TRACE, xmalloc.
Referenced by expand_aktions_liste.
void insert_in_lokale_liste(mutabor_box_type *box, struct do_aktion *action, struct anweisung *lauf, struct logik *logic)
References _, midi_ereignis::aktion, keyboard_ereignis::aktion, harmonie_ereignis::aktion, anweisung::aktion, anweisung::ausloeser, ausloeser_default, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser_taste, create_midi_scan_liste, expand_aktions_liste, expand_pattern, midi_ereignis::first_pos, logik::harmony_list, internal_error, harmonie_ereignis::ist_harmonieform, logik::keystroke_list, logik::midi_input_list, mutabor_error_message, MUTABOR_INVALID_KEY, mutabor_is_else_path, mutabor_is_harmonic_form, mutabor_is_no_harmonic_form, harmonie_ereignis::nachtaste, midi_ereignis::name, keyboard_ereignis::name, harmonie_ereignis::name, logik::name, midi_ereignis::next, keyboard_ereignis::next, harmonie_ereignis::next, harmonie_ereignis::pattern, midi_ereignis::scan_pos, TRACE, ausloeser::u, harmonie_ereignis::vortaste, xmalloc.
Referenced by expand_decition_tree, expandiere_logik.
double get_komplex_faktor(mutabor_box_type *box, struct komplex_intervall *lauf)
References _, compiler_error, komplex_intervall::faktor, mutabor_box_type::file, get_intervall, internal_error, intervall_absolut, intervall_komplex, mutabor_logic_parsed::list_of_intervalle, mutabor_error_message, komplex_intervall::name, do_aktion::next, TRACE, intervall::u.
Referenced by expand_tonliste, get_komplex_frequenz.
double get_komplex_frequenz(mutabor_box_type *box, struct ton *dieser)
References mutabor_box_type::file, get_komplex_faktor, get_ton, mutabor_logic_parsed::list_of_toene, ton::ton_komplex, intervall::u, ton::u.
Referenced by expand_tonliste.
void fprint_argument(mutabor_box_type *box, FILE *zieldatei, struct argument *argument)
References _, internal_error, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_parameter, mutabor_error_message, TRACE, intervall::u.
static void reduce_argument(mutabor_box_type *box, struct interpreter_argument_list *list, size_t index, struct interpreter_argument_list *reference)
References interpreter_argument::constant, interpreter_argument_list::data, interpreter_argument::index, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, interpreter_argument_list::types.
Referenced by generate_argument_list.
static struct interpreter_argument_list* generate_argument_list(mutabor_box_type *box, struct argument_list *element, struct interpreter_argument_list *bezugs_liste)
References _, argument_list::argument, argument::argument_type, interpreter_argument::constant, interpreter_argument_list::data, mutabor_box_type::file, if, interpreter_argument::index, internal_error, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, mutabor_error_message, argument_list::next, mutabor_logic_parsed::parameter_count, reduce_argument, interpreter_argument_list::size, TRACE, interpreter_argument_list::types, xcalloc, xmalloc.
Referenced by expandiere_name, expandiere_umstimmung.
static void resolve_parameters(mutabor_box_type *box, struct interpreter_argument_list *target, struct interpreter_argument_list *reference)
References _, interpreter_argument_list::data, interpreter_argument::index, internal_error, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, mutabor_error_message, interpreter_argument_list::size, interpreter_argument_list::types.
Referenced by expandiere_umstimmung.
static struct ton_einstell* expand_tonliste(mutabor_box_type *box, struct ton *the_tonliste)
References _, einstell_absolut, einstell_gleich, einstell_relativ, einstell_stumm, get_komplex_faktor, get_komplex_frequenz, internal_error, mutabor_convert_factor_to_pitch, mutabor_convert_frequency_to_pitch, mutabor_convert_pitch_to_interval, mutabor_convert_pitch_to_tone, mutabor_error_message, ton::name, ton_einstell::next, ton_absolut, ton::ton_absolut, ton_komplex, ton::ton_komplex, TRACE, ton_einstell::u, ton::u, xmalloc.
Referenced by expandiere_umstimmung.
static struct do_aktion* expandiere_tonsystem(mutabor_box_type *box, struct tonsystem *the_tonsystem)
References do_aktion::arguments, aufruf_tonsystem, mutabor_box_type::file, get_ton, get_wert_komplex_intervall, mutabor_logic_parsed::list_of_toene, mutabor_convert_factor_to_pitch, mutabor_convert_frequency_to_pitch, mutabor_convert_pitch_to_interval, mutabor_convert_pitch_to_tone, ton::name, do_aktion::name, ton::next, do_aktion::secondary_arguments, TSYS::ton, ton_list_laenge, TRACE, ton::u, xmalloc.
Referenced by expandiere_logik, expandiere_name.
static struct do_aktion* expandiere_logik(mutabor_box_type *box, struct logik *the_logik)
References _, logik::anweisungsliste, do_aktion::arguments, aufruf_logik, do_aktion::calling, compiler_error, logik::einstimmungs_name, expandiere_tonsystem, expandiere_umstimmung, mutabor_box_type::file, get_logik_nummer, get_umstimmung, logik::harmony_list, insert_in_lokale_liste, logik::keystroke_list, mutabor_logic_parsed::list_of_logiken, mutabor_logic_parsed::list_of_tonsysteme, mutabor_logic_parsed::list_of_umstimmungen, logik::midi_input_list, mutabor_error_message, mutASSERT, do_aktion::name, do_aktion::next, anweisung::next, parser_get_tonsystem, do_aktion::secondary_arguments, TRACE, do_aktion::u, xmalloc.
Referenced by expandiere_in_globale_liste, expandiere_name.
static struct do_aktion* expand_aktions_liste(mutabor_box_type *box, struct aktions_liste *the_liste, struct interpreter_argument_list *current_parameters)
References _, aktion_aufruf, aktion_harmony_analysis, aktion_midi_out, expand_harmony_analysis, expandiere_midi, expandiere_name, internal_error, mutabor_error_message, do_aktion::next, TRACE, do_aktion::u.
Referenced by expand_case_liste, expandiere_umstimmung, insert_in_lokale_liste.
static struct case_element* expand_case_liste(mutabor_box_type *box, struct case_liste *the_liste, struct interpreter_argument_list *aktuelle_parameter)
References case_liste::case_aktion, case_liste::case_label, expand_aktions_liste, case_liste::is_default, case_liste::next, TRACE, xmalloc.
Referenced by expandiere_umstimmung.
static int* create_midi_scan_liste(mutabor_box_type *box, struct midiliste *lauf)
References midiliste::midi_code, midi_list_laenge, midiliste::next, TRACE, xcalloc.
Referenced by insert_in_globale_liste, insert_in_lokale_liste.
PATTERNN* expand_pattern(mutabor_box_type *box, const char *harmonie_name)
References _, taste::code, compiler_error, mutabor_box_type::file, for, get_harmonie, mutabor_logic_parsed::list_of_harmonien, mutabor_error_message, MUTABOR_KEYRANGE_MAX_WIDTH, taste::next, taste::stern, harmonie::tastenliste, PTRN::tonigkeit, TRACE, xmalloc.
Referenced by insert_in_globale_liste, insert_in_lokale_liste.
void insert_in_globale_liste(mutabor_box_type *box, struct logik *lauf)
References _, midi_ereignis::aktion, keyboard_ereignis::aktion, harmonie_ereignis::aktion, logik::ausloeser, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser_taste, create_midi_scan_liste, expand_pattern, mutabor_box_type::file, midi_ereignis::first_pos, mutabor_logic_parsed::global_harmonies, mutabor_logic_parsed::global_keystrokes, mutabor_logic_parsed::global_midi_inputs, internal_error, harmonie_ereignis::ist_harmonieform, mutabor_error_message, MUTABOR_INVALID_KEY, mutabor_is_harmonic_form, mutabor_is_no_harmonic_form, mutASSERT, harmonie_ereignis::nachtaste, midi_ereignis::name, keyboard_ereignis::name, harmonie_ereignis::name, logik::name, midi_ereignis::next, keyboard_ereignis::next, harmonie_ereignis::next, harmonie_ereignis::pattern, midi_ereignis::scan_pos, midi_ereignis::the_logik_to_expand, keyboard_ereignis::the_logik_to_expand, harmonie_ereignis::the_logik_to_expand, TRACE, ausloeser::u, harmonie_ereignis::vortaste, xmalloc.
Referenced by expand_decition_tree.
static void expandiere_in_globale_liste(mutabor_box_type *box)
References midi_ereignis::aktion, DEBUGLOG2, expandiere_logik, mutabor_box_type::file, mutabor_logic_parsed::global_harmonies, mutabor_logic_parsed::global_keystrokes, mutabor_logic_parsed::global_midi_inputs, mutASSERT, midi_ereignis::next, midi_ereignis::the_logik_to_expand, TRACE.
Referenced by expand_decition_tree.
void expand_decition_tree(mutabor_box_type *box)
References logik::anweisungsliste, expandiere_in_globale_liste, mutabor_box_type::file, mutabor_logic_parsed::global_harmonies, mutabor_logic_parsed::global_keystrokes, mutabor_logic_parsed::global_midi_inputs, insert_in_globale_liste, insert_in_lokale_liste, mutabor_logic_parsed::list_of_logiken, logik_list_laenge, mutASSERT, logik::name, anweisung::next, logik::next, TRACE, xcalloc.
Referenced by mutabor::BoxClass::Compile, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.