Frac.h
MU32_FRAC_H
MU32_FRAC_H_PRECOMPILED
wxString TowxString(const frac &f)
Referenced by GetTheSpeedFactor, GisReadArtHeadOn, Note, GisReadHead::ToString, GisReadArtHead::ToString, GisNote::ToString.
STD_PRE::ostream& operator<<(STD_PRE::ostream &os, const frac &f)
References frac::d, frac::n.