mutaborGUI::GUIfiedInputDevice
typedef T mutaborGUI::GUIfiedInputDevice< T >::basetype
typedef GUIfiedInputDevice<T> mutaborGUI::GUIfiedInputDevice< T >::thistype
friend class GUIMidiPortFactory
friend class GUIMidiFileFactory
friend class GUIGisFactory
mutaborGUI::GUIfiedInputDevice< T >::GUIfiedInputDevice(const mutStringRef name=mutEmptyString, mutabor::MutaborModeType mode=mutabor::DeviceStop, int id=-1)
const basetype* mutaborGUI::GUIfiedInputDevice< T >::GetDevice() const
Referenced by mutaborGUI::GUIMidiPortFactory::DoCreateInput, mutaborGUI::GUIMidiFileFactory::DoCreateInput, mutaborGUI::GUIGisFactory::DoCreateInput.
basetype* mutaborGUI::GUIfiedInputDevice< T >::GetDevice()
virtual void mutaborGUI::GUIfiedInputDevice< T >::Play()
References mutaborGUI::GUIInputDeviceBase::Play.
virtual void mutaborGUI::GUIfiedInputDevice< T >::Pause()
References mutaborGUI::GUIInputDeviceBase::Pause.
virtual void mutaborGUI::GUIfiedInputDevice< T >::Stop()
References mutaborGUI::GUIInputDeviceBase::Stop.
virtual bool mutaborGUI::GUIfiedInputDevice< T >::Open()
References mutaborGUI::GUIInputDeviceBase::Open.
virtual void mutaborGUI::GUIfiedInputDevice< T >::Close()
References mutaborGUI::GUIInputDeviceBase::Close.
void mutaborGUI::GUIfiedInputDevice< T >::Add(mutabor::Route &route)
add a route
References mutaborGUI::GUIInputDeviceBase::Add.
bool mutaborGUI::GUIfiedInputDevice< T >::Replace(mutabor::Route &oldroute, mutabor::Route &newroute)
replace a route
References mutaborGUI::GUIInputDeviceBase::Replace.
bool mutaborGUI::GUIfiedInputDevice< T >::Remove(mutabor::Route &route)
remove a route
References mutaborGUI::GUIInputDeviceBase::Remove.
void mutaborGUI::GUIfiedInputDevice< T >::DisconnectFromAll()
Move routes to another device.
References TRACEC.
int mutaborGUI::GUIfiedInputDevice< T >::MoveInList(int count)
References mutaborGUI::GUIInputDeviceBase::MoveToInList.
virtual void mutaborGUI::GUIfiedInputDevice< T >::runtime_error(int type, const mutString &message, va_list &args)
References mutaborGUI::GUIInputDeviceBase::runtime_error.