mutaborGUI::MidiOutputFilterPanel
mutaborGUI::MidiOutputFilterPanel::MidiOutputFilterPanel(wxWindow *parent)
void mutaborGUI::MidiOutputFilterPanel::SetFromChannel(int current, int min, int max)
TODO: set limits according to changes: min.max = max.value and max.min = min.value.
Referenced by mutaborGUI::MutOutputMidiDeviceShape::GetFilterPanel.
int mutaborGUI::MidiOutputFilterPanel::GetFromChannel() const
Referenced by mutaborGUI::MutOutputMidiDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiOutputFilterPanel::SetToChannel(int current, int min, int max)
Referenced by mutaborGUI::MutOutputMidiDeviceShape::GetFilterPanel.
int mutaborGUI::MidiOutputFilterPanel::GetToChannel() const
Referenced by mutaborGUI::MutOutputMidiDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiOutputFilterPanel::SetAvoidDrumChannel(bool avoid)
Referenced by mutaborGUI::MutOutputMidiDeviceShape::GetFilterPanel.
bool mutaborGUI::MidiOutputFilterPanel::GetAvoidDrumChannel() const
Referenced by mutaborGUI::MutOutputMidiDeviceShape::ReadFilterPanel.