aktion.h
aktions_typ
MIDI-Daten ausgeben.
aufruf_typ
Logik aktivieren.
void init_aktions_liste(void)
Setzt Aktionsliste auf NULL.
Die Argumentliste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_new_aktion_aufruf_element(char *name)
Fügt eine Aufruf-Aktion ans Ende von list_of_argumente an.
Der Aufruf erhält die letzte eingelesene Argumentliste. name Bezeichnung des Aufrufs, der angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References aktions_liste::next, xmalloc, aktion_aufruf, aktions_liste::u, name, get_last_argument_liste.
Referenced by switch, yyparse.
void get_new_aktion_midi_out_element(void)
Fügt eine Midi-Ausgabe-Aktion ans Ende von list_of_aktionen an.
Dazu wird die letzte Integersequenz verwendet. Es wird immer die gesamte Liste durchsucht. Effektivität?
References aktions_liste::next, xmalloc, aktion_midi_out, aktions_liste::u, get_last_integersequenz.
Referenced by switch, yyparse.
void get_aktion_midi_out(void)
void get_aktion_aufruf(char *name)
void check_aktionen(struct aktions_liste *aktionen, char *name)
Testet eine Liste von Aktionen auf Zulässigkeit.
Wird eine nicht zulässige oder erreichbare Konfiguration gefunden, wird je nach Situation ein fataler Fehler oder eine Compiler-Warnung ausgelöst. aktionen Aktionsliste, die geprüft werden soll name Name für Meldungen
References aktions_liste::next, aktions_liste::aktions_typ, aktion_midi_out, aktions_liste::u, aktions_liste::aktion_midi_out, midiliste::midi_code, compiler_warning, fatal_error, midiliste::next, aktion_aufruf, get_umstimmung, aktions_liste::aktion_aufruf, list_of_umstimmungen, parser_get_tonsystem, list_of_tonsysteme, get_logik, list_of_logiken, argument_list_laenge, parameter_list_laenge, umstimmung::parameter_liste.
Referenced by check_konsistenz, check_logik_konsistenz.
void print_aktions_liste(struct aktions_liste *lauf)
Referenced by mutabor_programm_einlesen.
struct aktions_liste* get_last_aktions_liste(void)
Gibt die Wurzel von list_of_aktionen zurück.
References list_of_aktionen.
Referenced by get_umstimmung_umstimmungs_bund, get_umstimmungs_case_zahl_element, get_umstimmungs_case_default_element, get_new_anweisung.
struct do_aktion* expandiere_name(char *name, struct argument_liste *parameter, struct interpreter_parameter_liste *bezugs_liste)
Sucht nach einer Logik, einem Tonsystem bzw.
einer Umstimmung in dieser Reihenfolge. Wird eine Umstimmung zurückgeliefert, so werden gleich auch deren Parameter ersetzt. name Name der zu suchenden Logik, des Tonsystems oder der Umstimmung. parameter Argumente, für die Parameter-Ersetzung bezugs_liste Liste mit den Interpreter-Parametern, aus denen die aktuellen Parameter für die Expansion der Umstimmung generiert werden.
References get_logik, list_of_logiken, expandiere_logik, parser_get_tonsystem, list_of_tonsysteme, expandiere_tonsystem, get_umstimmung, list_of_umstimmungen, gen_parameter_liste, expandiere_umstimmung, fatal_error.
Referenced by expand_aktions_liste.
struct do_aktion* expandiere_umstimmung(struct umstimmung *the_umstimmung, struct interpreter_parameter_liste *aktuelle_parameter)
Ersetzt die Parameter einer Umstimmung durch deren Werte.
the_umstimmung Umstimmung, die bearbeitet werden soll. aktuelle_parameter Liste der Parameter, die ersetzt werden können
References xmalloc, name, umstimmung_taste_abs, aufruf_umst_taste_abs, do_aktion::u, get_wert_of_argument, umstimmung::u, umstimmung::umstimmung_taste_abs, do_aktion::next, umstimmung_breite_abs, aufruf_umst_breite_abs, umstimmung::umstimmung_breite_abs, umstimmung_wiederholung_abs, aufruf_umst_wiederholung_abs, DOUBLE_TO_LONG, FAKTOR_TO_MIDI, get_wert_komplex_intervall, umstimmung::umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, aufruf_umst_wiederholung_rel, umstimmung_taste_rel, aufruf_umst_taste_rel, umstimmung::umstimmung_taste_rel, umstimmung_breite_rel, aufruf_umst_breite_rel, umstimmung::umstimmung_breite_rel, umstimmung_toene_veraendert, aufruf_umst_toene_veraendert, expand_tonliste, umstimmung::umstimmung_toene_veraendert, umstimmung_umstimmungsbund, xfree, expand_aktions_liste, umstimmung::umstimmung_umstimmungsbund, umstimmung_umstimmungs_case, aufruf_umst_umst_case, umstimmung::umstimmung_umstimmungs_case, expand_case_liste, umstimmung_midi_out, aufruf_midi_out, umstimmung::umstimmung_midi_out, fatal_error.
Referenced by expandiere_logik, expandiere_name.
struct do_aktion* expandiere_midi(struct midiliste *liste)
Wandelt eine MIDI-Liste in eine MIDI-Ausgabe-Aktion um.
liste MIDI-Liste, die umgewandelt werden soll
References xmalloc, name, aufruf_midi_out, do_aktion::u, do_aktion::next.
Referenced by expand_aktions_liste.
struct do_aktion* expand_aktions_liste(struct aktions_liste *the_liste, struct interpreter_parameter_liste *aktuelle_parameter)
Ersetzt Parameter in einer Aktionsliste durch ihre aktuellen Werte.
the_liste Ausgangs-Liste mit den Aktionen, deren Parameter ersetzt werden sollon. aktuelle_parameter Liste mit den Aktuellen Parametern, die ersetzt werden können. Neu hinzukommende Aktionen werden erhalten. Kann das passieren?
References aktion_aufruf, expandiere_name, do_aktion::u, aktion_midi_out, expandiere_midi, fatal_error, expand_aktions_liste, do_aktion::next.
Referenced by expand_aktions_liste, expand_case_liste, expandiere_umstimmung, insert_in_lokale_liste.
struct do_aktion* expandiere_tonsystem(struct tonsystem *the_tonsystem)
Wandelt ein Tonsystem in eine Aktion um.
Dazu werden Tonnamen expandiert und die einzelnen Töne in MIDI-Werte umgerechnet. the_tonsystem Tonsystem.
References xmalloc, name, aufruf_tonsystem, TSYS::anker, TSYS::breite, ton_list_laenge, toene, TSYS::periode, DOUBLE_TO_LONG, FAKTOR_TO_MIDI, get_wert_komplex_intervall, ton::next, ton::name, TSYS::ton, FREQUENZ_TO_MIDI, get_ton, list_of_toene, ton::u.
Referenced by expandiere_logik, expandiere_name.