mutabor::CommonFileInputDevice
ThreadCommunication
friend class MidiFileFactory
friend class FileTimer
Referenced by Open.
FileTimer* mutabor::CommonFileInputDevice::timer
Referenced by Close, mutabor::CommonFileInputDevice::FileTimer::OnExit, Open, testCommonFileDeviceTimer::Play, Play, testCommonFileDeviceTimer::PrepareNextEvent, SetThreadKind, testCommonFileDeviceTimer::Stop, ThreadPlay, WaitForDeviceFinish, ~CommonFileInputDevice, mutabor::CommonFileInputDevice::FileTimer::~FileTimer.
safe_integer<int> mutabor::CommonFileInputDevice::threadsignal
Referenced by Close, Open, Pause, Play, Stop, ThreadPlay, WaitForDeviceFinish.
Mutex mutabor::CommonFileInputDevice::waitMutex
Referenced by Close, Open, Play, ThreadPlay, WaitForDeviceFinish.
Mutex mutabor::CommonFileInputDevice::threadReady
Mutex mutabor::CommonFileInputDevice::lockMode
Referenced by Play, Stop, ThreadPlay.
Mutex mutabor::CommonFileInputDevice::exitLock
Referenced by Close, ThreadPlay.
ThreadCondition mutabor::CommonFileInputDevice::waitCondition
Referenced by Close, Open, Play, ThreadPlay.
volatile mutint64 mutabor::CommonFileInputDevice::referenceTime
Fixed offset for the relative time the file returns.
Referenced by Play, Stop, ThreadPlay.
volatile mutint64 mutabor::CommonFileInputDevice::pauseTime
Referenced by Pause, Play, Stop.
timing_params mutabor::CommonFileInputDevice::timing
wxThreadKind mutabor::CommonFileInputDevice::threadkind
Referenced by Open, SetThreadKind.
virtual mutabor::CommonFileInputDevice::~CommonFileInputDevice()
References Close, mutabor::Device::isOpen, mutASSERT, timer.
void mutabor::CommonFileInputDevice::Save(tree_storage &config)
Save current device settings in a tree storage.
config (tree_storage) storage class, where the data will be saved.
References mutabor::tree_storage::GetPath, mutASSERT, mutabor::Device::Name, mutabor::tree_storage::Write.
void mutabor::CommonFileInputDevice::Load(tree_storage &config)
Load current device settings from a tree storage.
config (tree_storage) storage class, where the data will be loaded from.
References mutabor::tree_storage::GetPath, mutASSERT, mutabor::Device::Name, mutabor::tree_storage::Read.
bool mutabor::CommonFileInputDevice::Open()
References Close, mutabor::CurrentTime, DEBUGLOG, mutabor::DeviceStop, mutabor::DeviceTimingError, FileTimer, mutabor::safe_integer< T >::get, mutabor::Device::isOpen, mutabor::Device::Mode, mutASSERT, RequestPause, Stop, threadkind, threadsignal, timer, waitCondition, waitMutex.
Referenced by mutabor::InputGis::Open, SetName.
void mutabor::CommonFileInputDevice::Close()
References mutabor::CurrentTime, DEBUGLOG, exitLock, mutabor::safe_integer< T >::get, mutabor::Device::isOpen, mutASSERT, RequestExit, Stop, threadsignal, timer, waitCondition, waitMutex, mutabor::InputDeviceClass::wxTHREAD_WAIT_BLOCK.
Referenced by mutabor::InputGis::Close, Open, SetName, ~CommonFileInputDevice.
void mutabor::CommonFileInputDevice::Stop()
Stop playback or recording of the device.
References DEBUGLOG, mutabor::DeviceCompileError, mutabor::DevicePlay, mutabor::DeviceStop, mutabor::DeviceTimingError, lockMode, mutabor::Device::Mode, Pause, pauseTime, referenceTime, RequestPanic, ResetTime, threadsignal.
Referenced by Close, exception_error, Open, mutabor::InputGis::Stop, ThreadPlay.
void mutabor::CommonFileInputDevice::Play()
Command the device to play music.
This function starts playing the music of the device at the curren position.
References mutabor::CurrentTime, DEBUGLOG, mutabor::DeviceCompileError, mutabor::DeviceInitializing, mutabor::DeviceKilled, mutabor::DevicePause, mutabor::DevicePlay, mutabor::DeviceStop, mutabor::DeviceTimingError, mutabor::DeviceUnregistered, mutabor::safe_integer< T >::get, mutabor::CurrentTimer::Get, mutabor::CurrentTimer::isRealtime, lockMode, mutabor::Device::Mode, mutASSERT, pauseTime, referenceTime, RequestPause, threadsignal, timer, waitCondition, waitMutex.
Referenced by Pause, myDevice::Play.
void mutabor::CommonFileInputDevice::Pause()
Pause playback or recording of the device.
References mutabor::CurrentTime, mutabor::DeviceCompileError, mutabor::DevicePause, mutabor::DevicePlay, mutabor::DeviceStop, mutabor::DeviceTimingError, mutabor::CurrentTimer::Get, mutabor::CurrentTimer::isRealtime, mutabor::Device::Mode, mutASSERT, pauseTime, Play, RequestPause, threadsignal.
Referenced by myDevice::Pause, Stop.
virtual void mutabor::CommonFileInputDevice::doResetTime()
Reset the timing and music data after stopping the device.
Referenced by mutabor::InputGis::doResetTime, ThreadPlay.
virtual void mutabor::CommonFileInputDevice::threadCleanUp()
Do some cleanup if necessary after stopping the thread.
Referenced by ThreadPlay.
virtual void mutabor::CommonFileInputDevice::SetName(const std::string &s)
References Close, mutabor::Device::IsOpen, mutabor::Device::Name, Open.
virtual bool mutabor::CommonFileInputDevice::SetThreadKind(wxThreadKind k)
Sets the thread kind for the next thread that is being generated.
If we have already a timer thread then the thread kind will not be changed, but the value is stored for the next generated thread. k thread kind to be saved true if everything is ok. false if there is a thread that could not be updated.
References threadkind, timer.
wxThread::ExitCode mutabor::CommonFileInputDevice::exception_error()
Issue an error message and stop the device.
Error exit code.
References _mut, mutabor::DeviceKilled, mutabor::Device::Mode, print_stacktrace, mutabor::hidden::runtime_error, mutabor::Device::runtime_error, Stop, mutabor::str.
wxThread::ExitCode mutabor::CommonFileInputDevice::ThreadPlay(FileTimer *timer)
Play the file.
This function is called from the thread object. It plays the file using sleep operations.
References mutabor::CurrentTime, DEBUGLOG, DEFAULT_PANIC, mutabor::DeviceCompileError, mutabor::DeviceInitializing, mutabor::DevicePause, mutabor::DevicePlay, mutabor::DeviceStop, mutabor::DeviceTimingError, doResetTime, exitLock, mutabor::safe_integer< T >::get, mutabor::CurrentTimer::Get, mutabor::InputDeviceClass::GetNO_DELTA, mutabor::InputDeviceClass::IsDelta, lockMode, mutabor::Device::Mode, mutASSERT, mutint64, mutabor::InputDeviceClass::Panic, mutabor::InputDeviceClass::PrepareNextEvent, referenceTime, RequestExit, RequestPanic, RequestPause, ResetTime, mutabor::InputDeviceClass::ResumeKeys, mutabor::InputDeviceClass::SilenceKeys, mutabor::CurrentTimerBase::Sleep, Stop, threadCleanUp, threadsignal, timer, waitCondition, waitMutex.
wxThread::ExitCode mutabor::CommonFileInputDevice::WaitForDeviceFinish()
References DEBUGLOG, mutabor::DeviceCompileError, mutabor::DevicePause, mutabor::DevicePlay, mutabor::DeviceStop, mutabor::DeviceTimingError, mutabor::safe_integer< T >::get, mutabor::Device::Mode, mutASSERT, threadsignal, timer, waitMutex.
Referenced by CommonFileDeviceTest::testTimer.
virtual std::string mutabor::CommonFileInputDevice::GetTypeName() const
References _mutN.
mutabor::CommonFileInputDevice::operator std::string() const
References mutabor::str.
mutabor::CommonFileInputDevice::CommonFileInputDevice()
mutabor::CommonFileInputDevice::CommonFileInputDevice(std::string name, MutaborModeType mode, int id)