mutabor_backtrace
typedef std::vector<uintptr_t> mutabor_backtrace::base
bool mutabor_backtrace::print
Referenced by set_print, ~mutabor_backtrace.
bool mutabor_backtrace::global_print
Referenced by get_global_print, set_global_print, ~mutabor_backtrace.
struct backtrace_state * mutabor_backtrace::state
Referenced by mutabor_backtrace, ~mutabor_backtrace.
mutabor_backtrace::mutabor_backtrace(int omit_count=0)
References mutabor_backtrace_error_callback, mutabor_save_backtrace_callback, state.
mutabor_backtrace::~mutabor_backtrace()
References global_print, mutabor_backtrace_error_callback, mutabor_backtrace_print_callback, print, state.
void mutabor_backtrace::set_print(bool p=true)
References print.
Referenced by boost::mutabor::intrusive_ptr< T >::operator=, boost::mutabor::intrusive_ptr< T >::print_backtrace, boost::mutabor::intrusive_ptr< T >::~intrusive_ptr.
static void mutabor_backtrace::set_global_print(bool p=true)
References global_print.
Referenced by IMPLEMENT_APP.
static bool mutabor_backtrace::get_global_print()
References global_print.
Referenced by boost::mutabor::intrusive_ptr< T >::operator=.