frac
mutint64 frac::n
Referenced by frac, main, numerator, operator bool, operator!, operator!=, operator*, operator*=, operator+, operator+=, operator-, operator-=, operator/, operator/=, operator<, operator<=, operator=, operator==, operator>, operator>=.
mutint64 frac::d
Referenced by denominator, frac, main, operator!=, operator*, operator*=, operator+, operator+=, operator-, operator-=, operator/, operator/=, operator<, operator<=, operator=, operator==, operator>, operator>=.
frac::frac()
References d, n.
Referenced by operator*, operator+, operator-, operator/.
frac::frac(mutint64 integerval)
References d, n.
frac::frac(mutint64 numerator, mutint64 denominator)
References d, denominator, n, numerator.
mutint64 frac::numerator() const
References n.
Referenced by frac, GisReadArtHead::Read, mutabor::InputGis::ReadOn.
mutint64 frac::denominator() const
References d.
Referenced by frac, GisReadArtHead::Read, mutabor::InputGis::ReadOn.
frac & frac::operator=(const frac &f)
References d, n.
frac & frac::operator+=(const frac &f)
References d, gcd, n.
frac & frac::operator-=(const frac &f)
References d, gcd, n.
frac & frac::operator*=(const frac &f)
References d, gcd, n.
frac & frac::operator/=(const frac &f)
References d, gcd, n.
frac frac::operator+(const frac s)
References d, frac, gcd, n.
frac frac::operator-(const frac s)
References d, frac, gcd, n.
frac frac::operator*(const frac s)
References d, frac, gcd, n.
frac frac::operator/(const frac s)
References d, frac, gcd, n.
int frac::operator<(const frac &f)
References d, n.
int frac::operator<=(const frac &f)
References d, n.
int frac::operator==(const frac &f)
References d, n.
int frac::operator!=(const frac &f)
References d, n.
int frac::operator>=(const frac &f)
References d, n.
int frac::operator>(const frac &f)
References d, n.
frac::operator bool()
References n.
bool frac::operator!()
References n.
frac & frac::operator=(const int &i)
References d, n.
mutint64 frac::gcd(mutint64 a, mutint64 b)
References absLong.
Referenced by operator*, operator*=, operator+, operator+=, operator-, operator-=, operator/, operator/=.
STD_PRE::ostream& operator<<(STD_PRE::ostream &os, const frac f)