git:
  depth: 1
branches:
  except:
  - "/(?i:appveyor)/"
language: c++
sudo: required
group: travis_latest
compiler:
- gcc
  #- clang
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "MTAL4H3DcAH6be6NVdpj08LAKGtWh1YZXVN7f5i1rm34vF+YlurxiV7z7gGK9yzjmGFobqyF4CrDbZwzPtJKeV/8V+7OqgJsJ2SIPZlU3DnPt82PODK5ArrKXaR7qyeRUrJk1/kLlKqoDaV2TRdc+EDtCzHTi2oPCYejc3EbPgjBlM9eTs7WZCL1IzIVLqGFHr0sNHpQ5dYSXcg38V7/GeqySraTiBZ1WbJqUb23Js80oRIgN6dLDL1EV2/Sr7iqoFjPIsKpKWSSuo+HvJwYF36U/dmcG/nC78wO/pqBPumzyifdeH3Ii+nQiAQEfhYKYApuarUel5eR5vRVczC7CKJ+PSogi0l3XNzVz9fGFJUu0aYKwHv96PB4lvfwq/iXjZb86rXDqwqiCXUPMMth929SsQyVrbvdltNXs6ejuiSaQqVijUVlGMQT2ny94j0EFjyqZ4HuM9lsz4ouR00w/sfJc6Ji6WwEqsQnvlIPDJCqeBvXbM+gPhK7O2zu9PwHRuBuoORDVlo5u1HIpcTqJNSIvuY4d4sC6bbDoZLUBAum3e4oPtaO26xxyCc9gMkNaBWIe2OG9Iub16FEeFStsspw2el31qoRvZyqRI3iEjZqDbqEnpj451H2w+lUSbEO+6+buiYcRV/E1g6rls0Rfvl0UawmY8safE2mlx0UNiw="

addons:
  apt:
    sources:
    - sourceline: ppa:keinstein-junior/travis-ci-upgrades
    - sourceline: ppa:nschloe/debhelper-backports
    packages:
    - devscripts
    - pbuilder
    - fakeroot
    - debhelper
    - autoconf
    - libtool
    - autopoint
    - gettext
    - automake
    - flex
    - bison
    - libwxgtk3.0-dev
    - libboost-dev
    - libboost-thread-dev
    - libboost-locale-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libasound-dev
    - libcppunit-dev
    - doxygen
    - tex4ht
    - xvfb
  coverity_scan:
    project:
      name: "keinstein/mutabor"
      description: "Perform dynamic tunings in realtime music or use them for procesing MIDI files"
    notification_email: keinstein_junior@gmx.net
    build_command_prepend: "(cd lib/rtmidi && autoreconf -i -f) && autoreconf -i -f && ./configure"
    build_command: "make && make check"
    branch_pattern: coverity_scan
before_install:
- mkdir -p config lib/rtmidi/config
- touch config/config.rpath lib/rtmidi/config/config.rpath
- eval "${MATRIX_EVAL}"
- pwd
- ls
- |
  if test "$TRAVIS_OS_NAME" = osx
  then
    brew update 
  fi
- if test "$TRAVIS_OS_NAME" = osx ; then brew pin postgis ; fi
- if test "$TRAVIS_OS_NAME" = osx ; then brew upgrade boost automake ; fi
- if test "$TRAVIS_OS_NAME" = osx ; then rm -rf /usr/local/include/c++ ; fi
- if test "$TRAVIS_OS_NAME" = osx ; then brew install $EXTRA_BREW wxmac gettext flex bison libtool jack ; fi
- if test "$TRAVIS_OS_NAME" = osx ; then brew link --force $EXTRA_BREW boost wxmac gettext flex bison libtool autoconf jack ; fi
- if test "$TRAVIS_OS_NAME" = linux ; then eval TEST_RUNNER=xvfb-run ; else eval TEST_RUNNER= ; fi
- which gettextize
- gettextize --version
- which autopoint
- autopoint --version
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
- "(cd lib/rtmidi && autoreconf -i -f)"
- autoreconf -i -f && ./configure

