git:
  depth: 1
branches:
  except:
    - /(?i:appveyor)/
language: c++
sudo: required
group: travis_latest
compiler:
  - gcc
  - clang
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && EXTRA_BREW= && DYLD_LIBRARY_PATH=":/usr/local/opt/wxmac/lib/:/usr/local/Cellar/jack/0.125.0_2/lib:-L/usr/local/lib && MUTABOR_DEPLOY=true"

    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++ && EXTRA_BREW=gcc && DYLD_LIBRARY_PATH=":/usr/local/opt/wxmac/lib/:/usr/local/Cellar/jack/0.125.0_2/lib:-L/usr/local/lib && MUTABOR_DEPLOY=true"


addons:
  apt:
    sources:
    - sourceline: ppa:keinstein-junior/travis-ci-upgrades
    - sourceline: ppa:nschloe/debhelper-backports
    packages:
    - devscripts
    - pbuilder
    - fakeroot
    - debhelper
    - autoconf
    - libtool
    - autopoint
    - gettext
    - automake
    - flex
    - bison
    - libwxgtk3.0-dev
    - libboost-dev
    - libboost-thread-dev
    - libboost-locale-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libasound-dev
    - libcppunit-dev
    - doxygen
    - tex4ht
    - xvfb


before_install:
    - mkdir -p config lib/rtmidi/config
    - touch config/config.rpath lib/rtmidi/config/config.rpath
    - eval "${MATRIX_EVAL}"
    - pwd
    - ls
    - if test "$TRAVIS_OS_NAME" = osx ; then  brew update ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then brew upgrade boost automake ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then rm -rf /usr/local/include/c++ ; fi # fix broken gcc installation
    - if test "$TRAVIS_OS_NAME" = osx ; then brew install $EXTRA_BREW wxmac gettext flex bison libtool jack ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then brew link --force $EXTRA_BREW boost wxmac gettext flex bison libtool autoconf jack ; fi
    - if test "$TRAVIS_OS_NAME" = linux ; then eval TEST_RUNNER=xvfb-run ; else eval TEST_RUNNER= ; fi
    - which gettextize
    - gettextize --version
    - which autopoint
    - autopoint --version

script:
    - (cd lib/rtmidi && autoreconf -i -f)
    - autoreconf -i -f && ./configure && make -j4 && $TEST_RUNNER make check -j4
    - cat test-suite.log
    - $TEST_RUNNER make V=1 distcheck
    - cat test-suite.log
    - if cat */_build/test-suite.log ; then true ; else true; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then make install &&  make V=1 dmg ; fi ;
    - if test "$TRAVIS_OS_NAME" = linux && false ; then debuild ; fi ;
    - git clone --depth=1 --branch=master https://${GITHUB_TOKEN}@github.com/keinstein/mutabor-nightlies.git public
    - mkdir -p "public/docs/download/${CXX}_MAC_x86_64_${TRAVIS_TAG}"
    - if test "$TRAVIS_OS_NAME" = osx ; then mv *.dmg "public/docs/download/${CXX}_MAC_x86_64_${TRAVIS_TAG}" ; fi ;
    - if test "$TRAVIS_OS_NAME" = osx ; then cd public && git add "docs/download/${CXX}_MAC_x86_64_${TRAVIS_TAG}/*" && git commit -m "Automatic publishing via Travis-CI" ; fi ;
    - if test "$TRAVIS_OS_NAME" = osx ; then until git push origin master ;  do sleep 60 ; git pull origin ; done ; fi ;
    - if test "$TRAVIS_OS_NAME" = osx ; then cd .. ; fi

deploy:
- provider: releases
  api_key:
    secure: zoo9cYmsDytF4QqiOVMZC0OttLyln+OtkYZ6Oj2qERS8FWqYboVxtQs1IPBq30+r9pkCSyWdD8GOKzjTd/Bzvh/289rbU0WHaafsJnfnSsyZtpJudtMn4s6DMekbZECMrcCfBOuZnUG6uqp2ywGulpJdPCh73UnbqEwq9lluT+IDXgouX+utGPgToXhEc+OZWh1pdQMxM+6VmfUBJsUatrfOnD20TCVKcQwlf/OcUkhmLZspOjCgrTBoVUyNJACsSiEKN41Bx7mXvRjm7+PiFZ+WVTamIoL/i37bSzpAjlYLUWjdS7yqT3BzQf75ABFwTKotB5JLn3Q+JrUTJYyKDvd5iryxBISVtjcdP+ECeZP/j8pHKQmWPtBffpNF1FlUhGr/ry1vn7qMOrnLyumdjWgLuIDCeZcU7avu/rh38l3zTCx7G8OWa1HEJ2TX6GdJi02x/PKmgeO+vmJtSKjp+IXt8ULy5QzE6fz3WNkHX4b/t0IsOmzyJCnlflEcQiirfn0XdAN9a52pobkuD/L401odQrLzTJ/WwXuJcrrgmHZIqay5kbOkTtY7XrawZsMk6Xx1W0rNoUeDDMUi5wJvhRkuusUnIkSiRv1oPci6FEFkYAR4PTS6otYlL6uIRnpcvzYFwSGwV7Rwubw142TQ+DR24T/ahxKsAA2lhJgq0s4=
  skip_cleanup: true
  file_glob: true
  file: public/docs/download/${CXX}_MAC_x86_64_${TRAVIS_TAG}/*
  verbose: true
  on:
    condition: $MUTABOR_DEPLOY = true
    repo: keinstein/mutabor
    tags: true
    branch: master
- provider: pages
  skip_cleanup: true
  local_dir: public
  repo: keinstein/mutabor-nightlies
  target_branch: master
  keep_history: true
  github_token: $GITHUB_TOKEN
  verbose: true
  on:
    condition: $MUTABOR_DEPLOY = true
    repo: keinstein/mutabor
    branch: travis-github-provider
