git:
  depth: 3
language: c++
sudo: required
group: travis_latest
compiler:
  - gcc
  - clang
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && EXTRA_BREW= && DYLD_LIBRARY_PATH=":/usr/local/opt/wxmac/lib/:/usr/local/Cellar/jack/0.125.0_2/lib:-L/usr/local/lib"

    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++ && EXTRA_BREW=gcc && DYLD_LIBRARY_PATH=":/usr/local/opt/wxmac/lib/:/usr/local/Cellar/jack/0.125.0_2/lib:-L/usr/local/lib"


addons:
  apt:
    sources:
    - sourceline: ppa:cz.nic-labs/knot-dns
    packages:
    - devscripts
    - pbuilder
    - fakeroot
    - debhelper
    - autoconf
    - libtool
    - autopoint
    - gettext
    - automake
    - flex
    - bison
    - libwxgtk3.0-dev
    - libboost-dev
    - libboost-thread-dev
    - libboost-locale-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libasound-dev
    - libcppunit-dev
    - doxygen
    - tex4ht
    - xvfb


before_install:
    - mkdir -p config lib/rtmidi/config
    - touch config/config.rpath lib/rtmidi/config/config.rpath
    - eval "${MATRIX_EVAL}"
    - pwd
    - ls
    - if test "$TRAVIS_OS_NAME" = osx ; then  brew update ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then brew upgrade boost ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then rm -rf /usr/local/include/c++ ; fi # fix broken gcc installation
    - if test "$TRAVIS_OS_NAME" = osx ; then brew install $EXTRA_BREW wxmac gettext flex bison libtool autoconf jack  ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then brew link --force $EXTRA_BREW boost wxmac gettext flex bison libtool autoconf jack ; fi
    - if test "$TRAVIS_OS_NAME" = linux ; then eval TEST_RUNNER=xvfb-run ; else eval TEST_RUNNER= ; fi
    - which gettextize
    - gettextize --version
    - which autopoint
    - autopoint --version

script:
    - ls -l '/usr/local/opt' || true
    - if test "$TRAVIS_OS_NAME" = osx ; then ls -l /usr/local/opt/wxmac/lib ; fi ;
    - if test "$TRAVIS_OS_NAME" = osx ; then ls -l /usr/local/opt/boost/lib ; fi ;
    - if test "$TRAVIS_OS_NAME" = osx ; then echo "DYLD_LIBRARY_PATH = $DYLD_LIBRARY_PATH" ; fi ;
    - if test "$TRAVIS_OS_NAME" = osx ; then echo "DYLD_FALLBACK_FRAMEWORK_PATH = $DYLD_FALLBACK_FRAMEWORK_PATH" ; fi ;
    - ls -l '/usr/local/opt/wxmac' || true
    - ls -l '/usr/local/opt/wxmac/lib' || true
    - ls -l /usr/local/opt/wxmac/lib/libwx* || true
    - (cd lib/rtmidi && autoreconf -i -f) ;
    - autoreconf -i -f && ./configure && make printvariables && make && $TEST_RUNNER make check
    - cat test-suite.log 
    - $TEST_RUNNER make distcheck
    - cat test-suite.log 
    - if test "$TRAVIS_OS_NAME" = osx ; then brew ls --verbose boost wxmac ; fi ;
    - if test "$TRAVIS_OS_NAME" = osx ; then make install &&  make V=1 dmg ; fi ;
    - if test "$TRAVIS_OS_NAME" = linux && false ; then debuild ; fi ;
