sudo: required
language: generic

services:
  - docker

script:
    - wget -O- http://travis.debian.net/script.sh | sh -
    - ls ..

deploy:
- provider: releases
  api_key:
    secure: r/clPkRvXDVzyqfD6+fhktW+DIDUPimEwfK1Mxrh3obtJUEbB0pQnGilhjMuTyIxHtl8yRf3rMvX0hIaqBSFOUi6reHC5UoZUfc/AGE0DYph7VQY0wLBx/JGO5CVHsAeMvmPvLXiIv0yTEw7speZkakeKyD6nsgKVLj15jfGcGjyhNE5f1ZpoetK8/qO0ZNf9WFe0KM7DPjqGmIeWJ1z6G/hw3bXlgqOhbbq0qOCS+pfG8dZmu83lA6ci9KIqTOJYchcV9ljQ9DubYxEsBSt3dAo2FaVjJICN0XQ3SdrzLfllbSiylcxYrOtBZg9blXhmPpWpBRYW80zON9JRaZTklv65FpPyZ4wJM//pu4zeFGTzBTy4q6ZTXdNSUWi2mZgl7KA9ijqHrdiAzGc2ti/Q+irsDfdpEDOAXKhtKzMSQwka1syLjJTFc4wYEOiiHvpxzp0plKtQ44TbiOJfxkswaJAvXSOgRrfpLw2Ot7dDzsVEE/r9+Q7ntU0k5K9NbbXXb9njy8mhG18lMm+gyvK+AdFgxK4iXlpO6hJ605JgA+ioDQbqkxwzJ4SGecw1nV1x1b2sfaUa1MuXA0/XImYG0CZrl9rmhx2pgyIzI5B0peQRg/aot8VdJTLyiIw03yR0N6ogsTeg4TYKy5MLGL9RKPn+iPBgY4C0xXqtFZkkVU=
  skip_cleanup: true
  file_glob: true
  file:
    - ../*.deb
    - ../*.dsc
    - ../*.changes
  on:
    repo: keinstein/mutabor
    tags: true
