git:
  depth: 1
branches:
  except:
  - "/(?i:appveyor)/"
language: c++
sudo: required
group: travis_latest
compiler:
- gcc
  #- clang
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "npvMwqPINvv8ARh58fItW2U3AHshNQySSchKSyptMnyUNNz4tN6lUwI+mW/qC6Y8C39A53bn/KmBOG/ieGret//B4qklSqOoRkrXfDybzRAUEDcKCCwRt60vbr0560cgvBSD3dvGM3txH0Ov1eiiiYBkfodwyy091qpHZtuDuTLJ8BETF/nwdtUx8G7o9QzIyejiQ1xGwXsLrZgoffUrQDZCndOb7Z8gc3OQzIJxZHSIMlFMcvpei5YsbsbM191Q0EWdFRXra3QjhygHyeWh9/po0zOtQBKd/DMpArTBQDoXi/vtjocqUP4pnZhuegwTawigf7kG0ogGTKiA6v41LMjEzNmC944BJhzLBQ3EBYNjdICQ6oss3Uunm5RmBsJAsQfv/Y+pUOlD8hj3F90RjEj5VLI5rnf3g7h3zxMItD0kDHEaIDrOvEFdpYulhfIOJT2hstFLUFbZvb0RlACVFgbFSE/gfgEDXy2J5mJkm1UcKQRQ2SG3QVrg8uBnYJNlqxow+7a9tRySnSL23hZfSi19j3kRE2sp/USJKJ3NWzVpEo9zrXuxG9vhR/D/lWOzhUFIICxUxVFFzc0OEfG4UlJMGvGKtLxVZP83Le4sgSYI8Npsy+e53JMm0ymwOAwh3g1RSYux8FM49sHco0XZtzGe3T38LeY7Xyuvv5t2p2s="
addons:
  apt:
    sources:
    - sourceline: ppa:keinstein-junior/travis-ci-upgrades
    - sourceline: ppa:nschloe/debhelper-backports
    packages:
    - devscripts
    - pbuilder
    - fakeroot
    - debhelper
    - autoconf
    - libtool
    - autopoint
    - gettext
    - automake
    - flex
    - bison
    - libwxgtk3.0-dev
    - libboost-dev
    - libboost-thread-dev
    - libboost-locale-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libasound-dev
    - libcppunit-dev
    - doxygen
    - tex4ht
    - xvfb
  coverity_scan:
    project:
      name: "keinstein/mutabor"
      description: "Perform dynamic tunings in realtime music or use them for procesing MIDI files"
    notification_email: keinstein_junior@gmx.net
    build_command_prepend: "(cd lib/rtmidi && autoreconf -i -f) && autoreconf -i -f && ./configure"
    build_command: "make && make check"
    branch_pattern: coverity_scan
before_install:
- mkdir -p config lib/rtmidi/config
- touch config/config.rpath lib/rtmidi/config/config.rpath
- eval "${MATRIX_EVAL}"
- pwd
- ls
- if test "$TRAVIS_OS_NAME" = osx ; then  brew update ; fi
- if test "$TRAVIS_OS_NAME" = osx ; then brew pin postgis ; fi
- if test "$TRAVIS_OS_NAME" = osx ; then brew upgrade boost automake ; fi
- if test "$TRAVIS_OS_NAME" = osx ; then rm -rf /usr/local/include/c++ ; fi
- if test "$TRAVIS_OS_NAME" = osx ; then brew install $EXTRA_BREW wxmac gettext flex bison libtool jack ; fi
- if test "$TRAVIS_OS_NAME" = osx ; then brew link --force $EXTRA_BREW boost wxmac gettext flex bison libtool autoconf jack ; fi
- if test "$TRAVIS_OS_NAME" = linux ; then eval TEST_RUNNER=xvfb-run ; else eval TEST_RUNNER= ; fi
- which gettextize
- gettextize --version
- which autopoint
- autopoint --version
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

script:
- "(cd lib/rtmidi && autoreconf -i -f)"
- autoreconf -i -f && ./configure && make -j4 && $TEST_RUNNER make check -j4
- cat test-suite.log
- "$TEST_RUNNER make V=1 distcheck"
- cat test-suite.log
- if cat */_build/test-suite.log ; then true ; else true; fi
- if test "$TRAVIS_OS_NAME" = osx ; then make install &&  make V=1 dmg ; fi ;
- if test "$TRAVIS_OS_NAME" = linux && false ; then debuild ; fi ;
- git clone --depth=1 --branch=master https://${GITHUB_TOKEN}@github.com/keinstein/mutabor-nightlies.git public
- mkdir -p "public/docs/download/${CXX}_MAC_x86_64_${TRAVIS_TAG}"
- if test "$TRAVIS_OS_NAME" = osx ; then mv *.dmg "public/docs/download/${CXX}_MAC_x86_64_${TRAVIS_TAG}" ; fi ;
- if test "$TRAVIS_OS_NAME" = osx ; then cd public && git add "docs/download/${CXX}_MAC_x86_64_${TRAVIS_TAG}/*" && git commit -m "Automatic publishing via Travis-CI" ; fi ;
- #if test "$TRAVIS_OS_NAME" = osx ; then until git push origin master ;  do sleep 60 ; git pull origin ; done ; fi ;
- if test "$TRAVIS_OS_NAME" = osx ; then cd .. ; fi

deploy:
- provider: releases
  api_key:
    secure: r/clPkRvXDVzyqfD6+fhktW+DIDUPimEwfK1Mxrh3obtJUEbB0pQnGilhjMuTyIxHtl8yRf3rMvX0hIaqBSFOUi6reHC5UoZUfc/AGE0DYph7VQY0wLBx/JGO5CVHsAeMvmPvLXiIv0yTEw7speZkakeKyD6nsgKVLj15jfGcGjyhNE5f1ZpoetK8/qO0ZNf9WFe0KM7DPjqGmIeWJ1z6G/hw3bXlgqOhbbq0qOCS+pfG8dZmu83lA6ci9KIqTOJYchcV9ljQ9DubYxEsBSt3dAo2FaVjJICN0XQ3SdrzLfllbSiylcxYrOtBZg9blXhmPpWpBRYW80zON9JRaZTklv65FpPyZ4wJM//pu4zeFGTzBTy4q6ZTXdNSUWi2mZgl7KA9ijqHrdiAzGc2ti/Q+irsDfdpEDOAXKhtKzMSQwka1syLjJTFc4wYEOiiHvpxzp0plKtQ44TbiOJfxkswaJAvXSOgRrfpLw2Ot7dDzsVEE/r9+Q7ntU0k5K9NbbXXb9njy8mhG18lMm+gyvK+AdFgxK4iXlpO6hJ605JgA+ioDQbqkxwzJ4SGecw1nV1x1b2sfaUa1MuXA0/XImYG0CZrl9rmhx2pgyIzI5B0peQRg/aot8VdJTLyiIw03yR0N6ogsTeg4TYKy5MLGL9RKPn+iPBgY4C0xXqtFZkkVU=
  skip_cleanup: true
  file_glob: true
  file: public/docs/download/${CXX}_MAC_x86_64_${TRAVIS_TAG}/*
  on:
    condition: $MUTABOR_DEPLOY = true
    repo: keinstein/mutabor
    tags: true
    branch: master
- provider: pages
  skip_cleanup: true
  local_dir: public
  repo: keinstein/mutabor-nightlies
  target_branch: master
  keep_history: true
  github_token: $GITHUB_TOKEN
  verbose: true
  on:
    condition: $MUTABOR_DEPLOY = true
    repo: keinstein/mutabor
    branch: travis-github-provider
