sudo: required
language: generic

env:
    - TRAVIS_DEBIAN_DERIVATIVE=ubuntu
    - TRAVIS_DEBIAN_DISTRIBUTION=bionic

services:
  - docker

script:
    - wget -O- http://travis.debian.net/script.sh | sh -
