git:
  depth: 3
language: c++
sudo: required
group: travis_latest
compiler:
  - gcc
  - clang
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && EXTRA_BREW= "

    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++ && EXTRA_BREW=gcc "


addons:
  apt:
    packages:
    - devscripts
    - pbuilder
    - autoconf
    - libtool
    - autopoint
    - automake
    - flex
    - bison
    - libwxgtk3.0-dev
    - libboost-dev
    - libboost-thread-dev
    - libboost-locale-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libasound-dev
    - libcppunit-dev
    - doxygen
    - xvfb


before_install:
    - eval "${MATRIX_EVAL}"
    - pwd
    - ls
    - if test "$TRAVIS_OS_NAME" = linux ; then sudo apt-get -qq update ;  yes | sudo /usr/lib/pbuilder/pbuilder-satisfydepends ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then  brew update ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then brew upgrade boost ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then rm -rf /usr/local/include/c++ ; fi # fix broken gcc installation
    - if test "$TRAVIS_OS_NAME" = osx ; then brew install $EXTRA_BREW wxmac gettext flex bison libtool autoconf jack  ; fi
    - if test "$TRAVIS_OS_NAME" = osx ; then brew link --force $EXTRA_BREW wxmac gettext flex bison libtool autoconf jack ; fi
    - if test "$TRAVIS_OS_NAME" = linux ; then eval TEST_RUNNER=xvfb-run ; else eval TEST_RUNNER= ; fi

script:
  (cd lib/rtmidi && echo | gettextize -f && autoreconf -i -f) ; 
  echo | gettextize -f && autoreconf -i -f && ./configure && make -j4 && $TEST_RUNNER make check -j4 || (cat test-suite.log ; exit 1) || $TEST_RUNNER make check || (cat test-suite.log ; exit 1) || exit ;
  pwd ; ls ; 
  if test "$TRAVIS_OS_NAME" = osx ; then make dmg || exit; fi ;
  if test "$TRAVIS_OS_NAME" = linux ; then debuild || exit; fi ;
  pwd ; ls ;
