git:
  depth: 3
language: c++
group: travis_latest
compiler:
  - gcc
  - clang
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    
install:
  - if test  "$TRAVIS_OS_NAME" = osx ; then  brew update ; fi
  - if test "$TRAVIS_OS_NAME" = osx ; then brew upgrade boost ; fi
  - if test "$TRAVIS_OS_NAME" = osx ; then rm -rf /usr/local/include/c++ ; fi # fix broken gcc installation
  - if test "$TRAVIS_OS_NAME" = osx ; then brew install gcc wxmac gettext flex bison libtool autoconf ; fi

addons:
  apt:
    packages:
    - autoconf
    - libtool
    - autopoint
    - automake
    - flex
    - bison
    - libwxgtk3.0-dev
    - libboost-dev
    - libboost-thread-dev
    - libboost-locale-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libasound-dev
    - libcppunit-dev
    - doxygen
    
  
script:
  autoreconf -i -f && ./configure && make && make check
