libcppunit-devgit:
  depth: 3
language: c++
compiler:
  - gcc
  - clang
script:
  autoreconf -i -f && ./configure --with-boost-libdir=/usr/lib && make && make check
matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install wxmac autopoint && CC=gcc-4.9 && CXX=g++-4.9"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc wxmac autopoint && CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

addons:
  apt:
    packages:
    - libwxgtk3.0-dev
    - libboost-dev
    - flex
    - bison
    - automake
    - libcppunit-dev
    - autoconf
    - libtool
    - autopoint
    - doxygen
    - libasound-dev
    
  
