environment:
  matrix:
    ###
    - NAME: x86_64 check
      TOOLCHAIN: "default"
      MINGW_ARCH: x86_64
      MINGW_ROOT: c:\msys64\mingw64
      CONFIGURE_OPTIONS: --disable-debug --disable-silent-rules --disable-shared
      _CC: MINGW
      BOOST_LIBS: /c/msys64/mingw64/lib
      BOOST_INCLUDES: /c/msys64/mingw64/includes/boost
      TEST_COMMAND: make -j2 check

    - NAME: x86_64 nsis
      TOOLCHAIN: "default"
      MINGW_ARCH: x86_64
      MINGW_ROOT: c:\msys64\mingw64
      CONFIGURE_OPTIONS: --disable-debug --disable-silent-rules --disable-shared
      _CC: MINGW
      BOOST_LIBS: /c/msys64/mingw64/lib
      BOOST_INCLUDES: /c/msys64/mingw64/includes/boost
      TEST_COMMAND: make -j2 nsis
      MUTABOR_DEPLOY: true
      GITHUB_TOKEN:
        secure: CBpAyIWs05AwGPigYDbYgEzBNV3jhXm6rvoBA+GoFXB5CocdOAzen2ceL906o0EM


    - NAME: x86_64 static distcheck
      TOOLCHAIN: "default"
      MINGW_ARCH: x86_64
      MINGW_ROOT: c:\msys64\mingw64
      CONFIGURE_OPTINOS: --enable-debug --disable-silent-rules --disable-shared
      _CC: MINGW
      BOOST_LIBS: /c/msys64/mingw64/lib
      BOOST_INCLUDES: /c/msys64/mingw64/includes/boost
      TEST_COMMAND: make -j2 distcheck

    - NAME: x86_64 shared distcheck
      TOOLCHAIN: "default"
      MINGW_ARCH: x86_64
      MINGW_ROOT: c:\msys64\mingw64
      CONFIGURE_OPTINOS: --enable-debug --disable-silent-rules --disable-static --enable-shared
      _CC: MINGW
      BOOST_LIBS: /c/msys64/mingw64/lib
      BOOST_INCLUDES: /c/msys64/mingw64/includes/boost
      TEST_COMMAND: make -j2 distcheck

    - NAME: i686 check
      TOOLCHAIN: "default"
      MINGW_ARCH: i686
      MINGW_ROOT: c:\msys64\mingw32
      CONFIGURE_OPTIONS: --disable-debug --disable-silent-rules --disable-shared
      _CC: MINGW
      BOOST_LIBS: /c/msys64/mingw32/lib
      BOOST_INCLUDES: /c/msys64/mingw32/includes/boost
      TEST_COMMAND: make -j2 check 

    - NAME: i686 nsis
      TOOLCHAIN: "default"
      MINGW_ARCH: i686
      MINGW_ROOT: c:\msys64\mingw32
      CONFIGURE_OPTIONS: --disable-debug --disable-silent-rules --disable-shared
      _CC: MINGW
      BOOST_LIBS: /c/msys64/mingw32/lib
      BOOST_INCLUDES: /c/msys64/mingw32/includes/boost
      TEST_COMMAND: make -j2 nsis
      MUTABOR_DEPLOY: true
      GITHUB_TOKEN:
        secure: CBpAyIWs05AwGPigYDbYgEzBNV3jhXm6rvoBA+GoFXB5CocdOAzen2ceL906o0EM

    - NAME: i686 static distcheck
      TOOLCHAIN: "default"
      MINGW_ARCH: i686
      MINGW_ROOT: c:\msys64\mingw32
      CONFIGURE_OPTINOS: --enable-debug --disable-silent-rules --disable-shared
      _CC: MINGW
      BOOST_LIBS: /c/msys64/mingw32/lib
      BOOST_INCLUDES: /c/msys64/mingw32/includes/boost
      TEST_COMMAND: make -j2 distcheck

    - NAME: i686 shared distcheck
      TOOLCHAIN: "default"
      MINGW_ARCH: i686
      MINGW_ROOT: c:\msys64\mingw32
      CONFIGURE_OPTINOS: --enable-debug --disable-silent-rules --disable-static --enable-shared
      _CC: MINGW
      BOOST_LIBS: /c/msys64/mingw32/lib
      BOOST_INCLUDES: /c/msys64/mingw32/includes/boost
      TEST_COMMAND: make -j2 distcheck

# example see: https://github.com/wang-bin/avbuild/blob/master/appveyor.yml
init:
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - set MSYS2_PATH_TYPE=inherit
  - set MSYS2_DIR=C:\msys64

install:
# can not starts with %
#  - git submodule update --init
  - if /i %_CC%==MinGW (
      C:\msys64\usr\bin\pacman -Syyuu --noconfirm &&
      C:\msys64\usr\bin\pacman -Suu --noconfirm   &&
      C:\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-%MINGW_ARCH%-gcc &&
      C:\msys64\usr\bin\pacman -Sc --noconfirm
    )
  - C:\msys64\usr\bin\pacman -Ss --noconfirm boost
  - C:\msys64\usr\bin\pacman -Ss --noconfirm nsis
  - C:\msys64\usr\bin\pacman -Ss --noconfirm zip
  - C:\msys64\usr\bin\pacman -Ss --noconfirm autoconf
  - C:\msys64\usr\bin\pacman -Ss --noconfirm automake
  - C:\msys64\usr\bin\pacman -Ss --noconfirm libtool
#       C:\msys64\usr\bin\pacman -Ss --noconfirm gettext
#- C:\msys64\usr\bin\pacman -Ss --noconfirm jack
  - C:\msys64\usr\bin\pacman -Ss --noconfirm wxWidgets
  - C:\msys64\usr\bin\pacman -S --noconfirm --needed
      mingw-w64-%MINGW_ARCH%-boost autoconf mingw-w64-%MINGW_ARCH%-libtool automake1.15 mingw-w64-%MINGW_ARCH%-gettext mingw-w64-%MINGW_ARCH%-wxWidgets mingw-w64-%MINGW_ARCH%-nsis zip

build_script:
  - dir C:\
  - dir C:\msys64
  - dir C:\msys64\usr\bin
  - dir C:\msys64\opt
  - dir C:\msys64\mingw64
  - dir c:\msys64\mingw64\bin
  - dir C:\msys64\mingw64\x86_64-w64-mingw32
  - dir C:\msys64\mingw64\x86_64-w64-mingw32\bin
  - dir C:\mingw-w64
  - dir C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  - dir C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\opt\bin
  - SET PATH=%MINGW_ROOT%\bin;C:\mingw-w64\bin;C:\msys64\usr\bin;%PATH%	
  - echo "%PATH%"
  - bash -c "env"
  - bash -c pwd
  - bash -c "git submodule update --init --recursive"
  - bash -c "mkdir -p config"
  - bash -c "touch config/config.rpath"
  - bash -c "autoreconf -i -f"
  - bash -c "./configure %CONFIGURE_OPTIONS% --with-boost-libdir=$BOOST_LIBS || cat config.log"
  - bash -c "(%TEST_COMMAND%) || (cat test-suite.log ; false)"
  - bash -c "git config --global user.email "keinstein@users.sourceforge.net"
  - bash -c "git config --global user.name "Appveyor automatic deployment"
  - bash -c "if [[ $MUTABOR_DEPLOY =  true ]] ; then git clone  --depth=1 --branch=master https://${GITHUB_TOKEN}@github.com/keinstein/mutabor-nightlies public && mkdir -p public/docs/downloads/${CXX}_WIN_${MINGW_ARCH}_${APPVEYOR_REPO_TAG_NAME} && cp Mutabor*.exe *.zip public/docs/downloads/${CXX}_WIN_${MINGW_ARCH}_${APPVEYOR_REPO_TAG_NAME} && cd public && git add docs/downloads/${CXX}_WIN_${MINGW_ARCH}_${APPVEYOR_REPO_TAG_NAME} && git commit -m 'Automatic publishing from Appveyor' && until git push origin master ;  do sleep 60 ; git pull origin ; done; fi"

artifacts:
  - path: 'Mutabor*.exe'
    name: Releases
  - path: '*.zip'
    name: ZIPs
  - path: '*.log'
    name: logs

deploy:
  - provider: GitHub
    name: Releases
    description: Nightly build
    auth_token:
        secure: CBpAyIWs05AwGPigYDbYgEzBNV3jhXm6rvoBA+GoFXB5CocdOAzen2ceL906o0EM
    artifact: Releases,ZIPs
    force_update: true
    draft: false
    prerelease: false
    on:
        branch: master
        APPVEYOR_REPO_TAG: true
        MUTABOR_DEPLOY: true
