interval.c
adjazent
Eintrag der Adjazenzmatrix matrix.
a zeile der Matrix b Spalte der Matrix Eintrag der Matrix
Referenced by berechne_intervalle_absolut, test_zyklen.
struct intervall* list_of_intervalle
Wurzel der Intervallliste.
Referenced by mutabor_programm_einlesen.
int anzahl_intervalle
so viele Intervalle wurden gelesen
Referenced by berechne_intervalle_absolut, intervall_nummer, test_zyklen.
struct intervall** intervalle
Feld von Intervallen zum schnelleren Zugriff als ueber Listen
char* visited
Traversierungsmerker.
Referenced by berechne_intervalle_absolut, test_zyklen.
char* matrix
Adjazenzmatrix (auf sie darf nur ueber das folgende Makro zugegriffen werden !
Referenced by berechne_intervalle_absolut.
struct komplex_intervall* the_komplex_liste
Liste komplexer Intervalle.
Referenced by get_last_komplex_intervall.
void* MUTABOR_CLASS_FUNCTION(identifier, constructor)
References CHK_CLASS, MUT_CLASS, MUTABOR_CLASS_FUNCTION.
int MUTABOR_CLASS_FUNCTION(interval, compare)
Comparison between two objects.
Simple comparison by pointers.
References CHK_CLASS, MUT_CLASS, MUTABOR_FLOAT_FACTOR_COMPARE.
char* MUTABOR_CLASS_FUNCTION(interval, tostring)
Formats Class content as string.
Intented exspecially for debugging.
References CHK_CLASS, MUT_CLASS, MUT_VALUE, MUT_VIRTTABLE, name.
void MUTABOR_CLASS_FUNCTION(interval, set_factor)
References CHK_CLASS, MUT_VALUE.
struct intervall* get_intervall(char *name, struct intervall *liste)
Sucht ein Intervall aus einer Intervallliste.
name Name des gesuchten Intervalles liste Liste der Intervalle, in der das Intervall gesucht wird NULL falls Intervall nicht in liste Intervall sonst.
References get_intervall, intervall::name, intervall::next.
Referenced by check_komplex_intervall, get_intervall, get_komplex_faktor.
static double get_intervall_wert(char *name)
Sucht den Wert eines absoluten Intervalles aus der globalen Intervallliste.
Falls das erste gefundene Intervall nicht absolut ist, wird ein fataler Fehler ausgegeben. name Name des gesuchten Intervalles Frequenzverhältnis des Intervalles
References fatal_error, intervall_absolut, intervall::intervall_absolut, intervall_komplex, mutabor_debug_level, MUTABOR_ERROR_UNDEFINED_INTERVAL, intervall::name, intervall::next, intervall::u.
Referenced by get_wert_komplex_intervall.
double get_wert_komplex_intervall(struct komplex_intervall *intervall)
Berechnet den Wert eines komplexen Intervalles aus der globalen Intervallliste.
Falls ein Intervallwert nicht positiv ist, wird ein fataler Fehler ausgegeben. intervall Frequenzverhältnis des Intervalles
References komplex_intervall::faktor, fatal_error, get_intervall_wert, mutabor_debug_level, MUTABOR_ERROR_INVALID_INTERVAL_VALUE, name, komplex_intervall::name, intervall::next.
Referenced by berechne_intervall_endgueltig, berechne_ton_endgueltig, expandiere_tonsystem, expandiere_umstimmung, get_intervall_wert.
double get_komplex_faktor(struct komplex_intervall *lauf)
Berechnet den Intervall-Faktor eines komplexen Intervalles.
Bei Inkonsistenzen wird ein fataler Fehler ausgegeben. lauf Komplexes Intervall, das bei der Berechnung durchlaufen werden soll.
References komplex_intervall::faktor, fatal_error, get_intervall, intervall_absolut, komplex_intervall::name, intervall::next, intervall::u.
Referenced by expand_tonliste, get_komplex_faktor, get_komplex_frequenz.
int intervall_list_laenge(struct intervall *list)
Zählt die Einträge eine Liste von Intervallen.
list Liste der Intervalle Länge der Intervall-Liste Noch zu erledigenZählen in iterativer Form
References intervall_list_laenge, intervall::next.
Referenced by intervall_list_laenge, berechne_intervalle_absolut, mutabor::BoxClass::Compile.
static void belege_intervalle(struct intervall **intervalle, struct intervall *liste)
Belegt ein Feld von Zeigern auf Intervalle mit den Werten einer Intervallliste.
intervalle Feld, in das die Intervalle eingetragen werden. liste Liste mit den Intervallen, die einsortiert werden sollen. Noch zu erledigenZählen in iterativer Form
References intervall::next.
Referenced by berechne_intervalle_absolut.
static int intervall_nummer(char *name)
Sucht die Nummer eines Intervalles im globalen Intervall-Feld.
Wird das Intervall nicht gefunden, wird ein fataler Fehler ausgelöst. name Name des zu suchenden Intervalles. Laufende Nummer des Intervalls.
References anzahl_intervalle, fatal_error, mutabor_debug_level.
Referenced by berechne_intervall_endgueltig, berechne_intervalle_absolut.
static void test_zyklen(int startknoten)
Testet den Graphen der Intervalle auf Kreise.
startknoten Knoten, von dem an getestet werden soll. Noch zu erledigenKomplexität n!(?) reduzieren
References adjazent, anzahl_intervalle, fatal_error, name, visited.
Referenced by berechne_intervalle_absolut.
static void berechne_intervall_endgueltig(int k)
Berechnet für alle Intervalle die endgültigen Werte.
Wird ein nicht korrektes Intervall gefunden, wird ein fataler Fehler ausgelöst. k Nummer des aktuell zu bearbeitenden Intervalles.
References fatal_error, get_wert_komplex_intervall, intervall_absolut, intervall::intervall_absolut, intervall_komplex, intervall::intervall_komplex, intervall_nummer, intervall::intervall_typ, name, komplex_intervall::next, intervall::u.
Referenced by berechne_intervalle_absolut.
void berechne_intervalle_absolut(struct intervall *list_of_intervalle)
Berechnet aus einer Intervall-Liste ein Intervall-Feld mit absoluten Werten.
Dabei wird das Intervall-Feld aufgebaut, auf Kreisbezüge getestet und abschließend werden zusammengesetzte Intervalle zu absoluten Intervallen aufgelöst. list_of_intervalle Liste der Intervalle, die bearbeitet werden sollen. Fertige Intervalle in der Intervall-Liste list_of_intervalle.
References adjazent, anzahl_intervalle, belege_intervalle, berechne_intervall_endgueltig, fatal_error, intervall_absolut, intervall_komplex, intervall::intervall_komplex, intervall_list_laenge, intervall_nummer, matrix, mutabor_debug_level, name, komplex_intervall::next, test_zyklen, visited, xalloca, xde_alloca.
Referenced by mutabor_programm_einlesen.
void check_komplex_intervall(struct komplex_intervall *liste, char *konstrukt_name)
Sucht zusammengesetzte Intervalle in der globalen Intervallliste.
Ist ein Intervall nicht in der Intervallliste oder es wurde kein absolutes Intervall zurückgegeben, wird ein fataler Fehler ausgelöst. liste Liste der zu suchenden Intervalle. konstrukt_name Konstruktionsname für eventuelle Fehlermeldung.
References fatal_error, get_intervall, intervall_absolut, name, komplex_intervall::next.
Referenced by check_konsistenz, check_tonsystem_konsistenz, check_umstimmungs_konsistenz.
void init_komplex_ton_list(void)
Setzt Liste komplexer Intervalle auf NULL.
Die Liste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_new_faktor_anteil(double f, char *name)
Fügt ein Intervall ans Ende von the_komplex_liste an.
f Faktor des Intervalles. name Bezeichnung des Intervalles, das angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References komplex_intervall::faktor, mutabor_debug_level, name, komplex_intervall::next, xmalloc.
Referenced by switch, yyparse.
struct komplex_intervall* get_last_komplex_intervall(void)
Gibt Wurzelelement von the_komplex_liste zurück.
References the_komplex_liste.
Referenced by get_new_intervall_komplex, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_new_umstimm_expression_negative, get_new_umstimm_expression_positive, get_umstimmung_wiederholung_abs, get_umstimmung_wiederholung_abs_negative, get_umstimmung_wiederholung_rel_negative, get_umstimmung_wiederholung_rel_positive.
void get_new_intervall(char *name, double wert)
Einleseroutine fuer die Intervalle Es wird einfach eine Liste of Intervallen aufgebaut.
Das übergebene Intervall wird hinten angehängt. Taucht der Intervallname schon einmal auf, wird ein fataler Fehler ausgegeben. name Name des Intervalles wert Wert des Intervalles ( $\geq$ 0,001) Es wird immer die gesamte Liste durchsucht. Effektivität?
References fatal_error, intervall_absolut, name, intervall::next, intervall::u, xmalloc.
Referenced by mutabor_programm_einlesen, switch, yyparse.
void get_new_intervall_komplex(char *name)
Fügt ein komplexes Intervall ans Ende von list_of_intervalle an.
Taucht der Intervallname schon einmal auf, wird ein fataler Fehler ausgegeben. name Bezeichnung des Intervalles, das angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References fatal_error, get_last_komplex_intervall, intervall_komplex, name, intervall::next, intervall::u, xmalloc.
Referenced by switch, yyparse.