mutaborGUI::MidiFileInputFilterPanel
mutaborGUI::MidiFileInputFilterPanel::MidiFileInputFilterPanel(wxWindow *parent)
void mutaborGUI::MidiFileInputFilterPanel::SetFromChannel(int current, int min, int max)
TODO: set limits according to changes: min.max = max.value and max.min = min.value.
References MidiFileInputFilterPanelBase::from_channel.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileInputFilterPanel::GetFromChannel() const
References MidiFileInputFilterPanelBase::from_channel.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileInputFilterPanel::SetToChannel(int current, int min, int max)
References MidiFileInputFilterPanelBase::to_channel.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileInputFilterPanel::GetToChannel() const
References MidiFileInputFilterPanelBase::to_channel.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileInputFilterPanel::SetFromTrack(int current, int min, int max)
References MidiFileInputFilterPanelBase::from_track.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileInputFilterPanel::GetFromTrack() const
References MidiFileInputFilterPanelBase::from_track.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileInputFilterPanel::SetToTrack(int current, int min, int max)
References MidiFileInputFilterPanelBase::to_track.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileInputFilterPanel::GetToTrack() const
References MidiFileInputFilterPanelBase::to_track.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileInputFilterPanel::SetRouteType(mutabor::RouteType routetype)
References MidiFileInputFilterPanelBase::all_panel, MidiFileInputFilterPanelBase::channel_panel, MidiFileInputFilterPanelBase::else_panel, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, MidiFileInputFilterPanelBase::track_panel, MidiFileInputFilterPanelBase::type.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
mutabor::RouteType mutaborGUI::MidiFileInputFilterPanel::GetRouteType() const
References MidiFileInputFilterPanelBase::all_panel, MidiFileInputFilterPanelBase::channel_panel, MidiFileInputFilterPanelBase::else_panel, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, MidiFileInputFilterPanelBase::track_panel, MidiFileInputFilterPanelBase::type, UNREACHABLEC.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::ReadFilterPanel.