mutabor::CurrentTimerBase
struct timespec start mutabor::CurrentTimerBase::resolution
static void mutabor::CurrentTimerBase::Sleep(mutint64 time)
References DEBUGLOGTYPE.
Referenced by mutabor::watchdog< Box >::Entry, mutabor::CommonFileInputDevice::ThreadPlay.
void mutabor::CurrentTimerBase::Start(mutint64 t=0)
Referenced by mutabor::CurrentTimer::CurrentTimer, mutabor::CurrentTimer::Set, mutabor::CurrentTimer::UseRealtime.
mutint64 mutabor::CurrentTimerBase::Time()
References mutint64.
Referenced by mutabor::CurrentTimer::Get, mutabor::CurrentTimer::UseRealtime.