mutabor::BoxClass
interval_type_constants
boxidtype
KeyboardFlags
typedef tone mutabor::BoxClass::interval
typedef BoxListType mutabor::BoxClass::listtype
typedef std::list<logic_entry> mutabor::BoxClass::logic_list
typedef std::vector<tone_entry> mutabor::BoxClass::tone_list
typedef std::vector<current_tone_entry> mutabor::BoxClass::current_tone_list
mutabor::BoxClass::error_callback
void mutabor::BoxClass::log_action
void mutabor::BoxClass::lock_callback
void mutabor::BoxClass::unlock_callback
BoxListType mutabor::BoxClass::boxList
Referenced by mutaborGUI::BoxData::BoxData, ClearBoxList, FindInBoxList, GetBoxList, IsInBoxList.
int mutabor::BoxClass::nextboxid
Referenced by GetNextFreeBox.
mutabor::hidden::mutabor_callback_type mutabor::BoxClass::backend_callbacks
Referenced by mutabor::initialize_box_data.
friend class ::mutaborGUI::BoxData
friend class BoxFactory
void initialize_box_data()
struct mutabor_box_type* mutabor::BoxClass::box
Referenced by AddNote, mutabor::BoxClass::BoxLock::BoxLock, DeleteNote, interrupt_logic, KeyboardAnalysis, MidiAnalysis, resume_logic, mutaborGUI::BoxData::set_routefile_id, SetLogic.
idtype<BoxClass> mutabor::BoxClass::session_id
Referenced by get_session_id.
int mutabor::BoxClass::routefile_id
Referenced by get_routefile_id, GetType, IsNormal.
routeListType mutabor::BoxClass::routes
Referenced by DisconnectFromAll, GetChannel, GetRoutes, MidiOut, UpdateTones.
bool mutabor::BoxClass::open
Referenced by Close, IsOpen, Open.
std::string mutabor::BoxClass::current_logic
std::string mutabor::BoxClass::current_tonesystem
int mutabor::BoxClass::current_key_tonesystem
int mutabor::BoxClass::current_key_logic
unsigned int mutabor::BoxClass::updateflags
Referenced by UpdateCallback.
std::list<ChangedCallback *> mutabor::BoxClass::callbacks
Referenced by ExecuteCallbacks, Register, Unregister.
CompileCallback* mutabor::BoxClass::current_compile_callback
Referenced by compile_callback, mutabor::BoxClass::set_callback::set_callback, mutabor::BoxClass::set_callback::~set_callback.
Mutex mutabor::BoxClass::mutex
Referenced by mutaborGUI::BoxData::DoOpen, GetCurrentTones, GetLogics, GetToneSystem.
int mutabor::BoxClass::logic_timing
Referenced by dog_watching.
Mutex mutabor::BoxClass::logic_timing_mutex
Referenced by dog_watching.
mutint64 mutabor::BoxClass::loop_timeout
watchdog<Box>* mutabor::BoxClass::loopguard
Referenced by remove_watchdog.
mutabor::BoxClass::REFPTR_INTERFACE
mutabor::BoxClass::~BoxClass()
References debug_destruct_class, DEBUGLOG, intrusive_ptr_add_ref, TRACEC, UNREACHABLEC.
size_t mutabor::BoxClass::get_session_id() const
References session_id.
virtual BoxType mutabor::BoxClass::GetType()
References mutabor::Box0, routefile_id.
Referenced by GetLabel, GetTypeName.
virtual std::string mutabor::BoxClass::GetTypeName()
References _mut, mutabor::Box0, GetType, mutabor::GmnBox, mutabor::NewBox, mutabor::NoBox.
virtual std::string mutabor::BoxClass::GetLabel()
References _mut, mutabor::Box0, get_routefile_id, GetType, mutabor::GmnBox, mutabor::NewBox, mutabor::NoBox.
bool mutabor::BoxClass::IsNormal()
References mutabor::Box0, routefile_id.
int mutabor::BoxClass::get_routefile_id() const
References routefile_id.
Referenced by mutaborGUI::MutFrame::CeToggleKey, dog_watching, GetLabel.
void mutabor::BoxClass::set_routefile_id(int id)
References mutASSERT, mutabor::NewBox.
Referenced by BoxClass.
void mutabor::BoxClass::Save(tree_storage &config)
Save current device settings in a tree storage.
config (tree_storage) storage class, where the data will be saved.
Referenced by mutaborGUI::BoxData::Save.
void mutabor::BoxClass::Save(tree_storage &config, const RouteClass *route)
Save route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route) Route whos data shall be saved.
void mutabor::BoxClass::Load(tree_storage &config)
Load current device settings from a tree storage.
config (tree_storage) storage class, where the data will be loaded from.
Referenced by mutaborGUI::BoxData::Load.
void mutabor::BoxClass::Load(tree_storage &config, RouteClass *route)
Load route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route) Route whos data shall be loaded.
void mutabor::BoxClass::Add(Route &route)
add a route
References DEBUGLOG, mutASSERT, TRACEC.
bool mutabor::BoxClass::Replace(Route &oldRoute, Route &newRoute)
replace a route
References DEBUGLOG, mutASSERT.
bool mutabor::BoxClass::Remove(Route &route)
remove a route
References DEBUGLOG, intrusive_ptr_get_refcount, mutASSERT.
bool mutabor::BoxClass::MoveRoutes(Box &newclass)
Move routes to another device.
References mutaborGUI::IsOpen, mutabor::reconnect, TRACEC, UNREACHABLEC.
const routeListType& mutabor::BoxClass::GetRoutes() const
References routes.
Referenced by mutaborGUI::Check.
routeListType& mutabor::BoxClass::GetRoutes()
References routes.
int mutabor::BoxClass::MoveInList(int count)
Move the box in the box list.
count Number of places the box should be moved up. Negative values indicate downwards direction. new position in the box list.
Referenced by mutaborGUI::BoxData::MoveInList.
void mutabor::BoxClass::DisconnectFromAll()
Disconnect the device from all pairings with routes GUI data or something else.
This function should be extended in subclasses so that after calling it only temporary pointers (variables in functions or temporary objects) point to the object.
References mutabor::disconnect, routes, TRACEC.
Referenced by Destroy.
void mutabor::BoxClass::Panic(int type)
reset the device if requested
References mutabor::hidden::mutabor_reset_keys, mutASSERT.
void mutabor::BoxClass::Panic(Route r, int type)
References mutabor::hidden::mutabor_note_type::channel, DEBUGLOG, mutabor::hidden::mutabor_note_type::id, mutabor::hidden::mutabor_find_key_in_box, mutASSERT, mutabor::hidden::mutabor_note_type::next, mutabor::hidden::mutabor_note_type::number.
void mutabor::BoxClass::Panic(Route r, int type, size_t unique_id)
References mutabor::hidden::mutabor_find_key_in_box, mutASSERT, mutabor::hidden::mutabor_note_type::next.
void mutabor::BoxClass::Reset()
References mutabor::hidden::mutabor_reset_box.
bool mutabor::BoxClass::Open()
References DoOpen, open.
void mutabor::BoxClass::Close()
References DoClose, open.
Referenced by Destroy.
bool mutabor::BoxClass::DoOpen()
Referenced by mutaborGUI::BoxData::DoOpen, Open.
void mutabor::BoxClass::DoClose()
References mutASSERT.
Referenced by Close, mutaborGUI::BoxData::DoClose.
bool mutabor::BoxClass::IsOpen()
References open.
Referenced by Destroy.
BoxClass::logic_list mutabor::BoxClass::GetLogics()
Get a list of currently defined logics.
: this function replaces GetMutTag() from Runtime.cpp List of logic descriptions.
References mutabor::append_triggers, mutabor::hidden::mutabor_box_type::current_logic, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::global_harmonies, mutabor::hidden::mutabor_logic_parsed::global_keystrokes, mutabor::hidden::mutabor_logic_parsed::global_midi_inputs, mutabor::hidden::logik::harmony_list, mutabor::hidden::logik::keystroke_list, mutabor::hidden::logik::midi_input_list, mutex.
BoxClass::tone_system mutabor::BoxClass::GetToneSystem()
References mutabor::BoxClass::tone_system::anchor, mutabor::hidden::TSYS::anker, mutabor::hidden::mutabor_box_type::file, mutabor::BoxClass::tone_entry::invalid, mutabor::hidden::mutabor_active_tone, mutabor::hidden::mutabor_empty_tone, mutabor::hidden::mutabor_get_pitch_from_interval, mutabor::hidden::mutabor_get_pitch_from_tone, mutabor::hidden::mutabor_get_tone_type, mutabor::hidden::mutabor_invalid_tone, MUTABOR_KEYRANGE_MAX_WIDTH, mutASSERT, mutex, mutabor::BoxClass::tone_system::period, mutabor::hidden::TSYS::periode, mutabor::hidden::TSYS::ton, mutabor::BoxClass::tone_system::tones, mutabor::hidden::mutabor_box_type::tonesystem.
BoxClass::current_tone_list mutabor::BoxClass::GetCurrentTones()
References mutabor::hidden::mutabor_box_type::file, get_frequency, mutabor::BoxClass::tone::get_type, GetChannel, mutabor::BoxClass::tone_entry::invalid, mutabor::hidden::mutabor_box_type::key_count, mutabor::hidden::mutabor_empty_tone, mutabor::hidden::mutabor_find_key_in_box, mutabor::hidden::mutabor_get_pitch_from_tone, mutabor::hidden::mutabor_invalid_tone, mutex.
bool mutabor::BoxClass::Compile(CompileCallback *callback, const char *logic)
References _mut, mutabor::hidden::mutabor_scanner_data::anzahl_eingelesene_zeichen, mutabor::hidden::expand_decition_tree, mutabor::hidden::mutabor_box_type::file, get_errors, intervall_list_laenge, mutabor::hidden::mutabor_logic_parsed::list_of_intervalle, mutabor::hidden::mutabor_logic_parsed::list_of_logiken, mutabor::hidden::mutabor_logic_parsed::list_of_toene, mutabor::hidden::mutabor_logic_parsed::list_of_tonsysteme, mutabor::hidden::mutabor_logic_parsed::list_of_umstimmungen, mutabor::hidden::loesche_syntax_speicher, mutabor::hidden::logik_list_laenge, mutabor::hidden::mutabor_programm_einlesen, mutabor::BoxClass::CompileCallback::Refresh, mutabor::hidden::mutabor_box_type::scanner, mutabor::BoxClass::CompileCallback::SetMessage, mutabor::BoxClass::CompileCallback::SetStatus, mutabor::hidden::ton_list_laenge, mutabor::hidden::tonsystem_list_laenge, mutabor::hidden::umstimmungs_list_laenge, weiter_gehts_nach_compilerfehler.
void mutabor::BoxClass::MidiAnalysis(const std::vector< unsigned char > *midiCode)
References box, mutabor::hidden::MidiAnalysis.
void mutabor::BoxClass::MidiOut(struct midiliste *outliste)
References mutabor::hidden::midiliste::midi_code, mutabor::hidden::midi_list_laenge, routes.
Referenced by MidiOutCallback.
void mutabor::BoxClass::UpdateTones()
Update the currently playing tones to the current tone system.
this function was formerly defined as NotesCorrect
References routes.
int mutabor::BoxClass::GetChannel(int key, size_t channel, size_t id)
Get the MIDI channel of a given tone.
note Note that has been received channel Internal unique channel id id Internal unique Note id MIDI channel of the note
References mutabor::midi::NO_CHANNEL, routes, TRACE.
Referenced by GetCurrentTones.
void mutabor::BoxClass::AddNote(int note, size_t id, size_t channel, void *userdata)
References mutabor::hidden::AddKey, box.
void mutabor::BoxClass::DeleteNote(int note, size_t id, int channel)
References box, mutabor::hidden::DeleteKey.
bool mutabor::BoxClass::IsLogicKey(int key)
References mutabor::hidden::mutabor_box_type::current_logic, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::global_keystrokes, mutabor::is_logic_key, mutabor::hidden::logik::keystroke_list.
void mutabor::BoxClass::KeyboardAnalysis(int key, KeyboardFlags flags)
Execute the action associated with a key that is pressed on the computer keyboard.
key Key that has been pressed. flags Flags which type of action should be taken.
References box, mutabor::hidden::KeyboardAnalyse, mutabor::hidden::KeyboardAnalyseSimple, KeyboardAny, KeyboardLogic, KeyboardNoLogic.
void mutabor::BoxClass::KeyboardAnalysis(const std::string keys)
Execute the actions that are associated with the characters of a string.
: The character & denotes that the following character will not be a logic. keys
References box, mutabor::hidden::KeyboardIn.
BoxClass::tone mutabor::BoxClass::get_frequency(int note)
References mutabor::hidden::mutabor_get_note_frequency, mutabor::hidden::mutabor_box_type::tonesystem.
Referenced by GetCurrentTones.
int mutabor::BoxClass::get_index(int note)
References mutabor::hidden::mutabor_get_note_index, mutabor::hidden::mutabor_box_type::tonesystem.
int mutabor::BoxClass::get_distance(int note)
References mutabor::hidden::mutabor_get_note_distance, mutabor::hidden::mutabor_box_type::tonesystem.
void mutabor::BoxClass::interrupt_logic(bool allow_resume=true)
Break the execution of any running logic loops.
allow_resume if true allow the next call to the logic to resume logic execution
References mutabor::hidden::mutabor_box_flags::auto_reset_break_logic, box, mutabor::hidden::mutabor_box_flags::break_logic, mutabor::hidden::mutabor_box_type::flags.
Referenced by dog_watching.
void mutabor::BoxClass::resume_logic()
Allow the execution of logic actions after this function has been disabled.
References mutabor::hidden::mutabor_box_flags::auto_reset_break_logic, box, mutabor::hidden::mutabor_box_type::flags.
void mutabor::BoxClass::SetLogic(Box b)
References box, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_set_logic.
Referenced by mutaborGUI::BoxData::BoxData.
virtual void mutabor::BoxClass::Activate()
Activate the current box.
This method is called when a box is being activated. Its implementation should be done in the user code. Otherwise its just a no-op function.
void mutabor::BoxClass::Destroy()
Destroy the current object.
This function is called when an object shall be deleted. It clears up all references to itself so that it will be deleted if it is not needed anymore.This functions detatches the device from all routes and calls DoDestroy() afterwards. Finally the Device is going to removed from the device list.
References Close, debug_destroy_class, DisconnectFromAll, IsOpen, RemoveFromBoxList, TRACEC.
Referenced by mutaborGUI::BoxData::Destroy.
mutabor::BoxClass::operator std::string() const
References mutabor::str.
void mutabor::BoxClass::runtime_error(error_type type, const char *message)
Process an error message (doing the real work)
References mutabor::to_string.
Referenced by error_callback, mutabor::error_callback, issue_error.
void mutabor::BoxClass::issue_error(error_type type, const char *format,...)
Format and process a runtime error message or warning.
type error type. format Format string
References _mut, runtime_error.
Referenced by dog_watching.
virtual const std::string mutabor::BoxClass::get_errors()
Return the collected errors and warnings.
This function is a prototype for potential error message collection in the GUI part.a string containing the collected error messages
Referenced by Compile.
std::string mutabor::BoxClass::ActionToString(ChangedCallback::action *action)
References mutabor::hidden::do_aktion::name.
void mutabor::BoxClass::dog_watching()
References _mut, get_routefile_id, interrupt_logic, issue_error, logic_timing, logic_timing_mutex, mutabor::hidden::runtime_error, mutabor::hidden::runtime_warning.
void mutabor::BoxClass::remove_watchdog(T dog)
References loopguard, mutASSERT.
static int mutabor::BoxClass::GetNextFreeBox()
References nextboxid.
Referenced by mutaborGUI::NewMutBoxShape::InitializeDialog, mutaborGUI::MutBoxShape::InitializeDialog, BoxTest::testCopyPLay, BoxTest::testGetNextFreeBox, BoxTest::testParser.
static const listtype& mutabor::BoxClass::GetBoxList()
References boxList.
Referenced by mutabor::BoxClose, mutaborGUI::CheckBoxes, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutEditFile::Compile, mutaborGUI::MutRouteWnd::createBoxes, mutaborGUI::MutBoxChannelShape::InitializeRoute, mutaborGUI::MakeTopLevelsBoxes, mutabor::OpenAll, mutabor::Panic, mutabor::BoxFactory::SaveBoxes, InputMidiFileTest::setUp, CommonMidiOutputTest::setUp, CommonMidiInputTest::setUp, OutputMidiFileTest::setUp, CommonMidiOutputTest::tearDown, OutputMidiFileTest::tearDown, InputMidiFileTest::testAfterTouch, InputMidiFileTest::testAllControllerOff, InputMidiFileTest::testBankSelect, InputMidiFileTest::testBatchPlay1, InputMidiFileTest::testBoxMidiIn, InputMidiFileTest::testBug019010, InputMidiFileTest::testBug019010_2, InputMidiFileTest::testControllerPlay, InputMidiFileTest::testRpnNrpn, InputMidiFileTest::testSysEx, mutaborGUI::MutFrame::UpdateBoxMenu.
Box mutabor::BoxClass::GetBox(int id, boxidtype kind)
Scan the list of Boxes for a given id.
id (int) id to scan for (Box) pointer to the input device with the given id if found, NULL else.
References UNREACHABLECT.
Referenced by mutaborGUI::BoxDlg::AddButtonPressed, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutBoxShape::DoLeftDblClick, GetOrCreateBox, mutaborGUI::MutBoxShape::readDialog.
Box mutabor::BoxClass::GetOrCreateBox(int id)
Return the box that is associated with the corrent id.
In case such a box does not exist the box is created id Id to be fetched. Box that has been found or created
References mutabor::Box0, mutabor::BoxFactory::Create, GetBox, IDTypeFile.
Referenced by mutaborGUI::GUIRouteFactory::DoCreateBoxChannelShape, mutabor::TRouteClass< I, O, B >::Load, compat30::LoadRoutes, mutabor::MutaborTag, mutaborGUI::MutBoxShape::readDialog.
static void mutabor::BoxClass::ClearBoxList()
References boxList, mutASSERT.
Referenced by mutaborGUI::MutRouteWnd::CmRouteLoad, IMPLEMENT_APP, compat30::LoadRoutes, RouteTest::testDestroyAll.
void mutabor::BoxClass::CloseAll()
Close all boxes.
This function deactivates all boxes.
Referenced by mutabor::OpenAll.
bool mutabor::BoxClass::ActivateAll(bool isRealtime)
Activate all boxes.
This resets the action traces of all boxes. Code should be taken from MutFrame::DoActivate isRealtime Shall non-realtime devices (e.g., file devices) act in realtime mode or not true if Activation succeeded false otherwise
References mutabor::CurrentTime, mutabor::OpenAll, mutabor::OpenAllBoxes, mutabor::OpenAllInDevices, mutabor::OpenAllOutDevices, mutabor::CurrentTimer::UseRealtime.
Referenced by mutaborGUI::MutFrame::CmDoActivate.
void mutabor::BoxClass::StopAll()
Stop all boxes.
This resets the action traces of all boxes. Code should be taken from Stop()
References mutabor::CurrentTime, mutabor::InClose, mutabor::OutClose, mutabor::CurrentTimer::Stop.
Referenced by mutaborGUI::MutFrame::DoStop.
void mutabor::BoxClass::compile_callback(struct mutabor_box_type *b, int line_number)
References current_compile_callback, mutabor::BoxClass::CompileCallback::SetLine.
void mutabor::BoxClass::MidiOutCallback(struct mutabor::hidden::mutabor_box_type *b, struct mutabor::hidden::midiliste *outliste)
References MidiOut.
void mutabor::BoxClass::InitializeIds()
Initialize the internal device identifiers.
This function sets the internal device ids of all output devices, starting from 0 and incrementing by 1
References TRACET.
Referenced by mutabor::TRouteClass< I, O, B >::InitializeIds.
static void mutabor::BoxClass::log_action(mutabor_box_type *box, const char *action)
void mutabor::BoxClass::UpdateCallback(struct mutabor_box_type *b, unsigned int flags)
References mutabor::BoxClass::ChangedCallback::ActionChanged, mutabor::BoxClass::ChangedCallback::BoxChanged, mutabor::BoxClass::ChangedCallback::KeysChanged, mutabor::BoxClass::ChangedCallback::LogicChanged, mutabor::hidden::mutabor_action_changed, mutabor::hidden::mutabor_box_changed, mutabor::hidden::mutabor_keys_changed, mutabor::hidden::mutabor_logic_changed, updateflags.
static void mutabor::BoxClass::lock_callback(hidden::mutabor_logic_parsed *logic)
static void mutabor::BoxClass::unlock_callback(hidden::mutabor_logic_parsed *logic)
void mutabor::BoxClass::free_mutex_callback(hidden::mutabor_logic_parsed *logic)
References mutASSERT, mutabor::hidden::mutabor_logic_parsed::mutex.
mutabor::BoxClass::BoxClass(int id=-1)
References AppendToBoxList, mutabor::hidden::mutabor_initialize_box, set_routefile_id, mutabor::hidden::mutabor_box_type::userdata.
void mutabor::BoxClass::Register(ChangedCallback *callback)
References callbacks.
void mutabor::BoxClass::Unregister(ChangedCallback *callback)
References callbacks.
void mutabor::BoxClass::ExecuteCallbacks(unsigned int flags)
References callbacks.
void mutabor::BoxClass::ExecuteCallbacks(const char *action)
References callbacks.
void mutabor::BoxClass::AppendToBoxList(Box dev)
References DEBUGLOG2, isDebugFlag, print_stacktrace, UNREACHABLECT.
Referenced by BoxClass.
void mutabor::BoxClass::RemoveFromBoxList(Box dev)
References UNREACHABLECT.
Referenced by Destroy.
static listtype::iterator mutabor::BoxClass::FindInBoxList(Box b)
References boxList.
Referenced by IsInBoxList.
static bool mutabor::BoxClass::IsInBoxList(const Box b)
References boxList, FindInBoxList.
void mutabor::BoxClass::TruncateBoxList(Box dev)
References STUB.