aktion.c
struct aktions_liste* list_of_aktionen
Liste von Aktionen.
Referenced by get_last_aktions_liste.
void init_aktions_liste(void)
Setzt Aktionsliste auf NULL.
Die Argumentliste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_new_aktion_aufruf_element(char *name)
Fügt eine Aufruf-Aktion ans Ende von list_of_argumente an.
Der Aufruf erhält die letzte eingelesene Argumentliste. name Bezeichnung des Aufrufs, der angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References aktion_aufruf, get_last_argument_liste, name, aktions_liste::next, aktions_liste::u, xmalloc.
Referenced by switch, yyparse.
void get_new_aktion_midi_out_element(void)
Fügt eine Midi-Ausgabe-Aktion ans Ende von list_of_aktionen an.
Dazu wird die letzte Integersequenz verwendet. Es wird immer die gesamte Liste durchsucht. Effektivität?
References aktion_midi_out, get_last_integersequenz, aktions_liste::next, aktions_liste::u, xmalloc.
Referenced by switch, yyparse.
struct aktions_liste* get_last_aktions_liste(void)
Gibt die Wurzel von list_of_aktionen zurück.
References list_of_aktionen.
Referenced by get_new_anweisung, get_umstimmung_umstimmungs_bund, get_umstimmungs_case_default_element, get_umstimmungs_case_zahl_element.
void print_aktions_liste(struct aktions_liste *lauf)
Referenced by mutabor_programm_einlesen.
void check_aktionen(struct aktions_liste *aktionen, char *name)
Testet eine Liste von Aktionen auf Zulässigkeit.
Wird eine nicht zulässige oder erreichbare Konfiguration gefunden, wird je nach Situation ein fataler Fehler oder eine Compiler-Warnung ausgelöst. aktionen Aktionsliste, die geprüft werden soll name Name für Meldungen
References aktion_aufruf, aktions_liste::aktion_aufruf, aktion_midi_out, aktions_liste::aktion_midi_out, aktions_liste::aktions_typ, argument_list_laenge, compiler_warning, fatal_error, get_logik, get_umstimmung, list_of_logiken, list_of_tonsysteme, list_of_umstimmungen, midiliste::midi_code, midiliste::next, aktions_liste::next, parameter_list_laenge, umstimmung::parameter_liste, parser_get_tonsystem, aktions_liste::u.
Referenced by check_konsistenz, check_logik_konsistenz.
struct ton_einstell* expand_tonliste(struct ton *the_tonliste)
Expandiert eine Tonliste in eine einfach verkettete Liste von Einstellungen.
the_tonliste Liste von Tönen.
References DOUBLE_TO_LONG, einstell_absolut, einstell_gleich, einstell_relativ, einstell_stumm, FAKTOR_TO_MIDI, fatal_error, FREQUENZ_TO_MIDI, get_komplex_faktor, get_komplex_frequenz, ton::name, ton_einstell::next, ton_absolut, ton::ton_absolut, ton_komplex, ton::ton_komplex, ton::u, ton_einstell::u, xmalloc.
Referenced by expandiere_umstimmung.
struct do_aktion* expandiere_tonsystem(struct tonsystem *the_tonsystem)
Wandelt ein Tonsystem in eine Aktion um.
Dazu werden Tonnamen expandiert und die einzelnen Töne in MIDI-Werte umgerechnet. the_tonsystem Tonsystem.
References TSYS::anker, aufruf_tonsystem, TSYS::breite, DOUBLE_TO_LONG, FAKTOR_TO_MIDI, FREQUENZ_TO_MIDI, get_ton, get_wert_komplex_intervall, list_of_toene, name, ton::name, ton::next, TSYS::periode, toene, TSYS::ton, ton_list_laenge, ton::u, xmalloc.
Referenced by expandiere_logik, expandiere_name.
struct do_aktion* expand_aktions_liste(struct aktions_liste *the_liste, struct interpreter_parameter_liste *aktuelle_parameter)
Ersetzt Parameter in einer Aktionsliste durch ihre aktuellen Werte.
the_liste Ausgangs-Liste mit den Aktionen, deren Parameter ersetzt werden sollon. aktuelle_parameter Liste mit den Aktuellen Parametern, die ersetzt werden können. Neu hinzukommende Aktionen werden erhalten. Kann das passieren?
References aktion_aufruf, aktion_midi_out, expand_aktions_liste, expandiere_midi, expandiere_name, fatal_error, do_aktion::next, do_aktion::u.
Referenced by expand_aktions_liste, expand_case_liste, expandiere_umstimmung, insert_in_lokale_liste.
struct do_aktion* expandiere_umstimmung(struct umstimmung *the_umstimmung, struct interpreter_parameter_liste *aktuelle_parameter)
Ersetzt die Parameter einer Umstimmung durch deren Werte.
the_umstimmung Umstimmung, die bearbeitet werden soll. aktuelle_parameter Liste der Parameter, die ersetzt werden können
References aufruf_midi_out, aufruf_umst_breite_abs, aufruf_umst_breite_rel, aufruf_umst_taste_abs, aufruf_umst_taste_rel, aufruf_umst_toene_veraendert, aufruf_umst_umst_case, aufruf_umst_wiederholung_abs, aufruf_umst_wiederholung_rel, DOUBLE_TO_LONG, expand_aktions_liste, expand_case_liste, expand_tonliste, FAKTOR_TO_MIDI, fatal_error, get_wert_komplex_intervall, get_wert_of_argument, name, do_aktion::next, umstimmung::u, do_aktion::u, umstimmung_breite_abs, umstimmung::umstimmung_breite_abs, umstimmung_breite_rel, umstimmung::umstimmung_breite_rel, umstimmung_midi_out, umstimmung::umstimmung_midi_out, umstimmung_taste_abs, umstimmung::umstimmung_taste_abs, umstimmung_taste_rel, umstimmung::umstimmung_taste_rel, umstimmung_toene_veraendert, umstimmung::umstimmung_toene_veraendert, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, xfree, xmalloc.
Referenced by expandiere_logik, expandiere_name.
struct do_aktion* expandiere_name(char *name, struct argument_liste *parameter, struct interpreter_parameter_liste *bezugs_liste)
Sucht nach einer Logik, einem Tonsystem bzw.
einer Umstimmung in dieser Reihenfolge. Wird eine Umstimmung zurückgeliefert, so werden gleich auch deren Parameter ersetzt. name Name der zu suchenden Logik, des Tonsystems oder der Umstimmung. parameter Argumente, für die Parameter-Ersetzung bezugs_liste Liste mit den Interpreter-Parametern, aus denen die aktuellen Parameter für die Expansion der Umstimmung generiert werden.
References expandiere_logik, expandiere_tonsystem, expandiere_umstimmung, fatal_error, gen_parameter_liste, get_logik, get_umstimmung, list_of_logiken, list_of_tonsysteme, list_of_umstimmungen, parser_get_tonsystem.
Referenced by expand_aktions_liste.
struct do_aktion* expandiere_midi(struct midiliste *liste)
Wandelt eine MIDI-Liste in eine MIDI-Ausgabe-Aktion um.
liste MIDI-Liste, die umgewandelt werden soll
References aufruf_midi_out, name, do_aktion::next, do_aktion::u, xmalloc.
Referenced by expand_aktions_liste.