MisFile
char MisFile::Type
Referenced by Load, MisFile, Save, WriteInit.
int MisFile::nTrack
Referenced by MisFile, MisTrack::MisTrack, Save, WriteInit.
int MisFile::Speed
Referenced by Load, MisFile, Save, WriteInit.
char* MisFile::Id
Referenced by MisFile.
DWORD MisFile::Time
Referenced by CountOnDeltaTime, GetTrack, MisFile, ReadInit, ReadOn, WriteInit.
MisTrack* MisFile::Tracks
Referenced by CountOnDeltaTime, GetTrack, Load, MisFile, ReadInit, ReadOn, Save, WriteInit, ~MisFile.
MisNote* MisFile::Notes
Referenced by GetNote, MisFile, NoteOn.
Channel MisFile::Channels[16][16]
Referenced by MisTrack::AddNoteOn, GetChannel, GetNote, NoteOff, NoteOn, WriteInit.
Instrument* MisFile::Instruments
Referenced by AddInstrument, GetChannel, MisFile, NoteOff, NoteOn.
MisFile::MisFile(char *id)
References Id, Instruments, Notes, nTrack, Speed, Time, Tracks, Type.
MisFile::~MisFile()
References Tracks.
BYTE MisFile::Get(int i)
Referenced by Save.
int MisFile::Load(char *fileName="tmp.mid")
References MisTrack::Load, MisTrack::Next, ReadLength, Speed, Tracks, Type.
int MisFile::Save(char *fileName="tmp.mid")
References Get, nTrack, MisTrack::Save, Speed, Tracks, Type, WriteLength.
Referenced by main.
void MisFile::ReadInit()
References MisTrack::ReadInit, Time, Tracks.
DWORD MisFile::ReadOn(DWORD deltaTime=0, MisReadProceed *proceed=MisReadDummy)
References MisTrack::ReadOn, Time, Tracks.
void MisFile::WriteInit()
References Channels, Channel::nNotesOn, nTrack, Channel::Pitch, Channel::Sound, Speed, Time, Channel::Track, Tracks, Type.
Referenced by main.
MisTrack * MisFile::GetTrack(int id)
References Time, Tracks.
Referenced by NoteOff, NoteOn, WriteMis.
int MisFile::WriteMis(DWORD midi, MisTrack *track, int trackId)
References GetTrack, MisTrack::WriteMis.
void MisFile::CountOnDeltaTime(DWORD deltaTime)
References MisTrack::CountOnDeltaTime, Time, Tracks.
Referenced by main.
void MisFile::AddInstrument(int id, char von, char bis)
References Instruments.
Referenced by main.
MisNote ** MisFile::GetNote(int key, int pitch, int instrumentId)
References Channels, MisNote::Next, Notes, Channel::Pitch.
Referenced by NoteOff.
char MisFile::GetChannel(int Instrument, int Pitch, signed char sound)
References Instrument::Bis, Channels, GetInstrument, Instruments, Channel::nNotesOn, Instrument::Von.
Referenced by NoteOn.
int MisFile::NoteOn(int key, int pitch, char intensity, int id)
References MisTrack::AddNoteOn, Channels, GetChannel, GetInstrument, GetTrack, Instruments, Channel::nNotesOn, Notes, Instrument::Sound.
Referenced by WriteGis.
int MisFile::NoteOff(int key, int pitch, char intensity, int id)
References MisTrack::AddNoteOff, MisNote::Channel, Channels, GetInstrument, GetNote, GetTrack, Instruments, MisNote::Next, Channel::nNotesOn, Instrument::Von.
Referenced by WriteGis.
int MisFile::WriteGis(GisReadArtHead *head, GisToken *token, char turn, int id)
References GisReadArtHead::GetAlter, GetGisType, GisReadArtHead::GetIntensity, GisReadArtHead::GetOctave, GTNote, GTTag, NoteOff, NoteOn.
Referenced by Write.