Hilfs.cpp
_
OFFSET
Referenced by xmalloc.
void * xalloca(mutabor_box_type *box, size_t size)
References _, DEBUGLOG2, error, mutabor_error_message.
Referenced by berechne_intervalle_absolut, berechne_toene_absolut, check_konsistenz.
void xde_alloca(void *pointer)
Referenced by berechne_intervalle_absolut, berechne_toene_absolut, check_konsistenz.
void xfree(void *pointer)
Referenced by expandiere_umstimmung, yylex.
void * xmalloc(mutabor_box_type *box, size_t size)
References _, heap_element::anzahl_belegt, DEBUGLOG2, error, mutabor_box_type::file, mutabor_logic_parsed::heap, HEAP_PORTION_SYNTAX, mutabor_syntax_heap::heap_to_use_syntax, heap_element::inhalt, mutabor_error_message, heap_element::next, OFFSET, mutabor_syntax_heap::syntax_heap.
Referenced by allgemeine_initialisierungen, expand_case_liste, expand_harmony_analysis, expand_pattern, expand_tonliste, expandiere_logik, expandiere_midi, expandiere_tonsystem, expandiere_umstimmung, generate_argument_list, get_ausloeser_default, get_ausloeser_harmonie, get_ausloeser_harmonie_form, get_ausloeser_midi_in, get_ausloeser_taste, get_instrument_dekl, get_new_aktion_aufruf_element, get_new_aktion_harmony_analysis, get_new_aktion_midi_out_element, get_new_anchor_in_argument_list, get_new_anweisung, get_new_distance_in_argument_list, get_new_faktor_anteil, get_new_harmonie, get_new_integer_in_integersequenz, get_new_intervall, get_new_intervall_komplex, get_new_logik, get_new_name_in_argument_list, get_new_name_in_parameterlist, get_new_number_in_argument_list, get_new_taste, get_new_ton_absolut, get_new_ton_in_tonsystem, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_new_umstimm_expression, get_new_umstimm_expression_negative, get_new_umstimm_expression_positive, get_umstimmungs_case_default_element, get_umstimmungs_case_zahl_element, init_umstimmung, insert_in_globale_liste, insert_in_lokale_liste, xcalloc, xrealloc, yylex.
void * xrealloc(mutabor_box_type *box, void *block, size_t newsize)
References _, heap_element::anzahl_belegt, DEBUGLOG2, error, mutabor_box_type::file, mutabor_logic_parsed::heap, HEAP_PORTION_SYNTAX, mutabor_syntax_heap::heap_to_use_syntax, heap_element::inhalt, mutabor_error_message, xmalloc.
Referenced by yylex.
void * xcalloc(mutabor_box_type *box, size_t anzahl, size_t size)
References _, DEBUGLOG2, error, mutabor_error_message, xmalloc.
Referenced by check_aktionen, create_midi_scan_liste, expand_decition_tree, generate_argument_list.
int loesche_syntax_speicher(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::heap, mutabor_syntax_heap::heap_to_use_syntax, heap_element::next, mutabor_syntax_heap::syntax_heap.
Referenced by mutabor::BoxClass::Compile, GMutCompile, init_syntax_speicher, mutabor_set_logic, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.
int init_syntax_speicher(mutabor_box_type *box)
References loesche_syntax_speicher.
void yfree(void *pointer)
void * ymalloc(mutabor_box_type *box, size_t size)
References _, DEBUGLOG2, error, mutabor_error_message, mini_heap::next, mini_heap::pointer, mutabor_box_type::runtime_heap.
Referenced by call_actions, ycalloc, yrealloc.
void * yrealloc(mutabor_box_type *box, void *block, size_t newsize)
References ymalloc.
void * ycalloc(mutabor_box_type *box, size_t anzahl, size_t size)
References ymalloc.
Referenced by call_actions.
int init_laufzeit_speicher(mutabor_box_type *box)
References loesche_laufzeit_speicher.
int loesche_laufzeit_speicher(mutabor_box_type *box)
References mini_heap::next, mini_heap::pointer, mutabor_box_type::runtime_heap.
Referenced by init_laufzeit_speicher.