mutabor::Device
devidtype
friend class ::mutaborGUI::GUIOutputDeviceBase
Noch zu erledigenlift this restrection afer GUI is working again
friend class ::mutaborGUI::GUIInputDeviceBase
idtype<Device> mutabor::Device::session_id
Id used during runtime;.
Referenced by get_session_id, mutabor::CommonFileOutputDevice::TowxString, TowxString.
int mutabor::Device::routefile_id
Referenced by get_routefile_id, set_routefile_id, mutabor::CommonFileOutputDevice::TowxString, TowxString.
mutString mutabor::Device::Name
Referenced by mutabor::OutputMidiPort::do_Open, mutabor::InputMidiPort::GetName, GetName, mutabor::CommonFileOutputDevice::Load, mutabor::OutputGis::Load, mutabor::CommonFileInputDevice::Load, mutabor::InputGis::Open, mutabor::InputGis::ProceedRoute, mutabor::CommonFileOutputDevice::Save, mutabor::OutputGis::Save, mutabor::CommonFileInputDevice::Save, mutabor::OutputMidiPort::SetDevId, mutabor::InputMidiPort::SetDevId, mutabor::CommonFileOutputDevice::SetName, mutabor::OutputGis::SetName, mutabor::CommonFileInputDevice::SetName, SetName, mutabor::OutputMidiFile::SetName, mutabor::InputGis::Stop, mutabor::CommonFileOutputDevice::TowxString, mutabor::OutputGis::TowxString, mutabor::InputGis::TowxString, TowxString.
bool mutabor::Device::dirty
Referenced by Dirty, IsDirty, TowxString.
bool mutabor::Device::isOpen
Referenced by mutabor::CommonFileOutputDevice::Close, mutabor::CommonFileInputDevice::Close, mutabor::CommonFileOutputDevice::do_Open, IsOpen, midicmnInputDevice::Open, mutabor::CommonFileInputDevice::Open, TowxString, mutabor::CommonFileInputDevice::~CommonFileInputDevice.
enum MutaborModeType mutabor::Device::Mode
Referenced by mutabor::InputGis::Close, mutabor::CommonFileInputDevice::exception_error, GetMode, mutabor::InputDeviceClass::InputDeviceClass, mutabor::CommonFileInputDevice::Open, mutabor::InputGis::Open, mutabor::CommonFileInputDevice::Pause, mutabor::InputDeviceClass::Pause, mutabor::CommonFileInputDevice::Play, mutabor::InputDeviceClass::Play, testCommonFileDeviceTimer::PrepareNextEvent, SetMode, mutabor::CommonFileInputDevice::Stop, mutabor::InputGis::Stop, mutabor::InputDeviceClass::Stop, mutabor::CommonFileInputDevice::ThreadPlay, mutabor::InputDeviceClass::TowxString, mutabor::CommonFileInputDevice::WaitForDeviceFinish.
routeListType mutabor::Device::routes
Referenced by mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetRoutes, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::nRoutes, mutabor::InputDeviceClass::Panic, mutabor::InputGis::ProceedRoute, TowxString.
void* mutabor::Device::userdata
Referenced by getUserData, setUserData, TowxString.
virtual mutabor::Device::~Device()
References TRACEC.
virtual void mutabor::Device::Save(tree_storage &config)=0
Save current device settings in a tree storage.
config (tree_storage) storage class, where the data will be saved.
virtual void mutabor::Device::Save(tree_storage &config, const RouteClass *route)=0
Save route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route) Route whos data shall be saved.
virtual void mutabor::Device::Load(tree_storage &config)=0
Load current device settings from a tree storage.
config (tree_storage) storage class, where the data will be loaded from.
virtual void mutabor::Device::Load(tree_storage &config, RouteClass *route)=0
Load route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route) Route whos data shall be loaded.
virtual void mutabor::Device::Add(Route &route)=0
add a route
virtual bool mutabor::Device::Replace(Route &oldRoute, Route &newRoute)=0
replace a route
virtual bool mutabor::Device::Remove(Route &route)=0
remove a route
virtual void mutabor::Device::Panic(int type)=0
reset the device if requested
virtual void mutabor::Device::Play()
Start playback or recording of the device.
virtual void mutabor::Device::Pause()
Pause playback or recording of the device.
virtual void mutabor::Device::Stop()
Stop playback or recording of the device.
virtual void mutabor::Device::SetMode(MutaborModeType m)
References Mode.
MutaborModeType mutabor::Device::GetMode()
References Mode.
Referenced by CommonFileDeviceTest::testTimer.
void mutabor::Device::runtime_error(int type, mutString message,...)
Process an error message.
Referenced by mutabor::CommonFileInputDevice::exception_error, mutabor::MidiPortOutputProvider::Open, mutabor::InputGis::Open.
void mutabor::Device::runtime_error(int type, const mutStringRef message, va_list &args)
Process an error message (doing the real work)
References mutChar, mutPrintf, mutString, mutVPrintf, mutabor::to_string.
const wxString& mutabor::Device::GetName() const
References Name.
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::InitializeDialog, mutaborGUI::MutOutputMidiDeviceShape::readDialog.
virtual void mutabor::Device::SetName(const wxString &s)
References Name.
size_t mutabor::Device::get_session_id() const
References session_id.
int mutabor::Device::get_routefile_id() const
References routefile_id.
Referenced by compat30::SaveRoutes.
virtual void mutabor::Device::ReadData(wxConfigBase *config)
virtual void mutabor::Device::WriteData(wxConfigBase *config)
virtual mutString mutabor::Device::GetTypeName() const
References N_.
virtual bool mutabor::Device::Open()=0
Referenced by mutaborGUI::GUIMidiPortFactory::DoCreateInput, mutaborGUI::GUIMidiFileFactory::DoCreateInput, mutaborGUI::GUIGisFactory::DoCreateInput.
virtual void mutabor::Device::Close()=0
bool mutabor::Device::IsDirty() const
References dirty.
void mutabor::Device::Dirty(bool d=true)
References dirty.
bool mutabor::Device::IsOpen() const
References isOpen.
Referenced by mutaborGUI::GUIMidiPortFactory::DoCreateInput, mutaborGUI::GUIMidiFileFactory::DoCreateInput, mutaborGUI::GUIGisFactory::DoCreateInput, mutaborGUI::GUIMidiPortFactory::DoCreateOutput, mutaborGUI::GUIMidiFileFactory::DoCreateOutput, mutaborGUI::GUIGisFactory::DoCreateOutput, mutabor::OutputMidiPort::SetDevId, mutabor::InputMidiPort::SetDevId, mutabor::CommonFileOutputDevice::SetName, mutabor::CommonFileInputDevice::SetName, mutabor::OutputMidiFile::SetName, mutabor::OutputDeviceClass::~OutputDeviceClass.
wxString mutabor::Device::TowxString() const
References dirty, isOpen, Name, mutabor::NoBox, routefile_id, routes, session_id, userdata.
Referenced by mutabor::CommonTypedDeviceAPI< T, P, L >::TowxString.
mutabor::Device::Device(const mutStringRef name=mutEmptyString, int id=-1)
virtual void mutabor::Device::setUserData(void *data)
References userdata.
virtual void* mutabor::Device::getUserData() const
References userdata.
Referenced by mutaborGUI::GUIInputDeviceBase::GetGUIInputDevice, mutaborGUI::GUIOutputDeviceBase::GetGUIOutputDevice.
void mutabor::Device::set_routefile_id(int id)
References routefile_id.
Referenced by mutabor::DeviceFactory::LoadInputDevices.