configtree
wxConfigBase* configtree::config
configuration object
Referenced by DeleteEntry, DeleteGroup, GetPath, HasGroup, Read, SetPath, toFirstLeaf, toLeaf, toNextLeaf, toParent, Write, ~configtree.
bool configtree::deleteconfig
true if the config is private and must be deleted on deletion
Referenced by ~configtree.
std::stack<state> configtree::states
Referenced by toFirstLeaf, toLeaf, toNextLeaf, toParent.
configtree::configtree(wxConfigBase *conf, bool ownconfig=false)
virtual configtree::~configtree()
References config, deleteconfig.
long configtree::Read(const std::string &key, long defval)
Reads a long integer value.
key (std::string&) Name of the desired leaf in the tree defval (long) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
References config.
Referenced by Read.
double configtree::Read(const std::string &key, double defval)
Reads a double value.
key (std::string&) Name of the desired leaf in the tree defval (double) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
References config, Read.
int configtree::Read(const std::string &key, int defval)
Reads an integer value.
key (std::string&) Name of the desired leaf in the tree defval (int) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
References config, Read.
bool configtree::Read(const std::string &key, bool defval)
Reads a boolean value.
key (std::string&) Name of the desired leaf in the tree defval (bool) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
References config, Read.
std::string configtree::Read(const std::string &key, const std::string &defval)
Reads a string value.
key (std::string&) Name of the desired leaf in the tree defval (std::string&) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
References config, Read.
void configtree::Write(const std::string &key, long value)
Writes a long integer value.
key (std::string&) Name of the desired leaf in the tree value (long) value, to be written
References config.
Referenced by Write.
void configtree::Write(const std::string &key, double value)
Writes a double value.
key (std::string&) Name of the desired leaf in the tree value (double) value, to be written
References config, Write.
void configtree::Write(const std::string &key, int value)
Writes an integer value.
key (std::string&) Name of the desired leaf in the tree value (int) value, to be written
References config, Write.
void configtree::Write(const std::string &key, bool value)
Writes a boolean value.
key (std::string&) Name of the desired leaf in the tree value (bool) value, to be written
References config, Write.
void configtree::Write(const std::string &key, const std::string &value)
Writes a string value.
key (std::string&) Name of the desired leaf in the tree value (std::string&) value, to be written
References config, Write.
bool configtree::HasGroup(const std::string &subdir) const
Checks if the tree has a branch with the given name.
subdir (std::string&) subdirectory to check for. true if the current node has a leaf with the given name which is a node itself.
References config.
void configtree::toLeaf(const std::string &subdir)
Changes the current node downwards.
this function can be used to navigate towards the leaves in the tree. The argument can be considered like a subdirectory in a file system. subdir (std::string&) subdirectory to be written to.
References configtree::state::chdepth, config, DEBUGLOG, GetPath, configtree::state::group, configtree::state::leafid, mutASSERT, configtree::state::oldpath, SetPath, states, UNREACHABLEC.
Referenced by toFirstLeaf, toLeaf.
void configtree::toLeaf(const std::string &name, int id)
Changes the current node downwards.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. if the id is negative, it will create a new item. subdir (std::string&) name of the entity to be written to. id (int) id of the current object
References configtree::state::chdepth, config, DEBUGLOG, configtree::state::group, configtree::state::leafid, configtree::state::oldpath, states, toLeaf.
virtual int configtree::toFirstLeaf(const std::string &name)
Changes the current node downdwards to the first leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (std::string&) name of the entity to be read from. (int) id of the selected item toNextLeaf
int configtree::toFirstLeaf(const std::string &name, std::string &id)
Changes the current node downdwards to the first leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (std::string&) name of the entity to be read from. id (std::string&) reference to a String where the id of the leaf will be stored (int) id of the selected item toNextLeaf
References configtree::state::chdepth, config, DEBUGLOG, configtree::state::group, configtree::state::leafid, mutASSERT, configtree::state::oldpath, states, toLeaf.
virtual int configtree::toNextLeaf(const std::string &name)
Changes the current node downdwards to the next leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (std::string&) name of the entity to be read from. (int) id of the selected item toFirstLeaf
int configtree::toNextLeaf(const std::string &name, std::string &id)
Changes the current node downdwards to the next leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (std::string&) name of the entity to be read from. id (std::string&) reference to a String where the id of the leaf will be stored (int) id of the selected item toFirstLeaf
References config, DEBUGLOG, mutASSERT, SetPath, states.
void configtree::toParent(unsigned int count=1)
This function jumps up in the tree (i.e. towards the root).
count (int) number of nodes to go upward. Default: 1.
References configtree::state::chdepth, config, DEBUGLOG, configtree::state::group, configtree::state::leafid, mutASSERT, configtree::state::oldpath, SetPath, states, UNREACHABLEC.
std::string configtree::GetPath()
Return a string representation of the position in the current tree.
This function can be used to store the current position in the tree. std::string String representation of the current path. The concrete representation is implementation dependent and can vary for different tree types.
References config.
Referenced by toLeaf.
void configtree::SetPath(const std::string &path)
Set the current pointer in the tree.
This function can be used to store the current position in the tree. path (std::string) String representation of the new path as returned by GetPath(). The concrete representation is implementation dependent and can vary for different tree types.
References config, DEBUGLOG.
Referenced by toLeaf, toNextLeaf, toParent.
virtual void configtree::DeleteEntry(const std::string &path)
Delete an entry.
entry path to the entry that shall be deleted
References config.
virtual void configtree::DeleteGroup(const std::string &path)
Delete an entire group with all childs.
group path to the entry that shall be deleted
References config.