mutabor::MidiPortOutputProvider
RtMidiOut* mutabor::MidiPortOutputProvider::port
Referenced by Close, Open, RawMsg, SendSysEx, ~MidiPortOutputProvider.
mutabor::Device* mutabor::MidiPortOutputProvider::device
Referenced by Open.
mutabor::MidiPortOutputProvider::MidiPortOutputProvider(Device *p)
mutabor::MidiPortOutputProvider::~MidiPortOutputProvider()
References Close, port.
bool mutabor::MidiPortOutputProvider::Open(int id, const std::string name)
References _mut, device, mutabor::hidden::error, port, mutabor::Device::runtime_error, mutabor::str.
Referenced by mutabor::OutputMidiPort::do_Open.
bool mutabor::MidiPortOutputProvider::Open()
References port.
void mutabor::MidiPortOutputProvider::Close()
References port.
Referenced by ~MidiPortOutputProvider.
MidiPortOutputProvider& mutabor::MidiPortOutputProvider::operator()(int channel, uint8_t byte1, uint8_t byte2, uint8_t byte3)
Outputs a three-byte message.
channel channel to which data shall be sent to. How channels are split into tracks or subdevices is managed by the OutputProvider byte1 1st byte byte2 2nd byte byte3 3rd byte
References mutabor::midi::CHANNEL_MASK, mutASSERT, RawMsg, mutabor::midi::SYSTEM, mutabor::midi::TYPE_MASK, UNREACHABLEC.
MidiPortOutputProvider& mutabor::MidiPortOutputProvider::RawMsg(int channel, uint8_t byte1, uint8_t byte2, uint8_t byte3)
Outputs a raw three-byte message.
channel channel to which data shall be sent to. How channels are split into tracks or subdevices is managed by the OutputProvider byte1 1st byte byte2 2nd byte byte3 3rd byte
References port.
Referenced by operator().
MidiPortOutputProvider& mutabor::MidiPortOutputProvider::operator()(int channel, uint8_t byte1, uint8_t byte2)
Outputs a two-byte message.
channel channel to which data shall be sent to. How channels are split into tracks or subdevices is managed by the OutputProvider byte1 1st byte byte2 2nd byte
References mutabor::midi::CHANNEL_MASK, mutASSERT, RawMsg, mutabor::midi::SYSTEM, mutabor::midi::TYPE_MASK, UNREACHABLEC.
MidiPortOutputProvider& mutabor::MidiPortOutputProvider::RawMsg(int channel, uint8_t byte1, uint8_t byte2)
Outputs a two-byte message.
channel channel to which data shall be sent to. How channels are split into tracks or subdevices is managed by the OutputProvider byte1 1st byte byte2 2nd byte
References port.
MidiPortOutputProvider& mutabor::MidiPortOutputProvider::RawMsg(int channel, uint8_t byte1)
Outputs a one-byte message.
byte1 1st byte
References mutASSERT, port.
MidiPortOutputProvider& mutabor::MidiPortOutputProvider::SendSysEx(int channel, iterator from, iterator to)
Outputs a system exclusive message.
The message must include a valid device id. channel channel to which data shall be sent to. How channels are split into tracks or subdevices is managed by the OutputProvider (ignored) from iterator pointing to the beginning of the message. to iterator pointing just after the end of the message. the final 0xf7 is sent automatically.
References port, mutabor::midi::STARTBYTE_MASK, mutabor::midi::SYSEX_END, mutabor::midi::SYSEX_START, UNREACHABLEC.