mutabor::InputDeviceClass
wxThreadWait
friend class DeviceFactory
current_keys_type mutabor::InputDeviceClass::current_keys
Referenced by DoNoteOff, DoSilenceKeys, midicmnInputDevice::midicmnInputDevice, NoteOn, Panic, ResumeKeys.
Mutex mutabor::InputDeviceClass::write_lock
Referenced by NoteOff, NoteOn, Panic, ResumeKeys, SilenceKeys.
bool mutabor::InputDeviceClass::last_was_stop
Referenced by PauseAll, RealtimePlay, StopAll, was_last_stop.
virtual mutabor::InputDeviceClass::~InputDeviceClass()
References TRACEC.
virtual void mutabor::InputDeviceClass::Close()
References Stop.
Referenced by CommonMidiInputTest::testGlobalPanic, CommonMidiInputTest::testPanic.
virtual void mutabor::InputDeviceClass::Stop()
Stop playback or recording of the device.
References DEFAULT_PANIC, mutabor::DeviceStop, mutabor::Device::Mode, Panic.
Referenced by Close.
virtual void mutabor::InputDeviceClass::Play()
Command the device to play music.
This function starts playing the music of the device at the curren position.
References mutabor::DevicePause, mutabor::DevicePlay, mutabor::DeviceStop, mutabor::Device::Mode.
virtual wxThread::ExitCode mutabor::InputDeviceClass::WaitForDeviceFinish(wxThreadWait flags=wxTHREAD_WAIT_BLOCK)
Wait for the thread started with Play().
This function can be used to wait for the device to finish playing. It can be used for joinable threads, only. For detached threads its behaviour is undefined. flags Indicators how to wait see wxThread::Wait for more detail. exit code from the thread after it has ended. Non-threaded devices will return NULL.
virtual void mutabor::InputDeviceClass::Pause()
Pause playback or recording of the device.
References mutabor::DevicePause, mutabor::Device::Mode.
virtual bool mutabor::InputDeviceClass::NeedsRealTime()
virtual mutint64 mutabor::InputDeviceClass::PrepareNextEvent()
Go on to the next event.
This function must be provided by the device. It is asked to prepare the next event and return the time to wait in microseconds from the start of the piece. Though the timer has only milliseconds resolution, the errors will sum up so that we need a much higher resolution, here.Here, we use the measure that is used in the SMF standard. It has been designed to reduce the deviation of a 4 minutes piece at 120 bpm to 500μs. If it were 500ms it would be unusable.uint_fast64_t Absolute temporal position of the next event in the piece in μs.
References MUTABOR_NO_DELTA.
Referenced by mutabor::CommonFileInputDevice::ThreadPlay.
virtual DevType mutabor::InputDeviceClass::GetType() const
References mutabor::DTUnknown.
virtual std::string mutabor::InputDeviceClass::GetTypeName() const
References _mutN.
bool mutabor::InputDeviceClass::IsDelta(mutint64 d)
References GetNO_DELTA.
Referenced by mutabor::InputGis::ReadOn, mutabor::CommonFileInputDevice::ThreadPlay.
mutabor::InputDeviceClass::operator std::string() const
References mutabor::str.
void mutabor::InputDeviceClass::NoteOn(Route &R, int key, int velocity, size_t make_unique, const ChannelData &input_channel_data, void *userdata)
References mutabor::InputDeviceClass::current_keys_type::add, current_keys, DEBUGLOG, write_lock.
Referenced by mutabor::InputGis::Proceed.
void mutabor::InputDeviceClass::NoteOff(Route &R, int key, int velocity, size_t make_unique)
References DoNoteOff, write_lock.
Referenced by mutabor::InputGis::Proceed.
void mutabor::InputDeviceClass::DoNoteOff(Route &R, int key, int velocity, size_t make_unique)
References current_keys, DEBUGLOG, mutabor::InputDeviceClass::current_keys_type::remove.
Referenced by NoteOff, Panic.
void mutabor::InputDeviceClass::SilenceKeys(bool remove)
References DoSilenceKeys, write_lock.
Referenced by mutabor::CommonFileInputDevice::ThreadPlay.
void mutabor::InputDeviceClass::DoSilenceKeys(bool remove)
References mutabor::InputDeviceClass::current_keys_type::begin, mutabor::InputDeviceClass::current_keys_type::clear, mutabor::midi::CONTROLLER_OFF, current_keys, DEBUGLOG, mutabor::InputDeviceClass::current_keys_type::end, mutabor::midi::get_holds.
Referenced by Panic, SilenceKeys.
void mutabor::InputDeviceClass::ResumeKeys()
Noch zu erledigenmove implementation to midicmn and Co.
References mutabor::InputDeviceClass::current_keys_type::begin, current_keys, DEBUGLOG, mutabor::InputDeviceClass::current_keys_type::end, mutabor::ChannelData::get_controller, mutabor::midi::get_holds, GetChannelData, write_lock.
Referenced by mutabor::CommonFileInputDevice::ThreadPlay.
void mutabor::InputDeviceClass::Panic(int type)
reset the device if requested
References DoSilenceKeys, mutabor::Device::routes, write_lock.
Referenced by mutabor::InputGis::Stop, mutabor::InputMidiPort::Stop, Stop, CommonMidiInputTest::testPanic, mutabor::CommonFileInputDevice::ThreadPlay.
void mutabor::InputDeviceClass::Panic(int type, size_t unique_id)
References mutabor::InputDeviceClass::current_keys_type::add, mutabor::InputDeviceClass::current_keys_type::begin, mutabor::midi::CONTROLLER_OFF, current_keys, DoNoteOff, mutabor::InputDeviceClass::current_keys_type::end, mutabor::midi::get_holds, mutabor::InputDeviceClass::current_keys_type::remove, mutabor::Device::routes, write_lock.
virtual ChannelData& mutabor::InputDeviceClass::GetChannelData(const current_keys_type::entry &key) const =0
Referenced by ResumeKeys.
bool mutabor::InputDeviceClass::BatchPlay()
Play all input devices in batch mode The batch mode allows for direct conversion of data in a complex route environment.
In contrast to the normal Play() function this function doesn't use timers, but simulates timing.Noch zu erledigen{find a better place for BatchPlay and RealtimePlay: we should not reference CurrentTime from Device.{h,cpp,-inlines.h} }
References mutabor::CurrentTime, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::deviceList, mutabor::CurrentTimer::Get, mutabor::InClose, MUTABOR_NO_DELTA, mutASSERT, mutint64, mutabor::OpenAll, mutabor::OpenAllInDevices, mutabor::OpenAllOutDevices, mutabor::OutClose, mutabor::CurrentTimer::Set, mutabor::CurrentTimer::Stop, mutabor::CurrentTimer::UseRealtime.
Referenced by InputMidiFileTest::testAfterTouch, InputMidiFileTest::testAllControllerOff, InputMidiFileTest::testBankSelect, InputMidiFileTest::testBatchPlay1, OutputMidiFileTest::testBatchPlay1, InputMidiFileTest::testBoxMidiIn, InputMidiFileTest::testBug019010, InputMidiFileTest::testControllerPlay, InputMidiFileTest::testRpnNrpn, InputMidiFileTest::testSysEx.
void mutabor::InputDeviceClass::RealtimePlay()
Play all input devices in realtime mode The the realtime mode allows interactive playing together with the integrated sequencer.
References mutabor::CommonTypedDeviceAPI< InputDeviceClass >::deviceList, last_was_stop.
Referenced by mutabor::InputMidiPort::Proceed.
static void mutabor::InputDeviceClass::StopAll()
Stop all inupt devices.
References mutabor::CommonTypedDeviceAPI< InputDeviceClass >::deviceList, mutabor::DevicePause, mutabor::DevicePlay, last_was_stop.
Referenced by mutabor::InputMidiPort::Proceed.
static void mutabor::InputDeviceClass::PauseAll()
Pause all input devices.
References mutabor::CommonTypedDeviceAPI< InputDeviceClass >::deviceList, last_was_stop.
Referenced by mutabor::InputMidiPort::Proceed.
static bool mutabor::InputDeviceClass::was_last_stop()
References last_was_stop.
static mutint64 mutabor::InputDeviceClass::GetNO_DELTA()
References mutint64.
Referenced by IsDelta, testCommonFileDeviceTimer::PrepareNextEvent, mutabor::InputGis::ReadOn, mutabor::CommonFileInputDevice::ThreadPlay.
mutabor::InputDeviceClass::InputDeviceClass(const std::string &name="", mutabor::MutaborModeType m=DeviceStop, int id=-1)
References mutabor::Device::Mode.
void mutabor::InputDeviceClass::outputs_handle_event(event e)
References mutabor::Device::routes.