mhDefs.h
REUSE
ICON
Referenced by mutaborGUI::MutFrame::CmRoutes.
SSCANF
Referenced by compat30::LoadRoutes.
mumT
Referenced by IMPLEMENT_APP.
MDI_FORCE_EXTERN
typedef std::list<wxPoint> mutpointlist
wxHtmlHelpController* HelpController
Referenced by IMPLEMENT_APP.
wxString muT(const char *x)
Referenced by muT.
wxString muT(const wxChar *x)
wxString muT(const std::string &s)
References muT.
MutFileDataType FileNameDialog(wxWindow *parent, int Command=CM_FILEOPEN, wxString Filename=wxEmptyString)
References _, MutFileDataType::Canceled, mutaborGUI::CM_EXECUTE, CM_FILEOPEN, CM_FILESAVEAS, mutaborGUI::CM_ROUTELOAD, mutaborGUI::CM_ROUTESAVE, mutaborGUI::CM_ROUTESAVEAS, DEBUGLOG2, MutFileDataType::LogicSource, MutFileDataType::name, MutFileDataType::type, MutFileDataType::Unknown, MutFileDataType::UTF8TextRoute, MutFileDataType::XMLRoute1.
Referenced by mutaborGUI::MutFrame::CmFileOpen, mutaborGUI::MutEditFile::CmFileSaveAs, mutaborGUI::MutRouteWnd::CmRouteLoad, mutaborGUI::MutRouteWnd::CmRouteSaveAs, IMPLEMENT_APP.
void UpdateRecursive(wxWindow *win)
Call update on a Window hierarchy recursively.
this function is very expensive. It should be called very rarly (as well as Update(). win Parent window that shall be updated.
void PRINTSIZER(wxSizer *sizer, const wxString &offset=_T(""))
References DEBUGLOG2, DEBUGLOGTYPE.
Referenced by mutaborGUI::MutRouteWnd::InitDevices, mutaborGUI::MutRouteWnd::InitShapes, MutIconShapeClass< T >::Layout, mutaborGUI::MutRouteWnd::OnDraw.