mutaborGUI::MutRouteWnd
wxSizer* mutaborGUI::MutRouteWnd::InputSizer
Referenced by AddInputDevice, GetInputDevices, GetShapeSizer.
wxSizer* mutaborGUI::MutRouteWnd::OutputSizer
Referenced by AddOutputDevice, GetOutputDevices, GetShapeSizer.
wxSizer* mutaborGUI::MutRouteWnd::BoxSizer
Referenced by AddBox, AddRoute, GetBoxes, GetShapeSizer.
MutInputDeviceShapeList mutaborGUI::MutRouteWnd::InputDevices
MutOutputDeviceShapeList mutaborGUI::MutRouteWnd::OutputDevices
MutBoxShapeList mutaborGUI::MutRouteWnd::Boxes
Referenced by AddBox.
MutFileDataType mutaborGUI::MutRouteWnd::MurFileData
mutaborGUI::MutRouteWnd::MutRouteWnd(wxWindow *parent=NULL, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
Constructor for MutRouteWnd class.
This constructor sets up the Routing window. It loads Icons, initializes sizers and creates the shapes of the different routing elements (e.g., devices and boxes). parent parent Window as used in wxWidgets. pos positions of the window (if unset use application default) size size of the window (if unset use the application default).
void MutRouteWnd::InitShapes()
fills the window with the corresponding shapes.
This function is used to initialize the window with the current routing information. It creates the shapes for devices, routes and new objects.
References box, mutaborGUI::DebugCheckRoutes, DEBUGLOG, mutabor::BoxClass::GetOrCreateBox, mutaborGUI::BoxData::GetShapes, mutASSERT, mutabor::NewBox, PRINTSIZER, mutaborGUI::ToGUIBase.
void MutRouteWnd::InitDevices()
References mutaborGUI::DebugCheckRoutes, PRINTSIZER.
Referenced by CmRouteLoad, IMPLEMENT_APP.
void MutRouteWnd::ClearDevices()
bool mutaborGUI::MutRouteWnd::AddInputDevice(MutInputDeviceShape *device, const wxSizerFlags &flags)
Adds an input device shape.
device (MutInputDeviceShape *) device to be added flags (wxSizerFlages &) Sizer flags, which shall be applied
References FitInside, InputSizer, mutASSERT.
Referenced by mutaborGUI::MutNewInputDeviceShape::replaceSelfBy.
void MutRouteWnd::ClearInputDevices()
Clears all input device shapes.
References TRACEC.
bool mutaborGUI::MutRouteWnd::AddOutputDevice(MutOutputDeviceShape *device, const wxSizerFlags &flags)
Adds an output device shape.
device (MutInputDeviceShape *) device to be added flags (wxSizerFlages &) Sizer flags, which shall be applied
References FitInside, mutASSERT, OutputSizer.
Referenced by mutaborGUI::MutNewOutputDeviceShape::replaceSelfBy.
void MutRouteWnd::ClearOutputDevices()
Clears all output device shapes.
References TRACEC.
bool mutaborGUI::MutRouteWnd::AddBox(MutBoxShape *box, const wxSizerFlags &flags)
Adds a box shape.
box (MutInputDeviceShape *) box to be added flags (wxSizerFlages &) Sizer flags, which shall be applied
References Boxes, BoxSizer, MutIconShapeClass< T >::Fit, FitInside, mutaborGUI::MutBoxIconShape::Layout, mutASSERT.
Referenced by mutaborGUI::GUIRouteFactory::DoCreateBoxChannelShape, mutaborGUI::NewMutBoxShape::replaceSelfBy.
bool mutaborGUI::MutRouteWnd::AddRoute(MutBoxChannelShape *channel, const wxSizerFlags &flags)
References mutaborGUI::MutBoxShape::Add, BoxSizer, mutaborGUI::MutBoxChannelShape::GetRoute, mutaborGUI::BoxData::GetShape, mutASSERT, mutaborGUI::ToGUIBase.
void MutRouteWnd::ClearBoxes()
Clears all box shapes.
References TRACEC.
wxSizer* mutaborGUI::MutRouteWnd::GetInputDevices() const
References InputSizer.
Referenced by mutaborGUI::MutBoxChannelShape::InitializeInputFilter.
wxSizer* mutaborGUI::MutRouteWnd::GetBoxes() const
References BoxSizer.
wxSizer* mutaborGUI::MutRouteWnd::GetOutputDevices() const
References OutputSizer.
Referenced by mutaborGUI::MutBoxChannelShape::InitializeOutputFilter.
void MutRouteWnd::OnSize(wxSizeEvent &event)
void MutRouteWnd::FitInside()
Referenced by AddBox, AddInputDevice, AddOutputDevice, CmRouteLoad, IMPLEMENT_APP.
void MutRouteWnd::OnPaint(wxPaintEvent &event)
void MutRouteWnd::OnDraw(wxDC &dc)
References box, DEBUGLOG, mutaborGUI::MutBoxShape::DrawLines, mutASSERT, PRINTSIZER, UNREACHABLEC.
void MutRouteWnd::OnMoveShape(wxCommandEvent &event)
References DEBUGLOG.
wxSizer* mutaborGUI::MutRouteWnd::GetShapeSizer()
wxSizer* mutaborGUI::MutRouteWnd::GetShapeSizer(T *shape)
void mutaborGUI::MutRouteWnd::MoveShape(T *shape, int newpos)
wxSizer* mutaborGUI::MutRouteWnd::GetShapeSizer()
References InputSizer.
wxSizer* mutaborGUI::MutRouteWnd::GetShapeSizer()
References OutputSizer.
wxSizer* mutaborGUI::MutRouteWnd::GetShapeSizer()
References BoxSizer.
void MutRouteWnd::createInputDevices(wxSizerFlags flags)
References DEBUGLOG, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList, mutASSERT, TRACEC.
void MutRouteWnd::createBoxes(wxSizerFlags flags)
References box, mutabor::BoxClass::GetBoxList, mutaborGUI::BoxData::GetShape, mutASSERT, mutaborGUI::ToGUIBase, TRACEC, UNREACHABLEC.
void MutRouteWnd::createRoutes(wxSizerFlags flags)
References mutaborGUI::MutBoxChannelShape::Add, mutaborGUI::MutDeviceShape< T >::Add, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetRouteList, mutaborGUI::BoxData::GetShape, mutASSERT, mutaborGUI::ToGUIBase, TRACEC.
void MutRouteWnd::createOutputDevices(wxSizerFlags flags)
References mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList, TRACEC.
void MutRouteWnd::CmRouteLoad(wxCommandEvent &event)
interactive route loading
This function opens a file open dialog in order to load a route configuration from disk storage. event (wxCommandEvent) event to be processed
References _, MutFileDataType::Canceled, mutabor::BoxClass::ClearBoxList, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::ClearDeviceList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::ClearDeviceList, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::ClearRouteList, mutaborGUI::CM_ROUTES, mutaborGUI::DebugCheckRoutes, FileNameDialog, FitInside, InitDevices, mutaborGUI::xmltree::Load, compat30::LoadRoutes, mutabor::RouteFactory::LoadRoutes, MutFileDataType::LogicSource, mutASSERT, MutFileDataType::name, MutFileDataType::TextRoute, MutFileDataType::type, MutFileDataType::Unknown, UNREACHABLE, MutFileDataType::UTF8TextRoute, WK_ROUTE, MutFileDataType::XMLRoute1.
Referenced by mutaborGUI::MutApp::CmRouteLoad.
void MutRouteWnd::CmRouteSave(wxCommandEvent &event)
save routes to disk.
This function saves the current routing conifiguriton into a file on disk storage. event (wxCommandEvent) event to be processed
References _, MutFileDataType::Canceled, MutFileDataType::LogicSource, compat30::SaveRoutes, mutabor::RouteFactory::SaveRoutes, MutFileDataType::TextRoute, TRACET, MutFileDataType::Unknown, UNREACHABLE, MutFileDataType::UTF8TextRoute, MutFileDataType::XMLRoute1.
Referenced by mutaborGUI::MutApp::CmRouteSave.
void MutRouteWnd::CmRouteSaveAs(wxCommandEvent &event)
save routes with a new file name
This function opens a file save dialog in order to save a route configuration to disk storage. event (wxCommandEvent) event to be processed
References _, MutFileDataType::Canceled, FileNameDialog, MutFileDataType::LogicSource, MutFileDataType::name, MutFileDataType::TextRoute, TRACET, MutFileDataType::type, MutFileDataType::Unknown, UNREACHABLE, MutFileDataType::UTF8TextRoute, MutFileDataType::XMLRoute1.
Referenced by mutaborGUI::MutApp::CmRouteSaveAs.
void MutRouteWnd::MoveShape(wxWindow *shape, int newpos, wxSizer *sizer)
Rally move shape.
This function should not be called from outside the class. It's here, because C++ does not allow partial specialisation of functions. shape Shape to be moved. newpos New position where the shape shall be dropped. sizer Sizer that is responsible for the dropped window
References mutASSERT.