ton.h
ton_typ
Absoluter Ton.
ton_einstell_typ
Ton soll nicht erklingen.
struct ton* list_of_toene
Referenced by check_tonsystem_konsistenz, check_umstimmungs_konsistenz, expandiere_tonsystem, mutabor_programm_einlesen.
struct ton* ton_ohne_namen
Frequenz=0.
void berechne_toene_absolut(struct ton *ton_liste)
Berechnet die absoluten Tonwerte für eine einfach verkettete Tonliste.
Dabei werden die globalen Variablen anzahl_toene, toene, visited und die Adjazenzmatrix benutzt. Falls mit DEBUG_ANZEIGE compiliert, wird die Matrix nach der Aufstellung auf der Standardausgabe ausgegeben. list_of_toene
References adjazent, anzahl_toene, belege_toene, berechne_ton_endgueltig, fatal_error, matrix, mutabor_debug_level, name, test_zyklen, ton_absolut, ton_komplex, ton_list_laenge, ton_nummer, ton::u, visited, xalloca, xde_alloca.
Referenced by mutabor_programm_einlesen.
void drucke_ton(struct ton *lauf)
Gibt einen Ton auf der Standardausgabe aus.
lauf Ton
References komplex_intervall::faktor, ton::name, komplex_intervall::name, komplex_intervall::next, ton_absolut, ton::ton_absolut, ton_komplex, ton::ton_komplex, ton::ton_typ, ton::u.
Referenced by mutabor_programm_einlesen.
void get_new_ton_absolut(char *name, double wert)
Fügt einen absoluten Ton ans Ende von list_of_toene an.
Taucht der Tonname schon einmal auf, wird ein fataler Fehler ausgegeben. name Bezeichnung des Tones, das angefügt werden soll wert Wert des Tones, der angfügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References fatal_error, name, ton::next, ton_absolut, ton::u, xmalloc.
Referenced by mutabor_programm_einlesen, switch, yyparse.
double get_komplex_frequenz(struct ton *dieser)
Berechnet deie Frequenz eines komplexen Tones.
dieser Ton, für den die Frequenz berechnet werden soll.
References get_komplex_faktor, get_ton, ton::ton_komplex, ton::u.
Referenced by expand_tonliste.
void init_komplex_ton_list(void)
Setzt Liste komplexer Intervalle auf NULL.
Die Liste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_new_ton_komplex_positive(char *name, char *bezugston)
Fügt einen komplexen Ton ans Ende von list_of_toene an.
Dabei wird mittels get_last_komplex_intervall() die letzte eingelesene Intevallliste verwendet. Taucht der Tonname schon einmal auf, wird ein fataler Fehler ausgegeben. name Bezeichnung des Tones, das angefügt werden soll bezugston Basiston, auf den sich die Intervallliste bezieht. Es wird immer die gesamte Liste durchsucht. Effektivität?
References ton::bezugston, fatal_error, get_last_komplex_intervall, name, ton::next, ton_komplex, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_new_ton_komplex_negative(char *name, char *bezugston)
Fügt einen komplexen Ton ans Ende von list_of_toene an.
Dabei wird mittels get_last_komplex_intervall() die letzte eingelesene Intevallliste verwendet. Diese wird jedoch zunächst einmal invertiert. Taucht der Tonname schon einmal auf, wird ein fataler Fehler ausgegeben. name Bezeichnung des Tones, das angefügt werden soll bezugston Basiston, auf den sich die Intervallliste bezieht. Es wird immer die gesamte Liste durchsucht. Effektivität?
References ton::bezugston, komplex_intervall::faktor, fatal_error, get_last_komplex_intervall, name, ton::next, komplex_intervall::next, ton_komplex, ton::u, xmalloc.
Referenced by switch, yyparse.
void init_nullton(void)
References ton::name, ton::next, ton_absolut, ton::ton_absolut, ton::ton_typ, ton::u, xmalloc.
Referenced by allgemeine_initialisierungen.
void init_ton_liste(void)
Setzt ton_liste auf NULL.
Die Liste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_new_ton_in_tonsystem(char *name)
Fügt einen Ton ans Ende von ton_liste an.
name Name des Tones Es wird immer die gesamte Liste durchsucht. Effektivität?
References name, ton::next, xmalloc.
Referenced by switch, yyparse.
int ton_list_laenge(struct ton *list)
Zählen der Elemente einer einfach verketteten Tonliste.
list Liste der Töne Anzahl der Elemente von list
References ton::next, ton_list_laenge.
Referenced by berechne_toene_absolut, mutabor::BoxClass::Compile, expandiere_tonsystem, mutabor_programm_einlesen, ton_list_laenge.
struct ton* get_ton(char *name, struct ton *liste)
Sucht einen ton aus einer Tonliste.
name Name des gesuchten Tones liste Liste der Töne, in der der Ton gesucht wird ton_ohne_namen falls name == NULL NULL falls Ton nicht in liste Ton sonst.
References get_ton, ton::name, ton::next.
Referenced by check_konsistenz, check_tonsystem_konsistenz, check_umstimmungs_konsistenz, expandiere_tonsystem, get_komplex_frequenz, get_ton.