mutabor::OutputDeviceClass
friend class DeviceFactory
Mutex mutabor::OutputDeviceClass::write_lock
Referenced by AddTime, Controller, GetChannel, Gis, handle_event, MidiOut, NoteOff, NoteOn, Open, Panic, Quiet, UpdateTones.
virtual mutabor::OutputDeviceClass::~OutputDeviceClass()
References mutabor::Device::IsOpen, mutASSERT, TRACEC.
void mutabor::OutputDeviceClass::NoteOn(Box box, int taste, int velo, RouteClass *r, size_t id, const ChannelData &input_channel_data)
References do_NoteOn, write_lock.
Referenced by CommonMidiOutputTest::testMoreNotesThanChannels, CommonMidiOutputTest::testNoteOnOff, OutputMidiFileTest::testNoteOnOff.
void mutabor::OutputDeviceClass::NoteOff(Box box, int taste, int velo, RouteClass *r, size_t id, bool is_note_on)
References do_NoteOff, write_lock.
Referenced by CommonMidiOutputTest::testNoteOnOff, OutputMidiFileTest::testNoteOnOff.
void mutabor::OutputDeviceClass::UpdateTones(RouteClass *route)
References do_UpdateTones, write_lock.
void mutabor::OutputDeviceClass::Controller(int mutabor_channel, int controller, int value, size_t id)
References do_Controller, write_lock.
int mutabor::OutputDeviceClass::GetChannel(int inkey, size_t channel, size_t id)
References do_GetChannel, write_lock.
void mutabor::OutputDeviceClass::Gis(GisToken *token, char turn)
References do_Gis, write_lock.
void mutabor::OutputDeviceClass::AddTime(frac time)
References do_AddTime, write_lock.
void mutabor::OutputDeviceClass::MidiOut(mutabor::Box box, midi_string data)
References do_MidiOut, write_lock.
void mutabor::OutputDeviceClass::MidiOut(uint8_t *p, size_t n)
References do_MidiOut, write_lock.
void mutabor::OutputDeviceClass::handle_event(event e)
References do_handle_event, write_lock.
Referenced by all_handle_event.
void mutabor::OutputDeviceClass::Quiet(Route r, int type)
References do_Quiet, write_lock.
void mutabor::OutputDeviceClass::Quiet(Route r, int type, size_t id)
References do_Quiet, write_lock.
void mutabor::OutputDeviceClass::Panic(int type)
reset the device if requested
References do_Panic, write_lock.
bool mutabor::OutputDeviceClass::Open()
References do_Open, write_lock.
Referenced by mutaborGUI::GUIMidiPortFactory::DoCreateOutput, mutaborGUI::GUIMidiFileFactory::DoCreateOutput, mutaborGUI::GUIGisFactory::DoCreateOutput, mutabor::OutputMidiPort::SetDevId, mutabor::CommonFileOutputDevice::SetName, mutabor::OutputGis::SetName, mutabor::OutputMidiFile::SetName, CommonMidiInputTest::testGlobalPanic, CommonMidiOutputTest::testMoreNotesThanChannels, CommonMidiOutputTest::testNoteOnOff, OutputMidiFileTest::testNoteOnOff, CommonMidiInputTest::testPanic.
virtual bool mutabor::OutputDeviceClass::NeedsRealTime()
virtual DevType mutabor::OutputDeviceClass::GetType() const
References mutabor::DTUnknown.
virtual std::string mutabor::OutputDeviceClass::GetTypeName() const
References _mutN.
mutabor::OutputDeviceClass::operator std::string() const
static void mutabor::OutputDeviceClass::all_handle_event(event e)
References mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::deviceList, handle_event.
Referenced by mutabor::InputMidiPort::Proceed, mutabor::InputMidiFile::Proceed, mutabor::CommonMidiInput< D >::Proceed.
mutabor::OutputDeviceClass::OutputDeviceClass()
mutabor::OutputDeviceClass::OutputDeviceClass(const std::string &name, int id=-1)
virtual void mutabor::OutputDeviceClass::do_NoteOn(Box box, int taste, int velo, RouteClass *r, size_t id, const ChannelData &input_channel_data)=0
Really Send the beginning of a sounding note.
box Mutabor box that contains the tuning information taste input key from file or keyboard velo key press velocity r route that has been used to transmit the note id an additional number that is used to make the note unique input_channel_data current device settings (Controllers, Sound, etc.) OutputDeviceClass::NoteOn, OutputDeviceClass::NoteOff
Referenced by NoteOn.
virtual void mutabor::OutputDeviceClass::do_NoteOff(Box box, int taste, int velo, RouteClass *r, size_t id, bool is_note_on)=0
Referenced by NoteOff.
virtual void mutabor::OutputDeviceClass::do_UpdateTones(RouteClass *route)=0
Referenced by UpdateTones.
virtual void mutabor::OutputDeviceClass::do_Controller(int mutabor_channel, int controller, int value, size_t id)=0
Referenced by Controller.
virtual int mutabor::OutputDeviceClass::do_GetChannel(int inkey, size_t channel, size_t id)=0
Referenced by GetChannel.
virtual void mutabor::OutputDeviceClass::do_Gis(GisToken *token, char turn)=0
Referenced by Gis.
virtual void mutabor::OutputDeviceClass::do_AddTime(frac time)=0
Referenced by AddTime.
virtual void mutabor::OutputDeviceClass::do_MidiOut(mutabor::Box box, midi_string data)=0
Referenced by MidiOut.
virtual void mutabor::OutputDeviceClass::do_MidiOut(uint8_t *p, size_t n)=0
virtual void mutabor::OutputDeviceClass::do_handle_event(event e)=0
Referenced by handle_event.
virtual void mutabor::OutputDeviceClass::do_Quiet(Route r, int type)=0
Referenced by Quiet.
virtual void mutabor::OutputDeviceClass::do_Quiet(Route r, int type, size_t id)=0
virtual void mutabor::OutputDeviceClass::do_Panic(int type)
References STUBC.
Referenced by Panic.
virtual bool mutabor::OutputDeviceClass::do_Open()
Referenced by Open.