Execute.cpp
_
Referenced by mutaborGUI::RoutePanel::AddBox, BEGIN_EVENT_TABLE, mutaborGUI::BEGIN_EVENT_TABLE, berechne_intervall_endgueltig, berechne_intervalle_absolut, berechne_toene_absolut, berechne_ton_endgueltig, MutTextBox::BoxChangedAction, check_aktionen, check_ausloeser, check_komplex_intervall, check_konsistenz, OutputMidiFileTest::CheckOut, mutaborGUI::MutFrame::CloseAll, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::CmFileOpen, mutaborGUI::MutConfigDialog::CmHelp, mutaborGUI::MutFrame::CmInDevPlay, mutaborGUI::MutRouteWnd::CmRouteLoad, mutaborGUI::MutFrame::CmRoutes, mutaborGUI::MutRouteWnd::CmRouteSave, mutaborGUI::MutRouteWnd::CmRouteSaveAs, mutaborGUI::MutFrame::CmSetTitle, mutaborGUI::MutEditFile::Compile, mutabor::BoxClass::Compile, mutaborGUI::MutNewInputDeviceShape::Create, mutaborGUI::MutNewOutputDeviceShape::Create, mutaborGUI::MutChild::deleteFromWinAttrs, mutaborGUI::MutEditFile::DoFind, mutaborGUI::MutBoxShape::DoLeftDblClick, mutaborGUI::MutEditFile::DoLoadFile, mutaborGUI::DontWant, mutaborGUI::MutEditFile::DoSaveFile, mutaborGUI::RouteRemoveButton::EnableRoute, END_EVENT_TABLE, execute_aktion, expand_aktions_liste, expand_harmony_analysis, expand_pattern, expand_tonliste, expandiere_logik, expandiere_midi, expandiere_name, expandiere_umstimmung, FileNameDialog, fprint_argument, generate_argument_list, get_ausloeser_taste, get_instrument_dekl, get_intervall_wert, get_komplex_faktor, get_logik_nummer, get_new_harmonie, get_new_intervall, get_new_intervall_komplex, get_new_logik, get_new_ton_absolut, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_umstimmung_umstimm_case, get_umstimmung_umstimmungs_bund, get_umstimmung_wiederholung_abs_negative, get_wert_komplex_intervall, MutTextBox::GetKeys, mutabor::BoxClass::GetLabel, MutTextBox::GetToneSystem, mutabor::BoxClass::GetTypeName, IMPLEMENT_APP, IMPLEMENT_DYNAMIC_CLASS, init_umstimmung, mutaborGUI::BoxDlg::InitializeBoxTypes, mutaborGUI::NewMutBoxShape::InitializeDialog, mutaborGUI::MutBoxChannelShape::InitializeInputFilter, mutaborGUI::MutBoxChannelShape::InitializeOutputFilter, mutaborGUI::initMutBitmap, insert_in_globale_liste, insert_in_lokale_liste, intervall_nummer, mutaborGUI::IsOpen, mutaborGUI::IsWanted, link_arguments_to_parameters, mutabor::OutputMidiPort::Load, mutabor::InputMidiPort::Load, mutabor::OutputMidiFile::Load, mutabor::InputMidiFile::Load, local_harmony_analysis, mutaborGUI::MutFrame::LogicWinOpen, mutaborGUI::MutLogicWnd::MakeTitle, MutTextBox::MakeTitle, mutabor_error_type_to_string, mutAssertFailure, mutaborGUI::MutEditProperties::MutEditProperties, mutaborGUI::MutFrame::MutFrame, MutTextBox::OnClose, mutaborGUI::MutEditFile::OnFindDialog, mutaborGUI::MutEditFile::OnGoto, mutabor::MidiPortOutputProvider::Open, mutabor::InputGis::Open, mutabor::InputMidiPort::Open, mutabor::InputMidiFile::Open, mutabor::OpenAll, mutaborGUI::MutFrame::OpenFile, print_argumentliste, resolve_parameters, compat30::SaveRoutes, mutaborGUI::MutBoxShape::SetBox, mutabor::OutputMidiPort::SetDevId, mutabor::InputMidiPort::SetDevId, mutaborGUI::StatusBar::SetInsert, switch, test_zyklen, test_zyklen_nummer, mutaborGUI::MutFrame::TextBoxOpen, mutaborGUI::MutFrame::ToggleTextBox, ton_nummer, u_test_zyklen, mutaborGUI::MutLogicWnd::UpDate, mutaborGUI::MutFrame::UpdateBoxMenu, mutaborGUI::InputDevDlg::UpdateLayout, MutTextBox::UpdateUI, xalloca, xcalloc, xmalloc, xrealloc, ymalloc, yyerror, yylex.
KEY_CHANGED
Referenced by AddKey, DeleteKey.
struct mutabor_callback_type default_callbacks
mutabor_callback_type* mutabor_callbacks
Referenced by mutabor_get_callbacks, mutabor_set_callbacks.
int protokollfunktionen_aktiv
int protokollfunktion_aktionsausgabe
int zeige_aktuelles_tonsystem
const char * mutabor_error_type_to_string(mutabor_error_type type)
References _, compiler_error, compiler_warning, error, internal_error, runtime_error, runtime_warning, warning.
Referenced by mutabor_default_error_message, mutabor::to_string.
static void mutabor_default_update(mutabor_box_type *box, unsigned int flags)
static void mutabor_default_midi_out(mutabor_box_type *box, struct midiliste *outliste)
static void mutabor_default_error_message(mutabor_box_type *box, mutabor_error_type type, const char *message)
References mutabor_error_type_to_string.
static void mutabor_default_update_display(mutabor_box_type *box, int line_number)
static void mutabor_default_log_action(mutabor_box_type *box, const char *action)
static void mutabor_default_lock(mutabor_logic_parsed *logic)
mutabor_callback_type * mutabor_set_callbacks(mutabor_callback_type *callbacks)
Set the callbacks for the mutabor backend.
callbacks pointer to the object that holds all calbacks that are needed for the backend to run; old callback object.
References mutabor_callbacks.
Referenced by mutabor::initialize_box_data, BoxTest::setUp.
mutabor_callback_type * mutabor_get_callbacks()
Get the currently active callback object.
pointer to the currently active callback object
References mutabor_callbacks.
void update_pattern(mutabor_box_type *box)
Reset boxes.
References TSYS::breite, for, mutabor_find_key_in_box, mutabor_get_note_index, mutabor_box_type::pattern, mutabor_box_type::tonesystem, PTRN::tonigkeit, TRACE.
Referenced by execute_aktion.
void change_breite(mutabor_box_type *box, int neu)
References TSYS::anker, TSYS::breite, DEBUGLOG2, mutabor_get_note_frequency, MUTABOR_KEYRANGE_MAX_WIDTH, TSYS::periode, TSYS::ton, mutabor_box_type::tonesystem.
Referenced by execute_aktion.
void change_anker(mutabor_box_type *box, int neu)
References TSYS::anker, TSYS::breite, mutabor_box_type::distance, mutabor_get_note_frequency, MUTABOR_KEYRANGE_MAX_KEY, MUTABOR_KEYRANGE_MIN_KEY, TSYS::periode, TSYS::ton, mutabor_box_type::tonesystem, mutabor_box_type::tonesystem_memory, TRACE.
Referenced by execute_aktion.
void keyboard_analyse(int taste)
Referenced by KeyboardIn.
void HarmonyAnalysis(mutabor_box_type *box, PATTERNN *pattern)
References mutabor_box_type::current_logic, mutabor_box_type::file, mutabor_box_type::flags, mutabor_logic_parsed::global_harmonies, logik::harmony_list, local_harmony_analysis, mutabor_box_flags::local_harmony_before_global, mutASSERT, TRACE, UNREACHABLE.
Referenced by AddKey, DeleteKey, execute_aktion.
void execute_aktion(mutabor_box_type *box, struct do_aktion *aktion, struct interpreter_parameter_list *parameters)
References _, TSYS::anker, aufruf_harmony_analysis, aufruf_logik, aufruf_midi_out, do_aktion::aufruf_midi_out, aufruf_tonsystem, do_aktion::aufruf_tonsystem, do_aktion::aufruf_typ, aufruf_umst_breite_abs, aufruf_umst_breite_rel, do_aktion::aufruf_umst_breite_rel, aufruf_umst_taste_abs, aufruf_umst_taste_rel, do_aktion::aufruf_umst_taste_rel, aufruf_umst_toene_veraendert, do_aktion::aufruf_umst_toene_veraendert, aufruf_umst_umst_bund, aufruf_umst_umst_case, do_aktion::aufruf_umst_umst_case, aufruf_umst_wiederholung_abs, do_aktion::aufruf_umst_wiederholung_abs, aufruf_umst_wiederholung_rel, TSYS::breite, call_actions, do_aktion::calling, case_element::case_aktion, case_element::case_wert, change_anker, change_breite, mutabor_box_type::current_logic, interpreter_parameter_list::data, einstell_absolut, ton_einstell::einstell_absolut, einstell_gleich, einstell_relativ, ton_einstell::einstell_relativ, einstell_stumm, logik::einstimmung, HarmonyAnalysis, internal_error, case_element::is_default, do_aktion::logic, midiliste::midi_code, mutabor_box_changed, mutabor_convert_interval_to_pitch, mutabor_error_message, mutabor_keys_changed, mutabor_log_action, mutabor_midi_out, mutabor_update, mutASSERT, do_aktion::name, midiliste::next, ton_einstell::next, case_element::next, mutabor_box_type::pattern, TSYS::periode, interpreter_parameter_list::size, TSYS::ton, ton_einstell::ton_einstell_typ, mutabor_box_type::tonesystem, TRACE, ton_einstell::u, do_aktion::u, UNREACHABLE, update_pattern.
Referenced by call_actions.
static void call_actions(mutabor_box_type *box, struct do_aktion *aktion_list, struct interpreter_parameter_list *parameters)
References TSYS::anker, interpreter_argument::constant, mutabor_box_type::current_parameters, interpreter_parameter_list::data, interpreter_argument_list::data, mutabor_box_type::distance, execute_aktion, mutabor_box_type::file, interpreter_argument::index, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, mutASSERT, interpreter_parameter_list::next, mutabor_logic_parsed::parameter_count, mutabor_box_type::parameters, interpreter_parameter_list::size, interpreter_argument_list::size, mutabor_box_type::tonesystem, interpreter_argument_list::types, ycalloc, ymalloc.
Referenced by execute_aktion, local_harmony_analysis, local_keyboard_analysis, local_midi_analysis.
int tiefste_taste(mutabor_box_type *box)
return the smallest key pressed actually
References mutabor_box_type::key_count, mutabor_find_key_in_box, mutabor_note_type::next, mutabor_note_type::number, TRACE, UNREACHABLE.
Referenced by local_harmony_analysis.
int hoechste_taste(mutabor_box_type *box)
return the largest key pressed actually
References mutabor_box_type::key_count, mutabor_find_key_in_box, mutabor_note_type::next, mutabor_note_type::number, TRACE, UNREACHABLE.
Referenced by local_harmony_analysis.
int compare_harmonie(int breite, int startindex, PATTERNN *laufzeit, PATTERNN *vergleich)
References PTRN::tonigkeit, TRACE.
Referenced by local_harmony_analysis.
bool local_harmony_analysis(mutabor_box_type *box, struct harmonie_ereignis *trigger, PATTERNN *harmony)
References _, TSYS::breite, call_actions, compare_harmonie, mutabor_box_type::distance, any_trigger::harmony, any_trigger::harmony_trigger, hoechste_taste, internal_error, mutabor_box_type::last_trigger, mutabor_action_changed, mutabor_error_message, mutabor_get_note_index, MUTABOR_INVALID_KEY, mutabor_is_else_path, mutabor_is_harmonic_form, mutabor_is_no_harmonic_form, MUTABOR_NO_KEY, mutabor_update, harmonie_ereignis::next, tiefste_taste, mutabor_box_type::tonesystem, TRACE, any_trigger::type.
Referenced by HarmonyAnalysis.
void AddKey(mutabor_box_type *box, int taste, size_t id, size_t channel, void *userdata)
References mutabor_note_type::channel, DEBUGLOG2, HarmonyAnalysis, mutabor_note_type::id, KEY_CHANGED, mutabor_create_key_in_box, mutabor_get_note_index, mutabor_note_type::number, mutabor_box_type::pattern, mutabor_box_type::tonesystem, PTRN::tonigkeit, mutabor_note_type::userdata.
Referenced by mutabor::BoxClass::AddNote, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.
void DeleteKey(mutabor_box_type *box, int taste, size_t id, size_t channel)
References box, DEBUGLOG2, HarmonyAnalysis, mutabor_note_type::id, KEY_CHANGED, mutabor_box_type::last_key, mutabor_delete_key_in_box, mutabor_find_key_in_box, mutabor_get_note_index, mutabor_note_type::next, mutabor_note_type::number, mutabor_box_type::pattern, mutabor_box_type::tonesystem, PTRN::tonigkeit, TRACE.
Referenced by mutabor::BoxClass::DeleteNote, boxTest::testBug1Permutation2.
void KeyboardIn(mutabor_box_type *box, const char *keys)
References KeyboardAnalyse, KeyboardAnalyseSimple, TRACE.
static bool local_midi_analysis(mutabor_box_type *box, struct midi_ereignis *event, BYTE midiByte)
References midi_ereignis::aktion, call_actions, midi_ereignis::first_pos, mutabor_box_type::last_trigger, any_trigger::midi, any_trigger::midi_trigger, mutabor_action_changed, mutabor_update, midi_ereignis::next, midi_ereignis::scan_pos, any_trigger::type.
Referenced by MidiAnalysis.
void MidiAnalysis(mutabor_box_type *box, BYTE midiByte)
References mutabor_box_type::current_logic, mutabor_box_type::file, mutabor_box_type::flags, mutabor_logic_parsed::global_midi_inputs, local_midi_analysis, mutabor_box_flags::local_midi_before_global, logik::midi_input_list, mutASSERT, TRACE, UNREACHABLE.
Referenced by mutabor::BoxClass::MidiAnalysis.
static bool local_keyboard_analysis(mutabor_box_type *box, struct keyboard_ereignis *event, int key, char is_logic, char is_simple)
References call_actions, any_trigger::key, any_trigger::key_trigger, mutabor_box_type::last_trigger, mutabor_action_changed, mutabor_update, keyboard_ereignis::next, any_trigger::type.
Referenced by generic_keyboard_analysis.
static void generic_keyboard_analysis(mutabor_box_type *box, int taste, char isLogic, char isSimple)
References mutabor_box_type::current_logic, mutabor_box_type::file, mutabor_box_type::flags, mutabor_logic_parsed::global_keystrokes, logik::keystroke_list, local_keyboard_analysis, mutabor_box_flags::local_keyboard_before_global, mutASSERT, TRACE, UNREACHABLE.
Referenced by KeyboardAnalyse, KeyboardAnalyseSimple.
void KeyboardAnalyse(mutabor_box_type *box, int taste, char isLogic)
References generic_keyboard_analysis.
Referenced by mutabor::BoxClass::KeyboardAnalysis, KeyboardIn.
void KeyboardAnalyseSimple(mutabor_box_type *box, int taste)
References generic_keyboard_analysis.
Referenced by mutabor::BoxClass::KeyboardAnalysis, KeyboardIn.