mutabor::BoxClass::CompileCallback
virtual void mutabor::BoxClass::CompileCallback::Refresh()=0
Referenced by mutabor::BoxClass::Compile.
virtual void mutabor::BoxClass::CompileCallback::SetStatus(std::string status)=0
Referenced by mutabor::BoxClass::Compile.
virtual void mutabor::BoxClass::CompileCallback::SetMessage(std::string message)=0
Referenced by mutabor::BoxClass::Compile.
virtual void mutabor::BoxClass::CompileCallback::SetStatus(int logics, int tones, int tunings, int tone_systems, int intervals, int characters)=0
virtual void mutabor::BoxClass::CompileCallback::SetLine(int number)=0
Referenced by mutabor::BoxClass::compile_callback.