GUI
WinKind
typedef std::list<wxPoint> mutpointlist
typedef T MutIconShapeClass< T >::parenttype
typedef MutIconShapeClass<wxControl> MutIconShape
typedef wxDocChildFrame mutaborGUI::MutFrame::base
typedef std::map<int,mutabor::Box> mutaborGUI::MutFrame::boxCommandMap
int CompDlgSilenceMudflapBuild
wxHtmlHelpController* HelpController
Referenced by IMPLEMENT_APP.
MutIcon MutIconShapeClass< T >::Icon
the icon
Referenced by MutIconShapeClass< MutPanel >::GetIcon, MutIconShapeClass< MutPanel >::GetIconRect, MutIconShapeClass< MutPanel >::SetIcon.
wxStaticText* MutIconShapeClass< T >::staticText
Referenced by MutIconShapeClass< MutPanel >::SetLabel.
wxSize MutIconShapeClass< T >::maxBorderSize
Referenced by MutIconShapeClass< MutPanel >::GetIconRect.
wxSize MutIconShapeClass< T >::borderOffset
mutpointlist MutIconShapeClass< T >::usedperimeterpoints
Referenced by MutIconShapeClass< MutPanel >::ClearPerimeterPoints.
mutaborGUI::CompDlg* CompDia
wxMenu* mutaborGUI::MutFrame::editmenu
Referenced by mutaborGUI::MutFrame::MutFrame, mutaborGUI::MutFrame::SetEditMenu.
wxMenu* mutaborGUI::MutFrame::filemenu
Referenced by mutaborGUI::MutFrame::MutFrame, mutaborGUI::MutFrame::SetFileMenu, mutaborGUI::MutFrame::~MutFrame.
int mutaborGUI::MutFrame::curStatusImg
wxAuiManager mutaborGUI::MutFrame::auimanager
Referenced by mutaborGUI::MutFrame::CloseClientWindow, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::CmRoutes, mutaborGUI::MutFrame::DoBoxWindowsClose, mutaborGUI::MutFrame::DoStop, mutaborGUI::MutFrame::EventPassOn, mutaborGUI::MutFrame::GetDockArt, mutaborGUI::MutFrame::LogicWinOpen, mutaborGUI::MutFrame::MutFrame, mutaborGUI::MutFrame::SetClient, mutaborGUI::MutFrame::TextBoxOpen, mutaborGUI::MutFrame::~MutFrame.
wxWindow* mutaborGUI::MutFrame::client
Referenced by mutaborGUI::MutFrame::CeActivate, mutaborGUI::MutFrame::CmFileNew, mutaborGUI::MutFrame::CmFileOpen, mutaborGUI::MutFrame::CmRoutes, mutaborGUI::MutFrame::HasClient, mutaborGUI::MutFrame::LogicWinOpen, mutaborGUI::MutFrame::MutFrame, mutaborGUI::MutFrame::OnEraseBackground, mutaborGUI::MutFrame::OpenFile, mutaborGUI::MutFrame::PassEventToEditor, mutaborGUI::MutFrame::PassEventToEditorFind, mutaborGUI::MutFrame::PassEventToEditorUI, mutaborGUI::MutFrame::repaint_route, mutaborGUI::MutFrame::SetClient, mutaborGUI::MutFrame::TextBoxOpen.
MutFrame* mutaborGUI::MutFrame::ActiveWindow
Referenced by mutaborGUI::MutFrame::BoxWindowsClose, mutaborGUI::MutFrame::BoxWindowsOpen, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::DoStop, mutaborGUI::MutFrame::GetActiveDocument, mutaborGUI::MutFrame::GetActiveWindow, mutaborGUI::MutFrame::OnCloseWindow, mutaborGUI::MutFrame::RaiseLogic, mutaborGUI::MutFrame::RaiseTheFrame, mutaborGUI::MutFrame::ToggleTextBox.
std::map< int, mutabor::Box > mutaborGUI::MutFrame::boxCommandIds
Referenced by mutaborGUI::MutFrame::Destroy, mutaborGUI::MutFrame::RaiseLogic, mutaborGUI::MutFrame::UpdateBoxMenu.
bool mutaborGUI::asTS
Referenced by IMPLEMENT_APP, mutaborGUI::MutConfigDialog::MutConfigDialog, mutaborGUI::MutFrame::TextBoxOpen, MutTextBox::UpdateUI.
bool mutaborGUI::SaveEditor
Referenced by mutaborGUI::MutEditFile::Compile, IMPLEMENT_APP, mutaborGUI::MutConfigDialog::MutConfigDialog.
bool mutaborGUI::UseColorBars
Referenced by IMPLEMENT_APP, mutaborGUI::MutConfigDialog::MutConfigDialog.
bool mutaborGUI::OWM
Referenced by mutaborGUI::MutFrame::CeToggleOWM, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::CmToggleOWM.
bool mutaborGUI::CAW
Referenced by mutaborGUI::MutFrame::CeToggleCAW, mutaborGUI::MutFrame::CmToggleCAW, MutTextBox::MakeTitle, mutaborGUI::MutFrame::TextBoxOpen.
bool mutaborGUI::LogicOn
Referenced by BEGIN_EVENT_TABLE, mutaborGUI::MutFrame::CeActivate, mutaborGUI::MutFrame::CeExecute, mutaborGUI::MutFrame::CeInDevPlay, mutaborGUI::MutFrame::CeStop, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::CmInDevPlay, mutaborGUI::MutFrame::CmPanic, mutaborGUI::MutFrame::CmRoutes, mutaborGUI::MutFrame::CmToggleCAW, mutaborGUI::MutFrame::CmToggleOWM, mutaborGUI::MutEditFile::Compile, mutaborGUI::GUIMidiPortFactory::DoCreateInput, mutaborGUI::GUIMidiFileFactory::DoCreateInput, mutaborGUI::GUIGisFactory::DoCreateInput, mutaborGUI::GUIMidiPortFactory::DoCreateOutput, mutaborGUI::GUIMidiFileFactory::DoCreateOutput, mutaborGUI::GUIGisFactory::DoCreateOutput, mutaborGUI::MutBoxShape::DoLeftDblClick, mutaborGUI::MutDeviceShape< T >::DoLeftDblClick, mutaborGUI::MutFrame::DoStop, MutTextBox::OnClose, mutaborGUI::MutFrame::OnCreateStatusBar, mutaborGUI::BoxData::set_routefile_id, mutaborGUI::MutFrame::ToggleTextBox.
wxString mutaborGUI::CompiledFile
Referenced by mutaborGUI::MutLogicWnd::CmBox, mutaborGUI::MutEditFile::Compile, mutaborGUI::MutLogicWnd::MakeTitle.
int MutIconSilenceMudflapBuild
const wxString TextBoxTitle[][]
Referenced by MutTextBox::MakeTitle.
const wxChar MutPanelNameStr[][]
wxString muT(const char *x)
Referenced by muT.
wxString muT(const wxChar *x)
wxString muT(const std::string &s)
References muT.
MutFileDataType FileNameDialog(wxWindow *parent, int Command=CM_FILEOPEN, wxString Filename=wxEmptyString)
References _, MutFileDataType::Canceled, mutaborGUI::CM_EXECUTE, CM_FILEOPEN, CM_FILESAVEAS, mutaborGUI::CM_ROUTELOAD, mutaborGUI::CM_ROUTESAVE, mutaborGUI::CM_ROUTESAVEAS, DEBUGLOG2, MutFileDataType::LogicSource, MutFileDataType::name, MutFileDataType::type, MutFileDataType::Unknown, MutFileDataType::UTF8TextRoute, MutFileDataType::XMLRoute1.
Referenced by mutaborGUI::MutFrame::CmFileOpen, mutaborGUI::MutEditFile::CmFileSaveAs, mutaborGUI::MutRouteWnd::CmRouteLoad, mutaborGUI::MutRouteWnd::CmRouteSaveAs, IMPLEMENT_APP.
void UpdateRecursive(wxWindow *win)
Call update on a Window hierarchy recursively.
this function is very expensive. It should be called very rarly (as well as Update(). win Parent window that shall be updated.
void PRINTSIZER(wxSizer *sizer, const wxString &offset=_T(""))
References DEBUGLOG2, DEBUGLOGTYPE.
Referenced by mutaborGUI::MutRouteWnd::InitDevices, mutaborGUI::MutRouteWnd::InitShapes, MutIconShapeClass< T >::Layout, mutaborGUI::MutRouteWnd::OnDraw.
void PRINTWINDOW(wxWindow *window, const wxString &offset=_T(""))
References DEBUGLOG2, mutUnused.
BEGIN_EVENT_TABLE_TEMPLATE1(MutIconShapeClass, T, T) EVT_SIZE(MutIconShapeClass
wx >= 2.9.0 uses its own template support
Noch zu erledigenCheck out how wxWidgets 2.9 supports templates
References mutASSERT, TRACEC.
NoTabStaticText::NoTabStaticText(wxWindow *parent, wxWindowID id, const wxString &name)
virtual NoTabStaticText::~NoTabStaticText()
bool NoTabStaticText::AcceptsFocusFromKeyboard()
MutIconShapeClass< T >::MutIconShapeClass()
MutIconShapeClass< T >::MutIconShapeClass(wxWindow *parent, wxWindowID id)
bool MutIconShapeClass< T >::Create(wxWindow *parent, wxWindowID id=wxID_ANY)
Referenced by mutaborGUI::MutBoxIconShape::Create, mutaborGUI::MutBoxChannelShape::Create, mutaborGUI::MutDeviceShape< T >::Create, MutIconShapeClass< MutPanel >::MutIconShapeClass.
virtual MutIconShapeClass< T >::~MutIconShapeClass()
bool MutIconShapeClass< T >::Destroy()
Referenced by MutIconShapeClass< MutPanel >::DeleteSelfEvent, mutaborGUI::MutBoxChannelShape::Destroy, mutaborGUI::BoxData::Destroy.
void MutIconShapeClass< T >::SetIcon(const MutIcon &icon)
const MutIcon& MutIconShapeClass< T >::GetIcon() const
void MutIconShapeClass< T >::SetLabel(const wxString &st)
Referenced by mutaborGUI::NewMutBoxShape::Create, mutaborGUI::MutDeviceShape< T >::Create, mutaborGUI::MutOutputGuidoFileDeviceShape::SetLabel, mutaborGUI::MutOutputMidiFileDeviceShape::SetLabel, mutaborGUI::MutInputGuidoFileDeviceShape::SetLabel, mutaborGUI::MutInputMidiFileDeviceShape::SetLabel.
virtual MutIcon& MutIconShapeClass< T >::GetMutIcon()
Calculates the Icon to be used.
wxSize MutIconShapeClass< T >::DoGetBestSize() const
References DEBUGLOG, h, mutASSERT.
Referenced by mutaborGUI::GetStaticBoxSize.
void MutIconShapeClass< T >::UpdateBorder(long flag)
References mutUnused.
void MutIconShapeClass< T >::LostFocus()
References TRACEC.
void MutIconShapeClass< T >::GotFocus()
References DEBUGLOG, DEBUGLOGTYPE.
Referenced by mutaborGUI::BEGIN_EVENT_TABLE.
void MutIconShapeClass< T >::OnSize(wxSizeEvent &event)
void MutIconShapeClass< T >::OnGetFocus(wxFocusEvent &event)
References TRACEC.
void MutIconShapeClass< T >::OnKillFocus(wxFocusEvent &event)
References TRACEC.
void MutIconShapeClass< T >::OnMouseClick(wxMouseEvent &event)
References mutUnused, TRACEC.
void MutIconShapeClass< T >::OnPaint(wxPaintEvent &event)
void MutIconShapeClass< T >::OnMove(wxMoveEvent &event)
void MutIconShapeClass< T >::OnDraw(wxPaintDC &dc)
References DEBUGLOG.
Referenced by mutaborGUI::MutTag::OnDraw.
wxPoint MutIconShapeClass< T >::GetPerimeterPoint(const wxPoint &i, const wxPoint &o, wxWindow *paintingWindow) const
References DEBUGLOG, mutASSERT.
void MutIconShapeClass< T >::DrawPerimeterPoint(wxGraphicsContext &gc, const wxPoint &center, wxPoint p) const
virtual wxRect MutIconShapeClass< T >::GetIconRect() const
Referenced by mutaborGUI::MutTag::PaintCenteredText.
wxPoint MutIconShapeClass< T >::GetPositionInWindow(const wxWindow *win) const
Tries to find the correct position of the window in a parent window.
win parent window. position in win
bool MutIconShapeClass< T >::Recompute()
bool MutIconShapeClass< T >::Layout()
References DEBUGLOG, h, PRINTSIZER.
virtual void MutIconShapeClass< T >::Fit()
Referenced by mutaborGUI::MutRouteWnd::AddBox, mutaborGUI::MutBoxShape::DoLeftDblClick.
virtual bool MutIconShapeClass< T >::AcceptsFocus() const
void MutIconShapeClass< T >::DeleteSelf() __attribute__((deprecated))
void MutIconShapeClass< T >::DeleteSelfEvent(wxCloseEvent &event) __attribute__((deprecated))
void MutIconShapeClass< T >::ClearPerimeterPoints()
IMPLEMENT_APP(MutApp) namespace mutaborGUI
References _, mutaborGUI::asTS, mutaborGUI::BEGIN_EVENT_TABLE, mutabor::BoxClass::ClearBoxList, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::ClearDeviceList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::ClearDeviceList, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::ClearRouteList, CM_ABOUT, mutaborGUI::CM_ACTIVATE, mutaborGUI::CM_BRACEMATCH, mutaborGUI::CM_CHANGECASE, mutaborGUI::CM_CHANGELOWER, mutaborGUI::CM_CHANGEUPPER, mutaborGUI::CM_CHARSETANSI, mutaborGUI::CM_CHARSETMAC, mutaborGUI::CM_CHARSETUTF8, mutaborGUI::CM_COMPILE, mutaborGUI::CM_CONVERTCR, mutaborGUI::CM_CONVERTCRLF, mutaborGUI::CM_CONVERTEOL, mutaborGUI::CM_CONVERTLF, mutaborGUI::CM_DISPLAYEOL, mutaborGUI::CM_EXECUTE, CM_EXIT, CM_FILENEW, CM_FILEOPEN, mutaborGUI::CM_FINDNEXT, mutaborGUI::CM_FOLDTOGGLE, mutaborGUI::CM_GOTO, CM_HELP, mutaborGUI::CM_HELPCOMMON, mutaborGUI::CM_HELPHANDBOOK, CM_HELPINDEX, mutaborGUI::CM_HELPONHELP, mutaborGUI::CM_HELPREFERENCE, CM_HELPSEARCH, mutaborGUI::CM_HILIGHTFIRST, mutaborGUI::CM_HILIGHTLANG, mutaborGUI::CM_INDENTGUIDE, mutaborGUI::CM_INDEVPAUSE, mutaborGUI::CM_INDEVPLAY, mutaborGUI::CM_INDEVSTOP, mutaborGUI::CM_LINENUMBER, mutaborGUI::CM_LONGLINEON, mutaborGUI::CM_MOVE_DOWN, mutaborGUI::CM_MOVE_UP, mutaborGUI::CM_OVERTYPE, mutaborGUI::CM_PANIC, mutaborGUI::CM_PRINT_ERROR, mutaborGUI::CM_PROPERTIES, mutaborGUI::CM_READONLY, mutaborGUI::CM_REPLACENEXT, mutaborGUI::CM_ROUTELOAD, mutaborGUI::CM_ROUTES, mutaborGUI::CM_ROUTESAVE, mutaborGUI::CM_ROUTESAVEAS, mutaborGUI::CM_SELECTBOX, mutaborGUI::CM_SELECTLINE, mutaborGUI::CM_SETUP, mutaborGUI::CM_STOP, mutaborGUI::CM_TOGGLEACT, mutaborGUI::CM_TOGGLEKEY, mutaborGUI::CM_TOGGLETS, mutaborGUI::CM_USECHARSET, mutaborGUI::CM_WHITESPACE, mutaborGUI::CM_WRAPMODEON, mutaborGUI::cmCallExitId, mutaborGUI::MutFrame::CmFileNew, mutaborGUI::MutFrame::CmRoutes, mutabor::hidden::compiler_error, mutabor::hidden::compiler_warning, debug_is_all_deleted, debug_print_pointers, mutaborGUI::DebugCheckRoutes, DEBUGLOG, DEBUGLOGTYPE, END_EVENT_TABLE, mutabor::hidden::error, EVT_MENU, FileNameDialog, mutaborGUI::MutRouteWnd::FitInside, mutaborGUI::g_LanguagePrefs, mutaborGUI::g_LanguagePrefsSize, h, HelpController, InitDebugCommandLine, mutaborGUI::MutRouteWnd::InitDevices, mutaborGUI::InitGUIRouteFactories, mutabor::initialize_box_data, mutaborGUI::initMutIconShapes, mutabor::hidden::internal_error, LoadRoutes, mutabor::MidiInit, mutabor::MidiUninit, mumT, mutaborGUI::MUT_LAST, mutabor_assert_fail, mutUnused, mutaborGUI::MutFrame::OpenFile, PACKAGE_NAME, ProcessDebugCommandLine, GisReadArtHead::Read, mutaborGUI::MutFrame::RestoreState, mutabor::hidden::runtime_error, mutabor::hidden::runtime_warning, mutaborGUI::SaveEditor, SaveRoutes, mutabor_backtrace::set_global_print, mutaborGUI::MutFrame::SetFileMenu, mutabor::str, STUBC, mutabor::to_string, top_srcdir, TRACE, TRACEC, mutaborGUI::UseColorBars, mutabor::hidden::warning, WK_ROUTE.
WX_DECLARE_HASH_MAP(wxFrame *, wxFrame *, wxPointerHash, wxPointerEqual, FrameHash)
Declare a frame array as an hash table.
mutaborGUI::BEGIN_EVENT_TABLE(MutChild, MutTextBox) EVT_ACTIVATE(MutChild
References _, DEBUGLOG, mutASSERT, mutaborGUI::BoxData::SetActionsWindow, mutaborGUI::BoxData::SetKeyWindow, mutaborGUI::BoxData::SetTonesystemWindow, mutaborGUI::ToGUIBase, UNREACHABLEC, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by IMPLEMENT_APP, IMPLEMENT_DYNAMIC_CLASS.
bool mutaborGUI::IsOpen(WinKind kind, mutabor::Box &box)
References _, mutaborGUI::BoxData::GetActionsWindow, mutaborGUI::BoxData::GetKeyWindow, mutaborGUI::BoxData::GetLogicWindow, mutaborGUI::BoxData::GetTonesystemWindow, mutASSERT, mutaborGUI::ToGUIBase, UNREACHABLE, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by mutabor::CommonTypedDeviceAPI< T, P, L >::Destroy, mutabor::BoxClass::MoveRoutes, mutabor::CommonTypedDeviceAPI< T, P, L >::MoveRoutes, mutaborGUI::MutFrame::ToggleTextBox.
bool mutaborGUI::IsWanted(WinKind kind, mutabor::Box &box)
References _, mutASSERT, mutaborGUI::ToGUIBase, UNREACHABLE, mutaborGUI::BoxData::WantActionsWindow, mutaborGUI::BoxData::WantKeyWindow, mutaborGUI::BoxData::WantTonesystemWindow, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
void mutaborGUI::DontWant(WinKind kind, mutabor::Box &box)
References _, mutASSERT, mutaborGUI::ToGUIBase, UNREACHABLE, mutaborGUI::BoxData::WantActionsWindow, mutaborGUI::BoxData::WantKeyWindow, mutaborGUI::BoxData::WantTonesystemWindow, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
BEGIN_EVENT_TABLE(MutEditFile, wxStyledTextCtrl) EVT_MENU(CM_COMPILE
MutEditFile::CmCompile EVT_MENU(CM_COMPACT, MutEditFile::CmCompAct) EVT_MENU(CM_ACTIVATE
Referenced by IMPLEMENT_APP.
MutEditFile::CmCompile MutEditFile::CmCompAct EVT_MENU(CM_GETLINE, MutEditFile::CmGetLine) EVT_MENU(CM_HELPCONTEXT
MutEditFile::CmCompile MutEditFile::CmCompAct MutEditFile::CmHelpContext EVT_MENU(CM_PROPERTIES, MutEditFile::OnProperties) EVT_SIZE(MutEditFile
mutaborGUI::MutFrame::MutFrame(wxFrame *parent, const wxWindowID id, const wxString &title, const wxPoint &pos, const wxSize &size, const long style)
Constructor.
This constructor creates a new main window.
mutaborGUI::MutFrame::MutFrame(MutDocument *doc, MutView *v, wxFrame *frame, wxWindowID id, const wxString &title, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long type=wxDEFAULT_FRAME_STYLE, const wxString &name=wxT("Mutabor frame"))
References _, mutaborGUI::MutFrame::auimanager, mutaborGUI::MutFrame::client, mutaborGUI::MutFrame::DetermineFrameSize, mutaborGUI::MutFrame::editmenu, mutaborGUI::MutFrame::filemenu.
mutaborGUI::MutFrame::~MutFrame()
Destructor.
References mutaborGUI::MutFrame::auimanager, mutaborGUI::MutFrame::filemenu, mutASSERT, mutaborGUI::MutView::SetTextsw.
void mutaborGUI::MutFrame::PassEventToEditor(wxCommandEvent &event)
passes an event to the editor.
This function is used to pass one event to the client window. event Event to be passed
References mutaborGUI::MutFrame::client.
Referenced by mutaborGUI::MutFrame::CmFileOpen.
void mutaborGUI::MutFrame::PassEventToEditorUI(wxUpdateUIEvent &event)
passes an UpdateUIEvent to the editor.
This function is used to pass one event to the client window. event Event to be passed
References mutaborGUI::MutFrame::client.
void mutaborGUI::MutFrame::PassEventToEditorFind(wxFindDialogEvent &event)
passes a FindDialogEvent to the editor.
This function is used to pass one event to the client window. event Event to be passed
References mutaborGUI::MutFrame::client.
void mutaborGUI::MutFrame::EventPassOn(wxCommandEvent &event)
passes an event to the MDI client window.
VeraltetThis function was formerly used to pass one event to the client MDI window. event Event to be passed
References mutaborGUI::MutFrame::auimanager, DEBUGLOG.
void mutaborGUI::MutFrame::OnAuiChildEvent(wxAuiManagerEvent &event)
This function informs the child windows about AUI events.
It is an event handler AUI events.The AUI manager does not inform the childs directly. event Event as passed by wxWidgets.
void mutaborGUI::MutFrame::OnCloseWindow(wxCloseEvent &event)
Handles close event.
This function tries to determine, if we can close the current window.
References mutaborGUI::MutFrame::ActiveWindow, DEBUGLOG, mutaborGUI::MutFrame::Destroy, mutaborGUI::MutFrame::SaveState, TRACEC.
void mutaborGUI::MutFrame::OnPaint(wxPaintEvent &event)
Hande paint events for Document/View framework.
This function call the paint function
References mutUnused, STUBC.
void mutaborGUI::MutFrame::CmFileNew(wxCommandEvent &WXUNUSED(event))
This function creates a new file editor.
Handle new file event if we don't have a client yet.
References mutaborGUI::MutFrame::client, mutaborGUI::MutFrame::OpenFile, STUBC.
Referenced by IMPLEMENT_APP.
void mutaborGUI::MutFrame::CmFileOpen(wxCommandEvent &WXUNUSED(event))
Open an existing file if we don't have a client yet.
References _, mutaborGUI::MutFrame::client, CM_FILEOPEN, CM_FILESAVEAS, DEBUGLOG, FileNameDialog, mutaborGUI::MutFrame::OpenFile, mutaborGUI::MutFrame::PassEventToEditor, STUBC, UNREACHABLEC.
bool mutaborGUI::MutFrame::OpenFile(wxString path, bool newfile=false)
Opens the given file, if we don't have a client yet.
open a file in a new frame. path Path of the file to open Noch zu erledigenfile loading fails silently if it is not in the systems encoding.
References _, APPNAME, mutaborGUI::MutFrame::client, DEBUGLOG, mutaborGUI::MutEditFile::LoadFile, mutUnused, mutaborGUI::MutFrame::SetClient, STUBC.
Referenced by mutaborGUI::MutFrame::CmFileNew, mutaborGUI::MutFrame::CmFileOpen, IMPLEMENT_APP.
bool mutaborGUI::MutFrame::SetClient(wxWindow *win, const wxString &title)
Attach a client to the Frame.
Attach a client. window to be attached as the client.
References mutaborGUI::MutFrame::auimanager, mutaborGUI::MutFrame::client, DEBUGLOG, mutASSERT.
Referenced by mutaborGUI::MutFrame::OpenFile.
virtual void mutaborGUI::MutFrame::SetLabel(const wxString &label)
Set the window name, i.e. frame title.
void mutaborGUI::MutFrame::CmDoActivate(wxCommandEvent &event)
Get a file name to open static wxString FileNameDialog(wxWindow * parent);.
References _, mutabor::BoxClass::ActivateAll, mutaborGUI::MutFrame::ActiveWindow, mutaborGUI::StatusBar::AllSetActive, mutaborGUI::StatusBar::AllSetPlaystate, mutaborGUI::MutFrame::auimanager, mutaborGUI::MutFrame::BoxWindowsOpen, mutaborGUI::CheckBoxesUsed, Compiled, DEBUGLOG, mutabor::BoxClass::GetBox, mutabor::BoxClass::GetBoxList, mutaborGUI::BoxData::GetLogicWindow, mutaborGUI::LogicOn, mutaborGUI::MutChildApi::MakeTitle, mutabor::hidden::minimal_box_used, mutabor::NeedsRealTime, mutaborGUI::OWM, mutaborGUI::MutFrame::repaint_route, mutaborGUI::StatusBar::Stop, mutaborGUI::ToGUIBase, TRACEC, mutaborGUI::MutFrame::UpdateBoxMenu, WK_ACT, WK_KEY, WK_ROUTE.
Referenced by mutaborGUI::MutFrame::CmInDevPlay.
void mutaborGUI::MutFrame::RaiseLogic(wxCommandEvent &event)
References mutaborGUI::MutFrame::ActiveWindow, mutaborGUI::MutFrame::boxCommandIds, mutaborGUI::CM_BOX, DEBUGLOG, mutaborGUI::GetCurrentBox, mutaborGUI::BoxData::GetLogicWindow, muT, mutASSERT, mutaborGUI::MutFrame::RaiseTheFrame, mutaborGUI::SetCurrentBox, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::MutFrame::UpdateBoxMenu.
wxMenuItem * mutaborGUI::MutFrame::ClearMenuItem(int id)
References mutaborGUI::MutFrame::ClearSubMenu.
Referenced by mutaborGUI::MutFrame::DoStop, mutaborGUI::MutFrame::UpdateBoxMenu.
void mutaborGUI::MutFrame::ClearSubMenu(wxMenuItem *item)
References DEBUGLOG.
Referenced by mutaborGUI::MutFrame::ClearMenuItem.
void mutaborGUI::MutFrame::DoStop()
References mutaborGUI::MutFrame::ActiveWindow, mutaborGUI::StatusBar::AllSetActive, mutaborGUI::StatusBar::AllSetPlaystate, mutaborGUI::MutFrame::auimanager, mutaborGUI::MutFrame::ClearMenuItem, mutaborGUI::CM_SELECTBOX, mutaborGUI::StatusBar::Hide, mutaborGUI::LogicOn, mutASSERT, mutaborGUI::MutFrame::repaint_route, mutabor::BoxClass::StopAll, mutaborGUI::MutFrame::StopInDev, TRACEC.
Referenced by mutaborGUI::MutFrame::CmStop.
void mutaborGUI::MutFrame::CmStop(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::MutFrame::DoStop, mutUnused.
void mutaborGUI::MutFrame::CmPanic(wxCommandEvent &WXUNUSED(event))
References DEFAULT_PANIC, mutaborGUI::LogicOn, mutabor::Panic.
void mutaborGUI::MutFrame::CeExecute(wxUpdateUIEvent &event)
References mutaborGUI::LogicOn.
void mutaborGUI::MutFrame::CeActivate(wxUpdateUIEvent &event)
References mutaborGUI::MutFrame::client, mutaborGUI::LogicOn.
void mutaborGUI::MutFrame::CeStop(wxUpdateUIEvent &event)
References mutaborGUI::LogicOn.
void mutaborGUI::MutFrame::CmRoutes(wxCommandEvent &event)
References _, mutaborGUI::MutFrame::auimanager, mutaborGUI::MutFrame::client, DEBUGLOG, ICON, mutaborGUI::LogicOn, mutaborGUI::MutFrame::UpdateBoxMenu, WK_ROUTE.
Referenced by IMPLEMENT_APP.
void mutaborGUI::MutFrame::CmToggleKey(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::MutFrame::ToggleTextBox, WK_KEY.
void mutaborGUI::MutFrame::CmToggleTS(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::MutFrame::ToggleTextBox, WK_TS.
void mutaborGUI::MutFrame::CmToggleAct(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::MutFrame::ToggleTextBox, WK_ACT.
void mutaborGUI::MutFrame::CmToggleOWM(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::LogicOn, mutaborGUI::OWM, STUBC.
void mutaborGUI::MutFrame::CmToggleCAW(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::CAW, mutaborGUI::LogicOn, STUBC.
void mutaborGUI::MutFrame::CeToggleKey(wxUpdateUIEvent &event)
References DEBUGLOG, mutabor::BoxClass::get_routefile_id, mutaborGUI::GetCurrentBox, mutaborGUI::ToGUIBase, mutaborGUI::BoxData::WantKeyWindow.
void mutaborGUI::MutFrame::CeToggleTS(wxUpdateUIEvent &event)
References mutaborGUI::GetCurrentBox, mutaborGUI::ToGUIBase, mutaborGUI::BoxData::WantTonesystemWindow.
void mutaborGUI::MutFrame::CeToggleAct(wxUpdateUIEvent &event)
References mutaborGUI::GetCurrentBox, mutaborGUI::ToGUIBase, mutaborGUI::BoxData::WantActionsWindow.
void mutaborGUI::MutFrame::CeToggleOWM(wxUpdateUIEvent &event)
References mutaborGUI::OWM.
void mutaborGUI::MutFrame::CeToggleCAW(wxUpdateUIEvent &event)
References mutaborGUI::CAW.
void mutaborGUI::MutFrame::CmInDevStop(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::MutFrame::repaint_route, mutaborGUI::MutFrame::StopInDev.
void mutaborGUI::MutFrame::CmInDevPlay(wxCommandEvent &WXUNUSED(event))
References _, mutaborGUI::StatusBar::AllSetPlaystate, mutaborGUI::MutFrame::CmDoActivate, mutabor::CurrentTime, mutabor::CurrentTimer::isRealtime, mutaborGUI::LogicOn, mutaborGUI::StatusBar::Play, mutaborGUI::MutFrame::repaint_route, TRACEC.
void mutaborGUI::MutFrame::CmInDevPause(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::StatusBar::AllSetPlaystate, mutabor::DevicePlay, mutaborGUI::StatusBar::Pause, mutaborGUI::MutFrame::repaint_route.
void mutaborGUI::MutFrame::StopInDev()
References mutaborGUI::StatusBar::AllSetPlaystate, mutabor::DevicePause, mutabor::DevicePlay, mutaborGUI::StatusBar::Stop.
Referenced by mutaborGUI::MutFrame::CmInDevStop, mutaborGUI::MutFrame::DoStop.
void mutaborGUI::MutFrame::CeInDevStop(wxUpdateUIEvent &event)
References mutabor::DevicePause, mutabor::DevicePlay, mutabor::DTMidiFile.
void mutaborGUI::MutFrame::CeInDevPlay(wxUpdateUIEvent &event)
References DEBUGLOG, mutabor::DevicePause, mutabor::DeviceStop, mutabor::DTMidiFile, mutaborGUI::LogicOn.
void mutaborGUI::MutFrame::CeInDevPause(wxUpdateUIEvent &event)
References mutabor::DevicePlay, mutabor::DTMidiFile.
void mutaborGUI::MutFrame::CmSetTitle(wxCommandEvent &event)
References _, APPNAME.
void mutaborGUI::MutFrame::UpdateUI(wxCommandEvent &WXUNUSED(event))
Update GUI when the mutabor kernel or file players have acted.
void mutaborGUI::MutFrame::OnEraseBackground(wxEraseEvent &event)
References mutaborGUI::MutFrame::client.
void mutaborGUI::MutFrame::OnSize(wxSizeEvent &event)
wxAuiDockArt * mutaborGUI::MutFrame::GetDockArt()
References mutaborGUI::MutFrame::auimanager.
void mutaborGUI::MutFrame::SaveState()
Referenced by mutaborGUI::MutFrame::OnCloseWindow.
void mutaborGUI::MutFrame::RestoreState()
Referenced by IMPLEMENT_APP.
void mutaborGUI::MutFrame::LogicWinOpen(mutabor::Box box)
References _, mutaborGUI::MutFrame::auimanager, mutaborGUI::MutFrame::client, mutaborGUI::MutLogicWnd::MakeTitle, mutaborGUI::MutFrame::UpdateBoxMenu, WK_ROUTE.
void mutaborGUI::MutFrame::ToggleTextBox(WinKind kind)
References _, mutaborGUI::MutFrame::ActiveWindow, mutaborGUI::MutFrame::CloseClientWindow, DEBUGLOG, mutaborGUI::BoxData::GetActionsWindow, mutaborGUI::GetCurrentBox, mutaborGUI::BoxData::GetKeyWindow, mutaborGUI::BoxData::GetTonesystemWindow, mutaborGUI::IsOpen, mutaborGUI::LogicOn, mutASSERT, mutaborGUI::MutFrame::TextBoxOpen, mutaborGUI::BoxData::ToggleActionsWindow, mutaborGUI::BoxData::ToggleKeyWindow, mutaborGUI::MutFrame::ToggleTextBox, mutaborGUI::BoxData::ToggleTonesystemWindow, mutaborGUI::ToGUIBase, UNREACHABLEC, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by mutaborGUI::MutFrame::CmToggleAct, mutaborGUI::MutFrame::CmToggleKey, mutaborGUI::MutFrame::CmToggleTS, mutaborGUI::MutFrame::ToggleTextBox.
static void mutaborGUI::MutFrame::BoxWindowsOpen(mutabor::Box box, bool update=true)
References mutaborGUI::MutFrame::ActiveWindow, mutaborGUI::MutFrame::DoBoxWindowsOpen.
Referenced by mutaborGUI::MutFrame::CmDoActivate.
static void mutaborGUI::MutFrame::BoxWindowsClose(mutabor::Box box, bool update=true)
References mutaborGUI::MutFrame::ActiveWindow, mutaborGUI::MutFrame::DoBoxWindowsClose.
void mutaborGUI::MutFrame::DoBoxWindowsOpen(mutabor::Box box, bool update=true)
References mutUnused, STUBC, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::MutFrame::BoxWindowsOpen.
void mutaborGUI::MutFrame::DoBoxWindowsClose(mutabor::Box box, bool update=true)
References mutaborGUI::MutFrame::auimanager, mutaborGUI::MutFrame::CloseClientWindow, mutaborGUI::BoxData::GetActionsWindow, mutaborGUI::BoxData::GetKeyWindow, mutaborGUI::BoxData::GetLogicWindow, mutaborGUI::BoxData::GetTonesystemWindow, mutaborGUI::ToGUIBase, UNREACHABLEC, mutaborGUI::MutFrame::UpdateBoxMenu, WK_ROUTE.
Referenced by mutaborGUI::MutFrame::BoxWindowsClose.
void mutaborGUI::MutFrame::TextBoxOpen(WinKind kind, mutabor::Box &box, bool update_auimanager=true)
References _, mutaborGUI::asTS, mutaborGUI::MutFrame::auimanager, mutaborGUI::CAW, mutaborGUI::MutFrame::client, DEBUGLOG, MutTextBox::GetAllActions, MutTextBox::GetBoxActions, MutTextBox::GetKeys, MutTextBox::GetKind, MutTextBox::GetToneSystem, mutaborGUI::MutChild::MakeTitle, mutASSERT, mutabor::NoBox, mutabor::str, UNREACHABLEC, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by mutaborGUI::BoxData::DoOpen, mutaborGUI::MutFrame::ToggleTextBox.
void mutaborGUI::MutFrame::CmSelectBox()
void mutaborGUI::MutFrame::CmCloseChild()
References mutaborGUI::ChildToClose.
void mutaborGUI::MutFrame::CloseAll(WinKind kind=WK_NULL)
bool mutaborGUI::MutFrame::Destroy()
References mutaborGUI::MutFrame::boxCommandIds.
Referenced by mutaborGUI::MutFrame::OnCloseWindow.
wxRect mutaborGUI::MutFrame::DetermineFrameSize()
References TRACEC.
Referenced by mutaborGUI::MutFrame::MutFrame.
bool mutaborGUI::MutFrame::HasClient()
retrun true if we have already a client
References mutaborGUI::MutFrame::client.
Referenced by mutaborGUI::MutApp::MustOpenFrame.
void mutaborGUI::MutFrame::UpdateBoxMenu()
References _, mutaborGUI::MutFrame::boxCommandIds, mutaborGUI::MutFrame::ClearMenuItem, mutaborGUI::CM_ACTIVATE, mutaborGUI::CM_BOX, mutaborGUI::CM_SELECTBOX, DEBUGLOG, mutabor::BoxClass::GetBoxList, mutaborGUI::BoxData::GetCurrentBox, mutaborGUI::BoxData::GetLogicWindow, mutASSERT, mutaborGUI::MutFrame::RaiseLogic, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::CmRoutes, mutaborGUI::MutFrame::DoBoxWindowsClose, mutaborGUI::BoxData::DoClose, mutaborGUI::BoxData::DoOpen, mutaborGUI::MutFrame::LogicWinOpen, mutaborGUI::BoxData::set_routefile_id.
bool mutaborGUI::MutFrame::RaiseTheFrame()
References mutaborGUI::MutFrame::ActiveWindow.
Referenced by mutaborGUI::MutFrame::RaiseLogic.
static void mutaborGUI::MutFrame::repaint_route()
References mutaborGUI::MutFrame::client, WK_ROUTE.
Referenced by mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::CmInDevPause, mutaborGUI::MutFrame::CmInDevPlay, mutaborGUI::MutFrame::CmInDevStop, mutaborGUI::MutFrame::DoStop.
void mutaborGUI::MutFrame::SetFileMenu(wxMenu *f)
References mutaborGUI::MutFrame::filemenu.
Referenced by IMPLEMENT_APP.
void mutaborGUI::MutFrame::SetEditMenu(wxMenu *e)
References mutaborGUI::MutFrame::editmenu.
static wxDocument* mutaborGUI::MutFrame::GetActiveDocument()
References mutaborGUI::MutFrame::ActiveWindow.
static MutFrame* mutaborGUI::MutFrame::GetActiveWindow()
References mutaborGUI::MutFrame::ActiveWindow.
Referenced by BEGIN_EVENT_TABLE, mutaborGUI::BoxData::set_routefile_id.
void mutaborGUI::MutFrame::CloseClientWindow(wxWindow *w, bool update=true)
References mutaborGUI::MutFrame::auimanager, DEBUGLOG, mutASSERT.
Referenced by mutaborGUI::MutFrame::DoBoxWindowsClose, mutaborGUI::BoxData::DoClose, mutaborGUI::MutFrame::ToggleTextBox.
virtual wxStatusBar* mutaborGUI::MutFrame::OnCreateStatusBar(int number, long style, wxWindowID id, const wxString &name)
References mutaborGUI::StatusBar::Hide, mutaborGUI::LogicOn, mutaborGUI::StatusBar::SetActive, mutaborGUI::StatusBar::SetPlaystate.
void mutaborGUI::CheckBoxesUsed()
synchronizes used flag of mut_box with the routes
Referenced by mutaborGUI::MutFrame::CmDoActivate.
BEGIN_EVENT_TABLE(MutTextBox, wxListBox) EVT_MENU(CM_UPDATEUI
MutTextBox::UpdateUI EVT_CLOSE(MutTextBox::OnClose) END_EVENT_TABLE() MutTextBox
References _, mutaborGUI::BoxData::GetBackgroundColour, mutaborGUI::BoxData::GetTextColour, mutaborGUI::ToGUIBase, TRACEC.
WinKind operator++(WinKind &k)
WinKind operator++(WinKind &k, int)
IMPLEMENT_DYNAMIC_CLASS(MutPanel, wxControl) BEGIN_EVENT_TABLE(MutPanel
wxControl EVT_SIZE(MutPanel::OnSize) EVT_SET_FOCUS(MutPanel
References mutUnused.
mutaborGUI::MutChild::~MutChild()
References mutaborGUI::MutChild::deleteFromWinAttrs, mutASSERT, TRACEC, MutTextBox::winKind, WK_KEY, WK_NULL.
void mutaborGUI::MutChild::BoxChanged()
References MutTextBox::box, mutaborGUI::BoxData::GetBackgroundColour, mutaborGUI::BoxData::GetTextColour, mutaborGUI::MutChild::MakeTitle, mutASSERT, mutaborGUI::ToGUIBase.
void mutaborGUI::MutChild::OnActivate(wxActivateEvent &event)
References MutTextBox::box, mutASSERT, mutUnused, mutaborGUI::SetCurrentBox, TRACEC, MutTextBox::winKind, WK_KEY, WK_NULL.
void mutaborGUI::MutChild::deleteFromWinAttrs(bool setWant=true)
References _, MutTextBox::box, DEBUGLOG, mutASSERT, mutaborGUI::BoxData::SetActionsWindow, mutaborGUI::BoxData::SetKeyWindow, mutaborGUI::BoxData::SetTonesystemWindow, mutaborGUI::ToGUIBase, UNREACHABLEC, mutaborGUI::BoxData::WantActionsWindow, mutaborGUI::BoxData::WantKeyWindow, mutaborGUI::BoxData::WantTonesystemWindow, MutTextBox::winKind, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by mutaborGUI::MutChild::OnAuiClose, mutaborGUI::MutChild::OnClose, mutaborGUI::MutChild::~MutChild.
void mutaborGUI::MutChild::OnChar(wxKeyEvent &event)
References MutTextBox::box, mutaborGUI::BoxData::GetLogicWindow, mutASSERT, mutaborGUI::SetCurrentBox, mutaborGUI::ToGUIBase, TRACEC, UNREACHABLEC.
void mutaborGUI::MutChild::OnGetFocus(wxFocusEvent &event)
References MutTextBox::box, mutaborGUI::SetCurrentBox, TRACEC.
MutEditFile::MutEditFile(MutView *v, wxWindow *parent, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, const wxString &value=wxEmptyString, const wxString &name=wxTextCtrlNameStr)
References mutaborGUI::MutEditFile::Init, mutaborGUI::StatusBar::SetInsert.
MutEditFile::~MutEditFile()
References mutaborGUI::MutView::SetTextsw, mutaborGUI::MutEditFile::view.
bool MutEditFile::Compile(bool activate)
References _, mutaborGUI::CM_DOACTIVATE, mutaborGUI::CM_STOP, mutaborGUI::CompiledFile, mutaborGUI::DebugCheckRoutes, DEBUGLOG, mutaborGUI::CompDlg::EnableButton, mutabor::BoxClass::GetBoxList, mutaborGUI::MutEditFile::GoToErrorLine, mutaborGUI::LogicOn, mutaborGUI::MutEditFile::m_filename, mutaborGUI::SaveEditor, mutaborGUI::MutEditFile::SaveFile, mutaborGUI::BoxData::SetEditor, mutaborGUI::CompDlg::SetFileName, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::MutEditFile::CmCompAct, mutaborGUI::MutEditFile::CmCompile.
bool MutEditFile::DoLoadFile(const wxString &filename, int WXUNUSED(fileType))
References _, mutaborGUI::MutEditFile::autoConverter, DEBUGLOG, mutaborGUI::MutEditFile::DeterminePrefs, mutabor::hidden::error, mutaborGUI::MutEditFile::InitializePrefs, mutaborGUI::MutEditFile::m_filename, TRACEC.
Referenced by mutaborGUI::MutEditFile::LoadFile.
bool MutEditFile::DoSaveFile(const wxString &filename, int WXUNUSED(fileType))
References _, mutaborGUI::MutEditFile::autoConverter, DEBUGLOG, mutaborGUI::MutEditFile::GetValue, mutaborGUI::MutEditFile::m_filename.
Referenced by mutaborGUI::MutEditFile::SaveFile.
void MutEditFile::CmFileSave(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::MutEditFile::m_filename, mutaborGUI::MutEditFile::SaveFile.
Referenced by mutaborGUI::MutEditFile::CmFileSaveAs.
void MutEditFile::CmFileSaveAs(wxCommandEvent &event)
References mutaborGUI::CM_SETTITLE, mutaborGUI::MutEditFile::CmFileSave, FileNameDialog, mutaborGUI::MutEditFile::m_filename.
void MutEditFile::CmCompile(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::MutEditFile::Compile, DEBUGLOG, mutaborGUI::MutEditFile::m_filename.
void MutEditFile::CmCompAct(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::MutEditFile::Compile.
void MutEditFile::CmGetLine(wxCommandEvent &WXUNUSED(event))
References STUBC.
void MutEditFile::GoToErrorLine(int Line)
Referenced by mutaborGUI::MutEditFile::Compile.
void MutEditFile::CmHelpContext(wxCommandEvent &WXUNUSED(event))
References STUBC.
void MutEditFile::Init()
References DEFAULT_LANGUAGE, mutaborGUI::CommonInfo::displayEOLEnable, mutaborGUI::g_CommonPrefs, mutaborGUI::CommonInfo::indentGuideEnable, mutaborGUI::MutEditFile::InitializePrefs, mutaborGUI::CommonInfo::longLineOnEnable, mutaborGUI::MutEditFile::m_DividerID, mutaborGUI::MutEditFile::m_filename, mutaborGUI::MutEditFile::m_FoldingID, mutaborGUI::MutEditFile::m_FoldingMargin, mutaborGUI::MutEditFile::m_language, mutaborGUI::MutEditFile::m_LineNrID, mutaborGUI::MutEditFile::m_LineNrMargin, mutaborGUI::CommonInfo::overTypeInitial, mutaborGUI::CommonInfo::readOnlyInitial, mutaborGUI::CommonInfo::whiteSpaceEnable, mutaborGUI::CommonInfo::wrapModeInitial.
Referenced by mutaborGUI::MutEditFile::MutEditFile.
void MutEditFile::SaveSearchData()
References Write.
Referenced by mutaborGUI::MutEditFile::OnFindDialog.
void MutEditFile::OnSize(wxSizeEvent &event)
References mutaborGUI::CommonInfo::foldEnable, mutaborGUI::g_CommonPrefs, mutaborGUI::CommonInfo::lineNumberEnable, mutaborGUI::MutEditFile::m_FoldingMargin, mutaborGUI::MutEditFile::m_LineNrMargin.
void MutEditFile::OnEditUndoUI(wxUpdateUIEvent &event)
void MutEditFile::OnEditRedoUI(wxUpdateUIEvent &event)
void MutEditFile::OnEditRedo(wxCommandEvent &event)
void MutEditFile::OnEditUndo(wxCommandEvent &event)
void MutEditFile::OnEditClear(wxCommandEvent &event)
References Clear.
void MutEditFile::OnEditCut(wxCommandEvent &event)
void MutEditFile::OnEditCopy(wxCommandEvent &event)
References Copy.
void MutEditFile::OnEditPaste(wxCommandEvent &event)
void MutEditFile::OnFind(wxCommandEvent &event)
References mutUnused.
void MutEditFile::OnFindNext(wxCommandEvent &event)
References mutaborGUI::MutEditFile::DoFind, mutaborGUI::MutEditFile::FindFlags::Down.
void MutEditFile::OnFindDialog(wxFindDialogEvent &event)
References _, DEBUGLOG, mutaborGUI::MutEditFile::DoFind, mutaborGUI::MutEditFile::FindFlags::down, mutaborGUI::MutEditFile::FindFlags::Down, mutaborGUI::MutEditFile::SaveSearchData, mutaborGUI::MutEditFile::FindFlags::ShowNotFound, UNREACHABLEC, mutaborGUI::MutEditFile::FindFlags::UseCaret.
int MutEditFile::DoFind(const wxString &pattern, FindFlags flags)
References _, mutaborGUI::MutEditFile::FindFlags::askCircular, mutaborGUI::MutEditFile::FindFlags::down, mutaborGUI::MutEditFile::FindFlags::showNotFound, TRACEC, mutaborGUI::MutEditFile::FindFlags::useCaret.
Referenced by mutaborGUI::MutEditFile::OnFindDialog, mutaborGUI::MutEditFile::OnFindNext.
void MutEditFile::OnReplace(wxCommandEvent &event)
References mutaborGUI::MutEditFile::OnReplaceNext.
void MutEditFile::OnReplaceNext(wxCommandEvent &event)
Referenced by mutaborGUI::MutEditFile::OnReplace.
void MutEditFile::OnBraceMatch(wxCommandEvent &event)
void MutEditFile::OnGoto(wxCommandEvent &event)
References _.
void MutEditFile::OnEditIndentInc(wxCommandEvent &event)
void MutEditFile::OnEditIndentRed(wxCommandEvent &event)
void MutEditFile::OnEditSelectAll(wxCommandEvent &event)
void MutEditFile::OnEditSelectLine(wxCommandEvent &event)
void MutEditFile::OnHilightLang(wxCommandEvent &event)
view
References mutaborGUI::CM_HILIGHTFIRST, mutaborGUI::g_LanguagePrefs, mutaborGUI::MutEditFile::InitializePrefs, mutaborGUI::LanguageInfo::name.
void MutEditFile::OnDisplayEOL(wxCommandEvent &event)
void MutEditFile::OnIndentGuide(wxCommandEvent &event)
void MutEditFile::OnLineNumber(wxCommandEvent &event)
References mutaborGUI::MutEditFile::m_LineNrID, mutaborGUI::MutEditFile::m_LineNrMargin.
void MutEditFile::OnLongLineOn(wxCommandEvent &event)
void MutEditFile::OnWhiteSpace(wxCommandEvent &event)
void MutEditFile::OnFoldToggle(wxCommandEvent &event)
void MutEditFile::OnSetOverType(wxCommandEvent &event)
References mutaborGUI::StatusBar::SetInsert.
void MutEditFile::OnSetReadOnly(wxCommandEvent &event)
void MutEditFile::OnWrapmodeOn(wxCommandEvent &event)
void MutEditFile::OnUseCharset(wxCommandEvent &event)
void MutEditFile::OnChangeCase(wxCommandEvent &event)
extra
void MutEditFile::OnConvertEOL(wxCommandEvent &event)
void MutEditFile::OnMarginClick(wxStyledTextEvent &event)
misc
void MutEditFile::OnCharAdded(wxStyledTextEvent &event)
References DEBUGLOG.
void MutEditFile::OnStyleNeeded(wxStyledTextEvent &event)
References mutaborGUI::MutEditFile::lexer, mutaborGUI::MutSTCLexer::OnStyleNeeded.
void MutEditFile::OnUpdateStcUI(wxStyledTextEvent &event)
References mutaborGUI::StatusBar::SetPosition.
wxString MutEditFile::DeterminePrefs(const wxString &filename)
language/lexer
References mutaborGUI::LanguageInfo::filepattern, mutaborGUI::g_LanguagePrefs, mutaborGUI::g_LanguagePrefsSize, mutaborGUI::LanguageInfo::name.
Referenced by mutaborGUI::MutEditFile::DoLoadFile, mutaborGUI::MutEditFile::LoadFile.
bool MutEditFile::InitializePrefs(const wxString &filename)
References mutaborGUI::StyleInfo::background, DEBUGLOG, mutaborGUI::CommonInfo::displayEOLEnable, mutaborGUI::CommonInfo::foldEnable, mutaborGUI::LanguageInfo::folds, mutaborGUI::StyleInfo::fontname, mutaborGUI::StyleInfo::fontsize, mutaborGUI::StyleInfo::fontstyle, mutaborGUI::StyleInfo::foreground, mutaborGUI::g_CommonPrefs, mutaborGUI::g_LanguagePrefs, mutaborGUI::g_LanguagePrefsSize, mutaborGUI::g_StylePrefs, mutaborGUI::CommonInfo::indentEnable, mutaborGUI::CommonInfo::indentGuideEnable, mutaborGUI::StyleInfo::lettercase, mutaborGUI::LanguageInfo::lexer, mutaborGUI::CommonInfo::longLineOnEnable, mutaborGUI::MutEditFile::m_DividerID, mutaborGUI::MutEditFile::m_FoldingID, mutaborGUI::MutEditFile::m_FoldingMargin, mutaborGUI::MutEditFile::m_language, mutaborGUI::MutEditFile::m_LineNrID, MutSTC_FOLD_COMMENT, MutSTC_FOLD_COMMENTPY, MutSTC_FOLD_COMPACT, MutSTC_FOLD_HTML, MutSTC_FOLD_HTMLPREP, MutSTC_FOLD_PREPROC, MutSTC_FOLD_QUOTESPY, MutSTC_STYLE_BOLD, MutSTC_STYLE_HIDDEN, MutSTC_STYLE_ITALIC, MutSTC_STYLE_UNDERL, mutaborGUI::LanguageInfo::name, mutaborGUI::CommonInfo::overTypeInitial, mutaborGUI::CommonInfo::readOnlyInitial, STYLE_TYPES_COUNT, mutaborGUI::LanguageInfo::styles, mutaborGUI::CommonInfo::syntaxEnable, mutaborGUI::LanguageInfo::type, mutaborGUI::CommonInfo::whiteSpaceEnable, mutaborGUI::LanguageInfo::wordchars, mutaborGUI::LanguageInfo::words, mutaborGUI::CommonInfo::wrapModeInitial.
Referenced by mutaborGUI::MutEditFile::DoLoadFile, mutaborGUI::MutEditFile::Init, mutaborGUI::MutEditFile::LoadFile, mutaborGUI::MutEditFile::OnHilightLang.
bool MutEditFile::LoadFile()
load/save file
References mutaborGUI::MutEditFile::m_filename.
Referenced by mutaborGUI::MutFrame::OpenFile.
bool MutEditFile::LoadFile(const wxString &filename)
References mutaborGUI::MutEditFile::DeterminePrefs, mutaborGUI::MutEditFile::DoLoadFile, mutaborGUI::MutEditFile::InitializePrefs, mutaborGUI::MutEditFile::m_filename.
bool MutEditFile::SaveFile()
References mutaborGUI::MutEditFile::IsModified, mutaborGUI::MutEditFile::m_filename.
Referenced by mutaborGUI::MutEditFile::CmFileSave, mutaborGUI::MutEditFile::Compile.
bool MutEditFile::SaveFile(const wxString &filename)
References mutaborGUI::MutEditFile::DoSaveFile.
bool MutEditFile::IsModified()
Referenced by mutaborGUI::MutEditFile::SaveFile.
void MutEditFile::OnProperties(wxCommandEvent &WXUNUSED(event))
MutEditProperties::MutEditProperties(MutEditFile *edit, long style=0)
constructor
References _, mutaborGUI::MutEditFile::GetFilename, mutaborGUI::MutEditFile::m_language, mutaborGUI::LanguageInfo::name.
void MutTextBox::OnClose(wxCloseEvent &event)
References _, DEBUGLOG, mutaborGUI::BoxData::GetActionsWindow, mutaborGUI::BoxData::GetKeyWindow, mutaborGUI::BoxData::GetTonesystemWindow, mutaborGUI::LogicOn, mutASSERT, mutUnused, mutaborGUI::ToGUIBase, UNREACHABLEC, mutaborGUI::BoxData::WantActionsWindow, mutaborGUI::BoxData::WantKeyWindow, mutaborGUI::BoxData::WantTonesystemWindow, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by mutaborGUI::MutChild::OnClose.
void MutTextBox::UpdateUI(wxCommandEvent &event)
References _, mutaborGUI::asTS, UNREACHABLEC, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
void MutTextBox::BoxChangedAction(const char *a)
Handle action messages from ChangedCallback.
action action that shall be executed.
References mutaborGUI::CM_UPDATEUI, WK_ACT.
void MutTextBox::BoxChangedAction(int flags)
Handle box updates from ChangedCallback.
flags flags what has changed.
References _, mutaborGUI::CM_UPDATEUI, UNREACHABLEC, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
void MutTextBox::GetKeys(bool asTS)
Get the string describing the current key configuration of our box.
This function collects key data from the box of the object and updates the corresponding list. asTS bool if true frequencies will be shown as absolute cents otherwise relative to the previous key.
References _, Clear, mutabor::BoxClass::tone_entry::invalid, mutabor_convert_pitch_to_frequency, mutabor::BoxClass::tone_entry::silent, mutabor::BoxClass::tone_entry::sounding.
Referenced by mutaborGUI::MutFrame::TextBoxOpen.
void MutTextBox::GetToneSystem(bool asTS)
Update data to match the current tone system.
asTS bool if true frequencies will be shown as absolute cents otherwise relative to the previous key.
References _, mutabor::BoxClass::tone_system::anchor, Clear, mutabor::BoxClass::tone_entry::invalid, mutabor_convert_pitch_to_frequency, mutabor::BoxClass::tone_system::period, mutabor::BoxClass::tone_entry::silent, mutabor::BoxClass::tone_entry::sounding, mutabor::BoxClass::tone_system::tones.
Referenced by mutaborGUI::MutFrame::TextBoxOpen.
wxString MutTextBox::MakeTitle() const
References _, mutaborGUI::CAW, TextBoxTitle, WK_ACT.
Referenced by mutaborGUI::MutChild::MakeTitle.
void MutPanel::RemoveChild(wxWindowBase *child)
void MutPanel::SetFocus()
void MutPanel::SetFocusIgnoringChildren()
void MutPanel::OnChildFocus(wxChildFocusEvent &event)
References mutUnused.
void MutPanel::OnFocus(wxFocusEvent &event)
bool MutPanel::AcceptsFocus() const
void MutPanel::Init()
References MutPanel::m_container.
Referenced by MutPanel::MutPanel.
bool MutPanel::Create(wxWindow *parent, wxWindowID winid=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0, const wxValidator &validator=wxDefaultValidator, const wxString &name=wxPanelNameStr)
Referenced by MutPanel::MutPanel.
MutPanel::~MutPanel()
bool MutPanel::Destroy()
void MutPanel::InitDialog()
void MutPanel::OnSize(wxSizeEvent &event)
MUWX_COMPDLG_H
MUWX_COMPDLG_H_PRECOMPILED
Includes
DEF_MHARRAY
DEF_MHARRAYPTR
DEF_STACK
REUSE
ICON
Referenced by mutaborGUI::MutFrame::CmRoutes.
SSCANF
Referenced by compat30::LoadRoutes.
mumT
Referenced by IMPLEMENT_APP.
MDI_FORCE_EXTERN
MUWX_GUIBOXDATA_INLINES_H
MUWX_GUIBOXDATA_INLINES_H_PRECOMPILED
MUWX_GUIBOXDATA_H
MUWX_GUIBOXDATA_H_PRECOMPILED
MUWX_ICONSHAPE_H
MUWX_ICONSHAPE_H_PRECOMPILED
WXGUI_MUTABOR_RH
WXGUI_MUTABOR_RH_PRECOMPILED
MUWX_MUTAPP_H
MUWX_MUTAPP_H_PRECOMPILED
MUWX_MUT_BITMAPS_H
MUWX_MUT_BITMAPS_H_PRECOMPILED
MUWX_MUTCONFDLG_H
MUWX_MUTCONFDLG_H_PRECOMPILED
MUWX_MUTEDITFILE_H
MUWX_MUTEDITFILE_H_PRECOMPILED
MUWX_MUTFRAME_H
MUWX_MUTFRAME_H_PRECOMPILED
MUWX_MUTICON_H
MUWX_MUTICON_H_PRECOMPILED
MutIcon
MutICON
Referenced by mutaborGUI::initMutIconShapes.
MutNullIcon
Referenced by MutIconShapeClass< MutPanel >::GetMutIcon.
MUWX_MUTLOGICWND_H
MUWX_MUTLOGICWND_H_PRECOMPILED
MUWX_MUTTEXTBOX_H
MUWX_MUTTEXTBOX_H_PRECOMPILED
MUWX_PANEL_H
MUWX_PANEL_H_PRECOMPILED
MUWX_RESOURCELOUAD_H
MUWX_RESOURCELOUAD_H_PRECOMPILED
WXGUI_STATUSBAR
WXGUI_STATUSBAR_PRECOMPILED
MUWX_STCLANGUAGE_H
MUWX_STCLANGUAGE_H_PRECOMPILED