tonsystem.c
struct tonsystem* list_of_tonsysteme
Wurzel der Tonsysteme.
struct ton* ton_liste
Dient zum Aufsammeln einzelner Töne während eines Tonsystems.
Die aufgebaute Liste wird dann jeweils an das Tonsystem angehängt.
Referenced by get_new_tonsystem, get_new_tonsystem_negative.
int tonsystem_list_laenge(struct tonsystem *list)
Zählen der Elemente einer einfach verketteten Tonsystemliste.
list Liste der Tönsysteme Anzahl der Elemente von list
References tonsystem::next, tonsystem_list_laenge.
Referenced by mutabor::BoxClass::Compile, tonsystem_list_laenge.
struct tonsystem* parser_get_tonsystem(char *name, struct tonsystem *liste)
Sucht ein Tonsystem in einer Tonsystemliste.
name Name des gesuchten Tonsystems liste Liste der Tonsysteme, in der das System gesucht wird NULL falls Tonsystem nicht in liste Tonsystem sonst.
References tonsystem::name, tonsystem::next, parser_get_tonsystem.
Referenced by check_aktionen, check_konsistenz, check_logik_konsistenz, check_umstimmungs_konsistenz, expandiere_logik, expandiere_name, parser_get_tonsystem.
void init_ton_liste(void)
Setzt ton_liste auf NULL.
Die Liste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_new_ton_in_tonsystem(char *name)
Fügt einen Ton ans Ende von ton_liste an.
name Name des Tones Es wird immer die gesamte Liste durchsucht. Effektivität?
References name, ton::next, xmalloc.
Referenced by switch, yyparse.
void get_new_tonsystem(char *name, int taste)
Fügt ein Tonsystem ans Ende von list_of_tonsysteme an.
Der Aufruf erhält das letzte eingelesene Tonsystem. name Bezeichnung des Tonsystems, das angefügt werden soll taste Bezugstaste für das Tonsystem Es wird immer die gesamte Liste durchsucht. Effektivität?
References fatal_error, get_last_komplex_intervall, name, tonsystem::next, tonsystem::periode, tonsystem::taste, toene, ton_liste, xmalloc.
Referenced by switch, yyparse.
void get_new_tonsystem_negative(char *name, int taste)
Fügt ein Tonsystem ans Ende von list_of_tonsysteme an.
Der Aufruf erhält das letzte eingelesene Tonsystem in invertierter Form. name Bezeichnung des Tonsystems, das angefügt werden soll taste Bezugstaste für das Tonsystem Es wird immer die gesamte Liste durchsucht. Effektivität?
References komplex_intervall::faktor, fatal_error, get_last_komplex_intervall, name, tonsystem::next, komplex_intervall::next, tonsystem::taste, toene, ton_liste, xmalloc.
Referenced by switch, yyparse.
void check_tonsystem_konsistenz(void)
Tonsysteme testen.
Überprüfen, ob Periode und Töne deklariert sind und ob die Taste im Bereich 24 108 liegt.
References check_komplex_intervall, fatal_error, get_ton, list_of_toene, ton::name, tonsystem::name, ton::next, tonsystem::next, tonsystem::periode, tonsystem::taste, tonsystem::toene.
Referenced by check_konsistenz.