GisWriteHead
GisWriteHead* GisWriteHead::Next
Referenced by AddTime, CloseAllSubs, CloseSubs, CutOut, GetMatchingHeader, GisWriteHead, InsertAfter, ~GisWriteHead.
GisWriteHead * GisWriteHead::Prev
Referenced by CutOut, GetMatchingHeader, GisWriteHead, InsertAfter.
GisWriteHead* GisWriteHead::Boss
Referenced by CloseSubs, GisWriteHead.
int GisWriteHead::nSub
Referenced by CloseAllSubs, CloseSubs, GisWriteHead.
GisToken* GisWriteHead::Data
Referenced by CloseAllSubs, CloseSubs, GisWriteHead, ReadyForBoss, RemoveComma.
GisToken ** GisWriteHead::Cursor
Referenced by ChordNote::ChordNote, CloseAllSubs, CloseCurrentToken, CloseSubs, GisWriteHead, ProceedGis, ReadyForBoss, RemoveComma, State, WriteChord.
frac GisWriteHead::TotalTime
Referenced by AddTime, ChordNote::ChordNote, GisWriteHead.
frac GisWriteHead::CurrentTime
Referenced by AddTime, ChordNote::ChordNote, CloseCurrentToken, GisWriteHead, WriteChord.
mutString GisWriteHead::Id
Referenced by GetMatchingHeader, GisWriteHead, ProceedGis, ~GisWriteHead.
char GisWriteHead::SingleToken
Referenced by GisWriteHead, ReadyForBoss.
GisToken** GisWriteHead::ChordPos
Referenced by ChordNote::ChordNote, WriteChord.
ChordNote* GisWriteHead::ChordNotes
Referenced by AddTime, CloseCurrentToken, GetFreeNote, GetNote, GisWriteHead, ProceedGis, WriteChord.
char GisWriteHead::NoteOn
Referenced by GisWriteHead, ChordNote::MutNoteOff, ChordNote::MutNoteOn, ProceedGis, ChordNote::SetNoteOff, ChordNote::SetNoteOn.
char GisWriteHead::CommaAtEnd
Referenced by CloseAllSubs, CloseSubs, GisWriteHead, ProceedGis, ReadyForBoss, RemoveComma.
TagList* GisWriteHead::Octave
Referenced by GetOctave, GisWriteHead, ProceedGis, ~GisWriteHead.
TagList* GisWriteHead::Key
Referenced by GetKey, GisWriteHead, ProceedGis, ~GisWriteHead.
GisWriteHead::GisWriteHead(GisWriteHead *boss, const mutString id)
References Boss, CHECKDUP, ChordNotes, CommaAtEnd, CurrentTime, Cursor, Data, GTSegment, Id, Key, Next, NoteOn, nSub, Octave, Prev, SingleToken, State, TotalTime.
GisWriteHead::~GisWriteHead()
References Erase, Id, Key, mutFreeString, Next, Octave.
GisWriteHead * GisWriteHead::InsertAfter(GisWriteHead *position)
References Next, Prev.
Referenced by GetMatchingHeader.
GisWriteHead * GisWriteHead::CutOut()
References Next, Prev.
Referenced by CloseAllSubs, CloseSubs.
GisType GisWriteHead::State()
References Cursor, GTNull.
Referenced by CloseCurrentToken, GisWriteHead, ProceedGis.
ChordNote * GisWriteHead::GetFreeNote()
References ChordNote::AddGis, ChordNotes, CNNoteOn, mutEmptyString, mutT, ChordNote::Next.
Referenced by ProceedGis.
ChordNote * GisWriteHead::GetNote(int instrId, int taste)
References ChordNote::CheckId, ChordNotes, ChordNote::Next.
int GisWriteHead::ReadyForBoss()
References CloseCurrentToken, Comma, CommaAtEnd, Cursor, Data, GTNote, GTSequenz, GisToken::Next, SingleToken, GisToken::Type.
Referenced by CloseSubs.
void GisWriteHead::RemoveComma()
References CommaAtEnd, Cursor, Data, GisToken::Next.
Referenced by CloseAllSubs, CloseSubs.
int GisWriteHead::CloseSubs(GisToken **cont=0)
References Boss, CommaAtEnd, Cursor, CutOut, Data, h, mutT, Next, nSub, ReadyForBoss, RemoveComma.
Referenced by CloseAllSubs, CloseCurrentToken.
int GisWriteHead::CloseCurrentToken(char insertRest=1)
References ChordNotes, CloseSubs, CurrentTime, Cursor, GTComma, GTNote, GTNull, GTParaInt, GTParaReal, GTParaStr, GTSegment, GTSequenz, GTTag, GTTagBegin, GTTagEnd, GTUnknown, mutT, State, WriteChord.
Referenced by ProceedGis, ReadyForBoss.
int GisWriteHead::ProceedGis(GisToken *token, char turn=0)
References AddTag, ChordNotes, CloseCurrentToken, CommaAtEnd, GisToken::Copy, Cursor, TagListData::Data, EndTag, GetFreeNote, GTComma, GTNote, GTNull, GTParaInt, GTParaReal, GTParaStr, GTSegment, GTSequenz, GTTag, GTTagBegin, GTTagEnd, GTUnknown, TagListData::data::i, Id, Key, NoteOn, Octave, GisToken::Sep, ChordNote::SetNoteOff, ChordNote::SetNoteOn, State, TTkey, TToct, GisToken::Type, WriteChord, WTAG, WTAGEND.
Referenced by GisWriteHeadGis.
void GisWriteHead::WriteChord()
References ChordNote::CheckClose, ChordNotes, ChordPos, CurrentTime, Cursor, ChordNote::Cursor, ChordNote::Data, ChordNote::Next.
Referenced by CloseCurrentToken, ProceedGis.
void GisWriteHead::AddTime(frac dTime)
References AddTime, ChordNotes, ChordNote::CountOnTime, CurrentTime, Next, TotalTime.
Referenced by AddTime, mutabor::OutputGis::do_AddTime.
int GisWriteHead::GetOctave()
References TagListData::Data, TagListData::data::i, Octave.
Referenced by ChordNote::MutNoteOn.
int GisWriteHead::GetKey()
References TagListData::Data, TagListData::data::i, Key.
Referenced by ChordNote::MutNoteOn.