mutabor::DebugMidiOutputProvider
Device* mutabor::DebugMidiOutputProvider::device
std::string mutabor::DebugMidiOutputProvider::data
Referenced by ClearData, Close, Open, operator std::string, RawMsg, SendSysEx, WriteTime.
bool mutabor::DebugMidiOutputProvider::open
Referenced by Close, Open, operator(), RawMsg, SendSysEx.
mutabor::DebugMidiOutputProvider::DebugMidiOutputProvider(Device *d)
bool mutabor::DebugMidiOutputProvider::Open()
Opens the output.
true on success. false if an error occurred. In that case assume that everything below this function has been restored to closed state.
References data, mutASSERT, open, WriteTime.
void mutabor::DebugMidiOutputProvider::Close()
Opens the output.
true on success. false if an error occurred. In that case assume that everything below this function has been restored to closed state.
References data, mutASSERT, open, WriteTime.
DebugMidiOutputProvider& mutabor::DebugMidiOutputProvider::operator()(int channel, uint8_t byte1, uint8_t byte2, uint8_t byte3)
Outputs a three-byte message merging the channel into the data.
channel channel to which data shall be sent to. How channels are split into tracks or subdevices is managed by the OutputProvider byte1 1st byte byte2 2nd byte byte3 3rd byte
References mutabor::midi::CHANNEL_MASK, mutASSERT, open, RawMsg.
DebugMidiOutputProvider& mutabor::DebugMidiOutputProvider::RawMsg(int channel, uint8_t byte1, uint8_t byte2, uint8_t byte3)
Outputs a raw three-byte message.
channel channel to which data shall be sent to. How channels are split into tracks or subdevices is managed by the OutputProvider byte1 1st byte byte2 2nd byte byte3 3rd byte
References data, DEBUGLOG, mutASSERT, open, WriteTime.
Referenced by operator().
DebugMidiOutputProvider& mutabor::DebugMidiOutputProvider::operator()(int channel, uint8_t byte1, uint8_t byte2)
Outputs a two-byte message merging the channel into the message.
channel channel to which data shall be sent to. How channels are split into tracks or subdevices is managed by the OutputProvider byte1 1st byte byte2 2nd byte
References mutabor::midi::CHANNEL_MASK, mutASSERT, open, RawMsg.
DebugMidiOutputProvider& mutabor::DebugMidiOutputProvider::RawMsg(int channel, uint8_t byte1, uint8_t byte2)
Outputs a two-byte message.
channel channel to which data shall be sent to. How channels are split into tracks or subdevices is managed by the OutputProvider byte1 1st byte byte2 2nd byte
References data, DEBUGLOG, mutASSERT, open, mutabor::str, WriteTime.
DebugMidiOutputProvider& mutabor::DebugMidiOutputProvider::RawMsg(int channel, uint8_t byte1)
Outputs a one-byte message.
channel channel to which data shall be sent to. How channels are split into tracks or subdevices is managed by the OutputProvider byte1 byte
References data, DEBUGLOG, mutASSERT, open, WriteTime.
DebugMidiOutputProvider& mutabor::DebugMidiOutputProvider::SendSysEx(int channel, i from, i to)
Outputs a System Exclusive Message.
channel channel to which data shall be sent to. How channels are split into tracks or subdevices is managed by the OutputProvider message byte array containang the message count number of bytes to be sent
References data, DEBUGLOG, mutASSERT, open, mutabor::midi::STARTBYTE_MASK, mutabor::str, UNREACHABLEC, WriteTime.
mutabor::DebugMidiOutputProvider::operator std::string() const
References data.
void mutabor::DebugMidiOutputProvider::ClearData()
References data.
Referenced by midicmnOutputDevice::Check.
void mutabor::DebugMidiOutputProvider::WriteTime()
References mutabor::CurrentTime, data, mutabor::CurrentTimer::Get, mutabor::CurrentTimer::isRealtime, mutabor::str.
Referenced by Close, Open, RawMsg, SendSysEx.