GisTag
int GisTag::Id
Referenced by GisTag, ToString, ~GisTag.
mutString GisTag::Name
Referenced by Copy, GisTagBegin::Copy, GisTag, ToString, ~GisTag.
GisToken* GisTag::Para
Referenced by Copy, GisTagBegin::Copy, GetPara, GetParaType, GisTag, ToString, ~GisTag.
GisTag::GisTag(mutString name=mutEmptyString, GisToken *para=0, mutString sep=mutEmptyString, GisToken *next=0)
References CHECKDUP, DEBUGLOG, GetTagId, Id, Name, Para.
Referenced by Copy.
GisTag::GisTag(int id, char shortForm, GisToken *para=0, mutString sep=mutEmptyString, GisToken *next=0)
References Id, Name, Para, Tags, TagShorts.
GisTag::~GisTag()
References Id, mutFreeString, Name, Para.
virtual GisType GisTag::Type() const
References GTTag.
Referenced by AddTag, EndTag.
virtual GisToken* GisTag::Copy()
References CopyPara, GisTag, Name, Para, GisToken::Sep.
GisType GisTag::GetParaType(int nr)
References GTNull, GisToken::Next, Para, GisToken::Type.
GisToken * GisTag::GetPara(int nr)
References GisToken::Next, Para.
virtual wxString GisTag::ToString()
References Id, Name, Para, GisToken::ToString.
Referenced by GisTagBegin::ToString.