mutaborGUI::GUIfiedOutputDevice
typedef T mutaborGUI::GUIfiedOutputDevice< T >::basetype
typedef GUIfiedOutputDevice<T> mutaborGUI::GUIfiedOutputDevice< T >::thistype
friend class GUIMidiPortFactory
friend class GUIMidiFileFactory
friend class GUIGisFactory
mutaborGUI::GUIfiedOutputDevice< T >::GUIfiedOutputDevice(const mutStringRef name=mutEmptyString, int id=-1)
virtual mutaborGUI::GUIfiedOutputDevice< T >::~GUIfiedOutputDevice()
References TRACEC.
void mutaborGUI::GUIfiedOutputDevice< T >::Add(mutabor::Route &route)
add a route
References mutaborGUI::GUIOutputDeviceBase::Add, TRACEC.
bool mutaborGUI::GUIfiedOutputDevice< T >::Replace(mutabor::Route &oldroute, mutabor::Route &newroute)
replace a route
References mutaborGUI::GUIOutputDeviceBase::Replace, TRACEC.
bool mutaborGUI::GUIfiedOutputDevice< T >::Remove(mutabor::Route &route)
remove a route
References mutaborGUI::GUIOutputDeviceBase::Remove, TRACEC.
virtual mutabor::OutputDeviceClass* mutaborGUI::GUIfiedOutputDevice< T >::GetDevice()
Referenced by mutaborGUI::GUIMidiPortFactory::DoCreateOutput, mutaborGUI::GUIMidiFileFactory::DoCreateOutput, mutaborGUI::GUIGisFactory::DoCreateOutput.
void mutaborGUI::GUIfiedOutputDevice< T >::DisconnectFromAll()
References TRACEC.
int mutaborGUI::GUIfiedOutputDevice< T >::MoveInList(int count)
References mutaborGUI::GUIOutputDeviceBase::MoveToInList.
virtual void mutaborGUI::GUIfiedOutputDevice< T >::runtime_error(int type, const mutString &message, va_list &args)
References mutaborGUI::GUIOutputDeviceBase::runtime_error.