mutaborGUI
@60
typedef NoBoxSettingsBase mutaborGUI::NoBoxSettings
typedef GuidoFileBoxSettingsBase mutaborGUI::GuidoFileBoxSettings
typedef std::list< MutBoxShape * > mutaborGUI::MutBoxShapeList
typedef std::set<MutRouteWnd *> mutaborGUI::rwdset
typedef MutDeviceShape< inputdevicetypes > mutaborGUI::MutInputDeviceShape
typedef std::list< MutInputDeviceShape * > mutaborGUI::MutInputDeviceShapeList
typedef MutDeviceShape< outputdevicetypes > mutaborGUI::MutOutputDeviceShape
typedef std::list< MutOutputDeviceShape * > mutaborGUI::MutOutputDeviceShapeList
typedef GUIfiedRoute<mutabor::RouteClass> mutaborGUI::GUIRoute
Prototype of any GUI based route class.
This class is the prototype for any GUI based route. Since the base class remains RouteClass we must not any fields to it.
typedef GUIfiedOutputDevice<mutabor::OutputMidiPort> mutaborGUI::GUIOutputMidiPort
typedef GUIfiedInputDevice<mutabor::InputMidiPort> mutaborGUI::GUIInputMidiPort
typedef GUIfiedOutputDevice<mutabor::OutputMidiFile> mutaborGUI::GUIOutputMidiFile
typedef GUIfiedInputDevice<mutabor::InputMidiFile> mutaborGUI::GUIInputMidiFile
typedef GUIfiedOutputDevice<mutabor::OutputGis> mutaborGUI::GUIOutputGis
typedef GUIfiedInputDevice<mutabor::InputGis> mutaborGUI::GUIInputGis
typedef GisOutputFilterPanelBase mutaborGUI::GisOutputFilterPanel
typedef std::list<MutBoxChannelShape *> mutaborGUI::MutBoxChannelShapeList
wxHtmlHelpController* mutaborGUI::HelpController
Referenced by mutaborGUI::MutConfigDialog::CmHelp.
bool mutaborGUI::demo
bool mutaborGUI::asTS
Referenced by IMPLEMENT_APP, mutaborGUI::MutConfigDialog::MutConfigDialog, mutaborGUI::MutFrame::TextBoxOpen, MutTextBox::UpdateUI.
bool mutaborGUI::SaveEditor
Referenced by mutaborGUI::MutEditFile::Compile, IMPLEMENT_APP, mutaborGUI::MutConfigDialog::MutConfigDialog.
bool mutaborGUI::UseColorBars
Referenced by IMPLEMENT_APP, mutaborGUI::MutConfigDialog::MutConfigDialog.
bool mutaborGUI::OWM
Referenced by mutaborGUI::MutFrame::CeToggleOWM, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::CmToggleOWM.
bool mutaborGUI::CAW
Referenced by mutaborGUI::MutFrame::CeToggleCAW, mutaborGUI::MutFrame::CmToggleCAW, MutTextBox::MakeTitle, mutaborGUI::MutFrame::TextBoxOpen.
bool mutaborGUI::LogicOn
Referenced by BEGIN_EVENT_TABLE, mutaborGUI::MutFrame::CeActivate, mutaborGUI::MutFrame::CeExecute, mutaborGUI::MutFrame::CeInDevPlay, mutaborGUI::MutFrame::CeStop, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::CmInDevPlay, mutaborGUI::MutFrame::CmPanic, mutaborGUI::MutFrame::CmRoutes, mutaborGUI::MutFrame::CmToggleCAW, mutaborGUI::MutFrame::CmToggleOWM, mutaborGUI::MutEditFile::Compile, mutaborGUI::GUIMidiPortFactory::DoCreateInput, mutaborGUI::GUIMidiFileFactory::DoCreateInput, mutaborGUI::GUIGisFactory::DoCreateInput, mutaborGUI::GUIMidiPortFactory::DoCreateOutput, mutaborGUI::GUIMidiFileFactory::DoCreateOutput, mutaborGUI::GUIGisFactory::DoCreateOutput, mutaborGUI::MutBoxShape::DoLeftDblClick, mutaborGUI::MutDeviceShape< T >::DoLeftDblClick, mutaborGUI::MutFrame::DoStop, MutTextBox::OnClose, mutaborGUI::MutFrame::OnCreateStatusBar, mutaborGUI::BoxData::set_routefile_id, mutaborGUI::MutFrame::ToggleTextBox.
wxWindow* mutaborGUI::ChildToClose
Referenced by mutaborGUI::MutFrame::CmCloseChild.
wxString mutaborGUI::CompiledFile
Referenced by mutaborGUI::MutLogicWnd::CmBox, mutaborGUI::MutEditFile::Compile, mutaborGUI::MutLogicWnd::MakeTitle.
char mutaborGUI::WinName[5][12][5][12]
int mutaborGUI::pubTaste
Referenced by mutaborGUI::MutLogicWnd::CmTaste, mutaborGUI::MutLogicWnd::OnChar.
rwdset mutaborGUI::rwdtoplevels
Referenced by Check, CheckWindows, DebugCheckRoutes, MakeTopLevelsBoxes, MakeTopLevelsInput, MakeTopLevelsOutput, MakeTopLevelsRoutes.
mutaborGUI::MutIconShape
outputdevicetypes template class mutaborGUI::MutDeviceShape< inputdevicetypes >
InputDevDlgBase mutaborGUI::EVT_CHOICE(XRCID("DeviceChoice"), InputDevDlg::OnChoiceSelected) EVT_BUTTON((XRCID("DeviceChoice"), InputDevDlg::OnChoiceSelected) EVT_BUTTON(
InputDevDlg constructors
Referenced by IMPLEMENT_DYNAMIC_CLASS.
MutIcon mutaborGUI::DevUnknownBitmap
Referenced by initMutIcon, initMutIconShapes.
MutIcon mutaborGUI::MidiInputDevBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::Create, mutaborGUI::MutInputMidiDeviceShape::GetMutIcon, initMutIconShapes.
MutIcon mutaborGUI::NewInputDevBitmap
Referenced by mutaborGUI::MutNewInputDeviceShape::GetMutIcon, initMutIconShapes.
MutIcon mutaborGUI::MidiOutputDevBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::Create, mutaborGUI::MutOutputMidiDeviceShape::GetMutIcon, initMutIconShapes.
MutIcon mutaborGUI::NewOutputDevBitmap
Referenced by mutaborGUI::MutNewOutputDeviceShape::GetMutIcon, initMutIconShapes.
MutIcon mutaborGUI::MidiFileBitmap
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::GetMutIcon, mutaborGUI::MutInputMidiFileDeviceShape::GetMutIcon, initMutIconShapes.
MutIcon mutaborGUI::GuidoFileBitmap
Referenced by mutaborGUI::MutOutputGuidoFileDeviceShape::GetMutIcon, mutaborGUI::MutInputGuidoFileDeviceShape::GetMutIcon, initMutIconShapes.
MutIcon mutaborGUI::BoxBitmap
Referenced by mutaborGUI::MutBoxIconShape::GetMutIcon, initMutIconShapes.
MutIcon mutaborGUI::NewBoxBitmap
Referenced by IMPLEMENT_CLASS, initMutIconShapes.
MutIcon mutaborGUI::ActiveChannelBitmap
Referenced by mutaborGUI::MutBoxChannelShape::GetMutIcon, initMutIconShapes.
MutIcon mutaborGUI::PassiveChannelBitmap
Referenced by mutaborGUI::MutBoxChannelShape::GetMutIcon, initMutIconShapes.
MutIcon mutaborGUI::DevicePlayBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::createPlayButtons, initMutIconShapes.
MutIcon mutaborGUI::DevicePauseBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::createPauseButton, mutaborGUI::MutDeviceShape< T >::createPlayButtons, mutaborGUI::MutDeviceShape< T >::createRecordButtons, initMutIconShapes.
MutIcon mutaborGUI::DeviceStopBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::createPlayButtons, mutaborGUI::MutDeviceShape< T >::createRecordButtons, initMutIconShapes.
MutIcon mutaborGUI::DeviceRecordBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::createRecordButtons, initMutIconShapes.
const CommonInfo mutaborGUI::g_CommonPrefs
language types
Referenced by mutaborGUI::MutEditFile::Init, mutaborGUI::MutEditFile::InitializePrefs, mutaborGUI::MutEditFile::OnSize.
const wxChar* mutaborGUI::MutSectionKeywords
const wxChar* mutaborGUI::MutOperators
const wxChar* mutaborGUI::MutReservedWords
const wxChar* mutaborGUI::MutDelimiters
const wxChar* mutaborGUI::MutParameters
const wxChar* mutaborGUI::CppWordlist1
const wxChar* mutaborGUI::CppWordlist2
const wxChar* mutaborGUI::CppWordlist3
const wxChar* mutaborGUI::PythonWordlist1
const wxChar* mutaborGUI::PythonWordlist2
const LanguageInfo mutaborGUI::g_LanguagePrefs[]
languages
Referenced by mutaborGUI::MutEditFile::DeterminePrefs, IMPLEMENT_APP, mutaborGUI::MutEditFile::InitializePrefs, mutaborGUI::MutEditFile::OnHilightLang.
const int mutaborGUI::g_LanguagePrefsSize
Referenced by mutaborGUI::MutEditFile::DeterminePrefs, IMPLEMENT_APP, mutaborGUI::MutEditFile::InitializePrefs.
const StyleInfo mutaborGUI::g_StylePrefs[]
style types
Referenced by mutaborGUI::MutEditFile::InitializePrefs.
const int mutaborGUI::g_StylePrefsSize
void mutaborGUI::connect(mutabor::Box &box, MutBoxShape *shape)
References mutaborGUI::MutBoxShape::Add, mutaborGUI::MutBoxChannelShape::Add, mutaborGUI::BoxData::Add, DEBUGLOG2, mutaborGUI::MutBoxShape::GetBox, mutaborGUI::BoxData::GetShape, ToGUIBase, TRACE, UNREACHABLE.
Referenced by connect, mutaborGUI::MutDeviceShape< T >::Create.
bool mutaborGUI::disconnect(mutabor::Box &box, MutBoxShape *shape)
References DEBUGLOG2, mutaborGUI::MutBoxShape::GetBox, mutaborGUI::MutBoxShape::GetChannels, mutaborGUI::BoxData::GetShape, mutaborGUI::MutBoxShape::Remove, mutaborGUI::MutBoxChannelShape::Remove, mutaborGUI::BoxData::Remove, ToGUIBase, TRACE, UNREACHABLE.
Referenced by mutaborGUI::BoxData::Destroy, disconnect, mutaborGUI::MutDeviceShape< T >::ReadPanel, mutaborGUI::MutDeviceShape< T >::~MutDeviceShape.
BoxData* mutaborGUI::ToGUIBase(mutabor::BoxClass *b)
References mutASSERT.
Referenced by mutaborGUI::GUIRouteBase::Add, mutaborGUI::GUIOutputDeviceBase::Add, mutaborGUI::GUIInputDeviceBase::Add, mutaborGUI::MutRouteWnd::AddRoute, BEGIN_EVENT_TABLE, mutaborGUI::MutChild::BoxChanged, mutaborGUI::MutLogicWnd::BoxChanged, mutaborGUI::MutBoxShape::BoxChanged, mutaborGUI::BoxData::BoxData, mutaborGUI::MutFrame::CeToggleAct, mutaborGUI::MutFrame::CeToggleKey, mutaborGUI::MutFrame::CeToggleTS, Check, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutEditFile::Compile, connect, connect_device_shape, mutaborGUI::MutRouteWnd::createBoxes, mutaborGUI::MutRouteWnd::createRoutes, mutaborGUI::MutChild::deleteFromWinAttrs, disconnect, mutaborGUI::MutFrame::DoBoxWindowsClose, mutaborGUI::MutFrame::DoBoxWindowsOpen, mutaborGUI::GUIRouteFactory::DoCreateBoxChannelShape, mutaborGUI::GUIBoxFactory::DoCreateBoxShape, DontWant, mutaborGUI::MutBoxShape::DrawLines, EVT_CLOSE, mutaborGUI::MutDeviceShape< T >::GetGUIDevice, IsOpen, IsWanted, MakeTopLevelsBoxes, MakeTopLevelsInput, MakeTopLevelsOutput, MakeTopLevelsRoutes, mutaborGUI::MutChild::OnChar, MutTextBox::OnClose, mutaborGUI::MutFrame::RaiseLogic, mutaborGUI::MutBoxChannelShape::ReadPanel, mutaborGUI::GUIRouteBase::Remove, mutaborGUI::GUIOutputDeviceBase::Remove, mutaborGUI::GUIInputDeviceBase::Remove, mutaborGUI::GUIRouteBase::Replace, mutaborGUI::GUIOutputDeviceBase::Replace, mutaborGUI::GUIInputDeviceBase::Replace, mutaborGUI::MutFrame::ToggleTextBox, ToGUIBase, mutaborGUI::MutLogicWnd::UpDate, mutaborGUI::MutFrame::UpdateBoxMenu, mutaborGUI::MutLogicWnd::~MutLogicWnd.
BoxData* mutaborGUI::ToGUIBase(mutabor::Box &b)
References ToGUIBase.
const BoxData* mutaborGUI::ToGUIBase(const mutabor::BoxClass *b)
References mutASSERT.
const BoxData* mutaborGUI::ToGUIBase(const mutabor::Box &b)
References ToGUIBase.
mutabor::Box mutaborGUI::GetCurrentBox()
References mutaborGUI::BoxData::GetCurrentBox.
Referenced by mutaborGUI::MutFrame::CeToggleAct, mutaborGUI::MutFrame::CeToggleKey, mutaborGUI::MutFrame::CeToggleTS, mutaborGUI::MutFrame::RaiseLogic, mutaborGUI::MutFrame::ToggleTextBox.
void mutaborGUI::SetCurrentBox(mutabor::Box b)
References mutaborGUI::BoxData::SetCurrentBox.
Referenced by mutaborGUI::MutLogicWnd::CmMutTag, mutaborGUI::MutBoxShape::GotFocus, mutaborGUI::MutChild::OnActivate, mutaborGUI::MutLogicWnd::OnActivate, mutaborGUI::MutLogicWnd::OnChar, mutaborGUI::MutChild::OnChar, mutaborGUI::MutLogicWnd::OnGetFocus, mutaborGUI::MutChild::OnGetFocus, mutaborGUI::MutFrame::RaiseLogic, mutaborGUI::MutBoxShape::readDialog.
static void mutaborGUI::initMutBitmap(wxBitmap &bitmap, const wxString &filename, const wxBitmapType type)
References _, mutaborGUI::MutToolBarBitmaps::EmptyBitmap, mutASSERT.
Referenced by mutaborGUI::StatusBarBitmaps::DoInit, mutaborGUI::MutToolBarBitmaps::Init.
mutaborGUI::BEGIN_EVENT_TABLE(MutChild, MutTextBox) EVT_ACTIVATE(MutChild
References _, DEBUGLOG, mutASSERT, mutaborGUI::BoxData::SetActionsWindow, mutaborGUI::BoxData::SetKeyWindow, mutaborGUI::BoxData::SetTonesystemWindow, ToGUIBase, UNREACHABLEC, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by IMPLEMENT_APP, IMPLEMENT_DYNAMIC_CLASS.
bool mutaborGUI::IsOpen(WinKind kind, mutabor::Box &box)
References _, mutaborGUI::BoxData::GetActionsWindow, mutaborGUI::BoxData::GetKeyWindow, mutaborGUI::BoxData::GetLogicWindow, mutaborGUI::BoxData::GetTonesystemWindow, mutASSERT, ToGUIBase, UNREACHABLE, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by mutabor::CommonTypedDeviceAPI< T, P, L >::Destroy, mutabor::BoxClass::MoveRoutes, mutabor::CommonTypedDeviceAPI< T, P, L >::MoveRoutes, mutaborGUI::MutFrame::ToggleTextBox.
bool mutaborGUI::IsWanted(WinKind kind, mutabor::Box &box)
References _, mutASSERT, ToGUIBase, UNREACHABLE, mutaborGUI::BoxData::WantActionsWindow, mutaborGUI::BoxData::WantKeyWindow, mutaborGUI::BoxData::WantTonesystemWindow, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
void mutaborGUI::DontWant(WinKind kind, mutabor::Box &box)
References _, mutASSERT, ToGUIBase, UNREACHABLE, mutaborGUI::BoxData::WantActionsWindow, mutaborGUI::BoxData::WantKeyWindow, mutaborGUI::BoxData::WantTonesystemWindow, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
int mutaborGUI::NumberOfOpen(WinKind kind)
Referenced by mutaborGUI::MutLogicWnd::doClose.
void mutaborGUI::CheckBoxesUsed()
synchronizes used flag of mut_box with the routes
Referenced by mutaborGUI::MutFrame::CmDoActivate.
mutaborGUI::BEGIN_EVENT_TABLE(MutTag, MutIconShape) EVT_CHAR(MutTag
References CM_MUTTAG.
mutaborGUI::BEGIN_EVENT_TABLE(MutLogicWnd, wxScrolledWindow) EVT_SET_FOCUS(MutLogicWnd
References DEBUGLOG, mutaborGUI::BoxData::GetBackgroundColour, mutaborGUI::BoxData::GetLogicWindow, mutaborGUI::BoxData::GetTextColour, mutASSERT, mutaborGUI::BoxData::SetLogicWindow, ToGUIBase.
mutaborGUI::BEGIN_EVENT_TABLE(MutBoxChannelShape, MutIconShape) EVT_LEFT_DCLICK(MutBoxChannelShape
References DEBUGLOG, MutIconShapeClass< T >::GotFocus.
mutaborGUI::IMPLEMENT_DYNAMIC_CLASS(RoutePanel, RoutePanelBase) RoutePanel
BoxDlg event table definition
mutaborGUI::BEGIN_EVENT_TABLE(RouteRemoveButton, wxButton) EVT_BUTTON(wxID_REMOVE
RouteRemoveButton::RemoveButtonPressed mutaborGUI::END_EVENT_TABLE() IMPLEMENT_DYNAMIC_CLASS(RouteRemoveButton
mutaborGUI::BEGIN_EVENT_TABLE(BoxDlg, BoxDlgBase) EVT_BUTTON(
static wxSize mutaborGUI::GetStaticBoxSize(MutBoxIconShape *box)
References DEBUGLOGTYPE, MutIconShapeClass< T >::DoGetBestSize, mutASSERT.
mutaborGUI::IMPLEMENT_CLASS(MutBoxShape, MutBoxIconShape) BEGIN_EVENT_TABLE(MutBoxShape
static void mutaborGUI::CheckList(const T &list)
Check for duplicate entries in a list.
list List to be checked.
References DEBUGLOG2, mutASSERT.
Referenced by Check, CheckBoxes, CheckInputDevices, CheckOutputDevices, CheckRoutes, MakeTopLevelsBoxes, MakeTopLevelsInput, MakeTopLevelsOutput, MakeTopLevelsRoutes.
static void mutaborGUI::Check(const MutInputDeviceShape *input, const MutBoxChannelShape *route)
References mutaborGUI::MutDeviceShape< T >::GetChannels, mutaborGUI::MutBoxChannelShape::GetInput, mutASSERT.
static void mutaborGUI::Check(const MutInputDeviceShape *input, const RouteClass *route)
References Check, CheckList, mutASSERT, ToGUIBase.
static void mutaborGUI::Check(const InputDeviceClass *input, const MutBoxChannelShape *route)
References Check, mutaborGUI::BoxData::GetShapes, mutASSERT, ToGUIBase.
static void mutaborGUI::Check(const InputDeviceClass *input, const RouteClass *route)
References Check, CheckList, mutaborGUI::BoxData::GetShapes, mutASSERT, rwdtoplevels, ToGUIBase.
static void mutaborGUI::Check(const InputDeviceClass *input)
References Check, CheckList, DEBUGLOG2, mutabor::CommonTypedDeviceAPI< T, P, L >::GetRoutes, mutaborGUI::GUIInputDeviceBase::GetShape, mutASSERT, rwdtoplevels, ToGUIBase.
static void mutaborGUI::CheckInputDevices()
References Check, CheckList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList.
Referenced by DebugCheckRoutes.
static void mutaborGUI::Check(const MutOutputDeviceShape *output, const MutBoxChannelShape *route)
References mutaborGUI::MutDeviceShape< T >::GetChannels, mutaborGUI::MutBoxChannelShape::GetOutput, mutASSERT.
static void mutaborGUI::Check(const MutOutputDeviceShape *output, const RouteClass *route)
References Check, CheckList, mutASSERT, ToGUIBase.
static void mutaborGUI::Check(const OutputDeviceClass *output, const MutBoxChannelShape *route)
References Check, mutaborGUI::BoxData::GetShapes, mutASSERT, ToGUIBase.
static void mutaborGUI::Check(const OutputDeviceClass *output, const RouteClass *route)
References Check, CheckList, mutaborGUI::BoxData::GetShapes, mutASSERT, rwdtoplevels, ToGUIBase.
static void mutaborGUI::Check(const OutputDeviceClass *output)
References Check, CheckList, DEBUGLOG2, mutabor::CommonTypedDeviceAPI< T, P, L >::GetRoutes, mutaborGUI::GUIOutputDeviceBase::GetShape, mutASSERT, rwdtoplevels, ToGUIBase.
static void mutaborGUI::CheckOutputDevices()
References Check, CheckList, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList.
Referenced by DebugCheckRoutes.
static void mutaborGUI::Check(const MutBoxShape *box, const MutBoxChannelShape *route)
References mutaborGUI::MutBoxShape::GetBox, mutaborGUI::MutBoxShape::GetChannels, mutaborGUI::MutBoxChannelShape::GetRoute, mutASSERT.
static void mutaborGUI::Check(const MutBoxShape *box, const RouteClass *route)
References Check, CheckList, mutASSERT, ToGUIBase.
static void mutaborGUI::Check(const BoxClass *box, const MutBoxChannelShape *route)
References Check, mutaborGUI::BoxData::GetShape, mutASSERT, ToGUIBase.
static void mutaborGUI::Check(const MutBoxShape *shape)
References Check, mutaborGUI::MutBoxShape::GetBox, mutaborGUI::MutBoxShape::GetChannels, mutaborGUI::MutBoxChannelShape::GetRoute, mutaborGUI::BoxData::GetShape, mutASSERT, ToGUIBase, UNREACHABLE.
static void mutaborGUI::Check(const BoxClass *box, const RouteClass *route)
References Check, CheckList, mutaborGUI::BoxData::GetShapes, mutASSERT, rwdtoplevels, ToGUIBase.
static void mutaborGUI::Check(const BoxClass *box)
References Check, CheckList, DEBUGLOG2, mutabor::BoxClass::GetRoutes, mutaborGUI::BoxData::GetShape, mutASSERT, rwdtoplevels, ToGUIBase.
static void mutaborGUI::CheckBoxes()
References Check, CheckList, mutabor::BoxClass::GetBoxList.
Referenced by DebugCheckRoutes.
static void mutaborGUI::Check(const RouteClass *route, const MutBoxChannelShape *channel)
References CheckList, DEBUGLOG2, mutaborGUI::MutBoxShape::GetBox, mutabor::TRouteClass< I, O, B >::GetBox, mutabor::MIN_BOX, mutASSERT, rwdtoplevels, ToGUIBase.
static void mutaborGUI::Check(const RouteClass *route)
References Check, CheckList, DEBUGLOG2, mutabor::TRouteClass< I, O, B >::GetInputDevice, mutabor::TRouteClass< I, O, B >::GetOutputDevice, mutaborGUI::GUIRouteBase::GetShape, mutASSERT, rwdtoplevels, ToGUIBase, TRACE.
static void mutaborGUI::CheckRoutes()
References Check, CheckList, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetRouteList.
Referenced by DebugCheckRoutes.
static void mutaborGUI::Check(const MutInputDeviceShape *shape)
References mutaborGUI::MutDeviceShape< T >::GetDevice, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList, mutASSERT, ToGUIBase.
static void mutaborGUI::Check(const MutOutputDeviceShape *shape)
References mutaborGUI::MutDeviceShape< T >::GetDevice, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList, mutaborGUI::BoxData::GetShapes, mutASSERT, ToGUIBase.
static void mutaborGUI::Check(const MutBoxChannelShape *shape)
References mutaborGUI::MutBoxChannelShape::GetRoute, mutASSERT, ToGUIBase.
static void mutaborGUI::Check(const MutRouteWnd *win)
References mutaborGUI::MutRouteWnd::GetBoxes, mutaborGUI::MutRouteWnd::GetInputDevices, mutaborGUI::MutRouteWnd::GetOutputDevices, mutASSERT, UNREACHABLE.
Referenced by Check, CheckBoxes, CheckInputDevices, CheckOutputDevices, CheckRoutes, CheckWindows.
static void mutaborGUI::CheckWindows()
References Check, rwdtoplevels.
Referenced by DebugCheckRoutes.
static void mutaborGUI::MakeTopLevelsInput()
References CheckList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList, mutaborGUI::GUIInputDeviceBase::GetShapes, mutASSERT, rwdtoplevels, ToGUIBase.
Referenced by DebugCheckRoutes.
static void mutaborGUI::MakeTopLevelsOutput()
References CheckList, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList, mutaborGUI::GUIOutputDeviceBase::GetShapes, mutASSERT, rwdtoplevels, ToGUIBase.
Referenced by DebugCheckRoutes.
static void mutaborGUI::MakeTopLevelsBoxes()
References CheckList, mutabor::BoxClass::GetBoxList, mutaborGUI::BoxData::GetShapes, mutASSERT, rwdtoplevels, ToGUIBase.
Referenced by DebugCheckRoutes.
static void mutaborGUI::MakeTopLevelsRoutes()
References CheckList, mutaborGUI::GUIRouteBase::GetBoxChannelShapes, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetRouteList, mutASSERT, rwdtoplevels, ToGUIBase.
Referenced by DebugCheckRoutes.
void mutaborGUI::DebugCheckRoutes()
References CheckBoxes, CheckInputDevices, CheckOutputDevices, CheckRoutes, CheckWindows, MakeTopLevelsBoxes, MakeTopLevelsInput, MakeTopLevelsOutput, MakeTopLevelsRoutes, mutASSERT, rwdtoplevels.
Referenced by mutaborGUI::MutRouteWnd::CmRouteLoad, mutaborGUI::MutEditFile::Compile, mutaborGUI::MutBoxShape::DoLeftDblClick, mutaborGUI::MutDeviceShape< T >::DoLeftDblClick, mutabor::RouteFactory::DoSaveRoutes, IMPLEMENT_APP, mutaborGUI::MutRouteWnd::InitDevices, mutaborGUI::MutRouteWnd::InitShapes, mutaborGUI::MutBoxChannelShape::ReadPanel, GUIRouteTest::testConnect.
mutaborGUI::IMPLEMENT_ABSTRACT_CLASS_TEMPLATE1(MutDeviceShape, MutIconShape, inputdevicetypes) IMPLEMENT_ABSTRACT_CLASS_TEMPLATE1(MutDeviceShape
void mutaborGUI::connect(mutabor::Route &route, MutBoxChannelShape *shape)
References mutaborGUI::GUIRouteBase::Add, mutaborGUI::MutBoxChannelShape::Add, mutaborGUI::MutDeviceShape< T >::Add, ToGUIBase, UNREACHABLE.
void mutaborGUI::connect(MutBoxChannelShape *channel, MutOutputDeviceShape *out)
References connect, mutaborGUI::MutDeviceShape< T >::GetDevice, mutaborGUI::MutBoxChannelShape::GetRoute, UNREACHABLE.
void mutaborGUI::connect_device_shape(device_class *dev, shape_class *shape)
References mutaborGUI::MutBoxShape::Add, mutaborGUI::MutBoxChannelShape::Add, DEBUGLOG2, mutaborGUI::BoxData::GetShape, ToGUIBase, TRACE, UNREACHABLE.
Referenced by connect.
void mutaborGUI::connect(GUIOutputDeviceBase *out, MutOutputDeviceShape *shape)
References connect_device_shape.
void mutaborGUI::connect(GUIInputDeviceBase *in, MutInputDeviceShape *shape)
References connect_device_shape.
void mutaborGUI::connect(mutabor::OutputDevice &d, MutOutputDeviceShape *shape)
References connect, ToGUIBase.
void mutaborGUI::connect(mutabor::InputDevice &d, MutInputDeviceShape *shape)
References connect, ToGUIBase.
void mutaborGUI::connect(MutBoxChannelShape *channel, MutInputDeviceShape *in)
References connect, mutaborGUI::MutDeviceShape< T >::GetDevice, mutaborGUI::MutBoxChannelShape::GetRoute, UNREACHABLE.
bool mutaborGUI::disconnect(mutabor::Route &r, MutBoxChannelShape *shape)
References DEBUGLOG2, intrusive_ptr_get_refcount, mutaborGUI::GUIRouteBase::Remove, mutaborGUI::MutBoxChannelShape::Remove, mutaborGUI::MutDeviceShape< T >::Remove, ToGUIBase, UNREACHABLE.
bool mutaborGUI::disconnect(MutBoxChannelShape *channel, MutOutputDeviceShape *out)
References disconnect, mutaborGUI::MutDeviceShape< T >::GetDevice, mutaborGUI::MutBoxChannelShape::GetRoute, UNREACHABLE.
bool mutaborGUI::disconnect(MutBoxChannelShape *channel, MutInputDeviceShape *in)
References disconnect, mutaborGUI::MutDeviceShape< T >::GetDevice, mutaborGUI::MutBoxChannelShape::GetRoute, UNREACHABLE.
bool mutaborGUI::disconnect_device_shape(device_class *dev, shape_class *shape)
References DEBUGLOG2, TRACE, UNREACHABLE.
Referenced by disconnect.
bool mutaborGUI::disconnect(GUIOutputDeviceBase *out, MutOutputDeviceShape *shape)
References disconnect_device_shape.
bool mutaborGUI::disconnect(GUIInputDeviceBase *in, MutInputDeviceShape *shape)
References disconnect_device_shape.
bool mutaborGUI::disconnect(mutabor::OutputDevice &d, MutOutputDeviceShape *shape)
References disconnect, ToGUIBase.
bool mutaborGUI::disconnect(mutabor::InputDevice &d, MutInputDeviceShape *shape)
References disconnect, ToGUIBase.
bool mutaborGUI::reconnect(mutabor::Route &route, MutBoxShape *oldshape, MutBoxShape *newshape)
References mutaborGUI::MutBoxShape::GetBox, mutASSERT.
Referenced by mutaborGUI::MutDeviceShape< T >::ReadPanel, reconnect.
bool mutaborGUI::reconnect(GUIRoute *route, MutBoxShape *oldshape, MutBoxShape *newshape)
References reconnect.
bool mutaborGUI::reconnect(MutBoxChannelShape *channel, MutOutputDeviceShape *oldout, MutOutputDeviceShape *newout)
References mutaborGUI::MutDeviceShape< T >::GetDevice, mutaborGUI::MutBoxChannelShape::GetRoute, reconnect, UNREACHABLE.
bool mutaborGUI::reconnect(MutBoxChannelShape *channel, MutInputDeviceShape *oldin, MutInputDeviceShape *newin)
References mutaborGUI::MutDeviceShape< T >::GetDevice, mutaborGUI::MutBoxChannelShape::GetRoute, reconnect, UNREACHABLE.
bool mutaborGUI::reconnect(MutBoxChannelShape *channel, MutBoxShape *oldout, MutBoxShape *newout)
References mutaborGUI::MutBoxShape::GetBox, mutaborGUI::MutBoxChannelShape::GetRoute, reconnect, UNREACHABLE.
void mutaborGUI::InitGUIRouteFactories()
Referenced by IMPLEMENT_APP.
GUIRoute* mutaborGUI::ToGUIBase(mutabor::RouteClass *r)
const GUIRoute* mutaborGUI::ToGUIBase(const mutabor::RouteClass *r)
GUIRoute* mutaborGUI::ToGUIBase(mutabor::Route &r)
References ToGUIBase.
const GUIRoute* mutaborGUI::ToGUIBase(const mutabor::Route &r)
References ToGUIBase.
T* mutaborGUI::static_cast_to(mutabor::OutputDevice &o, T *type)
T* mutaborGUI::dynamic_cast_to(mutabor::OutputDevice &o, T *type)
const T* mutaborGUI::static_cast_to(const mutabor::OutputDevice &o, const T *type)
const T* mutaborGUI::dynamic_cast_to(const mutabor::OutputDevice &o, const T *type)
GUIOutputDeviceBase* mutaborGUI::ToGUIBase(mutabor::OutputDeviceClass *d)
References mutaborGUI::GUIOutputDeviceBase::GetGUIOutputDevice.
GUIOutputDeviceBase* mutaborGUI::ToGUIBase(mutabor::OutputDevice &d)
References ToGUIBase.
const GUIOutputDeviceBase* mutaborGUI::ToGUIBase(const mutabor::OutputDeviceClass *d)
References mutaborGUI::GUIOutputDeviceBase::GetGUIOutputDevice.
const GUIOutputDeviceBase* mutaborGUI::ToGUIBase(const mutabor::OutputDevice &d)
References ToGUIBase.
T* mutaborGUI::static_cast_to(mutabor::InputDevice &o, T *)
T* mutaborGUI::dynamic_cast_to(mutabor::InputDevice &o, T *)
const T* mutaborGUI::static_cast_to(const mutabor::InputDevice &o, const T *)
const T* mutaborGUI::dynamic_cast_to(const mutabor::InputDevice &o, const T *)
GUIInputDeviceBase* mutaborGUI::ToGUIBase(mutabor::InputDeviceClass *d)
References mutaborGUI::GUIInputDeviceBase::GetGUIInputDevice.
GUIInputDeviceBase* mutaborGUI::ToGUIBase(mutabor::InputDevice &d)
References ToGUIBase.
const GUIInputDeviceBase* mutaborGUI::ToGUIBase(const mutabor::InputDeviceClass *d)
References mutaborGUI::GUIInputDeviceBase::GetGUIInputDevice.
const GUIInputDeviceBase* mutaborGUI::ToGUIBase(const mutabor::InputDevice &d)
References ToGUIBase.
mutaborGUI::IMPLEMENT_DYNAMIC_CLASS(InputDevDlg, InputDevDlgBase) BEGIN_EVENT_TABLE(InputDevDlg
InputDevDlg type definition
mutaborGUI::IMPLEMENT_CLASS(NewMutBoxShape, MutBoxShape) MutIcon &NewMutBoxShape
References DEBUGLOG, mutASSERT, NewBoxBitmap.
static void mutaborGUI::initMutIcon(MutIcon &icon, const wxString &filename, const wxBitmapType type)
References DevUnknownBitmap.
Referenced by initMutIconShapes.
bool mutaborGUI::initMutIconShapes()
References ActiveChannelBitmap, BoxBitmap, DevicePauseBitmap, DevicePlayBitmap, DeviceRecordBitmap, DeviceStopBitmap, DevUnknownBitmap, GuidoFileBitmap, initMutIcon, MidiFileBitmap, MidiInputDevBitmap, MidiOutputDevBitmap, MutICON, NewBoxBitmap, NewInputDevBitmap, NewOutputDevBitmap, PassiveChannelBitmap.
Referenced by IMPLEMENT_APP.
mutaborGUI::BEGIN_EVENT_TABLE(StatusBar, wxStatusBar) EVT_MENU(CM_PLAYSTATE_CHANGED
wxString mutaborGUI::cbGetSubstring(wxCharBuffer &b, size_t pos, size_t length)