mutlex.h
mutabor_parser_IN_HEADER
YY_INT_ALIGNED
FLEX_SCANNER
YY_FLEX_MAJOR_VERSION
YY_FLEX_MINOR_VERSION
YY_FLEX_SUBMINOR_VERSION
FLEX_BETA
FLEXINT_H
INT8_MIN
INT16_MIN
INT32_MIN
INT8_MAX
INT16_MAX
INT32_MAX
UINT8_MAX
UINT16_MAX
UINT32_MAX
yyconst
YY_TYPEDEF_YY_SCANNER_T
yyin
yyout
yyextra
yyleng
yytext
yylineno
yycolumn
yy_flex_debug
YY_TYPEDEF_YY_BUFFER_STATE
YY_TYPEDEF_YY_SIZE_T
YY_STRUCT_YY_BUFFER_STATE
mutabor_parser_wrap
YY_SKIP_YYWRAP
FLEX_DEBUG
yytext_ptr
YY_EXTRA_TYPE
YY_READ_BUF_SIZE
YY_START_STACK_INCR
yyskel_static
YYTBL_MAGIC
Magic number for serialized format.
yypad64
Calculate (0-7) = number bytes needed to pad n to next 64-bit boundary.
YYTABLES_TYPES
YYTDFLAGS2BYTES
Extract corresponding data size_t from td_flags.
YY_DECL_IS_OURS
YY_DECL
yytbl_id
1-dim ints
yytbl_flags
data is an array of type flex_int8_t
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void* yyscan_t
typedef struct yy_buffer_state* YY_BUFFER_STATE
typedef unsigned int yy_size_t
int mutabor_parser_lex_init(yyscan_t *scanner)
References mutabor_parser_alloc, yy_init_globals.
Referenced by MUTABOR_CLASS_FUNCTION.
void mutabor_parser_restart(FILE *input_file, yyscan_t yyscanner)
Immediately switch to a different input stream.
input_file A readable stream. yyscanner The scanner object. This function does not reset the start condition to INITIAL .
References mutabor_parser__create_buffer, mutabor_parser__init_buffer, mutabor_parser__load_buffer_state, mutabor_parser_ensure_buffer_stack, YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyin.
Referenced by input, yy_get_next_buffer.
void mutabor_parser__switch_to_buffer(YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Switch to a different input buffer.
new_buffer The new input buffer. yyscanner The scanner object.
References mutabor_parser__load_buffer_state, mutabor_parser_ensure_buffer_stack, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars.
Referenced by mutabor_parser__scan_buffer.
YY_BUFFER_STATE mutabor_parser__create_buffer(FILE *file, int size, yyscan_t yyscanner)
Allocate and initialize an input buffer state.
file A readable stream. size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE. yyscanner The scanner object. the allocated buffer state.
References mutabor_parser__init_buffer, mutabor_parser_alloc, yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yy_buffer_state::yy_is_our_buffer.
Referenced by if, mutabor_parser_restart.
void mutabor_parser__delete_buffer(YY_BUFFER_STATE b, yyscan_t yyscanner)
Destroy the buffer.
b a buffer created with mutabor_parser__create_buffer() yyscanner The scanner object.
References mutabor_parser_free, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_buffer_state::yy_is_our_buffer.
Referenced by mutabor_parser_lex_destroy, mutabor_parser_pop_buffer_state.
void mutabor_parser__flush_buffer(YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
On the next scan, YY_INPUT will be called. b the buffer state to be flushed, usually YY_CURRENT_BUFFER. yyscanner The scanner object.
References mutabor_parser__load_buffer_state, yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, yy_buffer_state::yy_n_chars.
Referenced by mutabor_parser__init_buffer.
void mutabor_parser_push_buffer_state(YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
The new state becomes the current state. This function will allocate the stack if necessary. new_buffer The new state. yyscanner The scanner object.
References mutabor_parser__load_buffer_state, mutabor_parser_ensure_buffer_stack, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars.
void mutabor_parser_pop_buffer_state(yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
The next element becomes the new top. yyscanner The scanner object.
References mutabor_parser__delete_buffer, mutabor_parser__load_buffer_state, yyguts_t::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof.
Referenced by mutabor_parser_lex_destroy.
YY_BUFFER_STATE mutabor_parser__scan_buffer(char *base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
base the character buffer size the size in bytes of the character buffer yyscanner The scanner object. the newly allocated buffer state object.
References mutabor_parser__switch_to_buffer, mutabor_parser_alloc, yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, yy_buffer_state::yy_n_chars.
Referenced by mutabor_parser__scan_bytes.
YY_BUFFER_STATE mutabor_parser__scan_string(yyconst char *yy_str, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
The next call to mutabor_parser_lex() will scan from a copy of str. str a NUL-terminated string to scan yy_str a NUL-terminated string to scan yyscanner The scanner object. the newly allocated buffer state object. If you want to scan bytes that may contain NUL values, then use mutabor_parser__scan_bytes() instead.
References mutabor_parser__scan_bytes.
YY_BUFFER_STATE mutabor_parser__scan_bytes(yyconst char *bytes, int len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
The next call to mutabor_parser_lex() will scan from a copy of bytes. bytes the byte buffer to scan len the number of bytes in the buffer pointed to by bytes. yyscanner The scanner object. the newly allocated buffer state object.
References mutabor_parser__scan_buffer, mutabor_parser_alloc, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_is_our_buffer.
Referenced by mutabor_parser__scan_string.
void* mutabor_parser_alloc(yy_size_t, yyscan_t yyscanner)
Referenced by mutabor_parser__create_buffer, mutabor_parser__scan_buffer, mutabor_parser__scan_bytes, mutabor_parser_ensure_buffer_stack, mutabor_parser_lex_init, yytbl_data_load, yytbl_hdr_read.
void* mutabor_parser_realloc(void *, yy_size_t, yyscan_t yyscanner)
Referenced by mutabor_parser_ensure_buffer_stack, yy_get_next_buffer.
void mutabor_parser_free(void *, yyscan_t yyscanner)
Referenced by mutabor_parser__delete_buffer, mutabor_parser_lex_destroy, mutabor_parser_tables_destroy, yytbl_fload, yytbl_hdr_read.
static int yy_init_globals(yyscan_t yyscanner)
int mutabor_parser_lex_destroy(yyscan_t yyscanner)
References mutabor_parser__delete_buffer, mutabor_parser_free, mutabor_parser_pop_buffer_state, yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_start_stack.
Referenced by MUTABOR_CLASS_FUNCTION.
int mutabor_parser_get_debug(yyscan_t yyscanner)
References yy_flex_debug.
void mutabor_parser_set_debug(int debug_flag, yyscan_t yyscanner)
References yy_flex_debug.
YY_EXTRA_TYPE mutabor_parser_get_extra(yyscan_t yyscanner)
Get the user-defined data for this scanner.
yyscanner The scanner object.
References yyextra.
void mutabor_parser_set_extra(YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
This data is never touched by the scanner. user_defined The data to be associated with this scanner. yyscanner The scanner object.
References yyextra.
FILE* mutabor_parser_get_in(yyscan_t yyscanner)
Get the input stream.
yyscanner The scanner object.
References yyin.
void mutabor_parser_set_in(FILE *in_str, yyscan_t yyscanner)
Set the input stream.
This does not discard the current input buffer. in_str A readable stream. yyscanner The scanner object. mutabor_parser__switch_to_buffer
References yyin.
Referenced by MUTABOR_CLASS_FUNCTION.
FILE* mutabor_parser_get_out(yyscan_t yyscanner)
Get the output stream.
yyscanner The scanner object.
References yyout.
void mutabor_parser_set_out(FILE *out_str, yyscan_t yyscanner)
References yyout.
int mutabor_parser_get_leng(yyscan_t yyscanner)
Get the length of the current token.
yyscanner The scanner object.
References yyleng.
char* mutabor_parser_get_text(yyscan_t yyscanner)
Get the current token.
yyscanner The scanner object.
References yytext.
int mutabor_parser_get_lineno(yyscan_t yyscanner)
Get the current line number.
yyscanner The scanner object.
References YY_CURRENT_BUFFER, yylineno.
void mutabor_parser_set_lineno(int line_number, yyscan_t yyscanner)
Set the current line number.
line_number yyscanner The scanner object.
References YY_CURRENT_BUFFER, yy_fatal_error, yylineno.
YYSTYPE* mutabor_parser_get_lval(yyscan_t yyscanner)
References yylval.
void mutabor_parser_set_lval(YYSTYPE *yylval_param, yyscan_t yyscanner)
References yylval.
YYLTYPE* mutabor_parser_get_lloc(yyscan_t yyscanner)
References yylloc.
void mutabor_parser_set_lloc(YYLTYPE *yylloc_param, yyscan_t yyscanner)
References yylloc.
int mutabor_parser_tables_fload(FILE *fp, yyscan_t yyscanner)
Load the DFA tables for this scanner from the given stream.
References YYTABLES_NAME, yytbl_fload.
Referenced by main, MUTABOR_CLASS_FUNCTION.
int mutabor_parser_tables_destroy(yyscan_t yyscanner)
Destroy the loaded tables, freeing memory, etc.
References yytbl_dmap::dm_arr, yytbl_dmap::dm_id, mutabor_parser_free.
Referenced by MUTABOR_CLASS_FUNCTION.
int mutabor_parser_lex(YYSTYPE *yylval_param, YYLTYPE *yylloc_param, yyscan_t yyscanner)