mutaborGUI::MutLogicWnd
bool mutaborGUI::MutLogicWnd::Ok
Referenced by BoxChangedAction, UpDate.
int mutaborGUI::MutLogicWnd::nTags
wxWindow* mutaborGUI::MutLogicWnd::ColorBar1
wxWindow * mutaborGUI::MutLogicWnd::ColorBar2
mutabor::Box mutaborGUI::MutLogicWnd::box
Referenced by BoxChanged, CmBox, CmMutTag, CmTaste, MakeTitle, OnActivate, OnChar, OnGetFocus, UpDate, ~MutLogicWnd.
wxSize mutaborGUI::MutLogicWnd::TagMinSize
Referenced by FixSizer, UpDate.
mutaborGUI::MutLogicWnd::MutLogicWnd(wxWindow *parent, mutabor::Box b, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
mutaborGUI::MutLogicWnd::~MutLogicWnd()
References box, mutASSERT, mutaborGUI::BoxData::SetLogicWindow, mutaborGUI::ToGUIBase, UNREACHABLEC.
wxString mutaborGUI::MutLogicWnd::MakeTitle()
References _, box, mutaborGUI::CompiledFile.
Referenced by BoxChanged, CmBox, mutaborGUI::MutFrame::LogicWinOpen.
void mutaborGUI::MutLogicWnd::BoxChanged()
References box, mutaborGUI::BoxData::GetBackgroundColour, mutaborGUI::BoxData::GetTextColour, MakeTitle, mutASSERT, SetBackgroundColour, SetForegroundColour, mutaborGUI::ToGUIBase.
void mutaborGUI::MutLogicWnd::OnSize(wxSizeEvent &event)
References FixSizer.
void mutaborGUI::MutLogicWnd::FixSizer()
References mutASSERT, TagMinSize.
Referenced by OnSize, UpDate.
void mutaborGUI::MutLogicWnd::OnClose(wxCloseEvent &event)
References doClose.
void mutaborGUI::MutLogicWnd::OnAuiClose(wxAuiManagerEvent &event)
References doClose.
void mutaborGUI::MutLogicWnd::doClose(wxEvent &event)
References mutaborGUI::CM_STOP, DEBUGLOG, DEBUGLOGBASE, mutaborGUI::NumberOfOpen, TRACEC, WK_LOGIC.
Referenced by OnAuiClose, OnClose.
void mutaborGUI::MutLogicWnd::UpDate()
References _, box, mutabor::BoxClass::logic_entry::CurrentLogic, FixSizer, mutabor::BoxClass::logic_entry::Logic, mutASSERT, Ok, SetBackgroundColour, SetForegroundColour, TagMinSize, mutaborGUI::ToGUIBase.
Referenced by CmBox, CmUpdateUI.
void mutaborGUI::MutLogicWnd::CmMutTag(wxCommandEvent &event)
References box, mutaborGUI::MutTag::GetIsLogic, mutaborGUI::MutTag::GetKey, mutabor::BoxClass::KeyboardLogic, mutabor::BoxClass::KeyboardNoLogic, mutASSERT, mutaborGUI::SetCurrentBox, Tag, TRACEC, UNREACHABLEC.
void mutaborGUI::MutLogicWnd::CmUpdateUI(wxCommandEvent &event)
References UpDate.
void mutaborGUI::MutLogicWnd::CmBox()
References box, mutaborGUI::CompiledFile, DEBUGLOG, MakeTitle, UpDate.
void mutaborGUI::MutLogicWnd::OnChar(wxKeyEvent &event)
References box, CmTaste, mutaborGUI::pubTaste, mutaborGUI::SetCurrentBox, TRACEC.
void mutaborGUI::MutLogicWnd::CmTaste()
References box, mutaborGUI::CM_MUTTAG, mutabor::BoxClass::KeyboardAny, mutabor::BoxClass::KeyboardLogic, mutabor::BoxClass::KeyboardNoLogic, mutASSERT, mutaborGUI::pubTaste, UNREACHABLEC.
Referenced by OnChar.
void mutaborGUI::MutLogicWnd::OnActivate(wxActivateEvent &event)
References box, mutUnused, mutaborGUI::SetCurrentBox, TRACEC.
void mutaborGUI::MutLogicWnd::OnGetFocus(wxFocusEvent &event)
References box, mutaborGUI::SetCurrentBox, TRACEC.
void mutaborGUI::MutLogicWnd::BoxChangedAction(int flags)
References Ok.
bool mutaborGUI::MutLogicWnd::SetBackgroundColour(const wxColour &colour)
Referenced by BoxChanged, UpDate.
bool mutaborGUI::MutLogicWnd::SetForegroundColour(const wxColour &colour)
Referenced by BoxChanged, UpDate.