mutaborGUI::MutDocument
virtual DECLARE_DYNAMIC_CLASS (MutDocument) public mutaborGUI::MutDocument::~MutDocument()
Referenced by BEGIN_EVENT_TABLE.
virtual wxCommandProcessor* mutaborGUI::MutDocument::OnCreateCommandProcessor()
Referenced by BEGIN_EVENT_TABLE.
bool mutaborGUI::MutDocument::DoSaveDocument(const wxString &filename)
Referenced by BEGIN_EVENT_TABLE.
bool mutaborGUI::MutDocument::DoOpenDocument(const wxString &filename)
Referenced by BEGIN_EVENT_TABLE.
virtual bool mutaborGUI::MutDocument::OnNewDocument()
Referenced by BEGIN_EVENT_TABLE.
virtual bool mutaborGUI::MutDocument::IsModified(void) const
Referenced by BEGIN_EVENT_TABLE.
virtual void mutaborGUI::MutDocument::Modify(bool mod)
Referenced by BEGIN_EVENT_TABLE.
bool mutaborGUI::MutDocument::CheckLogic()
Referenced by BEGIN_EVENT_TABLE.
virtual bool mutaborGUI::MutDocument::OnSaveModified()
Referenced by BEGIN_EVENT_TABLE.
virtual wxOutputStream& mutaborGUI::MutDocument::SaveObject(wxOutputStream &stream)
Referenced by BEGIN_EVENT_TABLE.
virtual wxInputStream& mutaborGUI::MutDocument::LoadObject(wxInputStream &stream)
Referenced by BEGIN_EVENT_TABLE.
virtual bool mutaborGUI::MutDocument::OnCreate(const wxString &path, long flags)
Referenced by BEGIN_EVENT_TABLE.
void mutaborGUI::MutDocument::CmdNewView(wxCommandEvent &event)
Referenced by BEGIN_EVENT_TABLE.
void mutaborGUI::MutDocument::OnNewViewUpdateUI(wxUpdateUIEvent &event)
Referenced by BEGIN_EVENT_TABLE.
void mutaborGUI::MutDocument::CmdUpdateAllViews(wxCommandEvent &event)
Referenced by BEGIN_EVENT_TABLE.
bool mutaborGUI::MutDocument::TryParent(wxEvent &event)
Pass certain events to the Application.
MutView::ProcessEvent is called indirectly from MutApp event handlers. This leads to endless loops. To prevent these loops, we must be very careful, which kind of events get passed back.Probably no events should be propagated.
Referenced by BEGIN_EVENT_TABLE.