intrusive_ptr_refcount_type
typedef mutabor::ScopedCondLock<locking> intrusive_ptr_refcount_type< locking >::locker
volatile size_t intrusive_ptr_refcount_type< locking >::value
Referenced by intrusive_ptr_refcount_type< locking >::operator size_t, intrusive_ptr_refcount_type< locking >::operator++, intrusive_ptr_refcount_type< locking >::operator--.
mutabor::Mutex intrusive_ptr_refcount_type< locking >::mutex
Referenced by intrusive_ptr_refcount_type< locking >::lock, intrusive_ptr_refcount_type< locking >::operator size_t, intrusive_ptr_refcount_type< locking >::operator++, intrusive_ptr_refcount_type< locking >::operator--, intrusive_ptr_refcount_type< locking >::unlock.
intrusive_ptr_refcount_type< locking >::intrusive_ptr_refcount_type()
void intrusive_ptr_refcount_type< locking >::lock()
References intrusive_ptr_refcount_type< locking >::mutex.
Referenced by intrusive_ptr_refcount_type< locking >::operator size_t, intrusive_ptr_refcount_type< locking >::operator++, intrusive_ptr_refcount_type< locking >::operator--.
void intrusive_ptr_refcount_type< locking >::unlock()
References intrusive_ptr_refcount_type< locking >::mutex.
size_t intrusive_ptr_refcount_type< locking >::operator++()
References intrusive_ptr_refcount_type< locking >::lock, intrusive_ptr_refcount_type< locking >::mutex, intrusive_ptr_refcount_type< locking >::value.
size_t intrusive_ptr_refcount_type< locking >::operator++(int)
References intrusive_ptr_refcount_type< locking >::lock, intrusive_ptr_refcount_type< locking >::mutex, intrusive_ptr_refcount_type< locking >::value.
size_t intrusive_ptr_refcount_type< locking >::operator--()
References intrusive_ptr_refcount_type< locking >::lock, intrusive_ptr_refcount_type< locking >::mutex, intrusive_ptr_refcount_type< locking >::value.
size_t intrusive_ptr_refcount_type< locking >::operator--(int)
References intrusive_ptr_refcount_type< locking >::lock, intrusive_ptr_refcount_type< locking >::mutex, intrusive_ptr_refcount_type< locking >::value.
intrusive_ptr_refcount_type< locking >::operator size_t() const
References intrusive_ptr_refcount_type< locking >::lock, intrusive_ptr_refcount_type< locking >::mutex, intrusive_ptr_refcount_type< locking >::value.
void intrusive_ptr_add_ref(intrusive_ptr_T *obj)
void intrusive_ptr_release(intrusive_ptr_T *obj)
size_t intrusive_ptr_get_refcount(intrusive_ptr_T *obj)