Parser
struct aktions_liste* list_of_aktionen
Liste von Aktionen.
Referenced by get_last_aktions_liste.
struct ausloeser* tmp_ausloeser
Globaler Zwischenspeicher für auslösende Ereignisse.
Referenced by get_last_ausloeser.
struct harmonie_ereignis* first_harmonie[MAX_BOX][MAX_BOX]
Liste der globalen auslösenden Harmonieen.
Referenced by mutabor_tabellen_generator.
struct harmonie_ereignis** last_global_harmonie[MAX_BOX][MAX_BOX]
Letztes Element der globalen auslösenden Harmonien.
Referenced by mutabor_tabellen_generator.
struct harmonie_ereignis** first_lokal_harmonie
Liste der lokalen auslösenden Harmonien.
Referenced by expandiere_logik, mutabor_tabellen_generator.
struct keyboard_ereignis* first_keyboard[MAX_BOX][MAX_BOX]
Liste der globalen auslösenden Tastenereignissen.
Referenced by mutabor_tabellen_generator, boxTest::test_init.
struct keyboard_ereignis** last_global_keyboard[MAX_BOX][MAX_BOX]
Letztes Element der globalen auslösenden Tastenereignissen.
Referenced by mutabor_tabellen_generator, boxTest::test_init.
struct keyboard_ereignis** first_lokal_keyboard
Liste der lokalen auslösenden Tastenereignissen.
Referenced by expandiere_logik, mutabor_tabellen_generator.
struct midi_ereignis* first_midi[MAX_BOX][MAX_BOX]
Liste der globalen auslösenden MIDI-Ereignissen.
Referenced by mutabor_tabellen_generator, boxTest::test_init.
struct midi_ereignis** last_global_midi[MAX_BOX][MAX_BOX]
Letztes Element der globalen auslösenden MIDI-Ereignissen.
Referenced by mutabor_tabellen_generator, boxTest::test_init.
struct midi_ereignis** first_lokal_midi
Liste der lokalen auslösenden MIDI-Ereignissen.
Referenced by expandiere_logik, mutabor_tabellen_generator.
struct harmonie* list_of_harmonien
Wurzel der Harmonien.
Referenced by check_ausloeser, mutabor_programm_einlesen.
void init_aktions_liste(void)
Setzt Aktionsliste auf NULL.
Die Argumentliste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_new_aktion_aufruf_element(char *name)
Fügt eine Aufruf-Aktion ans Ende von list_of_argumente an.
Der Aufruf erhält die letzte eingelesene Argumentliste. name Bezeichnung des Aufrufs, der angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References aktion_aufruf, get_last_argument_liste, name, aktions_liste::next, aktions_liste::u, xmalloc.
Referenced by switch, yyparse.
void get_new_aktion_midi_out_element(void)
Fügt eine Midi-Ausgabe-Aktion ans Ende von list_of_aktionen an.
Dazu wird die letzte Integersequenz verwendet. Es wird immer die gesamte Liste durchsucht. Effektivität?
References aktion_midi_out, get_last_integersequenz, aktions_liste::next, aktions_liste::u, xmalloc.
Referenced by switch, yyparse.
struct aktions_liste* get_last_aktions_liste(void)
Gibt die Wurzel von list_of_aktionen zurück.
References list_of_aktionen.
Referenced by get_new_anweisung, get_umstimmung_umstimmungs_bund, get_umstimmungs_case_default_element, get_umstimmungs_case_zahl_element.
void print_aktions_liste(struct aktions_liste *lauf)
Referenced by mutabor_programm_einlesen.
void check_aktionen(struct aktions_liste *aktionen, char *name)
Testet eine Liste von Aktionen auf Zulässigkeit.
Wird eine nicht zulässige oder erreichbare Konfiguration gefunden, wird je nach Situation ein fataler Fehler oder eine Compiler-Warnung ausgelöst. aktionen Aktionsliste, die geprüft werden soll name Name für Meldungen
References aktion_aufruf, aktions_liste::aktion_aufruf, aktion_midi_out, aktions_liste::aktion_midi_out, aktions_liste::aktions_typ, argument_list_laenge, compiler_warning, fatal_error, get_logik, get_umstimmung, list_of_logiken, list_of_tonsysteme, list_of_umstimmungen, midiliste::midi_code, midiliste::next, aktions_liste::next, parameter_list_laenge, umstimmung::parameter_liste, parser_get_tonsystem, aktions_liste::u.
Referenced by check_konsistenz, check_logik_konsistenz.
void init_ausloeser(void)
Setzt Liste auslösender Ereignisse auf NULL.
Die Liste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
struct ausloeser* get_last_ausloeser(void)
Gibt Wurzelelement von tmp_ausloeser zurück.
References tmp_ausloeser.
Referenced by get_new_anweisung, get_new_logik.
void get_ausloeser_default(void)
Markiert tmp_ausloeser als Standard-Auslöser.
References ausloeser_default, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_harmonie(void)
Deklariert tmp_ausloeser als Harmonie-Auslöser und setzt die Werte aus dem Zwischenspeicher.
References ausloeser_harmonie, tmp_nach_taste, tmp_name, tmp_vor_taste, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_harmonie_form(void)
Deklariert tmp_ausloeser als Harmonie-Auslöser und setzt die Werte aus dem Zwischenspeicher.
References ausloeser_harmonie_form, tmp_nach_taste, tmp_name, tmp_vor_taste, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_taste(char *name)
Deklariert tmp_ausloeser als Tasten-Auslöser.
Ist die Taste nicht definiert, wird ein fataler Fehler ausgelöst. name Name der auslösenden Taste
References ausloeser_taste, fatal_error, name, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_midi_in(void)
Deklariert tmp_ausloeser als MIDI-Sequenz.
Dafür wird die letzte eingelesene Ganzzahlen-Folge verwendet.
References ausloeser_midi_in, get_last_integersequenz, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void print_ausloeser(struct ausloeser *this_)
Gibt einen Auslöser auf der Standard-Ausgabe aus.
this_ Auslöser.
References ausloeser_default, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser_taste, ausloeser::ausloeser_taste, ausloeser::ausloeser_typ, fatal_error, print_integersequenz, ausloeser::u.
Referenced by mutabor_programm_einlesen.
void check_ausloeser(struct ausloeser *ausloeser, char *name)
Testet einen Auslöser auf Zulässigkeit.
Wird eine nicht zulässige oder erreichbare Konfiguration gefunden, wird je nach Situation ein fataler Fehler oder eine Compiler-Warnung ausgelöst. ausloeser Auslöser, der geprüft werden soll name Name für Meldungen
References ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser::ausloeser_typ, compiler_warning, enthalten_in_tastenliste, fatal_error, get_harmonie, list_of_harmonien, midiliste::midi_code, midiliste::next, harmonie::tastenliste, ausloeser::u.
Referenced by check_konsistenz, check_logik_konsistenz.
struct harmonie* get_harmonie(char *name, struct harmonie *liste)
Sucht eine Harmonie in einer Harmonieliste.
name Name der gesuchten Harmonie liste Liste der Harmodien, in der gesucht wird NULL falls Harmonie nicht in liste Harmonie sonst.
References get_harmonie, harmonie::name, harmonie::next.
Referenced by check_ausloeser, expand_pattern, get_harmonie.
void drucke_harmonie(struct harmonie *this_)
Gibt eine Harmonie auf der Standardausgabe aus.
this_ Harmonie
References harmonie::bezugstaste, harmonie::name, taste::next, taste::stern, taste::taste, harmonie::tastenliste.
Referenced by mutabor_programm_einlesen.
void get_new_harmonie(char *name, int bezugstaste)
Fügt eine Harmonie ans Ende von list_of_harmonien an.
Dabei wird die letzte eingelesene Tastenliste (tmp_tastenliste) verwendet. name Name der Harmonie bezugstaste Bezugstaste für die Harmonie (Schlüssel-C = 60) Es wird immer die gesamte Liste durchsucht. Effektivität?
References harmonie::bezugstaste, fatal_error, mutabor_debug_level, name, harmonie::next, harmonie::tastenliste, tmp_tastenliste, xmalloc.
Referenced by switch, yyparse.
void get_harmoniebezeichner(int vor_taste, char *name, int nach_taste)
Sichert die Daten eines Harmoniebezeichners im globalen Zwischenspeicher.
vor_taste Tiefste Taste beim Anschlagen der Harmonie name Name der Harmonie(-form) nach_taste Höchste Teste beim Anschlagen der Harmonie
References name, tmp_nach_taste, tmp_name, tmp_vor_taste.
Referenced by switch, yyparse.