mutlex.c
YY_INT_ALIGNED
FLEX_SCANNER
YY_FLEX_MAJOR_VERSION
YY_FLEX_MINOR_VERSION
YY_FLEX_SUBMINOR_VERSION
FLEX_BETA
FLEXINT_H
INT8_MIN
INT16_MIN
INT32_MIN
INT8_MAX
INT16_MAX
INT32_MAX
UINT8_MAX
UINT16_MAX
UINT32_MAX
yyconst
YY_NULL
YY_SC_TO_UI
Referenced by while, yy_get_previous_state.
YY_TYPEDEF_YY_SCANNER_T
yyin
Referenced by if, input, mutabor_parser__load_buffer_state, mutabor_parser_get_in, mutabor_parser_restart, mutabor_parser_set_in, while, yy_get_next_buffer, yy_init_globals.
yyout
Referenced by if, mutabor_parser_get_out, mutabor_parser_set_out, yy_init_globals.
yyextra
Referenced by mutabor_parser_get_extra, mutabor_parser_set_extra.
yyleng
Referenced by mutabor_parser_get_leng, while.
yytext
Referenced by mutabor_parser_get_text, while.
yylineno
Referenced by input, mutabor_parser_get_lineno, mutabor_parser_set_lineno, while, yyunput.
yycolumn
Referenced by input, mutabor_parser_get_column, mutabor_parser_set_column, while.
yy_flex_debug
Referenced by mutabor_parser_get_debug, mutabor_parser_set_debug, while.
BEGIN
Referenced by while.
YY_START
Referenced by while.
YYSTATE
YY_STATE_EOF
Referenced by while.
YY_NEW_FILE
Referenced by input, while.
YY_END_OF_BUFFER_CHAR
Referenced by input, mutabor_parser__flush_buffer, mutabor_parser__scan_buffer, mutabor_parser__scan_bytes, yy_get_next_buffer.
YY_BUF_SIZE
Referenced by if, mutabor_parser_restart.
YY_TYPEDEF_YY_BUFFER_STATE
EOB_ACT_CONTINUE_SCAN
Referenced by input, while, yy_get_next_buffer.
EOB_ACT_END_OF_FILE
Referenced by input, while, yy_get_next_buffer.
EOB_ACT_LAST_MATCH
Referenced by input, while, yy_get_next_buffer.
YY_LESS_LINENO
yyless
unput
YY_TYPEDEF_YY_SIZE_T
YY_STRUCT_YY_BUFFER_STATE
YY_BUFFER_NEW
Referenced by mutabor_parser__flush_buffer, mutabor_parser__scan_buffer, while.
YY_BUFFER_NORMAL
Referenced by while.
YY_BUFFER_EOF_PENDING
Referenced by yy_get_next_buffer.
YY_CURRENT_BUFFER
Referenced by if, mutabor_parser__delete_buffer, mutabor_parser__flush_buffer, mutabor_parser__init_buffer, mutabor_parser__switch_to_buffer, mutabor_parser_get_column, mutabor_parser_get_lineno, mutabor_parser_lex_destroy, mutabor_parser_pop_buffer_state, mutabor_parser_push_buffer_state, mutabor_parser_restart, mutabor_parser_set_column, mutabor_parser_set_lineno, yy_get_next_buffer.
YY_CURRENT_BUFFER_LVALUE
Referenced by if, input, mutabor_parser__delete_buffer, mutabor_parser__load_buffer_state, mutabor_parser__switch_to_buffer, mutabor_parser_lex_destroy, mutabor_parser_pop_buffer_state, mutabor_parser_push_buffer_state, mutabor_parser_restart, while, yy_get_next_buffer, yyunput.
YY_FLUSH_BUFFER
yy_new_buffer
yy_set_interactive
yy_set_bol
YY_AT_BOL
mutabor_parser_wrap
Referenced by input, while.
YY_SKIP_YYWRAP
FLEX_DEBUG
yytext_ptr
YY_DO_BEFORE_ACTION
Referenced by while.
YY_NUM_RULES
YY_END_OF_BUFFER
Referenced by while.
REJECT
yymore
YY_MORE_ADJ
Referenced by while, yy_get_next_buffer, yy_get_previous_state.
YY_RESTORE_YY_MORE_OFFSET
Referenced by while.
YY_USER_ACTION
BUMP
Referenced by while.
INITIAL
Referenced by while.
string
Referenced by mutabor::BoxClass::ActionToString, mutAssertFailure.
YY_EXTRA_TYPE
yylval
yylloc
YY_READ_BUF_SIZE
Referenced by yy_get_next_buffer.
ECHO
Referenced by while.
YY_INPUT
Referenced by yy_get_next_buffer.
yyterminate
Referenced by while.
YY_START_STACK_INCR
YY_FATAL_ERROR
Referenced by mutabor_parser__create_buffer, mutabor_parser__scan_buffer, mutabor_parser__scan_bytes, while, yy_get_next_buffer, yyunput.
yyskel_static
YYTBL_MAGIC
Magic number for serialized format.
Referenced by yytbl_hdr_read.
yypad64
Calculate (0-7) = number bytes needed to pad n to next 64-bit boundary.
Referenced by yytbl_data_load.
YYTABLES_TYPES
YYTDFLAGS2BYTES
Extract corresponding data size_t from td_flags.
Referenced by yytbl_data_load.
YY_DECL_IS_OURS
YY_DECL
YY_BREAK
Referenced by while.
YY_RULE_SETUP
Referenced by while.
YY_EXIT_FAILURE
Referenced by yy_fatal_error.
yyless
YYTABLES_NAME
Referenced by mutabor_parser_tables_fload.
yytbl_id
1-dim ints
yytbl_flags
data is an array of type flex_int8_t
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void* yyscan_t
typedef struct yy_buffer_state* YY_BUFFER_STATE
typedef unsigned int yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
yyconst flex_int16_t* yy_accept
Referenced by while, yy_get_previous_state, yy_try_NUL_trans.
yyconst flex_int32_t* yy_ec
Referenced by while, yy_get_previous_state.
yyconst flex_int32_t* yy_meta
Referenced by while, yy_get_previous_state, yy_try_NUL_trans.
yyconst flex_int16_t* yy_base
Referenced by while, yy_get_previous_state, yy_try_NUL_trans.
yyconst flex_int16_t* yy_def
Referenced by while, yy_get_previous_state, yy_try_NUL_trans.
yyconst flex_int16_t* yy_nxt
Referenced by while, yy_get_previous_state, yy_try_NUL_trans, yytbl_data_load.
yyconst flex_int16_t* yy_chk
Referenced by while, yy_get_previous_state, yy_try_NUL_trans.
yyconst flex_int32_t* yy_rule_can_match_eol
Referenced by while.
yyconst flex_int16_t* yy_rule_linenum
Referenced by while.
struct yytbl_dmap yydmap[][]
A {0,0,0}-terminated list of structs, forming the map.
YY_DECL register yy_state_type yy_current_state
The main scanner function which does all the work.
register char* yy_cp
register char * yy_bp
register int yy_act
struct yyguts_t* yyg
yylval
yylloc
int mutabor_parser_lex_init(yyscan_t *scanner)
References mutabor_parser_alloc, yy_init_globals.
Referenced by MUTABOR_CLASS_FUNCTION.
void mutabor_parser_restart(FILE *input_file, yyscan_t yyscanner)
Immediately switch to a different input stream.
input_file A readable stream. yyscanner The scanner object. This function does not reset the start condition to INITIAL .
References mutabor_parser__create_buffer, mutabor_parser__init_buffer, mutabor_parser__load_buffer_state, mutabor_parser_ensure_buffer_stack, YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyin.
Referenced by input, yy_get_next_buffer.
void mutabor_parser__switch_to_buffer(YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Switch to a different input buffer.
new_buffer The new input buffer. yyscanner The scanner object.
References mutabor_parser__load_buffer_state, mutabor_parser_ensure_buffer_stack, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars.
Referenced by mutabor_parser__scan_buffer.
YY_BUFFER_STATE mutabor_parser__create_buffer(FILE *file, int size, yyscan_t yyscanner)
Allocate and initialize an input buffer state.
file A readable stream. size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE. yyscanner The scanner object. the allocated buffer state.
References mutabor_parser__init_buffer, mutabor_parser_alloc, yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yy_buffer_state::yy_is_our_buffer.
Referenced by if, mutabor_parser_restart.
void mutabor_parser__delete_buffer(YY_BUFFER_STATE b, yyscan_t yyscanner)
Destroy the buffer.
b a buffer created with mutabor_parser__create_buffer() yyscanner The scanner object.
References mutabor_parser_free, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_buffer_state::yy_is_our_buffer.
Referenced by mutabor_parser_lex_destroy, mutabor_parser_pop_buffer_state.
void mutabor_parser__flush_buffer(YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
On the next scan, YY_INPUT will be called. b the buffer state to be flushed, usually YY_CURRENT_BUFFER. yyscanner The scanner object.
References mutabor_parser__load_buffer_state, yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, yy_buffer_state::yy_n_chars.
Referenced by mutabor_parser__init_buffer.
void mutabor_parser_push_buffer_state(YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
The new state becomes the current state. This function will allocate the stack if necessary. new_buffer The new state. yyscanner The scanner object.
References mutabor_parser__load_buffer_state, mutabor_parser_ensure_buffer_stack, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars.
void mutabor_parser_pop_buffer_state(yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
The next element becomes the new top. yyscanner The scanner object.
References mutabor_parser__delete_buffer, mutabor_parser__load_buffer_state, yyguts_t::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof.
Referenced by mutabor_parser_lex_destroy.
static void mutabor_parser_ensure_buffer_stack(yyscan_t yyscanner)
References mutabor_parser_alloc, mutabor_parser_realloc, yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top.
Referenced by if, mutabor_parser__switch_to_buffer, mutabor_parser_push_buffer_state, mutabor_parser_restart.
static void mutabor_parser__load_buffer_state(yyscan_t yyscanner)
References yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, yyin.
Referenced by if, mutabor_parser__flush_buffer, mutabor_parser__switch_to_buffer, mutabor_parser_pop_buffer_state, mutabor_parser_push_buffer_state, mutabor_parser_restart.
static void mutabor_parser__init_buffer(YY_BUFFER_STATE b, FILE *file, yyscan_t yyscanner)
References isatty, mutabor_parser__flush_buffer, yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive.
Referenced by mutabor_parser__create_buffer, mutabor_parser_restart.
YY_BUFFER_STATE mutabor_parser__scan_buffer(char *base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
base the character buffer size the size in bytes of the character buffer yyscanner The scanner object. the newly allocated buffer state object.
References mutabor_parser__switch_to_buffer, mutabor_parser_alloc, yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, yy_buffer_state::yy_n_chars.
Referenced by mutabor_parser__scan_bytes.
YY_BUFFER_STATE mutabor_parser__scan_string(yyconst char *yy_str, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
The next call to mutabor_parser_lex() will scan from a copy of str. str a NUL-terminated string to scan yy_str a NUL-terminated string to scan yyscanner The scanner object. the newly allocated buffer state object. If you want to scan bytes that may contain NUL values, then use mutabor_parser__scan_bytes() instead.
References mutabor_parser__scan_bytes.
YY_BUFFER_STATE mutabor_parser__scan_bytes(yyconst char *bytes, int len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
The next call to mutabor_parser_lex() will scan from a copy of bytes. bytes the byte buffer to scan len the number of bytes in the buffer pointed to by bytes. yyscanner The scanner object. the newly allocated buffer state object.
References mutabor_parser__scan_buffer, mutabor_parser_alloc, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_is_our_buffer.
Referenced by mutabor_parser__scan_string.
void * mutabor_parser_alloc(yy_size_t, yyscan_t yyscanner)
Referenced by mutabor_parser__create_buffer, mutabor_parser__scan_buffer, mutabor_parser__scan_bytes, mutabor_parser_ensure_buffer_stack, mutabor_parser_lex_init, yytbl_data_load, yytbl_hdr_read.
void * mutabor_parser_realloc(void *, yy_size_t, yyscan_t yyscanner)
Referenced by mutabor_parser_ensure_buffer_stack, yy_get_next_buffer.
void mutabor_parser_free(void *, yyscan_t yyscanner)
Referenced by mutabor_parser__delete_buffer, mutabor_parser_lex_destroy, mutabor_parser_tables_destroy, yytbl_fload, yytbl_hdr_read.
static yy_state_type yy_get_previous_state(yyscan_t yyscanner)
References yy_accept, yy_base, yyguts_t::yy_c_buf_p, yy_chk, yy_cp, yy_current_state, yy_def, yy_ec, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yy_nxt, YY_SC_TO_UI, yyguts_t::yy_start.
Referenced by while.
static yy_state_type yy_try_NUL_trans(yy_state_type current_state, yyscan_t yyscanner)
References yy_accept, yy_base, yyguts_t::yy_c_buf_p, yy_chk, yy_cp, yy_current_state, yy_def, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, yy_meta, yy_nxt.
Referenced by while.
static int yy_get_next_buffer(yyscan_t yyscanner)
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, mutabor_parser_realloc, mutabor_parser_restart, yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yyguts_t::yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_READ_BUF_SIZE, yyin.
Referenced by input, while.
static void yy_fatal_error(yyconst char msg[], yyscan_t yyscanner)
Referenced by mutabor_parser_set_column, mutabor_parser_set_lineno, yytbl_data_load, yytbl_hdr_read.
int mutabor_parser_lex_destroy(yyscan_t yyscanner)
References mutabor_parser__delete_buffer, mutabor_parser_free, mutabor_parser_pop_buffer_state, yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_start_stack.
Referenced by MUTABOR_CLASS_FUNCTION.
int mutabor_parser_get_debug(yyscan_t yyscanner)
References yy_flex_debug.
void mutabor_parser_set_debug(int debug_flag, yyscan_t yyscanner)
References yy_flex_debug.
YY_EXTRA_TYPE mutabor_parser_get_extra(yyscan_t yyscanner)
Get the user-defined data for this scanner.
yyscanner The scanner object.
References yyextra.
void mutabor_parser_set_extra(YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
This data is never touched by the scanner. user_defined The data to be associated with this scanner. yyscanner The scanner object.
References yyextra.
FILE * mutabor_parser_get_in(yyscan_t yyscanner)
Get the input stream.
yyscanner The scanner object.
References yyin.
void mutabor_parser_set_in(FILE *in_str, yyscan_t yyscanner)
Set the input stream.
This does not discard the current input buffer. in_str A readable stream. yyscanner The scanner object. mutabor_parser__switch_to_buffer
References yyin.
Referenced by MUTABOR_CLASS_FUNCTION.
FILE * mutabor_parser_get_out(yyscan_t yyscanner)
Get the output stream.
yyscanner The scanner object.
References yyout.
void mutabor_parser_set_out(FILE *out_str, yyscan_t yyscanner)
References yyout.
int mutabor_parser_get_leng(yyscan_t yyscanner)
Get the length of the current token.
yyscanner The scanner object.
References yyleng.
char * mutabor_parser_get_text(yyscan_t yyscanner)
Get the current token.
yyscanner The scanner object.
References yytext.
int mutabor_parser_get_lineno(yyscan_t yyscanner)
Get the current line number.
yyscanner The scanner object.
References YY_CURRENT_BUFFER, yylineno.
void mutabor_parser_set_lineno(int line_number, yyscan_t yyscanner)
Set the current line number.
line_number yyscanner The scanner object.
References YY_CURRENT_BUFFER, yy_fatal_error, yylineno.
YYSTYPE * mutabor_parser_get_lval(yyscan_t yyscanner)
References yylval.
void mutabor_parser_set_lval(YYSTYPE *yylval_param, yyscan_t yyscanner)
References yylval.
YYLTYPE * mutabor_parser_get_lloc(yyscan_t yyscanner)
References yylloc.
void mutabor_parser_set_lloc(YYLTYPE *yylloc_param, yyscan_t yyscanner)
References yylloc.
static void yyunput(int c, char *buf_ptr, yyscan_t yyscanner)
static int input(yyscan_t yyscanner)
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, if, mutabor_parser_restart, mutabor_parser_wrap, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER_CHAR, yy_get_next_buffer, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, YY_NEW_FILE, yycolumn, yyin, yylineno.
Referenced by mutaborGUI::MutBoxChannelShape::Add, mutaborGUI::MutBoxChannelShape::DrawLines, mutaborGUI::MutBoxChannelShape::InitializeInputFilter, mutaborGUI::MutBoxChannelShape::ReadPanel, mutaborGUI::MutBoxChannelShape::Remove, mutaborGUI::MutBoxChannelShape::Replace.
yyskel_static flex_int32_t yytbl_calc_total_len(const struct yytbl_data *tbl)
Get the number of integers in this table.
This is NOT the same thing as the number of elements. td the table the number of integers in the table
References yytbl_data::td_hilen, yytbl_data::td_id, yytbl_data::td_lolen, YYTD_ID_TRANSITION.
Referenced by yytbl_data_load.
int mutabor_parser_tables_fload(FILE *fp, yyscan_t yyscanner)
Load the DFA tables for this scanner from the given stream.
References YYTABLES_NAME, yytbl_fload.
Referenced by main, MUTABOR_CLASS_FUNCTION.
int mutabor_parser_tables_destroy(yyscan_t yyscanner)
Destroy the loaded tables, freeing memory, etc.
References yytbl_dmap::dm_arr, yytbl_dmap::dm_id, mutabor_parser_free.
Referenced by MUTABOR_CLASS_FUNCTION.
int mutabor_parser_lex(YYSTYPE *yylval_param, YYLTYPE *yylloc_param, yyscan_t yyscanner)
if(yyg->yy_init)
References mutabor_parser__create_buffer, mutabor_parser__load_buffer_state, mutabor_parser_ensure_buffer_stack, YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_init, yyguts_t::yy_start, yyin, yyout.
while(1)
References ANSONSTEN, BEGIN, BUMP, ECHO, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, F_NUMBER, fatal_error, FORM, HARMONIE, IDENTIFIER, INITIAL, INSTRUMENT, INTEGER, INTERVALL, LOGIK, MIDI_IN, MIDI_OUT, mutabor_parser_wrap, TASTE, TON, TONSYSTEM, UMSTIMMUNG, WURZEL, yy_accept, yy_base, YY_BREAK, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yyguts_t::yy_c_buf_p, yy_chk, yy_cp, YY_CURRENT_BUFFER_LVALUE, yy_current_state, yy_def, yyguts_t::yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, yy_ec, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_flex_debug, yy_get_next_buffer, yy_get_previous_state, yyguts_t::yy_hold_char, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_NEW_FILE, yy_nxt, YY_RESTORE_YY_MORE_OFFSET, yy_rule_can_match_eol, yy_rule_linenum, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yyguts_t::yy_start, YY_STATE_EOF, yy_try_NUL_trans, yycolumn, yyin, yyleng, yylineno, yylloc, yylval, yyterminate, yytext.
static void yyunput(int c, register char *yy_bp, yyscan_t yyscanner)
References char, yy_bp, yyguts_t::yy_c_buf_p, yy_cp, YY_CURRENT_BUFFER_LVALUE, YY_FATAL_ERROR, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, yylineno.
int isatty(int)
static void yy_fatal_error(yyconst char *msg, yyscan_t yyscanner)
References YY_EXIT_FAILURE.
int mutabor_parser_get_column(yyscan_t yyscanner)
Get the current column number.
yyscanner The scanner object.
References YY_CURRENT_BUFFER, yycolumn.
void mutabor_parser_set_column(int column_no, yyscan_t yyscanner)
Set the current column.
line_number yyscanner The scanner object.
References YY_CURRENT_BUFFER, yy_fatal_error, yycolumn.
static int yy_init_globals(yyscan_t yyscanner)
References yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, yyguts_t::yy_init, yyguts_t::yy_start, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, yyguts_t::yy_start_stack_ptr, yyin, yyout.
Referenced by mutabor_parser_lex_init.
static int yytbl_read8(void *v, struct yytbl_reader *rd)
References yytbl_reader::bread, yytbl_reader::fp.
Referenced by yytbl_data_load.
static int yytbl_read16(void *v, struct yytbl_reader *rd)
References yytbl_reader::bread, yytbl_reader::fp.
Referenced by yytbl_data_load, yytbl_hdr_read.
static int yytbl_read32(void *v, struct yytbl_reader *rd)
References yytbl_reader::bread, yytbl_reader::fp.
Referenced by yytbl_data_load, yytbl_hdr_read.
static int yytbl_hdr_read(struct yytbl_hdr *th, struct yytbl_reader *rd, yyscan_t yyscanner)
Read the header.
References yytbl_reader::bread, yytbl_reader::fp, mutabor_parser_alloc, mutabor_parser_free, yytbl_hdr::th_flags, yytbl_hdr::th_hsize, yytbl_hdr::th_magic, yytbl_hdr::th_name, yytbl_hdr::th_ssize, yytbl_hdr::th_version, yy_fatal_error, YYTBL_MAGIC, yytbl_read16, yytbl_read32.
Referenced by yytbl_fload.
static struct yytbl_dmap* yytbl_dmap_lookup(struct yytbl_dmap *dmap, int id, yyscan_t yyscanner)
lookup id in the dmap list.
dmap pointer to first element in list NULL if not found.
References yytbl_dmap::dm_id.
Referenced by yytbl_data_load.
static int yytbl_data_load(struct yytbl_dmap *dmap, struct yytbl_reader *rd, yyscan_t yyscanner)
Read a table while mapping its contents to the local array.
dmap used to performing mapping 0 on success
References yytbl_reader::bread, yytbl_dmap::dm_arr, yytbl_dmap::dm_sz, mutabor_parser_alloc, yytbl_data::td_flags, yytbl_data::td_hilen, yytbl_data::td_id, yytbl_data::td_lolen, yy_fatal_error, yy_nxt, yypad64, yytbl_calc_total_len, yytbl_dmap_lookup, yytbl_read16, yytbl_read32, yytbl_read8, YYTD_ID_TRANSITION, YYTD_PTRANS, YYTD_STRUCT, YYTDFLAGS2BYTES.
Referenced by yytbl_fload.
static int yytbl_fload(FILE *fp, const char *key, yyscan_t yyscanner)
References yytbl_reader::bread, yytbl_reader::fp, mutabor_parser_free, yytbl_hdr::th_hsize, yytbl_hdr::th_name, yytbl_hdr::th_ssize, yytbl_hdr::th_version, yytbl_data_load, yytbl_hdr_read.
Referenced by mutabor_parser_tables_fload.