mutaborGUI::MutFrame
typedef wxDocChildFrame mutaborGUI::MutFrame::base
typedef std::map<int,mutabor::Box> mutaborGUI::MutFrame::boxCommandMap
wxMenu* mutaborGUI::MutFrame::editmenu
Referenced by MutFrame, SetEditMenu.
wxMenu* mutaborGUI::MutFrame::filemenu
Referenced by MutFrame, SetFileMenu, ~MutFrame.
int mutaborGUI::MutFrame::curStatusImg
wxAuiManager mutaborGUI::MutFrame::auimanager
Referenced by CloseClientWindow, CmDoActivate, CmRoutes, DoBoxWindowsClose, DoStop, EventPassOn, GetDockArt, LogicWinOpen, MutFrame, SetClient, TextBoxOpen, ~MutFrame.
wxWindow* mutaborGUI::MutFrame::client
Referenced by CeActivate, CmFileNew, CmFileOpen, CmRoutes, HasClient, LogicWinOpen, MutFrame, OnEraseBackground, OpenFile, PassEventToEditor, PassEventToEditorFind, PassEventToEditorUI, repaint_route, SetClient, TextBoxOpen.
MutFrame* mutaborGUI::MutFrame::ActiveWindow
Referenced by BoxWindowsClose, BoxWindowsOpen, CmDoActivate, DoStop, GetActiveDocument, GetActiveWindow, OnCloseWindow, RaiseLogic, RaiseTheFrame, ToggleTextBox.
std::map< int, mutabor::Box > mutaborGUI::MutFrame::boxCommandIds
Referenced by Destroy, RaiseLogic, UpdateBoxMenu.
mutaborGUI::MutFrame::MutFrame(wxFrame *parent, const wxWindowID id, const wxString &title, const wxPoint &pos, const wxSize &size, const long style)
Constructor.
This constructor creates a new main window.
mutaborGUI::MutFrame::MutFrame(MutDocument *doc, MutView *v, wxFrame *frame, wxWindowID id, const wxString &title, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long type=wxDEFAULT_FRAME_STYLE, const wxString &name=wxT("Mutabor frame"))
References _, auimanager, client, DetermineFrameSize, editmenu, filemenu.
mutaborGUI::MutFrame::~MutFrame()
Destructor.
References auimanager, filemenu, mutASSERT, mutaborGUI::MutView::SetTextsw.
void mutaborGUI::MutFrame::PassEventToEditor(wxCommandEvent &event)
passes an event to the editor.
This function is used to pass one event to the client window. event Event to be passed
References client.
Referenced by CmFileOpen.
void mutaborGUI::MutFrame::PassEventToEditorUI(wxUpdateUIEvent &event)
passes an UpdateUIEvent to the editor.
This function is used to pass one event to the client window. event Event to be passed
References client.
void mutaborGUI::MutFrame::PassEventToEditorFind(wxFindDialogEvent &event)
passes a FindDialogEvent to the editor.
This function is used to pass one event to the client window. event Event to be passed
References client.
void mutaborGUI::MutFrame::EventPassOn(wxCommandEvent &event)
passes an event to the MDI client window.
VeraltetThis function was formerly used to pass one event to the client MDI window. event Event to be passed
References auimanager, DEBUGLOG.
void mutaborGUI::MutFrame::OnAuiChildEvent(wxAuiManagerEvent &event)
This function informs the child windows about AUI events.
It is an event handler AUI events.The AUI manager does not inform the childs directly. event Event as passed by wxWidgets.
void mutaborGUI::MutFrame::OnCloseWindow(wxCloseEvent &event)
Handles close event.
This function tries to determine, if we can close the current window.
References ActiveWindow, DEBUGLOG, Destroy, SaveState, TRACEC.
void mutaborGUI::MutFrame::OnPaint(wxPaintEvent &event)
Hande paint events for Document/View framework.
This function call the paint function
References mutUnused, STUBC.
void mutaborGUI::MutFrame::CmFileNew(wxCommandEvent &WXUNUSED(event))
This function creates a new file editor.
Handle new file event if we don't have a client yet.
References client, OpenFile, STUBC.
Referenced by IMPLEMENT_APP.
void mutaborGUI::MutFrame::CmFileOpen(wxCommandEvent &WXUNUSED(event))
Open an existing file if we don't have a client yet.
References _, client, CM_FILEOPEN, CM_FILESAVEAS, DEBUGLOG, FileNameDialog, OpenFile, PassEventToEditor, STUBC, UNREACHABLEC.
bool mutaborGUI::MutFrame::OpenFile(wxString path, bool newfile=false)
Opens the given file, if we don't have a client yet.
open a file in a new frame. path Path of the file to open Noch zu erledigenfile loading fails silently if it is not in the systems encoding.
References _, APPNAME, client, DEBUGLOG, mutaborGUI::MutEditFile::LoadFile, mutUnused, SetClient, STUBC.
Referenced by CmFileNew, CmFileOpen, IMPLEMENT_APP.
bool mutaborGUI::MutFrame::SetClient(wxWindow *win, const wxString &title)
Attach a client to the Frame.
Attach a client. window to be attached as the client.
References auimanager, client, DEBUGLOG, mutASSERT.
Referenced by OpenFile.
virtual void mutaborGUI::MutFrame::SetLabel(const wxString &label)
Set the window name, i.e. frame title.
void mutaborGUI::MutFrame::CmDoActivate(wxCommandEvent &event)
Get a file name to open static wxString FileNameDialog(wxWindow * parent);.
References _, mutabor::BoxClass::ActivateAll, ActiveWindow, mutaborGUI::StatusBar::AllSetActive, mutaborGUI::StatusBar::AllSetPlaystate, auimanager, BoxWindowsOpen, mutaborGUI::CheckBoxesUsed, Compiled, DEBUGLOG, mutabor::BoxClass::GetBox, mutabor::BoxClass::GetBoxList, mutaborGUI::BoxData::GetLogicWindow, mutaborGUI::LogicOn, mutaborGUI::MutChildApi::MakeTitle, mutabor::hidden::minimal_box_used, mutabor::NeedsRealTime, mutaborGUI::OWM, repaint_route, mutaborGUI::StatusBar::Stop, mutaborGUI::ToGUIBase, TRACEC, UpdateBoxMenu, WK_ACT, WK_KEY, WK_ROUTE.
Referenced by CmInDevPlay.
void mutaborGUI::MutFrame::RaiseLogic(wxCommandEvent &event)
References ActiveWindow, boxCommandIds, mutaborGUI::CM_BOX, DEBUGLOG, mutaborGUI::GetCurrentBox, mutaborGUI::BoxData::GetLogicWindow, muT, mutASSERT, RaiseTheFrame, mutaborGUI::SetCurrentBox, mutaborGUI::ToGUIBase.
Referenced by UpdateBoxMenu.
wxMenuItem * mutaborGUI::MutFrame::ClearMenuItem(int id)
References ClearSubMenu.
Referenced by DoStop, UpdateBoxMenu.
void mutaborGUI::MutFrame::ClearSubMenu(wxMenuItem *item)
References DEBUGLOG.
Referenced by ClearMenuItem.
void mutaborGUI::MutFrame::DoStop()
References ActiveWindow, mutaborGUI::StatusBar::AllSetActive, mutaborGUI::StatusBar::AllSetPlaystate, auimanager, ClearMenuItem, mutaborGUI::CM_SELECTBOX, mutaborGUI::StatusBar::Hide, mutaborGUI::LogicOn, mutASSERT, repaint_route, mutabor::BoxClass::StopAll, StopInDev, TRACEC.
Referenced by CmStop.
void mutaborGUI::MutFrame::CmStop(wxCommandEvent &WXUNUSED(event))
References DoStop, mutUnused.
void mutaborGUI::MutFrame::CmPanic(wxCommandEvent &WXUNUSED(event))
References DEFAULT_PANIC, mutaborGUI::LogicOn, mutabor::Panic.
void mutaborGUI::MutFrame::CeExecute(wxUpdateUIEvent &event)
References mutaborGUI::LogicOn.
void mutaborGUI::MutFrame::CeActivate(wxUpdateUIEvent &event)
References client, mutaborGUI::LogicOn.
void mutaborGUI::MutFrame::CeStop(wxUpdateUIEvent &event)
References mutaborGUI::LogicOn.
void mutaborGUI::MutFrame::CmRoutes(wxCommandEvent &event)
References _, auimanager, client, DEBUGLOG, ICON, mutaborGUI::LogicOn, UpdateBoxMenu, WK_ROUTE.
Referenced by IMPLEMENT_APP.
void mutaborGUI::MutFrame::CmToggleKey(wxCommandEvent &WXUNUSED(event))
References ToggleTextBox, WK_KEY.
void mutaborGUI::MutFrame::CmToggleTS(wxCommandEvent &WXUNUSED(event))
References ToggleTextBox, WK_TS.
void mutaborGUI::MutFrame::CmToggleAct(wxCommandEvent &WXUNUSED(event))
References ToggleTextBox, WK_ACT.
void mutaborGUI::MutFrame::CmToggleOWM(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::LogicOn, mutaborGUI::OWM, STUBC.
void mutaborGUI::MutFrame::CmToggleCAW(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::CAW, mutaborGUI::LogicOn, STUBC.
void mutaborGUI::MutFrame::CeToggleKey(wxUpdateUIEvent &event)
References DEBUGLOG, mutabor::BoxClass::get_routefile_id, mutaborGUI::GetCurrentBox, mutaborGUI::ToGUIBase, mutaborGUI::BoxData::WantKeyWindow.
void mutaborGUI::MutFrame::CeToggleTS(wxUpdateUIEvent &event)
References mutaborGUI::GetCurrentBox, mutaborGUI::ToGUIBase, mutaborGUI::BoxData::WantTonesystemWindow.
void mutaborGUI::MutFrame::CeToggleAct(wxUpdateUIEvent &event)
References mutaborGUI::GetCurrentBox, mutaborGUI::ToGUIBase, mutaborGUI::BoxData::WantActionsWindow.
void mutaborGUI::MutFrame::CeToggleOWM(wxUpdateUIEvent &event)
References mutaborGUI::OWM.
void mutaborGUI::MutFrame::CeToggleCAW(wxUpdateUIEvent &event)
References mutaborGUI::CAW.
void mutaborGUI::MutFrame::CmInDevStop(wxCommandEvent &WXUNUSED(event))
References repaint_route, StopInDev.
void mutaborGUI::MutFrame::CmInDevPlay(wxCommandEvent &WXUNUSED(event))
References _, mutaborGUI::StatusBar::AllSetPlaystate, CmDoActivate, mutabor::CurrentTime, mutabor::CurrentTimer::isRealtime, mutaborGUI::LogicOn, mutaborGUI::StatusBar::Play, repaint_route, TRACEC.
void mutaborGUI::MutFrame::CmInDevPause(wxCommandEvent &WXUNUSED(event))
References mutaborGUI::StatusBar::AllSetPlaystate, mutabor::DevicePlay, mutaborGUI::StatusBar::Pause, repaint_route.
void mutaborGUI::MutFrame::StopInDev()
References mutaborGUI::StatusBar::AllSetPlaystate, mutabor::DevicePause, mutabor::DevicePlay, mutaborGUI::StatusBar::Stop.
Referenced by CmInDevStop, DoStop.
void mutaborGUI::MutFrame::CeInDevStop(wxUpdateUIEvent &event)
References mutabor::DevicePause, mutabor::DevicePlay, mutabor::DTMidiFile.
void mutaborGUI::MutFrame::CeInDevPlay(wxUpdateUIEvent &event)
References DEBUGLOG, mutabor::DevicePause, mutabor::DeviceStop, mutabor::DTMidiFile, mutaborGUI::LogicOn.
void mutaborGUI::MutFrame::CeInDevPause(wxUpdateUIEvent &event)
References mutabor::DevicePlay, mutabor::DTMidiFile.
void mutaborGUI::MutFrame::CmSetTitle(wxCommandEvent &event)
References _, APPNAME.
void mutaborGUI::MutFrame::UpdateUI(wxCommandEvent &WXUNUSED(event))
Update GUI when the mutabor kernel or file players have acted.
void mutaborGUI::MutFrame::OnEraseBackground(wxEraseEvent &event)
References client.
void mutaborGUI::MutFrame::OnSize(wxSizeEvent &event)
wxAuiDockArt * mutaborGUI::MutFrame::GetDockArt()
References auimanager.
void mutaborGUI::MutFrame::SaveState()
Referenced by OnCloseWindow.
void mutaborGUI::MutFrame::RestoreState()
Referenced by IMPLEMENT_APP.
void mutaborGUI::MutFrame::LogicWinOpen(mutabor::Box box)
References _, auimanager, client, mutaborGUI::MutLogicWnd::MakeTitle, UpdateBoxMenu, WK_ROUTE.
void mutaborGUI::MutFrame::ToggleTextBox(WinKind kind)
References _, ActiveWindow, CloseClientWindow, DEBUGLOG, mutaborGUI::BoxData::GetActionsWindow, mutaborGUI::GetCurrentBox, mutaborGUI::BoxData::GetKeyWindow, mutaborGUI::BoxData::GetTonesystemWindow, mutaborGUI::IsOpen, mutaborGUI::LogicOn, mutASSERT, TextBoxOpen, mutaborGUI::BoxData::ToggleActionsWindow, mutaborGUI::BoxData::ToggleKeyWindow, ToggleTextBox, mutaborGUI::BoxData::ToggleTonesystemWindow, mutaborGUI::ToGUIBase, UNREACHABLEC, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by CmToggleAct, CmToggleKey, CmToggleTS, ToggleTextBox.
void mutaborGUI::MutFrame::DoBoxWindowsOpen(mutabor::Box box, bool update=true)
References mutUnused, STUBC, mutaborGUI::ToGUIBase.
Referenced by BoxWindowsOpen.
void mutaborGUI::MutFrame::DoBoxWindowsClose(mutabor::Box box, bool update=true)
References auimanager, CloseClientWindow, mutaborGUI::BoxData::GetActionsWindow, mutaborGUI::BoxData::GetKeyWindow, mutaborGUI::BoxData::GetLogicWindow, mutaborGUI::BoxData::GetTonesystemWindow, mutaborGUI::ToGUIBase, UNREACHABLEC, UpdateBoxMenu, WK_ROUTE.
Referenced by BoxWindowsClose.
void mutaborGUI::MutFrame::TextBoxOpen(WinKind kind, mutabor::Box &box, bool update_auimanager=true)
References _, mutaborGUI::asTS, auimanager, mutaborGUI::CAW, client, DEBUGLOG, MutTextBox::GetAllActions, MutTextBox::GetBoxActions, MutTextBox::GetKeys, MutTextBox::GetKind, MutTextBox::GetToneSystem, mutaborGUI::MutChild::MakeTitle, mutASSERT, mutabor::NoBox, mutabor::str, UNREACHABLEC, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by mutaborGUI::BoxData::DoOpen, ToggleTextBox.
void mutaborGUI::MutFrame::CmSelectBox()
void mutaborGUI::MutFrame::CmCloseChild()
References mutaborGUI::ChildToClose.
void mutaborGUI::MutFrame::CloseAll(WinKind kind=WK_NULL)
bool mutaborGUI::MutFrame::Destroy()
References boxCommandIds.
Referenced by OnCloseWindow.
wxRect mutaborGUI::MutFrame::DetermineFrameSize()
References TRACEC.
Referenced by MutFrame.
bool mutaborGUI::MutFrame::HasClient()
retrun true if we have already a client
References client.
Referenced by mutaborGUI::MutApp::MustOpenFrame.
void mutaborGUI::MutFrame::UpdateBoxMenu()
References _, boxCommandIds, ClearMenuItem, mutaborGUI::CM_ACTIVATE, mutaborGUI::CM_BOX, mutaborGUI::CM_SELECTBOX, DEBUGLOG, mutabor::BoxClass::GetBoxList, mutaborGUI::BoxData::GetCurrentBox, mutaborGUI::BoxData::GetLogicWindow, mutASSERT, RaiseLogic, mutaborGUI::ToGUIBase.
Referenced by CmDoActivate, CmRoutes, DoBoxWindowsClose, mutaborGUI::BoxData::DoClose, mutaborGUI::BoxData::DoOpen, LogicWinOpen, mutaborGUI::BoxData::set_routefile_id.
bool mutaborGUI::MutFrame::RaiseTheFrame()
References ActiveWindow.
Referenced by RaiseLogic.
void mutaborGUI::MutFrame::SetFileMenu(wxMenu *f)
References filemenu.
Referenced by IMPLEMENT_APP.
void mutaborGUI::MutFrame::SetEditMenu(wxMenu *e)
References editmenu.
void mutaborGUI::MutFrame::CloseClientWindow(wxWindow *w, bool update=true)
References auimanager, DEBUGLOG, mutASSERT.
Referenced by DoBoxWindowsClose, mutaborGUI::BoxData::DoClose, ToggleTextBox.
static void mutaborGUI::MutFrame::BoxWindowsOpen(mutabor::Box box, bool update=true)
References ActiveWindow, DoBoxWindowsOpen.
Referenced by CmDoActivate.
static void mutaborGUI::MutFrame::BoxWindowsClose(mutabor::Box box, bool update=true)
References ActiveWindow, DoBoxWindowsClose.
static void mutaborGUI::MutFrame::repaint_route()
References client, WK_ROUTE.
Referenced by CmDoActivate, CmInDevPause, CmInDevPlay, CmInDevStop, DoStop.
static wxDocument* mutaborGUI::MutFrame::GetActiveDocument()
References ActiveWindow.
static MutFrame* mutaborGUI::MutFrame::GetActiveWindow()
References ActiveWindow.
Referenced by BEGIN_EVENT_TABLE, mutaborGUI::BoxData::set_routefile_id.
virtual wxStatusBar* mutaborGUI::MutFrame::OnCreateStatusBar(int number, long style, wxWindowID id, const wxString &name)
References mutaborGUI::StatusBar::Hide, mutaborGUI::LogicOn, mutaborGUI::StatusBar::SetActive, mutaborGUI::StatusBar::SetPlaystate.