mut.cc
YYBISON
YYBISON_VERSION
YYSKELETON_NAME
YYPURE
YYPUSH
YYPULL
_
MAX_IDENTIFIER_LEN
Referenced by yylex.
FEHLERZEILE
Referenced by switch.
YYERROR_VERBOSE
YYMALLOC
YYFREE
YYMAXLIMIT
YY_NULL
Referenced by yysyntax_error.
YYERROR_VERBOSE
YY_YY__MUTABOR_GIT_SRC_KERNEL_MUT_HH_INCLUDED
YYDEBUG
YYTOKENTYPE
MUTABOR_TOKEN_IDENTIFIER
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_F_NUMBER
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_INTEGER
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_INTERVAL
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_TONE
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_TONESYSTEM
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_RETUNING
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_HARMONY
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_LOGIC
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_MIDICHANNEL
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_KEY
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_FORM
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_ROOT
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_MIDI_IN
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_MIDI_OUT
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_HARMONY_ANALYSIS
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_CALLS
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while.
MUTABOR_TOKEN_ELSE
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_PARAMETER
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded.
MUTABOR_TOKEN_ANCHOR
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_DISTANCE
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while, yylex.
MUTABOR_TOKEN_ENDOFFILE
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded.
MUTABOR_TOKEN_ERROR
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, yylex.
MUTABOR_TOKEN_SPACES
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while.
MUTABOR_TOKEN_COMMENT
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while.
MUTABOR_TOKEN_COMMENT_START
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while.
MUTABOR_TOKEN_COMMENT_END
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while.
MUTABOR_TOKEN_OTHER
Referenced by mutaborGUI::MutSTCLexer::OnStyleNeeded, while.
YYSTYPE_IS_TRIVIAL
yystype
YYSTYPE_IS_DECLARED
yyltype
YYLTYPE_IS_DECLARED
YYLTYPE_IS_TRIVIAL
YYLEX_PARAM
YYSIZE_T
Referenced by if, yysyntax_error, yytnamerr.
YYSIZE_MAXIMUM
YY_
Referenced by if, yysyntax_error.
__attribute__
YYUSE
YYID
YYSTACK_ALLOC
Referenced by if.
YYSTACK_FREE
Referenced by if.
YYSTACK_ALLOC_MAXIMUM
Referenced by yysyntax_error.
YYSTACK_GAP_MAXIMUM
YYSTACK_BYTES
Referenced by if.
YYCOPY_NEEDED
YYSTACK_RELOCATE
Referenced by if.
YYCOPY
YYFINAL
YYLAST
Referenced by for, yysyntax_error.
YYNTOKENS
Referenced by yysyntax_error.
YYNNTS
YYNRULES
YYNSTATES
YYUNDEFTOK
YYMAXUTOK
YYTRANSLATE
YYPACT_NINF
YYTABLE_NINF
yypact_value_is_default
Referenced by for, yysyntax_error.
yytable_value_is_error
Referenced by if, yysyntax_error.
yyerrok
yyclearin
YYEMPTY
Referenced by if, yysyntax_error.
YYEOF
Referenced by if.
YYACCEPT
YYABORT
Referenced by for, if.
YYERROR
YYFAIL
YYRECOVERING
YYBACKUP
YYTERROR
Referenced by for, yysyntax_error.
YYERRCODE
YYLLOC_DEFAULT
YYRHSLOC
YY_LOCATION_PRINT
YYLEX
Referenced by if.
YYDPRINTF
Referenced by if.
YY_SYMBOL_PRINT
YY_STACK_PRINT
Referenced by for.
YY_REDUCE_PRINT
YYINITDEPTH
YYMAXDEPTH
Referenced by if.
YYCASE_
Referenced by yysyntax_error.
YY_INITIAL_VALUE
YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
YY_IGNORE_MAYBE_UNINITIALIZED_END
YYPOPSTACK
Referenced by for, while.
YYSYNTAX_ERROR
Referenced by if.
yytokentype
typedef union YYSTYPE YYSTYPE
typedef struct YYLTYPE YYLTYPE
typedef unsigned char yytype_uint8
typedef short int yytype_int8
typedef unsigned short int yytype_uint16
typedef short int yytype_int16
const yytype_uint8 yytranslate[][]
const char* const yytname[][]
const yytype_uint8 yyr1[][]
const yytype_uint8 yyr2[][]
const yytype_uint8 yydefact[][]
const yytype_int16 yydefgoto[][]
const yytype_int16 yypact[][]
const yytype_int16 yypgoto[][]
const yytype_int16 yytable[][]
const yytype_int16 yycheck[][]
const yytype_uint8 yystos[][]
yylocp FILE* yyo
YYLTYPE const* const yylocp
int end_col
return res
Referenced by MisFile::Load, MisFile::Save.
int yylen
Referenced by yyparse.
const char* yysrc
const char* yys
return yyd
int yytype
YYSTYPE* yyvaluep
YYLTYPE* yylocationp
yyexhaustedlab box
Referenced by mutaborGUI::GUIRouteBase::Add, mutaborGUI::RoutePanel::AddBox, mutaborGUI::BoxDlg::AddButtonPressed, mutaborGUI::MutBoxShape::AddChannel, mutaborGUI::BEGIN_EVENT_TABLE, mutaborGUI::MutFrame::CeToggleAct, mutaborGUI::MutFrame::CeToggleKey, mutaborGUI::MutFrame::CeToggleTS, mutaborGUI::MutFrame::CloseAll, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutEditFile::Compile, mutabor::TRouteClass< I, O, B >::Create, mutaborGUI::MutRouteWnd::createBoxes, mutaborGUI::MutChild::deleteFromWinAttrs, DeleteKey, mutabor::TRouteClass< I, O, B >::Destroy, mutaborGUI::disconnect, mutabor::BoxFactory::DoCreateBox, error_callback, mutaborGUI::GUIfiedRoute< T >::GUIfiedRoute, mutaborGUI::IMPLEMENT_DYNAMIC_CLASS, mutaborGUI::NewMutBoxShape::InitializeDialog, mutaborGUI::MutBoxChannelShape::InitializeRoute, mutaborGUI::MutRouteWnd::InitShapes, KeyboardIn, compat30::LoadRoutes, mutaborGUI::MutChild::OnActivate, mutaborGUI::MutChild::OnChar, mutaborGUI::MutRouteWnd::OnDraw, mutaborGUI::MutChild::OnGetFocus, mutabor::BoxClass::Panic, mutabor::InputGis::Proceed, mutabor::CommonMidiInput< D >::ProceedRoute, mutaborGUI::MutFrame::RaiseLogic, mutaborGUI::MutBoxChannelShape::ReadPanel, mutabor::BoxClass::Reset, mutabor::BoxClass::set_routefile_id, boxTest::testAddKey, InputMidiFileTest::testBatchPlay1, InputMidiFileTest::testBug019010, InputMidiFileTest::testBug019010_2, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, RouteTest::testDestroyAll, boxTest::testFindKeyByKey, mutaborGUI::MutFrame::ToggleTextBox, mutabor::BoxClass::~BoxClass.
YYSTYPE yyval_default
YYLTYPE yyloc_default
YYLTYPE yylloc
Referenced by yyparse.
yynerrs
Referenced by if, yyparse.
else yystate
Referenced by for, yyparse.
yyerrstatus
Referenced by yyparse.
yytype_int16 yyssa[YYINITDEPTH][YYINITDEPTH]
Referenced by yyparse.
yytype_int16* yyss
Referenced by if, yyparse.
yyssp
Referenced by for, yyparse, yysyntax_error.
YYSTYPE yyvsa[YYINITDEPTH][YYINITDEPTH]
Referenced by yyparse.
YYSTYPE* yyvs
Referenced by if, yyparse.
YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN * yyvsp
Referenced by yyparse.
YYLTYPE yylsa[YYINITDEPTH][YYINITDEPTH]
Referenced by yyparse.
YYLTYPE* yyls
Referenced by if, yyparse.
* yylsp
Referenced by for, yyparse.
YY_IGNORE_MAYBE_UNINITIALIZED_END yyerror_range[3]
yystacksize
yyn
Referenced by for, if, yyparse, yysyntax_error, yytnamerr.
yyresult
int yytoken
Referenced by yysyntax_error.
yyval
Referenced by yyparse.
YYLTYPE yyloc
char yymsgbuf[128][128]
Referenced by if.
char* yymsg
Referenced by if, yysyntax_error.
YYSIZE_T yymsg_alloc
yychar
Referenced by yyparse.
goto yysetstate
yynewstate __pad0__
yysetstate __pad1__
goto yybackup
yybackup __pad2__
else
goto yynewstate
Referenced by yyparse.
yydefault __pad3__
goto yyreduce
Referenced by if, yyparse.
yyreduce __pad4__
yyerrlab __pad5__
goto yyerrlab1
yyerrorlab __pad6__
yyerrlab1 __pad7__
yyacceptlab __pad8__
goto yyreturn
yyabortlab __pad9__
yyexhaustedlab __pad10__
yyreturn __pad11__
int yyparse()
Referenced by mutabor_programm_einlesen.
int yylex(YYSTYPE *lvalp, YYLTYPE *llocp, mutabor_box_type *box)
Noch zu erledigencheck whether this function is necessary for any system but windows
References _, mutabor_scanner_data::anzahl_eingelesene_zeichen, compiler_error, mutabor_scanner_data::data, DEBUGLOG2, YYSTYPE::f_value, YYLTYPE::first_line, YYSTYPE::identifier, YYSTYPE::integer, LINE_DRAW_QUANTUM, MAX_IDENTIFIER_LEN, mutabor_error_message, MUTABOR_TOKEN_ANCHOR, MUTABOR_TOKEN_DISTANCE, MUTABOR_TOKEN_ELSE, MUTABOR_TOKEN_ERROR, MUTABOR_TOKEN_F_NUMBER, MUTABOR_TOKEN_FORM, MUTABOR_TOKEN_HARMONY, MUTABOR_TOKEN_HARMONY_ANALYSIS, MUTABOR_TOKEN_IDENTIFIER, MUTABOR_TOKEN_INTEGER, MUTABOR_TOKEN_INTERVAL, MUTABOR_TOKEN_KEY, MUTABOR_TOKEN_LOGIC, MUTABOR_TOKEN_MIDI_IN, MUTABOR_TOKEN_MIDI_OUT, MUTABOR_TOKEN_MIDICHANNEL, MUTABOR_TOKEN_RETUNING, MUTABOR_TOKEN_ROOT, MUTABOR_TOKEN_TONE, MUTABOR_TOKEN_TONESYSTEM, mutASSERT, mutabor_scanner_data::pos, mutabor_box_type::scanner, show_line_number, xfree, xmalloc, xrealloc.
void yyerror(YYLTYPE *locp, mutabor_box_type *box, const char *err)
References _, compiler_error, YYLTYPE::first_line, mutabor_error_message.
Referenced by if, yyparse.
__attribute__((__unused__)) static unsigned yy_location_print_(yyo
if(0<=yylocp->first_line)
References YYLTYPE::first_column, YYLTYPE::first_line.
Referenced by EndTag, generate_argument_list.
static YYSIZE_T yystrlen(yystr) const char *yystr
Referenced by yysyntax_error, yytnamerr.
for(yylen=0;yystr[yylen];yylen++) continue
Referenced by berechne_toene_absolut, check_konsistenz, expand_pattern, update_pattern.
static char* yystpcpy(yydest, yysrc) char *yydest
Referenced by yytnamerr.
while((*yyd++=*yys++)!= '\0') continue
static YYSIZE_T yytnamerr(char *yyres, const char *yystr)
References yyn, YYSIZE_T, yystpcpy, yystrlen.
Referenced by yysyntax_error.
static int yysyntax_error(YYSIZE_T *yymsg_alloc, char **yymsg, yytype_int16 *yyssp, int yytoken)
References YY_, YY_NULL, YYCASE_, YYEMPTY, YYLAST, yymsg, yyn, YYNTOKENS, yypact_value_is_default, YYSIZE_T, yyssp, YYSTACK_ALLOC_MAXIMUM, yystrlen, yytable_value_is_error, YYTERROR, yytnamerr, yytoken.
static void yydestruct(yymsg, yytype, yyvaluep, yylocationp, box) const char *yymsg
Referenced by for, if, while.
YYUSE(yylocationp)
YYUSE(box)
if(!yymsg) yymsg
References YY_, yyerror, yymsg, yymsgbuf, yynerrs, YYSTACK_ALLOC, YYSTACK_FREE, YYSYNTAX_ERROR.
YY_SYMBOL_PRINT(yymsg, yytype, yyvaluep, yylocationp)
YYUSE(yytype)
int yyparse(box) mutabor_box_type *box
YYSTYPE yylval YY_INITIAL_VALUE(yyval_default)
YYDPRINTF((stderr,"Starting parse\n"))
if(yyss+yystacksize-1<=yyssp)
References YY_, YYABORT, YYDPRINTF, yyls, yyalloc::yyls_alloc, YYMAXDEPTH, YYSIZE_T, yyss, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yyvs, yyalloc::yyvs_alloc.
YYDPRINTF((stderr,"Entering state %d\n", yystate))
if(yystate==YYFINAL) YYACCEPT
if(yypact_value_is_default(yyn)) goto yydefault
if(yychar==YYEMPTY)
References YYDPRINTF, YYLEX.
if(yychar<=YYEOF)
References YYDPRINTF, YYEOF.
YY_SYMBOL_PRINT("Next token is", yytoken,&yylval,&yylloc)
if(yyn< 0||YYLAST< yyn||yycheck[yyn]!=yytoken) goto yydefault
if(yyn<=0)
References yyn, yyreduce, yytable_value_is_error.
if(yyerrstatus) yyerrstatus--
References YYABORT, yydestruct, YYEMPTY, YYEOF, yylval.
YY_SYMBOL_PRINT("Shifting", yytoken,&yylval,&yylloc)
if(yyn==0) goto yyerrlab
YYLLOC_DEFAULT(yyloc,(yylsp-yylen), yylen)
YY_REDUCE_PRINT(yyn)
switch(yyn)
References _, YYSTYPE::arguments, compiler_error, compiler_warning, eintrage_parameterliste_in_umstimmung, enumerate_parameters, YYSTYPE::f_value, FEHLERZEILE, get_ausloeser_default, get_ausloeser_harmonie, get_ausloeser_harmonie_form, get_ausloeser_midi_in, get_ausloeser_taste, get_harmoniebezeichner, get_instrument_dekl, get_new_aktion_aufruf_element, get_new_aktion_harmony_analysis, get_new_aktion_midi_out_element, get_new_anchor_in_argument_list, get_new_anweisung, get_new_distance_in_argument_list, get_new_faktor_anteil, get_new_harmonie, get_new_integer_in_integersequenz, get_new_intervall, get_new_intervall_komplex, get_new_logik, get_new_name_in_argument_list, get_new_name_in_parameterlist, get_new_number_in_argument_list, get_new_taste, get_new_ton_absolut, get_new_ton_in_tonsystem, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_new_umstimm_expression, get_new_umstimm_expression_negative, get_new_umstimm_expression_positive, get_new_umstimmung, get_umstimmung_breite_abs, get_umstimmung_breite_rel, get_umstimmung_midi_out, get_umstimmung_taste_abs, get_umstimmung_taste_rel, get_umstimmung_tonhoehe_veraendert, get_umstimmung_umstimm_case, get_umstimmung_umstimmungs_bund, get_umstimmung_wiederholung_abs, get_umstimmung_wiederholung_abs_negative, get_umstimmung_wiederholung_rel_negative, get_umstimmung_wiederholung_rel_positive, get_umstimmungs_case_default_element, get_umstimmungs_case_zahl_element, init_aktions_liste, init_anweisungs_liste, init_ausloeser, init_integersequenz, init_komplex_ton_list, init_tastenliste, init_ton_liste, init_umstimm_expression_list, init_umstimmung, init_umstimmungs_case_liste, YYSTYPE::integer, mutabor_error_message, MUTABOR_NO_KEY, mutT, YYSTYPE::parameters, vervollstaendige_logik.
YY_SYMBOL_PRINT("-> $$ =", yyr1[yyn],&yyval,&yyloc)
YYPOPSTACK(yylen)
YY_STACK_PRINT(yyss, yyssp)
if(0<=yystate &&yystate<=YYLAST &&yycheck[yystate]==*yyssp) yystate
for(;;)
References YY_STACK_PRINT, YYABORT, yydestruct, YYLAST, yylsp, yyn, yypact_value_is_default, YYPOPSTACK, yyssp, yystate, YYTERROR.
YYLLOC_DEFAULT(yyloc, yyerror_range, 2)
YY_SYMBOL_PRINT("Shifting", yystos[yyn], yyvsp, yylsp)
yyexhaustedlab YY_("memory exhausted"))
yydestruct("Cleanup: discarding lookahead", yytoken,&yylval,&yylloc, box)
while(yyssp!=yyss)
References yydestruct, YYPOPSTACK.
if(yyss!=yyssa) YYSTACK_FREE(yyss)
if(yymsg!=yymsgbuf) YYSTACK_FREE(yymsg)
return YYID(yyresult)
void init_yylex()
Referenced by GMutCompile.