GIS.h
MU32_ROUTING_GMN_GIS_H
MU32_ROUTING_GMN_GIS_H_PRECOMPILED
FOR_MUTWIN
CHECKDUP
Referenced by GisNote::GisNote, GisParaStr::GisParaStr, GisTag::GisTag, GisToken::GisToken, GisWriteHead::GisWriteHead.
NTAGS
Referenced by GetTagId.
NTAGSHORTS
Referenced by GetTagId.
TTintens
Referenced by GisReadArtHead::Read.
TTslur
TTtempo
Referenced by GisReadArtHead::Read.
TTinstr
Referenced by GisReadArtHead::Read.
TTtie
Referenced by ChordNote::CheckCloseTie.
TTstacc
Referenced by GisReadArtHead::Read.
TTaccent
Referenced by GisReadArtHead::Read.
TTten
Referenced by GisReadArtHead::Read.
TTkey
Referenced by GisWriteHead::ProceedGis.
TToct
Referenced by GisWriteHead::ProceedGis, GisReadArtHead::Read.
TTalter
Referenced by ChordNote::MutNoteOn, mutabor::InputGis::Proceed, GisReadArtHead::Read.
TTmutabor
Referenced by mutabor::InputGis::Proceed.
GMN_NO_KEY
Referenced by ChordNote::ChordNote, ChordNote::Cmp, GisNote::GisNote, ChordNote::MutNoteOn.
GisType
const char* Tags[NTAGS][NTAGS]
Referenced by GetTagId, GisTag::GisTag.
const char* TagShorts[NTAGSHORTS][NTAGSHORTS]
Referenced by GetTagId, GisTag::GisTag.
int GetTagId(const std::string &name, std::string &registered)
References DEBUGLOG2, NTAGS, NTAGSHORTS, Tags, TagShorts.
Referenced by GisTag::GisTag.
GisToken * CopyPara(GisToken *para)
References GisToken::Copy, GisToken::Next.
Referenced by GisTag::Copy, GisTagBegin::Copy.
GisType GetGisType(GisToken *token)
References GTNull, GisToken::Type.
Referenced by CloseAllSubs, GetMidiInstrument, GetReal, GetTheSpeedFactor, mutabor::MutaborTag, ChordNote::MutNoteOff, mutabor::InputGis::Proceed, MisFile::WriteGis.
GisToken * GisParse(const std::string FileName)
References Current, DEBUGLOG2, GspParse, LastOpenBracket, LastOpenRange, LastPara, Para, Root, TagMode, TagName, TagSep, UnRavel.
Referenced by GetInFile, main, mutabor::InputGis::Open.
int StartSep()
References Current, DEBUGLOG2.
Referenced by GspParse.
int BeginSegment()
References BuildTag, GisSegment::Contents, Current, DEBUGLOG2, LastOpenBracket, TagMode.
Referenced by DoParse.
int EndSegment()
References BuildTag, Current, DEBUGLOG2, LastOpenBracket, GisToken::Next, TagMode.
Referenced by DoParse.
int BeginSequenz()
References BuildTag, GisSequenz::Contents, Current, DEBUGLOG2, LastOpenBracket, TagMode.
Referenced by DoParse.
int EndSequenz()
References BuildTag, Current, DEBUGLOG2, LastOpenBracket, GisToken::Next, Sep, TagMode.
Referenced by DoParse.
int BeginParameter()
References AddStr, DEBUGLOG2, TagSep.
Referenced by ReadTag.
int EndParameter()
References AddStr, DEBUGLOG2, LastPara, Para, GisToken::Sep, TagSep.
Referenced by DoParse, ReadTag.
int BeginRange()
References AddStr, Clear, Current, DEBUGLOG2, GisTagBegin::End, LastOpenRange, LastPara, GisToken::Next, Para, GisToken::Sep, Tag, TagMode, TagName, TagSep.
Referenced by DoParse.
int EndRange()
References GisTagEnd::Begin, BuildTag, Current, DEBUGLOG2, GisTagBegin::End, LastOpenRange, GisToken::Next, Tag, TagMode.
Referenced by DoParse.
int NextSequenz()
References BuildTag, DEBUGLOG2, TagMode.
Referenced by DoParse.
int Tag(const std::string &tagName)
References BuildTag, DEBUGLOG2, Sep, TagMode, TagName, TagSep.
Referenced by BeginRange, BuildTag, mutaborGUI::MutLogicWnd::CmMutTag, DoParse, EndRange, ReadTag.
int TagParaInt(long i)
References DEBUGLOG2, LastPara, GisToken::Next, Para.
Referenced by ReadParaNumber.
int TagParaReal(double x)
References DEBUGLOG2, LastPara, GisToken::Next, Para.
Referenced by ReadParaNumber.
int TagParaStr(const std::string &s)
References DEBUGLOG2, LastPara, GisToken::Next, Para.
Referenced by ReadParaStr.
int Comma()
References BuildTag, Current, DEBUGLOG2, TagMode.
Referenced by DoParse, GisWriteHead::ReadyForBoss.
int Note(const std::string &name, const std::string &accedentials, int octave, const mutabor::frac &duration)
References BuildTag, Current, DEBUGLOG2, GisToken::Next, octave, mutabor::str, TagMode.
Referenced by ChordNote::MutNoteOn, ReadNote.
std::string GISPrettyPrint(std::string s)