runtime
jmp_buf weiter_gehts_nach_compilerfehler
struct keyboard_ereignis* last
Referenced by mutabor::ChannelData::get_next_changed_controller, mutabor_create_key_in_box, boxTest::testAddKey, boxTest::testDeleteKey.
jmp_buf weiter_gehts_nach_compilerfehler
Referenced by mutabor::BoxClass::Compile, GMutCompile.
double mutabor_convert_pitch_to_factor(double interval)
Convert an interval represented as MIDI based double value to a frequency factor.
The microtonal part is retained in the double return value. interval interval in a midi based double. A half tone is represented as 1.00, and an octave as 12.00. frequency factor
Referenced by mutabor_convert_pitch_to_frequency.
double mutabor_convert_factor_to_pitch(double interval)
Convert an interval from factor representation to a pitch based double according to MIDI pitch numbers.
The microtonal part can be given in the double value. interval factor to be converted a double value that represents the interval. a semitone is represented as 1.00, and an octave as 12.00
Referenced by expand_tonliste, expandiere_tonsystem, expandiere_umstimmung, mutabor_convert_frequency_to_pitch.
double mutabor_convert_pitch_to_frequency(double tone)
Convert an interval represented as MIDI based double value to a frequency.
The microtonal part is retained in the double return value. tone pitch in a midi based double. A half tone is represented as 1.00, and an octave as 12.00. frequency factor
References mutabor_convert_pitch_to_factor.
Referenced by MutTextBox::GetKeys, MutTextBox::GetToneSystem.
double mutabor_convert_frequency_to_pitch(double tone)
Convert a tone from frequency representation to a pitch based double according to MIDI pitch numbers.
The microtonal part can be given in the double value. tone frequency to be converted a double value that represents the pitch. a semitone is represented as 1.00, and an octave as 12.00
References mutabor_convert_factor_to_pitch.
Referenced by expand_tonliste, expandiere_tonsystem.
bool TSChanged(mutabor_box_type *box)
References TSYS::breite, mutabor_box_type::last_tonesystem, mutabor_box_type::tonesystem.
void GetInDevicesMode(enum MutaborModeType *mode)
References mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList.
char GetChannels(mutabor_box_type *box, char start, int &base, int &from, int &to, int &thru)
References mutabor_box_type::file, mutabor_logic_parsed::lauf_instrument, mutabor_logic_parsed::list_of_config_instrumente, keyboard_ereignis::next.
Referenced by mutaborGUI::MutBoxShape::AddChannel.
void SetChannels(mutabor_box_type *box, int base, int from, int to, int thru)
References mutabor_box_type::file, get_instrument_dekl, mutabor_logic_parsed::list_of_config_instrumente.
bool GetELine(const wxString &p, size_t &i, wxString &s)
DevType Str2DT(const wxString &type)
Referenced by compat30::LoadRoutes.
bool GetLine(char **p, char *s)
void GetTimerData(UINT &min, UINT &max)
MU32_MIDIKERN_H
MU32_MIDIKERN_H_PRECOMPILED
DRUMCHANNEL
Referenced by mutabor::CommonMidiOutput< T, D >::do_NoteOff, mutabor::CommonMidiOutput< T, D >::EmergencyFindChannel, mutabor::ChannelFilter::operator().
GETLINE
MU32_RUNTIME_H
MU32_RUNTIME_H_PRECOMPILED
UINT