mutaborGUI::InputFilterPanel
mutaborGUI::InputFilterPanel::InputFilterPanel(wxWindow *parent)
wxChoicebook* mutaborGUI::InputFilterPanel::GetInputDeviceBook()
References InputFilterPanelBase::inputDevice.
Referenced by mutaborGUI::MutBoxChannelShape::InitializeInputFilter.
void mutaborGUI::InputFilterPanel::AddPage(wxPanel *panel, const wxString &label, bool selected, MutInputDeviceShape *shape)
References TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::MutBoxChannelShape::InitializeInputFilter.
wxWindow * mutaborGUI::InputFilterPanel::GetCurrentDevicePage()
MutInputDeviceShape * mutaborGUI::InputFilterPanel::GetCurrentSelection()
References mutaborGUI::InputFilterPanel::InputShapeData::GetDevice, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::MutBoxChannelShape::ReadPanel.