mutaborGUI::MutChild
mutaborGUI::MutChild::MutChild(WinKind winkind, mutabor::Box b, wxWindow *parent=NULL, wxWindowID id=-1, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
mutaborGUI::MutChild::~MutChild()
References deleteFromWinAttrs, mutASSERT, TRACEC, MutTextBox::winKind, WK_KEY, WK_NULL.
virtual wxString mutaborGUI::MutChild::MakeTitle()
References MutTextBox::MakeTitle.
Referenced by BoxChanged, mutaborGUI::MutFrame::TextBoxOpen.
void mutaborGUI::MutChild::BoxChanged()
References MutTextBox::box, mutaborGUI::BoxData::GetBackgroundColour, mutaborGUI::BoxData::GetTextColour, MakeTitle, mutASSERT, mutaborGUI::ToGUIBase.
void mutaborGUI::MutChild::OnActivate(wxActivateEvent &event)
References MutTextBox::box, mutASSERT, mutUnused, mutaborGUI::SetCurrentBox, TRACEC, MutTextBox::winKind, WK_KEY, WK_NULL.
void mutaborGUI::MutChild::deleteFromWinAttrs(bool setWant=true)
References _, MutTextBox::box, DEBUGLOG, mutASSERT, mutaborGUI::BoxData::SetActionsWindow, mutaborGUI::BoxData::SetKeyWindow, mutaborGUI::BoxData::SetTonesystemWindow, mutaborGUI::ToGUIBase, UNREACHABLEC, mutaborGUI::BoxData::WantActionsWindow, mutaborGUI::BoxData::WantKeyWindow, mutaborGUI::BoxData::WantTonesystemWindow, MutTextBox::winKind, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by OnAuiClose, OnClose, ~MutChild.
void mutaborGUI::MutChild::OnClose(wxCloseEvent &event)
References deleteFromWinAttrs, mutASSERT, MutTextBox::OnClose, TRACEC, MutTextBox::winKind, WK_KEY, WK_NULL.
void mutaborGUI::MutChild::OnAuiClose(wxAuiManagerEvent &event)
References deleteFromWinAttrs, mutASSERT, mutUnused, TRACEC, MutTextBox::winKind, WK_KEY, WK_NULL.
void mutaborGUI::MutChild::GetClientSize(int *width, int *height)
References mutASSERT, MutTextBox::winKind, WK_KEY, WK_NULL.
void mutaborGUI::MutChild::SetClientSize(int width, int height)
References mutASSERT, MutTextBox::winKind, WK_KEY, WK_NULL.
void mutaborGUI::MutChild::SetClientSize(const wxSize &size)
References mutASSERT, MutTextBox::winKind, WK_KEY, WK_NULL.
void mutaborGUI::MutChild::ClientToScreen(int *x, int *y)
References mutASSERT, MutTextBox::winKind, WK_KEY, WK_NULL.
wxPoint mutaborGUI::MutChild::ClientToScreen(const wxPoint &pt) const
References mutASSERT, MutTextBox::winKind, WK_KEY, WK_NULL.
void mutaborGUI::MutChild::OnChar(wxKeyEvent &event)
References MutTextBox::box, mutaborGUI::BoxData::GetLogicWindow, mutASSERT, mutaborGUI::SetCurrentBox, mutaborGUI::ToGUIBase, TRACEC, UNREACHABLEC.
void mutaborGUI::MutChild::OnGetFocus(wxFocusEvent &event)
References MutTextBox::box, mutaborGUI::SetCurrentBox, TRACEC.