//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __wxresource_h__
#define __wxresource_h__
class ConfigDlg : public wxDialog {
protected:
 wxRadioBox* ToneSystem;
 wxCheckBox* SaveEditor;
 wxCheckBox* ColorBars;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;
 wxButton* wxID_HELP;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("ConfigDlg"), wxT("wxDialog"));
  ToneSystem = XRCCTRL(*this,"ToneSystem",wxRadioBox);
  SaveEditor = XRCCTRL(*this,"SaveEditor",wxCheckBox);
  ColorBars = XRCCTRL(*this,"ColorBars",wxCheckBox);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
  wxID_HELP = XRCCTRL(*this,"wxID_HELP",wxButton);
 }
public:
ConfigDlg(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class AboutDlg : public wxDialog {
protected:
 wxHtmlWindow* m_htmlWin2;
 wxButton* wxID_OK;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("AboutDlg"), wxT("wxDialog"));
  m_htmlWin2 = XRCCTRL(*this,"m_htmlWin2",wxHtmlWindow);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
 }
public:
AboutDlg(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class CompileDlg : public wxDialog {
protected:
 wxStaticText* m_staticText1;
 wxStaticText* filename;
 wxStaticText* m_staticText3;
 wxStaticText* line;
 wxStaticText* m_staticText5;
 wxStaticText* logic;
 wxStaticText* tonelabel;
 wxStaticText* tones;
 wxStaticText* m_staticText9;
 wxStaticText* tunes;
 wxStaticLine* m_staticline1;
 wxStaticText* m_staticText11;
 wxStaticText* tone_system;
 wxStaticText* m_staticText13;
 wxStaticText* intervals;
 wxStaticText* m_staticText15;
 wxStaticText* chars;
 wxStaticText* message;
 wxButton* wxID_OK;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("CompileDlg"), wxT("wxDialog"));
  m_staticText1 = XRCCTRL(*this,"m_staticText1",wxStaticText);
  filename = XRCCTRL(*this,"filename",wxStaticText);
  m_staticText3 = XRCCTRL(*this,"m_staticText3",wxStaticText);
  line = XRCCTRL(*this,"line",wxStaticText);
  m_staticText5 = XRCCTRL(*this,"m_staticText5",wxStaticText);
  logic = XRCCTRL(*this,"logic",wxStaticText);
  tonelabel = XRCCTRL(*this,"tonelabel",wxStaticText);
  tones = XRCCTRL(*this,"tones",wxStaticText);
  m_staticText9 = XRCCTRL(*this,"m_staticText9",wxStaticText);
  tunes = XRCCTRL(*this,"tunes",wxStaticText);
  m_staticline1 = XRCCTRL(*this,"m_staticline1",wxStaticLine);
  m_staticText11 = XRCCTRL(*this,"m_staticText11",wxStaticText);
  tone_system = XRCCTRL(*this,"tone_system",wxStaticText);
  m_staticText13 = XRCCTRL(*this,"m_staticText13",wxStaticText);
  intervals = XRCCTRL(*this,"intervals",wxStaticText);
  m_staticText15 = XRCCTRL(*this,"m_staticText15",wxStaticText);
  chars = XRCCTRL(*this,"chars",wxStaticText);
  message = XRCCTRL(*this,"message",wxStaticText);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
 }
public:
CompileDlg(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class mutabor_box : public wxDialog {
protected:
 wxRadioButton* use_box;
 wxTextCtrl* m_textCtrl2;
 wxRadioButton* guido_box;
 wxFilePickerCtrl* m_filePicker1;
 wxRadioButton* no_box;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;
 wxButton* wxID_HELP;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("mutabor_box"), wxT("wxDialog"));
  use_box = XRCCTRL(*this,"use_box",wxRadioButton);
  m_textCtrl2 = XRCCTRL(*this,"m_textCtrl2",wxTextCtrl);
  guido_box = XRCCTRL(*this,"guido_box",wxRadioButton);
  m_filePicker1 = XRCCTRL(*this,"m_filePicker1",wxFilePickerCtrl);
  no_box = XRCCTRL(*this,"no_box",wxRadioButton);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
  wxID_HELP = XRCCTRL(*this,"wxID_HELP",wxButton);
 }
public:
mutabor_box(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class InputFilterDlgBase : public wxDialog {
protected:
 wxRadioBox* Type;
 wxStaticText* fromlabel;
 wxTextCtrl* From;
 wxStaticText* tolabel;
 wxTextCtrl* To;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;
 wxButton* wxID_REMOVE;
 wxButton* wxID_HELP;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("InputFilterDlgBase"), wxT("wxDialog"));
  Type = XRCCTRL(*this,"Type",wxRadioBox);
  fromlabel = XRCCTRL(*this,"fromlabel",wxStaticText);
  From = XRCCTRL(*this,"From",wxTextCtrl);
  tolabel = XRCCTRL(*this,"tolabel",wxStaticText);
  To = XRCCTRL(*this,"To",wxTextCtrl);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
  wxID_REMOVE = XRCCTRL(*this,"wxID_REMOVE",wxButton);
  wxID_HELP = XRCCTRL(*this,"wxID_HELP",wxButton);
 }
public:
InputFilterDlgBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class InputDevDlgBase : public wxDialog {
protected:
 wxChoice* DeviceChoice;
 wxChoice* PortChoice;
 wxFilePickerCtrl* MidiFilePicker;
 wxFilePickerCtrl* GuidoFilePicker;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;
 wxButton* wxID_REMOVE;
 wxButton* wxID_HELP;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("InputDevDlgBase"), wxT("wxDialog"));
  DeviceChoice = XRCCTRL(*this,"DeviceChoice",wxChoice);
  PortChoice = XRCCTRL(*this,"PortChoice",wxChoice);
  MidiFilePicker = XRCCTRL(*this,"MidiFilePicker",wxFilePickerCtrl);
  GuidoFilePicker = XRCCTRL(*this,"GuidoFilePicker",wxFilePickerCtrl);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
  wxID_REMOVE = XRCCTRL(*this,"wxID_REMOVE",wxButton);
  wxID_HELP = XRCCTRL(*this,"wxID_HELP",wxButton);
 }
public:
InputDevDlgBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class OutputDevDlgBase : public wxDialog {
protected:
 wxChoice* DeviceChoice;
 wxChoice* PortChoice;
 wxStaticText* MidiBendingRangeLabel;
 wxSpinCtrl* MidiBendingRange;
 wxStaticText* m_staticText21;
 wxFilePickerCtrl* MidiFilePicker;
 wxStaticText* MidiFileBendingRangeLabel;
 wxSpinCtrl* MidiFileBendingRange;
 wxStaticText* m_staticText23;
 wxFilePickerCtrl* GuidoFilePicker;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;
 wxButton* wxID_REMOVE;
 wxButton* wxID_HELP;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("OutputDevDlgBase"), wxT("wxDialog"));
  DeviceChoice = XRCCTRL(*this,"DeviceChoice",wxChoice);
  PortChoice = XRCCTRL(*this,"PortChoice",wxChoice);
  MidiBendingRangeLabel = XRCCTRL(*this,"MidiBendingRangeLabel",wxStaticText);
  MidiBendingRange = XRCCTRL(*this,"MidiBendingRange",wxSpinCtrl);
  m_staticText21 = XRCCTRL(*this,"m_staticText21",wxStaticText);
  MidiFilePicker = XRCCTRL(*this,"MidiFilePicker",wxFilePickerCtrl);
  MidiFileBendingRangeLabel = XRCCTRL(*this,"MidiFileBendingRangeLabel",wxStaticText);
  MidiFileBendingRange = XRCCTRL(*this,"MidiFileBendingRange",wxSpinCtrl);
  m_staticText23 = XRCCTRL(*this,"m_staticText23",wxStaticText);
  GuidoFilePicker = XRCCTRL(*this,"GuidoFilePicker",wxFilePickerCtrl);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
  wxID_REMOVE = XRCCTRL(*this,"wxID_REMOVE",wxButton);
  wxID_HELP = XRCCTRL(*this,"wxID_HELP",wxButton);
 }
public:
OutputDevDlgBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class BoxDlgBase : public wxDialog {
protected:
 wxChoicebook* boxType;
 wxButton* wxID_REMOVE;
 wxScrolledWindow* routeWindow;
 wxButton* wxID_ADD;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;
 wxButton* wxID_HELP;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("BoxDlgBase"), wxT("wxDialog"));
  boxType = XRCCTRL(*this,"boxType",wxChoicebook);
  wxID_REMOVE = XRCCTRL(*this,"wxID_REMOVE",wxButton);
  routeWindow = XRCCTRL(*this,"routeWindow",wxScrolledWindow);
  wxID_ADD = XRCCTRL(*this,"wxID_ADD",wxButton);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
  wxID_HELP = XRCCTRL(*this,"wxID_HELP",wxButton);
 }
public:
BoxDlgBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class MutaborBoxSettingsBase : public wxPanel {
protected:
 wxStaticText* boxNumberLabel;
 wxSpinCtrl* boxNumber;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("MutaborBoxSettingsBase"), wxT("wxPanel"));
  boxNumberLabel = XRCCTRL(*this,"boxNumberLabel",wxStaticText);
  boxNumber = XRCCTRL(*this,"boxNumber",wxSpinCtrl);
 }
public:
MutaborBoxSettingsBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class GuidoFileBoxSettingsBase : public wxPanel {
protected:

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("GuidoFileBoxSettingsBase"), wxT("wxPanel"));
 }
public:
GuidoFileBoxSettingsBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class NoBoxSettingsBase : public wxPanel {
protected:

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("NoBoxSettingsBase"), wxT("wxPanel"));
 }
public:
NoBoxSettingsBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class InputFilterPanelBase : public wxPanel {
protected:
 wxChoicebook* inputDevice;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("InputFilterPanelBase"), wxT("wxPanel"));
  inputDevice = XRCCTRL(*this,"inputDevice",wxChoicebook);
 }
public:
InputFilterPanelBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class OutputFilterPanelBase : public wxPanel {
protected:
 wxChoicebook* outputDevice;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("OutputFilterPanelBase"), wxT("wxPanel"));
  outputDevice = XRCCTRL(*this,"outputDevice",wxChoicebook);
 }
public:
OutputFilterPanelBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class RoutePanelBase : public wxPanel {
protected:
 wxStaticText* m_staticText25;
 wxChoice* box;
 wxRadioButton* active;
 wxRadioButton* passive;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("RoutePanelBase"), wxT("wxPanel"));
  m_staticText25 = XRCCTRL(*this,"m_staticText25",wxStaticText);
  box = XRCCTRL(*this,"box",wxChoice);
  active = XRCCTRL(*this,"active",wxRadioButton);
  passive = XRCCTRL(*this,"passive",wxRadioButton);
 }
public:
RoutePanelBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class GisInputFilterPanelBase : public wxPanel {
protected:
 wxChoicebook* type;
 wxPanel* all_panel;
 wxPanel* box_tag_panel;
 wxStaticText* m_staticText26;
 wxSpinCtrl* from_box;
 wxStaticText* m_staticText27;
 wxSpinCtrl* to_box;
 wxPanel* staves_panel;
 wxStaticText* m_staticText28;
 wxSpinCtrl* from_staff;
 wxStaticText* m_staticText29;
 wxSpinCtrl* to_staff;
 wxPanel* else_panel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("GisInputFilterPanelBase"), wxT("wxPanel"));
  type = XRCCTRL(*this,"type",wxChoicebook);
  all_panel = XRCCTRL(*this,"all_panel",wxPanel);
  box_tag_panel = XRCCTRL(*this,"box_tag_panel",wxPanel);
  m_staticText26 = XRCCTRL(*this,"m_staticText26",wxStaticText);
  from_box = XRCCTRL(*this,"from_box",wxSpinCtrl);
  m_staticText27 = XRCCTRL(*this,"m_staticText27",wxStaticText);
  to_box = XRCCTRL(*this,"to_box",wxSpinCtrl);
  staves_panel = XRCCTRL(*this,"staves_panel",wxPanel);
  m_staticText28 = XRCCTRL(*this,"m_staticText28",wxStaticText);
  from_staff = XRCCTRL(*this,"from_staff",wxSpinCtrl);
  m_staticText29 = XRCCTRL(*this,"m_staticText29",wxStaticText);
  to_staff = XRCCTRL(*this,"to_staff",wxSpinCtrl);
  else_panel = XRCCTRL(*this,"else_panel",wxPanel);
 }
public:
GisInputFilterPanelBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class GisOutputFilterPanelBase : public wxPanel {
protected:

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("GisOutputFilterPanelBase"), wxT("wxPanel"));
 }
public:
GisOutputFilterPanelBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class MidiInputFilterPanelBase : public wxPanel {
protected:
 wxChoicebook* type;
 wxPanel* all_panel;
 wxPanel* channel_panel;
 wxStaticText* m_staticText30;
 wxSpinCtrl* from_channel;
 wxStaticText* m_staticText31;
 wxSpinCtrl* to_channel;
 wxPanel* key_panel;
 wxStaticText* m_staticText32;
 wxSpinCtrl* from_key;
 wxStaticText* m_staticText33;
 wxSpinCtrl* to_key;
 wxPanel* else_panel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("MidiInputFilterPanelBase"), wxT("wxPanel"));
  type = XRCCTRL(*this,"type",wxChoicebook);
  all_panel = XRCCTRL(*this,"all_panel",wxPanel);
  channel_panel = XRCCTRL(*this,"channel_panel",wxPanel);
  m_staticText30 = XRCCTRL(*this,"m_staticText30",wxStaticText);
  from_channel = XRCCTRL(*this,"from_channel",wxSpinCtrl);
  m_staticText31 = XRCCTRL(*this,"m_staticText31",wxStaticText);
  to_channel = XRCCTRL(*this,"to_channel",wxSpinCtrl);
  key_panel = XRCCTRL(*this,"key_panel",wxPanel);
  m_staticText32 = XRCCTRL(*this,"m_staticText32",wxStaticText);
  from_key = XRCCTRL(*this,"from_key",wxSpinCtrl);
  m_staticText33 = XRCCTRL(*this,"m_staticText33",wxStaticText);
  to_key = XRCCTRL(*this,"to_key",wxSpinCtrl);
  else_panel = XRCCTRL(*this,"else_panel",wxPanel);
 }
public:
MidiInputFilterPanelBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class MidiOutputFilterPanelBase : public wxPanel {
protected:
 wxStaticText* m_staticText34;
 wxSpinCtrl* from_channel;
 wxStaticText* m_staticText35;
 wxSpinCtrl* to_channel;
 wxCheckBox* avoid_drum_channel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("MidiOutputFilterPanelBase"), wxT("wxPanel"));
  m_staticText34 = XRCCTRL(*this,"m_staticText34",wxStaticText);
  from_channel = XRCCTRL(*this,"from_channel",wxSpinCtrl);
  m_staticText35 = XRCCTRL(*this,"m_staticText35",wxStaticText);
  to_channel = XRCCTRL(*this,"to_channel",wxSpinCtrl);
  avoid_drum_channel = XRCCTRL(*this,"avoid_drum_channel",wxCheckBox);
 }
public:
MidiOutputFilterPanelBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class MidiFileInputFilterPanelBase : public wxPanel {
protected:
 wxChoicebook* type;
 wxPanel* all_panel;
 wxPanel* channel_panel;
 wxStaticText* m_staticText36;
 wxSpinCtrl* from_channel;
 wxStaticText* m_staticText37;
 wxSpinCtrl* to_channel;
 wxPanel* track_panel;
 wxStaticText* m_staticText38;
 wxSpinCtrl* from_track;
 wxStaticText* m_staticText39;
 wxSpinCtrl* to_track;
 wxPanel* else_panel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("MidiFileInputFilterPanelBase"), wxT("wxPanel"));
  type = XRCCTRL(*this,"type",wxChoicebook);
  all_panel = XRCCTRL(*this,"all_panel",wxPanel);
  channel_panel = XRCCTRL(*this,"channel_panel",wxPanel);
  m_staticText36 = XRCCTRL(*this,"m_staticText36",wxStaticText);
  from_channel = XRCCTRL(*this,"from_channel",wxSpinCtrl);
  m_staticText37 = XRCCTRL(*this,"m_staticText37",wxStaticText);
  to_channel = XRCCTRL(*this,"to_channel",wxSpinCtrl);
  track_panel = XRCCTRL(*this,"track_panel",wxPanel);
  m_staticText38 = XRCCTRL(*this,"m_staticText38",wxStaticText);
  from_track = XRCCTRL(*this,"from_track",wxSpinCtrl);
  m_staticText39 = XRCCTRL(*this,"m_staticText39",wxStaticText);
  to_track = XRCCTRL(*this,"to_track",wxSpinCtrl);
  else_panel = XRCCTRL(*this,"else_panel",wxPanel);
 }
public:
MidiFileInputFilterPanelBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class MidiFileOutputFilterPanelBase : public wxPanel {
protected:
 wxStaticText* m_staticText40;
 wxSpinCtrl* from_channel;
 wxStaticText* m_staticText41;
 wxSpinCtrl* to_channel;
 wxCheckBox* avoid_drum_channel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("MidiFileOutputFilterPanelBase"), wxT("wxPanel"));
  m_staticText40 = XRCCTRL(*this,"m_staticText40",wxStaticText);
  from_channel = XRCCTRL(*this,"from_channel",wxSpinCtrl);
  m_staticText41 = XRCCTRL(*this,"m_staticText41",wxStaticText);
  to_channel = XRCCTRL(*this,"to_channel",wxSpinCtrl);
  avoid_drum_channel = XRCCTRL(*this,"avoid_drum_channel",wxCheckBox);
 }
public:
MidiFileOutputFilterPanelBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class UnknownInputFilterPanelBase : public wxPanel {
protected:

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("UnknownInputFilterPanelBase"), wxT("wxPanel"));
 }
public:
UnknownInputFilterPanelBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class UnknownOutputFilterPanelBase : public wxPanel {
protected:

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("UnknownOutputFilterPanelBase"), wxT("wxPanel"));
 }
public:
UnknownOutputFilterPanelBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class ScalaImportDialogBase : public wxDialog {
protected:
 wxStaticText* IntervalPrefixLabel;
 wxTextCtrl* IntervalPrefix;
 wxStaticText* TonePrevfixLabel;
 wxTextCtrl* TonePrefix;
 wxStaticText* ToneSystemLabel;
 wxTextCtrl* ToneSystem;
 wxStaticText* LogicLabel;
 wxTextCtrl* Logic;
 wxStaticText* ScalaLabel;
 wxFilePickerCtrl* ScalaFile;
 wxStaticText* KeyMapLabel;
 wxFilePickerCtrl* KeyMap;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("ScalaImportDialogBase"), wxT("wxDialog"));
  IntervalPrefixLabel = XRCCTRL(*this,"IntervalPrefixLabel",wxStaticText);
  IntervalPrefix = XRCCTRL(*this,"IntervalPrefix",wxTextCtrl);
  TonePrevfixLabel = XRCCTRL(*this,"TonePrevfixLabel",wxStaticText);
  TonePrefix = XRCCTRL(*this,"TonePrefix",wxTextCtrl);
  ToneSystemLabel = XRCCTRL(*this,"ToneSystemLabel",wxStaticText);
  ToneSystem = XRCCTRL(*this,"ToneSystem",wxTextCtrl);
  LogicLabel = XRCCTRL(*this,"LogicLabel",wxStaticText);
  Logic = XRCCTRL(*this,"Logic",wxTextCtrl);
  ScalaLabel = XRCCTRL(*this,"ScalaLabel",wxStaticText);
  ScalaFile = XRCCTRL(*this,"ScalaFile",wxFilePickerCtrl);
  KeyMapLabel = XRCCTRL(*this,"KeyMapLabel",wxStaticText);
  KeyMap = XRCCTRL(*this,"KeyMap",wxFilePickerCtrl);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
 }
public:
ScalaImportDialogBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlResource();
#endif
