mutaborGUI::BoxData
typedef mutabor::BoxClass mutaborGUI::BoxData::basetype
MutBoxShapeList mutaborGUI::BoxData::shapes
Noch zu erledigencurent_logic and current_tonesystem are set but unused as well as current_key_tonesystem and current_key_logic
Referenced by Add, Destroy, GetShape, GetShapes, MoveToInList, Remove, set_routefile_id.
MutEditFile* mutaborGUI::BoxData::editor
Referenced by BoxData, DoClose, DoOpen, GetEditor, SetEditor.
wxColour mutaborGUI::BoxData::text_colour
Referenced by GetTextColour, set_routefile_id.
wxColour mutaborGUI::BoxData::background_colour
Referenced by GetBackgroundColour, set_routefile_id.
WinAttr mutaborGUI::BoxData::winattr
Referenced by GetActionsWindow, GetKeyWindow, GetLogicWindow, GetTonesystemWindow, Load, Save, set_routefile_id, SetActionsWindow, SetKeyWindow, SetLogicWindow, SetTonesystemWindow, ToggleActionsWindow, ToggleKeyWindow, ToggleTonesystemWindow, WantActionsWindow, WantKeyWindow, WantTonesystemWindow.
friend class GUIBoxFactory
mutabor::Box mutaborGUI::BoxData::curBox
Referenced by Activate, GetCurrentBox, SetCurrentBox.
const MutBoxShape * mutaborGUI::BoxData::GetShape(wxWindow *parent) const
References shapes.
Referenced by mutaborGUI::MutRouteWnd::AddRoute, mutaborGUI::Check, mutaborGUI::connect, mutaborGUI::connect_device_shape, mutaborGUI::MutRouteWnd::createBoxes, mutaborGUI::MutRouteWnd::createRoutes, mutaborGUI::disconnect, mutaborGUI::GUIRouteFactory::DoCreateBoxChannelShape, mutaborGUI::MutBoxChannelShape::ReadPanel.
MutBoxShape * mutaborGUI::BoxData::GetShape(wxWindow *parent)
References shapes.
void mutaborGUI::BoxData::set_routefile_id(int id)
References mutaborGUI::BoxData::WinAttr::actions_window, background_colour, mutabor::BoxClass::box, mutaborGUI::MutChildApi::BoxChanged, mutaborGUI::MutBoxShape::BoxChanged, DEBUGLOG2, mutaborGUI::MutFrame::GetActiveWindow, mutabor::GmnBox, mutabor::hidden::mutabor_box_type::id, mutaborGUI::BoxData::WinAttr::key_window, mutaborGUI::BoxData::WinAttr::logic_window, mutaborGUI::LogicOn, mutabor::NewBox, mutabor::NoBox, shapes, text_colour, mutaborGUI::BoxData::WinAttr::tonesystem_window, mutaborGUI::MutFrame::UpdateBoxMenu, winattr, WK_ROUTE.
Referenced by BoxData.
MutEditFile* mutaborGUI::BoxData::GetEditor()
References editor.
void mutaborGUI::BoxData::SetEditor(MutEditFile *edit)
References editor.
Referenced by mutaborGUI::MutEditFile::Compile.
const wxColour& mutaborGUI::BoxData::GetBackgroundColour() const
References background_colour.
Referenced by mutaborGUI::BEGIN_EVENT_TABLE, mutaborGUI::MutChild::BoxChanged, mutaborGUI::MutLogicWnd::BoxChanged, mutaborGUI::MutBoxShape::BoxChanged, EVT_CLOSE.
const wxColour& mutaborGUI::BoxData::GetTextColour() const
References text_colour.
Referenced by mutaborGUI::BEGIN_EVENT_TABLE, mutaborGUI::MutChild::BoxChanged, mutaborGUI::MutLogicWnd::BoxChanged, mutaborGUI::MutBoxShape::BoxChanged, EVT_CLOSE.
bool mutaborGUI::BoxData::WantKeyWindow() const
References mutaborGUI::BoxData::WinAttr::want_key_window, winattr.
Referenced by mutaborGUI::MutFrame::CeToggleKey, mutaborGUI::MutChild::deleteFromWinAttrs, mutaborGUI::DontWant, DoOpen, mutaborGUI::IsWanted, MutTextBox::OnClose, SetKeyWindow.
void mutaborGUI::BoxData::SetKeyWindow(MutChild *w, bool reset=false)
References mutaborGUI::BoxData::WinAttr::key_window, WantKeyWindow, winattr.
Referenced by mutaborGUI::BEGIN_EVENT_TABLE, mutaborGUI::MutChild::deleteFromWinAttrs.
MutChild* mutaborGUI::BoxData::GetKeyWindow() const
References mutaborGUI::BoxData::WinAttr::key_window, winattr.
Referenced by mutaborGUI::MutFrame::DoBoxWindowsClose, DoClose, mutaborGUI::IsOpen, MutTextBox::OnClose, mutaborGUI::MutFrame::ToggleTextBox.
bool mutaborGUI::BoxData::WantTonesystemWindow() const
References mutaborGUI::BoxData::WinAttr::want_tonesystem_window, winattr.
Referenced by mutaborGUI::MutFrame::CeToggleTS, mutaborGUI::MutChild::deleteFromWinAttrs, mutaborGUI::DontWant, DoOpen, mutaborGUI::IsWanted, MutTextBox::OnClose, SetTonesystemWindow.
void mutaborGUI::BoxData::SetTonesystemWindow(MutChild *w, bool reset=false)
References mutaborGUI::BoxData::WinAttr::tonesystem_window, WantTonesystemWindow, winattr.
Referenced by mutaborGUI::BEGIN_EVENT_TABLE, mutaborGUI::MutChild::deleteFromWinAttrs.
MutChild* mutaborGUI::BoxData::GetTonesystemWindow() const
References mutaborGUI::BoxData::WinAttr::tonesystem_window, winattr.
Referenced by mutaborGUI::MutFrame::DoBoxWindowsClose, DoClose, mutaborGUI::IsOpen, MutTextBox::OnClose, mutaborGUI::MutFrame::ToggleTextBox.
bool mutaborGUI::BoxData::WantActionsWindow() const
References mutaborGUI::BoxData::WinAttr::want_actions_window, winattr.
Referenced by mutaborGUI::MutFrame::CeToggleAct, mutaborGUI::MutChild::deleteFromWinAttrs, mutaborGUI::DontWant, DoOpen, mutaborGUI::IsWanted, MutTextBox::OnClose, SetActionsWindow.
void mutaborGUI::BoxData::SetActionsWindow(MutChild *w, bool reset=false)
References mutaborGUI::BoxData::WinAttr::actions_window, WantActionsWindow, winattr.
Referenced by mutaborGUI::BEGIN_EVENT_TABLE, mutaborGUI::MutChild::deleteFromWinAttrs.
MutChild* mutaborGUI::BoxData::GetActionsWindow() const
References mutaborGUI::BoxData::WinAttr::actions_window, winattr.
Referenced by mutaborGUI::MutFrame::DoBoxWindowsClose, DoClose, mutaborGUI::IsOpen, MutTextBox::OnClose, mutaborGUI::MutFrame::ToggleTextBox.
void mutaborGUI::BoxData::WantKeyWindow(bool yesno)
References mutaborGUI::BoxData::WinAttr::want_key_window, winattr.
void mutaborGUI::BoxData::WantTonesystemWindow(bool yesno)
References mutaborGUI::BoxData::WinAttr::want_tonesystem_window, winattr.
void mutaborGUI::BoxData::WantActionsWindow(bool yesno)
References mutaborGUI::BoxData::WinAttr::want_actions_window, winattr.
bool mutaborGUI::BoxData::ToggleKeyWindow()
References mutaborGUI::BoxData::WinAttr::want_key_window, winattr.
Referenced by mutaborGUI::MutFrame::ToggleTextBox.
bool mutaborGUI::BoxData::ToggleTonesystemWindow()
References mutaborGUI::BoxData::WinAttr::want_tonesystem_window, winattr.
Referenced by mutaborGUI::MutFrame::ToggleTextBox.
bool mutaborGUI::BoxData::ToggleActionsWindow()
References mutaborGUI::BoxData::WinAttr::want_actions_window, winattr.
Referenced by mutaborGUI::MutFrame::ToggleTextBox.
void mutaborGUI::BoxData::SetLogicWindow(MutLogicWnd *w)
References mutaborGUI::BoxData::WinAttr::logic_window, winattr.
Referenced by mutaborGUI::BEGIN_EVENT_TABLE, mutaborGUI::MutLogicWnd::~MutLogicWnd.
MutLogicWnd* mutaborGUI::BoxData::GetLogicWindow() const
References mutaborGUI::BoxData::WinAttr::logic_window, winattr.
Referenced by Activate, mutaborGUI::BEGIN_EVENT_TABLE, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::DoBoxWindowsClose, DoClose, mutaborGUI::IsOpen, mutaborGUI::MutChild::OnChar, mutaborGUI::MutFrame::RaiseLogic, mutaborGUI::MutFrame::UpdateBoxMenu.
const MutBoxShapeList& mutaborGUI::BoxData::GetShapes() const
References shapes.
Referenced by mutaborGUI::Check, mutaborGUI::GUIBoxFactory::DoCreateBoxShape, mutaborGUI::MutRouteWnd::InitShapes, mutaborGUI::MakeTopLevelsBoxes, mutaborGUI::GUIRouteBase::Remove, mutaborGUI::GUIRouteBase::Replace.
void mutaborGUI::BoxData::MoveToInList(int newpos)
Move the associated box shape to a given position.
This function handles the GUI part of MoveInList(). newpos New position of the shape in the list. This parameter should reflect the actual position of the box in the (non GUI) box list.
References shapes.
Referenced by MoveInList.
int mutaborGUI::BoxData::MoveInList(int count)
Move the box in the box list.
count Number of places the box should be moved up. Negative values indicate downwards direction. new position in the box list.
References mutabor::BoxClass::MoveInList, MoveToInList.
void mutaborGUI::BoxData::Add(MutBoxShape *shape)
References shapes, UNREACHABLEC.
Referenced by mutaborGUI::connect.
bool mutaborGUI::BoxData::Remove(MutBoxShape *shape)
References mutASSERT, shapes, UNREACHABLEC.
Referenced by mutaborGUI::disconnect.
void mutaborGUI::BoxData::Destroy()
Destroy the current object.
This function is called when an object shall be deleted. It clears up all references to itself so that it will be deleted if it is not needed anymore.This functions detatches the device from all routes and calls DoDestroy() afterwards. Finally the Device is going to removed from the device list.
References MutIconShapeClass< T >::Destroy, mutabor::BoxClass::Destroy, mutaborGUI::disconnect, GetCurrentBox, SetCurrentBox, shapes.
void mutaborGUI::BoxData::Save(mutabor::tree_storage &config)
Save current device settings in a tree storage.
config (tree_storage) storage class, where the data will be saved.
References mutabor::BoxClass::Save, mutaborGUI::BoxData::WinAttr::want_actions_window, mutaborGUI::BoxData::WinAttr::want_key_window, mutaborGUI::BoxData::WinAttr::want_tonesystem_window, winattr, mutabor::tree_storage::Write.
void mutaborGUI::BoxData::Load(mutabor::tree_storage &config)
Load current device settings from a tree storage.
config (tree_storage) storage class, where the data will be loaded from.
References mutabor::BoxClass::Load, mutabor::tree_storage::Read, mutaborGUI::BoxData::WinAttr::want_actions_window, mutaborGUI::BoxData::WinAttr::want_key_window, mutaborGUI::BoxData::WinAttr::want_tonesystem_window, winattr.
bool mutaborGUI::BoxData::DoOpen()
do the work for opening a box
References mutabor::BoxClass::DoOpen, editor, mutASSERT, mutabor::BoxClass::mutex, mutaborGUI::MutFrame::TextBoxOpen, UNREACHABLEC, mutaborGUI::MutFrame::UpdateBoxMenu, WantActionsWindow, WantKeyWindow, WantTonesystemWindow, WK_ACT, WK_KEY, WK_ROUTE, WK_TS.
void mutaborGUI::BoxData::DoClose()
do the work for closing a box
References mutaborGUI::MutFrame::CloseClientWindow, editor, GetActionsWindow, GetKeyWindow, GetLogicWindow, GetTonesystemWindow, mutASSERT, UNREACHABLEC, mutaborGUI::MutFrame::UpdateBoxMenu, WK_ROUTE.
void mutaborGUI::BoxData::Activate()
Activate the current box.
This method is called when a box is being activated. Its implementation should be done in the user code. Otherwise its just a no-op function.
References curBox, GetLogicWindow.
static mutabor::Box mutaborGUI::BoxData::GetCurrentBox()
References curBox.
Referenced by Destroy, mutaborGUI::GetCurrentBox, mutaborGUI::MutFrame::UpdateBoxMenu.
static void mutaborGUI::BoxData::SetCurrentBox(mutabor::Box b)
References curBox.
Referenced by Destroy, mutaborGUI::SetCurrentBox.
mutaborGUI::BoxData::BoxData(int id)
References mutabor::BoxClass::boxList, editor, set_routefile_id, mutabor::BoxClass::SetLogic, mutaborGUI::ToGUIBase.
void mutaborGUI::BoxData::runtime_error(mutabor::error_type type, const char *message)
Process an error message (doing the real work)
References mutaborGUI::CM_PRINT_ERROR, mutabor::hidden::internal_error, mutabor::to_string.