box.cpp
int laufzeit_meldungen_erlaubt
int aktuelles_midi_instrument
size_t minimal_box_used
Referenced by mutaborGUI::CheckBoxesUsed, mutaborGUI::MutFrame::CloseAll, mutaborGUI::MutFrame::CmDoActivate.
int keys_changed_sum
void mutabor_set_logic(struct mutabor_box_type *box, struct mutabor_logic_parsed *logic)
References mutabor_box_type::file, loesche_syntax_speicher, mutabor_lock_logic, mutabor_unlock_logic, mutabor_logic_parsed::refcount.
Referenced by mutabor::BoxClass::SetLogic.
void mutabor_reset_keys(struct mutabor_box_type *box)
References mutabor_box_type::current_keys, mutabor_key_index_type::key, mutabor_box_type::key_count, mutabor_delete_key_in_box, mutabor_find_key_in_box, MUTABOR_KEYRANGE_MAX_WIDTH, MUTABOR_NO_NEXT, mutabor_note_type::next, mutabor_box_type::pattern, PTRN::tonigkeit.
Referenced by mutabor_reset_box, mutabor::BoxClass::Panic.
void mutabor_reset_box(struct mutabor_box_type *box)
References TSYS::anker, mutabor_box_type::current_logic, mutabor_box_type::current_parameters, mutabor_box_type::distance, mutabor_box_type::last_tonesystem, mutabor_convert_pitch_to_interval, mutabor_convert_pitch_to_tone, MUTABOR_KEYRANGE_MAX_WIDTH, mutabor_reset_keys, TSYS::ton, mutabor_box_type::tonesystem, mutabor_box_type::tonesystem_memory.
Referenced by mutabor_initialize_box, mutabor::BoxClass::Reset.
void mutabor_initialize_box(mutabor_box_type *box, int id)
References mutabor_box_type::current_keys, mutabor_box_type::current_logic, mutabor_box_type::current_parameters, mutabor_box_type::id, mutabor_key_index_type::key, mutabor_initialize_keyplane, mutabor_reset_box, mutASSERT, mutabor_box_type::parameters, mutabor_box_type::userdata.
Referenced by mutabor::BoxClass::BoxClass, boxTest::setUp.
void mutabor_initialize_keyplane(mutabor_key_index_type *plane)
References mutabor_key_index_type::key, MUT_BOX_MAX_KEY_INDEX, MUTABOR_NO_NEXT, mutabor_note_type::next, mutabor_key_index_type::next, mutabor_note_type::userdata.
Referenced by mutabor_create_key_in_box, mutabor_initialize_box.