interpreter.c
struct interpreter_parameter_liste zentrums_knoten
Diese Zweielementige Liste ist Parameterliste bei Logiken.
struct interpreter_parameter_liste abstands_knoten
Diese Zweielementige Liste ist Parameterliste bei Logiken.
struct interpreter_parameter_liste* start_parameter_liste
Diese Zweielementige Liste ist Parameterliste bei Logiken.
Referenced by insert_in_lokale_liste.
int laufzeit_zentrum[MAX_BOX][MAX_BOX]
int laufzeit_abstand[MAX_BOX][MAX_BOX]
struct cache_konstanten* cache_konstanten
int(* get_cache_konstante(int wert))[MAX_BOX]
Sichert, dass ein Wert in cache_konstanten vorhanden ist und gibt das entsprechende Element der Liste zurück.
Bei neuen Einträgen werden alle Einträge des entsprechenden Feldes konstante auf den übergebenen Wert gesetzt. wert Wert, dessen Element zurückgegeben werden soll
References cache_konstanten::konstante, MAX_BOX, cache_konstanten::next, xmalloc.
Referenced by gen_parameter_liste, get_wert_of_argument.
void mutabor_tabellen_generator(void)
Initialisiert die Mutabor-Tabellen.
Dabei werden die globalen und die lokalen Auslöser initialisiert.
References logik::anweisungsliste, expandiere_in_globale_liste, first_harmonie, first_keyboard, first_lokal_harmonie, first_lokal_keyboard, first_lokal_midi, first_midi, get_ende_harmonie, get_ende_keyboard, get_ende_midi, insert_in_globale_liste, insert_in_lokale_liste, last_global_harmonie, last_global_keyboard, last_global_midi, list_of_logiken, logik_list_laenge, MAX_BOX, logik::name, logik::next, anweisung::next, xcalloc.
Referenced by GMutCompile.