argument.c
struct argument_liste* list_of_argumente
Argumentliste.
Referenced by get_last_argument_liste.
int argument_list_laenge(struct argument_liste *list)
Zählen der Elemente einer einfach verketteten Argumentliste.
list Liste der Argumente Anzahl der Elemente von list
References argument_list_laenge, anweisung::next.
Referenced by argument_list_laenge, check_aktionen, check_konsistenz, check_umstimmungs_konsistenz.
void print_argumentliste(struct argument_liste *this_)
Gibt eine Argumentliste auf der Standardausgabe aus.
this_ Liste der Argumente, die ausgegeben werden sollen.
References argument::argument_typ, anweisung::next, argument::parameter, print_argumentliste, argument::u, zahl, argument::zahl.
void init_argument_liste(void)
Setzt Argumentliste auf NULL.
Die Argumentliste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by yyparse.
void get_new_number_in_argument_list(double parameter_zahl)
Fügt eine Zahl ans Ende von list_of_argumente an.
parameter_zahl Zahl, die angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität? Noch zu erledigenTypkonvertierung von double nach int prüfen
References argument::argument_typ, argument_liste::next, argument::u, xmalloc, zahl, argument::zahl.
Referenced by switch, yyparse.
void get_new_name_in_argument_list(char *parameter_name)
Fügt einen Namen ans Ende von list_of_argumente an.
parameter_name Name, der angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References argument::argument_typ, fatal_error, name, argument_liste::next, parameter, argument::parameter, argument::u, xmalloc.
Referenced by switch, yyparse.
struct argument_liste* get_last_argument_liste(void)
Gibt die Wurzel von list_of_argumente zurück.
References list_of_argumente.
Referenced by get_new_aktion_aufruf_element.
void drucke_argument(struct argument *z_or_p)
Gibt ein Argument auf der Standardausgabe aus.
z_or_p Argument.
References argument::parameter, argument::u, zahl, argument::zahl.
Referenced by mutabor_programm_einlesen.
void fprint_argument(FILE *zieldatei, struct argument *argument)
Schreibt ein Argument in eine Zieldatei.
Das Argument wird je nach Typ als Zeichenkette oder Zahl ausgegeben. Ist der Typ unbekannt, wird ein fataler Fehler ausgegeben. zieldatei Datei, in die geschrieben werden soll. Diese muss schon für das Schreiben geöffnet sein. argument Argument, das geschrieben werden soll.
References fatal_error, MUTABOR_ERROR_UNDEFINED, parameter, argument::parameter, zahl, argument::zahl.
int* get_wert_of_argument(struct argument *argument, struct interpreter_parameter_liste *aktuelle_parameter)
Gibt das Wertefeld eines Argumentes zurück.
argument Argument, das gesucht werden soll. aktuelle_parameter Interpreter-Parameter-Liste mit Wertefeldern für nichtnumerische Argumente.
References argument::argument_typ, fatal_error, get_cache_konstante, MUTABOR_ERROR_UNDEFINED, interpreter_parameter_liste::next, parameter, argument::parameter, argument::u, interpreter_parameter_liste::werte_feld, zahl, argument::zahl.
Referenced by expandiere_umstimmung.