gmut.cpp
OUTLISTDATA
Referenced by main.
typedef struct INLISTTAG InListTag
typedef struct OUTLISTTAG OutListTag
ostream* Echo
#include "midikern.h"
Referenced by GetInFile, GMutCompile, main, PrintHelp.
jmp_buf weiter_gehts_nach_compilerfehler
Referenced by GMutCompile, mutabor::BoxClass::Compile.
InListTag* InList
Referenced by GetInFile.
OutListTag* OutList
Referenced by GetOutFile.
int Error
Referenced by GetInFile, main.
InDevice* GetInFile(char *name)
References INLISTTAG::Data, Echo, Error, ExtCheck, GisParse, GspError, GspErrorLine, GspErrorLineNr, GspErrorPos, GspErrorText, InList, INLISTTAG::Next.
Referenced by main.
OutDevice* GetOutFile(char *name)
References OUTLISTTAG::Device, ExtCheck, OUTLISTTAG::Next, OutList.
Referenced by main.
void DoRoute(InDevice *In, OutDevice *Out, char *s)
References mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff.
Referenced by main.
char GMutCompile(char *fileName)
References Echo, init_yylex, loesche_syntax_speicher, mutabor_programm_einlesen, weiter_gehts_nach_compilerfehler.
Referenced by main.
void PrintHelp()
References Echo.
Referenced by main.
int main(int argc, char *argv[])
References DoRoute, Echo, Error, ExtCheck, GetInFile, GetOutFile, GMutCompile, GTUnknown, mutabor::InClose, mutabor::InOpen, KeyboardIn, OUTLISTTAG::Next, mutabor::OutAddTime, mutabor::OutClose, OUTLISTDATA, mutabor::OutOpen, PrintHelp.