mutaborGUI::MutDeviceShape
typedef T::Device mutaborGUI::MutDeviceShape< T >::devicetype
typedef T::DeviceClass mutaborGUI::MutDeviceShape< T >::DeviceClass
typedef T::GUIDeviceBase mutaborGUI::MutDeviceShape< T >::GUIDeviceBase
typedef T::DeviceDialog mutaborGUI::MutDeviceShape< T >::DeviceDialog
typedef T::FilterPanel mutaborGUI::MutDeviceShape< T >::FilterPanel
typedef MutDeviceShape<T> mutaborGUI::MutDeviceShape< T >::thistype
typedef std::map<wxString *, MutDeviceShape *, strptrless> mutaborGUI::MutDeviceShape< T >::stringmaptype
typedef stringmaptype::iterator mutaborGUI::MutDeviceShape< T >::stringmapiterator
MutBoxChannelShapeList mutaborGUI::MutDeviceShape< T >::routes
Referenced by mutaborGUI::MutDeviceShape< T >::GetChannels, mutaborGUI::MutDeviceShape< T >::MoveRoutes.
devicetype mutaborGUI::MutDeviceShape< T >::device
Referenced by mutaborGUI::MutDeviceShape< T >::Add, mutaborGUI::MutDeviceShape< T >::DoLeftDblClick, mutaborGUI::MutDeviceShape< T >::GetDevice, mutaborGUI::MutDeviceShape< T >::GetGUIDevice, mutaborGUI::MutDeviceShape< T >::getRoutes, mutaborGUI::MutDeviceShape< T >::MoveDevice, mutaborGUI::MutDeviceShape< T >::Remove, mutaborGUI::MutDeviceShape< T >::Replace, mutaborGUI::MutDeviceShape< T >::replaceSelfBy.
wxSizer* mutaborGUI::MutDeviceShape< T >::playbuttons
wxSizerFlags mutaborGUI::MutDeviceShape< T >::sizerFlags
Referenced by mutaborGUI::MutDeviceShape< T >::GetSizerFlags, mutaborGUI::MutDeviceShape< T >::SetSizerFlags.
mutaborGUI::MutDeviceShape< T >::~MutDeviceShape()
References mutaborGUI::disconnect, TRACEC.
bool mutaborGUI::MutDeviceShape< T >::Create(wxWindow *parent, wxWindowID id, const wxString &name=wxEmptyString)
References MutIconShapeClass< T >::Create, DEBUGLOG, MutIconShapeClass< T >::SetLabel.
Referenced by mutaborGUI::MutNewInputDeviceShape::Create, mutaborGUI::MutOutputMidiFileDeviceShape::Create, mutaborGUI::MutNewOutputDeviceShape::Create, mutaborGUI::MutOutputMidiDeviceShape::Create, mutaborGUI::MutInputGuidoFileDeviceShape::Create, mutaborGUI::MutOutputGuidoFileDeviceShape::Create, mutaborGUI::MutInputMidiDeviceShape::Create, mutaborGUI::MutInputMidiFileDeviceShape::Create, mutaborGUI::MutDeviceShape< T >::MutDeviceShape.
bool mutaborGUI::MutDeviceShape< T >::Create(wxWindow *parent, wxWindowID id, devicetype &d)
References mutaborGUI::connect, DEBUGLOG, mutaborGUI::MidiInputDevBitmap, mutaborGUI::MidiOutputDevBitmap, mutASSERT, TRACEC.
const devicetype& mutaborGUI::MutDeviceShape< T >::GetDevice() const
References mutaborGUI::MutDeviceShape< T >::device.
Referenced by mutaborGUI::connect, mutaborGUI::disconnect, mutaborGUI::reconnect, mutaborGUI::MutDeviceShape< T >::replaceSelfBy.
devicetype& mutaborGUI::MutDeviceShape< T >::GetDevice()
References mutaborGUI::MutDeviceShape< T >::device.
const GUIDeviceBase* mutaborGUI::MutDeviceShape< T >::GetGUIDevice() const
References mutaborGUI::MutDeviceShape< T >::device, mutaborGUI::ToGUIBase.
GUIDeviceBase* mutaborGUI::MutDeviceShape< T >::GetGUIDevice()
References mutaborGUI::MutDeviceShape< T >::device, mutaborGUI::ToGUIBase.
mutabor::routeListType& mutaborGUI::MutDeviceShape< T >::getRoutes()
References mutaborGUI::MutDeviceShape< T >::device, TRACEC, UNREACHABLEC.
const MutBoxChannelShapeList& mutaborGUI::MutDeviceShape< T >::GetChannels() const
References mutaborGUI::MutDeviceShape< T >::routes.
virtual void mutaborGUI::MutDeviceShape< T >::Add(DeviceClass *dev)
add a device
References mutaborGUI::MutDeviceShape< T >::device, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::GUIRouteBase::Add, mutaborGUI::connect, mutaborGUI::MutRouteWnd::createRoutes.
virtual bool mutaborGUI::MutDeviceShape< T >::Replace(devicetype olddev, devicetype newdev)
replace a device
References mutaborGUI::MutDeviceShape< T >::device, TRACEC, UNREACHABLEC.
virtual bool mutaborGUI::MutDeviceShape< T >::Remove(devicetype dev)
remove a device
References mutaborGUI::MutDeviceShape< T >::device, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::disconnect, mutaborGUI::GUIRouteBase::Remove.
void mutaborGUI::MutDeviceShape< T >::Add(MutBoxChannelShape *route)
add a route
References mutASSERT.
bool mutaborGUI::MutDeviceShape< T >::Replace(MutBoxChannelShape *oldroute, MutBoxChannelShape *newroute)
replace a route
References mutASSERT.
bool mutaborGUI::MutDeviceShape< T >::Remove(MutBoxChannelShape *route)
remove a route
References UNREACHABLEC.
bool mutaborGUI::MutDeviceShape< T >::MoveRoutes(MutDeviceShape *newclass)
Move routes to another device.
References mutaborGUI::MutDeviceShape< T >::routes.
bool mutaborGUI::MutDeviceShape< T >::Recompute()
virtual wxPanel* mutaborGUI::MutDeviceShape< T >::GetFilterPanel(wxWindow *parent, mutabor::Route &route) const =0
virtual void mutaborGUI::MutDeviceShape< T >::ReadFilterPanel(wxWindow *panel, mutabor::Route &route)=0
Referenced by mutaborGUI::MutDeviceShape< T >::ReadPanel.
void mutaborGUI::MutDeviceShape< T >::ReadPanel(FilterPanel *panel, MutBoxChannelShape *channel)
References mutaborGUI::disconnect, mutaborGUI::MutBoxChannelShape::GetRoute, mutASSERT, mutaborGUI::MutDeviceShape< T >::ReadFilterPanel, mutaborGUI::reconnect, TRACEC, UNREACHABLEC.
void mutaborGUI::MutDeviceShape< T >::OnKeyDown(wxKeyEvent &event)
void mutaborGUI::MutDeviceShape< T >::CmMoveIcon(wxCommandEvent &event)
Move the corresponding device in the device list and update the GUI according to the new order.
event wxCommandEvent containing the request
void mutaborGUI::MutDeviceShape< T >::CmDeviceNotification(wxCommandEvent &event)
The device notifies the shape about a state change.
event wxCommandEvent containing the request
References mutaborGUI::MutDeviceShape< T >::DoDeviceNotification.
void mutaborGUI::MutDeviceShape< T >::DoDeviceNotification(wxCommandEvent &event)
The device notifies the shape about a state change.
event wxCommandEvent containing the request
References mutabor::DeviceCompileError, mutabor::DeviceInitializing, mutabor::DevicePause, mutabor::DevicePlay, mutabor::DeviceStop, mutabor::DeviceTimingError, mutabor::DeviceUnregistered.
Referenced by mutaborGUI::MutDeviceShape< T >::CmDeviceNotification.
void mutaborGUI::MutDeviceShape< T >::LeftDblClickEvent(wxMouseEvent &event)
Get a double click and prepare for execution of the command.
Since programs might produce segmentation faults when the object is deleted during processing of mouse events, we send us a new event using the event queue.
References mutaborGUI::CM_LEFT_DOUBLE_CLICK.
void mutaborGUI::MutDeviceShape< T >::CmLeftDblClick(wxCommandEvent &event)
Process a double click.
Since programs might produce segmentation faults when the object is deleted during processing of mouse events, we send us a new event using the event queue.
References mutaborGUI::MutDeviceShape< T >::DoLeftDblClick.
static void mutaborGUI::MutDeviceShape< T >::SetSizerFlags(wxSizerFlags flags)
References mutaborGUI::MutDeviceShape< T >::sizerFlags.
static const wxSizerFlags& mutaborGUI::MutDeviceShape< T >::GetSizerFlags()
References mutaborGUI::MutDeviceShape< T >::sizerFlags.
mutaborGUI::MutDeviceShape< T >::MutDeviceShape()
mutaborGUI::MutDeviceShape< T >::MutDeviceShape(wxWindow *parent, wxWindowID id, const wxString &name=wxEmptyString)
References mutaborGUI::MutDeviceShape< T >::Create.
mutaborGUI::MutDeviceShape< T >::MutDeviceShape(wxWindow *parent, wxWindowID id, devicetype &d)
References mutaborGUI::MutDeviceShape< T >::Create.
virtual void mutaborGUI::MutDeviceShape< T >::MoveDevice(int count)
Move the corresponding device in the device list and update the GUI according to the new order.
count number of entries the device should be moved up. Negative values indicate downwards direction.
References mutaborGUI::MutDeviceShape< T >::device.
void mutaborGUI::MutDeviceShape< T >::DoLeftDblClick()
Execute the double click.
Despite its name this function must not be called directly from a double click event handler. Click event handlers are not proof against control deletion.
References mutaborGUI::GUIDeviceFactory::CreateShape, mutaborGUI::DebugCheckRoutes, mutaborGUI::MutDeviceShape< T >::device, mutabor::DTNotSet, mutaborGUI::LogicOn, mutASSERT, TRACE, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::MutDeviceShape< T >::CmLeftDblClick.
OutputDevDlg * mutaborGUI::MutOutputDeviceShape::ShowDeviceDialog()
References ABSTRACT_FUNCTIONC.
virtual void mutaborGUI::MutDeviceShape< T >::InitializeDialog(DeviceDialog *in) const
virtual bool mutaborGUI::MutDeviceShape< T >::readDialog(DeviceDialog *dlg)
Initialize device data from a dialog.
Transfers the data from a dialog window into the corresponding device object. dlg device dialog true if the device has changed in a way that it must be reinitialized. false otherwise
References mutASSERT.
bool mutaborGUI::MutDeviceShape< T >::DetachDevice()
detach device
Detaches the device from any route and deletes the device. true if the corresponding device has been removed and we can delete the Shape.
References TRACEC.
bool mutaborGUI::MutDeviceShape< T >::replaceSelfBy(thistype *newshape)
References mutaborGUI::MutDeviceShape< T >::device, mutaborGUI::MutDeviceShape< T >::GetDevice, mutASSERT, TRACEC, TRACET.
virtual bool mutaborGUI::MutDeviceShape< T >::CanHandleType(mutabor::DevType type)
void mutaborGUI::MutDeviceShape< T >::createPlayButtons()
References mutaborGUI::DevicePauseBitmap, mutaborGUI::DevicePlayBitmap, mutaborGUI::DeviceStopBitmap, mutASSERT.
void mutaborGUI::MutDeviceShape< T >::createPauseButton()
References mutaborGUI::DevicePauseBitmap, mutASSERT.
void mutaborGUI::MutDeviceShape< T >::createRecordButtons()
References mutaborGUI::DevicePauseBitmap, mutaborGUI::DeviceRecordBitmap, mutaborGUI::DeviceStopBitmap, mutASSERT.
void mutaborGUI::MutDeviceShape< T >::PlayButtonPressed(wxCommandEvent &event)