instrument.h
struct instrument* list_of_instrumente
Wurzel der Instrumente.
Referenced by yyparse.
struct instrument* list_of_config_instrumente
Wurzel der Instrumentenkonfiguration.
Referenced by mutabor_programm_einlesen.
void get_instrument_dekl(int midi_in, int midi_von, int midi_bis, int midi_umleit, struct instrument **list_to_insert)
Einlesen der Instrumentdeklarationen.
Falls das Instrument schon vorhanden ist, wird eine Fehlermeldung ausgegeben. midi_in MIDI-Instrument midi_von kleinster MIDI-Kanal midi_bis größter MIDI-Kanal midi_umleit MIDI-Durchleitung list_to_insert Instrumentenliste Es wird immer die gesamte Liste durchsucht. Effektivität?
References fatal_error, instrument::midi_bis, instrument::midi_in, instrument::midi_umleit, instrument::midi_von, instrument::next, xmalloc.
Referenced by mutabor_programm_einlesen, SetChannels, switch, yyparse.