/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 for compiling in ansi mode. */
/* #undef ANSI */

/* Define to 1 for compiling in debug mode. */
#define DEBUG 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `asound' library (-lasound). */
#define HAVE_LIBASOUND 0

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `pow' function. */
#define HAVE_POW 1

/* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of this package */
#define PACKAGE "mutabor"

/* address for reporting bugs */
#define PACKAGE_BUGREPORT "mutabor@math.tu-dresden.de"

/* Define to the full name of this package. */
#define PACKAGE_NAME "mutabor"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mutabor 3.9"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "mutabor"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.9"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version of this package */
#define VERSION "3.9"

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
#define YYTEXT_POINTER 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */


/* Debug also for Bison output. */
#ifdef DEBUG
#  define YYDEBUG 1
#endif

/* Windows VC6 
#define MUTWIN
#define WX
#define RTMIDI
#define __WINDOWS_MM__
#define REUSE(x) 
#define NO_SSTREAM */

/* Windows VC8 */
#define MUTWIN
#define WX
#define RTMIDI
#define __WINDOWS_MM__
#define REUSE(x) x
#define NO_SSTREAM 

#define VC8