#!/bin/sh

installpath=./help

if command -v xhtex > /dev/null 2>&1 ; then
  true
else
  export PATH=/usr/share/tex4ht:$PATH
fi

#        latex $5 '\makeatletter\def\HCode{\futurelet\HCode\HChar}\def\HChar{\ifx"\HCode\def\HCode"##1"{\Link##1}\expandafter\HCode\else\expandafter\Link\fi}\def\Link#1.a.b.c.{\g@addto@macro\@documentclasshook{\RequirePackage[#1,html]{tex4ht}}\let\HCode\documentstyle\def\documentstyle{\let\documentstyle\HCode\expandafter\def\csname tex4ht\endcsname{#1,html}\def\HCode####1{\documentstyle[tex4ht,}\@ifnextchar[{\HCode}{\documentstyle[tex4ht]}}}\makeatother\HCode '$2'.a.b.c.\input ' $1

for datei in "$@"
do
  rm -f ${datei%.tex}.{idx,aux,ind,xref,4ct,4tc,tmp}
done

for seq in 1 2 3 4
do 
  for datei in "$@"
  do
      dateiname=`basename "$datei"`
    echo 
    echo $seq $datei
    echo $TEXINPUTS
    echo
	latex -interaction=nonstopmode '\def\outputformat{help}\input '"$datei"
	if [ -f "${datei%.tex}".idx ] 
	then
  	  tex '\def\filename{{'"${dateiname%.tex}"'}{idx}{4dx}{ind}} \input  idxmake.4ht' 
	  makeindex -o ${datei%.tex}.ind ${dateiname%.tex}.4dx 
	  makeindex -s wxdin.ist -o ${datei%.tex}.wxi ${dateiname%.tex}.4dx
        fi
  done
done

mkdir -p "$installpath"


for datei in "$@"
do
	instpath="$installpath"
        tex4ht -f/${datei%.tex} -cunihtf -utf8 -cconvert -cvalidate
        t4ht -f/${datei%.tex} -cunihtf -utf8 -cconvert -cvalidatehtml ## -d~/WWW/temp/ -m644 

	filebase="`basename ${datei%.tex}`"

	# for portability reasons: don't use “{html,png,js,css}”
	mv ${filebase}*.html ${filebase}*.png ${filebase}*.js ${filebase}*.css $instpath

	$htmldecode <${filebase}.hhk | sed -e '/^ *$/ d' >$instpath/${filebase}.hhk
	$htmldecode <${filebase}.hhc | sed -e '/^ *$/ d' >$instpath/${filebase}.hhc
	$fixhhp <${filebase}.hhp|sed -e 's/^ *//g; /^$/ d' |$htmldecode>$instpath/${filebase}.hhp
	cp *.png $instpath
done
cp "$srcdir"/*.png "$installpath"
cp "$top_docdir"/*.png "$installpath"
(cd $instpath ; zip ../help.zip *)

