.TH Mutabor "1" "Jannuary 2012" "Mutabor 4.0.0beta2" "User Commands"
.SH NAME 
Mutabor \- the dynamic tempered piano is a GUI based MIDI microtuner
.SH SYNOPSIS
.B mutabor
[\fI-h\fR] [\fI--verbose\fR] [\fIlogic file\fR...]
.SH DESCRIPTION
Mutabor is a microtuner designed to be used via GUI. It retunes MIDI streams in real time. So it allows to design mutable tunings like adaptive Just Intonation (adaptive JI).

The commmand line is limited to open logic files in the Mutabor editor. Each logic file given will be opened.
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message
.TP
\fB\-\-verbose\fR
generate verbose log messages
.SH "SEE ALSO"
The full documentation is availlable in form of PDF files from the mutabor homepage at http://www.math.tu-dresden.de/~mutabor.

