mutaborGUI::GisInputFilterPanel
mutaborGUI::GisInputFilterPanel::GisInputFilterPanel(wxWindow *parent)
void mutaborGUI::GisInputFilterPanel::SetFromBox(int current, int min, int max)
TODO: set limits according to changes: min.max = max.value and max.min = min.value.
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::GetFilterPanel.
int mutaborGUI::GisInputFilterPanel::GetFromBox() const
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::ReadFilterPanel.
void mutaborGUI::GisInputFilterPanel::SetToBox(int current, int min, int max)
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::GetFilterPanel.
int mutaborGUI::GisInputFilterPanel::GetToBox() const
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::ReadFilterPanel.
void mutaborGUI::GisInputFilterPanel::SetFromStaff(int current, int min, int max)
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::GetFilterPanel.
int mutaborGUI::GisInputFilterPanel::GetFromStaff() const
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::ReadFilterPanel.
void mutaborGUI::GisInputFilterPanel::SetToStaff(int current, int min, int max)
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::GetFilterPanel.
int mutaborGUI::GisInputFilterPanel::GetToStaff() const
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::ReadFilterPanel.
void mutaborGUI::GisInputFilterPanel::SetRouteType(RouteType routetype)
References mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, UNREACHABLEC.
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::GetFilterPanel.
RouteType mutaborGUI::GisInputFilterPanel::GetRouteType()
References mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, UNREACHABLEC.
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::ReadFilterPanel.