mutaborGUI::MutDocManager
bool mutaborGUI::MutDocManager::ProcessEvent(wxEvent &event)
Extend event processing to search the view's event table.
Referenced by END_EVENT_TABLE.
virtual wxString mutaborGUI::MutDocManager::MakeFrameTitle(wxDocument *doc)
calculate the frame title
Referenced by END_EVENT_TABLE.
void mutaborGUI::MutDocManager::CmExecuteLogic(wxCommandEvent &event)
Referenced by END_EVENT_TABLE.
void mutaborGUI::MutDocManager::ConnectToApp(wxEvtHandler *handler)
Connect the event handling functions to the events.
handler Event handler that shall call the handling functions.
Referenced by END_EVENT_TABLE.
void mutaborGUI::MutDocManager::DisconnectFromApp(wxEvtHandler *handler)
Disconnect the event handling functions from the events.
handler Event handler that should have called the handling functions.
Referenced by END_EVENT_TABLE.
void mutaborGUI::MutDocManager::doConnect(C &Connect)
Referenced by END_EVENT_TABLE.