umstimmung.h
umstimmung_typ
eine Ankertaste absolut stimmen
struct umstimmung* list_of_umstimmungen
Wurzel der Umstimmungen.
Referenced by check_aktionen, check_konsistenz, check_logik_konsistenz, expandiere_logik, expandiere_name, mutabor_programm_einlesen.
struct umstimmung* tmp_umstimmung
Referenced by get_new_umstimmung, get_umstimmung_midi_out, get_umstimmung_umstimm_case_parameter, get_umstimmung_umstimm_case_zahl.
void init_umstimmung(char *name)
Erzeugt eine leere Umstimmung auf tmp_umstimmung.
Vorher wird jedoch die Umstimmungsliste list_of_umstimmungen durchsucht, ob name schon vorhanden ist. Gegebenenfalls wird ein fataler Fehler ausgeworfen. name Name der neu einzurichtenden Umstimmung. tmp_umstimmnug wird nicht gelöscht. Das muss gegebenenfalls extra erledigt werden.
References fatal_error, name, umstimmung::next, xmalloc.
Referenced by switch, yyparse.
void eintrage_parameterliste_in_umstimmung(void)
Hängt die letzte eingelesene Parameterliste an geeigneter Stelle in tmp_umstimmung ein.
References get_last_parameter_liste.
Referenced by switch, yyparse.
void get_new_umstimmung(void)
Hängt tmp_umstimmung an list_of_umstimmungen an.
Es wird immer die gesamte Liste durchsucht. Effektivität?
References umstimmung::next, tmp_umstimmung.
Referenced by switch, yyparse.
void get_umstimmung_taste_abs(enum argument_typ argument, double zahl_wert, char *parameter)
Baut tmp_umstimmung zu einer absoluten Tasten-Umstimmung aus.
Wird nicht-numerisch umgestimmt, und wirde der Parameter nicht definiert, wird ein fataler Fehler ausgelöst. argument Typ des Argumentes der Umstimmung zahl_wert Zahlenwert eines numerischen Argumentes. Wird ansonsten ignoriert. parameter Name des Parameters für die nicht numerische Umstimmung. Noch zu erledigenTypkonvertierung von double nach int prüfen
References umstimmung::argument, fatal_error, umstimmung::name, parameter, umstimmung::parameter_liste, parameter_nummer, umstimmung::u, umstimmung_taste_abs, zahl.
Referenced by switch, yyparse.
void get_umstimmung_taste_rel(enum argument_typ argument, double zahl_wert, char *parameter, char vorzeichen)
Baut tmp_umstimmung zu einer relativen Tasten-Umstimmung aus.
Wird nicht-numerisch umgestimmt, und wirde der Parameter nicht definiert, wird ein fataler Fehler ausgelöst. argument Typ des Argumentes der Umstimmung zahl_wert Zahlenwert eines numerischen Argumentes. Wird ansonsten ignoriert. parameter Name des Parameters für die nicht numerische Umstimmung. vorzeichen Rechenzeichen für die Umstimmung. Rechenzeichen = +/-, also Richtung? Noch zu erledigenTypkonvertierung von double nach int prüfen.
References umstimmung::argument, fatal_error, name, parameter, umstimmung::parameter_liste, parameter_nummer, umstimmung::u, umstimmung_taste_rel, zahl.
Referenced by switch, yyparse.
void get_umstimmung_breite_abs(enum argument_typ argument, double zahl_wert, char *parameter)
Baut tmp_umstimmung zu einer absoluten Änderung der Referenz-Breite aus.
Wird nicht-numerisch umgestimmt, und wirde der Parameter nicht definiert, wird ein fataler Fehler ausgelöst. argument Typ des Argumentes der Umstimmung zahl_wert Zahlenwert eines numerischen Argumentes. Wird ansonsten ignoriert. parameter Name des Parameters für die nicht numerische Umstimmung. Noch zu erledigenTypkonvertierung von double nauch int prüfen.
References umstimmung::argument, fatal_error, umstimmung::name, parameter, umstimmung::parameter_liste, parameter_nummer, umstimmung::u, umstimmung_breite_abs, zahl.
Referenced by switch, yyparse.
void get_umstimmung_breite_rel(enum argument_typ argument, double zahl_wert, char *parameter, char vorzeichen)
Baut tmp_umstimmung zu einer relativen Änderung der Referenz-Breite aus.
Wird nicht-numerisch umgestimmt, und wirde der Parameter nicht definiert, wird ein fataler Fehler ausgelöst. argument Typ des Argumentes der Umstimmung zahl_wert Zahlenwert eines numerischen Argumentes. Wird ansonsten ignoriert. parameter Name des Parameters für die nicht numerische Umstimmung. vorzeichen Rechenzeichen für die Umstimmung. Rechenzeichen = +/-, also Richtung? Noch zu erledigenTypkonvertierung von double nach int prüfen.
References umstimmung::argument, fatal_error, umstimmung::name, parameter, umstimmung::parameter_liste, parameter_nummer, umstimmung::u, umstimmung_breite_rel, zahl.
Referenced by switch, yyparse.
void init_umstimm_expression_list(void)
Setzt tmp_tonliste auf NULL.
Die Liste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_umstimmung_tonhoehe_veraendert(void)
Baut tmp_umstimmung zu einer Änderung der Tonhöhe aus.
Dabei wird tmp_tonliste als Tonliste der Veränderung eingehängt.
References tmp_tonliste, umstimmung_toene_veraendert, umstimmung::umstimmung_toene_veraendert.
Referenced by switch, yyparse.
void get_new_umstimm_expression(char *bezugston)
Fügt einen einfachen komplexen Ton ans Ende von tmp_tonliste an.
Dabei wird sowohl der Name des Tones als auch der des Bezugstones des komplexen Intervalles auf name gesetzt. Die komplexe Intervallliste wird leer initialisiert. bezugston Bezeichnung des Tones, der angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References ton::bezugston, name, ton::next, ton_komplex, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_new_umstimm_expression_positive(char *bezugston)
Fügt einen komplexen Ton ans Ende von tmp_tonliste an.
Dabei wird sowohl der Name des Tones als auch der des Bezugstones des komplexen Intervalles auf name gesetzt. Als komplexe Intervallliste wird die letzte eingelesene eingehängt. bezugston Bezeichnung des Tones, der angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References ton::bezugston, get_last_komplex_intervall, name, ton::next, ton_komplex, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_new_umstimm_expression_negative(char *bezugston)
Fügt einen komplexen Ton ans Ende von tmp_tonliste an.
Dabei wird sowohl der Name des Tones als auch der des Bezugstones des komplexen Intervalles auf name gesetzt. Als komplexe Intervallliste wird die letzte eingelesene eingehängt. Diese wird jedoch vorher invertiert. bezugston Bezeichnung des Tones, der angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References ton::bezugston, komplex_intervall::faktor, get_last_komplex_intervall, name, ton::next, komplex_intervall::next, ton_komplex, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_abs(void)
Baut tmp_umstimmung zu einer absoluten Änderung der Wiederholungsvorschrift aus.
Dabei wird die letzte eingelesene komplexe Intervallliste verwendet.
References get_last_komplex_intervall, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_abs_negative(void)
Baut tmp_umstimmung zu einer absoluten Änderung der Wiederholungsvorschrift aus.
Dabei wird die letzte eingelesene komplexe Intervallliste verwendet. Diese wird jedoch vorher invertiert. Ist sie leer, wird ein fataler Fehler ausgelöst.
References komplex_intervall::faktor, fatal_error, get_last_komplex_intervall, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_rel_positive(void)
Baut tmp_umstimmung zu einer relativen änderung der Wiederholungsvorschrift aus.
Dabei wird die letzte eingelesene komplexe Intervallliste verwendet.
References get_last_komplex_intervall, umstimmung_wiederholung_rel, umstimmung::umstimmung_wiederholung_rel.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_rel_negative(void)
Baut tmp_umstimmung zu einer relativen Änderung der Wiederholungsvorschrift aus.
Dabei wird die letzte eingelesene komplexe Intervallliste verwendet. Diese wird jedoch vorher invertiert. Ist sie leer, wird ein fataler Fehler ausgelöst.
References komplex_intervall::faktor, get_last_komplex_intervall, umstimmung_wiederholung_rel, umstimmung::umstimmung_wiederholung_rel.
Referenced by switch, yyparse.
void get_umstimmung_umstimmungs_bund(void)
Baut tmp_umstimmung zu einem Umstimmungsbund aus.
Dazu wird die letzte eingelesene Aktionsliste verwendet. Falls ein Parameter darin nicht definiert ist, wird ein fataler Fehler ausgelöst.
References aktion_aufruf, aktions_liste::aktion_aufruf, argument_liste::argument, argument::argument_typ, fatal_error, get_last_aktions_liste, name, argument_liste::next, aktions_liste::next, parameter, argument::parameter, parameter_nummer, argument::u, aktions_liste::u, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund.
Referenced by switch, yyparse.
void get_umstimmung_midi_out(void)
Baut tmp_umstimmung zu einer MIDI-Ausgabe aus.
Dabei wird die letzte eingelesene Ganzzahlen-Liste verwendet.
References get_last_integersequenz, tmp_umstimmung, umstimmung_midi_out, umstimmung::umstimmung_midi_out.
Referenced by switch, yyparse.
int umstimmungs_list_laenge(struct umstimmung *list)
Zählen der Elemente einer einfach verketteten Umstimmungsliste.
list Liste der Umstimmungen Anzahl der Elemente von list
References umstimmung::next, umstimmungs_list_laenge.
Referenced by check_konsistenz, mutabor::BoxClass::Compile, umstimmungs_list_laenge.
struct umstimmung* get_umstimmung(char *name, struct umstimmung *liste)
Sucht eine Umstimmung in einer Umstimmungsliste.
name Name der gesuchten Umstimmung liste Liste der Umstimmungen, in der die Umstimmung gesucht wird NULL falls Umstimmung nicht in liste Umstimmung sonst.
References get_umstimmung, umstimmung::name, umstimmung::next.
Referenced by check_aktionen, check_konsistenz, check_logik_konsistenz, check_umstimmungs_konsistenz, expandiere_logik, expandiere_name, get_umstimmung.
void check_umstimmungs_konsistenz(void)
References aktion_aufruf, aktions_liste::aktion_aufruf, argument_list_laenge, case_label_enthalten_in_case_liste, check_komplex_intervall, fatal_error, get_logik, get_ton, get_umstimmung, list_of_logiken, list_of_toene, list_of_tonsysteme, ton::name, umstimmung::name, ton::next, aktions_liste::next, umstimmung::next, parameter_list_laenge, parser_get_tonsystem, ton_absolut, ton::ton_komplex, ton::u, aktions_liste::u, umstimmung::u, umstimmung_breite_abs, umstimmung_breite_rel, umstimmung_taste_abs, umstimmung_taste_rel, umstimmung_toene_veraendert, umstimmung::umstimmung_toene_veraendert, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, umstimmung::umstimmung_wiederholung_rel.
Referenced by check_konsistenz.