GSP_File.cpp
mutChar CurrentLine[GSP_MAX_LINE][GSP_MAX_LINE]
Referenced by DoError, GetSep, GspParse, ReadLong, ReadNewLine, ReadNote, ReadParaStr, ReadTag, SavePos, takesep.
size_t CurrentPos
Referenced by DoError, DoParse, GetSep, GspParse, ReadLong, ReadNewLine, ReadNote, ReadParaNumber, ReadParaStr, ReadTag, SavePos, takesep.
int Eof
Referenced by DoParse, GetSep, GspParse, ReadNewLine, ReadParaStr.
mutTextStream* File
Referenced by CloseFile, OpenFile, ReadNewLine.
int OpenFile(const mutString &Name)
References File, mutStreamBad.
Referenced by GspParse.
int CloseFile()
References File.
Referenced by GspParse.
int ReadNewLine()
References CurrentLine, CurrentPos, Eof, File, GSP_MAX_LINE, GspCurrentLineNr, mutEmptyString, mutStreamBad, mutStreamEOF.
Referenced by GetSep, ReadParaStr.