mutabor::Track
typedef std::vector<uint8_t> mutabor::Track::base
mutint64 mutabor::Track::Time
Referenced by ResetPosition.
timing_params mutabor::Track::timing
Referenced by getMidiIickSignature, ResetPosition, SetQuarterDuration.
size_t mutabor::Track::position
Referenced by GetPosition, ResetPosition, Stop.
mutint64 mutabor::Track::current_delta
Referenced by ResetPosition, Stop, UpdateDelta.
mutint64 mutabor::Track::remaining_delta
Referenced by GetDelta, PassDelta, ResetDelta, ResetPosition, SetQuarterDuration, Stop, UpdateDelta.
uint8_t mutabor::Track::running_status
Referenced by ResetPosition.
bool mutabor::Track::running_sysex
Referenced by FixSysEx, ResetPosition, SendSysEx, SendSysExCont, Stop.
int mutabor::Track::sysex_id
Referenced by FixSysEx, SendSysExCont, Stop.
mutabor::Track::Track()
References c_str, DEBUGLOG.
mutabor::Track::Track(timing_params p)
References c_str, DEBUGLOG.
mutabor::Track::~Track()
size_t mutabor::Track::GetPosition()
References position.
void mutabor::Track::ResetPosition(size_t p, bool resettiming=false)
References c_str, current_delta, DEBUGLOG, position, remaining_delta, running_status, running_sysex, mutabor::timing_params::set_quarter_duration, Time, timing.
Referenced by Reset.
void mutabor::Track::ResetDelta()
References DEBUGLOG, remaining_delta.
void mutabor::Track::Reset()
References ResetPosition.
Referenced by mutabor::MidiFileOutputProvider::Open.
mutint64 mutabor::Track::GetDelta()
References remaining_delta.
mutint64 mutabor::Track::ReadDelta()
References DEBUGLOG, MUTABOR_NO_DELTA, mutASSERT.
mutint64 mutabor::Track::PassDelta(mutint64 p)
References DEBUGLOG, MUTABOR_NO_DELTA, mutASSERT, remaining_delta.
mutint64 mutabor::Track::UpdateDelta()
References current_delta, DEBUGLOG, MUTABOR_NO_DELTA, mutASSERT, remaining_delta.
void mutabor::Track::WriteDelta()
References mutabor::CurrentTime, DEBUGLOG, mutabor::CurrentTimer::Get, mutASSERT, mutint64.
Referenced by MidiOut, SendMeta, SendSysExCont.
void mutabor::Track::SetQuarterDuration(mutint64 new_duration, bool update=false, mutint64 offset=0)
References DEBUGLOG, MUTABOR_NO_DELTA, mutint64, remaining_delta, mutabor::timing_params::set_quarter_duration, timing, mutabor::timing_params::update_duration_midi.
std::pair<uint8_t,uint8_t> mutabor::Track::getMidiIickSignature()
References mutabor::timing_params::get_MIDI_tick_signature, timing.
Referenced by mutabor::MidiFileOutputProvider::Save.
uint32_t mutabor::Track::ReadInt()
References _mutN.
Track::base mutabor::Track::ReadMessage()
References _mut, mutabor::midi::get_data_size, mutabor::midi::META, mutabor::midi::META_SEQUENCER_SPECIFIC, mutASSERT, mutabor::midi::reset_running_status, mutabor::midi::store_running_status, mutabor::midi::SYSEX_END, mutabor::midi::SYSEX_START.
void mutabor::Track::WriteNumber(size_t count)
References _mutN.
Referenced by FixSysEx, SendMeta, SendSysExCont, WriteLongChunk.
void mutabor::Track::WriteLength(std::ostream &os, size_t l)
void mutabor::Track::MidiOut(uint8_t c1, uint8_t c2, uint8_t c3)
References FixSysEx, WriteDelta.
Referenced by mutabor::MidiFileOutputProvider::RawMsg.
void mutabor::Track::MidiOut(uint8_t c1, uint8_t c2)
References FixSysEx, WriteDelta.
void mutabor::Track::MidiOut(uint8_t c1)
References FixSysEx, WriteDelta.
void mutabor::Track::WriteLongChunk(i from, i to, size_t offset=0)
References WriteNumber.
Referenced by SendMeta, SendSysExCont.
void mutabor::Track::SendMeta(uint8_t type, i from, i to, mutint64 delta=MUTABOR_NO_DELTA)
References FixSysEx, mutabor::midi::META, MUTABOR_NO_DELTA, mutabor::midi::STARTBYTE_MASK, UNREACHABLEC, WriteDelta, WriteLongChunk, WriteNumber.
void mutabor::Track::SendSysEx(i from, i to, mutint64 delta=MUTABOR_NO_DELTA)
References FixSysEx, running_sysex, SendSysExCont, mutabor::midi::STARTBYTE_MASK, mutabor::midi::SYSEX_END, UNREACHABLEC.
Referenced by mutabor::MidiFileOutputProvider::SendSysEx.
void mutabor::Track::SendSysExCont(i from, i to, mutint64 delta=MUTABOR_NO_DELTA, size_t offset=0)
References _mutN, MUTABOR_NO_DELTA, running_sysex, mutabor::midi::SYSEX_END, sysex_id, mutabor::midi::SYSEX_START, WriteDelta, WriteLongChunk, WriteNumber.
Referenced by SendSysEx.
void mutabor::Track::FixSysEx()
References running_sysex, mutabor::midi::SYSEX_END, sysex_id, WriteNumber.
Referenced by MidiOut, SendMeta, SendSysEx.
void mutabor::Track::Save(std::ostream &os)
References mutabor::midi::META, mutabor::midi::META_END_OF_TRACK, mutabor::midi::META_SET_TEMPO, mutabor::midi::META_TIME_SIGNATURE, WriteLength.
Referenced by mutabor::MidiFileOutputProvider::Close, mutabor::MidiFileOutputProvider::Save.
void mutabor::Track::Stop()
References current_delta, MUTABOR_NO_DELTA, position, remaining_delta, running_sysex, sysex_id.
mutabor::Track::operator std::string() const
References mutabor::str.
std::string mutabor::Track::c_str() const
Referenced by ResetPosition, Track.