ausloeser.c
struct ausloeser* tmp_ausloeser
Globaler Zwischenspeicher für auslösende Ereignisse.
Referenced by get_last_ausloeser.
struct harmonie_ereignis* first_harmonie[MAX_BOX][MAX_BOX]
Liste der globalen auslösenden Harmonieen.
Referenced by mutabor_tabellen_generator.
struct harmonie_ereignis** last_global_harmonie[MAX_BOX][MAX_BOX]
Letztes Element der globalen auslösenden Harmonien.
Referenced by mutabor_tabellen_generator.
struct harmonie_ereignis** first_lokal_harmonie
Liste der lokalen auslösenden Harmonien.
Referenced by expandiere_logik, mutabor_tabellen_generator.
struct keyboard_ereignis* first_keyboard[MAX_BOX][MAX_BOX]
Liste der globalen auslösenden Tastenereignissen.
Referenced by mutabor_tabellen_generator, boxTest::test_init.
struct keyboard_ereignis** last_global_keyboard[MAX_BOX][MAX_BOX]
Letztes Element der globalen auslösenden Tastenereignissen.
Referenced by mutabor_tabellen_generator, boxTest::test_init.
struct keyboard_ereignis** first_lokal_keyboard
Liste der lokalen auslösenden Tastenereignissen.
Referenced by expandiere_logik, mutabor_tabellen_generator.
struct midi_ereignis* first_midi[MAX_BOX][MAX_BOX]
Liste der globalen auslösenden MIDI-Ereignissen.
Referenced by mutabor_tabellen_generator, boxTest::test_init.
struct midi_ereignis** last_global_midi[MAX_BOX][MAX_BOX]
Letztes Element der globalen auslösenden MIDI-Ereignissen.
Referenced by mutabor_tabellen_generator, boxTest::test_init.
struct midi_ereignis** first_lokal_midi
Liste der lokalen auslösenden MIDI-Ereignissen.
Referenced by expandiere_logik, mutabor_tabellen_generator.
void init_ausloeser(void)
Setzt Liste auslösender Ereignisse auf NULL.
Die Liste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
struct ausloeser* get_last_ausloeser(void)
Gibt Wurzelelement von tmp_ausloeser zurück.
References tmp_ausloeser.
Referenced by get_new_anweisung, get_new_logik.
void get_ausloeser_default(void)
Markiert tmp_ausloeser als Standard-Auslöser.
References ausloeser_default, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_harmonie(void)
Deklariert tmp_ausloeser als Harmonie-Auslöser und setzt die Werte aus dem Zwischenspeicher.
References ausloeser_harmonie, tmp_nach_taste, tmp_name, tmp_vor_taste, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_harmonie_form(void)
Deklariert tmp_ausloeser als Harmonie-Auslöser und setzt die Werte aus dem Zwischenspeicher.
References ausloeser_harmonie_form, tmp_nach_taste, tmp_name, tmp_vor_taste, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_taste(char *name)
Deklariert tmp_ausloeser als Tasten-Auslöser.
Ist die Taste nicht definiert, wird ein fataler Fehler ausgelöst. name Name der auslösenden Taste
References ausloeser_taste, fatal_error, name, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_midi_in(void)
Deklariert tmp_ausloeser als MIDI-Sequenz.
Dafür wird die letzte eingelesene Ganzzahlen-Folge verwendet.
References ausloeser_midi_in, get_last_integersequenz, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void print_ausloeser(struct ausloeser *this_)
Gibt einen Auslöser auf der Standard-Ausgabe aus.
this_ Auslöser.
References ausloeser_default, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser_taste, ausloeser::ausloeser_taste, ausloeser::ausloeser_typ, fatal_error, print_integersequenz, ausloeser::u.
Referenced by mutabor_programm_einlesen.
void check_ausloeser(struct ausloeser *ausloeser, char *name)
Testet einen Auslöser auf Zulässigkeit.
Wird eine nicht zulässige oder erreichbare Konfiguration gefunden, wird je nach Situation ein fataler Fehler oder eine Compiler-Warnung ausgelöst. ausloeser Auslöser, der geprüft werden soll name Name für Meldungen
References ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser::ausloeser_typ, compiler_warning, enthalten_in_tastenliste, fatal_error, get_harmonie, list_of_harmonien, midiliste::midi_code, midiliste::next, harmonie::tastenliste, ausloeser::u.
Referenced by check_konsistenz, check_logik_konsistenz.
void insert_in_globale_liste(int instrument, struct logik *lauf)
Fügt die auslösende Harmonien, Taste bzw.
das Midiereignis der Logik in die entsprechenede globale Liste eines Instrumentes ein. instrument Instrument, für das das Ereignis eingefügt werden soll. lauf Logik, deren Auslöser eingefügt werden soll.
References keyboard_ereignis::aktion, midi_ereignis::aktion, harmonie_ereignis::aktion, logik::ausloeser, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser_taste, create_midi_scan_liste, expand_pattern, fatal_error, midi_ereignis::first_pos, harmonie_ereignis::ist_harmonieform, harmonie_ereignis::nachtaste, name, logik::name, keyboard_ereignis::next, midi_ereignis::next, harmonie_ereignis::next, harmonie_ereignis::pattern, midi_ereignis::scan_pos, keyboard_ereignis::the_logik_to_expand, midi_ereignis::the_logik_to_expand, harmonie_ereignis::the_logik_to_expand, ausloeser::u, harmonie_ereignis::vortaste, xmalloc.
Referenced by expand_decition_tree, mutabor_tabellen_generator.
struct harmonie_ereignis** get_ende_harmonie(struct harmonie_ereignis **lauf)
Liefert einen Zeiger auf den Nachfolge-Zeiger des letzten Elementes einer Harmonie-Ereignis-Liste.
lauf Zeiger auf die Wurzel einer einfach verketteten Liste von Harmonieereignissen.
References get_ende_harmonie, harmonie_ereignis::next.
Referenced by expand_decition_tree, get_ende_harmonie, mutabor_tabellen_generator.
struct keyboard_ereignis** get_ende_keyboard(struct keyboard_ereignis **lauf)
Liefert einen Zeiger auf den Nachfolge-Zeiger des letzten Elementes einer Tasten-Ereignis-Liste.
lauf Zeiger auf die Wurzel einer einfach verketteten Liste von Tastenereignissen.
References get_ende_keyboard, keyboard_ereignis::next.
Referenced by expand_decition_tree, get_ende_keyboard, mutabor_tabellen_generator.
struct midi_ereignis** get_ende_midi(struct midi_ereignis **lauf)
Liefert einen Zeiger auf den Nachfolge-Zeiger des letzten Elementes einer MIDI-Ereignis-Liste.
lauf Zeiger auf die Wurzel einer einfach verketteten Liste von MIDI-Ereignissen.
References get_ende_midi, midi_ereignis::next.
Referenced by expand_decition_tree, get_ende_midi, mutabor_tabellen_generator.
void insert_in_lokale_liste(int instrument, struct anweisung *lauf, char *name_der_logik)
Fügt die auslösende Harmonien, Taste bzw.
das Midiereignis der Logik in die entsprechenede lokale Liste eines Instrumentes ein. instrument Instrument, für das das Ereignis eingefügt werden soll. lauf Anweisung, deren Auslöser eingefügt werden soll. name_der_logik Name der Logik, zu der die Anweisung gehört.
References anweisung::aktion, keyboard_ereignis::aktion, midi_ereignis::aktion, harmonie_ereignis::aktion, anweisung::ausloeser, ausloeser_default, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser_taste, create_midi_scan_liste, expand_aktions_liste, expand_pattern, fatal_error, midi_ereignis::first_pos, harmonie_ereignis::ist_harmonieform, harmonie_ereignis::nachtaste, name, keyboard_ereignis::next, midi_ereignis::next, harmonie_ereignis::next, harmonie_ereignis::pattern, midi_ereignis::scan_pos, start_parameter_liste, ausloeser::u, harmonie_ereignis::vortaste, xmalloc.
Referenced by expand_decition_tree, expandiere_logik, mutabor_tabellen_generator.
void expandiere_in_globale_liste(void)
Expandiert die Auslösenden Ereignisse aller angesammeldten Logiken in die globale Liste.
References midi_ereignis::aktion, expandiere_logik, MAX_BOX, midi_ereignis::next, midi_ereignis::the_logik_to_expand.
Referenced by expand_decition_tree, mutabor_tabellen_generator.