debug.cpp
HEADERFILENAME
HEADERFILENAME_PRECOMPILED
Noch zu erledigenmove thread.h into src/kernel
DEBUGFLAG
typedef std::list<ptrlist_item> ptrlist
ptrlist debug_save_pointers
class consoleinit g_consoleinit
void mutabor_debug_lock()
References mutabor::debugmutex.
void mutabor_debug_unlock()
References mutabor::debugmutex.
void debug_destroy_class(void *ptr, std::string file, int l)
References mutASSERT.
Referenced by mutabor::TRouteClass< I, O, B >::Destroy, mutabor::BoxClass::Destroy, mutabor::CommonTypedDeviceAPI< T, P, L >::Destroy.
void debug_destruct_class(void *ptr)
References mutASSERT.
Referenced by mutabor::BoxClass::~BoxClass, mutabor::CommonTypedDeviceAPI< T, P, L >::~CommonTypedDeviceAPI, mutabor::TRouteClass< I, O, B >::~TRouteClass.
void debug_print_pointers()
Referenced by IMPLEMENT_APP.
bool debug_is_all_deleted()
Referenced by IMPLEMENT_APP.
static void mutabor_backtrace_error_callback(void *data, const char *msg, int errnum)
Referenced by mutabor_backtrace::mutabor_backtrace, print_stacktrace, mutabor_backtrace::~mutabor_backtrace.
static int mutabor_backtrace_print_callback(void *data, uintptr_t pc, const char *filename, int lineno, const char *function)
Referenced by print_stacktrace, mutabor_backtrace::~mutabor_backtrace.
int mutabor_backtrace_simple_print_callback(void *data, uintptr_t pc)
Referenced by print_stacktrace.
void print_stacktrace(bool flag)
References mutabor_backtrace_error_callback, mutabor_backtrace_print_callback, mutabor_backtrace_simple_print_callback.
Referenced by mutabor::BoxClass::AppendToBoxList, mutabor::CommonFileInputDevice::exception_error.
static int mutabor_save_backtrace_callback(void *data, uintptr_t pc)
Referenced by mutabor_backtrace::mutabor_backtrace.
void MutInitConsole()
Referenced by consoleinit::consoleinit.
std::string StreamToHex(std::istream &buf)
Referenced by OutputMidiFileTest::CheckOut.