mutabor::OutputMidiFile
typedef CommonMidiOutput<MidiFileOutputProvider,CommonFileOutputDevice> mutabor::OutputMidiFile::base
friend class MidiFileFactory
virtual mutabor::OutputMidiFile::~OutputMidiFile()
void mutabor::OutputMidiFile::Save(tree_storage &config)
Save current device settings in a tree storage.
config (tree_storage) storage class, where the data will be saved.
References bending_range, mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::Write.
Referenced by OutputMidiFileTest::CheckOut.
void mutabor::OutputMidiFile::Save(tree_storage &config, const RouteClass *route)
Save route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route ) Route whos data shall be saved.
References mutabor::TRouteClass< I, O, B >::GetOutputFrom, mutabor::TRouteClass< I, O, B >::GetOutputTo, mutabor::tree_storage::GetPath, mutASSERT, mutabor::TRouteClass< I, O, B >::OutputAvoidDrumChannel, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent, mutabor::tree_storage::Write.
void mutabor::OutputMidiFile::Load(tree_storage &config)
Load current device settings from a tree storage.
config (tree_storage) storage class, where the data will be loaded from.
References bending_range, mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::Read.
void mutabor::OutputMidiFile::Load(tree_storage &config, RouteClass *route)
Loade route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route ) Route whos data shall be loaded.
References _mut, mutabor::tree_storage::GetPath, mutASSERT, mutabor::TRouteClass< I, O, B >::OutputAvoidDrumChannel, mutabor::tree_storage::Read, mutabor::hidden::runtime_error, mutabor::TRouteClass< I, O, B >::SetOutputFrom, mutabor::TRouteClass< I, O, B >::SetOutputTo, mutabor::str, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent, mutabor::hidden::warning.
void mutabor::OutputMidiFile::Close()
Referenced by SetName, OutputMidiFileTest::testBatchPlay1, OutputMidiFileTest::testNoteOnOff.
virtual void mutabor::OutputMidiFile::SetName(const std::string &s)
References Close, mutabor::Device::IsOpen, mutabor::Device::Name, mutabor::OutputDeviceClass::Open.
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::readDialog, OutputMidiFileTest::setUp.
virtual DevType mutabor::OutputMidiFile::GetType() const
References mutabor::DTMidiFile.
virtual int mutabor::OutputMidiFile::GetMaxChannel() const
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::GetFilterPanel.
virtual int mutabor::OutputMidiFile::GetMinChannel() const
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::GetFilterPanel.
virtual std::string mutabor::OutputMidiFile::GetTypeName() const
References _mutN.
mutabor::OutputMidiFile::operator std::string() const
References bending_range, mutabor::str.
void mutabor::OutputMidiFile::Save(std::ostream &os)
References mutabor::CommonMidiOutput< MidiFileOutputProvider, CommonFileOutputDevice >::Out, mutabor::MidiFileOutputProvider::Save.
mutabor::OutputMidiFile::OutputMidiFile()
mutabor::OutputMidiFile::OutputMidiFile(const std::string name, int id=-1, int bendingRange=2)
virtual void mutabor::OutputMidiFile::do_Gis(GisToken *token, char turn)
virtual void mutabor::OutputMidiFile::do_AddTime(frac time)