mutaborGUI::MutBoxShape
MutBoxIconShape* mutaborGUI::MutBoxShape::m_icon
Referenced by SetBox.
wxSizer* mutaborGUI::MutBoxShape::channels
Referenced by Detach, GetChannels.
mutabor::Box mutaborGUI::MutBoxShape::box
Referenced by Add, DoLeftDblClick, GetBox, Remove, Replace.
wxSizerFlags mutaborGUI::MutBoxShape::sizerFlags
Referenced by GetSizerFlags, SetSizerFlags.
mutaborGUI::MutBoxShape::MutBoxShape()
mutaborGUI::MutBoxShape::MutBoxShape(wxWindow *parent, wxWindowID wid, mutabor::Box &b)
References Create.
virtual mutaborGUI::MutBoxShape::~MutBoxShape()
bool mutaborGUI::MutBoxShape::Create(wxWindow *parent, wxWindowID wid)
References mutaborGUI::MutBoxIconShape::Create.
Referenced by mutaborGUI::NewMutBoxShape::Create, MutBoxShape.
bool mutaborGUI::MutBoxShape::Create(wxWindow *parent, wxWindowID wid, mutabor::Box &b)
void mutaborGUI::MutBoxShape::DoLeftDblClick()
References _, box, mutabor::Box0, mutabor::BoxFactory::Create, mutaborGUI::DebugCheckRoutes, MutIconShapeClass< T >::Fit, mutabor::BoxClass::GetBox, mutaborGUI::BoxDlg::GetBoxNumber, mutaborGUI::BoxDlg::GetBoxType, mutabor::BoxClass::IDTypeFile, mutaborGUI::MutBoxIconShape::Layout, mutaborGUI::LogicOn, mutASSERT, readDialog, TRACE, UNREACHABLEC.
Referenced by CmLeftDblClick.
void mutaborGUI::MutBoxShape::GotFocus()
References mutaborGUI::SetCurrentBox.
bool mutaborGUI::MutBoxShape::SetBackgroundColour(const wxColour &colour)
References mutASSERT.
void mutaborGUI::MutBoxShape::CmMoveIcon(wxCommandEvent &event)
Move the box in the box list and update the GUI according to the new order.
Move the box in the box and update the GUI according to the new order.This function provides the event handler that is called from the GUI. event wxCommandEvent containing the request event wxCommandEvent containing the request
References UNREACHABLEC.
void mutaborGUI::MutBoxShape::LeftDblClickEvent(wxMouseEvent &event)
Get a double click and prepare for execution of the command.
Since programs might produce segmentation faults when the object is deleted during processing of mouse events, we send us a new event using the event queue.
References mutaborGUI::CM_LEFT_DOUBLE_CLICK.
void mutaborGUI::MutBoxShape::CmLeftDblClick(wxCommandEvent &event)
Process a double click.
Since programs might produce segmentation faults when the object is deleted during processing of mouse events, we send us a new event using the event queue.
References DoLeftDblClick, mutUnused.
void mutaborGUI::MutBoxShape::OnKeyDown(wxKeyEvent &event)
BoxDlg * mutaborGUI::MutBoxShape::ShowBoxDialog() const
Constructs the box configuration dialog.
Noch zu erledigenuse value “unknown” for dynamic dialog creation
References mutaborGUI::BoxDlg::GetRouteWindow, mutASSERT.
void mutaborGUI::MutBoxShape::InitializeDialog(BoxDlg *dlg) const
References mutabor::Box0, mutabor::BoxClass::GetNextFreeBox, mutASSERT, mutabor::NoBox, mutaborGUI::BoxDlg::SetBoxNumber, mutaborGUI::BoxDlg::SetBoxType.
MutBoxChannelShape * mutaborGUI::MutBoxShape::AddChannel(RoutePanel *panel)
References mutabor::connect, mutabor::RouteFactory::Create, mutabor::hidden::GetChannels, mutASSERT, mutaborGUI::MutBoxChannelShape::ReadPanel.
virtual void mutaborGUI::MutBoxShape::Add(mutabor::Box &b)
add a box
References box, SetBox, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::GUIRouteBase::Add, mutaborGUI::MutRouteWnd::AddRoute, mutaborGUI::connect, mutaborGUI::connect_device_shape.
virtual bool mutaborGUI::MutBoxShape::Replace(mutabor::Box oldbox, mutabor::Box newbox)
replace a box
References box, SetBox, TRACEC, UNREACHABLEC.
virtual bool mutaborGUI::MutBoxShape::Remove(mutabor::Box b)
remove a box
References box, SetBox, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::disconnect.
MutBoxChannelShape * mutaborGUI::MutBoxShape::Add(MutBoxChannelShape *channel)
References mutaborGUI::MutBoxChannelShape::Add, DEBUGLOG, mutASSERT.
bool mutaborGUI::MutBoxShape::Remove(MutBoxChannelShape *shape)
bool mutaborGUI::MutBoxShape::HasChannel(const mutabor::Route &route)
References mutaborGUI::MutBoxChannelShape::GetRoute, mutASSERT.
void mutaborGUI::MutBoxShape::AddPossibleOutput(MutOutputDeviceShape *device)
References mutabor::connect, mutASSERT.
void mutaborGUI::MutBoxShape::DrawLines(wxDC &dc, wxWindow *paintingWindow)
References DEBUGLOG, mutaborGUI::MutBoxChannelShape::DrawLines, mutASSERT.
Referenced by mutaborGUI::MutRouteWnd::OnDraw.
bool mutaborGUI::MutBoxShape::Detach(wxWindow *window)
References UNREACHABLEC.
Referenced by Detach.
virtual bool mutaborGUI::MutBoxShape::Detach(wxSizer *sizer)
References channels, Detach.
virtual bool mutaborGUI::MutBoxShape::Detach(int index)
References channels, Detach.
bool mutaborGUI::MutBoxShape::replaceSelfBy(MutBoxShape *newshape)
References mutASSERT, UNREACHABLEC.
bool mutaborGUI::MutBoxShape::DeleteBox()
References mutaborGUI::MutBoxChannelShape::GetRoute, mutASSERT.
bool mutaborGUI::MutBoxShape::readDialog(BoxDlg *boxdlg)
References mutabor::Box0, mutabor::connect, mutabor::BoxClass::GetBox, mutaborGUI::BoxDlg::GetBoxNumber, mutaborGUI::BoxDlg::GetBoxType, mutabor::BoxClass::GetOrCreateBox, mutaborGUI::BoxDlg::GetRouteWindow, mutabor::GmnBox, mutabor::BoxClass::IDTypeFile, mutASSERT, mutabor::NoBox, mutaborGUI::SetCurrentBox.
Referenced by DoLeftDblClick.
virtual bool mutaborGUI::MutBoxShape::CanHandleType(int type)
mutabor::Box mutaborGUI::MutBoxShape::GetBox() const
References box.
Referenced by mutaborGUI::Check, mutaborGUI::connect, mutaborGUI::disconnect, mutaborGUI::reconnect.
wxSizer* mutaborGUI::MutBoxShape::GetChannels() const
References channels.
Referenced by mutaborGUI::Check, mutaborGUI::disconnect.
void mutaborGUI::MutBoxShape::BoxChanged()
Updates the Display of the Box shape after a change of the box that must be honoured by this shape.
References _, mutaborGUI::BoxData::GetBackgroundColour, mutaborGUI::BoxData::GetTextColour, mutabor::GmnBox, mutabor::NewBox, mutabor::NoBox, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::BoxData::set_routefile_id.
static void mutaborGUI::MutBoxShape::SetSizerFlags(wxSizerFlags flags)
References sizerFlags.
static const wxSizerFlags& mutaborGUI::MutBoxShape::GetSizerFlags()
References sizerFlags.
virtual void mutaborGUI::MutBoxShape::MoveBox(int count)
Move the box in the box list and update the GUI according to the new order.
count number of entries the device should be moved up. Negative values indicate downwards direction.
void mutaborGUI::MutBoxShape::SetBox(bool nullify=true)
References _, m_icon, MutIconShapeClass< T >::SetLabel.
Referenced by Add, Remove, Replace.
void mutaborGUI::MutBoxShape::SetBox(mutabor::Box &b, bool layout=true)