midicalc.h
DOUBLE_TO_LONG
Referenced by expand_tonliste, expandiere_tonsystem, expandiere_umstimmung.
FREQUENZ_TO_MIDI
Frequenz nach Midi umrechnen.
Es gilt: \[0.05776226504666210908=\ln\left(\sqrt[12]2\right)\]. x Freqenz erweiterte Midi-Tastennummer
Referenced by expand_tonliste, expandiere_tonsystem.
FAKTOR_TO_MIDI
Faktor nach Midi umrechnen.
Es gilt: \[17.31234049066756089=\frac{12}{\ln 2}\]. x Faktor erweiterte Midi-Tastennummer
Referenced by expand_tonliste, expandiere_tonsystem, expandiere_umstimmung.
void init_integersequenz(void)
Setzt Integersequenz auf NULL.
Die Integersequenz wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_new_integer_in_integersequenz(int wert)
Hängt einen Wert an list_of_integers an.
wert Anzuhängende ganze Zahl Es wird immer die gesamte Liste durchsucht. Effektivität?
References midiliste::midi_code, midiliste::next, xmalloc.
Referenced by switch, yyparse.
int midi_list_laenge(struct midiliste *list)
Zählen der Elemente einer einfach verketteten MIDI-Liste.
list MIDI-Liste Anzahl der Elemente von list
References midi_list_laenge, umstimmung::next.
Referenced by create_midi_scan_liste, midi_list_laenge, mutabor::BoxClass::MidiOut.
struct midiliste* get_last_integersequenz(void)
Gibt die Wurzel von list_of_integers zurück.
References list_of_integers.
Referenced by get_ausloeser_midi_in, get_new_aktion_midi_out_element, get_umstimmung_midi_out.
int* create_midi_scan_liste(struct midiliste *lauf)
Wandelt eine einfach verkettete MIDI-Liste in ein Ganzzahlen-(int)-Feld um.
Ganzzahlenfeld. Der Letzte Eintrag enthält quasi als Wächter den Wert -1.
References midi_list_laenge, xcalloc, midiliste::next, midiliste::midi_code.
Referenced by insert_in_globale_liste, insert_in_lokale_liste.
void print_integersequenz(struct midiliste *this_)
Gibt eine Integersequenz aus.
this_ Sequenz
References midiliste::midi_code, print_integersequenz, midiliste::next.
Referenced by print_integersequenz, print_ausloeser.