Interpre.h
MU32_INTERPRE_H
MU32_INTERPRE_H_PRECOMPILED
SYNTHESIZER_TYP_KEINER
SYNTHESIZER_TYP_FB01
SYNTHESIZER_TYP_MULTI16
SYNTHESIZER_TYP_GIS
ton_einstell_typ
interpreter_parameter_indices
aufruf_typ
is_harmonic_form_collection
typedef long mutabor_interval
typedef mutabor_interval mutabor_tone
typedef struct TSYS tone_system
typedef struct PTRN PATTERNN
int laufzeit_meldungen_erlaubt
void message_tasten_liste(void)
double mutabor_convert_interval_to_pitch(mutabor_interval interval)
Convert an interval to half tone based pitch according to MIDI pitch numbers.
The microtonal part is retained in the double return value. interval Interval in the internal representation of Mutabor. a double value that represents the interval. a half tone is represented as 1.00, and an octave as 12.00.
Referenced by execute_aktion, mutabor::BoxClass::GetToneSystem, mutabor_convert_tone_to_pitch.
mutabor_interval mutabor_convert_pitch_to_interval(double interval)
Convert an interval from half tone based pitch according to MIDI pitch numbers.
The microtonal part can be given in the double value. interval a double value that represents the interval. a semitone is represented as 1.00, and an octave as 12.00 interval in the internal representation of Mutabor.
Referenced by expand_tonliste, expandiere_tonsystem, expandiere_umstimmung, mutabor_convert_pitch_to_tone, mutabor_reset_box.
double mutabor_convert_tone_to_pitch(mutabor_tone tone)
Convert a tone to half tone based pitch according to MIDI pitch numbers.
The microtonal part is retained in the double return value. interval Interval in the internal representation of Mutabor. a double value that represents the tone a' is represented as 69.00
References mutabor_convert_interval_to_pitch.
Referenced by mutabor::BoxClass::GetCurrentTones, mutabor::BoxClass::GetToneSystem.
mutabor_tone mutabor_convert_pitch_to_tone(double tone)
Convert a tone from half tone based pitch according to MIDI pitch numbers.
The microtonal part can be given in the double value. tone a double value that represents the tone. a' is represented as 69.00 tone in the internal representation of Mutabor.
References mutabor_convert_pitch_to_interval.
Referenced by expand_tonliste, expandiere_tonsystem, mutabor_reset_box.
void HARMONIE_analyse(int instr, PATTERNN *pattern)
void MIDI_analyse(int code)
void KEYB_analyse(int key)
void MAUS_analyse(int mx, int my)
void Add_Key(int instr, int key, int velo)
void Delete_Key(int instr, int key)
tone_system* lz_get_tonsystem(int instr)
PATTERNN* get_pattern(int instr)