s/^INTERVALL/INTERVAL /
s/^WURZEL/ROOT  /
s/^TONSYSTEM /TONESYSTEM/
s/^TON /TONE/
s/^UMSTIMMUNG/RETUNING  /
s/^HARMONIE/PATTERN /
s/^LOGIK/LOGIC/
s/^FORM   /SHIFTED/
s/^MIDIKANAL  /MIDICHANNEL/
s/^TASTE/KEY  /
s/^MIDIIN[|]MIDI\\ EIN/MIDIIN          /
s/^MIDIOUT[|]MIDI\\ AUS/MIDIOUT          /
s/^ANSONSTEN/ELSE     /
