object.c
void* MUTABOR_CLASS_FUNCTION(object, constructor)
Constructor for class object.
Does nothing than error checking.
References CHK_CLASS.
void* MUTABOR_CLASS_FUNCTION(object, destructor)
Destructor for class object.
Does nothing than error checking.
References CHK_CLASS.
int MUTABOR_CLASS_FUNCTION(object, compare)
Comparison between two objects.
Simple comparison by pointers.
References CHK_CLASS.
char* MUTABOR_CLASS_FUNCTION(object, tostring)
Formats Class content as string.
Intented exspecially for debugging.
References CHK_CLASS, MUT_VIRTTABLE.
void* mutabor_new(void *_type)
Creates a new object in Heap space.
If the table of virtual functions is not initialized yet, it will be initialized. _type Pointer to the virtual table of the desired class. It plays the role of class name.
References CHK_CLASS, MUT_CLASS, MUT_VIRTTABLE.
void mutabor_delete(void *_object)
Deletes an object from the heap.
_object object to be deleted.
References CHK_CLASS, mutabor_virttable_object::destructor, mutabor_class_object::virttable.
Referenced by main, MUTABOR_CLASS_FUNCTION.
int mutabor_check_class(void *_self, void *object)
Checks, if a pointer is a subclass of a given class.
_self object to be checked object pointer to the virtual table of the desired class. 0 if not an object of the desired class 1 if _self is an instance of object The function does not return if it encounters cyclic dependencies of objects (or what it takes as objects). In most cases of weired data structures it will (hopefully) fail with a null pointer dereference or a segmentation fault.
References MUT_VIRTCALL, mutabor_check_class.
Referenced by mutabor_check_class.