parameter.h
typedef int parameter_typ
Ganzzahliger Parametertyp.
struct interpreter_parameter_liste* start_parameter_liste
Diese Zweielementige Liste ist Parameterliste bei Logiken.
Referenced by insert_in_lokale_liste.
void init_parameter_liste(void)
Setzt Namensliste auf NULL.
Die Namensliste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by yyparse.
void get_new_name_in_parameterlist(char *name)
Hängt einen Namen an list_of_names an.
Ist der Name schon in der Liste vorhanden, wird ein fataler Fehler ausgelöst. name Name, der angehängt werden soll. Noch zu erledigenFehlercodes sollten per #define in Header-Dateien stehen.
References fatal_error, name, parameter_liste::next, xmalloc.
Referenced by switch, yyparse.
void get_new_number_in_parameterlist(double wert)
int parameter_list_laenge(struct parameter_liste *list)
Zählen der Elemente einer einfach verketteten Parameterliste.
list Liste der Parameter Anzahl der Elemente von list
References parameter_list_laenge.
Referenced by check_aktionen, check_konsistenz, check_logik_konsistenz, check_umstimmungs_konsistenz, parameter_list_laenge.
int parameter_nummer(int aktueller_index, char *such_name, struct parameter_liste *knoten)
Sucht einen Namen in einer Liste.
aktueller_index Ausgangswert such_name Name, der gesucht werden soll knoten Liste, in der der Name gesucht wird EOF falls such_name nicht in parameter_liste aktueller_index+Position von such_name in parameter_liste, falls gefunden. Es gibt keine Überprüfung, ob aktueller_index in die Nähe von EOF kommt.
References name, parameter_liste::next, parameter_nummer.
Referenced by get_umstimmung_breite_abs, get_umstimmung_breite_rel, get_umstimmung_taste_abs, get_umstimmung_taste_rel, get_umstimmung_umstimm_case_parameter, get_umstimmung_umstimm_case_zahl, get_umstimmung_umstimmungs_bund, parameter_nummer.
struct parameter_liste* get_last_parameter_liste(void)
Gibt Wurzelelement der allgemeinen Namensliste zurück.
References list_of_names.
Referenced by eintrage_parameterliste_in_umstimmung.
struct interpreter_parameter_liste* gen_parameter_liste(struct argument_liste *liste, struct interpreter_parameter_liste *bezugs_liste)
Generiert eine Interpreter-Parameterliste aus eine Argumentliste.
Dabei wird eine Bezugsliste verwendet, die für parametrische argumente die Wertefelder zur Verfügung stellt. Taucht ein unerwartetes Ereignis auf, wird ein fataler Fehler ausgelöst. liste Liste der Argumente, die in die Interpreter-Liste eingetragen werden sollen. bezugs_liste Liste mit den Bezügen/Wertefeldern, die für nichtnumerische Argumente verwendet werden soll.
References argument_liste::argument, argument::argument_typ, fatal_error, gen_parameter_liste, get_cache_konstante, interpreter_parameter_liste::next, argument_liste::next, parameter, argument::parameter, argument::u, interpreter_parameter_liste::werte_feld, xmalloc, zahl, argument::zahl.
Referenced by expandiere_name, gen_parameter_liste.