harmonie.h
typedef struct PTRN PATTERNN
Pattern-Struktur für Analyse der Harmonieformen.
struct harmonie* list_of_harmonien
Wurzel der Harmonien.
Referenced by check_ausloeser, mutabor_programm_einlesen.
int tmp_vor_taste
Zwischenspeicher für tiefste Taste einer Harmonie.
Referenced by get_ausloeser_harmonie, get_ausloeser_harmonie_form, get_harmoniebezeichner.
char* tmp_name
Zwischenspeicher für Name einer Harmonie.
Referenced by get_ausloeser_harmonie, get_ausloeser_harmonie_form, get_harmoniebezeichner.
int tmp_nach_taste
Zwischenspeicher für höchste Taste einer Harmonie.
Referenced by get_ausloeser_harmonie, get_ausloeser_harmonie_form, get_harmoniebezeichner.
void drucke_harmonie(struct harmonie *this_)
Gibt eine Harmonie auf der Standardausgabe aus.
this_ Harmonie
References harmonie::name, harmonie::bezugstaste, harmonie::tastenliste, taste::next, taste::stern, taste::taste.
Referenced by mutabor_programm_einlesen.
void get_new_harmonie(char *name, int bezugstaste)
Fügt eine Harmonie ans Ende von list_of_harmonien an.
Dabei wird die letzte eingelesene Tastenliste (tmp_tastenliste) verwendet. name Name der Harmonie bezugstaste Bezugstaste für die Harmonie (Schlüssel-C = 60) Es wird immer die gesamte Liste durchsucht. Effektivität?
References mutabor_debug_level, harmonie::next, fatal_error, xmalloc, name, harmonie::tastenliste, tmp_tastenliste, harmonie::bezugstaste.
Referenced by switch, yyparse.
void get_harmoniebezeichner(int vor_taste, char *name, int nach_taste)
Sichert die Daten eines Harmoniebezeichners im globalen Zwischenspeicher.
vor_taste Tiefste Taste beim Anschlagen der Harmonie name Name der Harmonie(-form) nach_taste Höchste Teste beim Anschlagen der Harmonie
References tmp_vor_taste, tmp_name, name, tmp_nach_taste.
Referenced by switch, yyparse.
struct harmonie* get_harmonie(char *name, struct harmonie *liste)
Sucht eine Harmonie in einer Harmonieliste.
name Name der gesuchten Harmonie liste Liste der Harmodien, in der gesucht wird NULL falls Harmonie nicht in liste Harmonie sonst.
References harmonie::name, get_harmonie, harmonie::next.
Referenced by get_harmonie, check_ausloeser, expand_pattern.
PATTERNN* expand_pattern(char *harmonie_name)
Erzeugt eine Suchmaske für die Suche nach Harmonien.
harmonie_name Name der Harmonie, für die die Maske erzeugt werden soll. Ganzzahlenfeld, das die Harmonie-Suchmaske symbolisiert
References get_harmonie, fatal_error, xmalloc, MAX_BREITE, PTRN::tonigkeit, for, harmonie::tastenliste, taste::stern, taste::taste.
Referenced by insert_in_globale_liste, insert_in_lokale_liste.