mutabor::CurrentTimer
mutint64 mutabor::CurrentTimer::time
Referenced by Get.
bool mutabor::CurrentTimer::is_realtime
Referenced by CurrentTimer, Get, isRealtime, operator+=, Set, UseRealtime.
mutabor::CurrentTimer::CurrentTimer(mutint64 t=0)
Constructor starting the time at a given parameter.
t start time
References is_realtime, mutabor::CurrentTimerBase::Start.
virtual mutabor::CurrentTimer::~CurrentTimer()
Destructor.
void mutabor::CurrentTimer::UseRealtime(bool flag)
Switch between realtime and batch mode.
flag indicating real time mode: true for realtime and false for batch mode.
References is_realtime, mutabor::CurrentTimerBase::Start, mutabor::CurrentTimerBase::Time.
Referenced by mutabor::BoxClass::ActivateAll, mutabor::InputDeviceClass::BatchPlay, testCommonFileDeviceTimer::Play, myDevice::Play, InputMidiFileTest::setUp, CommonMidiOutputTest::setUp, CommonMidiInputTest::setUp, OutputMidiFileTest::setUp, InputMidiFileTest::testAllControllerOff, InputMidiFileTest::testBankSelect, InputMidiFileTest::testBatchPlay1, OutputMidiFileTest::testBatchPlay1, InputMidiFileTest::testBug019010, InputMidiFileTest::testBug019010_2, InputMidiFileTest::testControllerPlay.
bool mutabor::CurrentTimer::isRealtime()
Return the mode of the timer.
true realtime mode false batch mode
References is_realtime.
Referenced by mutaborGUI::MutFrame::CmInDevPlay, mutabor::CommonFileInputDevice::Pause, mutabor::CommonFileInputDevice::Play, mutabor::DebugMidiOutputProvider::WriteTime.
void mutabor::CurrentTimer::Set(mutint64 t=0)
Set the current time.
t time in μs.
References is_realtime, mutabor::CurrentTimerBase::Start.
Referenced by mutabor::InputDeviceClass::BatchPlay, operator=.
mutint64 mutabor::CurrentTimer::Get()
Return the current time in μs.
Time in μs.
References is_realtime, mutabor::CurrentTimerBase::Time, time.
Referenced by mutabor::InputDeviceClass::BatchPlay, testCommonFileDeviceTimer::Open, testCommonFileDeviceTimer::Pause, mutabor::CommonFileInputDevice::Pause, testCommonFileDeviceTimer::Play, mutabor::CommonFileInputDevice::Play, testCommonFileDeviceTimer::PrepareNextEvent, testCommonFileDeviceTimer::Stop, CommonFileDeviceTest::testTimer, mutabor::CommonFileInputDevice::ThreadPlay, mutabor::Track::WriteDelta, mutabor::DebugMidiOutputProvider::WriteTime.
void mutabor::CurrentTimer::Stop()
Dummy function for stopping the timer.
Currently this function does nothing. It is called from the global Stop function to support APIs that need to stop the global timer.
Referenced by mutabor::InputDeviceClass::BatchPlay, mutabor::BoxClass::StopAll.
CurrentTimer& mutabor::CurrentTimer::operator=(mutint64 t)
Assign a time value.
t time in μs. reference to self.
References Set.
CurrentTimer& mutabor::CurrentTimer::operator+=(mutint64 t)
Increment a time value in batch mode.
t time to add to the current time. reference to self.
References is_realtime, mutASSERT.