mutaborGUI::MutView
friend class MutDocument
Referenced by END_EVENT_TABLE.
DECLARE_EVENT_TABLE () protected MutEditFile* mutaborGUI::MutView::textsw
MutView::ProcessEvent is called indirectly from MutApp event handlers.
This leads to endless loops. To prevent these loops, we must be very careful, which kind of events get passed back.Probably no events should be propagated.
Referenced by END_EVENT_TABLE, GetTextsw, SetTextsw.
mutaborGUI::MutView::MutView()
virtual mutaborGUI::MutView::~MutView()
Referenced by END_EVENT_TABLE.
virtual bool mutaborGUI::MutView::OnCreate(wxDocument *doc, long flags)
Referenced by END_EVENT_TABLE.
virtual bool mutaborGUI::MutView::OnClose(bool deleteWindow=true)
Referenced by END_EVENT_TABLE.
virtual void mutaborGUI::MutView::OnDraw(wxDC *dc)
Referenced by END_EVENT_TABLE.
virtual void mutaborGUI::MutView::OnUpdate(wxView *sender, wxObject *hint=NULL)
Referenced by END_EVENT_TABLE.
virtual void mutaborGUI::MutView::OnActivateView(bool activate, wxView *activeView, wxView *deactiveView)
Referenced by END_EVENT_TABLE.
MutEditFile* mutaborGUI::MutView::GetTextsw()
References textsw.
void mutaborGUI::MutView::SetTextsw(MutEditFile *t)
References textsw.
Referenced by mutaborGUI::MutEditFile::~MutEditFile, mutaborGUI::MutFrame::~MutFrame.
MutFrame* mutaborGUI::MutView::GetMutFrame()
References mutASSERT.
Referenced by END_EVENT_TABLE.