Document: mutabor
Title: Debian mutabor Manual
Author: <insert document author here>
Abstract: This manual describes what mutabor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mutabor/mutabor.sgml.gz

Format: postscript
Files: /usr/share/doc/mutabor/mutabor.ps.gz

Format: text
Files: /usr/share/doc/mutabor/mutabor.text.gz

Format: HTML
Index: /usr/share/doc/mutabor/html/index.html
Files: /usr/share/doc/mutabor/html/*.html
