box.h
MU32_BOX_H
MU32_BOX_H_PRECOMPILED
MUT_BOX_MAX_KEY_INDEX_LOG
Referenced by mutabor_create_key_in_box, mutabor_find_key_in_box.
MUT_BOX_MAX_KEY_INDEX
Referenced by boxTest::checkMask, mutabor_create_key_in_box, mutabor_find_key_in_box, mutabor_initialize_keyplane, boxTest::test_init, boxTest::testAddDeleteKey, boxTest::testAddKey, boxTest::testDeleteKey, boxTest::testMUT_BOX_MAX_KEY_INDEX, boxTest::testReaddKey, boxTest::verifyAddKey, boxTest::verifyLastKey.
MUTABOR_NO_NEXT
Referenced by mutabor_create_key_in_box, mutabor_delete_key_in_box, mutabor_find_key_in_box, mutabor_find_key_in_box_by_key, mutabor_initialize_keyplane, mutabor_reset_keys, boxTest::test_init, boxTest::testBug1Permutation1, boxTest::testFindKeyByKey, boxTest::verifyLastKey.
typedef struct mutabor_key_index_type mutabor_key_index_type
typedef struct mutabor_box_type mutabor_box_type
int laufzeit_meldungen_erlaubt
int aktuelles_midi_instrument
size_t minimal_box_used
Referenced by mutaborGUI::CheckBoxesUsed, mutaborGUI::MutFrame::CloseAll, mutaborGUI::MutFrame::CmDoActivate.
int keys_changed_sum
int mutabor_get_note_index(int note, tone_system *system)
References TSYS::anker, TSYS::breite.
Referenced by AddKey, DeleteKey, mutabor::BoxClass::get_index, local_harmony_analysis, mutabor_get_note_frequency, update_pattern.
int mutabor_get_note_distance(int note, tone_system *system)
References TSYS::anker, TSYS::breite.
Referenced by mutabor::BoxClass::get_distance, mutabor_get_note_frequency.
long mutabor_get_note_frequency(int note, tone_system *system)
References mutabor_get_note_distance, mutabor_get_note_index, TSYS::periode, TSYS::ton.
Referenced by change_anker, change_breite, mutabor::BoxClass::get_frequency.
void mutabor_set_logic(struct mutabor_box_type *box, struct mutabor_logic_parsed *logic)
References mutabor_box_type::file, loesche_syntax_speicher, mutabor_lock_logic, mutabor_unlock_logic, mutabor_logic_parsed::refcount.
Referenced by mutabor::BoxClass::SetLogic.
void mutabor_reset_keys(struct mutabor_box_type *box)
References mutabor_box_type::current_keys, mutabor_key_index_type::key, mutabor_box_type::key_count, mutabor_delete_key_in_box, mutabor_find_key_in_box, MUTABOR_KEYRANGE_MAX_WIDTH, MUTABOR_NO_NEXT, mutabor_note_type::next, mutabor_box_type::pattern, PTRN::tonigkeit.
Referenced by mutabor_reset_box, mutabor::BoxClass::Panic.
void mutabor_reset_box(struct mutabor_box_type *box)
References TSYS::anker, mutabor_box_type::current_logic, mutabor_box_type::current_parameters, mutabor_box_type::distance, mutabor_box_type::last_tonesystem, mutabor_convert_pitch_to_interval, mutabor_convert_pitch_to_tone, MUTABOR_KEYRANGE_MAX_WIDTH, mutabor_reset_keys, TSYS::ton, mutabor_box_type::tonesystem, mutabor_box_type::tonesystem_memory.
Referenced by mutabor_initialize_box, mutabor::BoxClass::Reset.
void mutabor_initialize_box(mutabor_box_type *box, int id)
References mutabor_box_type::current_keys, mutabor_box_type::current_logic, mutabor_box_type::current_parameters, mutabor_box_type::id, mutabor_key_index_type::key, mutabor_initialize_keyplane, mutabor_reset_box, mutASSERT, mutabor_box_type::parameters, mutabor_box_type::userdata.
Referenced by mutabor::BoxClass::BoxClass, boxTest::setUp.
void mutabor_initialize_boxes()
void mutabor_initialize_keyplane(mutabor_key_index_type *plane)
References mutabor_key_index_type::key, MUT_BOX_MAX_KEY_INDEX, MUTABOR_NO_NEXT, mutabor_note_type::next, mutabor_key_index_type::next, mutabor_note_type::userdata.
Referenced by mutabor_create_key_in_box, mutabor_initialize_box.
void mutabor_check_key_count(mutabor_box_type *box)
Referenced by mutabor_create_key_in_box, mutabor_delete_key_in_box, mutabor_find_key_in_box.
mutabor_note_type* mutabor_find_key_in_box(mutabor_box_type *box, size_t index)
References mutabor_box_type::current_keys, mutabor_key_index_type::key, mutabor_box_type::key_count, MUT_BOX_MAX_KEY_INDEX, MUT_BOX_MAX_KEY_INDEX_LOG, mutabor_check_key_count, MUTABOR_NO_NEXT, mutabor_key_index_type::next.
Referenced by boxTest::checkMask, DeleteKey, mutabor::BoxClass::GetCurrentTones, hoechste_taste, mutabor_create_key_in_box, mutabor_delete_key_in_box, mutabor_find_key_in_box_by_key, mutabor_reset_keys, mutabor::BoxClass::Panic, boxTest::testFindKeyByKey, tiefste_taste, update_pattern, boxTest::verifyAddKey, boxTest::verifyLastKey.
size_t mutabor_find_key_in_box_by_key(mutabor_box_type *box, int key_number, size_t index)
Find a key in the given box.
box Box to be seached in. key Key number to be found. index Starting point. The first index to be checked is its successer. So you have to check index number 0 yourself (which should be fast enough). index of the key structure that has been found our 0 otherwise.
References mutabor_find_key_in_box, MUTABOR_NO_NEXT, mutabor_note_type::next, mutabor_note_type::number.
Referenced by boxTest::testBug1Permutation1, boxTest::testFindKeyByKey.
void mutabor_delete_key_in_box(mutabor_box_type *box, size_t index)
Delete the key with the given index from the box.
box Box where the key shall be deleted. index Index of the key in box->current_keys of the key that shall be deleted.
References DEBUGLOG2, mutabor_box_type::key_count, mutabor_box_type::last_key, mutabor_check_key_count, mutabor_find_key_in_box, MUTABOR_NO_NEXT, mutASSERT, mutabor_note_type::next, UNREACHABLE, mutabor_note_type::userdata, mutabor_box_type::userdata.
Referenced by DeleteKey, mutabor_reset_keys, boxTest::testBug1Permutation1, boxTest::testDeleteKey, boxTest::testFindKeyByKey.
mutabor_note_type* mutabor_create_key_in_box(mutabor_box_type *box)
References mutabor_box_type::current_keys, mutabor_key_index_type::key, mutabor_box_type::key_count, last, mutabor_box_type::last_key, MUT_BOX_MAX_KEY_INDEX, MUT_BOX_MAX_KEY_INDEX_LOG, mutabor_check_key_count, mutabor_find_key_in_box, mutabor_initialize_keyplane, MUTABOR_NO_NEXT, mutASSERT, mutabor_note_type::next, mutabor_key_index_type::next, UNREACHABLE, mutabor_note_type::userdata.
Referenced by AddKey, boxTest::testAddKey, boxTest::testReaddKey.