heap.c
OFFSET
Größe eines Größentyps.
Referenced by xmalloc.
char SeRiEnNuMmEr[][]
Referenced by intern_ungetc.
int the_character
Zeichen und Flag, ob ein gecachetes Zeichen da ist.
Referenced by intern_fgetc, intern_ungetc.
int is_valid
Referenced by intern_fgetc, intern_ungetc.
struct heap_element* syntax_heap
Syntax-Heap.
Referenced by loesche_syntax_speicher, xmalloc.
struct heap_element* heap_to_use_syntax
Zeiger auf Syntax-Heap-Elemente.
Referenced by xmalloc.
struct mini_heap* laufzeit_heap
Laufzeit-Heap.
Referenced by loesche_laufzeit_speicher, ymalloc.
int intern_fgetc(FILE *stream)
Spezielle Implementation von fgetc.
Es wird getestet, ob sich noch ein Zeichen im Zwischenspeicher befindet. In diesem Fall wird das Zeichen zurückgegeben und der Zwischenspeicher geleert. Ansonsten wird ein neues Zeichen eingelesen. stream Datei, von der das Zeichen eingelesen werden soll. Ein zeichen aus dem Eingabestrom.
References is_valid, the_character.
Referenced by yylex.
int intern_ungetc(int c, FILE *stream)
Spezielle Implementation von ungetc.
Das Zeichen im Zwischenspeicher wird an Position 0 vom Seriennummer-Feld geschrieben und danach wird das übergebene Zeichen c in den Zwischenspeicher gelegt. c Zeichen, das ,,zurückgeschrieben`` werden soll. stream Datei, für das das Zurückschreiben stattfinden soll. Das gesamte Programm kann auf diese Art und Weise maximal ein Zeichen zwischenspeichern. Bei weiteren Aufrufen wird das vorher gespeicherte Zeichen einfach überschrieben.
References is_valid, SeRiEnNuMmEr, the_character.
Referenced by yylex.
void* xalloca(size_t size)
Allokiert einen Speicherbereich und erzeugt im Fehlerfall einen fatalen Fehler.
size Größe des benötigten Speicherbereiches in chars. Zeiger auf den Speicherbereich.
References fatal_error.
Referenced by berechne_intervalle_absolut, berechne_toene_absolut, check_konsistenz.
void xde_alloca(void *pointer)
Gibt einen Speicherbereich wieder frei.
pointer Zeiger auf den freizugebenden Speicherbereich.
Referenced by berechne_intervalle_absolut, berechne_toene_absolut, check_konsistenz.
void xfree(void *pointer)
Freigeben oder auch nich.
pointer Zeiger auf den Speicherbereich, der hier nicht freigegeben wird.
Referenced by yylex, expandiere_umstimmung.
void* xmalloc(size_t size)
Belegt einen Speicherbereich in der einfach verketteten Liste syntax_heap.
Gegebenenfalls wird ein neues Element angelegt. size Anzahl der Zeichen (char), die belegt werden sollen.
References heap_element::anzahl_belegt, fatal_error, HEAP_PORTION_SYNTAX, heap_element::inhalt, heap_element::next, OFFSET, syntax_heap.
Referenced by allgemeine_initialisierungen, expand_case_liste, expand_harmony_analysis, expand_pattern, expand_tonliste, expandiere_logik, expandiere_midi, expandiere_tonsystem, expandiere_umstimmung, gen_parameter_liste, generate_argument_list, get_ausloeser_default, get_ausloeser_harmonie, get_ausloeser_harmonie_form, get_ausloeser_midi_in, get_ausloeser_taste, get_cache_konstante, get_instrument_dekl, get_new_aktion_aufruf_element, get_new_aktion_harmony_analysis, get_new_aktion_midi_out_element, get_new_anchor_in_argument_list, get_new_anweisung, get_new_distance_in_argument_list, get_new_faktor_anteil, get_new_harmonie, get_new_integer_in_integersequenz, get_new_intervall, get_new_intervall_komplex, get_new_logik, get_new_name_in_argument_list, get_new_name_in_parameterlist, get_new_number_in_argument_list, get_new_taste, get_new_ton_absolut, get_new_ton_in_tonsystem, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_new_umstimm_expression, get_new_umstimm_expression_negative, get_new_umstimm_expression_positive, get_umstimmungs_case_default_element, get_umstimmungs_case_zahl_element, init_nullton, init_umstimmung, insert_in_globale_liste, insert_in_lokale_liste, xcalloc, xrealloc, yylex.
void* xrealloc(void *block, size_t newsize)
Ändert die Größe eines aktuellen Speicherbereiches im privaten Syntax-Heap.
Im Fehlerfall wird ein fataler Fehler ausgelöst. block Zeiger auf den Block, dessen Größe geändert werden soll. newsize Neue Größe für den Block.
References heap_element::anzahl_belegt, fatal_error, HEAP_PORTION_SYNTAX, heap_element::inhalt, xmalloc.
Referenced by yylex.
void* xcalloc(size_t anzahl, size_t size)
Fordert einen Speicherbereich vom Syntax-Heap an, der anzahl * size Zeichen enthält.
anzahl Anzahl der Einheiten size Größe einer Speichereinheit.
References fatal_error, xmalloc.
Referenced by check_aktionen, create_midi_scan_liste, expand_decition_tree, generate_argument_list, mutabor_tabellen_generator.
int loesche_syntax_speicher(void)
Löscht den gesamten Syntax-Heap.
Anschließend werden die beiden Zeiger syntax_heap und heap_to_use auf NULL gesetzt. 0 kein Fehler 1 Fehler
References heap_element::next, syntax_heap.
Referenced by mutabor::BoxClass::Compile, GMutCompile, init_syntax_speicher, mutabor_set_logic, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.
int init_syntax_speicher(void)
Initialisiert den Syntax-Heap.
Rückgabewert vom Löschen. Siehe loesche_syntax_speicher.
References loesche_syntax_speicher.
void yfree(void *pointer)
Löscht pointer nicht vom Laufzeit-Heap.
;-). pointer Zeiger auf den zu ,,löschenden`` Speicherbreich.
void* ymalloc(size_t size)
Fordert Speicher auf dem Laufzeit-Heap an.
Dabei wird auf der Liste ein neues Element angelegt. size Größe des Speicherbereiches in char-Einheiten. Zeiger auf den Speicherbereich.
References fatal_error, laufzeit_heap, mini_heap::next, mini_heap::pointer.
Referenced by call_actions, ycalloc, yrealloc.
void* yrealloc(void *block, size_t newsize)
Ändert die Größe eines Elementes auf dem Laufzeit-Heap.
block Zeiger auf das zu ändernde Element. newsize neue Größe Zeiger auf das neue Element. es wird nicht geprüft, ob der neue Speicherbereich größer, als der alte ist. Das kann gegebenenfalls zu Speicherüberlauf-Fehlern führen.
References ymalloc.
void* ycalloc(size_t anzahl, size_t size)
Fordert eine Anzahl von Einheiten auf dem Laufzeit-Heap an.
anzahl Anzahl der Speichereinheiten. size Größe einer Einheit. Speicherbereich.
References ymalloc.
Referenced by call_actions.
int init_laufzeit_speicher(void)
Initialisiert (Löscht) den Laufzeit-Speicher.
0 kein Fehler 1 Fehler
References loesche_laufzeit_speicher.
int loesche_laufzeit_speicher(void)
Löscht den Laufzeitspeicher.
0 kein Fehler 1 Fehler
References laufzeit_heap, mini_heap::next, mini_heap::pointer.
Referenced by init_laufzeit_speicher.