mutaborGUI::GUIInputDeviceBase
MutInputDeviceShapeList mutaborGUI::GUIInputDeviceBase::shapes
Referenced by Add, GetShape, MoveToInList, Remove, Replace.
virtual mutabor::InputDeviceClass* mutaborGUI::GUIInputDeviceBase::GetDevice()=0
Referenced by Add, Remove.
const MutInputDeviceShapeList& mutaborGUI::GUIInputDeviceBase::GetShapes() const
Referenced by mutaborGUI::MakeTopLevelsInput.
MutInputDeviceShapeList& mutaborGUI::GUIInputDeviceBase::GetShapes()
void mutaborGUI::GUIInputDeviceBase::Add(mutabor::Route &route)
add a route
References mutaborGUI::MutBoxChannelShape::Add, DEBUGLOG, GetDevice, mutaborGUI::GUIRouteBase::GetShape, intrusive_ptr_get_refcount, mutASSERT, shapes, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::GUIfiedInputDevice< T >::Add.
bool mutaborGUI::GUIInputDeviceBase::Replace(mutabor::Route &oldroute, mutabor::Route &newroute)
replace a route
References mutaborGUI::GUIRouteBase::GetShape, mutASSERT, Remove, shapes, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::GUIfiedInputDevice< T >::Replace.
bool mutaborGUI::GUIInputDeviceBase::Remove(mutabor::Route &route)
remove a route
References DEBUGLOG, GetDevice, mutaborGUI::GUIRouteBase::GetShape, intrusive_ptr_get_refcount, mutASSERT, mutaborGUI::MutBoxChannelShape::Remove, shapes, mutaborGUI::ToGUIBase, UNREACHABLEC.
Referenced by mutaborGUI::GUIfiedInputDevice< T >::Remove, Replace.
void mutaborGUI::GUIInputDeviceBase::Add(MutInputDeviceShape *shape)
Move routes to another device.
References shapes, UNREACHABLEC.
bool mutaborGUI::GUIInputDeviceBase::Remove(MutInputDeviceShape *shape)
References mutASSERT, shapes, UNREACHABLEC.
void mutaborGUI::GUIInputDeviceBase::Play()
Referenced by mutaborGUI::GUIfiedInputDevice< T >::Play.
void mutaborGUI::GUIInputDeviceBase::Stop()
Referenced by mutaborGUI::GUIfiedInputDevice< T >::Stop.
void mutaborGUI::GUIInputDeviceBase::Pause()
Referenced by mutaborGUI::GUIfiedInputDevice< T >::Pause.
bool mutaborGUI::GUIInputDeviceBase::Open()
Referenced by mutaborGUI::GUIfiedInputDevice< T >::Open.
void mutaborGUI::GUIInputDeviceBase::Close()
Referenced by mutaborGUI::GUIfiedInputDevice< T >::Close.
MutInputDeviceShape * mutaborGUI::GUIInputDeviceBase::GetShape(wxWindow *parent)
References shapes.
Referenced by mutaborGUI::GUIRouteBase::Add, mutaborGUI::Check, mutaborGUI::GUIRouteBase::Remove, mutaborGUI::GUIRouteBase::Replace.
void mutaborGUI::GUIInputDeviceBase::MoveToInList(int newpos)
Move the associated device shape to a given position.
This function handles the GUI part of GUIInputDevice::MoveInList(). newpos New position of the shape in the list. This parameter should reflect the actual position of the device in the (non GUI) input device list.
References shapes.
Referenced by mutaborGUI::GUIfiedInputDevice< T >::MoveInList.
void mutaborGUI::GUIInputDeviceBase::Destroy()
References mutabor::disconnect, TRACEC.
void mutaborGUI::GUIInputDeviceBase::runtime_error(int type, const mutStringRef message, va_list &args)
References mutaborGUI::CM_PRINT_ERROR, mutabor::hidden::internal_error, mutabor::to_string.
Referenced by mutaborGUI::GUIfiedInputDevice< T >::runtime_error.
static GUIInputDeviceBase* mutaborGUI::GUIInputDeviceBase::GetGUIInputDevice(mutabor::InputDeviceClass *d)
References mutabor::Device::getUserData.
Referenced by mutaborGUI::ToGUIBase.
static const GUIInputDeviceBase* mutaborGUI::GUIInputDeviceBase::GetGUIInputDevice(const mutabor::InputDeviceClass *d)
References mutabor::Device::getUserData.
void mutaborGUI::GUIInputDeviceBase::NotifyShapes()
References mutaborGUI::CM_DEVICE_STATE_CHANGED.