MutIconShapeClass
typedef T MutIconShapeClass< T >::parenttype
MutIcon MutIconShapeClass< T >::Icon
the icon
Referenced by MutIconShapeClass< MutPanel >::GetIcon, MutIconShapeClass< MutPanel >::GetIconRect, MutIconShapeClass< MutPanel >::SetIcon.
wxStaticText* MutIconShapeClass< T >::staticText
Referenced by MutIconShapeClass< MutPanel >::SetLabel.
wxSize MutIconShapeClass< T >::maxBorderSize
Referenced by MutIconShapeClass< MutPanel >::GetIconRect.
wxSize MutIconShapeClass< T >::borderOffset
mutpointlist MutIconShapeClass< T >::usedperimeterpoints
Referenced by MutIconShapeClass< MutPanel >::ClearPerimeterPoints.
MutIconShapeClass< T >::MutIconShapeClass()
MutIconShapeClass< T >::MutIconShapeClass(wxWindow *parent, wxWindowID id)
bool MutIconShapeClass< T >::Create(wxWindow *parent, wxWindowID id=wxID_ANY)
Referenced by mutaborGUI::MutBoxIconShape::Create, mutaborGUI::MutBoxChannelShape::Create, mutaborGUI::MutDeviceShape< T >::Create, MutIconShapeClass< MutPanel >::MutIconShapeClass.
virtual MutIconShapeClass< T >::~MutIconShapeClass()
bool MutIconShapeClass< T >::Destroy()
Referenced by MutIconShapeClass< MutPanel >::DeleteSelfEvent, mutaborGUI::MutBoxChannelShape::Destroy, mutaborGUI::BoxData::Destroy.
void MutIconShapeClass< T >::SetIcon(const MutIcon &icon)
const MutIcon& MutIconShapeClass< T >::GetIcon() const
void MutIconShapeClass< T >::SetLabel(const wxString &st)
Referenced by mutaborGUI::MutDeviceShape< T >::Create, mutaborGUI::MutBoxShape::SetBox, mutaborGUI::MutOutputGuidoFileDeviceShape::SetLabel, mutaborGUI::MutOutputMidiFileDeviceShape::SetLabel, mutaborGUI::MutInputGuidoFileDeviceShape::SetLabel, mutaborGUI::MutInputMidiFileDeviceShape::SetLabel, mutaborGUI::MutLogicWnd::UpDate.
virtual MutIcon& MutIconShapeClass< T >::GetMutIcon()
Calculates the Icon to be used.
wxSize MutIconShapeClass< T >::DoGetBestSize() const
References DEBUGLOG, h, mutASSERT.
Referenced by mutaborGUI::GetStaticBoxSize.
void MutIconShapeClass< T >::UpdateBorder(long flag)
References mutUnused.
void MutIconShapeClass< T >::LostFocus()
References TRACEC.
void MutIconShapeClass< T >::GotFocus()
References DEBUGLOG, DEBUGLOGTYPE.
Referenced by mutaborGUI::BEGIN_EVENT_TABLE.
void MutIconShapeClass< T >::OnSize(wxSizeEvent &event)
void MutIconShapeClass< T >::OnGetFocus(wxFocusEvent &event)
References TRACEC.
void MutIconShapeClass< T >::OnKillFocus(wxFocusEvent &event)
References TRACEC.
void MutIconShapeClass< T >::OnMouseClick(wxMouseEvent &event)
References mutUnused, TRACEC.
void MutIconShapeClass< T >::OnPaint(wxPaintEvent &event)
void MutIconShapeClass< T >::OnMove(wxMoveEvent &event)
void MutIconShapeClass< T >::OnDraw(wxDC &dc)
References DEBUGLOG.
Referenced by mutaborGUI::MutTag::OnDraw.
wxPoint MutIconShapeClass< T >::GetPerimeterPoint(const wxPoint &i, const wxPoint &o, wxWindow *paintingWindow) const
References DEBUGLOG, mutASSERT.
void MutIconShapeClass< T >::DrawPerimeterPoint(wxDC &dc, const wxPoint &center, wxPoint p) const
virtual wxRect MutIconShapeClass< T >::GetIconRect() const
Referenced by mutaborGUI::MutTag::PaintCenteredText.
wxPoint MutIconShapeClass< T >::GetPositionInWindow(const wxWindow *win) const
Tries to find the correct position of the window in a parent window.
win parent window. position in win
void MutIconShapeClass< T >::LineTo(wxDC &dc, const wxPoint &p, const wxRect &screenpos) const
bool MutIconShapeClass< T >::Recompute()
bool MutIconShapeClass< T >::Layout()
References DEBUGLOG, h, PRINTSIZER.
virtual void MutIconShapeClass< T >::Fit()
Referenced by mutaborGUI::MutRouteWnd::AddBox, mutaborGUI::MutBoxShape::DoLeftDblClick.
virtual bool MutIconShapeClass< T >::AcceptsFocus() const
void MutIconShapeClass< T >::DeleteSelf() __attribute__((deprecated))
void MutIconShapeClass< T >::DeleteSelfEvent(wxCloseEvent &event) __attribute__((deprecated))
void MutIconShapeClass< T >::ClearPerimeterPoints()