mutaborGUI::MutCommandProcessor
MutDocument* mutaborGUI::MutCommandProcessor::document
mutaborGUI::MutCommandProcessor::MutCommandProcessor(MutDocument *doc=NULL, int maxCommands=-1)
virtual mutaborGUI::MutCommandProcessor::~MutCommandProcessor()
virtual bool mutaborGUI::MutCommandProcessor::Submit(wxCommand *command, bool storeIt=true)
Referenced by BEGIN_EVENT_TABLE.
virtual void mutaborGUI::MutCommandProcessor::Store(wxCommand *command)
Referenced by BEGIN_EVENT_TABLE.
virtual bool mutaborGUI::MutCommandProcessor::Undo()
Referenced by BEGIN_EVENT_TABLE.
virtual bool mutaborGUI::MutCommandProcessor::Redo()
Referenced by BEGIN_EVENT_TABLE.
virtual bool mutaborGUI::MutCommandProcessor::CanUndo() const
Referenced by BEGIN_EVENT_TABLE.
virtual bool mutaborGUI::MutCommandProcessor::CanRedo() const
Referenced by BEGIN_EVENT_TABLE.
virtual void mutaborGUI::MutCommandProcessor::Initialize()
Referenced by BEGIN_EVENT_TABLE.
virtual void mutaborGUI::MutCommandProcessor::SetMenuStrings()
Referenced by BEGIN_EVENT_TABLE.
virtual void mutaborGUI::MutCommandProcessor::ClearCommands()
Referenced by BEGIN_EVENT_TABLE.
virtual bool mutaborGUI::MutCommandProcessor::IsDirty() const
virtual bool mutaborGUI::MutCommandProcessor::DoCommand(wxCommand &cmd)
Referenced by BEGIN_EVENT_TABLE.
virtual bool mutaborGUI::MutCommandProcessor::UndoCommand(wxCommand &cmd)
Referenced by BEGIN_EVENT_TABLE.