Execute.h
MU32_EXECUTE_H
MU32_EXECUTE_H_PRECOMPILED
mutabor_changed_flags
mutabor_error_type
typedef struct mutabor_box_type mutabor_box_type
typedef void mutabor_callback_update_type(mutabor_box_type *box, unsigned int flags)(mutabor_box_type *box, unsigned int flags)
typedef void mutabor_callback_midi_out_type(mutabor_box_type *box, struct midiliste *outliste)(mutabor_box_type *box, struct midiliste *outliste)
typedef void mutabor_callback_error_message_type(mutabor_box_type *box, mutabor_error_type type, const char *message)(mutabor_box_type *box, mutabor_error_type type, const char *message)
typedef void mutabor_callback_update_display(mutabor_box_type *box, int line_number)(mutabor_box_type *box, int line_number)
typedef void mutabor_callback_log_action(mutabor_box_type *box, const char *action)(mutabor_box_type *box, const char *action)
typedef void mutabor_callback_lock_logic(mutabor_logic_parsed *logic)(mutabor_logic_parsed *logic)
struct mutabor_callback_type* mutabor_callbacks
Referenced by mutabor_get_callbacks, mutabor_set_callbacks.
const char * mutabor_error_type_to_string(mutabor_error_type type)
References _, compiler_error, compiler_warning, error, internal_error, runtime_error, runtime_warning, warning.
Referenced by mutabor_default_error_message, mutabor::to_string.
void mutabor_update(mutabor_box_type *box, unsigned int flags)
References mutabor_callback_type::update.
Referenced by execute_aktion, local_harmony_analysis, local_keyboard_analysis, local_midi_analysis.
void mutabor_midi_out(mutabor_box_type *box, struct midiliste *outliste)
References mutabor_callback_type::midi_out.
Referenced by execute_aktion.
void mutabor_error_message(mutabor_box_type *box, enum mutabor_error_type type, const char *message,...)
References mutabor_callback_type::error_message.
Referenced by berechne_intervall_endgueltig, berechne_intervalle_absolut, berechne_toene_absolut, berechne_ton_endgueltig, check_aktionen, check_ausloeser, check_komplex_intervall, check_konsistenz, execute_aktion, expand_aktions_liste, expand_pattern, expand_tonliste, expandiere_logik, expandiere_name, expandiere_umstimmung, fprint_argument, generate_argument_list, get_ausloeser_taste, get_instrument_dekl, get_intervall_wert, get_komplex_faktor, get_logik_nummer, get_new_harmonie, get_new_intervall, get_new_intervall_komplex, get_new_logik, get_new_ton_absolut, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_umstimmung_umstimm_case, get_umstimmung_umstimmungs_bund, get_umstimmung_wiederholung_abs_negative, get_wert_komplex_intervall, init_umstimmung, insert_in_globale_liste, insert_in_lokale_liste, intervall_nummer, link_arguments_to_parameters, local_harmony_analysis, resolve_parameters, switch, test_zyklen, test_zyklen_nummer, ton_nummer, u_test_zyklen, xalloca, xcalloc, xmalloc, xrealloc, ymalloc, yyerror, yylex.
void show_line_number(mutabor_box_type *box, int line_number)
References mutabor_callback_type::update_display.
Referenced by yylex.
void mutabor_log_action(mutabor_box_type *box, const char *action)
References mutabor_callback_type::log_action.
Referenced by execute_aktion.
void mutabor_lock_logic(mutabor_logic_parsed *logic)
References mutabor_callback_type::lock_logic.
Referenced by mutabor_set_logic.
void mutabor_unlock_logic(mutabor_logic_parsed *logic)
References mutabor_callback_type::unlock_logic.
Referenced by mutabor_set_logic.
mutabor_callback_type * mutabor_set_callbacks(mutabor_callback_type *callbacks)
Set the callbacks for the mutabor backend.
callbacks pointer to the object that holds all calbacks that are needed for the backend to run; old callback object.
References mutabor_callbacks.
Referenced by mutabor::initialize_box_data, BoxTest::setUp.
mutabor_callback_type * mutabor_get_callbacks()
Get the currently active callback object.
pointer to the currently active callback object
References mutabor_callbacks.
void KeyboardIn(mutabor_box_type *box, const char *keys)
References KeyboardAnalyse, KeyboardAnalyseSimple, TRACE.
void AddKey(mutabor_box_type *box, int taste, size_t id, size_t channel, void *userdata)
References mutabor_note_type::channel, HarmonyAnalysis, mutabor_note_type::id, KEY_CHANGED, mutabor_create_key_in_box, mutabor_get_note_index, mutabor_note_type::number, mutabor_box_type::pattern, mutabor_box_type::tonesystem, PTRN::tonigkeit, mutabor_note_type::userdata.
Referenced by mutabor::BoxClass::AddNote, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.
void DeleteKey(mutabor_box_type *box, int taste, size_t id, size_t channel)
References box, HarmonyAnalysis, mutabor_note_type::id, KEY_CHANGED, mutabor_box_type::last_key, mutabor_delete_key_in_box, mutabor_find_key_in_box, mutabor_get_note_index, mutabor_note_type::next, mutabor_note_type::number, mutabor_box_type::pattern, mutabor_box_type::tonesystem, PTRN::tonigkeit, TRACE.
Referenced by mutabor::BoxClass::DeleteNote, boxTest::testBug1Permutation2.
void MidiAnalysis(mutabor_box_type *box, BYTE midiByte)
References mutabor_box_type::current_logic, mutabor_box_type::file, mutabor_box_type::flags, mutabor_logic_parsed::global_midi_inputs, local_midi_analysis, mutabor_box_flags::local_midi_before_global, logik::midi_input_list, mutASSERT, TRACE, UNREACHABLE.
Referenced by mutabor::BoxClass::MidiAnalysis.
void KeyboardAnalyse(mutabor_box_type *box, int taste, char isLogic)
References generic_keyboard_analysis.
Referenced by mutabor::BoxClass::KeyboardAnalysis, KeyboardIn.
void KeyboardAnalyseSimple(mutabor_box_type *box, int taste)
References generic_keyboard_analysis.
Referenced by mutabor::BoxClass::KeyboardAnalysis, KeyboardIn.