mutabor::DeviceFactory
typedef std::vector<DeviceFactory *> mutabor::DeviceFactory::factorylist
DeviceFactory::factorylist mutabor::DeviceFactory::factories
Referenced by CreateInput, CreateOutput, mutaborGUI::GUIDeviceFactory::CreateShape, Destroy, DeviceFactory.
mutabor::DeviceFactory::DeviceFactory(size_t id=0)
References factories, UNREACHABLEC.
Referenced by mutaborGUI::GUIDeviceFactory::CreateShape.
mutabor::DeviceFactory::~DeviceFactory()
InputDevice mutabor::DeviceFactory::Create(int type, const mutStringRef name, MutaborModeType mode, int id)
OutputDevice mutabor::DeviceFactory::Create(int type, const mutStringRef name, MutaborModeType mode, int id)
static OutputDevice mutabor::DeviceFactory::CreateOutput(int type, const mutStringRef name=mutEmptyString, MutaborModeType mode=DeviceStop, int id=-1)
References factories, mutASSERT, UNREACHABLECT.
Referenced by LoadOutputDevices, compat30::LoadRoutes, OutputMidiFileTest::setUp, GUIRouteTest::testConnect, RouteTest::testDestroyAll.
static InputDevice mutabor::DeviceFactory::CreateInput(int type, const mutStringRef name=mutEmptyString, MutaborModeType mode=DeviceStop, int id=-1)
References factories, mutASSERT, UNREACHABLECT.
Referenced by LoadInputDevices, compat30::LoadRoutes, InputMidiFileTest::setUp, OutputMidiFileTest::testBatchPlay1, GUIRouteTest::testConnect, RouteTest::testDestroyAll.
static T mutabor::DeviceFactory::Create(int type, const mutStringRef name=mutEmptyString, MutaborModeType mode=DeviceStop, int id=-1)
static void mutabor::DeviceFactory::Destroy()
References factories, UNREACHABLECT.
void mutabor::DeviceFactory::LoadOutputDevices(tree_storage &config)
load the routes from a tree based configuration
config conifiguration to be read from
References CreateOutput, DEBUGLOGTYPE, mutabor::DTMidiPort, mutabor::tree_storage::GetPath, mutASSERT, mutChar, mutabor::tree_storage::Read, mutabor::tree_storage::toFirstLeaf, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toNextLeaf, mutabor::tree_storage::toParent.
Referenced by mutabor::RouteFactory::DoLoadRoutes.
void mutabor::DeviceFactory::SaveOutputDevices(tree_storage &config)
write the routes to the configuration
config configuration to be written to
References mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList, mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent, mutabor::tree_storage::Write.
Referenced by mutabor::RouteFactory::DoSaveRoutes.
void mutabor::DeviceFactory::LoadInputDevices(tree_storage &config)
load the routes from a tree based configuration
config conifiguration to be read from
References CreateInput, DEBUGLOGTYPE, mutabor::DTMidiPort, mutabor::tree_storage::GetPath, mutASSERT, mutChar, mutabor::tree_storage::Read, mutabor::Device::set_file_id, mutabor::tree_storage::toFirstLeaf, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toNextLeaf, mutabor::tree_storage::toParent, TRACE.
Referenced by mutabor::RouteFactory::DoLoadRoutes.
void mutabor::DeviceFactory::SaveInputDevices(tree_storage &config)
write the routes to the configuration
config configuration to be written to
References mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList, mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent, TRACE, mutabor::tree_storage::Write.
Referenced by mutabor::RouteFactory::DoSaveRoutes.
virtual size_t mutabor::DeviceFactory::GetType() const =0
virtual OutputDeviceClass* mutabor::DeviceFactory::DoCreateOutput(const mutStringRef name, int id=-1) const =0
virtual InputDeviceClass* mutabor::DeviceFactory::DoCreateInput(const mutStringRef name, MutaborModeType mode, int id=-1) const =0
void mutabor::DeviceFactory::DoLoadOutputDevices(tree_storage &config) const
load the routes from a tree based configuration
config conifiguration to be read from
References STUBC.
void mutabor::DeviceFactory::DoSaveOutputDevices(tree_storage &config) const
write the routes to the configuration
config configuration to be written to
References STUBC.
void mutabor::DeviceFactory::DoLoadInputDevices(tree_storage &config) const
load the routes from a tree based configuration
config conifiguration to be read from
References STUBC.
void mutabor::DeviceFactory::DoSaveInputDevices(tree_storage &config) const
write the routes to the configuration
config configuration to be written to
References STUBC.