argument.h
argument_typ
void drucke_argument(struct argument *z_or_p)
Gibt ein Argument auf der Standardausgabe aus.
z_or_p Argument.
References argument::parameter, argument::u, zahl, argument::zahl.
Referenced by mutabor_programm_einlesen.
void init_argument_liste(void)
Setzt Argumentliste auf NULL.
Die Argumentliste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by yyparse.
void get_new_name_in_argument_list(char *parameter)
Fügt einen Namen ans Ende von list_of_argumente an.
parameter_name Name, der angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References argument::argument_typ, fatal_error, name, argument_liste::next, parameter, argument::parameter, argument::u, xmalloc.
Referenced by switch, yyparse.
void get_new_number_in_argument_list(double parameter)
Fügt eine Zahl ans Ende von list_of_argumente an.
parameter_zahl Zahl, die angefügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität? Noch zu erledigenTypkonvertierung von double nach int prüfen
References argument::argument_typ, argument_liste::next, argument::u, xmalloc, zahl, argument::zahl.
Referenced by switch, yyparse.
int* get_wert_of_argument(struct argument *argument, struct interpreter_parameter_liste *aktuelle_parameter)
Gibt das Wertefeld eines Argumentes zurück.
argument Argument, das gesucht werden soll. aktuelle_parameter Interpreter-Parameter-Liste mit Wertefeldern für nichtnumerische Argumente.
References argument::argument_typ, fatal_error, get_cache_konstante, MUTABOR_ERROR_UNDEFINED, interpreter_parameter_liste::next, parameter, argument::parameter, argument::u, interpreter_parameter_liste::werte_feld, zahl, argument::zahl.
Referenced by expandiere_umstimmung.
int argument_list_laenge(struct argument_liste *list)
Zählen der Elemente einer einfach verketteten Argumentliste.
list Liste der Argumente Anzahl der Elemente von list
References argument_list_laenge, anweisung::next.
Referenced by argument_list_laenge, check_aktionen, check_konsistenz, check_umstimmungs_konsistenz.
struct argument_liste* get_last_argument_liste(void)
Gibt die Wurzel von list_of_argumente zurück.
References list_of_argumente.
Referenced by get_new_aktion_aufruf_element.