mutabor::TRouteClass
typedef TRouteClass mutabor::TRouteClass< I, O, B >::thistype
typedef I mutabor::TRouteClass< I, O, B >::InputDevice
typedef O mutabor::TRouteClass< I, O, B >::OutputDevice
typedef B mutabor::TRouteClass< I, O, B >::Box
typedef boost::intrusive_ptr<TRouteClass> mutabor::TRouteClass< I, O, B >::Route
typedef std::list<Route> mutabor::TRouteClass< I, O, B >::routeListType
typedef std::list<thistype *> mutabor::TRouteClass< I, O, B >::routePtrList
friend class RouteFactory
friend class mutaborGUI::GUIRouteBase
Noch zu erledigenremove this reference after GUI is working again
OutputDevice mutabor::TRouteClass< I, O, B >::Out
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::Controller, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetChannel, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetOutputDevice, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::MidiOut, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::NoteOff, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::NoteOn, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::Panic, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::UpdateTones.
InputDevice mutabor::TRouteClass< I, O, B >::In
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetInputDevice.
Box mutabor::TRouteClass< I, O, B >::box
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetBox, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::MidiAnalysis, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::MidiOut, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::NoteOff, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::NoteOn, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::Panic, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::SetBox, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::TRouteClass.
idtype<TRouteClass<I,O> > mutabor::TRouteClass< I, O, B >::session_id
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::Controller, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::get_session_id, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetChannel, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::NoteOff, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::NoteOn.
int mutabor::TRouteClass< I, O, B >::routefile_id
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::get_routefile_id.
int mutabor::TRouteClass< I, O, B >::inputid
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetDeviceId, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::SetDeviceId.
int mutabor::TRouteClass< I, O, B >::outputid
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetDeviceId, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::SetDeviceId.
int mutabor::TRouteClass< I, O, B >::boxid
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetBoxId, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::SetBoxId.
RouteType mutabor::TRouteClass< I, O, B >::Type
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetType, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetTypeName, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::SetType.
int mutabor::TRouteClass< I, O, B >::IFrom
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::Check, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetInputFrom, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::SetInputFrom.
int mutabor::TRouteClass< I, O, B >::ITo
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::Check, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetInputTo, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::SetInputTo.
bool mutabor::TRouteClass< I, O, B >::Active
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetActive, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::MidiAnalysis, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::NoteOff, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::NoteOn, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::SetActive.
int mutabor::TRouteClass< I, O, B >::OFrom
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetOutputFrom, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::SetOutputFrom.
int mutabor::TRouteClass< I, O, B >::OTo
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetOutputTo, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::SetOutputTo.
bool mutabor::TRouteClass< I, O, B >::ONoDrum
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::OutputAvoidDrumChannel.
mutabor::TRouteClass< I, O, B >::REFPTR_INTERFACE
TRouteClass< I, O, B >::routeListType mutabor::TRouteClass< I, O, B >::routeList
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::ClearRouteList, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetRouteList.
mutabor::TRouteClass< I, O, B >::~TRouteClass()
References debug_destruct_class, DEBUGLOG, mutASSERT, TRACEC.
void mutabor::TRouteClass< I, O, B >::Save(tree_storage &config)
Write the route settings into a tree based configuration.
config (tree_storage &) configuration where the route settings will be stored
References mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::Write.
void mutabor::TRouteClass< I, O, B >::Load(tree_storage &config)
Read the route into from a tree based configuration.
config (tree_storage &) configuration where the route settings will be read from
References mutabor::connect, mutabor::BoxClass::GetOrCreateBox, mutabor::tree_storage::GetPath, mutASSERT, mutabor::NoBox, mutabor::tree_storage::Read.
char mutabor::TRouteClass< I, O, B >::Check(int i)
const OutputDevice& mutabor::TRouteClass< I, O, B >::GetOutputDevice() const
Referenced by mutaborGUI::Check.
const InputDevice& mutabor::TRouteClass< I, O, B >::GetInputDevice() const
Referenced by mutaborGUI::Check.
void mutabor::TRouteClass< I, O, B >::NoteOn(int key, int velocity, size_t make_unique, const ChannelData &input_channel_data, void *userdata)
void mutabor::TRouteClass< I, O, B >::NoteOff(int key, int velocity, size_t make_unique)
void mutabor::TRouteClass< I, O, B >::MidiAnalysis(const std::vector< unsigned char > *midiCode)
void mutabor::TRouteClass< I, O, B >::MidiOut(midi_string &data)
void mutabor::TRouteClass< I, O, B >::UpdateTones()
int mutabor::TRouteClass< I, O, B >::GetChannel(int key, size_t channel, size_t id)
void mutabor::TRouteClass< I, O, B >::Panic(int type)
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::Panic.
void mutabor::TRouteClass< I, O, B >::Panic(int type, size_t unique_id)
void mutabor::TRouteClass< I, O, B >::Controller(int controller, int value, size_t make_unique)
void mutabor::TRouteClass< I, O, B >::Add(OutputDevice &out)
add a new output device
virtual void mutabor::TRouteClass< I, O, B >::Add(InputDevice &in)
add a new input device
virtual void mutabor::TRouteClass< I, O, B >::Add(Box &b)
add a new box
bool mutabor::TRouteClass< I, O, B >::Replace(OutputDevice &olddev, OutputDevice &newdev)
replace an existing output device
References UNREACHABLEC.
virtual bool mutabor::TRouteClass< I, O, B >::Replace(InputDevice &olddev, InputDevice &newdev)
replace an existing input device
virtual bool mutabor::TRouteClass< I, O, B >::Replace(Box &oldbox, Box &newbox)
replace an existing box
bool mutabor::TRouteClass< I, O, B >::Remove(OutputDevice &out)
remove an existing output device
References UNREACHABLEC.
virtual bool mutabor::TRouteClass< I, O, B >::Remove(InputDevice &in)
remove an existing input device
virtual bool mutabor::TRouteClass< I, O, B >::Remove(Box &b)
remov an existing box
void mutabor::TRouteClass< I, O, B >::SetDeviceId(int Id, I)
void mutabor::TRouteClass< I, O, B >::SetDeviceId(int Id, O)
void mutabor::TRouteClass< I, O, B >::SetBoxId(int Id)
int mutabor::TRouteClass< I, O, B >::GetDeviceId(I)
int mutabor::TRouteClass< I, O, B >::GetDeviceId(O)
int mutabor::TRouteClass< I, O, B >::GetBoxId()
bool mutabor::TRouteClass< I, O, B >::GetActive() const
void mutabor::TRouteClass< I, O, B >::SetActive(bool active)
Box mutabor::TRouteClass< I, O, B >::GetBox() const
Referenced by mutaborGUI::Check, mutabor::CommonMidiOutput< T, D >::do_UpdateTones.
virtual void mutabor::TRouteClass< I, O, B >::SetBox(Box b)
RouteType mutabor::TRouteClass< I, O, B >::GetType() const
Referenced by mutabor::InputMidiPort::Load, mutabor::InputMidiFile::Load, mutabor::InputMidiPort::Save, mutabor::InputMidiFile::Save.
void mutabor::TRouteClass< I, O, B >::SetType(RouteType type)
Referenced by mutabor::InputMidiPort::Load.
const mutString& mutabor::TRouteClass< I, O, B >::GetTypeName()
int mutabor::TRouteClass< I, O, B >::GetInputFrom() const
Referenced by mutabor::InputMidiPort::Save, mutabor::InputMidiFile::Save.
void mutabor::TRouteClass< I, O, B >::SetInputFrom(int i)
Referenced by mutabor::InputMidiPort::Load, mutabor::InputMidiFile::Load.
int mutabor::TRouteClass< I, O, B >::GetOutputFrom() const
Referenced by mutabor::ChannelFilter::check, mutabor::CommonMidiOutput< T, D >::do_NoteOff, mutabor::CommonMidiOutput< T, D >::EmergencyFindChannel, mutabor::ChannelFilter::operator(), mutabor::OutputMidiPort::Save, mutabor::OutputMidiFile::Save.
void mutabor::TRouteClass< I, O, B >::SetOutputFrom(int o)
Referenced by mutabor::OutputMidiPort::Load, mutabor::OutputMidiFile::Load.
int mutabor::TRouteClass< I, O, B >::GetInputTo() const
Referenced by mutabor::InputMidiPort::Save, mutabor::InputMidiFile::Save.
void mutabor::TRouteClass< I, O, B >::SetInputTo(int i)
Referenced by mutabor::InputMidiPort::Load, mutabor::InputMidiFile::Load.
int mutabor::TRouteClass< I, O, B >::GetOutputTo() const
Referenced by mutabor::ChannelFilter::check, mutabor::CommonMidiOutput< T, D >::do_NoteOff, mutabor::CommonMidiOutput< T, D >::EmergencyFindChannel, mutabor::ChannelFilter::operator(), mutabor::OutputMidiPort::Save, mutabor::OutputMidiFile::Save.
void mutabor::TRouteClass< I, O, B >::SetOutputTo(int o)
Referenced by mutabor::OutputMidiPort::Load, mutabor::OutputMidiFile::Load.
bool mutabor::TRouteClass< I, O, B >::OutputAvoidDrumChannel() const
Referenced by mutabor::CommonMidiOutput< T, D >::do_NoteOff, mutabor::CommonMidiOutput< T, D >::EmergencyFindChannel, mutabor::OutputMidiPort::Load, mutabor::OutputMidiFile::Load, mutabor::ChannelFilter::operator(), mutabor::OutputMidiPort::Save, mutabor::OutputMidiFile::Save.
void mutabor::TRouteClass< I, O, B >::OutputAvoidDrumChannel(bool avoid)
int mutabor::TRouteClass< I, O, B >::get_routefile_id() const
size_t mutabor::TRouteClass< I, O, B >::get_session_id() const
Referenced by mutabor::CommonMidiOutput< T, D >::do_NoteOff, mutabor::CommonMidiOutput< T, D >::do_NoteOn, mutabor::CommonMidiOutput< T, D >::do_UpdateTones, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::NoteOn.
void mutabor::TRouteClass< I, O, B >::Destroy()
Remove from Route list to be deleted, when it becomes free.
As we are using smart pointers the Route gets deleted, when no pointers point to it any more. As we want to interactively manage routes, We must allow routes to have no input device attached to it. This function explicitely allows to delete the object when it is not used any more.
References debug_destroy_class, mutabor::disconnect.
wxString mutabor::TRouteClass< I, O, B >::TowxString() const
Referenced by mutaborGUI::Check.
static const routeListType& mutabor::TRouteClass< I, O, B >::GetRouteList()
void mutabor::TRouteClass< I, O, B >::InitializeIds()
Initialize the internal device identifiers.
This function sets the internal device ids of all input devices, starting from 0 and incrementing by 1
References mutabor::BoxClass::InitializeIds, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::InitializeIds, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::InitializeIds.
void mutabor::TRouteClass< I, O, B >::SaveRoutes(tree_storage &config)
Save the current routes in a tree storage.
This function saves all routes in a tree based storage. config (tree_storage *) storage driver to use for saving.
References mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent.
void mutabor::TRouteClass< I, O, B >::LoadRoutes(tree_storage &config)
Load the current routes from a tree storage.
This function loads all routs from a tree based storage. config (tree_storage *) storage driver to use for saving.
References mutabor::RouteFactory::Create, DEBUGLOGTYPE, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDevice, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDevice, mutabor::tree_storage::GetPath, mutabor::Device::IDTypeFile, intrusive_ptr_get_refcount, mutASSERT, mutabor::tree_storage::Read, mutabor::tree_storage::toFirstLeaf, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toNextLeaf, mutabor::tree_storage::toParent, TRACET.
static void mutabor::TRouteClass< I, O, B >::ClearRouteList()
mutabor::TRouteClass< I, O, B >::WATCHEDPTR(void, routing, TRouteClass) userdata
mutabor::TRouteClass< I, O, B >::TRouteClass()
mutabor::TRouteClass< I, O, B >::TRouteClass(InputDevice &in, OutputDevice &out, RouteType type=RTall, int iFrom=-1, int iTo=-1, Box &box=NULL, bool active=false, int oFrom=-1, int oTo=-1, bool oNoDrum=true)
void mutabor::TRouteClass< I, O, B >::Create(InputDevice &in, OutputDevice &out, RouteType type=RTall, int iFrom=-1, int iTo=-1, Box box=NULL, bool active=false, int oFrom=-1, int oTo=-1, bool oNoDrum=true)
References mutabor::connect, DEBUGLOG, intrusive_ptr_get_refcount.
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::TRouteClass.
void mutabor::TRouteClass< I, O, B >::setUserData(void *data)
void * mutabor::TRouteClass< I, O, B >::getUserData() const
void mutabor::TRouteClass< I, O, B >::AppendToRouteList(Route route)
References mutASSERT, TRACET.
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::TRouteClass.
void mutabor::TRouteClass< I, O, B >::RemoveFromRouteList(Route route)
References mutASSERT.