mutabor::InputGis
typedef CommonFileInputDevice mutabor::InputGis::base
friend class GisFactory
GisToken* mutabor::InputGis::Data
Referenced by Close, doResetTime, InputGis, Open.
GisReadArtHead* mutabor::InputGis::Head
Referenced by Close, doResetTime, InputGis, Open, ReadOn, Stop.
const ChannelData mutabor::InputGis::channel_data
Channel data (controllers etc.), currently used to provide the corresponding function.
Referenced by GetChannelData.
mutint64 mutabor::InputGis::minDelta
currently unused
Referenced by operator std::string, PrepareNextEvent, Stop.
mutabor::InputGis::InputGis(const std::string name="", mutabor::MutaborModeType mode=mutabor::DeviceStop, int id=-1)
References Data, Head.
virtual mutabor::InputGis::~InputGis()
void mutabor::InputGis::Save(tree_storage &config, const RouteClass *route)
Save route settings (filter settings) for a given route.
currently unusedSome route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route ) Route whos data shall be saved.Save route settings (filter settings) for a given route Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route ) Route whos data shall be saved.
References mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent.
void mutabor::InputGis::Load(tree_storage &config, RouteClass *route)
Loade route settings (filter settings) for a given route.
Load route settings (filter settings) for a given route.Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route) Route whos data shall be loaded.Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route ) Route whos data shall be loaded.
References mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent.
bool mutabor::InputGis::Open()
References Data, DEBUGLOG, mutabor::DeviceCompileError, GisParse, GspError, GspErrorLineNr, GspErrorPos, GspErrorText, Head, mutabor::Device::Mode, mutabor::Device::Name, mutabor::CommonFileInputDevice::Open, mutabor::Device::runtime_error, mutabor::str.
Referenced by myDevice::Open.
void mutabor::InputGis::Close()
References mutabor::CommonFileInputDevice::Close, Data, mutabor::DeviceCompileError, Head, mutabor::Device::Mode.
Referenced by myDevice::Close.
void mutabor::InputGis::Stop()
Stop playback or recording of the device.
References DEFAULT_PANIC, mutabor::DeviceCompileError, mutabor::DeviceStop, doResetTime, Head, minDelta, mutabor::Device::Mode, mutabor::InputDeviceClass::Panic, mutabor::CommonFileInputDevice::Stop.
Referenced by myDevice::Stop.
void mutabor::InputGis::doResetTime()
Reset the timing and music data after stopping the device.
References GisReadArtHead::Box, Data, DEBUGLOG, mutabor::CommonFileInputDevice::doResetTime, Head, mutabor::Device::Name, GisReadHead::PrevPtr.
Referenced by Stop.
void mutabor::InputGis::Proceed(GisReadArtHead *h, char turn, Route route)
References GisReadArtHead::Box, mutabor::Cd, mutabor::CurrentId, mutabor::CurrentSep, GisReadHead::Cursor, DEBUGLOG, GetGisType, GisReadArtHead::GetInstr, GisReadArtHead::GetIntensity, GisReadArtHead::GetOctave, GTNote, GTTag, GTTagBegin, GTTagEnd, GisReadHead::Id, mutabor::MutaborTag, mutASSERT, mutabor::NoBox, mutabor::InputDeviceClass::NoteOff, mutabor::InputDeviceClass::NoteOn, mutabor::ChannelData::program_change, GisToken::Sep, TTalter, TTmutabor.
Referenced by ProceedRoute.
void mutabor::InputGis::ProceedRoute(GisReadArtHead *h, char turn)
References GisReadArtHead::Box, GisReadHead::Cursor, DEBUGLOG, GisReadHead::Id, mutASSERT, mutabor::Device::Name, mutabor::NoBox, Proceed, mutabor::Device::routes, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff.
Referenced by ReadOn.
mutint64 mutabor::InputGis::ReadOn(mutint64 delta)
References GisReadHead::Boss, GisReadHead::Cursor, GisReadHead::CursorNext, GisReadHead::CutOut, DEBUGLOG, DEBUGLOG2, GisReadArtHead::Delta, mutabor::frac::denominator, mutabor::InputDeviceClass::GetNO_DELTA, GisReadArtHead::GetSpeedFactor, h, Head, mutabor::InputDeviceClass::IsDelta, mutASSERT, mutint64, GisReadHead::Next, GisReadHead::nSub, mutabor::frac::numerator, ProceedRoute, GisReadArtHead::Read, mutabor::str, GisReadHead::Time, GisReadArtHead::Time2, GisReadHead::Turn.
Referenced by PrepareNextEvent.
virtual DevType mutabor::InputGis::GetType() const
References mutabor::DTGis.
mutint64 mutabor::InputGis::PrepareNextEvent()
Go on to the next event.
This function must be provided by the device. It is asked to prepare the next event and return the time to wait in microseconds from the start of the piece. Though the timer has only milliseconds resolution, the errors will sum up so that we need a much higher resolution, here.Here, we use the measure that is used in the SMF standard. It has been designed to reduce the deviation of a 4 minutes piece at 120 bpm to 500μs. If it were 500ms it would be unusable.uint_fast64_t Absolute temporal position of the next event in the piece in μs.
References DEBUGLOG, minDelta, ReadOn.
virtual std::string mutabor::InputGis::GetTypeName() const
References _mutN.
virtual ChannelData& mutabor::InputGis::GetChannelData(const current_keys_type::entry &key) const
References channel_data.
virtual mutabor::InputGis::operator std::string() const
References minDelta, mutabor::Device::Name, mutabor::str.