mutabor::BoxFactory
typedef std::vector<BoxFactory *> mutabor::BoxFactory::factorylist
BoxFactory::factorylist mutabor::BoxFactory::factories
Referenced by BoxFactory, Create, mutaborGUI::GUIBoxFactory::CreateBoxShape, Destroy.
mutabor::BoxFactory::BoxFactory(size_t id=0)
References factories, UNREACHABLEC.
Referenced by mutaborGUI::GUIBoxFactory::CreateBoxShape.
mutabor::BoxFactory::~BoxFactory()
static Box mutabor::BoxFactory::Create(int type, int id=NewBox)
References mutabor::Box0, factories, mutASSERT, mutabor::NewBox, UNREACHABLECT.
Referenced by mutaborGUI::MutBoxShape::DoLeftDblClick, mutabor::BoxClass::GetOrCreateBox, LoadBoxes, CommonMidiOutputTest::setUp, CommonMidiInputTest::setUp, OutputMidiFileTest::setUp, InputMidiFileTest::testAfterTouch, InputMidiFileTest::testAllControllerOff, InputMidiFileTest::testBankSelect, InputMidiFileTest::testBatchPlay1, InputMidiFileTest::testBoxMidiIn, InputMidiFileTest::testBug019010, InputMidiFileTest::testBug019010_2, GUIRouteTest::testConnect, InputMidiFileTest::testControllerPlay, BoxTest::testCopyPLay, RouteTest::testDestroyAll, BoxTest::testGetNextFreeBox, BoxTest::testParser, InputMidiFileTest::testRpnNrpn, InputMidiFileTest::testSysEx.
static void mutabor::BoxFactory::Destroy()
References factories, UNREACHABLECT.
void mutabor::BoxFactory::LoadBoxes(tree_storage &config)
load the routes from a tree based configuration
config conifiguration to be read from
References Create, DEBUGLOGTYPE, mutabor::tree_storage::GetPath, mutASSERT, mutabor::NoBox, mutabor::tree_storage::Read, mutabor::tree_storage::toFirstLeaf, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toNextLeaf, mutabor::tree_storage::toParent.
Referenced by mutabor::RouteFactory::DoLoadRoutes.
void mutabor::BoxFactory::SaveBoxes(tree_storage &config)
write the routes to the configuration
config configuration to be written to
References mutabor::BoxClass::GetBoxList, mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent, mutabor::tree_storage::Write.
Referenced by mutabor::RouteFactory::DoSaveRoutes.
virtual size_t mutabor::BoxFactory::GetType()
References mutabor::Box0.
BoxClass * mutabor::BoxFactory::DoCreateBox(int id=-1) const
void mutabor::BoxFactory::DoLoadBoxes(tree_storage &config) const
load the routes from a tree based configuration
config conifiguration to be read from
References STUBC.
void mutabor::BoxFactory::DoSaveBoxes(tree_storage &config) const
write the routes to the configuration
config configuration to be written to
References STUBC.