GIS.cpp
strdupchr
Referenced by GisNote::GisNote.
AddStr
Referenced by BeginParameter, BeginRange, EndParameter.
const char* Tags[NTAGS][NTAGS]
Referenced by GetTagId, GisTag::GisTag.
const char* TagShorts[NTAGSHORTS][NTAGSHORTS]
Referenced by GetTagId, GisTag::GisTag.
GisToken* Root
Referenced by GisParse.
GisToken** Current
Referenced by BeginRange, BeginSegment, BeginSequenz, BuildTag, Comma, EndRange, EndSegment, EndSequenz, GisParse, Note, StartSep, UnRavel.
GisToken * LastOpenBracket
Referenced by BeginSegment, BeginSequenz, EndSegment, EndSequenz, GisParse, UnRavel.
GisTagBegin* LastOpenRange
Referenced by BeginRange, EndRange, GisParse.
char TagMode
Referenced by BeginRange, BeginSegment, BeginSequenz, BuildTag, Comma, EndRange, EndSegment, EndSequenz, GisParse, NextSequenz, Note, Tag.
std::string TagName
Referenced by BeginRange, BuildTag, GisParse, Tag, UnRavel.
std::string TagSep
Referenced by BeginParameter, BeginRange, BuildTag, EndParameter, GisParse, Tag.
GisToken* Para
Referenced by BeginRange, BuildTag, EndParameter, GisTag::GetPara, GisTag::GetParaType, GisParse, TagParaInt, TagParaReal, TagParaStr, UnRavel.
GisToken * LastPara
Referenced by BeginRange, BuildTag, EndParameter, GisParse, TagParaInt, TagParaReal, TagParaStr.
int LastOctave
mutabor::frac LastDuration
int debugcount
int Name2Key(const std::string name)
Referenced by GisNote::GetKey.
int Acc2Int(const std::string &acc)
Referenced by GisNote::GetKey.
void Clear(std::string *s)
Referenced by BeginRange, BuildTag, MutTextBox::GetKeys, MutTextBox::GetToneSystem, mutaborGUI::MutEditFile::OnEditClear, UnRavel.
int BuildTag()
References Clear, Current, DEBUGLOG2, LastPara, Para, Tag, TagMode, TagName, TagSep.
Referenced by BeginSegment, BeginSequenz, Comma, EndRange, EndSegment, EndSequenz, NextSequenz, Note, Tag.
int StartSep()
References Current, DEBUGLOG2.
Referenced by GspParse.
int BeginSegment()
References BuildTag, GisSegment::Contents, Current, DEBUGLOG2, LastOpenBracket, TagMode.
Referenced by DoParse.
int EndSegment()
References BuildTag, Current, DEBUGLOG2, LastOpenBracket, GisToken::Next, TagMode.
Referenced by DoParse.
int BeginSequenz()
References BuildTag, GisSequenz::Contents, Current, DEBUGLOG2, LastOpenBracket, TagMode.
Referenced by DoParse.
int EndSequenz()
References BuildTag, Current, DEBUGLOG2, LastOpenBracket, GisToken::Next, Sep, TagMode.
Referenced by DoParse.
int BeginParameter()
References AddStr, DEBUGLOG2, TagSep.
Referenced by ReadTag.
int EndParameter()
References AddStr, DEBUGLOG2, LastPara, Para, GisToken::Sep, TagSep.
Referenced by DoParse, ReadTag.
int BeginRange()
References AddStr, Clear, Current, DEBUGLOG2, GisTagBegin::End, LastOpenRange, LastPara, GisToken::Next, Para, GisToken::Sep, Tag, TagMode, TagName, TagSep.
Referenced by DoParse.
int EndRange()
References GisTagEnd::Begin, BuildTag, Current, DEBUGLOG2, GisTagBegin::End, LastOpenRange, GisToken::Next, Tag, TagMode.
Referenced by DoParse.
int NextSequenz()
References BuildTag, DEBUGLOG2, TagMode.
Referenced by DoParse.
int Note(const std::string &name, const std::string &accedentials, int octave, const mutabor::frac &duration)
References BuildTag, Current, DEBUGLOG2, GisToken::Next, octave, mutabor::str, TagMode.
Referenced by ChordNote::MutNoteOn, ReadNote.
int Tag(const std::string &tagName)
References BuildTag, DEBUGLOG2, Sep, TagMode, TagName, TagSep.
Referenced by BeginRange, BuildTag, mutaborGUI::MutLogicWnd::CmMutTag, DoParse, EndRange, ReadTag.
int TagParaInt(long i)
References DEBUGLOG2, LastPara, GisToken::Next, Para.
Referenced by ReadParaNumber.
int TagParaReal(double x)
References DEBUGLOG2, LastPara, GisToken::Next, Para.
Referenced by ReadParaNumber.
int TagParaStr(const std::string &s)
References DEBUGLOG2, LastPara, GisToken::Next, Para.
Referenced by ReadParaStr.
int Comma()
References BuildTag, Current, DEBUGLOG2, TagMode.
Referenced by DoParse, GisWriteHead::ReadyForBoss.
void UnRavel()
References Clear, Current, LastOpenBracket, GisToken::Next, Para, TagName.
Referenced by GisParse.
GisType GetGisType(GisToken *token)
References GTNull, GisToken::Type.
Referenced by CloseAllSubs, GetMidiInstrument, GetReal, GetTheSpeedFactor, mutabor::MutaborTag, ChordNote::MutNoteOff, mutabor::InputGis::Proceed, MisFile::WriteGis.
int GetTagId(const std::string &name, std::string &registered)
References DEBUGLOG2, NTAGS, NTAGSHORTS, Tags, TagShorts.
Referenced by GisTag::GisTag.
GisToken * CopyPara(GisToken *para)
References GisToken::Copy, GisToken::Next.
Referenced by GisTag::Copy, GisTagBegin::Copy.
GisToken * GisParse(const std::string FileName)
References Current, DEBUGLOG2, GspParse, LastOpenBracket, LastOpenRange, LastPara, Para, Root, TagMode, TagName, TagSep, UnRavel.
Referenced by GetInFile, main, mutabor::InputGis::Open.
std::string GISPrettyPrint(std::string s)