mutaborGUI::MutBoxChannelShape
friend class GUIRouteFactory
mutabor::Route mutaborGUI::MutBoxChannelShape::route
Referenced by GetGUIRoute, GetRoute, InitializeInputFilter, InitializeOutputFilter, InitializeRoute.
MutInputDeviceShape* mutaborGUI::MutBoxChannelShape::input
Referenced by GetInput, InitializeInputFilter.
MutOutputDeviceShape* mutaborGUI::MutBoxChannelShape::output
Referenced by GetOutput, InitializeOutputFilter.
MutIcon & mutaborGUI::MutBoxChannelShape::GetMutIcon()
Calculates the Icon to be used.
References mutaborGUI::ActiveChannelBitmap, DEBUGLOG, mutASSERT, mutaborGUI::PassiveChannelBitmap.
mutaborGUI::MutBoxChannelShape::MutBoxChannelShape(wxWindow *p=NULL, wxWindowID id=wxID_ANY, mutabor::Route r=NULL)
Constructor.
Constructor for MutBoxChannelShape. This function constructs a window via Create(), which calles the corresponding attatch function.
References Create.
mutaborGUI::MutBoxChannelShape::~MutBoxChannelShape()
virtual bool mutaborGUI::MutBoxChannelShape::AcceptsFocus() const
bool mutaborGUI::MutBoxChannelShape::Destroy()
References MutIconShapeClass< T >::Destroy.
bool mutaborGUI::MutBoxChannelShape::Create(wxWindow *p=NULL, wxWindowID id=wxID_ANY, mutabor::Route r=NULL)
Create the window.
This function does the work of window creation and connects to the underlying route if necessary. It will complain if a route is already attached to the channel shape. wxWindow * p parent window wxWindowId id id of the shape Route r Route of the undelying Mutabor engine. true if everything is ok false if an error has occured
References mutabor::connect, MutIconShapeClass< T >::Create, mutASSERT, UNREACHABLEC.
Referenced by MutBoxChannelShape.
virtual void mutaborGUI::MutBoxChannelShape::GotFocus()
void mutaborGUI::MutBoxChannelShape::LostFocus()
void mutaborGUI::MutBoxChannelShape::LeftDblClickEvent(wxMouseEvent &event)
void mutaborGUI::MutBoxChannelShape::Add(MutOutputDeviceShape *out)
add a new output device
References UNREACHABLEC.
Referenced by mutaborGUI::MutBoxShape::Add, mutaborGUI::GUIOutputDeviceBase::Add, mutaborGUI::GUIInputDeviceBase::Add, mutaborGUI::connect, mutaborGUI::connect_device_shape, mutaborGUI::MutRouteWnd::createRoutes.
void mutaborGUI::MutBoxChannelShape::Add(MutInputDeviceShape *in)
add a new input device
References TRACEC, UNREACHABLEC.
void mutaborGUI::MutBoxChannelShape::Add(mutabor::Route &r)
add a new route
References DEBUGLOG, UNREACHABLEC.
virtual void mutaborGUI::MutBoxChannelShape::Add(MutBoxShape *box)
add a new box shape
bool mutaborGUI::MutBoxChannelShape::Replace(MutOutputDeviceShape *olddev, MutOutputDeviceShape *newdev)
replace an existing output device
References UNREACHABLEC.
bool mutaborGUI::MutBoxChannelShape::Replace(MutInputDeviceShape *olddev, MutInputDeviceShape *newdev)
replace an existing input device
References mutASSERT, TRACEC.
bool mutaborGUI::MutBoxChannelShape::Replace(mutabor::Route &oldroute, mutabor::Route &newroute)
replace an existing route
References DEBUGLOG, mutASSERT.
virtual bool mutaborGUI::MutBoxChannelShape::Replace(MutBoxShape *oldbox, MutBoxShape *newbox)
replace a box shape
bool mutaborGUI::MutBoxChannelShape::Remove(MutOutputDeviceShape *out)
replace an existing output device
remove an existing output device
References UNREACHABLEC.
Referenced by mutaborGUI::disconnect, mutaborGUI::GUIOutputDeviceBase::Remove, mutaborGUI::GUIInputDeviceBase::Remove.
bool mutaborGUI::MutBoxChannelShape::Remove(MutInputDeviceShape *in)
replace an existing input device
remove an existing input device
References TRACEC, UNREACHABLEC.
bool mutaborGUI::MutBoxChannelShape::Remove(mutabor::Route &r)
remove a Route
remove an attatched route
References DEBUGLOG, UNREACHABLEC.
virtual bool mutaborGUI::MutBoxChannelShape::Remove(MutBoxShape *box)
remove a box from the route shape
mutabor::Route& mutaborGUI::MutBoxChannelShape::GetRoute() const
References route.
Referenced by mutaborGUI::MutRouteWnd::AddRoute, mutaborGUI::Check, mutaborGUI::connect, mutaborGUI::MutBoxShape::DeleteBox, mutaborGUI::disconnect, mutaborGUI::MutBoxShape::HasChannel, mutaborGUI::MutDeviceShape< T >::ReadPanel, mutaborGUI::reconnect.
const MutInputDeviceShape* mutaborGUI::MutBoxChannelShape::GetInput() const
References input.
Referenced by mutaborGUI::Check.
MutInputDeviceShape* mutaborGUI::MutBoxChannelShape::GetInput()
References input.
const MutOutputDeviceShape* mutaborGUI::MutBoxChannelShape::GetOutput() const
References output.
Referenced by mutaborGUI::Check.
MutOutputDeviceShape* mutaborGUI::MutBoxChannelShape::GetOutput()
References output.
GUIRoute* mutaborGUI::MutBoxChannelShape::GetGUIRoute() const
References route.
void mutaborGUI::MutBoxChannelShape::ReadPanel(RoutePanel *panel)
References mutabor::connect, mutaborGUI::DebugCheckRoutes, DEBUGLOG, mutabor::disconnect, mutaborGUI::RoutePanel::GetActive, mutaborGUI::RoutePanel::GetBox, mutaborGUI::InputFilterPanel::GetCurrentSelection, mutaborGUI::OutputFilterPanel::GetCurrentSelection, mutaborGUI::RoutePanel::GetInput, mutaborGUI::RoutePanel::GetOutput, mutaborGUI::BoxData::GetShape, mutASSERT, mutabor::reconnect, mutaborGUI::ToGUIBase, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::MutBoxShape::AddChannel.
void mutaborGUI::MutBoxChannelShape::DrawLines(wxGraphicsContext &dc, wxWindow *paintingWindow, const wxPoint &origin) const
References mutASSERT.
Referenced by mutaborGUI::MutBoxShape::DrawLines.
wxPoint mutaborGUI::MutBoxChannelShape::GetPerimeterPoint(const wxPoint &i, const wxPoint &o, wxWindow *paintingWindow) const
References DEBUGLOG, mutASSERT.
void mutaborGUI::MutBoxChannelShape::DrawPerimeterPoint(wxDC &dc, const wxPoint &center, wxPoint p) const
References mutASSERT, mutUnused.
void mutaborGUI::MutBoxChannelShape::Refresh(bool eraseBackground=true, const wxRect *rect=NULL)
void mutaborGUI::MutBoxChannelShape::DetachChannel()
Detaches the channel from a box shape.
This function detaches a channel from its containing Box. The shape is not deteted.
References mutabor::disconnect.
void mutaborGUI::MutBoxChannelShape::DeleteRoute()
void mutaborGUI::MutBoxChannelShape::CreateRoutePanel(MutBoxChannelShape *channel, MutRouteWnd *parentwin, wxWindow *routeWindow, const mutabor::Box &box)
References mutaborGUI::RouteRemoveButton::EnableRoute, mutaborGUI::RoutePanel::SetChannel, mutaborGUI::RoutePanel::SetInput, mutaborGUI::RoutePanel::SetOutput, UNREACHABLECT.
void mutaborGUI::MutBoxChannelShape::InitializeInputFilter(InputFilterPanel *panel, MutRouteWnd *par, MutBoxChannelShape *shape=NULL)
References _, mutaborGUI::InputFilterPanel::AddPage, DEBUGLOGTYPE, mutaborGUI::InputFilterPanel::GetInputDeviceBook, mutaborGUI::MutRouteWnd::GetInputDevices, input, intrusive_ptr_get_refcount, mutASSERT, route, TRACET.
void mutaborGUI::MutBoxChannelShape::InitializeRoute(RoutePanel *panel, MutRouteWnd *par, MutBoxChannelShape *shape=NULL, mutabor::Box b=NULL)
References mutaborGUI::RoutePanel::AddBox, DEBUGLOGTYPE, mutabor::BoxClass::GetBoxList, mutASSERT, route, mutaborGUI::RoutePanel::SetActive.
void mutaborGUI::MutBoxChannelShape::InitializeOutputFilter(OutputFilterPanel *panel, MutRouteWnd *par, MutBoxChannelShape *shape=NULL)
References _, DEBUGLOGTYPE, mutaborGUI::OutputFilterPanel::GetOutputDeviceBook, mutaborGUI::MutRouteWnd::GetOutputDevices, mutASSERT, output, route.