compat30
static std::locale compat30::nolocale("C")
Referenced by GetLine.
static OutputDevice compat30::GetOut(int nr)
References mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDevice, mutabor::Device::IDTypeFile.
Referenced by LoadRoutes.
static RouteType compat30::Str2RT(char *type)
parse a string representation of a route type
This function returns the numeric route type to a string representation type String (array of char) numeric id of the route type
References mutabor::RTName.
Referenced by LoadRoutes.
static DevType compat30::Str2DT(const std::string type)
References DEBUGLOG2.
Referenced by LoadRoutes.
static bool compat30::find_in_string(const std::string &haystack, char needle)
Referenced by GetLine.
static bool compat30::GetLine(const std::string &p, size_t &i, std::string &s)
References find_in_string, nolocale.
void compat30::LoadRoutes(const std::string &)
load the routes from a text string
config string to be read from the error message in case of an error.
References mutabor::BoxClass::ClearBoxList, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::ClearDeviceList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::ClearDeviceList, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::ClearRouteList, mutabor::RouteFactory::Create, mutabor::DeviceFactory::CreateInput, mutabor::DeviceFactory::CreateOutput, DEBUGLOG2, mutabor::DTGis, mutabor::DTMidiFile, mutabor::DTMidiPort, mutabor::DTNotSet, mutabor::DTUnknown, mutabor::hidden::error, GETLINE, mutabor::BoxClass::GetOrCreateBox, GetOut, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::InitializeIds, SSCANF, Str2DT, Str2RT, STUB, TRACE, UNREACHABLE.
Referenced by mutaborGUI::MutRouteWnd::CmRouteLoad.
void compat30::SaveRoutes(std::string &)
write the routes to the given string
config string to be written to the error message in case of an error.
References DEBUGLOG2, mutabor::DTGis, mutabor::DTMidiFile, mutabor::DTMidiPort, mutabor::DTNotSet, mutabor::DTUnknown, mutabor::Device::get_routefile_id, mutabor::CommonMidiOutput< T, D >::GetBendingRange, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::InitializeIds, mutabor::NoBox, mutabor::RTName, mutabor::str, STUB, UNREACHABLE.
Referenced by mutaborGUI::MutRouteWnd::CmRouteSave.