mutabor::BoxClass::tone
typedef hidden::mutabor_tone mutabor::BoxClass::tone::base
mutabor::BoxClass::tone::tone()
References mutabor::hidden::MUT_INTERVAL::active, mutabor::hidden::mutabor_invalid_tone, mutabor::hidden::MUT_INTERVAL::value.
mutabor::BoxClass::tone::tone(base t)
mutabor::BoxClass::tone::tone(int inkey)
References mutabor::hidden::MUT_INTERVAL::active, mutabor::hidden::mutabor_active_tone, mutint64, mutabor::hidden::MUT_INTERVAL::value.
bool mutabor::BoxClass::tone::is_ok()
References mutabor::hidden::MUT_INTERVAL::active, mutabor::hidden::mutabor_invalid_tone.
bool mutabor::BoxClass::tone::is_active()
References mutabor::hidden::MUT_INTERVAL::active, mutabor::hidden::mutabor_active_tone.
Referenced by mutabor::CommonMidiOutput< T, D >::do_NoteOn.
bool mutabor::BoxClass::tone::is_empty()
References mutabor::hidden::MUT_INTERVAL::active, mutabor::hidden::mutabor_empty_tone.
interval_type_constants mutabor::BoxClass::tone::get_type() const
References mutabor::hidden::mutabor_get_tone_type.
Referenced by mutabor::BoxClass::GetCurrentTones.
long mutabor::BoxClass::tone::get_bend() const
Return the microtonal part of the in fixed point integer format.
This format has been chosen as some device backends need some space for additional calculations. On the other hand the 24 bit provides much room to avoid rounding errors in the logic.Microtonal part in fixed point format with 24 bits after the comma. I.e. 0x1000000 denotes one pitch.
References mutabor::hidden::MUT_INTERVAL::value.
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::pitch_and_bend.
long mutabor::BoxClass::tone::get_pitch() const
References mutabor::hidden::MUT_INTERVAL::value.
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::pitch_and_bend.
mutint64 mutabor::BoxClass::tone::get_value() const
References mutabor::hidden::MUT_INTERVAL::value.
void mutabor::BoxClass::tone::add_value(mutint64 &retval) const
References mutabor::hidden::MUT_INTERVAL::active, mutabor::hidden::mutabor_active_tone, mutabor::hidden::MUT_INTERVAL::value.
bool mutabor::BoxClass::tone::operator==(const tone &t) const
References mutabor::hidden::MUT_INTERVAL::active, mutabor::hidden::MUT_INTERVAL::value.