GSP.cpp
SepPos
Referenced by GetSep, ReadLong, ReadNote, ReadParaNumber, ReadTag.
BracketDeep
Referenced by DoParse, GspParse.
NEW_LINE
Referenced by GetSep, ReadParaStr.
uchar
CHAR0
Referenced by DoParse, GetSep, GspParse, ReadLong, ReadNote, ReadParaNumber, ReadParaStr, ReadTag.
CHAR1
Referenced by GetSep, ReadParaStr.
TAKESEP
Referenced by GetSep.
int GspCurrentLineNr
Referenced by DoError, GetSep, GspParse, ReadNewLine, SavePos.
int GspErrorLineNr
Referenced by CheckError, DoError, GetInFile, GspParse, main, mutabor::InputGis::Open.
int GspErrorPos
Referenced by CheckError, DoError, GetInFile, GspParse, main, mutabor::InputGis::Open.
mutString GspErrorLine
Referenced by CheckError, DoError, GetInFile, GspParse, main.
int GspError
Referenced by CheckError, DoError, DoParse, GetInFile, GetSep, GspParse, main, mutabor::InputGis::Open, ReadTag.
int PossibleErrorLineNr
Referenced by CheckError, SavePos.
int PossibleErrorPos
Referenced by CheckError, SavePos.
mutString PossibleErrorLine
Referenced by CheckError, SavePos.
mutString Sep
Referenced by ChordNote::CheckCloseAlter, ChordNote::CheckCloseTie, GetSep, SepPos, takesep.
char ParaMode
Referenced by DoParse, GetSep, ReadTag.
char Komma
Referenced by DoParse, GetSep.
int NumberLength
Referenced by ReadLong, ReadParaNumber.
mutString Brackets
Referenced by DoParse, GspParse.
char LastTag
Referenced by DoParse, GspParse, ReadTag.
int octave
Referenced by GisNote::GisNote, GspParse, Note, ReadNote.
mutString accedentials
Referenced by GisNote::GisNote, ReadNote.
frac duration
Referenced by ReadNote, mutabor::timing_params::update_duration_exact, mutabor::timing_params::update_duration_midi.
mutChar SepChars[][]
Referenced by GetSep.
mutChar DelimitChars[][]
Referenced by DoParse.
bool minus
Referenced by ReadParaNumber.
size_t SepPos()
References Sep.
void AddStr(mutString &Target, int Pos, const mutString &Source)
References DEBUGLOG2, mutUnused.
Referenced by GetSep, ReadParaStr.
int CharIn(mutChar c, const mutChar *s)
References DEBUGLOG2, mutStrChr.
Referenced by DoParse, GetSep, ReadNote.
int IsLetter(mutChar c)
References mutT.
Referenced by DoParse, ReadNote, ReadTag.
int DoError(int nr, int pos=-1)
References CurrentLine, CurrentPos, GspCurrentLineNr, GspError, GspErrorLine, GspErrorLineNr, GspErrorPos.
Referenced by DoParse, GetSep, GspParse, ReadNote.
int CheckError(int nr)
References GspError, GspErrorLine, GspErrorLineNr, GspErrorPos, PossibleErrorLine, PossibleErrorLineNr, PossibleErrorPos.
Referenced by DoParse, GspParse, ReadNote, ReadParaNumber, ReadParaStr, ReadTag.
void SavePos()
References CurrentLine, CurrentPos, GspCurrentLineNr, mutCopyIntoString, PossibleErrorLine, PossibleErrorLineNr, PossibleErrorPos.
Referenced by DoParse.
wxString& takesep()
References CurrentLine, CurrentPos, DEBUGLOG2, Sep.
int GetSep()
References AddStr, CHAR0, CHAR1, CharIn, CurrentLine, CurrentPos, DEBUGLOG2, DoError, Eof, GspCurrentLineNr, GspError, Komma, mutChar, mutEmptyString, mutT, NEW_LINE, ParaMode, ReadNewLine, Sep, SepChars, SepPos, TAKESEP.
Referenced by DoParse, GspParse, ReadLong, ReadNote, ReadParaNumber, ReadParaStr, ReadTag.
long ReadLong(int SignAllowed)
References CHAR0, CurrentLine, CurrentPos, DEBUGLOG2, GetSep, mutIsdigit, mutT, NumberLength, SepPos.
Referenced by ReadNote, ReadParaNumber.
int ReadParaNumber()
References CHAR0, CheckError, CurrentPos, GetSep, minus, mutChar, mutT, NumberLength, ReadLong, SepPos, TagParaInt, TagParaReal.
Referenced by DoParse.
int ReadParaStr()
References AddStr, CHAR0, CHAR1, CheckError, CurrentLine, CurrentPos, Eof, GetSep, mutChar, mutString, mutT, NEW_LINE, ReadNewLine, TagParaStr.
Referenced by DoParse.
int ReadTag()
References BeginParameter, CHAR0, CheckError, CurrentLine, CurrentPos, EndParameter, GetSep, GspError, IsLetter, LastTag, mutChar, mutString, mutT, ParaMode, SepPos, Tag.
Referenced by DoParse.
int ReadNote()
References accedentials, CHAR0, CharIn, CheckError, CurrentLine, CurrentPos, DEBUGLOG2, DoError, duration, GetSep, IsLetter, mutChar, mutString, mutT, Note, octave, ReadLong, SepPos.
Referenced by DoParse.
int DoParse()
References BeginRange, BeginSegment, BeginSequenz, BracketDeep, Brackets, CHAR0, CharIn, CheckError, Comma, CurrentPos, DEBUGLOGBASE, DelimitChars, DoError, EndParameter, EndRange, EndSegment, EndSequenz, Eof, GetSep, GspError, IsLetter, Komma, LastTag, mutChar, mutIsdigit, mutT, NextSequenz, ParaMode, ReadNote, ReadParaNumber, ReadParaStr, ReadTag, SavePos, Tag.
Referenced by GspParse.
int GspParse(const mutString &FileName)
References BracketDeep, Brackets, CHAR0, CheckError, CloseFile, CurrentLine, CurrentPos, DoError, DoParse, Eof, GetSep, GspCurrentLineNr, GspError, GspErrorLine, GspErrorLineNr, GspErrorPos, LastTag, mutEmptyString, octave, OpenFile, StartSep.
Referenced by GisParse.