logik.h
struct logik* list_of_logiken
Wurzel der Logiken.
Referenced by check_aktionen, check_konsistenz, check_umstimmungs_konsistenz, expandiere_name, mutabor_programm_einlesen, mutabor_tabellen_generator.
void vervollstaendige_logik(void)
Hängt die letzte eingelesene Anweisung in der letzten Logik von list_of_logiken ein.
Es wird immer die gesamte Liste durchsucht. Effektivität? Die Anweisungsliste wird nicht gelöscht. Das muss gegebenenfalls vorher extra getan werden.
References logik::anweisungsliste, get_last_anweisungs_liste, logik::next.
Referenced by switch, yyparse.
void get_new_logik(char *name, char *einstimmung)
Fügt eine neue Logik ans Ende von list_of_logiken an.
Dabei wird der letzte eingelesene Auslöser verwendet. Die Anweisungsliste wird zunächst als Leer deklariert. name Name der Logik einstimmung Name der Einstimmnug der Logik Es wird immer die gesamte Liste durchsucht. Effektivität?
References logik::anweisungsliste, logik::einstimmung, logik::einstimmungs_name, fatal_error, get_last_ausloeser, name, logik::next, xmalloc.
Referenced by switch, yyparse.
int logik_list_laenge(struct logik *list)
Zählen der Elemente einer einfach verketteten Logikliste.
list Liste der Logiken Anzahl der Elemente von list
References logik_list_laenge, logik::next.
Referenced by check_konsistenz, mutabor::BoxClass::Compile, expand_decition_tree, logik_list_laenge, mutabor_tabellen_generator.
int get_logik_nummer(char *name, struct logik *liste)
Ermitteln der Position einer Logik.
Falls liste leer wird eine Fehlermeldung ausgegeben. name Name der zu suchenden Logik liste Liste, in der die Logik gesucht wird Nummer der Logik in der Liste
References fatal_error, get_logik_nummer, logik::name, logik::next.
Referenced by expandiere_logik, get_logik_nummer.
struct logik* get_logik(char *name, struct logik *liste)
Sucht eine Logik in einer Logikliste.
name Name der gesuchten Logik liste Liste der Logiken, in der gesucht wird NULL falls Logik nicht in liste Logik sonst.
References get_logik, logik::name, logik::next.
Referenced by check_aktionen, check_konsistenz, check_umstimmungs_konsistenz, expandiere_name, get_logik.
void setze_nummer_von_abstand_und_zentrum(void)
Setzt Paramater-Nummern von Abstand und Zentrum.
Durchsucht die Logikliste list_of_logiken und setzt bei jedem Argument jeder Aktion jeder anweisung die Parameter-Nummer auf 0, wenn der Parameter-Name ,,ABSTANDheißt, und \li 1, wenn der Parameter-Name ,,ZENTRUM heißt.
References anweisung::aktion, aktion_aufruf, aktions_liste::aktion_aufruf, aktions_liste::aktions_typ, logik::anweisungsliste, argument_liste::argument, argument::argument_typ, fatal_error, logik::name, logik::next, anweisung::next, argument_liste::next, parameter, argument::parameter, argument::u, aktions_liste::u, zahl.
Referenced by mutabor_programm_einlesen.
void check_logik_konsistenz(void)
References logik::anweisungsliste, logik::ausloeser, anweisung::ausloeser, ausloeser_default, ausloeser::ausloeser_typ, check_aktionen, check_ausloeser, compiler_warning, logik::einstimmungs_name, fatal_error, get_umstimmung, list_of_tonsysteme, list_of_umstimmungen, name, logik::name, logik::next, anweisung::next, umstimmung::next, parameter_list_laenge, parser_get_tonsystem.
Referenced by check_konsistenz.
struct do_aktion* expandiere_logik(struct logik *the_logik)
Wandelt eine Logik in eine Aktion um.
Dabei werden die Namen der entsprechenden Bezeichner der Logik durch die zugehörigen Werte ersetzt. Anschließend werden lokale Harmonie, Klaviatur und Midiwerte auf die ersten der Logik initialisiert. the_logik Logik, die expandiert werden soll.
References aufruf_logik, logik::einstimmungs_name, expandiere_tonsystem, expandiere_umstimmung, fatal_error, first_lokal_harmonie, first_lokal_keyboard, first_lokal_midi, get_logik_nummer, get_umstimmung, list_of_tonsysteme, list_of_umstimmungen, name, umstimmung::next, parser_get_tonsystem, umstimmung::u, xmalloc.
Referenced by expandiere_in_globale_liste, expandiere_name.