mutabor::hidden
mutabor_changed_flags
mutabor_error_type
argument_typ
intervall_typ
ton_typ
umstimmung_typ
ausloeser_typ
harmony_type
aktions_typ
mutabor_interval_type_constants
ton_einstell_typ
interpreter_parameter_indices
aufruf_typ
is_harmonic_form_collection
yytokentype
yytokentype
yytokentype
umst_oder_logik_typ
yytokentype
typedef struct mutabor::hidden::mutabor_key_index_type mutabor::hidden::mutabor_key_index_type
typedef struct mutabor::hidden::mutabor_box_type mutabor::hidden::mutabor_box_type
Mutabor box type.
typedef void(* mutabor::hidden::mutabor_callback_update_type)(struct mutabor_box_type *box, unsigned int flags))(struct mutabor_box_type *box, unsigned int flags)
typedef void(* mutabor::hidden::mutabor_callback_midi_out_type)(struct mutabor_box_type *box, struct midiliste *outliste))(struct mutabor_box_type *box, struct midiliste *outliste)
typedef void(* mutabor::hidden::mutabor_callback_error_message_type)(struct mutabor_box_type *box, enum mutabor_error_type type, const char *message))(struct mutabor_box_type *box, enum mutabor_error_type type, const char *message)
typedef void(* mutabor::hidden::mutabor_callback_update_display)(struct mutabor_box_type *box, int line_number))(struct mutabor_box_type *box, int line_number)
typedef void(* mutabor::hidden::mutabor_callback_log_action)(struct mutabor_box_type *box, const char *action))(struct mutabor_box_type *box, const char *action)
typedef void(* mutabor::hidden::mutabor_callback_lock_logic)(struct mutabor_logic_parsed *logic))(struct mutabor_logic_parsed *logic)
typedef struct mutabor::hidden::MUT_INTERVAL mutabor::hidden::mutabor_interval
typedef mutabor_interval mutabor::hidden::mutabor_tone
typedef struct mutabor::hidden::TSYS mutabor::hidden::tone_system
typedef struct mutabor::hidden::PTRN mutabor::hidden::PATTERNN
typedef union YYSTYPE mutabor::hidden::YYSTYPE
typedef struct YYLTYPE mutabor::hidden::YYLTYPE
typedef unsigned char mutabor::hidden::yytype_uint8
typedef signed char mutabor::hidden::yytype_int8
typedef unsigned short int mutabor::hidden::yytype_uint16
typedef short int mutabor::hidden::yytype_int16
typedef struct keyboard_ereignis mutabor::hidden::keyboard_action
typedef struct midi_ereignis mutabor::hidden::midi_action
typedef struct harmonie_ereignis mutabor::hidden::harmony_action
typedef int* mutabor::hidden::intptr
size_t mutabor::hidden::minimal_box_used
Referenced by mutaborGUI::MutFrame::CmDoActivate.
struct mutabor_callback_type mutabor::hidden::default_callbacks
struct mutabor_callback_type * mutabor::hidden::mutabor_callbacks
Referenced by mutabor_get_callbacks, mutabor_set_callbacks.
int mutabor::hidden::yydebug
Referenced by boxTest::testCycles, boxTest::testHaronic_form.
const yytype_uint8 mutabor::hidden::yytranslate[][]
const yytype_uint16 mutabor::hidden::yyrline[][]
const char* const mutabor::hidden::yytname[][]
const yytype_int16 mutabor::hidden::yypact[][]
const yytype_uint8 mutabor::hidden::yydefact[][]
const yytype_int16 mutabor::hidden::yypgoto[][]
const yytype_int16 mutabor::hidden::yydefgoto[][]
const yytype_int16 mutabor::hidden::yytable[][]
const yytype_int16 mutabor::hidden::yycheck[][]
const yytype_uint8 mutabor::hidden::yystos[][]
const yytype_uint8 mutabor::hidden::yyr1[][]
const yytype_uint8 mutabor::hidden::yyr2[][]
jmp_buf mutabor::hidden::weiter_gehts_nach_compilerfehler
void mutabor::hidden::mutabor_set_logic(struct mutabor_box_type *box, struct mutabor_logic_parsed *logic)
References mutabor::hidden::mutabor_box_type::file, loesche_syntax_speicher, mutabor_free_logic_mutex, mutabor_lock_logic, mutabor_unlock_logic, mutabor::hidden::mutabor_logic_parsed::refcount.
Referenced by mutabor::BoxClass::SetLogic.
void mutabor::hidden::mutabor_reset_keys(struct mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::current_keys, mutabor::hidden::mutabor_key_index_type::key, mutabor::hidden::mutabor_box_type::key_count, mutabor_delete_key_in_box, mutabor_find_key_in_box, MUTABOR_KEYRANGE_MAX_WIDTH, MUTABOR_NO_NEXT, mutabor::hidden::mutabor_note_type::next, mutabor::hidden::mutabor_box_type::pattern, mutabor::hidden::PTRN::tonigkeit.
Referenced by mutabor_reset_box, mutabor::BoxClass::Panic.
void mutabor::hidden::mutabor_reset_box(struct mutabor_box_type *box)
References mutabor::hidden::TSYS::anker, mutabor::hidden::mutabor_box_type::current_logic, mutabor::hidden::mutabor_box_type::current_parameters, mutabor::hidden::mutabor_box_type::distance, mutabor::hidden::mutabor_box_type::last_tonesystem, mutabor_get_interval_from_pitch, mutabor_get_tone_from_pitch, MUTABOR_KEYRANGE_MAX_WIDTH, mutabor_reset_keys, mutabor::hidden::TSYS::ton, mutabor::hidden::mutabor_box_type::tonesystem, mutabor::hidden::mutabor_box_type::tonesystem_memory.
Referenced by mutabor_initialize_box, mutabor::BoxClass::Reset.
void mutabor::hidden::mutabor_initialize_box(mutabor_box_type *box, int id)
References mutabor::hidden::mutabor_box_type::current_keys, mutabor::hidden::mutabor_box_type::current_logic, mutabor::hidden::mutabor_box_type::current_parameters, mutabor::hidden::mutabor_box_type::id, mutabor::hidden::mutabor_key_index_type::key, mutabor_initialize_keyplane, mutabor_reset_box, mutASSERT, mutabor::hidden::mutabor_box_type::parameters, mutabor::hidden::mutabor_box_type::userdata.
Referenced by mutabor::BoxClass::BoxClass, boxTest::setUp.
void mutabor::hidden::mutabor_initialize_keyplane(mutabor_key_index_type *plane)
References mutabor::hidden::mutabor_key_index_type::key, MUT_BOX_MAX_KEY_INDEX, MUTABOR_NO_NEXT, mutabor::hidden::mutabor_note_type::next, mutabor::hidden::mutabor_key_index_type::next, mutabor::hidden::mutabor_note_type::userdata.
Referenced by mutabor_create_key_in_box, mutabor_initialize_box.
void mutabor::hidden::mutabor_check_key_count(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::key_count, mutabor_find_key_in_box, MUTABOR_NO_NEXT, mutASSERT, mutabor::hidden::mutabor_note_type::next, UNREACHABLE.
Referenced by mutabor_create_key_in_box, mutabor_delete_key_in_box, mutabor_find_key_in_box.
void mutabor::hidden::mutabor_initialize_boxes()
mutabor_note_type* mutabor::hidden::mutabor_find_key_in_box(mutabor_box_type *box, size_t index)
References mutabor::hidden::mutabor_box_type::current_keys, mutabor::hidden::mutabor_key_index_type::key, mutabor::hidden::mutabor_box_type::key_count, MUT_BOX_MAX_KEY_INDEX, MUT_BOX_MAX_KEY_INDEX_LOG, mutabor_check_key_count, MUTABOR_NO_NEXT, mutabor::hidden::mutabor_key_index_type::next.
Referenced by boxTest::checkMask, DeleteKey, mutabor::BoxClass::GetCurrentTones, hoechste_taste, mutabor_check_key_count, mutabor_create_key_in_box, mutabor_delete_key_in_box, mutabor_find_key_in_box_by_key, mutabor_reset_keys, mutabor::BoxClass::Panic, boxTest::testFindKeyByKey, tiefste_taste, update_pattern, boxTest::verifyAddKey, boxTest::verifyLastKey.
size_t mutabor::hidden::mutabor_find_key_in_box_by_key(mutabor_box_type *box, int key_number, size_t index)
Find a key in the given box.
box Box to be seached in. key Key number to be found. index Starting point. The first index to be checked is its successer. So you have to check index number 0 yourself (which should be fast enough). index of the key structure that has been found our 0 otherwise.
References mutabor_find_key_in_box, MUTABOR_NO_NEXT, mutabor::hidden::mutabor_note_type::next, mutabor::hidden::mutabor_note_type::number.
Referenced by boxTest::testBug1Permutation1, boxTest::testFindKeyByKey.
void mutabor::hidden::mutabor_delete_key_in_box(mutabor_box_type *box, size_t index)
Delete the key with the given index from the box.
box Box where the key shall be deleted. index Index of the key in box->current_keys of the key that shall be deleted.
References DEBUGLOG2, mutabor::hidden::mutabor_box_type::key_count, mutabor::hidden::mutabor_box_type::last_key, mutabor_check_key_count, mutabor_find_key_in_box, MUTABOR_NO_NEXT, mutASSERT, mutabor::hidden::mutabor_note_type::next, UNREACHABLE, mutabor::hidden::mutabor_note_type::userdata.
Referenced by DeleteKey, mutabor_reset_keys, boxTest::testBug1Permutation1, boxTest::testDeleteKey, boxTest::testFindKeyByKey.
mutabor_note_type* mutabor::hidden::mutabor_create_key_in_box(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::current_keys, mutabor::hidden::mutabor_key_index_type::key, mutabor::hidden::mutabor_box_type::key_count, mutabor::hidden::mutabor_box_type::last_key, MUT_BOX_MAX_KEY_INDEX, MUT_BOX_MAX_KEY_INDEX_LOG, mutabor_check_key_count, mutabor_find_key_in_box, mutabor_initialize_keyplane, MUTABOR_NO_NEXT, mutASSERT, mutabor::hidden::mutabor_note_type::next, mutabor::hidden::mutabor_key_index_type::next, UNREACHABLE, mutabor::hidden::mutabor_note_type::userdata.
Referenced by AddKey, boxTest::testAddKey, boxTest::testReaddKey.
const char * mutabor::hidden::mutabor_error_type_to_string(mutabor_error_type type)
References _mut, compiler_error, compiler_warning, error, internal_error, runtime_error, runtime_warning, warning.
Referenced by mutabor_default_error_message, mutabor::to_string.
static void mutabor::hidden::mutabor_default_update(mutabor_box_type *box, unsigned int flags)
static void mutabor::hidden::mutabor_default_midi_out(mutabor_box_type *box, struct midiliste *outliste)
static void mutabor::hidden::mutabor_default_error_message(mutabor_box_type *box, mutabor_error_type type, const char *message)
References mutabor_error_type_to_string.
static void mutabor::hidden::mutabor_default_update_display(mutabor_box_type *box, int line_number)
static void mutabor::hidden::mutabor_default_log_action(mutabor_box_type *box, const char *action)
static void mutabor::hidden::mutabor_default_lock(mutabor_logic_parsed *logic)
struct mutabor_callback_type * mutabor::hidden::mutabor_set_callbacks(struct mutabor_callback_type *callbacks)
Set the callbacks for the mutabor backend.
callbacks pointer to the object that holds all calbacks that are needed for the backend to run; old callback object.
References mutabor_callbacks.
Referenced by mutabor::initialize_box_data, BoxTest::setUp.
struct mutabor_callback_type * mutabor::hidden::mutabor_get_callbacks()
Get the currently active callback object.
pointer to the currently active callback object
References mutabor_callbacks.
void mutabor::hidden::update_pattern(mutabor_box_type *box)
Reset boxes.
References mutabor::hidden::TSYS::breite, mutabor_find_key_in_box, mutabor_get_note_index, mutabor::hidden::mutabor_box_type::pattern, mutabor::hidden::mutabor_box_type::tonesystem, mutabor::hidden::PTRN::tonigkeit, TRACE.
Referenced by execute_aktion.
void mutabor::hidden::change_breite(mutabor_box_type *box, int neu)
References mutabor::hidden::TSYS::anker, mutabor::hidden::TSYS::breite, DEBUGLOG2, mutabor_get_note_frequency, MUTABOR_KEYRANGE_MAX_WIDTH, mutabor_tone_get_interval, mutabor::hidden::TSYS::periode, mutabor::hidden::TSYS::ton, mutabor::hidden::mutabor_box_type::tonesystem.
Referenced by execute_aktion.
void mutabor::hidden::change_anker(mutabor_box_type *box, int neu)
References mutabor::hidden::TSYS::anker, mutabor::hidden::TSYS::breite, mutabor::hidden::mutabor_box_type::distance, mutabor_get_note_frequency, MUTABOR_KEYRANGE_MAX_KEY, MUTABOR_KEYRANGE_MIN_KEY, mutabor_tone_copy_distance, mutabor::hidden::TSYS::periode, mutabor::hidden::TSYS::ton, mutabor::hidden::mutabor_box_type::tonesystem, mutabor::hidden::mutabor_box_type::tonesystem_memory, TRACE.
Referenced by execute_aktion.
void mutabor::hidden::keyboard_analyse(int taste)
Referenced by KeyboardIn.
void mutabor::hidden::HarmonyAnalysis(mutabor_box_type *box, PATTERNN *pattern)
References mutabor::hidden::mutabor_box_type::current_logic, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_box_type::flags, mutabor::hidden::mutabor_logic_parsed::global_harmonies, mutabor::hidden::logik::harmony_list, local_harmony_analysis, mutabor::hidden::mutabor_box_flags::local_harmony_before_global, mutASSERT, TRACE, UNREACHABLE.
Referenced by AddKey, DeleteKey, execute_aktion.
void mutabor::hidden::execute_aktion(mutabor_box_type *box, struct do_aktion *aktion, struct interpreter_parameter_list *parameters)
References _mut, mutabor::hidden::MUT_INTERVAL::active, mutabor::hidden::TSYS::anker, aufruf_harmony_analysis, aufruf_logik, aufruf_midi_out, mutabor::hidden::do_aktion::aufruf_midi_out, aufruf_tonsystem, mutabor::hidden::do_aktion::aufruf_tonsystem, mutabor::hidden::do_aktion::aufruf_typ, aufruf_umst_breite_abs, aufruf_umst_breite_rel, mutabor::hidden::do_aktion::aufruf_umst_breite_rel, aufruf_umst_taste_abs, aufruf_umst_taste_rel, mutabor::hidden::do_aktion::aufruf_umst_taste_rel, aufruf_umst_toene_veraendert, mutabor::hidden::do_aktion::aufruf_umst_toene_veraendert, aufruf_umst_umst_bund, aufruf_umst_umst_case, mutabor::hidden::do_aktion::aufruf_umst_umst_case, aufruf_umst_wiederholung_abs, mutabor::hidden::do_aktion::aufruf_umst_wiederholung_abs, aufruf_umst_wiederholung_rel, mutabor::hidden::TSYS::breite, call_actions, mutabor::hidden::do_aktion::calling, mutabor::hidden::case_element::case_aktion, mutabor::hidden::case_element::case_wert, change_anker, change_breite, mutabor::hidden::mutabor_box_type::current_logic, mutabor::hidden::interpreter_parameter_list::data, einstell_absolut, einstell_gleich, einstell_relativ, einstell_stumm, mutabor::hidden::logik::einstimmung, HarmonyAnalysis, internal_error, mutabor::hidden::ton_einstell::interval, mutabor::hidden::case_element::is_default, mutabor::hidden::do_aktion::logic, mutabor::hidden::midiliste::midi_code, mutabor_add_interval_to_tone, mutabor_add_intervals, mutabor_box_changed, mutabor_empty_tone, mutabor_error_message, mutabor_get_pitch_from_interval, mutabor_keys_changed, mutabor_log_action, mutabor_midi_out, mutabor_update, mutASSERT, mutabor::hidden::do_aktion::name, mutabor::hidden::midiliste::next, mutabor::hidden::ton_einstell::next, mutabor::hidden::case_element::next, mutabor::hidden::mutabor_box_type::pattern, mutabor::hidden::TSYS::periode, mutabor::hidden::interpreter_parameter_list::size, mutabor::hidden::TSYS::ton, mutabor::hidden::ton_einstell::ton_einstell_typ, mutabor::hidden::ton_einstell::tone, mutabor::hidden::mutabor_box_type::tonesystem, TRACE, mutabor::hidden::ton_einstell::u, mutabor::hidden::do_aktion::u, UNREACHABLE, update_pattern.
Referenced by call_actions.
static void mutabor::hidden::call_actions(mutabor_box_type *box, struct do_aktion *aktion_list, struct interpreter_parameter_list *parameters)
References mutabor::hidden::TSYS::anker, mutabor::hidden::mutabor_box_flags::break_logic, mutabor::hidden::interpreter_argument::constant, mutabor::hidden::mutabor_box_type::current_parameters, mutabor::hidden::interpreter_parameter_list::data, mutabor::hidden::interpreter_argument_list::data, mutabor::hidden::mutabor_box_type::distance, execute_aktion, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_box_type::flags, mutabor::hidden::interpreter_argument::index, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, mutASSERT, mutabor::hidden::interpreter_parameter_list::next, mutabor::hidden::mutabor_logic_parsed::parameter_count, mutabor::hidden::mutabor_box_type::parameters, mutabor::hidden::interpreter_argument_list::size, mutabor::hidden::mutabor_box_type::tonesystem, mutabor::hidden::interpreter_argument_list::types, ycalloc, ymalloc.
Referenced by execute_aktion, local_harmony_analysis, local_keyboard_analysis, local_midi_analysis.
int mutabor::hidden::tiefste_taste(mutabor_box_type *box)
return the smallest key pressed actually
References mutabor::hidden::mutabor_box_type::key_count, mutabor_find_key_in_box, mutabor::hidden::mutabor_note_type::next, mutabor::hidden::mutabor_note_type::number, TRACE, UNREACHABLE.
Referenced by local_harmony_analysis.
int mutabor::hidden::hoechste_taste(mutabor_box_type *box)
return the largest key pressed actually
References mutabor::hidden::mutabor_box_type::key_count, mutabor_find_key_in_box, mutabor::hidden::mutabor_note_type::next, mutabor::hidden::mutabor_note_type::number, TRACE, UNREACHABLE.
Referenced by local_harmony_analysis.
int mutabor::hidden::compare_harmonie(int breite, int startindex, PATTERNN *laufzeit, PATTERNN *vergleich)
References mutabor::hidden::PTRN::tonigkeit, TRACE.
Referenced by local_harmony_analysis.
bool mutabor::hidden::local_harmony_analysis(mutabor_box_type *box, struct harmonie_ereignis *trigger, PATTERNN *harmony)
References _mut, mutabor::hidden::TSYS::breite, call_actions, compare_harmonie, mutabor::hidden::mutabor_box_type::distance, mutabor::hidden::any_trigger::harmony, mutabor::hidden::any_trigger::harmony_trigger, hoechste_taste, internal_error, mutabor::hidden::mutabor_box_type::last_trigger, mutabor_action_changed, mutabor_error_message, mutabor_get_note_index, mutabor_harmony_postkey, mutabor_harmony_prekey, mutabor_is_else_path, mutabor_is_harmonic_form, mutabor_is_no_harmonic_form, mutabor_update, mutabor::hidden::harmonie_ereignis::next, tiefste_taste, mutabor::hidden::mutabor_box_type::tonesystem, TRACE, mutabor::hidden::any_trigger::type, mutabor::hidden::any_trigger::u.
Referenced by HarmonyAnalysis.
void mutabor::hidden::AddKey(mutabor_box_type *box, int taste, size_t id, size_t channel, void *userdata)
References mutabor::hidden::mutabor_note_type::channel, DEBUGLOG2, HarmonyAnalysis, mutabor::hidden::mutabor_note_type::id, KEY_CHANGED, mutabor_create_key_in_box, mutabor_get_note_index, mutabor::hidden::mutabor_note_type::number, mutabor::hidden::mutabor_box_type::pattern, mutabor::hidden::mutabor_box_type::tonesystem, mutabor::hidden::PTRN::tonigkeit, mutabor::hidden::mutabor_note_type::userdata.
Referenced by mutabor::BoxClass::AddNote, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.
void mutabor::hidden::DeleteKey(mutabor_box_type *box, int taste, size_t id, size_t channel)
References DEBUGLOG2, HarmonyAnalysis, mutabor::hidden::mutabor_note_type::id, KEY_CHANGED, mutabor::hidden::mutabor_box_type::last_key, mutabor_delete_key_in_box, mutabor_find_key_in_box, mutabor_get_note_index, mutabor::hidden::mutabor_note_type::next, mutabor::hidden::mutabor_note_type::number, mutabor::hidden::mutabor_box_type::pattern, mutabor::hidden::mutabor_box_type::tonesystem, mutabor::hidden::PTRN::tonigkeit, TRACE.
Referenced by mutabor::BoxClass::DeleteNote, boxTest::testBug1Permutation2.
void mutabor::hidden::KeyboardIn(mutabor_box_type *box, const char *keys)
References KeyboardAnalyse, KeyboardAnalyseSimple, TRACE.
Referenced by mutabor::BoxClass::KeyboardAnalysis.
static bool mutabor::hidden::local_midi_analysis(mutabor_box_type *box, struct midi_ereignis *event, const uint8_t *message, size_t size)
References mutabor::hidden::midi_ereignis::aktion, call_actions, mutabor::hidden::midi_ereignis::first_pos, mutabor::hidden::mutabor_box_type::last_trigger, mutabor::hidden::any_trigger::midi, mutabor::hidden::any_trigger::midi_trigger, mutabor_action_changed, mutabor_update, mutabor::hidden::midi_ereignis::next, mutabor::hidden::any_trigger::type, mutabor::hidden::any_trigger::u.
Referenced by MidiAnalysis.
void mutabor::hidden::MidiAnalysis(mutabor_box_type *box, const uint8_t *message, size_t size)
References mutabor::hidden::mutabor_box_type::current_logic, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_box_type::flags, mutabor::hidden::mutabor_logic_parsed::global_midi_inputs, local_midi_analysis, mutabor::hidden::mutabor_box_flags::local_midi_before_global, mutabor::hidden::logik::midi_input_list, mutASSERT, TRACE, UNREACHABLE.
Referenced by mutabor::BoxClass::MidiAnalysis.
static bool mutabor::hidden::local_keyboard_analysis(mutabor_box_type *box, struct keyboard_ereignis *event, int key, char is_logic, char is_simple)
References call_actions, mutabor::hidden::any_trigger::key, mutabor::hidden::any_trigger::key_trigger, mutabor::hidden::mutabor_box_type::last_trigger, mutabor_action_changed, mutabor_update, mutabor::hidden::keyboard_ereignis::next, mutabor::hidden::any_trigger::type, mutabor::hidden::any_trigger::u.
Referenced by generic_keyboard_analysis.
static void mutabor::hidden::generic_keyboard_analysis(mutabor_box_type *box, int taste, char isLogic, char isSimple)
References mutabor::hidden::mutabor_box_type::current_logic, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_box_type::flags, mutabor::hidden::mutabor_logic_parsed::global_keystrokes, mutabor::hidden::logik::keystroke_list, local_keyboard_analysis, mutabor::hidden::mutabor_box_flags::local_keyboard_before_global, mutASSERT, TRACE, UNREACHABLE.
Referenced by KeyboardAnalyse, KeyboardAnalyseSimple.
void mutabor::hidden::KeyboardAnalyse(mutabor_box_type *box, int taste, char isLogic)
References generic_keyboard_analysis.
Referenced by mutabor::BoxClass::KeyboardAnalysis, KeyboardIn.
void mutabor::hidden::KeyboardAnalyseSimple(mutabor_box_type *box, int taste)
References generic_keyboard_analysis.
Referenced by mutabor::BoxClass::KeyboardAnalysis, KeyboardIn.
void mutabor::hidden::mutabor_update(struct mutabor_box_type *box, unsigned int flags)
References mutabor::hidden::mutabor_callback_type::update.
Referenced by execute_aktion, local_harmony_analysis, local_keyboard_analysis, local_midi_analysis.
void mutabor::hidden::mutabor_midi_out(struct mutabor_box_type *box, struct midiliste *outliste)
References mutabor::hidden::mutabor_callback_type::midi_out.
Referenced by execute_aktion.
void mutabor::hidden::mutabor_error_message(struct mutabor_box_type *box, enum mutabor_error_type type, const char *message,...)
References _mut, mutabor::hidden::mutabor_callback_type::error_message.
Referenced by berechne_intervall_endgueltig, berechne_intervalle_absolut, berechne_toene_absolut, berechne_ton_endgueltig, check_aktionen, check_ausloeser, check_komplex_intervall, check_konsistenz, execute_aktion, expand_aktions_liste, expand_pattern, expand_tonliste, expandiere_name, expandiere_umstimmung, fprint_argument, generate_argument_list, get_ausloeser_taste, get_instrument_dekl, get_intervall_wert, get_komplex_faktor, get_logik_nummer, get_new_harmonie, get_new_intervall, get_new_intervall_komplex, get_new_logik, get_new_ton_absolut, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_umstimmung_umstimm_case, get_umstimmung_umstimmungs_bund, get_umstimmung_wiederholung_abs_negative, get_wert_komplex_intervall, init_umstimmung, insert_in_globale_liste, insert_in_lokale_liste, intervall_nummer, link_arguments_to_parameters, local_harmony_analysis, print_ausloeser, resolve_parameters, test_zyklen, test_zyklen, test_zyklen_nummer, ton_nummer, u_test_zyklen, xalloca, xcalloc, xmalloc, xrealloc, ymalloc, yyerror, yylex, yyparse.
void mutabor::hidden::show_line_number(struct mutabor_box_type *box, int line_number)
References mutabor::hidden::mutabor_callback_type::update_display.
Referenced by yylex.
void mutabor::hidden::mutabor_log_action(struct mutabor_box_type *box, const char *action)
References mutabor::hidden::mutabor_callback_type::log_action.
Referenced by execute_aktion.
void mutabor::hidden::mutabor_lock_logic(struct mutabor_logic_parsed *logic)
References mutabor::hidden::mutabor_callback_type::lock_logic.
Referenced by mutabor_set_logic.
void mutabor::hidden::mutabor_unlock_logic(struct mutabor_logic_parsed *logic)
References mutabor::hidden::mutabor_callback_type::unlock_logic.
Referenced by mutabor_set_logic.
void mutabor::hidden::mutabor_free_logic_mutex(struct mutabor_logic_parsed *logic)
References mutabor::hidden::mutabor_callback_type::free_mutex.
Referenced by mutabor_set_logic.
void mutabor::hidden::xfree(void *pointer)
Referenced by expandiere_umstimmung, yylex.
void mutabor::hidden::mutabor_codegenerator(const char *filename)
void mutabor::hidden::write_kompletten_code(FILE *zieldatei)
void mutabor::hidden::get_new_number_in_parameterlist(double wert)
void get_new_relativ_anteil (double f, char *linke_grenze, char *rechte_grenze);
void mutabor::hidden::init_umstimmungs_case_aktions_liste(void)
void mutabor::hidden::get_umstimmungs_case_aktions_element(const char *aktion)
void mutabor::hidden::get_aktion_midi_out(void)
void mutabor::hidden::get_aktion_aufruf(const char *name)
int mutabor::hidden::init_speicher_total(void)
int mutabor::hidden::loesche_speicher_total(void)
void * mutabor::hidden::xalloca(mutabor_box_type *box, size_t size)
References _mut, DEBUGLOG2, error, mutabor_error_message.
Referenced by berechne_intervalle_absolut, berechne_toene_absolut, check_konsistenz.
void mutabor::hidden::xde_alloca(void *pointer)
Referenced by berechne_intervalle_absolut, berechne_toene_absolut, check_konsistenz.
void * mutabor::hidden::xmalloc(mutabor_box_type *box, size_t size)
References _mut, DEBUGLOG2, error, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::heap, HEAP_PORTION_SYNTAX, mutabor::hidden::mutabor_syntax_heap::heap_to_use_syntax, mutabor_error_message, OFFSET, mutabor::hidden::mutabor_syntax_heap::syntax_heap.
Referenced by allgemeine_initialisierungen, expand_case_liste, expand_harmony_analysis, expand_pattern, expand_tonliste, expandiere_logik, expandiere_midi, expandiere_tonsystem, expandiere_umstimmung, generate_argument_list, get_ausloeser_default, get_ausloeser_harmonie, get_ausloeser_harmonie_form, get_ausloeser_midi_in, get_ausloeser_taste, get_instrument_dekl, get_new_aktion_aufruf_element, get_new_aktion_harmony_analysis, get_new_aktion_midi_out_element, get_new_anchor_in_argument_list, get_new_anweisung, get_new_distance_in_argument_list, get_new_faktor_anteil, get_new_harmonie, get_new_integer_in_integersequenz, get_new_intervall, get_new_intervall_komplex, get_new_logik, get_new_name_in_argument_list, get_new_name_in_parameterlist, get_new_number_in_argument_list, get_new_taste, get_new_ton_absolut, get_new_ton_in_tonsystem, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_new_umstimm_expression, get_new_umstimm_expression_negative, get_new_umstimm_expression_positive, get_umstimmungs_case_default_element, get_umstimmungs_case_zahl_element, init_umstimmung, insert_in_globale_liste, insert_in_lokale_liste, xcalloc, xrealloc, yylex.
void * mutabor::hidden::xrealloc(mutabor_box_type *box, void *block, size_t newsize)
References _mut, DEBUGLOG2, error, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::heap, HEAP_PORTION_SYNTAX, mutabor::hidden::mutabor_syntax_heap::heap_to_use_syntax, mutabor_error_message, xmalloc.
Referenced by yylex.
void * mutabor::hidden::xcalloc(mutabor_box_type *box, size_t anzahl, size_t size)
References _mut, DEBUGLOG2, error, mutabor_error_message, xmalloc.
Referenced by check_aktionen, create_midi_scan_liste, expand_decition_tree, generate_argument_list.
int mutabor::hidden::loesche_syntax_speicher(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::heap, mutabor::hidden::mutabor_syntax_heap::heap_to_use_syntax, mutabor::hidden::heap_element::next, mutabor::hidden::mutabor_logic_parsed::refcount, mutabor::hidden::mutabor_syntax_heap::syntax_heap.
Referenced by mutabor::BoxClass::Compile, GMutCompile, init_syntax_speicher, mutabor_set_logic, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testCycles, boxTest::testFindKeyByKey, boxTest::testHaronic_form.
int mutabor::hidden::init_syntax_speicher(mutabor_box_type *box)
References loesche_syntax_speicher.
void mutabor::hidden::yfree(void *pointer)
void * mutabor::hidden::ymalloc(mutabor_box_type *box, size_t size)
References _mut, DEBUGLOG2, error, mutabor_error_message, mutabor::hidden::mutabor_box_type::runtime_heap.
Referenced by call_actions, ycalloc, yrealloc.
void * mutabor::hidden::yrealloc(mutabor_box_type *box, void *block, size_t newsize)
References ymalloc.
void * mutabor::hidden::ycalloc(mutabor_box_type *box, size_t anzahl, size_t size)
References ymalloc.
Referenced by call_actions.
int mutabor::hidden::init_laufzeit_speicher(mutabor_box_type *box)
References loesche_laufzeit_speicher.
int mutabor::hidden::loesche_laufzeit_speicher(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::runtime_heap.
Referenced by init_laufzeit_speicher.
void mutabor::hidden::message_tasten_liste(void)
enum mutabor_interval_type_constants mutabor::hidden::mutabor_get_interval_type(mutabor_interval interval)
Check whether an interval has a defined value or is empty.
interval interval to be checkd. true if the interval is not set or empty.
References mutabor::hidden::MUT_INTERVAL::active.
Referenced by mutabor_convert_interval_to_factor.
enum mutabor_interval_type_constants mutabor::hidden::mutabor_get_tone_type(mutabor_tone tone)
References mutabor::hidden::MUT_INTERVAL::active.
Referenced by mutabor::BoxClass::tone::get_type, mutabor::BoxClass::GetToneSystem.
void mutabor::hidden::mutabor_invalidate_interval(mutabor_interval *interval)
References mutabor::hidden::MUT_INTERVAL::active, mutabor_invalid_interval.
void mutabor::hidden::mutabor_invalidate_tone(mutabor_tone *tone)
References mutabor::hidden::MUT_INTERVAL::active, mutabor_invalid_tone.
void mutabor::hidden::mutabor_clear_interval(mutabor_interval *interval)
References mutabor::hidden::MUT_INTERVAL::active, mutabor_empty_interval.
void mutabor::hidden::mutabor_clear_tone(mutabor_tone *tone)
References mutabor::hidden::MUT_INTERVAL::active, mutabor_empty_tone.
double mutabor::hidden::mutabor_convert_interval_to_factor(mutabor_interval interval)
Convert an interval to half tone based pitch according to MIDI pitch numbers.
The microtonal part is retained in the double return value. interval Interval in the internal representation of Mutabor. a double value that represents the interval. a half tone is represented as 1.00, and an octave as 12.00.
References mutabor_active_interval, mutabor_convert_pitch_to_factor, mutabor_empty_interval, mutabor_get_interval_type, mutabor_invalid_interval, UNREACHABLE, mutabor::hidden::MUT_INTERVAL::value.
Referenced by mutabor_convert_tone_to_factor.
mutabor_interval mutabor::hidden::mutabor_convert_factor_to_interval(double interval)
Convert an interval from a frequecy factor.
The microtonal part can be given in the double value. interval a double value that represents the interval. a semitone is represented as 1.00, and an octave as 12.00 interval in the internal representation of Mutabor.
References mutabor::hidden::MUT_INTERVAL::active, mutabor_active_interval, mutabor_convert_factor_to_pitch, mutabor_empty_interval, mutabor_invalid_interval, mutint64, mutabor::hidden::MUT_INTERVAL::value.
Referenced by expand_tonliste, expandiere_tonsystem, expandiere_umstimmung, mutabor_convert_factor_to_tone.
mutabor_interval mutabor::hidden::mutabor_get_interval_from_pitch(double pitch)
Convert an interval from half tone based pitch according to MIDI pitch numbers.
The microtonal part can be given in the double value. interval a double value that represents the interval. a semitone is represented as 1.00, and an octave as 12.00 interval in the internal representation of Mutabor. The resulting interval is always a valid non-nil interval.
References mutabor::hidden::MUT_INTERVAL::active, mutabor_active_interval, mutint64, mutabor::hidden::MUT_INTERVAL::value.
Referenced by mutabor_reset_box.
double mutabor::hidden::mutabor_get_pitch_from_interval(mutabor_interval interval)
Convert an interval from half tone based pitch according to MIDI pitch numbers.
The microtonal part can be given in the double value. interval in the internal representation of Mutabor. a double value that represents the interval. a semitone is represented as 1.00, and an octave as 12.00 The resulting interval is always a valid non-nil interval.
References mutabor::hidden::MUT_INTERVAL::value.
Referenced by execute_aktion, mutabor::BoxClass::GetToneSystem.
double mutabor::hidden::mutabor_convert_tone_to_factor(mutabor_tone tone)
Convert a tone to half tone based pitch according to MIDI pitch numbers.
The microtonal part is retained in the double return value. interval Interval in the internal representation of Mutabor. a double value that represents the tone a' is represented as 69.00
References mutabor_convert_interval_to_factor.
mutabor_tone mutabor::hidden::mutabor_convert_factor_to_tone(double tone)
Convert a tone from half tone based pitch according to MIDI pitch numbers.
The microtonal part can be given in the double value. tone a double value that represents the tone. a' is represented as 69.00 tone in the internal representation of Mutabor.
References mutabor_convert_factor_to_interval.
mutabor_tone mutabor::hidden::mutabor_convert_frequency_to_tone(double frequency)
Convert a tone from half tone based pitch according to MIDI pitch numbers.
The microtonal part can be given in the double value. frequency a double value that represents the tone. a' is represented as 440.00 tone in the internal representation of Mutabor.
References mutabor::hidden::MUT_INTERVAL::active, mutabor_active_tone, mutabor_convert_frequency_to_pitch, mutabor_empty_tone, mutabor_invalid_tone, mutint64, mutabor::hidden::MUT_INTERVAL::value.
Referenced by expand_tonliste, expandiere_tonsystem.
mutabor_tone mutabor::hidden::mutabor_get_tone_from_pitch(double pitch)
Convert an tone from half tone based pitch according to MIDI pitch numbers.
The microtonal part can be given in the double value. tone a double value that represents the interval. a semitone is represented as 1.00, and an octave as 12.00 tone in the internal representation of Mutabor. The resulting interval is always a valid non-nil interval.
References mutabor::hidden::MUT_INTERVAL::active, mutabor_active_tone, mutint64, mutabor::hidden::MUT_INTERVAL::value.
Referenced by mutabor_reset_box.
double mutabor::hidden::mutabor_get_pitch_from_tone(mutabor_tone tone)
Convert an tone from half tone based pitch according to MIDI pitch numbers.
The microtonal part can be given in the double value. tone in the internal representation of Mutabor. a double value that represents the tone. a semitone is represented as 1.00, and an octave as 12.00 The resulting interval is always a valid non-nil interval.
References mutabor::hidden::MUT_INTERVAL::value.
Referenced by mutabor::BoxClass::GetCurrentTones, mutabor::BoxClass::GetToneSystem.
mutabor_tone mutabor::hidden::mutabor_add_interval_to_tone(const mutabor_tone tone, int count, const mutabor_interval interval)
References mutabor::hidden::MUT_INTERVAL::active, mutabor_active_interval, mutabor_empty_interval, mutabor_invalid_interval, mutint64, mutabor::hidden::MUT_INTERVAL::value.
Referenced by execute_aktion, mutabor_get_note_frequency.
mutabor_interval mutabor::hidden::mutabor_tone_get_interval(const mutabor_tone t1, const mutabor_tone t2)
References mutabor::hidden::MUT_INTERVAL::active, mutabor_active_tone, mutabor_empty_tone, mutabor_invalid_tone, mutabor::hidden::MUT_INTERVAL::value.
Referenced by change_breite.
mutabor_interval mutabor::hidden::mutabor_add_intervals(const mutabor_interval interval1, int count, const mutabor_interval interval2)
References mutabor::hidden::MUT_INTERVAL::active, mutabor_active_interval, mutabor_empty_interval, mutabor_invalid_interval, mutint64, mutabor::hidden::MUT_INTERVAL::value.
Referenced by execute_aktion.
mutabor_tone mutabor::hidden::mutabor_tone_copy_distance(const mutabor_tone offset, const mutabor_tone t1, const mutabor_tone t2)
Add the distance of t1 - t2 to offset.
This function transfers the interval between two tones to two other tones. offset new base tone t1 old tone t2 old base tone offset + (t1 - t2)
References mutabor::hidden::MUT_INTERVAL::active, mutabor_active_tone, mutabor_empty_tone, mutabor_invalid_tone, mutabor::hidden::MUT_INTERVAL::value.
Referenced by change_anker.
int mutabor::hidden::mutabor_get_note_index(int note, tone_system *system)
References mutabor::hidden::TSYS::anker, mutabor::hidden::TSYS::breite, if, mutASSERT.
Referenced by AddKey, DeleteKey, mutabor::BoxClass::get_index, local_harmony_analysis, mutabor_get_note_frequency, update_pattern.
int mutabor::hidden::mutabor_get_note_distance(int note, tone_system *system)
References mutabor::hidden::TSYS::anker, mutabor::hidden::TSYS::breite, mutASSERT.
Referenced by mutabor::BoxClass::get_distance, mutabor_get_note_frequency.
mutabor_interval mutabor::hidden::mutabor_get_note_frequency(int note, tone_system *system)
References mutabor_add_interval_to_tone, mutabor_get_note_distance, mutabor_get_note_index, mutabor::hidden::TSYS::periode, mutabor::hidden::TSYS::ton.
Referenced by change_anker, change_breite, mutabor::BoxClass::get_frequency.
void mutabor::hidden::HARMONIE_analyse(int instr, PATTERNN *pattern)
void mutabor::hidden::MIDI_analyse(int code)
void mutabor::hidden::KEYB_analyse(int key)
void mutabor::hidden::MAUS_analyse(int mx, int my)
void mutabor::hidden::Add_Key(int instr, int key, int velo)
void mutabor::hidden::Delete_Key(int instr, int key)
tone_system* mutabor::hidden::lz_get_tonsystem(int instr)
PATTERNN* mutabor::hidden::get_pattern(int instr)
int mutabor::hidden::intervall_list_laenge(struct intervall *list)
Referenced by berechne_intervalle_absolut, mutabor::BoxClass::Compile.
void mutabor::hidden::berechne_intervalle_absolut(mutabor_box_type *box, struct intervall *list_of_intervalle)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::interval_count, intervall_list_laenge, mutabor::hidden::mutabor_logic_parsed::check_intervals, xalloca, mutabor::hidden::mutabor_logic_parsed::visited_intervals, mutabor::hidden::mutabor_logic_parsed::interval_matrix, belege_intervalle, adjacent, mutabor::hidden::intervall::intervall_typ, intervall_absolut, intervall_komplex, mutabor::hidden::intervall::u, mutabor::hidden::intervall::intervall_komplex, intervall_nummer, mutabor_error_message, internal_error, _, mutabor::hidden::intervall::name, test_zyklen, berechne_intervall_endgueltig, xde_alloca.
Referenced by mutabor_programm_einlesen.
void mutabor::hidden::check_komplex_intervall(mutabor_box_type *box, struct komplex_intervall *liste, const char *konstrukt_name)
References get_intervall, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_intervalle, mutabor_error_message, compiler_error, _, intervall_absolut, internal_error, mutabor::hidden::intervall::intervall_typ.
Referenced by check_konsistenz.
double mutabor::hidden::get_wert_komplex_intervall(mutabor_box_type *box, struct komplex_intervall *intervall)
References get_intervall_wert, mutabor_error_message, compiler_error, _.
Referenced by get_intervall_wert, berechne_intervall_endgueltig, berechne_ton_endgueltig, expandiere_tonsystem, expandiere_umstimmung.
int mutabor::hidden::yyparse(mutabor_box_type *box)
References _mut, mutabor::hidden::YYSTYPE::arguments, compiler_error, compiler_warning, eintrage_parameterliste_in_umstimmung, enumerate_parameters, mutabor::hidden::YYSTYPE::f_value, FEHLERZEILE, mutabor::hidden::mutabor_box_type::file, get_ausloeser_default, get_ausloeser_harmonie, get_ausloeser_harmonie_form, get_ausloeser_midi_in, get_ausloeser_taste, get_harmoniebezeichner, get_instrument_dekl, get_new_aktion_aufruf_element, get_new_aktion_harmony_analysis, get_new_aktion_midi_out_element, get_new_anchor_in_argument_list, get_new_anweisung, get_new_distance_in_argument_list, get_new_faktor_anteil, get_new_harmonie, get_new_integer_in_integersequenz, get_new_intervall, get_new_intervall_komplex, get_new_logik, get_new_name_in_argument_list, get_new_name_in_parameterlist, get_new_number_in_argument_list, get_new_taste, get_new_ton_absolut, get_new_ton_in_tonsystem, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_new_umstimm_expression, get_new_umstimm_expression_negative, get_new_umstimm_expression_positive, get_new_umstimmung, get_umstimmung_breite_abs, get_umstimmung_breite_rel, get_umstimmung_midi_out, get_umstimmung_taste_abs, get_umstimmung_taste_rel, get_umstimmung_tonhoehe_veraendert, get_umstimmung_umstimm_case, get_umstimmung_umstimmungs_bund, get_umstimmung_wiederholung_abs, get_umstimmung_wiederholung_abs_negative, get_umstimmung_wiederholung_rel_negative, get_umstimmung_wiederholung_rel_positive, get_umstimmungs_case_default_element, get_umstimmungs_case_zahl_element, mutabor::hidden::YYSTYPE::identifier, init_aktions_liste, init_anweisungs_liste, init_ausloeser, init_integersequenz, init_komplex_ton_list, init_tastenliste, init_ton_liste, init_umstimm_expression_list, init_umstimmung, init_umstimmungs_case_liste, mutabor::hidden::YYSTYPE::integer, mutabor::hidden::mutabor_logic_parsed::list_of_instrumente, mutabor_error_message, mutabor_harmony_bothkey, mutabor_harmony_nokey, mutabor_harmony_postkey, mutabor_harmony_prekey, mutabor::hidden::YYSTYPE::parameters, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, vervollstaendige_logik, YY_, YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_INITIAL_VALUE, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yyclearin, yydestruct, YYDPRINTF, YYEMPTY, YYEOF, yyerror, YYFINAL, YYINITDEPTH, YYLAST, yylex, YYLLOC_DEFAULT, YYMAXDEPTH, YYNTOKENS, yypact_value_is_default, YYPOPSTACK, YYSIZE_T, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, YYSYNTAX_ERROR, yytable_value_is_error, YYTERROR, YYTRANSLATE.
Referenced by mutabor_programm_einlesen.
int mutabor::hidden::yylex(YYSTYPE *lvalp, YYLTYPE *llocp, mutabor_box_type *box)
Noch zu erledigencheck whether this function is necessary for any system but windows
References _mut, mutabor::hidden::mutabor_scanner_data::anzahl_eingelesene_zeichen, compiler_error, mutabor::hidden::mutabor_scanner_data::data, DEBUGLOG2, mutabor::hidden::YYSTYPE::f_value, mutabor::hidden::YYLTYPE::first_line, mutabor::hidden::YYSTYPE::identifier, mutabor::hidden::YYSTYPE::integer, LINE_DRAW_QUANTUM, MAX_IDENTIFIER_LEN, mutabor_error_message, MUTABOR_TOKEN_ANCHOR, MUTABOR_TOKEN_DISTANCE, MUTABOR_TOKEN_ELSE, MUTABOR_TOKEN_ERROR, MUTABOR_TOKEN_F_NUMBER, MUTABOR_TOKEN_FORM, MUTABOR_TOKEN_HARMONY, MUTABOR_TOKEN_HARMONY_ANALYSIS, MUTABOR_TOKEN_IDENTIFIER, MUTABOR_TOKEN_INTEGER, MUTABOR_TOKEN_INTERVAL, MUTABOR_TOKEN_KEY, MUTABOR_TOKEN_LOGIC, MUTABOR_TOKEN_MIDI_IN, MUTABOR_TOKEN_MIDI_OUT, MUTABOR_TOKEN_MIDICHANNEL, MUTABOR_TOKEN_RETUNING, MUTABOR_TOKEN_ROOT, MUTABOR_TOKEN_TONE, MUTABOR_TOKEN_TONESYSTEM, mutASSERT, mutabor::hidden::mutabor_scanner_data::pos, mutabor::hidden::mutabor_box_type::scanner, show_line_number, xfree, xmalloc, xrealloc.
Referenced by yyparse.
void mutabor::hidden::yyerror(YYLTYPE *locp, mutabor_box_type *box, const char *err)
References _mut, compiler_error, mutabor::hidden::YYLTYPE::first_line, mutabor_error_message.
Referenced by yyparse.
static YY_ATTRIBUTE_UNUSED unsigned mutabor::hidden::yy_location_print_(FILE *yyo, YYLTYPE const *const yylocp)
References mutabor::hidden::YYLTYPE::first_column, mutabor::hidden::YYLTYPE::first_line, mutabor::hidden::YYLTYPE::last_column, mutabor::hidden::YYLTYPE::last_line, YYFPRINTF.
static void mutabor::hidden::yy_symbol_value_print(FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep, YYLTYPE const *const yylocationp, mutabor_box_type *box)
References YYNTOKENS, YYUSE.
Referenced by yy_symbol_print.
static void mutabor::hidden::yy_symbol_print(FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep, YYLTYPE const *const yylocationp, mutabor_box_type *box)
References YY_LOCATION_PRINT, yy_symbol_value_print, YYFPRINTF, YYNTOKENS.
Referenced by yy_reduce_print.
static void mutabor::hidden::yy_stack_print(yytype_int16 *yybottom, yytype_int16 *yytop)
References YYFPRINTF.
static void mutabor::hidden::yy_reduce_print(yytype_int16 *yyssp, YYSTYPE *yyvsp, YYLTYPE *yylsp, int yyrule, mutabor_box_type *box)
References yy_symbol_print, YYFPRINTF.
static YYSIZE_T mutabor::hidden::yystrlen(const char *yystr)
References YYSIZE_T.
Referenced by yysyntax_error, yytnamerr.
static char* mutabor::hidden::yystpcpy(char *yydest, const char *yysrc)
Referenced by yytnamerr.
static YYSIZE_T mutabor::hidden::yytnamerr(char *yyres, const char *yystr)
References YYSIZE_T, yystpcpy, yystrlen.
Referenced by yysyntax_error.
static int mutabor::hidden::yysyntax_error(YYSIZE_T *yymsg_alloc, char **yymsg, yytype_int16 *yyssp, int yytoken)
References YY_, YY_NULLPTR, YYCASE_, YYEMPTY, YYLAST, YYNTOKENS, yypact_value_is_default, YYSIZE_T, YYSTACK_ALLOC_MAXIMUM, yystrlen, yytable_value_is_error, YYTERROR, yytnamerr.
static void mutabor::hidden::yydestruct(const char *yymsg, int yytype, YYSTYPE *yyvaluep, YYLTYPE *yylocationp, mutabor_box_type *box)
References YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_SYMBOL_PRINT, YYUSE.
Referenced by yyparse.
void mutabor::hidden::init_yylex()
Referenced by GMutCompile.
static void mutabor::hidden::berechne_toene_absolut(mutabor_box_type *box, struct ton *ton_liste)
References _mut, mutabor::hidden::mutabor_logic_parsed::anzahl_toene, belege_toene, berechne_ton_endgueltig, mutabor::hidden::mutabor_box_type::file, internal_error, isDebugFlag, mutabor_adjacent, mutabor_error_message, mutabor::hidden::ton::name, test_zyklen, mutabor::hidden::mutabor_logic_parsed::toene, ton_absolut, ton_komplex, mutabor::hidden::ton::ton_komplex, ton_list_laenge, ton_nummer, mutabor::hidden::ton::ton_typ, mutabor::hidden::mutabor_logic_parsed::tone_matrix, TRACE, mutabor::hidden::ton::u, mutabor::hidden::mutabor_logic_parsed::visited_tones, xalloca, xde_alloca.
Referenced by mutabor_programm_einlesen.
static void mutabor::hidden::check_konsistenz(mutabor_box_type *box)
References _mut, aktion_aufruf, mutabor::hidden::aktions_liste::aktion_aufruf, allgemeine_initialisierungen, mutabor::hidden::logik::anweisungsliste, mutabor::hidden::mutabor_logic_parsed::anzahl_umstimmungen_und_logiken, argument_list_laenge, mutabor::hidden::anweisung::ausloeser, mutabor::hidden::logik::ausloeser, ausloeser_default, mutabor::hidden::ausloeser::ausloeser_typ, belege_zyklenfeld, case_label_enthalten_in_case_liste, check_aktionen, check_ausloeser, check_komplex_intervall, compiler_error, compiler_warning, mutabor::hidden::mutabor_box_type::file, get_logik, get_ton, get_umstimmung, internal_error, mutabor::hidden::mutabor_logic_parsed::list_of_logiken, mutabor::hidden::mutabor_logic_parsed::list_of_toene, mutabor::hidden::mutabor_logic_parsed::list_of_tonsysteme, mutabor::hidden::mutabor_logic_parsed::list_of_umstimmungen, mutabor::hidden::umst_oder_logik::logik, logik_list_laenge, mutabor_error_message, MUTABOR_KEYRANGE_MAX_KEY, MUTABOR_KEYRANGE_MIN_KEY, mutabor_u_adjacent, mutabor::hidden::ton::name, mutabor::hidden::tonsystem::name, mutabor::hidden::umstimmung::name, mutabor::hidden::logik::name, mutabor::hidden::ton::next, mutabor::hidden::tonsystem::next, mutabor::hidden::anweisung::next, mutabor::hidden::logik::next, parameter_list_laenge, parser_get_tonsystem, mutabor::hidden::logik::parser_tuning, mutabor::hidden::tonsystem::periode, mutabor::hidden::tonsystem::taste, test_zyklen_nummer, mutabor::hidden::tonsystem::toene, ton_absolut, mutabor::hidden::ton::ton_komplex, TRACE, typ_logik, typ_umstimmung, mutabor::hidden::umst_oder_logik::u, mutabor::hidden::ton::u, mutabor::hidden::umstimmung::u, mutabor::hidden::aktions_liste::u, mutabor::hidden::mutabor_logic_parsed::u_matrix, u_test_zyklen, mutabor::hidden::mutabor_logic_parsed::u_visited, mutabor::hidden::umst_oder_logik::umst_oder_logik_typ, mutabor::hidden::umst_oder_logik::umstimmung, umstimmung_breite_abs, umstimmung_breite_rel, umstimmung_taste_abs, umstimmung_taste_rel, umstimmung_toene_veraendert, mutabor::hidden::umstimmung::umstimmung_toene_veraendert, mutabor::hidden::umstimmung::umstimmung_typ, umstimmung_umstimmungs_case, mutabor::hidden::umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, mutabor::hidden::umstimmung::umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, mutabor::hidden::umstimmung::umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, mutabor::hidden::umstimmung::umstimmung_wiederholung_rel, umstimmungs_list_laenge, xalloca, xde_alloca, mutabor::hidden::mutabor_logic_parsed::zyklen_feld.
Referenced by mutabor_programm_einlesen.
static void mutabor::hidden::drucke_ton(struct ton *lauf)
References mutabor::hidden::komplex_intervall::faktor, mutabor::hidden::komplex_intervall::name, mutabor::hidden::ton::name, mutabor::hidden::komplex_intervall::next, ton_absolut, mutabor::hidden::ton::ton_absolut, ton_komplex, mutabor::hidden::ton::ton_komplex, mutabor::hidden::ton::ton_typ, mutabor::hidden::ton::u.
Referenced by mutabor_programm_einlesen.
static void mutabor::hidden::drucke_harmonie(struct harmonie *this_)
References mutabor::hidden::harmonie::bezugstaste, mutabor::hidden::taste::code, mutabor::hidden::harmonie::name, mutabor::hidden::taste::stern, mutabor::hidden::harmonie::tastenliste.
Referenced by mutabor_programm_einlesen.
static void mutabor::hidden::drucke_argument(struct argument *z_or_p)
References mutabor::hidden::parameter_list::index, mutabor::hidden::argument::integer, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_parameter, mutabor::hidden::parameter_list::name, mutabor::hidden::argument::parameter, mutabor::hidden::argument::u.
Referenced by mutabor_programm_einlesen, print_action.
static void mutabor::hidden::print_ausloeser(mutabor_box_type *box, struct ausloeser *this_)
References _mut, ausloeser_default, ausloeser_harmonie, mutabor::hidden::ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, mutabor::hidden::ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, mutabor::hidden::ausloeser::ausloeser_midi_in, ausloeser_taste, mutabor::hidden::ausloeser::ausloeser_taste, mutabor::hidden::ausloeser::ausloeser_typ, internal_error, mutabor_error_message, print_integersequenz, mutabor::hidden::ausloeser::u.
Referenced by mutabor_programm_einlesen.
static void mutabor::hidden::print_action(struct aktions_liste *action)
References aktion_aufruf, mutabor::hidden::aktions_liste::aktion_aufruf, aktion_harmony_analysis, aktion_midi_out, drucke_argument, mutabor::hidden::argument_list::next, STUB, mutabor::hidden::aktions_liste::u, UNREACHABLE.
Referenced by mutabor_programm_einlesen, print_action_list.
static void mutabor::hidden::print_action_list(struct aktions_liste *actionlist)
References print_action, TRACE.
Referenced by mutabor_programm_einlesen.
void mutabor::hidden::allgemeine_initialisierungen(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::ton::name, mutabor::hidden::ton::next, ton_absolut, mutabor::hidden::ton::ton_absolut, mutabor::hidden::mutabor_logic_parsed::ton_ohne_namen, mutabor::hidden::ton::ton_typ, TRACE, mutabor::hidden::ton::u, xmalloc.
Referenced by check_konsistenz.
int mutabor::hidden::ton_list_laenge(const struct ton *list)
References mutabor::hidden::ton::next, TRACE.
Referenced by berechne_toene_absolut, mutabor::BoxClass::Compile, expandiere_tonsystem, mutabor_programm_einlesen.
int mutabor::hidden::tonsystem_list_laenge(const struct tonsystem *list)
References mutabor::hidden::tonsystem::next, TRACE.
Referenced by mutabor::BoxClass::Compile.
int mutabor::hidden::umstimmungs_list_laenge(const struct umstimmung *list)
References mutabor::hidden::umstimmung::next, TRACE.
Referenced by check_konsistenz, mutabor::BoxClass::Compile.
int mutabor::hidden::logik_list_laenge(const struct logik *list)
References mutabor::hidden::logik::next, TRACE.
Referenced by check_konsistenz, mutabor::BoxClass::Compile, expand_decition_tree.
int mutabor::hidden::midi_list_laenge(const struct midiliste *list)
References mutabor::hidden::midiliste::next, TRACE.
Referenced by create_midi_scan_liste, mutabor::BoxClass::MidiOut.
int mutabor::hidden::get_logik_nummer(mutabor_box_type *box, const char *name, struct logik *liste)
References _mut, internal_error, mutabor_error_message, mutabor::hidden::logik::name, mutabor::hidden::logik::next, TRACE.
Referenced by expandiere_logik.
int mutabor::hidden::parameter_list_laenge(struct parameter_list *list)
References TRACE.
Referenced by check_aktionen, check_konsistenz.
int mutabor::hidden::argument_list_laenge(struct argument_list *list)
References TRACE.
Referenced by check_aktionen, check_konsistenz.
struct ton * mutabor::hidden::get_ton(mutabor_box_type *box, const char *name, struct ton *liste)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::ton::name, mutabor::hidden::ton::next, mutabor::hidden::mutabor_logic_parsed::ton_ohne_namen, TRACE.
Referenced by check_konsistenz, expandiere_tonsystem, get_komplex_frequenz.
struct intervall * mutabor::hidden::get_intervall(const char *name, struct intervall *liste)
References mutabor::hidden::intervall::name, mutabor::hidden::intervall::next, TRACE.
Referenced by check_komplex_intervall, get_komplex_faktor.
struct tonsystem * mutabor::hidden::parser_get_tonsystem(const char *name, struct tonsystem *liste)
References mutabor::hidden::tonsystem::name, mutabor::hidden::tonsystem::next, TRACE.
Referenced by check_aktionen, check_konsistenz, expandiere_logik, expandiere_name.
struct umstimmung * mutabor::hidden::get_umstimmung(const char *name, struct umstimmung *liste)
References mutabor::hidden::umstimmung::name, mutabor::hidden::umstimmung::next, TRACE.
Referenced by check_aktionen, check_konsistenz, expandiere_logik, expandiere_name.
struct harmonie * mutabor::hidden::get_harmonie(const char *name, struct harmonie *liste)
References mutabor::hidden::harmonie::name, mutabor::hidden::harmonie::next, TRACE.
Referenced by check_ausloeser, expand_pattern.
struct logik * mutabor::hidden::get_logik(const char *name, struct logik *liste)
References mutabor::hidden::logik::name, mutabor::hidden::logik::next, TRACE.
Referenced by check_aktionen, check_konsistenz, expandiere_name.
void mutabor::hidden::init_integersequenz(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_integers, TRACE.
Referenced by yyparse.
void mutabor::hidden::get_new_integer_in_integersequenz(mutabor_box_type *box, int wert)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_integers, mutabor::hidden::midiliste::next, TRACE, xmalloc.
Referenced by yyparse.
static struct midiliste* mutabor::hidden::get_last_integersequenz(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_integers, TRACE.
Referenced by get_ausloeser_midi_in, get_new_aktion_midi_out_element, get_umstimmung_midi_out.
void mutabor::hidden::init_parameter_liste(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_names, TRACE.
struct parameter_list * mutabor::hidden::get_new_name_in_parameterlist(mutabor_box_type *box, const char *name)
References TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::enumerate_parameters(mutabor_box_type *box, struct parameter_list *parameters)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::parameter_count.
Referenced by yyparse.
static struct parameter_list* mutabor::hidden::get_parameter_by_name(mutabor_box_type *box, const char *search_name, struct parameter_list *node)
References mutabor::hidden::parameter_list::next, TRACE.
Referenced by get_umstimmung_umstimm_case, get_umstimmung_umstimmungs_bund, link_arguments_to_parameters.
void mutabor::hidden::print_argumentliste(struct argument_list *this_)
References _mut, mutabor::hidden::argument::argument_type, mutabor::hidden::argument::integer, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_parameter, mutabor::hidden::parameter_list::name, mutabor::hidden::argument::parameter, TRACE, mutabor::hidden::argument::u.
void mutabor::hidden::init_argument_liste(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_argumente, TRACE.
struct argument_list * mutabor::hidden::get_new_number_in_argument_list(mutabor_box_type *box, double number)
References mutabor::hidden::argument::argument_type, mutabor::hidden::argument::integer, mutabor_argument_integer, TRACE, mutabor::hidden::argument::u, xmalloc.
Referenced by yyparse.
struct argument_list * mutabor::hidden::get_new_name_in_argument_list(mutabor_box_type *box, const char *parameter_name)
References mutabor::hidden::argument::argument_type, mutabor_argument_parameter, mutabor::hidden::parameter_list::name, mutabor::hidden::argument::parameter, TRACE, mutabor::hidden::argument::u, xmalloc.
Referenced by yyparse.
struct argument_list * mutabor::hidden::get_new_distance_in_argument_list(mutabor_box_type *box)
References mutabor::hidden::argument::argument_type, mutabor_argument_distance, TRACE, xmalloc.
Referenced by yyparse.
struct argument_list * mutabor::hidden::get_new_anchor_in_argument_list(mutabor_box_type *box)
References mutabor::hidden::argument::argument_type, mutabor_argument_anchor, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::init_aktions_liste(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_aktionen, TRACE.
Referenced by yyparse.
void mutabor::hidden::get_new_aktion_aufruf_element(mutabor_box_type *box, const char *name, struct argument_list *arguments)
References aktion_aufruf, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_aktionen, mutabor::hidden::aktions_liste::next, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_new_aktion_midi_out_element(mutabor_box_type *box)
References aktion_midi_out, mutabor::hidden::mutabor_box_type::file, get_last_integersequenz, mutabor::hidden::mutabor_logic_parsed::list_of_aktionen, mutabor::hidden::aktions_liste::next, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_new_aktion_harmony_analysis(mutabor_box_type *box)
References aktion_harmony_analysis, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_aktionen, mutabor::hidden::aktions_liste::next, TRACE, xmalloc.
Referenced by yyparse.
static struct aktions_liste* mutabor::hidden::get_last_aktions_liste(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_aktionen, TRACE.
Referenced by get_new_anweisung, get_new_logik, get_umstimmung_umstimmungs_bund, get_umstimmungs_case_default_element, get_umstimmungs_case_zahl_element.
void mutabor::hidden::init_komplex_ton_list(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::the_komplex_liste, TRACE.
Referenced by yyparse.
void mutabor::hidden::get_new_faktor_anteil(mutabor_box_type *box, double f, const char *name)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::komplex_intervall::next, mutabor::hidden::mutabor_logic_parsed::the_komplex_liste, TRACE, xmalloc.
Referenced by yyparse.
struct komplex_intervall* mutabor::hidden::get_last_komplex_intervall(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::the_komplex_liste, TRACE.
Referenced by get_new_intervall_komplex, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_new_umstimm_expression_negative, get_new_umstimm_expression_positive, get_umstimmung_wiederholung_abs, get_umstimmung_wiederholung_abs_negative, get_umstimmung_wiederholung_rel_negative, get_umstimmung_wiederholung_rel_positive.
bool mutabor::hidden::mutabor_programm_einlesen(mutabor_box_type *box, const char *logic)
References mutabor::hidden::anweisung::aktion, mutabor::hidden::logik::anweisungsliste, mutabor::hidden::anweisung::ausloeser, mutabor::hidden::logik::ausloeser, berechne_intervalle_absolut, berechne_toene_absolut, mutabor::hidden::case_liste::case_aktion, mutabor::hidden::case_liste::case_label, check_konsistenz, mutabor::hidden::mutabor_scanner_data::data, DEBUGLOG2, drucke_argument, drucke_harmonie, drucke_ton, mutabor::hidden::mutabor_box_type::file, get_instrument_dekl, get_new_intervall, get_new_ton_absolut, intervall_absolut, mutabor::hidden::intervall::intervall_absolut, mutabor::hidden::intervall::intervall_typ, mutabor::hidden::case_liste::is_default, isDebugFlag, mutabor::hidden::mutabor_logic_parsed::list_of_config_instrumente, mutabor::hidden::mutabor_logic_parsed::list_of_constants, mutabor::hidden::mutabor_logic_parsed::list_of_harmonien, mutabor::hidden::mutabor_logic_parsed::list_of_instrumente, mutabor::hidden::mutabor_logic_parsed::list_of_intervalle, mutabor::hidden::mutabor_logic_parsed::list_of_logiken, mutabor::hidden::mutabor_logic_parsed::list_of_toene, mutabor::hidden::mutabor_logic_parsed::list_of_tonsysteme, mutabor::hidden::mutabor_logic_parsed::list_of_umstimmungen, mutabor::hidden::instrument::midi_bis, mutabor::hidden::instrument::midi_in, mutabor::hidden::instrument::midi_von, mutabor::hidden::mutabor_logic_parsed::mutex, mutabor::hidden::parameter_list::name, mutabor::hidden::intervall::name, mutabor::hidden::ton::name, mutabor::hidden::tonsystem::name, mutabor::hidden::umstimmung::name, mutabor::hidden::logik::name, mutabor::hidden::parameter_list::next, mutabor::hidden::intervall::next, mutabor::hidden::ton::next, mutabor::hidden::tonsystem::next, mutabor::hidden::umstimmung::next, mutabor::hidden::harmonie::next, mutabor::hidden::logik::next, mutabor::hidden::instrument::next, mutabor::hidden::umstimmung::parameter_liste, mutabor::hidden::logik::parser_tuning, mutabor::hidden::tonsystem::periode, mutabor::hidden::mutabor_scanner_data::pos, print_action, print_action_list, print_ausloeser, mutabor::hidden::mutabor_box_type::scanner, STUB, mutabor::hidden::tonsystem::taste, mutabor::hidden::tonsystem::toene, ton_list_laenge, TRACE, mutabor::hidden::intervall::u, mutabor::hidden::umstimmung::u, umstimmung_breite_abs, umstimmung_breite_rel, mutabor::hidden::umstimmung::umstimmung_breite_rel, umstimmung_midi_out, umstimmung_taste_abs, umstimmung_taste_rel, mutabor::hidden::umstimmung::umstimmung_taste_rel, umstimmung_toene_veraendert, mutabor::hidden::umstimmung::umstimmung_toene_veraendert, umstimmung_umstimmungs_case, mutabor::hidden::umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, mutabor::hidden::umstimmung::umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, yyparse.
Referenced by mutabor::BoxClass::Compile, GMutCompile, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testCycles, boxTest::testFindKeyByKey, boxTest::testHaronic_form.
void mutabor::hidden::print_integersequenz(struct midiliste *this_)
References mutabor::hidden::midiliste::midi_code, mutabor::hidden::midiliste::next.
Referenced by print_ausloeser.
void mutabor::hidden::get_new_intervall(mutabor_box_type *box, const char *name, double wert)
References _mut, compiler_error, mutabor::hidden::mutabor_box_type::file, intervall_absolut, mutabor::hidden::mutabor_logic_parsed::list_of_intervalle, mutabor_error_message, mutabor::hidden::intervall::next, TRACE, xmalloc.
Referenced by mutabor_programm_einlesen, yyparse.
void mutabor::hidden::get_new_intervall_komplex(mutabor_box_type *box, const char *name)
References _mut, compiler_error, mutabor::hidden::mutabor_box_type::file, get_last_komplex_intervall, intervall_komplex, mutabor::hidden::mutabor_logic_parsed::list_of_intervalle, mutabor_error_message, mutabor::hidden::intervall::next, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_new_ton_absolut(mutabor_box_type *box, const char *name, double wert)
References _mut, compiler_error, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_toene, mutabor_error_message, mutabor::hidden::ton::next, ton_absolut, TRACE, xmalloc.
Referenced by mutabor_programm_einlesen, yyparse.
void mutabor::hidden::get_new_ton_komplex_positive(mutabor_box_type *box, const char *name, const char *bezugston)
References _mut, compiler_error, mutabor::hidden::mutabor_box_type::file, get_last_komplex_intervall, mutabor::hidden::mutabor_logic_parsed::list_of_toene, mutabor_error_message, mutabor::hidden::ton::next, ton_komplex, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_new_ton_komplex_negative(mutabor_box_type *box, const char *name, const char *bezugston)
References _mut, compiler_error, mutabor::hidden::mutabor_box_type::file, get_last_komplex_intervall, internal_error, mutabor::hidden::mutabor_logic_parsed::list_of_toene, mutabor_error_message, mutabor::hidden::ton::next, ton_komplex, TRACE, xmalloc.
Referenced by yyparse.
static const char* mutabor::hidden::check_name(mutabor_box_type *box, const char *name)
References _mut, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_logiken, mutabor::hidden::mutabor_logic_parsed::list_of_tonsysteme, mutabor::hidden::mutabor_logic_parsed::list_of_umstimmungen, mutabor::hidden::logik::next.
Referenced by get_new_logik, get_new_tonsystem, init_umstimmung.
void mutabor::hidden::init_ton_liste(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::ton_liste, TRACE.
Referenced by yyparse.
void mutabor::hidden::get_new_ton_in_tonsystem(mutabor_box_type *box, const char *name)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::ton::next, mutabor::hidden::mutabor_logic_parsed::ton_liste, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_new_tonsystem(mutabor_box_type *box, const char *name, int taste)
References _mut, check_name, compiler_error, error, mutabor::hidden::mutabor_box_type::file, get_last_komplex_intervall, mutabor::hidden::mutabor_logic_parsed::list_of_tonsysteme, mutabor_error_message, mutabor::hidden::mutabor_logic_parsed::ton_liste, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_new_tonsystem_negative(mutabor_box_type *box, const char *name, int taste)
References _mut, compiler_error, mutabor::hidden::mutabor_box_type::file, get_last_komplex_intervall, internal_error, mutabor::hidden::mutabor_logic_parsed::list_of_tonsysteme, mutabor_error_message, mutabor::hidden::tonsystem::next, mutabor::hidden::mutabor_logic_parsed::ton_liste, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::init_umstimmung(mutabor_box_type *box, const char *name)
References _mut, check_name, compiler_error, error, mutabor::hidden::mutabor_box_type::file, mutabor_error_message, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, TRACE, xmalloc.
Referenced by yyparse.
static void mutabor::hidden::link_arguments_to_parameters(mutabor_box_type *box, struct argument_list *arguments, struct parameter_list *parameters, struct umstimmung *retuning)
References _mut, compiler_error, get_parameter_by_name, internal_error, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_parameter, mutabor_error_message, mutabor::hidden::umstimmung::name.
Referenced by get_new_umstimmung, get_umstimmung_umstimm_case, get_umstimmung_umstimmungs_bund.
void mutabor::hidden::get_new_umstimmung(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, link_arguments_to_parameters, mutabor::hidden::mutabor_logic_parsed::list_of_umstimmungen, mutabor::hidden::umstimmung::next, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, TRACE.
Referenced by yyparse.
void mutabor::hidden::eintrage_parameterliste_in_umstimmung(mutabor_box_type *box, struct umstimmung *ret, parameter_list *list)
References TRACE.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_taste_abs(mutabor_box_type *box, argument_list *argument)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_taste_abs.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_taste_rel(mutabor_box_type *box, argument_list *argument, char vorzeichen)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_taste_rel, mutabor::hidden::umstimmung::umstimmung_taste_rel.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_breite_abs(mutabor_box_type *box, argument_list *argument)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_breite_abs.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_breite_rel(mutabor_box_type *box, argument_list *argument, char vorzeichen)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_breite_rel, mutabor::hidden::umstimmung::umstimmung_breite_rel.
Referenced by yyparse.
void mutabor::hidden::init_umstimm_expression_list(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_tonliste, TRACE.
Referenced by yyparse.
void mutabor::hidden::get_new_umstimm_expression(mutabor_box_type *box, const char *bezugston)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::ton::next, mutabor::hidden::mutabor_logic_parsed::tmp_tonliste, ton_komplex, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_new_umstimm_expression_positive(mutabor_box_type *box, const char *bezugston)
References mutabor::hidden::mutabor_box_type::file, get_last_komplex_intervall, mutabor::hidden::ton::next, mutabor::hidden::mutabor_logic_parsed::tmp_tonliste, ton_komplex, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_new_umstimm_expression_negative(mutabor_box_type *box, const char *bezugston)
References mutabor::hidden::komplex_intervall::faktor, mutabor::hidden::mutabor_box_type::file, get_last_komplex_intervall, mutabor::hidden::ton::next, mutabor::hidden::mutabor_logic_parsed::tmp_tonliste, ton_komplex, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_tonhoehe_veraendert(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_tonliste, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, umstimmung_toene_veraendert, mutabor::hidden::umstimmung::umstimmung_toene_veraendert.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_wiederholung_abs(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, get_last_komplex_intervall, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, umstimmung_wiederholung_abs, mutabor::hidden::umstimmung::umstimmung_wiederholung_abs.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_wiederholung_abs_negative(mutabor_box_type *box)
References _mut, mutabor::hidden::mutabor_box_type::file, get_last_komplex_intervall, internal_error, mutabor_error_message, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, umstimmung_wiederholung_abs, mutabor::hidden::umstimmung::umstimmung_wiederholung_abs.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_wiederholung_rel_positive(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, get_last_komplex_intervall, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_wiederholung_rel, mutabor::hidden::umstimmung::umstimmung_wiederholung_rel.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_wiederholung_rel_negative(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, get_last_komplex_intervall, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_wiederholung_rel, mutabor::hidden::umstimmung::umstimmung_wiederholung_rel.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_umstimmungs_bund(mutabor_box_type *box)
References _mut, aktion_aufruf, mutabor::hidden::aktions_liste::aktion_aufruf, mutabor::hidden::argument_list::argument, mutabor::hidden::argument::argument_type, compiler_error, mutabor::hidden::mutabor_box_type::file, get_last_aktions_liste, get_parameter_by_name, link_arguments_to_parameters, mutabor_argument_parameter, mutabor_error_message, mutabor::hidden::parameter_list::name, mutabor::hidden::umstimmung::name, mutabor::hidden::argument::parameter, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, TRACE, mutabor::hidden::argument::u, umstimmung_umstimmungsbund, mutabor::hidden::umstimmung::umstimmung_umstimmungsbund.
Referenced by yyparse.
void mutabor::hidden::get_umstimmungs_case_zahl_element(mutabor_box_type *box, int konstante)
References mutabor::hidden::mutabor_box_type::file, get_last_aktions_liste, mutabor::hidden::case_liste::next, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_umstimmungs_case_default_element(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, get_last_aktions_liste, MUTABOR_NO_CASE_LABEL, mutabor::hidden::case_liste::next, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::init_umstimmungs_case_liste(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_umstimm_case(mutabor_box_type *box, argument_list *argument)
References _mut, aktion_aufruf, mutabor::hidden::aktions_liste::aktion_aufruf, mutabor::hidden::argument_list::argument, compiler_error, mutabor::hidden::mutabor_box_type::file, get_parameter_by_name, link_arguments_to_parameters, mutabor_argument_parameter, mutabor_error_message, mutabor::hidden::parameter_list::name, mutabor::hidden::umstimmung::name, mutabor::hidden::argument::parameter, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE, mutabor::hidden::argument::u, umstimmung_umstimmungs_case, mutabor::hidden::umstimmung::umstimmung_umstimmungs_case.
Referenced by yyparse.
void mutabor::hidden::get_umstimmung_midi_out(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, get_last_integersequenz, mutabor::hidden::mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_midi_out, mutabor::hidden::umstimmung::umstimmung_midi_out.
Referenced by yyparse.
void mutabor::hidden::init_tastenliste(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_tastenliste, TRACE.
Referenced by yyparse.
void mutabor::hidden::get_new_taste(mutabor_box_type *box, int taste, char stern)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::taste::next, mutabor::hidden::mutabor_logic_parsed::tmp_tastenliste, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_new_harmonie(mutabor_box_type *box, const char *name, int bezugstaste)
References _mut, compiler_error, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::list_of_harmonien, mutabor_error_message, mutabor::hidden::harmonie::next, mutabor::hidden::mutabor_logic_parsed::tmp_tastenliste, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_harmoniebezeichner(mutabor_box_type *box, enum harmony_type flags, int vor_taste, const char *name, int nach_taste)
Save a harmony temporary harmony descriptor in the parser data.
box Box the parser belongs to. flags Flags that tell which keys to use. vor_taste Lowest key of the described harmony. name Name of the harmony that shall be used nach_taste Highest key of the described harmony
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_harmony_flags, mutabor::hidden::mutabor_logic_parsed::tmp_nach_taste, mutabor::hidden::mutabor_logic_parsed::tmp_name, mutabor::hidden::mutabor_logic_parsed::tmp_vor_taste.
Referenced by yyparse.
void mutabor::hidden::init_ausloeser(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_ausloeser, TRACE.
Referenced by yyparse.
struct ausloeser* mutabor::hidden::get_last_ausloeser(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_ausloeser, TRACE.
Referenced by get_new_anweisung, get_new_logik.
void mutabor::hidden::get_ausloeser_default(mutabor_box_type *box)
References ausloeser_default, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_ausloeser, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_ausloeser_harmonie(mutabor_box_type *box)
References ausloeser_harmonie, mutabor::hidden::ausloeser::ausloeser_harmonie, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_ausloeser, mutabor::hidden::mutabor_logic_parsed::tmp_harmony_flags, mutabor::hidden::mutabor_logic_parsed::tmp_nach_taste, mutabor::hidden::mutabor_logic_parsed::tmp_name, mutabor::hidden::mutabor_logic_parsed::tmp_vor_taste, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_ausloeser_harmonie_form(mutabor_box_type *box)
References ausloeser_harmonie_form, mutabor::hidden::ausloeser::ausloeser_harmonie_form, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_ausloeser, mutabor::hidden::mutabor_logic_parsed::tmp_harmony_flags, mutabor::hidden::mutabor_logic_parsed::tmp_nach_taste, mutabor::hidden::mutabor_logic_parsed::tmp_name, mutabor::hidden::mutabor_logic_parsed::tmp_vor_taste, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_ausloeser_taste(mutabor_box_type *box, const char *name)
References _mut, ausloeser_taste, mutabor::hidden::ausloeser::ausloeser_taste, compiler_error, mutabor::hidden::mutabor_box_type::file, mutabor_error_message, mutabor::hidden::mutabor_logic_parsed::tmp_ausloeser, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_ausloeser_midi_in(mutabor_box_type *box)
References ausloeser_midi_in, mutabor::hidden::ausloeser::ausloeser_midi_in, mutabor::hidden::mutabor_box_type::file, get_last_integersequenz, mutabor::hidden::mutabor_logic_parsed::tmp_ausloeser, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::init_anweisungs_liste(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_anweisungsliste, TRACE.
Referenced by yyparse.
struct anweisung* mutabor::hidden::get_last_anweisungs_liste(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::tmp_anweisungsliste, TRACE.
Referenced by vervollstaendige_logik.
void mutabor::hidden::get_new_anweisung(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, get_last_aktions_liste, get_last_ausloeser, mutabor::hidden::anweisung::next, mutabor::hidden::mutabor_logic_parsed::tmp_anweisungsliste, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::get_new_logik(mutabor_box_type *box, const char *name)
References _mut, check_name, compiler_error, error, mutabor::hidden::mutabor_box_type::file, get_last_aktions_liste, get_last_ausloeser, mutabor::hidden::mutabor_logic_parsed::list_of_logiken, mutabor_error_message, mutabor::hidden::logik::next, TRACE, xmalloc.
Referenced by yyparse.
void mutabor::hidden::vervollstaendige_logik(mutabor_box_type *box)
References mutabor::hidden::mutabor_box_type::file, get_last_anweisungs_liste, mutabor::hidden::mutabor_logic_parsed::list_of_logiken, mutabor::hidden::logik::next, TRACE.
Referenced by yyparse.
void mutabor::hidden::get_instrument_dekl(mutabor_box_type *box, int midi_in, int midi_von, int midi_bis, int midi_umleit, struct instrument **list_to_insert)
References _mut, compiler_error, mutabor_error_message, mutabor::hidden::instrument::next, TRACE, xmalloc.
Referenced by mutabor_programm_einlesen, SetChannels, yyparse.
static void mutabor::hidden::belege_toene(struct ton **toene, struct ton *liste)
References mutabor::hidden::ton::next, TRACE.
Referenced by berechne_toene_absolut.
static int mutabor::hidden::ton_nummer(mutabor_box_type *box, const char *name)
References _mut, mutabor::hidden::mutabor_logic_parsed::anzahl_toene, compiler_error, mutabor::hidden::mutabor_box_type::file, mutabor_error_message, mutabor::hidden::ton::name, mutabor::hidden::mutabor_logic_parsed::toene, TRACE.
Referenced by berechne_toene_absolut, berechne_ton_endgueltig.
static void mutabor::hidden::test_zyklen(mutabor_box_type *box, int startknoten)
References _mut, mutabor::hidden::mutabor_logic_parsed::anzahl_toene, compiler_error, mutabor::hidden::mutabor_box_type::file, mutabor_adjacent, mutabor_error_message, mutabor::hidden::ton::name, mutabor::hidden::mutabor_logic_parsed::toene, ton_absolut, mutabor::hidden::ton::ton_absolut, mutabor::hidden::mutabor_logic_parsed::tone_matrix, TRACE, mutabor::hidden::mutabor_logic_parsed::visited_tones.
Referenced by berechne_intervalle_absolut, berechne_toene_absolut, test_zyklen.
static void mutabor::hidden::berechne_ton_endgueltig(mutabor_box_type *box, int k)
References _mut, mutabor::hidden::mutabor_box_type::file, get_wert_komplex_intervall, internal_error, mutabor_error_message, mutabor::hidden::mutabor_logic_parsed::toene, ton_absolut, mutabor::hidden::ton::ton_absolut, ton_komplex, mutabor::hidden::ton::ton_komplex, ton_nummer, mutabor::hidden::ton::ton_typ, TRACE, mutabor::hidden::ton::u.
Referenced by berechne_toene_absolut.
int mutabor::hidden::enthalten_in_tastenliste(int taste, struct taste *lauf)
References TRACE.
Referenced by check_ausloeser.
int mutabor::hidden::case_label_enthalten_in_case_liste(double case_label, struct case_liste *lauf)
References TRACE.
Referenced by check_konsistenz.
static void mutabor::hidden::check_ausloeser(mutabor_box_type *box, struct ausloeser *ausloeser, const char *name)
References _mut, ausloeser_harmonie, mutabor::hidden::ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, mutabor::hidden::ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, mutabor::hidden::ausloeser::ausloeser_midi_in, mutabor::hidden::ausloeser::ausloeser_typ, compiler_error, compiler_warning, enthalten_in_tastenliste, mutabor::hidden::mutabor_box_type::file, get_harmonie, mutabor::hidden::mutabor_logic_parsed::list_of_harmonien, mutabor::hidden::midiliste::midi_code, mutabor_error_message, mutabor_harmony_invalid, mutabor_harmony_postkey, mutabor_harmony_prekey, mutabor::hidden::harmonie::tastenliste, TRACE, mutabor::hidden::ausloeser::u.
Referenced by check_konsistenz.
static void mutabor::hidden::check_aktionen(mutabor_box_type *box, struct aktions_liste *aktionen, const char *name)
References _mut, aktion_aufruf, mutabor::hidden::aktions_liste::aktion_aufruf, aktion_harmony_analysis, aktion_midi_out, mutabor::hidden::aktions_liste::aktion_midi_out, mutabor::hidden::aktions_liste::aktions_typ, argument_list_laenge, compiler_error, compiler_warning, mutabor::hidden::mutabor_box_type::file, get_logik, get_umstimmung, internal_error, mutabor::hidden::mutabor_logic_parsed::list_of_logiken, mutabor::hidden::mutabor_logic_parsed::list_of_tonsysteme, mutabor::hidden::mutabor_logic_parsed::list_of_umstimmungen, mutabor::hidden::midiliste::midi_code, mutabor_error_message, mutabor::hidden::midiliste::next, parameter_list_laenge, mutabor::hidden::umstimmung::parameter_liste, parser_get_tonsystem, TRACE, mutabor::hidden::aktions_liste::u, xcalloc.
Referenced by check_konsistenz.
static void mutabor::hidden::belege_zyklenfeld(struct umst_oder_logik *zyklen_feld, struct umstimmung *liste1, struct logik *liste2)
References mutabor::hidden::umst_oder_logik::logik, mutabor::hidden::umstimmung::next, mutabor::hidden::logik::next, TRACE, typ_logik, typ_umstimmung, mutabor::hidden::umst_oder_logik::u, mutabor::hidden::umst_oder_logik::umst_oder_logik_typ, mutabor::hidden::umst_oder_logik::umstimmung.
Referenced by check_konsistenz.
static int mutabor::hidden::test_zyklen_nummer(mutabor_box_type *box, const char *name)
References _mut, mutabor::hidden::mutabor_logic_parsed::anzahl_umstimmungen_und_logiken, compiler_error, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::umst_oder_logik::logik, mutabor_error_message, mutabor::hidden::umstimmung::name, mutabor::hidden::logik::name, TRACE, typ_logik, typ_umstimmung, mutabor::hidden::umst_oder_logik::u, mutabor::hidden::umst_oder_logik::umst_oder_logik_typ, mutabor::hidden::umst_oder_logik::umstimmung, mutabor::hidden::mutabor_logic_parsed::zyklen_feld.
Referenced by check_konsistenz.
static void mutabor::hidden::u_test_zyklen(mutabor_box_type *box, int startknoten)
References _mut, mutabor::hidden::mutabor_logic_parsed::anzahl_umstimmungen_und_logiken, compiler_error, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::umst_oder_logik::logik, mutabor_error_message, mutabor_u_adjacent, mutabor::hidden::umstimmung::name, mutabor::hidden::logik::name, TRACE, typ_logik, typ_umstimmung, mutabor::hidden::umst_oder_logik::u, mutabor::hidden::umstimmung::u, mutabor::hidden::mutabor_logic_parsed::u_matrix, mutabor::hidden::mutabor_logic_parsed::u_visited, mutabor::hidden::umst_oder_logik::umst_oder_logik_typ, mutabor::hidden::umst_oder_logik::umstimmung, mutabor::hidden::umstimmung::umstimmung_typ, umstimmung_umstimmungsbund, mutabor::hidden::umstimmung::umstimmung_umstimmungsbund, mutabor::hidden::mutabor_logic_parsed::zyklen_feld.
Referenced by check_konsistenz.
bool mutabor::hidden::TSChanged(mutabor_box_type *box)
References mutabor::hidden::TSYS::breite, mutabor::hidden::mutabor_box_type::last_tonesystem, mutabor::hidden::mutabor_box_type::tonesystem.
void mutabor::hidden::GetInDevicesMode(enum MutaborModeType *mode)
References mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList.
char mutabor::hidden::GetChannels(mutabor_box_type *box, char start, int &base, int &from, int &to, int &thru)
References mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::lauf_instrument, mutabor::hidden::mutabor_logic_parsed::list_of_config_instrumente.
Referenced by mutaborGUI::MutBoxShape::AddChannel.
void mutabor::hidden::SetChannels(mutabor_box_type *box, int base, int from, int to, int thru)
References mutabor::hidden::mutabor_box_type::file, get_instrument_dekl, mutabor::hidden::mutabor_logic_parsed::list_of_config_instrumente.
bool mutabor::hidden::GetELine(const std::string &p, size_t &i, std::string &s)
DevType mutabor::hidden::Str2DT(const std::string &type)
bool mutabor::hidden::GetLine(char **p, char *s)
static struct do_aktion * mutabor::hidden::expandiere_name(mutabor_box_type *box, const char *name, struct argument_list *parameter, struct interpreter_argument_list *bezugs_liste)
References _, compiler_error, expandiere_logik, expandiere_tonsystem, expandiere_umstimmung, mutabor::hidden::mutabor_box_type::file, generate_argument_list, get_logik, get_umstimmung, mutabor::hidden::mutabor_logic_parsed::list_of_logiken, mutabor::hidden::mutabor_logic_parsed::list_of_tonsysteme, mutabor::hidden::mutabor_logic_parsed::list_of_umstimmungen, mutabor_error_message, parser_get_tonsystem, TRACE.
Referenced by expand_aktions_liste.
static struct do_aktion * mutabor::hidden::expandiere_umstimmung(mutabor_box_type *box, struct umstimmung *the_umstimmung, struct interpreter_argument_list *aktuelle_parameter)
References _, mutabor::hidden::umstimmung::argument_liste, mutabor::hidden::do_aktion::arguments, aufruf_midi_out, mutabor::hidden::do_aktion::aufruf_midi_out, aufruf_umst_breite_abs, aufruf_umst_breite_rel, mutabor::hidden::do_aktion::aufruf_umst_breite_rel, aufruf_umst_taste_abs, aufruf_umst_taste_rel, mutabor::hidden::do_aktion::aufruf_umst_taste_rel, aufruf_umst_toene_veraendert, mutabor::hidden::do_aktion::aufruf_umst_toene_veraendert, aufruf_umst_umst_bund, aufruf_umst_umst_case, mutabor::hidden::do_aktion::aufruf_umst_umst_case, aufruf_umst_wiederholung_abs, mutabor::hidden::do_aktion::aufruf_umst_wiederholung_abs, aufruf_umst_wiederholung_rel, mutabor::hidden::do_aktion::aufruf_umst_wiederholung_rel, expand_aktions_liste, expand_case_liste, expand_tonliste, generate_argument_list, get_wert_komplex_intervall, internal_error, mutabor_convert_factor_to_interval, mutabor_error_message, mutabor::hidden::do_aktion::name, mutabor::hidden::do_aktion::next, resolve_parameters, mutabor::hidden::do_aktion::retuning, mutabor::hidden::do_aktion::secondary_arguments, TRACE, mutabor::hidden::umstimmung::u, umstimmung_breite_abs, umstimmung_breite_rel, mutabor::hidden::umstimmung::umstimmung_breite_rel, umstimmung_midi_out, mutabor::hidden::umstimmung::umstimmung_midi_out, umstimmung_taste_abs, umstimmung_taste_rel, mutabor::hidden::umstimmung::umstimmung_taste_rel, umstimmung_toene_veraendert, mutabor::hidden::umstimmung::umstimmung_toene_veraendert, umstimmung_umstimmungs_case, mutabor::hidden::umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, mutabor::hidden::umstimmung::umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, mutabor::hidden::umstimmung::umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, xfree, xmalloc.
Referenced by expandiere_logik, expandiere_name.
static struct do_aktion * mutabor::hidden::expandiere_midi(mutabor_box_type *box, struct midiliste *liste)
References _, aufruf_midi_out, mutabor::hidden::do_aktion::aufruf_midi_out, TRACE, xmalloc.
Referenced by expand_aktions_liste.
static struct do_aktion * mutabor::hidden::expand_harmony_analysis(mutabor_box_type *box)
References _, aufruf_harmony_analysis, TRACE, xmalloc.
Referenced by expand_aktions_liste.
void mutabor::hidden::insert_in_lokale_liste(mutabor_box_type *box, struct do_aktion *action, struct anweisung *lauf, struct logik *logic)
References _, mutabor::hidden::anweisung::aktion, mutabor::hidden::anweisung::ausloeser, ausloeser_default, ausloeser_harmonie, mutabor::hidden::ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, mutabor::hidden::ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, mutabor::hidden::ausloeser::ausloeser_midi_in, ausloeser_taste, create_midi_scan_liste, expand_aktions_liste, expand_pattern, mutabor::hidden::logik::harmony_list, internal_error, mutabor::hidden::logik::keystroke_list, mutabor::hidden::logik::midi_input_list, mutabor_error_message, mutabor_harmony_invalid, mutabor_is_else_path, mutabor_is_harmonic_form, mutabor_is_no_harmonic_form, mutabor::hidden::logik::name, mutabor::hidden::midi_ereignis::next, mutabor::hidden::keyboard_ereignis::next, mutabor::hidden::harmonie_ereignis::next, TRACE, mutabor::hidden::ausloeser::u, xmalloc.
Referenced by expand_decition_tree, expandiere_logik.
static struct do_aktion * mutabor::hidden::expand_aktions_liste(mutabor_box_type *box, struct aktions_liste *the_liste, struct interpreter_argument_list *current_parameters)
References _, aktion_aufruf, mutabor::hidden::aktions_liste::aktion_aufruf, aktion_harmony_analysis, aktion_midi_out, mutabor::hidden::aktions_liste::aktion_midi_out, expand_harmony_analysis, expandiere_midi, expandiere_name, internal_error, mutabor_error_message, mutabor::hidden::do_aktion::next, TRACE.
Referenced by expand_case_liste, expandiere_logik, expandiere_umstimmung, insert_in_lokale_liste.
double mutabor::hidden::get_komplex_faktor(mutabor_box_type *box, struct komplex_intervall *lauf)
References _, compiler_error, mutabor::hidden::komplex_intervall::faktor, mutabor::hidden::mutabor_box_type::file, get_intervall, internal_error, intervall_absolut, mutabor::hidden::intervall::intervall_absolut, intervall_komplex, mutabor::hidden::intervall::intervall_komplex, mutabor::hidden::mutabor_logic_parsed::list_of_intervalle, mutabor_error_message, mutabor::hidden::komplex_intervall::name, TRACE.
Referenced by expand_tonliste, get_komplex_frequenz.
double mutabor::hidden::get_komplex_frequenz(mutabor_box_type *box, struct ton *dieser)
References mutabor::hidden::mutabor_box_type::file, get_komplex_faktor, get_ton, mutabor::hidden::mutabor_logic_parsed::list_of_toene, mutabor::hidden::ton::ton_absolut, mutabor::hidden::ton::ton_komplex, mutabor::hidden::ton::u.
Referenced by expand_tonliste.
void mutabor::hidden::fprint_argument(mutabor_box_type *box, FILE *zieldatei, struct argument *argument)
References _, mutabor::hidden::argument::integer, internal_error, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_parameter, mutabor_error_message, mutabor::hidden::parameter_list::name, mutabor::hidden::argument::parameter, TRACE.
static void mutabor::hidden::reduce_argument(mutabor_box_type *box, struct interpreter_argument_list *list, size_t index, struct interpreter_argument_list *reference)
References mutabor::hidden::interpreter_argument::constant, mutabor::hidden::interpreter_argument_list::data, mutabor::hidden::interpreter_argument::index, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, mutabor::hidden::interpreter_argument_list::types.
Referenced by generate_argument_list.
static struct interpreter_argument_list* mutabor::hidden::generate_argument_list(mutabor_box_type *box, struct argument_list *element, struct interpreter_argument_list *bezugs_liste)
References _, mutabor::hidden::argument_list::argument, mutabor::hidden::argument::argument_type, mutabor::hidden::interpreter_argument::constant, mutabor::hidden::interpreter_argument_list::data, mutabor::hidden::mutabor_box_type::file, if, mutabor::hidden::interpreter_argument::index, internal_error, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, mutabor_error_message, mutabor::hidden::argument_list::next, mutabor::hidden::mutabor_logic_parsed::parameter_count, reduce_argument, mutabor::hidden::interpreter_argument_list::size, TRACE, mutabor::hidden::interpreter_argument_list::types, xcalloc, xmalloc.
Referenced by expandiere_name, expandiere_umstimmung.
static void mutabor::hidden::resolve_parameters(mutabor_box_type *box, struct interpreter_argument_list *target, struct interpreter_argument_list *reference)
References _, mutabor::hidden::interpreter_argument_list::data, mutabor::hidden::interpreter_argument::index, internal_error, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, mutabor_error_message, mutabor::hidden::interpreter_argument_list::size, mutabor::hidden::interpreter_argument_list::types.
Referenced by expandiere_umstimmung.
static struct ton_einstell* mutabor::hidden::expand_tonliste(mutabor_box_type *box, struct ton *the_tonliste)
References _, einstell_absolut, einstell_gleich, einstell_relativ, einstell_stumm, get_komplex_faktor, get_komplex_frequenz, internal_error, mutabor::hidden::ton_einstell::interval, mutabor_convert_factor_to_interval, mutabor_convert_frequency_to_tone, mutabor_error_message, mutabor::hidden::ton::name, ton_absolut, mutabor::hidden::ton::ton_absolut, ton_komplex, mutabor::hidden::ton::ton_komplex, mutabor::hidden::ton_einstell::tone, TRACE, mutabor::hidden::ton::u, xmalloc.
Referenced by expandiere_umstimmung.
static struct do_aktion* mutabor::hidden::expandiere_tonsystem(mutabor_box_type *box, struct tonsystem *the_tonsystem)
References mutabor::hidden::MUT_INTERVAL::active, aufruf_tonsystem, mutabor::hidden::do_aktion::aufruf_tonsystem, mutabor::hidden::mutabor_box_type::file, get_ton, get_wert_komplex_intervall, mutabor::hidden::mutabor_logic_parsed::list_of_toene, mutabor_convert_factor_to_interval, mutabor_convert_frequency_to_tone, mutabor_empty_tone, mutabor::hidden::ton::name, mutabor::hidden::TSYS::ton, mutabor::hidden::ton::ton_absolut, ton_list_laenge, TRACE, xmalloc.
Referenced by expandiere_logik, expandiere_name.
static struct do_aktion* mutabor::hidden::expandiere_logik(mutabor_box_type *box, struct logik *the_logik)
References mutabor::hidden::logik::anweisungsliste, aufruf_logik, expand_aktions_liste, expandiere_tonsystem, expandiere_umstimmung, mutabor::hidden::mutabor_box_type::file, get_logik_nummer, get_umstimmung, mutabor::hidden::logik::harmony_list, insert_in_lokale_liste, mutabor::hidden::logik::keystroke_list, mutabor::hidden::mutabor_logic_parsed::list_of_logiken, mutabor::hidden::mutabor_logic_parsed::list_of_tonsysteme, mutabor::hidden::mutabor_logic_parsed::list_of_umstimmungen, mutabor::hidden::do_aktion::logic, mutabor::hidden::logik::midi_input_list, mutASSERT, mutabor::hidden::anweisung::next, parser_get_tonsystem, mutabor::hidden::logik::parser_tuning, TRACE, xmalloc.
Referenced by expandiere_in_globale_liste, expandiere_name.
static struct case_element* mutabor::hidden::expand_case_liste(mutabor_box_type *box, struct case_liste *the_liste, struct interpreter_argument_list *aktuelle_parameter)
References expand_aktions_liste, TRACE, xmalloc.
Referenced by expandiere_umstimmung.
static int* mutabor::hidden::create_midi_scan_liste(mutabor_box_type *box, struct midiliste *lauf)
References mutabor::hidden::midiliste::midi_code, midi_list_laenge, mutabor::hidden::midiliste::next, TRACE, xcalloc.
Referenced by insert_in_globale_liste, insert_in_lokale_liste.
PATTERNN* mutabor::hidden::expand_pattern(mutabor_box_type *box, const char *harmonie_name)
References _, mutabor::hidden::taste::code, compiler_error, mutabor::hidden::mutabor_box_type::file, get_harmonie, mutabor::hidden::mutabor_logic_parsed::list_of_harmonien, mutabor_error_message, MUTABOR_KEYRANGE_MAX_WIDTH, mutabor::hidden::taste::stern, mutabor::hidden::harmonie::tastenliste, mutabor::hidden::PTRN::tonigkeit, TRACE, xmalloc.
Referenced by insert_in_globale_liste, insert_in_lokale_liste.
void mutabor::hidden::insert_in_globale_liste(mutabor_box_type *box, struct logik *lauf)
References _, mutabor::hidden::logik::ausloeser, ausloeser_harmonie, mutabor::hidden::ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, mutabor::hidden::ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, mutabor::hidden::ausloeser::ausloeser_midi_in, ausloeser_taste, create_midi_scan_liste, expand_pattern, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::global_harmonies, mutabor::hidden::mutabor_logic_parsed::global_keystrokes, mutabor::hidden::mutabor_logic_parsed::global_midi_inputs, internal_error, mutabor_error_message, mutabor_harmony_invalid, mutabor_is_harmonic_form, mutabor_is_no_harmonic_form, mutASSERT, mutabor::hidden::logik::name, mutabor::hidden::midi_ereignis::next, mutabor::hidden::keyboard_ereignis::next, mutabor::hidden::harmonie_ereignis::next, TRACE, mutabor::hidden::ausloeser::u, xmalloc.
Referenced by expand_decition_tree.
static void mutabor::hidden::expandiere_in_globale_liste(mutabor_box_type *box)
References DEBUGLOG2, expandiere_logik, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::global_harmonies, mutabor::hidden::mutabor_logic_parsed::global_keystrokes, mutabor::hidden::mutabor_logic_parsed::global_midi_inputs, mutASSERT, TRACE.
Referenced by expand_decition_tree.
void mutabor::hidden::expand_decition_tree(mutabor_box_type *box)
References mutabor::hidden::logik::anweisungsliste, expandiere_in_globale_liste, mutabor::hidden::mutabor_box_type::file, mutabor::hidden::mutabor_logic_parsed::global_harmonies, mutabor::hidden::mutabor_logic_parsed::global_keystrokes, mutabor::hidden::mutabor_logic_parsed::global_midi_inputs, insert_in_globale_liste, insert_in_lokale_liste, mutabor::hidden::mutabor_logic_parsed::list_of_logiken, logik_list_laenge, mutASSERT, mutabor::hidden::logik::name, mutabor::hidden::anweisung::next, mutabor::hidden::logik::next, TRACE, xcalloc.
Referenced by mutabor::BoxClass::Compile, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testCycles, boxTest::testFindKeyByKey, boxTest::testHaronic_form.