MisTrack
MisTrack* MisTrack::Next
Referenced by CountOnDeltaTime, MisFile::Load, MisTrack, ReadInit, ReadOn, Save, ~MisTrack.
int MisTrack::Id
Referenced by MisTrack.
MisFile* MisTrack::File
Referenced by AddNoteOn, MisTrack.
DWORD MisTrack::EventLength
Referenced by ReadMidi, WriteMis.
DWORD MisTrack::EventPos
Referenced by ReadMidi, WriteMis.
DWORD MisTrack::Pos
Referenced by Load, ReadInit, ReadOn, WriteMis.
BYTE MisTrack::StatusByte
Referenced by AddMidi, AddMidi3, MisTrack, ReadMidi, WriteMis.
DWORD MisTrack::CurrentTime
Referenced by AddNoteOff, AddNoteOn, CountOnDeltaTime, MisTrack, ReadInit, ReadOn, WriteMis.
MisTrack::MisTrack(MisFile *file, int id, MisTrack *next=0)
References CurrentTime, File, Id, Next, MisFile::nTrack, StatusByte.
MisTrack::~MisTrack()
References Next.
BYTE MisTrack::Get(int i)
Referenced by ReadDeltaTime, ReadMidi, Save.
int MisTrack::Load(ifstream &is)
References NextMeta, Pos, ReadLength.
Referenced by MisFile::Load.
int MisTrack::Save(ofstream &os)
References Get, Next, Save, WriteLength.
Referenced by MisFile::Save, Save.
void MisTrack::AddMidiText(char MidiNr, char *Text)
void MisTrack::AddDeltaTime(DWORD delta)
Referenced by AddNoteOff, AddNoteOn, WriteMis.
void MisTrack::AddMidi(DWORD para, int length=-1)
References lMidiCode, StatusByte.
Referenced by AddNoteOff, AddNoteOn.
void MisTrack::AddMidi3(BYTE a1, BYTE a2, BYTE a3)
References StatusByte.
Referenced by AddNoteOn.
void MisTrack::Copy(MisTrack *from, int &position, int length)
DWORD MisTrack::ReadDeltaTime(DWORD &pos)
References Get.
Referenced by NextMeta, ReadInit, ReadMidi, ReadOn.
DWORD MisTrack::ReadMidi(DWORD &pos)
References EventLength, EventPos, Get, lMidiCode, ReadDeltaTime, StatusByte.
Referenced by NextMeta, ReadOn.
char MisTrack::NextMeta(DWORD &pos, BYTE &nr, DWORD &startPos)
References ReadDeltaTime, ReadMidi.
Referenced by Load.
void MisTrack::ReadInit()
References CurrentTime, Next, Pos, ReadDeltaTime, ReadInit.
Referenced by MisFile::ReadInit, ReadInit.
DWORD MisTrack::ReadOn(DWORD deltaTime, MisReadProceed *proceed)
References CurrentTime, Midi, Next, Pos, ReadDeltaTime, ReadMidi, ReadOn.
Referenced by MisFile::ReadOn, ReadOn.
int MisTrack::WriteMis(DWORD midi, MisTrack *track)
References AddDeltaTime, CurrentTime, EventLength, EventPos, lMidiCode, Pos, StatusByte.
Referenced by MisFile::WriteMis.
void MisTrack::CountOnDeltaTime(DWORD deltaTime)
References CountOnDeltaTime, CurrentTime, Next.
Referenced by MisFile::CountOnDeltaTime, CountOnDeltaTime.
int MisTrack::AddNoteOn(char channel, int key, int pitch, char intensity, signed char sound)
References AddDeltaTime, AddMidi, AddMidi3, ADDPITCH, MisFile::Channels, CurrentTime, File, Channel::Pitch, Channel::Sound.
Referenced by MisFile::NoteOn.
int MisTrack::AddNoteOff(char channel, int key, char intensity)
References AddDeltaTime, AddMidi, CurrentTime.
Referenced by MisFile::NoteOff.