ausloeser.h
ausloeser_typ
Harmonie.
struct harmonie_ereignis* first_harmonie[MAX_BOX][MAX_BOX]
Liste der globalen auslösenden Harmonieen.
Referenced by mutabor_tabellen_generator.
struct harmonie_ereignis** last_global_harmonie[MAX_BOX][MAX_BOX]
Letztes Element der globalen auslösenden Harmonien.
Referenced by mutabor_tabellen_generator.
struct harmonie_ereignis** first_lokal_harmonie
Liste der lokalen auslösenden Harmonien.
Referenced by mutabor_tabellen_generator, expandiere_logik.
struct keyboard_ereignis* first_keyboard[MAX_BOX][MAX_BOX]
Liste der globalen auslösenden Tastenereignissen.
Referenced by boxTest::test_init, mutabor_tabellen_generator.
struct keyboard_ereignis** last_global_keyboard[MAX_BOX][MAX_BOX]
Letztes Element der globalen auslösenden Tastenereignissen.
Referenced by boxTest::test_init, mutabor_tabellen_generator.
struct keyboard_ereignis** first_lokal_keyboard
Liste der lokalen auslösenden Tastenereignissen.
Referenced by mutabor_tabellen_generator, expandiere_logik.
struct midi_ereignis* first_midi[MAX_BOX][MAX_BOX]
Liste der globalen auslösenden MIDI-Ereignissen.
Referenced by boxTest::test_init, mutabor_tabellen_generator.
struct midi_ereignis** last_global_midi[MAX_BOX][MAX_BOX]
Letztes Element der globalen auslösenden MIDI-Ereignissen.
Referenced by boxTest::test_init, mutabor_tabellen_generator.
struct midi_ereignis** first_lokal_midi
Liste der lokalen auslösenden MIDI-Ereignissen.
Referenced by mutabor_tabellen_generator, expandiere_logik.
void print_ausloeser(struct ausloeser *this_)
Gibt einen Auslöser auf der Standard-Ausgabe aus.
this_ Auslöser.
References ausloeser::ausloeser_typ, fatal_error, ausloeser_default, ausloeser_harmonie, ausloeser::u, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_taste, ausloeser::ausloeser_taste, ausloeser_midi_in, print_integersequenz, ausloeser::ausloeser_midi_in.
Referenced by mutabor_programm_einlesen.
void init_ausloeser(void)
Setzt Liste auslösender Ereignisse auf NULL.
Die Liste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_ausloeser_default(void)
Markiert tmp_ausloeser als Standard-Auslöser.
References xmalloc, ausloeser_default.
Referenced by switch, yyparse.
void get_ausloeser_harmonie(void)
Deklariert tmp_ausloeser als Harmonie-Auslöser und setzt die Werte aus dem Zwischenspeicher.
References xmalloc, ausloeser_harmonie, ausloeser::u, tmp_vor_taste, tmp_name, tmp_nach_taste.
Referenced by switch, yyparse.
void get_ausloeser_harmonie_form(void)
Deklariert tmp_ausloeser als Harmonie-Auslöser und setzt die Werte aus dem Zwischenspeicher.
References xmalloc, ausloeser_harmonie_form, ausloeser::u, tmp_vor_taste, tmp_name, tmp_nach_taste.
Referenced by switch, yyparse.
void get_ausloeser_taste(char *name)
Deklariert tmp_ausloeser als Tasten-Auslöser.
Ist die Taste nicht definiert, wird ein fataler Fehler ausgelöst. name Name der auslösenden Taste
References xmalloc, ausloeser_taste, ausloeser::u, name, fatal_error.
Referenced by switch, yyparse.
void get_ausloeser_midi_in(void)
Deklariert tmp_ausloeser als MIDI-Sequenz.
Dafür wird die letzte eingelesene Ganzzahlen-Folge verwendet.
References xmalloc, ausloeser_midi_in, ausloeser::u, get_last_integersequenz.
Referenced by switch, yyparse.
void check_ausloeser(struct ausloeser *ausloeser, char *name)
Testet einen Auslöser auf Zulässigkeit.
Wird eine nicht zulässige oder erreichbare Konfiguration gefunden, wird je nach Situation ein fataler Fehler oder eine Compiler-Warnung ausgelöst. ausloeser Auslöser, der geprüft werden soll name Name für Meldungen
References ausloeser::ausloeser_typ, ausloeser_harmonie_form, get_harmonie, ausloeser::u, ausloeser::ausloeser_harmonie_form, list_of_harmonien, fatal_error, enthalten_in_tastenliste, harmonie::tastenliste, compiler_warning, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_midi_in, ausloeser::ausloeser_midi_in, midiliste::midi_code, midiliste::next.
Referenced by check_konsistenz, check_logik_konsistenz.
void insert_in_globale_liste(int instrument, struct logik *lauf)
Fügt die auslösende Harmonien, Taste bzw.
das Midiereignis der Logik in die entsprechenede globale Liste eines Instrumentes ein. instrument Instrument, für das das Ereignis eingefügt werden soll. lauf Logik, deren Auslöser eingefügt werden soll.
References logik::ausloeser, ausloeser_harmonie, ausloeser::u, ausloeser::ausloeser_harmonie, harmonie_ereignis::next, xmalloc, harmonie_ereignis::pattern, expand_pattern, harmonie_ereignis::ist_harmonieform, harmonie_ereignis::vortaste, harmonie_ereignis::nachtaste, name, logik::name, harmonie_ereignis::aktion, harmonie_ereignis::the_logik_to_expand, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_taste, keyboard_ereignis::next, keyboard_ereignis::aktion, keyboard_ereignis::the_logik_to_expand, ausloeser_midi_in, midi_ereignis::next, midi_ereignis::first_pos, midi_ereignis::scan_pos, create_midi_scan_liste, ausloeser::ausloeser_midi_in, midi_ereignis::aktion, midi_ereignis::the_logik_to_expand, fatal_error.
Referenced by expand_decition_tree, mutabor_tabellen_generator.
void expandiere_in_globale_liste(void)
Expandiert die Auslösenden Ereignisse aller angesammeldten Logiken in die globale Liste.
References MAX_BOX, midi_ereignis::aktion, expandiere_logik, midi_ereignis::the_logik_to_expand, midi_ereignis::next.
Referenced by expand_decition_tree, mutabor_tabellen_generator.
struct midi_ereignis** get_ende_midi(struct midi_ereignis **lauf)
Liefert einen Zeiger auf den Nachfolge-Zeiger des letzten Elementes einer MIDI-Ereignis-Liste.
lauf Zeiger auf die Wurzel einer einfach verketteten Liste von MIDI-Ereignissen.
References get_ende_midi, midi_ereignis::next.
Referenced by expand_decition_tree, get_ende_midi, mutabor_tabellen_generator.
struct keyboard_ereignis** get_ende_keyboard(struct keyboard_ereignis **lauf)
Liefert einen Zeiger auf den Nachfolge-Zeiger des letzten Elementes einer Tasten-Ereignis-Liste.
lauf Zeiger auf die Wurzel einer einfach verketteten Liste von Tastenereignissen.
References get_ende_keyboard, keyboard_ereignis::next.
Referenced by expand_decition_tree, get_ende_keyboard, mutabor_tabellen_generator.
struct harmonie_ereignis** get_ende_harmonie(struct harmonie_ereignis **lauf)
Liefert einen Zeiger auf den Nachfolge-Zeiger des letzten Elementes einer Harmonie-Ereignis-Liste.
lauf Zeiger auf die Wurzel einer einfach verketteten Liste von Harmonieereignissen.
References get_ende_harmonie, harmonie_ereignis::next.
Referenced by expand_decition_tree, get_ende_harmonie, mutabor_tabellen_generator.
struct ausloeser* get_last_ausloeser(void)
Gibt Wurzelelement von tmp_ausloeser zurück.
References tmp_ausloeser.
Referenced by get_new_anweisung, get_new_logik.