mutaborGUI::MidiFileOutputFilterPanel
mutaborGUI::MidiFileOutputFilterPanel::MidiFileOutputFilterPanel(wxWindow *parent)
void mutaborGUI::MidiFileOutputFilterPanel::SetFromChannel(int current, int min, int max)
TODO: set limits according to changes: min.max = max.value and max.min = min.value.
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileOutputFilterPanel::GetFromChannel() const
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileOutputFilterPanel::SetToChannel(int current, int min, int max)
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileOutputFilterPanel::GetToChannel() const
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileOutputFilterPanel::SetAvoidDrumChannel(bool avoid)
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::GetFilterPanel.
bool mutaborGUI::MidiFileOutputFilterPanel::GetAvoidDrumChannel() const
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::ReadFilterPanel.