anweisung.c
struct anweisung* tmp_anweisungsliste
Globaler Zwischenspeicher für genau eine Anweisungsliste.
Referenced by get_last_anweisungs_liste.
void init_anweisungs_liste(void)
Setzt globalen Anweisungs-Zwischenspeicher auf NULL.
Die Liste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
struct anweisung* get_last_anweisungs_liste(void)
Gibt Wurzelelement von #tmp_anweisungs_liste zurück.
References tmp_anweisungsliste.
Referenced by vervollstaendige_logik.
void get_new_anweisung(void)
Fügt eine neue Anweisung ans Ende von tmp_anweisungsliste an.
Dabei werden der letzte eingelesene Auslöser und die letzte Aktionsliste verwendet. Es wird immer die gesamte Liste durchsucht. Effektivität?
References anweisung::aktion, get_last_aktions_liste, get_last_ausloeser, anweisung::next, xmalloc.
Referenced by switch, yyparse.