mutabor::channel_queue_template
typedef std::vector<T> mutabor::channel_queue_template< T, count >::basetype
typedef basetype::iterator mutabor::channel_queue_template< T, count >::iterator
typedef basetype::const_iterator mutabor::channel_queue_template< T, count >::const_iterator
iterator mutabor::channel_queue_template< T, count >::first_free
Referenced by mutabor::channel_queue_template< unsigned char, 16 >::free_channel, mutabor::channel_queue_template< unsigned char, 16 >::get_first_free, mutabor::channel_queue_template< unsigned char, 16 >::init, mutabor::channel_queue_template< unsigned char, 16 >::reserve_channel, mutabor::channel_queue_template< unsigned char, 16 >::reserve_channel_filtered, mutabor::channel_queue_template< unsigned char, 16 >::sustain_channel.
iterator mutabor::channel_queue_template< T, count >::last_sustained
Referenced by mutabor::channel_queue_template< unsigned char, 16 >::free_channel, mutabor::channel_queue_template< unsigned char, 16 >::get_last_sustained, mutabor::channel_queue_template< unsigned char, 16 >::init, mutabor::channel_queue_template< unsigned char, 16 >::reserve_channel, mutabor::channel_queue_template< unsigned char, 16 >::sustain_channel.
mutabor::channel_queue_template< T, count >::channel_queue_template(T size=count)
void mutabor::channel_queue_template< T, count >::init()
Referenced by mutabor::channel_queue_template< unsigned char, 16 >::channel_queue_template.
iterator mutabor::channel_queue_template< T, count >::find_channel(T nr)
Referenced by mutabor::channel_queue_template< unsigned char, 16 >::free_channel, mutabor::channel_queue_template< unsigned char, 16 >::reserve_channel, mutabor::channel_queue_template< unsigned char, 16 >::sustain_channel.
const_iterator mutabor::channel_queue_template< T, count >::find_channel(T nr) const
iterator mutabor::channel_queue_template< T, count >::find_matching_channel(iterator start, F filter)
Referenced by mutabor::channel_queue_template< unsigned char, 16 >::reserve_channel_filtered.
const_iterator mutabor::channel_queue_template< T, count >::reserve_channel_filtered(F filter)
Reserves the first free channel.
That is usually the longest unused one.This can change if certain Channels are registered to be sustained. In that case they are postponed until no channels are availlable anymore. Sustaining is not handled by this class.number of the first free channel end() if no free or sustained channel can be found
iterator mutabor::channel_queue_template< T, count >::reserve_channel(iterator actual)
Referenced by mutabor::channel_queue_template< unsigned char, 16 >::reserve_channel, mutabor::channel_queue_template< unsigned char, 16 >::reserve_channel_filtered.
iterator mutabor::channel_queue_template< T, count >::reserve_channel(T nr)
Forcibly reserve given channel regardless of its state.
This function is used if there are no free channels left and the system frees a channel depending on semantic data. nr Channel to be reserved iterator to the channel.
void mutabor::channel_queue_template< T, count >::free_channel(T nr)
Find and free a channel.
the channel must not be freed already. nr Channel to bee freed.
Referenced by mutabor::channel_queue_template< unsigned char, 16 >::free_channel, mutabor::channel_queue_template< unsigned char, 16 >::unsustain_channel.
void mutabor::channel_queue_template< T, count >::free_channel(iterator current)
Mark a channel to be free.
current iterator pointing to the channel to be regarded as free.
void mutabor::channel_queue_template< T, count >::sustain_channel(T nr, bool sustain=true)
Find and sustain a channel.
the channel must not be sustaind already. nr Channel to bee sustaind.
Referenced by mutabor::channel_queue_template< unsigned char, 16 >::sustain_channel.
iterator mutabor::channel_queue_template< T, count >::sustain_channel(iterator current)
Mark a channel to be sustained.
current iterator pointing to the channel to be regarded as sustained.
void mutabor::channel_queue_template< T, count >::unsustain_channel(iterator current)
Unmark channel to be sustained;.
current iterator pointing to the channel to be regarded as sustained.
Referenced by mutabor::channel_queue_template< unsigned char, 16 >::sustain_channel.
iterator mutabor::channel_queue_template< T, count >::get_first_free()
iterator mutabor::channel_queue_template< T, count >::get_last_sustained()
void mutabor::channel_queue_template< T, count >::move_to_end(iterator current, iterator end)
Move current pointer to the end of a range.
current current position end position after the end position of the element.
Referenced by mutabor::channel_queue_template< unsigned char, 16 >::free_channel, mutabor::channel_queue_template< unsigned char, 16 >::reserve_channel, mutabor::channel_queue_template< unsigned char, 16 >::sustain_channel.
void mutabor::channel_queue_template< T, count >::move_to_front(iterator current, iterator final)
Move current pointer to the beginning of a range.
current current position final position where the element should be moved to
Referenced by mutabor::channel_queue_template< unsigned char, 16 >::free_channel, mutabor::channel_queue_template< unsigned char, 16 >::reserve_channel.