mutabor::tree_storage
mutabor::tree_storage::tree_storage()
default constructor.
virtual mutabor::tree_storage::~tree_storage()
virtual destructor
virtual long mutabor::tree_storage::Read(const mutStringRef key, long defval)=0
Reads a long integer value.
key (mutStringRef) Name of the desired leaf in the tree defval (long) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
Referenced by mutabor::CommonFileOutputDevice::Load, mutabor::OutputGis::Load, mutabor::TRouteClass< I, O, B >::Load, mutabor::CommonFileInputDevice::Load, mutaborGUI::BoxData::Load, mutabor::OutputMidiPort::Load, mutabor::InputMidiPort::Load, mutabor::OutputMidiFile::Load, mutabor::InputMidiFile::Load, mutabor::BoxFactory::LoadBoxes, mutabor::DeviceFactory::LoadInputDevices, mutabor::DeviceFactory::LoadOutputDevices, mutabor::TRouteClass< I, O, B >::LoadRoutes, Read.
virtual double mutabor::tree_storage::Read(const mutStringRef key, double defval)=0
Reads a double value.
key (mutStringRef) Name of the desired leaf in the tree defval (double) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
virtual int mutabor::tree_storage::Read(const mutStringRef key, int defval)=0
Reads an integer value.
key (mutStringRef) Name of the desired leaf in the tree defval (int) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
virtual bool mutabor::tree_storage::Read(const mutStringRef key, bool defval)=0
Reads a boolean value.
key (mutStringRef) Name of the desired leaf in the tree defval (bool) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
virtual mutString mutabor::tree_storage::Read(const mutStringRef key, const mutStringRef defval)=0
Reads a string value.
key (mutStringRef) Name of the desired leaf in the tree defval (mutStringRef) default value, if the leaf is not availlable data read or defval, if the leaf does not exist.
mutString mutabor::tree_storage::Read(const mutStringRef key, const mutChar *defval)
References mutString, Read.
mutString mutabor::tree_storage::Read(const mutStringRef key, mutChar *defval)
References mutString, Read.
virtual void mutabor::tree_storage::Write(const mutStringRef key, long value)=0
Writes a long integer value.
key (mutStringRef) Name of the desired leaf in the tree value (long) value, to be written
Referenced by mutabor::CommonFileOutputDevice::Save, mutabor::OutputGis::Save, mutabor::TRouteClass< I, O, B >::Save, mutabor::CommonFileInputDevice::Save, mutaborGUI::BoxData::Save, mutabor::OutputMidiPort::Save, mutabor::InputMidiPort::Save, mutabor::OutputMidiFile::Save, mutabor::InputMidiFile::Save, mutabor::BoxFactory::SaveBoxes, mutabor::DeviceFactory::SaveInputDevices, mutabor::DeviceFactory::SaveOutputDevices.
virtual void mutabor::tree_storage::Write(const mutStringRef key, double value)=0
Writes a double value.
key (mutStringRef) Name of the desired leaf in the tree value (double) value, to be written
virtual void mutabor::tree_storage::Write(const mutStringRef key, int value)=0
Writes an integer value.
key (mutStringRef) Name of the desired leaf in the tree value (int) value, to be written
virtual void mutabor::tree_storage::Write(const mutStringRef key, bool value)=0
Writes a boolean value.
key (mutStringRef) Name of the desired leaf in the tree value (bool) value, to be written
virtual void mutabor::tree_storage::Write(const mutStringRef key, const mutStringRef value)=0
Writes a string value.
key (mutStringRef) Name of the desired leaf in the tree value (mutStringRef) value, to be written
virtual bool mutabor::tree_storage::HasGroup(const mutStringRef) const =0
Checks if the tree has a branch with the given name.
subdir (mutStringRef) subdirectory to check for. true if the current node has a leaf with the given name which is a node itself.
virtual void mutabor::tree_storage::toLeaf(const mutStringRef subdir)=0
Changes the current node downwards.
this function can be used to navigate towards the leaves in the tree. The argument can be considered like a subdirectory in a file system. subdir (mutStringRef) subdirectory to be written to.
Referenced by mutabor::RouteFactory::DoLoadRoutes, mutabor::RouteFactory::DoSaveRoutes, mutabor::OutputGis::Load, mutabor::InputGis::Load, mutabor::OutputMidiPort::Load, mutabor::InputMidiPort::Load, mutabor::OutputMidiFile::Load, mutabor::InputMidiFile::Load, mutabor::BoxFactory::LoadBoxes, mutabor::DeviceFactory::LoadInputDevices, mutabor::DeviceFactory::LoadOutputDevices, mutabor::TRouteClass< I, O, B >::LoadRoutes, mutabor::OutputGis::Save, mutabor::InputGis::Save, mutabor::OutputMidiPort::Save, mutabor::InputMidiPort::Save, mutabor::OutputMidiFile::Save, mutabor::InputMidiFile::Save, mutabor::BoxFactory::SaveBoxes, mutabor::DeviceFactory::SaveInputDevices, mutabor::DeviceFactory::SaveOutputDevices, mutabor::TRouteClass< I, O, B >::SaveRoutes.
virtual void mutabor::tree_storage::toLeaf(const mutStringRef name, int id)=0
Changes the current node downwards.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. if the id is negative, it will create a new item. subdir (mutStringRef) name of the entity to be written to. id (int) id of the current object
virtual int mutabor::tree_storage::toFirstLeaf(const mutStringRef name)=0
Changes the current node downdwards to the first leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (mutStringRef) name of the entity to be read from. (int) id of the selected item toNextLeaf
Referenced by mutabor::BoxFactory::LoadBoxes, mutabor::DeviceFactory::LoadInputDevices, mutabor::DeviceFactory::LoadOutputDevices, mutabor::TRouteClass< I, O, B >::LoadRoutes.
virtual int mutabor::tree_storage::toFirstLeaf(const mutStringRef name, mutStringRef id)=0
Changes the current node downdwards to the first leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (mutStringRef) name of the entity to be read from. id (mutStringRef) reference to a String where the id of the leaf will be stored (int) id of the selected item toNextLeaf
virtual int mutabor::tree_storage::toNextLeaf(const mutStringRef name)=0
Changes the current node downdwards to the next leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (mutStringRef) name of the entity to be read from. (int) id of the selected item toFirstLeaf
Referenced by mutabor::BoxFactory::LoadBoxes, mutabor::DeviceFactory::LoadInputDevices, mutabor::DeviceFactory::LoadOutputDevices, mutabor::TRouteClass< I, O, B >::LoadRoutes.
virtual int mutabor::tree_storage::toNextLeaf(const mutStringRef name, mutStringRef id)=0
Changes the current node downdwards to the next leaf of given type.
this function can be used to navigate towards the leaves in the tree. The argument can be considered as Items with a unique id. subdir (mutStringRef) name of the entity to be read from. id (mutStringRef) reference to a String where the id of the leaf will be stored (int) id of the selected item toFirstLeaf
virtual void mutabor::tree_storage::toParent(unsigned int count=1)=0
This function jumps up in the tree (i.e. towards the root).
count (int) number of nodes to go upward. Default: 1.
Referenced by mutabor::RouteFactory::DoLoadRoutes, mutabor::RouteFactory::DoSaveRoutes, mutabor::OutputGis::Load, mutabor::InputGis::Load, mutabor::OutputMidiPort::Load, mutabor::InputMidiPort::Load, mutabor::OutputMidiFile::Load, mutabor::InputMidiFile::Load, mutabor::BoxFactory::LoadBoxes, mutabor::DeviceFactory::LoadInputDevices, mutabor::DeviceFactory::LoadOutputDevices, mutabor::TRouteClass< I, O, B >::LoadRoutes, mutabor::OutputGis::Save, mutabor::InputGis::Save, mutabor::OutputMidiPort::Save, mutabor::InputMidiPort::Save, mutabor::OutputMidiFile::Save, mutabor::InputMidiFile::Save, mutabor::BoxFactory::SaveBoxes, mutabor::DeviceFactory::SaveInputDevices, mutabor::DeviceFactory::SaveOutputDevices, mutabor::TRouteClass< I, O, B >::SaveRoutes.
virtual mutString mutabor::tree_storage::GetPath()=0
Return a string representation of the position in the current tree.
This function can be used to store the current position in the tree. mutString String representation of the current path. The concrete representation is implementation dependent and can vary for different tree types.
Referenced by mutabor::RouteFactory::DoLoadRoutes, mutabor::RouteFactory::DoSaveRoutes, mutabor::CommonFileOutputDevice::Load, mutabor::OutputGis::Load, mutabor::TRouteClass< I, O, B >::Load, mutabor::CommonFileInputDevice::Load, mutabor::InputGis::Load, mutabor::OutputMidiPort::Load, mutabor::InputMidiPort::Load, mutabor::OutputMidiFile::Load, mutabor::InputMidiFile::Load, mutabor::BoxFactory::LoadBoxes, mutabor::DeviceFactory::LoadInputDevices, mutabor::DeviceFactory::LoadOutputDevices, mutabor::TRouteClass< I, O, B >::LoadRoutes, mutabor::CommonFileOutputDevice::Save, mutabor::OutputGis::Save, mutabor::TRouteClass< I, O, B >::Save, mutabor::CommonFileInputDevice::Save, mutabor::InputGis::Save, mutabor::OutputMidiPort::Save, mutabor::InputMidiPort::Save, mutabor::OutputMidiFile::Save, mutabor::InputMidiFile::Save, mutabor::BoxFactory::SaveBoxes, mutabor::DeviceFactory::SaveInputDevices, mutabor::DeviceFactory::SaveOutputDevices, mutabor::TRouteClass< I, O, B >::SaveRoutes.
virtual void mutabor::tree_storage::SetPath(const mutStringRef path)=0
Set the current pointer in the tree.
This function can be used to store the current position in the tree. path (mutString) String representation of the new path as returned by GetPath(). The concrete representation is implementation dependent and can vary for different tree types.
virtual void mutabor::tree_storage::DeleteEntry(const mutStringRef path)=0
Delete an entry.
entry path to the entry that shall be deleted
virtual void mutabor::tree_storage::DeleteGroup(const mutStringRef path)=0
Delete an entire group with all childs.
group path to the entry that shall be deleted
Referenced by mutabor::RouteFactory::DoSaveRoutes.