mutabor::InputMidiPort
typedef CommonMidiInput<InputDeviceClass> mutabor::InputMidiPort::parentType
friend class MidiPortFactory
int mutabor::InputMidiPort::DevId
Referenced by GetDevId, SetDevId.
HMIDIIN mutabor::InputMidiPort::hMidiIn
virtual mutabor::InputMidiPort::~InputMidiPort()
void mutabor::InputMidiPort::Save(tree_storage &config)
Save current device settings in a tree storage.
config (tree_storage) storage class, where the data will be saved.
References mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::Write.
void mutabor::InputMidiPort::Save(tree_storage &config, const RouteClass *route)
Save route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route ) Route whos data shall be saved.
References mutabor::TRouteClass< I, O, B >::GetInputFrom, mutabor::TRouteClass< I, O, B >::GetInputTo, mutabor::tree_storage::GetPath, mutabor::TRouteClass< I, O, B >::GetType, mutASSERT, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent, mutabor::tree_storage::Write.
void mutabor::InputMidiPort::Load(tree_storage &config)
Load current device settings from a tree storage.
config (tree_storage) storage class, where the data will be loaded from.
References mutabor::tree_storage::GetPath, mutASSERT, mutabor::tree_storage::Read, mutabor::rtmidiin.
void mutabor::InputMidiPort::Load(tree_storage &config, RouteClass *route)
Loade route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route ) Route whos data shall be loaded.
References _mut, mutabor::tree_storage::GetPath, mutabor::TRouteClass< I, O, B >::GetType, mutASSERT, mutabor::tree_storage::Read, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, mutabor::hidden::runtime_error, mutabor::TRouteClass< I, O, B >::SetInputFrom, mutabor::TRouteClass< I, O, B >::SetInputTo, mutabor::TRouteClass< I, O, B >::SetType, mutabor::str, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent.
bool mutabor::InputMidiPort::Open()
References _mut, mutabor::hidden::error, mutabor::MidiInPortFunc, mutASSERT, mutabor::hidden::runtime_error, mutabor::str, mutabor::hidden::warning.
Referenced by SetDevId.
void mutabor::InputMidiPort::Close()
References DEFAULT_PANIC, mutASSERT, mutabor::Panic.
Referenced by SetDevId.
virtual void mutabor::InputMidiPort::Stop()
Stop playback or recording of the device.
References DEFAULT_PANIC, mutabor::InputDeviceClass::Panic.
virtual void mutabor::InputMidiPort::Play(wxThreadKind tk=wxTHREAD_DETACHED)
virtual void mutabor::InputMidiPort::Pause()
Pause playback or recording of the device.
virtual frac mutabor::InputMidiPort::ReadOn(frac time)
virtual bool mutabor::InputMidiPort::NeedsRealTime()
virtual void mutabor::InputMidiPort::SetDevId(int id)
References _mut, Close, DevId, mutabor::Device::IsOpen, mutabor::Device::Name, Open, mutabor::rtmidiin.
Referenced by mutaborGUI::MutInputMidiDeviceShape::readDialog.
virtual int mutabor::InputMidiPort::GetDevId()
References DevId.
Referenced by mutaborGUI::MutInputMidiDeviceShape::InitializeDialog.
virtual const std::string& mutabor::InputMidiPort::GetName()
References mutabor::Device::Name.
Referenced by mutaborGUI::MutInputMidiDeviceShape::readDialog.
virtual void mutabor::InputMidiPort::SetName(const std::string &s)
InputMidiPort::proceed_bool mutabor::InputMidiPort::shouldProceed(Route R, const std::vector< unsigned char > *midiCode, int data=0)
References mutASSERT, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, UNREACHABLEC.
void mutabor::InputMidiPort::Proceed(const std::vector< unsigned char > *midiCode, int data=0, int channel_offset=0)
References mutabor::midi::ACTIVE_SENSE, mutabor::OutputDeviceClass::all_handle_event, mutabor::midi::CLOCK, mutabor::midi::CONTINUE_PLAY, mutabor::create_event, DEBUGLOG, mutabor::midi::META, mutabor::InputDeviceClass::PauseAll, mutabor::midi::QUARTER_FRAME, mutabor::midi::REALTIME_UNDEFINED, mutabor::InputDeviceClass::RealtimePlay, mutabor::midi::SONG_POSITION, mutabor::midi::SONG_SELECT, mutabor::midi::START_PLAY, mutabor::midi::STOP_PLAY, mutabor::InputDeviceClass::StopAll, mutabor::midi::SYSEX_END, mutabor::midi::SYSEX_START, mutabor::midi::SYSTEM_UNDEFINED1, mutabor::midi::SYSTEM_UNDEFINED2, mutabor::midi::TICK, mutabor::midi::TUNE_REQUEST.
virtual int mutabor::InputMidiPort::GetMaxChannel() const
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
virtual int mutabor::InputMidiPort::GetMinChannel() const
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
virtual int mutabor::InputMidiPort::GetMaxKey() const
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
virtual int mutabor::InputMidiPort::GetMinKey() const
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
virtual DevType mutabor::InputMidiPort::GetType() const
References mutabor::DTMidiPort.
virtual std::string mutabor::InputMidiPort::GetTypeName() const
References _mutN.
mutabor::InputMidiPort::operator std::string() const
References mutabor::str.
mutabor::InputMidiPort::InputMidiPort(const std::string name="", MutaborModeType mode=DeviceStop, int id=-1)
References mutabor::CommonMidiInput< InputDeviceClass >::channel_data.