mutabor
BoxType
@40
MutaborModeType
DevType
RouteType
all events will pass
typedef hidden::mutabor_error_type mutabor::error_type
typedef boost::intrusive_ptr< BoxClass > mutabor::Box
typedef std::vector<Box> mutabor::BoxListType
typedef std::vector< uint8_t > mutabor::midi_string
typedef boost::intrusive_ptr< OutputDeviceClass > mutabor::OutputDevice
typedef CommonTypedDeviceAPI<OutputDeviceClass>::listtype mutabor::OutputDeviceList
typedef std::set<OutputDevice> mutabor::OutputDeviceSet
typedef boost::intrusive_ptr< InputDeviceClass > mutabor::InputDevice
typedef CommonTypedDeviceAPI<InputDeviceClass>::listtype mutabor::InputDeviceList
typedef system_byte_event<midi::SYSTEM_UNDEFINED1> mutabor::system_common_midi_undef1_event
typedef system_byte_event<midi::SYSTEM_UNDEFINED2> mutabor::system_common_midi_undef2_event
typedef system_byte_event<midi::TUNE_REQUEST> mutabor::tune_request_event
typedef system_byte_event<midi::SYSEX_END> mutabor::sysex_end_event
typedef system_byte_event<midi::CLOCK> mutabor::system_realtime_clock_event
typedef system_byte_event<midi::TICK> mutabor::system_realtime_tick_event
typedef system_byte_event<midi::START_PLAY> mutabor::start_play_event
typedef system_byte_event<midi::CONTINUE_PLAY> mutabor::continue_play_event
typedef system_byte_event<midi::STOP_PLAY> mutabor::stop_play_event
typedef system_byte_event<midi::REALTIME_UNDEFINED> mutabor::system_realtime_midi_undef2
typedef system_byte_event<midi::ACTIVE_SENSE> mutabor::active_sense_event
typedef system_byte_event<midi::RESET> mutabor::reset_event
typedef generic_text_event<midi::EVENT_TEXT> mutabor::text_event
typedef generic_text_event<midi::COPYRIGHT_NOTICE> mutabor::copyright_event
typedef generic_text_event<midi::SEQUENCE_NAME> mutabor::sequence_name_event
typedef generic_text_event<midi::TRACK_NAME> mutabor::track_name_event
typedef generic_text_event<midi::INSTRUMENT_NAME> mutabor::instrument_name_event
typedef generic_text_event<midi::LYRIC> mutabor::lyric_event
typedef generic_text_event<midi::MARKER> mutabor::marker_event
typedef generic_text_event<midi::CUE_POINT> mutabor::cue_point_event
typedef system_byte_event<midi::END_OF_TRACK> mutabor::end_track_event
typedef boost::intrusive_ptr< event_class > mutabor::event
typedef std::vector<Track> mutabor::TrackList
typedef channel_queue_template<unsigned char,16> mutabor::channel_queue_type
typedef struct mutabor::TAK mutabor::TonAufKanal
typedef TRouteClass<InputDevice,OutputDevice, Box>::Route mutabor::Route
typedef TRouteClass<InputDevice,OutputDevice, Box> mutabor::RouteClass
typedef TRouteClass<InputDevice,OutputDevice, Box>::routeListType mutabor::routeListType
typedef TRouteClass<InputDevice,OutputDevice, Box>::routePtrList mutabor::routePtrList
typedef wxThread mutabor::Thread
typedef wxThreadKind mutabor::ThreadKind
typedef wxMutex mutabor::Mutex
typedef wxMutexLocker mutabor::ScopedLock
typedef wxMutexError mutabor::ThreadResult
typedef wxCondition mutabor::ThreadCondition
struct mutabor_debug_flagtype mutabor::mutabor_debug_flags
Referenced by CommonMidiInputTest::tearDown, OutputMidiFileTest::tearDown, boxTest::testCycles.
debugFlags mutabor::debugFlagInitialiser
Mutex mutabor::debugmutex
Referenced by mutabor_debug_lock, mutabor_debug_unlock.
char mutabor::InDevChanged
std::string mutabor::teststring
std::string mutabor::CurrentId
Referenced by mutabor::OutputGis::do_Gis, mutabor::InputGis::Proceed.
std::string mutabor::CurrentSep
Referenced by mutabor::InputGis::Proceed.
ChannelData mutabor::Cd(0)(0)
Referenced by mutabor::CommonMidiOutput< T, D >::do_Controller, mutabor::CommonMidiOutput< T, D >::do_NoteOff, mutabor::CommonMidiOutput< T, D >::do_NoteOn, mutabor::CommonMidiOutput< T, D >::do_Open, mutabor::CommonMidiOutput< T, D >::do_Panic, mutabor::CommonMidiOutput< T, D >::do_UpdateControllers, mutabor::CommonMidiOutput< T, D >::do_UpdateTones, mutabor::InputGis::Proceed.
RtMidiOut * mutabor::rtmidiout
Referenced by mutabor::OutputMidiPort::Load, MidiInit, MidiUninit, mutabor::OutputMidiPort::SetDevId.
RtMidiIn * mutabor::rtmidiin
Referenced by mutabor::InputMidiPort::Load, MidiInit, MidiUninit, mutabor::InputMidiPort::SetDevId.
const std::string mutabor::RTName[]
Referenced by mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetTypeName, compat30::SaveRoutes, compat30::Str2RT.
const std::string mutabor::DevTypeName[]
CurrentTimer mutabor::CurrentTime
Referenced by mutabor::BoxClass::ActivateAll, ChordNote::AddGis, GisWriteHead::AddTime, mutabor::InputDeviceClass::BatchPlay, ChordNote::ChordNote, mutabor::CommonFileInputDevice::Close, mutabor::CommonMidiOutput< T, D >::Close, GisWriteHead::CloseCurrentToken, mutaborGUI::MutFrame::CmInDevPlay, ChordNote::CountOnTime, mutabor::watchdog< Box >::Entry, ChordNote::MutNoteOff, testCommonFileDeviceTimer::Open, mutabor::CommonFileInputDevice::Open, testCommonFileDeviceTimer::Pause, mutabor::CommonFileInputDevice::Pause, testCommonFileDeviceTimer::Play, myDevice::Play, mutabor::CommonFileInputDevice::Play, testCommonFileDeviceTimer::PrepareNextEvent, ChordNote::SetNoteOff, InputMidiFileTest::setUp, CommonMidiOutputTest::setUp, CommonMidiInputTest::setUp, OutputMidiFileTest::setUp, testCommonFileDeviceTimer::Stop, mutabor::BoxClass::StopAll, InputMidiFileTest::testAfterTouch, InputMidiFileTest::testAllControllerOff, InputMidiFileTest::testBankSelect, InputMidiFileTest::testBatchPlay1, OutputMidiFileTest::testBatchPlay1, InputMidiFileTest::testBoxMidiIn, InputMidiFileTest::testBug019010, InputMidiFileTest::testBug019010_2, InputMidiFileTest::testControllerPlay, InputMidiFileTest::testRpnNrpn, InputMidiFileTest::testSysEx, CommonFileDeviceTest::testTimer, mutabor::CommonFileInputDevice::ThreadPlay, GisWriteHead::WriteChord, mutabor::Track::WriteDelta, mutabor::DebugMidiOutputProvider::WriteTime.
std::string mutabor::str(T obj)
Referenced by mutabor::CommonFileInputDevice::exception_error, GisReadArtHeadOn, IMPLEMENT_APP, mutabor::OutputMidiPort::Load, mutabor::InputMidiPort::Load, mutabor::OutputMidiFile::Load, mutabor::InputMidiFile::Load, mutabor_assert_fail, Note, mutabor::MidiPortOutputProvider::Open, mutabor::InputGis::Open, mutabor::InputMidiPort::Open, mutabor::InputMidiFile::Open, mutabor::CommonFileOutputDevice::operator std::string, mutabor::InputGis::operator std::string, mutabor::CommonFileInputDevice::operator std::string, mutabor::timing_params::operator std::string, mutabor::OutputMidiPort::operator std::string, mutabor::Track::operator std::string, mutabor::TRouteClass< I, O, B >::operator std::string, mutabor::InputMidiPort::operator std::string, mutabor::OutputMidiFile::operator std::string, mutabor::Device::operator std::string, mutabor::BoxClass::operator std::string, mutabor::InputMidiFile::operator std::string, mutabor::CommonTypedDeviceAPI< T, P, L >::operator std::string, mutabor::InputDeviceClass::operator std::string, mutabor::DebugMidiOutputProvider::RawMsg, mutabor::InputGis::ReadOn, compat30::SaveRoutes, mutabor::DebugMidiOutputProvider::SendSysEx, mutabor::OutputMidiPort::SetDevId, CommonMidiInputTest::testGlobalPanic, CommonMidiOutputTest::testNoteOnOff, CommonMidiInputTest::testPanic, mutaborGUI::MutFrame::TextBoxOpen, GisReadHead::ToString, GisReadArtHead::ToString, GisTag::ToString, GisTagBegin::ToString, GisTagEnd::ToString, GisNote::ToString, GisParaInt::ToString, GisParaReal::ToString, GisParaStr::ToString, mutabor::DebugMidiOutputProvider::WriteTime.
std::string mutabor::str(frac f)
Referenced by mutabor::frac::operator std::string.
std::ostream& mutabor::operator<<(std::ostream &os, const frac &f)
References mutabor::frac::d, mutabor::frac::n.
bool mutabor::is_key_trigger(struct any_trigger &trigger)
References mutabor::hidden::any_trigger::key, mutabor::hidden::any_trigger::type.
bool mutabor::is_harmony_trigger(struct any_trigger &trigger)
References mutabor::hidden::any_trigger::key, mutabor::hidden::any_trigger::type.
bool mutabor::is_midi_trigger(struct any_trigger &trigger)
References mutabor::hidden::any_trigger::key, mutabor::hidden::any_trigger::type.
keyboard_action* mutabor::get_key_trigger(struct any_trigger &trigger)
References mutabor::hidden::any_trigger::key_trigger, mutabor::hidden::any_trigger::u.
harmony_action* mutabor::get_harmony_trigger(struct any_trigger &trigger)
References mutabor::hidden::any_trigger::harmony_trigger, mutabor::hidden::any_trigger::u.
midi_action* mutabor::get_midi_trigger(struct any_trigger &trigger)
References mutabor::hidden::any_trigger::midi_trigger, mutabor::hidden::any_trigger::u.
bool mutabor::OpenAll(int mode)
References _mut, mutabor::BoxClass::CloseAll, mutabor::BoxClass::GetBoxList, InOpen, mutabor::BoxClass_CallOpen::ok, OpenAllBoxes, OpenAllInDevices, OpenAllOutDevices, OutClose, OutOpen.
Referenced by mutabor::BoxClass::ActivateAll, mutabor::InputDeviceClass::BatchPlay.
static void mutabor::append_triggers(BoxClass::logic_list &list, mutabor_box_type *box, struct mutabor::hidden::logik *logic, struct keyboard_ereignis *keystrokes)
References mutabor::BoxClass::logic_entry::CurrentLogic, mutabor::hidden::any_trigger::key, mutabor::hidden::any_trigger::key_trigger, mutabor::hidden::mutabor_box_type::last_trigger, mutabor::BoxClass::logic_entry::Logic, mutabor::hidden::keyboard_ereignis::next, mutabor::BoxClass::logic_entry::none, mutabor::hidden::any_trigger::type, mutabor::hidden::any_trigger::u.
Referenced by mutabor::BoxClass::GetLogics.
static void mutabor::append_triggers(BoxClass::logic_list &list, mutabor_box_type *box, struct mutabor::hidden::logik *logic, struct harmonie_ereignis *harmonies)
References mutabor::BoxClass::logic_entry::CurrentLogic, mutabor::hidden::any_trigger::harmony, mutabor::hidden::any_trigger::harmony_trigger, mutabor::hidden::mutabor_box_type::last_trigger, mutabor::BoxClass::logic_entry::Logic, mutabor::BoxClass::logic_entry::name, mutabor::hidden::harmonie_ereignis::next, mutabor::BoxClass::logic_entry::none, mutabor::hidden::any_trigger::type, mutabor::hidden::any_trigger::u.
static void mutabor::append_triggers(BoxClass::logic_list &list, mutabor_box_type *box, struct mutabor::hidden::logik *logic, struct midi_ereignis *midis)
References mutabor::BoxClass::logic_entry::CurrentLogic, mutabor::hidden::mutabor_box_type::last_trigger, mutabor::BoxClass::logic_entry::Logic, mutabor::hidden::any_trigger::midi, mutabor::hidden::any_trigger::midi_trigger, mutabor::BoxClass::logic_entry::name, mutabor::hidden::midi_ereignis::next, mutabor::BoxClass::logic_entry::none, mutabor::hidden::any_trigger::type, mutabor::hidden::any_trigger::u.
static bool mutabor::is_logic_key(struct keyboard_ereignis *e, int key)
References mutabor::hidden::keyboard_ereignis::next, mutabor::hidden::keyboard_ereignis::taste, mutabor::hidden::keyboard_ereignis::the_logik_to_expand.
Referenced by mutabor::BoxClass::IsLogicKey.
static void mutabor::error_callback(mutabor_box_type *b, error_type type, const char *message)
References mutabor::BoxClass::runtime_error.
void mutabor::Panic(int type)
References mutabor::BoxClass::GetBoxList, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList.
Referenced by mutabor::InputMidiPort::Close, mutaborGUI::MutFrame::CmPanic, mutabor::CommonMidiInput< D >::ProceedRoute, CommonMidiInputTest::testGlobalPanic.
void mutabor::initialize_box_data()
References mutabor::BoxClass::backend_callbacks, mutabor::hidden::mutabor_set_callbacks.
Referenced by IMPLEMENT_APP, InputMidiFileTest::testAfterTouch, InputMidiFileTest::testBoxMidiIn, InputMidiFileTest::testSysEx.
const char* mutabor::to_string(error_type type)
References mutabor::hidden::mutabor_error_type_to_string.
Referenced by IMPLEMENT_APP, mutaborGUI::GUIRouteBase::runtime_error, mutaborGUI::BoxData::runtime_error, mutaborGUI::GUIOutputDeviceBase::runtime_error, mutaborGUI::GUIInputDeviceBase::runtime_error, mutabor::Device::runtime_error, mutabor::BoxClass::runtime_error.
void mutabor::BoxClose()
References mutabor::BoxClass::GetBoxList.
void mutabor::InitDeviceFactories()
Referenced by main.
bool mutabor::OutOpen()
References DEBUGLOG2, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList.
Referenced by main, OpenAll.
void mutabor::OutClose()
References mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList.
Referenced by mutabor::InputDeviceClass::BatchPlay, main, OpenAll, mutabor::BoxClass::StopAll.
void mutabor::OutAddTime(frac time)
References mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList.
Referenced by main.
bool mutabor::InOpen()
References DEBUGLOGBASE, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList, TRACE.
Referenced by main, OpenAll.
void mutabor::InClose()
References mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList, TRACE.
Referenced by mutabor::InputDeviceClass::BatchPlay, main, mutabor::BoxClass::StopAll.
bool mutabor::NeedsRealTime()
References mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList, TRACE.
Referenced by mutaborGUI::MutFrame::CmDoActivate.
event_class* mutabor::create_meta_event(const std::vector< unsigned char > *code, size_t unique_id)
References mutabor::midi::META_CHANNEL_PREFIX, mutabor::midi::META_COPYRIGHT_NOTICE, mutabor::midi::META_CUE_POINT, mutabor::midi::META_END_OF_TRACK, mutabor::midi::META_EVENT_TEXT, mutabor::midi::META_INSTRUMENT_NAME, mutabor::midi::META_KEY_SIGNATURE, mutabor::midi::META_LYRIC, mutabor::midi::META_MARKER, mutabor::midi::META_SEQUENCE_NAME, mutabor::midi::META_SEQUENCE_NUMBER, mutabor::midi::META_SEQUENCER_SPECIFIC, mutabor::midi::META_SET_TEMPO, mutabor::midi::META_SMPTE_OFFSET, mutabor::midi::META_TIME_SIGNATURE.
Referenced by create_system_event.
event_class* mutabor::create_system_event(const std::vector< unsigned char > *code, size_t unique_id)
References mutabor::midi::ACTIVE_SENSE, mutabor::midi::CLOCK, mutabor::midi::CONTINUE_PLAY, create_meta_event, mutabor::midi::META, mutASSERT, mutabor::midi::QUARTER_FRAME, mutabor::midi::REALTIME_UNDEFINED, mutabor::midi::SONG_POSITION, mutabor::midi::SONG_SELECT, mutabor::midi::START_PLAY, mutabor::midi::STOP_PLAY, mutabor::midi::SYSEX_END, mutabor::midi::SYSEX_START, mutabor::midi::SYSTEM_UNDEFINED1, mutabor::midi::SYSTEM_UNDEFINED2, mutabor::midi::TICK, mutabor::midi::TUNE_REQUEST.
Referenced by create_event.
event_class* mutabor::create_event(const std::vector< unsigned char > *code, size_t unique_id)
References mutabor::midi::CHANNEL_PRESSURE, mutabor::midi::CHANNEL_PRESSURE_VAL, mutabor::midi::CONTROLLER, create_system_event, mutabor::midi::KEY_PRESSURE, mutASSERT, mutabor::midi::SYSTEM.
Referenced by mutabor::InputMidiPort::Proceed, mutabor::InputMidiFile::Proceed, mutabor::CommonMidiInput< D >::Proceed, mutabor::CommonMidiInput< D >::ProceedRoute, mutabor::InputMidiFile::ReadMidiProceed.
void mutabor::MutaborTag(GisReadArtHead *h, GisToken *Para, mutabor::Box box)
References GisReadArtHead::Box, GetGisType, mutabor::BoxClass::GetOrCreateBox, GTParaInt, GTParaStr, GisToken::Next, GisToken::Type.
Referenced by mutabor::InputGis::Proceed.
static uint32_t mutabor::ReadLength(std::istream &is)
Referenced by mutabor::InputMidiFile::Open.
void CALLBACK mutabor::MidiInPortFunc(HMIDIIN hMidiIn, UINT wMsg, DWORD dwInstance, DWORD dwParam1, DWORD dwParam2)
Referenced by mutabor::InputMidiPort::Open.
void mutabor::MidiInit()
References mutabor::hidden::error, rtmidiin, rtmidiout.
Referenced by IMPLEMENT_APP.
void mutabor::MidiUninit()
References rtmidiin, rtmidiout.
Referenced by IMPLEMENT_APP.
void mutabor::connect(Route r, OutputDevice out)
Referenced by mutaborGUI::MutBoxShape::AddChannel, mutaborGUI::MutBoxShape::AddPossibleOutput, connect, mutaborGUI::MutBoxChannelShape::Create, mutabor::TRouteClass< I, O, B >::Create, mutaborGUI::GUIRouteFactory::DoCreateBoxChannelShape, mutabor::TRouteClass< I, O, B >::Load, mutaborGUI::MutBoxShape::readDialog, mutaborGUI::MutBoxChannelShape::ReadPanel, CommonMidiOutputTest::setUp, CommonMidiInputTest::setUp, OutputMidiFileTest::setUp, InputMidiFileTest::testAfterTouch, InputMidiFileTest::testAllControllerOff, InputMidiFileTest::testBankSelect, InputMidiFileTest::testBatchPlay1, OutputMidiFileTest::testBatchPlay1, InputMidiFileTest::testBoxMidiIn, InputMidiFileTest::testBug019010, InputMidiFileTest::testBug019010_2, GUIRouteTest::testConnect, InputMidiFileTest::testControllerPlay, RouteTest::testDestroyAll, InputMidiFileTest::testRpnNrpn, InputMidiFileTest::testSysEx.
void mutabor::connect(Route r, Box box)
void mutabor::connect(OutputDevice &out, Route &r)
References connect.
bool mutabor::disconnect(Route r, OutputDevice out)
Referenced by mutaborGUI::GUIRouteBase::Destroy, mutaborGUI::GUIOutputDeviceBase::Destroy, mutabor::TRouteClass< I, O, B >::Destroy, mutaborGUI::GUIInputDeviceBase::Destroy, mutaborGUI::MutBoxChannelShape::DetachChannel, disconnect, mutabor::BoxClass::DisconnectFromAll, mutabor::CommonTypedDeviceAPI< T, P, L >::DisconnectFromAll, mutaborGUI::MutBoxChannelShape::ReadPanel, GUIRouteTest::testConnect.
bool mutabor::disconnect(Route r, Box box)
bool mutabor::disconnect(OutputDevice &out, Route &r)
References disconnect.
bool mutabor::disconnect(Box &box, Route &r)
References disconnect.
bool mutabor::reconnect(Route r, OutputDevice oldout, OutputDevice newout)
References mutASSERT.
Referenced by mutabor::BoxClass::MoveRoutes, mutabor::CommonTypedDeviceAPI< T, P, L >::MoveRoutes, mutaborGUI::MutBoxChannelShape::ReadPanel, GUIRouteTest::testConnect.
bool mutabor::reconnect(Route r, Box oldbox, Box newbox)
References mutASSERT.
bool mutabor::reconnect(OutputDevice out, Route oldroute, Route newroute)
References DEBUGLOG2.
Route mutabor::FindRoute(size_t id)
std::string mutabor::str(const timing_params &t)