MutTextBox
int MutTextBox::ColorBox
WinKind MutTextBox::winKind
Referenced by BoxChangedAction, mutaborGUI::MutChild::ClientToScreen, mutaborGUI::MutChild::GetClientSize, GetKind, MakeTitle, NewText, mutaborGUI::MutChild::OnAuiClose, mutaborGUI::MutChild::OnClose, OnClose, mutaborGUI::MutChild::SetClientSize, UpdateUI.
mutabor::Box MutTextBox::box
Referenced by Box, GetBoxActions, GetKeys, GetToneSystem, MakeTitle, MutTextBox, OnClose.
bool MutTextBox::Ok
Referenced by BoxChangedAction, UpdateUI.
MutTextBox::MutTextBox(WinKind k, mutabor::Box &b, wxWindow *parent=NULL, wxWindowID id=-1, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
References box, mutaborGUI::BoxData::GetBackgroundColour, mutaborGUI::BoxData::GetTextColour, mutaborGUI::ToGUIBase, TRACEC.
void MutTextBox::UpdateUI(wxCommandEvent &event)
References _, mutaborGUI::asTS, GetKeys, GetToneSystem, Ok, UNREACHABLEC, winKind, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
void MutTextBox::BoxChangedAction(int flags)
Handle box updates from ChangedCallback.
flags flags what has changed.
References _, mutaborGUI::CM_UPDATEUI, Ok, UNREACHABLEC, winKind, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
void MutTextBox::BoxChangedAction(const char *a)
Handle action messages from ChangedCallback.
action action that shall be executed.
References mutaborGUI::CM_UPDATEUI, winKind, WK_ACT.
void MutTextBox::GetKeys(bool asTS)
Get the string describing the current key configuration of our box.
This function collects key data from the box of the object and updates the corresponding list. asTS bool if true frequencies will be shown as absolute cents otherwise relative to the previous key.
References _, box, Clear, mutabor::BoxClass::tone_entry::invalid, mutabor_convert_pitch_to_frequency, mutabor::BoxClass::tone_entry::silent, mutabor::BoxClass::tone_entry::sounding.
Referenced by mutaborGUI::MutFrame::TextBoxOpen, UpdateUI.
void MutTextBox::GetToneSystem(bool asTS)
Update data to match the current tone system.
asTS bool if true frequencies will be shown as absolute cents otherwise relative to the previous key.
References _, mutabor::BoxClass::tone_system::anchor, box, Clear, mutabor::BoxClass::tone_entry::invalid, mutabor_convert_pitch_to_frequency, mutabor::BoxClass::tone_system::period, mutabor::BoxClass::tone_entry::silent, mutabor::BoxClass::tone_entry::sounding, mutabor::BoxClass::tone_system::tones.
Referenced by mutaborGUI::MutFrame::TextBoxOpen, UpdateUI.
void MutTextBox::GetAllActions()
Update date to match the list of all actions executed at sometime in any box.
References NewText.
Referenced by mutaborGUI::MutFrame::TextBoxOpen.
void MutTextBox::GetBoxActions()
Update date to match the list of all actions executed at sometime in one fixed box.
References box, NewText.
Referenced by mutaborGUI::MutFrame::TextBoxOpen.
void MutTextBox::NewText(char *s, bool newTitle=false)
References Clear, muT, mutASSERT, TRACEC, winKind, WK_ACT, WK_KEY, WK_NULL.
Referenced by GetAllActions, GetBoxActions.
void MutTextBox::NewText(const wxString &s, bool newTitle=false)
References Clear, DEBUGLOG, mutASSERT, winKind, WK_ACT, WK_KEY, WK_NULL.
wxString MutTextBox::MakeTitle() const
References _, box, mutaborGUI::CAW, TextBoxTitle, winKind, WK_ACT.
Referenced by mutaborGUI::MutChild::MakeTitle.
void MutTextBox::OnClose(wxCloseEvent &event)
References _, box, DEBUGLOG, mutaborGUI::BoxData::GetActionsWindow, mutaborGUI::BoxData::GetKeyWindow, mutaborGUI::BoxData::GetTonesystemWindow, mutaborGUI::LogicOn, mutASSERT, mutUnused, mutaborGUI::ToGUIBase, UNREACHABLEC, mutaborGUI::BoxData::WantActionsWindow, mutaborGUI::BoxData::WantKeyWindow, mutaborGUI::BoxData::WantTonesystemWindow, winKind, WK_ACT, WK_EDIT, WK_KEY, WK_LOGIC, WK_NULL, WK_ROUTE, WK_TS.
Referenced by mutaborGUI::MutChild::OnClose.
WinKind MutTextBox::GetKind()
References winKind.
Referenced by mutaborGUI::MutFrame::TextBoxOpen.
mutabor::Box MutTextBox::Box()
References box.