Parser.h
SRC_KERNEL_PARSER_H
SRC_KERNEL_PARSER_H_PRECOMPILED
MUTABOR_NO_CASE_LABEL
Referenced by get_umstimmungs_case_default_element.
mutabor_adjacent
Referenced by berechne_toene_absolut, test_zyklen.
mutabor_u_adjacent
Referenced by check_konsistenz, u_test_zyklen.
umst_oder_logik_typ
int ton_list_laenge(const struct ton *list)
References ton::next, TRACE.
Referenced by berechne_toene_absolut, mutabor::BoxClass::Compile, expandiere_tonsystem, mutabor_programm_einlesen.
int tonsystem_list_laenge(const struct tonsystem *list)
References tonsystem::next, TRACE.
Referenced by mutabor::BoxClass::Compile.
int umstimmungs_list_laenge(const struct umstimmung *list)
References umstimmung::next, TRACE.
Referenced by check_konsistenz, mutabor::BoxClass::Compile.
int logik_list_laenge(const struct logik *list)
References logik::next, TRACE.
Referenced by check_konsistenz, mutabor::BoxClass::Compile, expand_decition_tree.
int midi_list_laenge(const struct midiliste *list)
References midiliste::next, TRACE.
Referenced by create_midi_scan_liste, mutabor::BoxClass::MidiOut.
int get_logik_nummer(mutabor_box_type *box, const char *name, struct logik *liste)
References _, internal_error, mutabor_error_message, logik::name, logik::next, TRACE.
Referenced by expandiere_logik.
struct ton * get_ton(mutabor_box_type *box, const char *name, struct ton *liste)
References mutabor_box_type::file, ton::name, ton::next, mutabor_logic_parsed::ton_ohne_namen, TRACE.
Referenced by check_konsistenz, expandiere_tonsystem, get_komplex_frequenz.
struct intervall * get_intervall(const char *name, struct intervall *liste)
References intervall::name, intervall::next, TRACE.
Referenced by check_komplex_intervall, get_komplex_faktor.
struct tonsystem * parser_get_tonsystem(const char *name, struct tonsystem *liste)
References tonsystem::name, tonsystem::next, TRACE.
Referenced by check_aktionen, check_konsistenz, expandiere_logik, expandiere_name.
struct umstimmung * get_umstimmung(const char *name, struct umstimmung *liste)
References umstimmung::name, umstimmung::next, TRACE.
Referenced by check_aktionen, check_konsistenz, expandiere_logik, expandiere_name.
struct harmonie * get_harmonie(const char *name, struct harmonie *liste)
References harmonie::name, harmonie::next, TRACE.
Referenced by check_ausloeser, expand_pattern.
struct logik * get_logik(const char *name, struct logik *liste)
References logik::name, logik::next, TRACE.
Referenced by check_aktionen, check_konsistenz, expandiere_name.
void init_integersequenz(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::list_of_integers, TRACE.
Referenced by switch, yyparse.
void get_new_integer_in_integersequenz(mutabor_box_type *box, int wert)
References mutabor_box_type::file, mutabor_logic_parsed::list_of_integers, midiliste::midi_code, midiliste::next, TRACE, xmalloc.
Referenced by switch, yyparse.
struct parameter_list * get_new_name_in_parameterlist(mutabor_box_type *box, const char *name)
References parameter_list::name, parameter_list::next, TRACE, xmalloc.
Referenced by switch, yyparse.
void enumerate_parameters(mutabor_box_type *box, struct parameter_list *parameters)
References mutabor_box_type::file, parameter_list::index, parameter_list::next, mutabor_logic_parsed::parameter_count.
Referenced by switch.
struct argument_list * get_new_number_in_argument_list(mutabor_box_type *box, double number)
References argument::argument_type, argument::integer, mutabor_argument_integer, argument_list::next, TRACE, argument::u, xmalloc.
Referenced by switch, yyparse.
struct argument_list * get_new_name_in_argument_list(mutabor_box_type *box, const char *parameter_name)
References argument::argument_type, mutabor_argument_parameter, parameter_list::name, argument_list::next, argument::parameter, TRACE, argument::u, xmalloc.
Referenced by switch, yyparse.
struct argument_list * get_new_distance_in_argument_list(mutabor_box_type *box)
References argument::argument_type, mutabor_argument_distance, argument_list::next, TRACE, xmalloc.
Referenced by switch.
struct argument_list * get_new_anchor_in_argument_list(mutabor_box_type *box)
References argument::argument_type, mutabor_argument_anchor, argument_list::next, TRACE, xmalloc.
Referenced by switch.
void init_aktions_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::list_of_aktionen, TRACE.
Referenced by switch, yyparse.
void get_new_aktion_aufruf_element(mutabor_box_type *box, const char *name, struct argument_list *arguments)
References aktion_aufruf, mutabor_box_type::file, mutabor_logic_parsed::list_of_aktionen, aktions_liste::name, aktions_liste::next, TRACE, aktions_liste::u, xmalloc.
Referenced by switch, yyparse.
void get_new_aktion_midi_out_element(mutabor_box_type *box)
References aktion_midi_out, mutabor_box_type::file, get_last_integersequenz, mutabor_logic_parsed::list_of_aktionen, aktions_liste::next, TRACE, aktions_liste::u, xmalloc.
Referenced by switch, yyparse.
void get_new_aktion_harmony_analysis(mutabor_box_type *box)
References aktion_harmony_analysis, mutabor_box_type::file, mutabor_logic_parsed::list_of_aktionen, aktions_liste::next, TRACE, xmalloc.
Referenced by switch.
void init_komplex_ton_list(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::the_komplex_liste, TRACE.
Referenced by switch, yyparse.
void get_new_faktor_anteil(mutabor_box_type *box, double f, const char *name)
References komplex_intervall::faktor, mutabor_box_type::file, komplex_intervall::name, komplex_intervall::next, mutabor_logic_parsed::the_komplex_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
bool mutabor_programm_einlesen(mutabor_box_type *box, const char *logic)
References anweisung::aktion, logik::anweisungsliste, anweisung::ausloeser, logik::ausloeser, berechne_intervalle_absolut, berechne_toene_absolut, case_liste::case_aktion, case_liste::case_label, check_konsistenz, mutabor_scanner_data::data, DEBUGLOG2, logik::einstimmungs_name, mutabor_box_type::file, get_instrument_dekl, get_new_intervall, get_new_ton_absolut, intervall_absolut, intervall::intervall_absolut, intervall::intervall_typ, case_liste::is_default, isDebugFlag, mutabor_logic_parsed::list_of_config_instrumente, mutabor_logic_parsed::list_of_constants, mutabor_logic_parsed::list_of_harmonien, mutabor_logic_parsed::list_of_instrumente, mutabor_logic_parsed::list_of_intervalle, mutabor_logic_parsed::list_of_logiken, mutabor_logic_parsed::list_of_toene, mutabor_logic_parsed::list_of_tonsysteme, mutabor_logic_parsed::list_of_umstimmungen, instrument::midi_bis, instrument::midi_in, instrument::midi_von, parameter_list::name, intervall::name, ton::name, tonsystem::name, umstimmung::name, logik::name, parameter_list::next, intervall::next, ton::next, tonsystem::next, case_liste::next, umstimmung::next, harmonie::next, anweisung::next, logik::next, instrument::next, umstimmung::parameter_liste, tonsystem::periode, mutabor_scanner_data::pos, mutabor_box_type::scanner, STUB, tonsystem::taste, tonsystem::toene, ton_list_laenge, TRACE, intervall::u, ton::u, umstimmung::u, umstimmung_breite_abs, umstimmung_breite_rel, umstimmung::umstimmung_breite_rel, umstimmung_midi_out, umstimmung_taste_abs, umstimmung_taste_rel, umstimmung::umstimmung_taste_rel, umstimmung_toene_veraendert, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, yyparse.
Referenced by mutabor::BoxClass::Compile, GMutCompile, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.
void get_new_intervall(mutabor_box_type *box, const char *name, double wert)
References _, compiler_error, mutabor_box_type::file, intervall_absolut, mutabor_logic_parsed::list_of_intervalle, mutabor_error_message, intervall::name, intervall::next, TRACE, intervall::u, xmalloc.
Referenced by mutabor_programm_einlesen, switch, yyparse.
void get_new_intervall_komplex(mutabor_box_type *box, const char *name)
References _, compiler_error, mutabor_box_type::file, get_last_komplex_intervall, intervall_komplex, mutabor_logic_parsed::list_of_intervalle, mutabor_error_message, intervall::name, intervall::next, TRACE, intervall::u, xmalloc.
Referenced by switch, yyparse.
void get_new_ton_absolut(mutabor_box_type *box, const char *name, double wert)
References _, compiler_error, mutabor_box_type::file, mutabor_logic_parsed::list_of_toene, mutabor_error_message, ton::name, ton::next, ton_absolut, TRACE, ton::u, xmalloc.
Referenced by mutabor_programm_einlesen, switch, yyparse.
void get_new_ton_komplex_positive(mutabor_box_type *box, const char *name, const char *bezugston)
References _, ton::bezugston, compiler_error, mutabor_box_type::file, get_last_komplex_intervall, mutabor_logic_parsed::list_of_toene, mutabor_error_message, ton::name, ton::next, ton_komplex, TRACE, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_new_ton_komplex_negative(mutabor_box_type *box, const char *name, const char *bezugston)
References _, ton::bezugston, compiler_error, komplex_intervall::faktor, mutabor_box_type::file, get_last_komplex_intervall, internal_error, mutabor_logic_parsed::list_of_toene, mutabor_error_message, ton::name, komplex_intervall::next, ton::next, ton_komplex, TRACE, ton::u, xmalloc.
Referenced by switch, yyparse.
void init_ton_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::ton_liste, TRACE.
Referenced by switch, yyparse.
void get_new_ton_in_tonsystem(mutabor_box_type *box, const char *name)
References mutabor_box_type::file, ton::name, ton::next, mutabor_logic_parsed::ton_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_new_tonsystem(mutabor_box_type *box, const char *name, int taste)
References _, compiler_error, mutabor_box_type::file, get_last_komplex_intervall, mutabor_logic_parsed::list_of_tonsysteme, mutabor_error_message, tonsystem::name, tonsystem::next, tonsystem::periode, tonsystem::taste, tonsystem::toene, mutabor_logic_parsed::ton_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_new_tonsystem_negative(mutabor_box_type *box, const char *name, int taste)
References _, compiler_error, komplex_intervall::faktor, mutabor_box_type::file, get_last_komplex_intervall, internal_error, mutabor_logic_parsed::list_of_tonsysteme, mutabor_error_message, tonsystem::name, komplex_intervall::next, tonsystem::next, tonsystem::taste, mutabor_logic_parsed::ton_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
void init_umstimmung(mutabor_box_type *box, const char *name)
References _, compiler_error, mutabor_box_type::file, mutabor_logic_parsed::list_of_umstimmungen, mutabor_error_message, umstimmung::name, umstimmung::next, umstimmung::parameter_liste, mutabor_logic_parsed::tmp_umstimmung, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_new_umstimmung(mutabor_box_type *box)
References umstimmung::argument_liste, mutabor_box_type::file, link_arguments_to_parameters, mutabor_logic_parsed::list_of_umstimmungen, umstimmung::next, umstimmung::parameter_liste, mutabor_logic_parsed::tmp_umstimmung, TRACE.
Referenced by switch, yyparse.
void eintrage_parameterliste_in_umstimmung(mutabor_box_type *box, struct umstimmung *ret, parameter_list *list)
References umstimmung::parameter_liste, TRACE.
Referenced by switch, yyparse.
void get_umstimmung_taste_abs(mutabor_box_type *box, argument_list *argument)
References umstimmung::argument_liste, mutabor_box_type::file, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_taste_abs.
Referenced by switch, yyparse.
void get_umstimmung_taste_rel(mutabor_box_type *box, argument_list *argument, char vorzeichen)
References umstimmung::argument_liste, mutabor_box_type::file, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung::u, umstimmung_taste_rel.
Referenced by switch, yyparse.
void get_umstimmung_breite_abs(mutabor_box_type *box, argument_list *argument)
References umstimmung::argument_liste, mutabor_box_type::file, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_breite_abs.
Referenced by switch, yyparse.
void get_umstimmung_breite_rel(mutabor_box_type *box, argument_list *argument, char vorzeichen)
References umstimmung::argument_liste, mutabor_box_type::file, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung::u, umstimmung_breite_rel.
Referenced by switch, yyparse.
void init_umstimm_expression_list(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_tonliste, TRACE.
Referenced by switch, yyparse.
void get_new_umstimm_expression(mutabor_box_type *box, const char *bezugston)
References ton::bezugston, mutabor_box_type::file, ton::name, ton::next, mutabor_logic_parsed::tmp_tonliste, ton_komplex, TRACE, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_new_umstimm_expression_positive(mutabor_box_type *box, const char *bezugston)
References ton::bezugston, mutabor_box_type::file, get_last_komplex_intervall, ton::name, ton::next, mutabor_logic_parsed::tmp_tonliste, ton_komplex, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_new_umstimm_expression_negative(mutabor_box_type *box, const char *bezugston)
References ton::bezugston, komplex_intervall::faktor, mutabor_box_type::file, get_last_komplex_intervall, ton::name, komplex_intervall::next, ton::next, mutabor_logic_parsed::tmp_tonliste, ton_komplex, TRACE, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_umstimmung_tonhoehe_veraendert(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_tonliste, mutabor_logic_parsed::tmp_umstimmung, umstimmung_toene_veraendert, umstimmung::umstimmung_toene_veraendert.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_abs(mutabor_box_type *box)
References mutabor_box_type::file, get_last_komplex_intervall, mutabor_logic_parsed::tmp_umstimmung, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_abs_negative(mutabor_box_type *box)
References _, komplex_intervall::faktor, mutabor_box_type::file, get_last_komplex_intervall, internal_error, mutabor_error_message, mutabor_logic_parsed::tmp_umstimmung, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_rel_positive(mutabor_box_type *box)
References mutabor_box_type::file, get_last_komplex_intervall, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_wiederholung_rel, umstimmung::umstimmung_wiederholung_rel.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_rel_negative(mutabor_box_type *box)
References komplex_intervall::faktor, mutabor_box_type::file, get_last_komplex_intervall, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_wiederholung_rel, umstimmung::umstimmung_wiederholung_rel.
Referenced by switch, yyparse.
void get_umstimmung_umstimmungs_bund(mutabor_box_type *box)
References _, aktion_aufruf, aktions_liste::aktion_aufruf, argument_list::argument, argument::argument_type, compiler_error, mutabor_box_type::file, get_last_aktions_liste, get_parameter_by_name, link_arguments_to_parameters, mutabor_argument_parameter, mutabor_error_message, parameter_list::name, umstimmung::name, argument_list::next, aktions_liste::next, argument::parameter, mutabor_logic_parsed::tmp_umstimmung, TRACE, argument::u, aktions_liste::u, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund.
Referenced by switch, yyparse.
void get_umstimmungs_case_zahl_element(mutabor_box_type *box, int konstante)
References case_liste::case_aktion, case_liste::case_label, mutabor_box_type::file, get_last_aktions_liste, case_liste::is_default, case_liste::next, mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_umstimmungs_case_default_element(mutabor_box_type *box)
References case_liste::case_aktion, case_liste::case_label, mutabor_box_type::file, get_last_aktions_liste, case_liste::is_default, MUTABOR_NO_CASE_LABEL, case_liste::next, mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
void init_umstimmungs_case_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE.
Referenced by switch, yyparse.
void get_umstimmung_umstimm_case(mutabor_box_type *box, argument_list *argument)
References _, aktion_aufruf, aktions_liste::aktion_aufruf, argument_list::argument, compiler_error, mutabor_box_type::file, get_parameter_by_name, link_arguments_to_parameters, mutabor_argument_parameter, mutabor_error_message, parameter_list::name, umstimmung::name, argument_list::next, case_liste::next, aktions_liste::next, argument::parameter, mutabor_logic_parsed::tmp_umstimmung, mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE, argument::u, aktions_liste::u, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case.
Referenced by switch.
void get_umstimmung_midi_out(mutabor_box_type *box)
References mutabor_box_type::file, get_last_integersequenz, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_midi_out, umstimmung::umstimmung_midi_out.
Referenced by switch, yyparse.
void init_tastenliste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_tastenliste, TRACE.
Referenced by switch, yyparse.
void get_new_taste(mutabor_box_type *box, int taste, char stern)
References taste::code, mutabor_box_type::file, taste::next, taste::stern, mutabor_logic_parsed::tmp_tastenliste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_new_harmonie(mutabor_box_type *box, const char *name, int bezugstaste)
References _, harmonie::bezugstaste, compiler_error, mutabor_box_type::file, mutabor_logic_parsed::list_of_harmonien, mutabor_error_message, harmonie::name, harmonie::next, harmonie::tastenliste, mutabor_logic_parsed::tmp_tastenliste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_harmoniebezeichner(mutabor_box_type *box, int vor_taste, const char *name, int nach_taste)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_nach_taste, mutabor_logic_parsed::tmp_name, mutabor_logic_parsed::tmp_vor_taste.
Referenced by switch, yyparse.
void init_ausloeser(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_ausloeser, TRACE.
Referenced by switch, yyparse.
void get_ausloeser_default(mutabor_box_type *box)
References ausloeser_default, mutabor_box_type::file, mutabor_logic_parsed::tmp_ausloeser, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_harmonie(mutabor_box_type *box)
References ausloeser_harmonie, mutabor_box_type::file, mutabor_logic_parsed::tmp_ausloeser, mutabor_logic_parsed::tmp_nach_taste, mutabor_logic_parsed::tmp_name, mutabor_logic_parsed::tmp_vor_taste, TRACE, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_harmonie_form(mutabor_box_type *box)
References ausloeser_harmonie_form, mutabor_box_type::file, mutabor_logic_parsed::tmp_ausloeser, mutabor_logic_parsed::tmp_nach_taste, mutabor_logic_parsed::tmp_name, mutabor_logic_parsed::tmp_vor_taste, TRACE, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_taste(mutabor_box_type *box, const char *name)
References _, ausloeser_taste, compiler_error, mutabor_box_type::file, mutabor_error_message, ausloeser::name, mutabor_logic_parsed::tmp_ausloeser, TRACE, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_midi_in(mutabor_box_type *box)
References ausloeser_midi_in, mutabor_box_type::file, get_last_integersequenz, mutabor_logic_parsed::tmp_ausloeser, TRACE, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void init_anweisungs_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_anweisungsliste, TRACE.
Referenced by switch, yyparse.
void get_new_anweisung(mutabor_box_type *box)
References mutabor_box_type::file, get_last_aktions_liste, get_last_ausloeser, anweisung::next, mutabor_logic_parsed::tmp_anweisungsliste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_new_logik(mutabor_box_type *box, const char *name, const char *einstimmung)
References _, logik::anweisungsliste, compiler_error, logik::einstimmung, logik::einstimmungs_name, mutabor_box_type::file, get_last_ausloeser, logik::harmony_list, logik::keystroke_list, mutabor_logic_parsed::list_of_logiken, logik::midi_input_list, mutabor_error_message, logik::name, logik::next, TRACE, xmalloc.
Referenced by switch, yyparse.
void vervollstaendige_logik(mutabor_box_type *box)
References logik::anweisungsliste, mutabor_box_type::file, get_last_anweisungs_liste, mutabor_logic_parsed::list_of_logiken, logik::next, TRACE.
Referenced by switch, yyparse.
void get_instrument_dekl(mutabor_box_type *box, int midi_in, int midi_von, int midi_bis, int midi_umleit, struct instrument **list_to_insert)
References _, compiler_error, mutabor_error_message, logik::next, instrument::next, TRACE, xmalloc.
Referenced by mutabor_programm_einlesen, SetChannels, switch, yyparse.