GIS_Head.h
MU32_ROUTING_GMN_GIS_HEAD_H
MU32_ROUTING_GMN_GIS_HEAD_H_PRECOMPILED
CNAlter
Referenced by ChordNote::CheckCloseAlter, ChordNote::MutNoteOff, ChordNote::MutNoteOn.
CNNoteOn
Referenced by GisWriteHead::GetFreeNote, ChordNote::MutNoteOff, ChordNote::MutNoteOn, ChordNote::SetNoteOff, ChordNote::SetNoteOn.
ARType
typedef void GisReadProceed(GisReadHead *, char)(GisReadHead *, char)
typedef struct TagListData TagList
typedef void GisReadArtProceed(GisReadArtHead *token, char turn)(GisReadArtHead *token, char turn)
GisReadProceed GisReadDummy
GisReadArtProceed GisReadArtDummy
frac GisReadHeadOn(GisReadHead **Head, frac dTime, GisReadProceed *proceed)
References GisReadHead::Boss, GisReadHead::Cursor, GisReadHead::CursorNext, GisReadHead::CutOut, h, GisReadHead::Next, GisReadHead::nSub, GisReadHead::Read, GisReadHead::Time.
TagList * Copy(TagList *list)
References TagListData::Data, TagListData::Next, TagListData::Tag.
Referenced by GisReadArtHead::GisReadArtHead, mutaborGUI::MutEditFile::OnEditCopy.
void Erase(TagList *list)
References TagListData::Next.
Referenced by GisReadArtHead::~GisReadArtHead, GisWriteHead::~GisWriteHead.
frac GisReadArtHeadOn(GisReadArtHead **Head, frac dTime, GisReadArtProceed *proceed)
References GisReadHead::Boss, GisReadHead::Cursor, GisReadHead::CursorNext, GisReadHead::CutOut, DEBUGLOG2, h, GisReadHead::Next, GisReadHead::nSub, GisReadArtHead::Read, GisReadHead::Time, GisReadArtHead::Time2, TowxString, TRACE, GisReadHead::Turn.
Referenced by main.
int GisWriteHeadGis(GisWriteHead **head, mutString id, GisToken *token, char turn)
References GetMatchingHeader, GisWriteHead::ProceedGis.
Referenced by mutabor::OutputGis::do_Gis.
GisWriteHead * GetMatchingHeader(GisWriteHead **head, const mutString id)
References h, GisWriteHead::Id, GisWriteHead::InsertAfter, mutLen, mutStrCmp, GisWriteHead::Next, GisWriteHead::Prev.
Referenced by GisWriteHeadGis.
void CloseAllSubs(GisWriteHead *head)
References GisWriteHead::CloseSubs, GisWriteHead::CommaAtEnd, GisWriteHead::Cursor, GisWriteHead::CutOut, GisWriteHead::Data, GetGisType, GTSegment, h, mutT, GisWriteHead::Next, GisWriteHead::nSub, GisWriteHead::RemoveComma.
Referenced by mutabor::OutputGis::Close.