mutaborGUI::MutBoxIconShape
mutaborGUI::MutBoxIconShape::MutBoxIconShape()
mutaborGUI::MutBoxIconShape::MutBoxIconShape(wxWindow *parent, wxWindowID id=wxID_ANY)
References Create.
virtual mutaborGUI::MutBoxIconShape::~MutBoxIconShape()
bool mutaborGUI::MutBoxIconShape::Create(wxWindow *parent=NULL, wxWindowID id=wxID_ANY)
References MutIconShapeClass< T >::Create.
Referenced by mutaborGUI::MutBoxShape::Create, MutBoxIconShape.
virtual bool mutaborGUI::MutBoxIconShape::SetForegroundColour(const wxColour &colour)
References MutIconShapeClass< MutPanel >::staticText.
void mutaborGUI::MutBoxIconShape::GetBordersForSizer(int &borderTop, int &borderOther) const
References DEBUGLOG, MutIconShapeClass< MutPanel >::DoGetBestSize.
void mutaborGUI::MutBoxIconShape::OnDraw(wxDC &dc)
References MutIconShapeClass< MutPanel >::borderOffset, DEBUGLOG, MutIconShapeClass< MutPanel >::GetIcon, GetMutIcon, MutIconShapeClass< MutPanel >::maxBorderSize, MutIconShapeClass< MutPanel >::SetIcon, MutIconShapeClass< MutPanel >::staticText.
bool mutaborGUI::MutBoxIconShape::Layout()
References MutIconShapeClass< MutPanel >::borderOffset, MutIconShapeClass< MutPanel >::staticText, TRACEC.
Referenced by mutaborGUI::MutRouteWnd::AddBox, mutaborGUI::MutBoxShape::DoLeftDblClick.
MutIcon& mutaborGUI::MutBoxIconShape::GetMutIcon()
Calculates the Icon to be used.
References mutaborGUI::BoxBitmap, mutASSERT.
Referenced by OnDraw.