parser.c
u_adjazent
Adjazenz-Matrix Eintrag von u_matrix.
a Zeile b Spalte
Referenced by check_konsistenz, u_test_zyklen.
umst_oder_logik_typ
struct instrument* list_of_instrumente
Wurzel der Instrumente.
Referenced by yyparse.
struct instrument* list_of_config_instrumente
Wurzel der Instrumentenkonfiguration.
Referenced by mutabor_programm_einlesen.
FILE* mutabor_parser_in
Quelldatei f¸r das Mutabor-Programm.
Referenced by mutabor_programm_einlesen.
int anzahl_umstimmungen_und_logiken
so viele Umstimmungen wurden gelesen
Referenced by check_konsistenz, test_zyklen_nummer, u_test_zyklen.
struct umst_oder_logik* zyklen_feld
Feld von Umstimmungen zum schnelleren Zugriff als ueber Listen.
char* u_visited
Traversierungsmerker.
char* u_matrix
Adjazenzmatrix (auf sie darf nur ueber das folgende Makro zugegriffen werden !
void allgemeine_initialisierungen(void)
Allgemeine Initialisierungen.
Definiert ton_ohne_namen als ,,Nullton``.
References init_nullton.
void mutabor_programm_einlesen(char *filename)
Liest ein Mutabor-Programm ein.
Ist DEBUG_ANZEIGE definiert, dann werden die erzeugten Strukturen auf der Standard-Ausgabe angezeigt. Eigentlich sollte die Debug-Ausgabe auf die Standardfehlerausgabe.
References logik::ausloeser, berechne_intervalle_absolut, berechne_toene_absolut, case_liste::case_aktion, case_liste::case_label, check_konsistenz, drucke_argument, drucke_harmonie, drucke_ton, logik::einstimmungs_name, fatal_error, get_instrument_dekl, get_new_intervall, get_new_ton_absolut, intervall_absolut, intervall::intervall_absolut, intervall::intervall_typ, case_liste::is_default, list_of_config_instrumente, list_of_harmonien, list_of_intervalle, list_of_logiken, list_of_toene, list_of_tonsysteme, list_of_umstimmungen, instrument::midi_bis, instrument::midi_in, instrument::midi_von, mutabor_debug_level, mutabor_parser_in, mutabor_parser_parse, parameter_liste::name, logik::name, ton::name, tonsystem::name, umstimmung::name, komplex_intervall::name, intervall::name, instrument::next, parameter_liste::next, harmonie::next, logik::next, case_liste::next, ton::next, tonsystem::next, aktions_liste::next, umstimmung::next, intervall::next, umstimmung::parameter_liste, tonsystem::periode, print_aktions_liste, print_ausloeser, setze_nummer_von_abstand_und_zentrum, tonsystem::taste, tonsystem::toene, ton_list_laenge, ton::u, umstimmung::u, intervall::u, umstimmung_breite_abs, umstimmung::umstimmung_breite_abs, umstimmung_breite_rel, umstimmung::umstimmung_breite_rel, umstimmung_taste_abs, umstimmung::umstimmung_taste_abs, umstimmung_taste_rel, umstimmung::umstimmung_taste_rel, umstimmung_toene_veraendert, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, umstimmung::umstimmung_wiederholung_rel.
Referenced by mutabor::BoxClass::Compile, GMutCompile, main, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.
static void belege_zyklenfeld(struct umst_oder_logik *zyklen_feld, struct umstimmung *liste1, struct logik *liste2)
Erzeugt ein Array, in dem alle Umstimmungen und Logiken enthalten sind.
zyklen_feld Feld mit den Umstimmungen und Logiken liste1 einfach verkettete Liste mit Umstimmungen liste2 einfach verkettete Liste mit Logiken
References umst_oder_logik::logik, logik::next, umstimmung::next, typ_logik, typ_umstimmung, umst_oder_logik::u, umst_oder_logik::umst_oder_logik_typ, umst_oder_logik::umstimmung.
Referenced by check_konsistenz.
static int test_zyklen_nummer(char *name)
Sucht eine Umstimmung oder eine Logik in zyklen_feld.
Wird der Name nicht gefunden, wird ein fataler Fehler ausgelˆst. name Name der Umstimmung oder der Logik Nummer der gefundenen Umstimmung oder Logik
References anzahl_umstimmungen_und_logiken, fatal_error, typ_logik, typ_umstimmung, umst_oder_logik::u, umst_oder_logik::umst_oder_logik_typ.
Referenced by check_konsistenz.
static void u_test_zyklen(int startknoten)
Sucht nach Kreisen in der Adjazenzmatrix u_matrix.
startknoten Knoten, von dem ausgegangen werden soll
References anzahl_umstimmungen_und_logiken, fatal_error, umst_oder_logik::logik, logik::name, umstimmung::name, typ_umstimmung, umst_oder_logik::u, u_adjazent, umst_oder_logik::umst_oder_logik_typ, umst_oder_logik::umstimmung.
Referenced by check_konsistenz.
void check_konsistenz(void)
Testet das gesamte Mutabor-Programm auf Konsistenz.
Tonsysteme: ‹berpr¸fen, ob Periode und Tˆne deklariert sind und ob die Taste im Bereich 36 - 96 liegt. Umstimmungen: pr¸fen, ob alle Tˆne und Intervalle global deklariert sind, ob Umstimmungsbund und umstimmungs_case keine Rekursion enth‰lt, ob case_labels eindeutig sind, und ob die benutzten Parameter zu den deklarierten Parametern passen. Logiken: öberprÅfen, ob Einstimmung deklariert ist und ob die Anweisungen korrekt deklariert sind. Gegebenenfalls werden Warnungen und fatale Fehler ausgelˆst.
References aktion_aufruf, aktions_liste::aktion_aufruf, allgemeine_initialisierungen, anzahl_umstimmungen_und_logiken, belege_zyklenfeld, check_logik_konsistenz, check_tonsystem_konsistenz, check_umstimmungs_konsistenz, get_logik, get_umstimmung, list_of_logiken, list_of_umstimmungen, logik_list_laenge, mutabor_debug_level, case_liste::next, aktions_liste::next, test_zyklen_nummer, typ_logik, typ_umstimmung, aktions_liste::u, umst_oder_logik::u, umstimmung::u, u_adjazent, u_test_zyklen, umst_oder_logik::umstimmung, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund, umstimmungs_list_laenge, xalloca, xde_alloca.
Referenced by mutabor_programm_einlesen.