MidiKern.h
MU32_MIDIKERN_H
MU32_MIDIKERN_H_PRECOMPILED
DRUMCHANNEL
Referenced by mutabor::CommonMidiOutput< T, D >::do_NoteOff, mutabor::CommonMidiOutput< T, D >::EmergencyFindChannel, mutabor::ChannelFilter::operator().
DEFAULT_PANIC
Referenced by mutabor::InputMidiPort::Close, mutaborGUI::MutFrame::CmPanic, mutabor::InputGis::Stop, mutabor::InputMidiPort::Stop, mutabor::InputDeviceClass::Stop, CommonMidiInputTest::testGlobalPanic, CommonMidiInputTest::testPanic, mutabor::CommonFileInputDevice::ThreadPlay.
double mutabor_convert_pitch_to_factor(double interval)
Convert an interval represented as MIDI based double value to a frequency factor.
The microtonal part is retained in the double return value. interval interval in a midi based double. A half tone is represented as 1.00, and an octave as 12.00. frequency factor
Referenced by mutabor_convert_pitch_to_frequency.
double mutabor_convert_factor_to_pitch(double interval)
Convert an interval from factor representation to a pitch based double according to MIDI pitch numbers.
The microtonal part can be given in the double value. interval factor to be converted a double value that represents the interval. a semitone is represented as 1.00, and an octave as 12.00
Referenced by mutabor::hidden::expand_tonliste, mutabor::hidden::expandiere_tonsystem, mutabor::hidden::expandiere_umstimmung, mutabor_convert_frequency_to_pitch.
double mutabor_convert_pitch_to_frequency(double tone)
Convert an interval represented as MIDI based double value to a frequency.
The microtonal part is retained in the double return value. tone pitch in a midi based double. A half tone is represented as 1.00, and an octave as 12.00. frequency factor
References mutabor_convert_pitch_to_factor.
Referenced by MutTextBox::GetKeys, MutTextBox::GetToneSystem.
double mutabor_convert_frequency_to_pitch(double tone)
Convert a tone from frequency representation to a pitch based double according to MIDI pitch numbers.
The microtonal part can be given in the double value. tone frequency to be converted a double value that represents the pitch. a semitone is represented as 1.00, and an octave as 12.00
References mutabor_convert_factor_to_pitch.
Referenced by mutabor::hidden::expand_tonliste, mutabor::hidden::expandiere_tonsystem.