mutabor::frac
mutint64 mutabor::frac::n
Referenced by frac, numerator, operator bool, operator std::string, operator!, operator!=, operator*, operator*=, operator+, operator+=, operator-, operator-=, operator/, operator/=, operator<, mutabor::operator<<, operator<=, operator=, operator==, operator>, operator>=.
mutint64 mutabor::frac::d
Referenced by denominator, frac, operator std::string, operator!=, operator*, operator*=, operator+, operator+=, operator-, operator-=, operator/, operator/=, operator<, mutabor::operator<<, operator<=, operator=, operator==, operator>, operator>=.
mutabor::frac::frac()
References d, n.
mutabor::frac::frac(mutint64 integerval)
References d, n.
mutabor::frac::frac(mutint64 numerator, mutint64 denominator)
References d, denominator, n, numerator.
mutint64 mutabor::frac::numerator() const
References n.
Referenced by frac, mutabor::InputGis::ReadOn.
mutint64 mutabor::frac::denominator() const
References d.
Referenced by frac, mutabor::InputGis::ReadOn.
frac & frac::operator=(const frac &f)
References d, n.
frac & frac::operator+=(const frac &f)
References d, n.
frac & frac::operator-=(const frac &f)
References d, n.
frac & frac::operator*=(const frac &f)
References d, n.
frac & frac::operator/=(const frac &f)
References d, n.
frac frac::operator+(const frac &s)
References d, n.
frac frac::operator-(const frac &s)
References d, n.
frac frac::operator*(const frac &s)
References d, n.
frac frac::operator/(const frac &s)
References d, n.
int frac::operator<(const frac &f)
References d, n.
int frac::operator<=(const frac &f)
References d, n.
int frac::operator==(const frac &f)
References d, n.
int frac::operator!=(const frac &f)
References d, n.
int frac::operator>=(const frac &f)
References d, n.
int frac::operator>(const frac &f)
References d, n.
mutabor::frac::operator bool()
References n.
bool mutabor::frac::operator!()
References n.
frac & frac::operator=(const int &i)
mutint64 frac::gcd(mutint64 a, mutint64 b)
References absLong.
mutabor::frac::operator std::string() const
References d, n, mutabor::str.
std::ostream& operator<<(std::ostream &os, const frac &f)