mutaborGUI::RoutePanel
typedef std::list<BoxShapeData *> mutaborGUI::RoutePanel::boxdatalisttype
InputFilterPanel* mutaborGUI::RoutePanel::inPanel
Referenced by DECLARE_DYNAMIC_CLASS, GetInput, RoutePanel, SetInput.
OutputFilterPanel* mutaborGUI::RoutePanel::outPanel
Referenced by DECLARE_DYNAMIC_CLASS, GetOutput, RoutePanel, SetOutput.
MutBoxChannelShape* mutaborGUI::RoutePanel::channel
Referenced by DECLARE_DYNAMIC_CLASS, GetChannel, RoutePanel, SetChannel.
boxdatalisttype mutaborGUI::RoutePanel::boxdatalist
mutaborGUI::RoutePanel::DECLARE_DYNAMIC_CLASS(RoutePanel) public
References channel, inPanel, outPanel.
mutaborGUI::RoutePanel::RoutePanel(wxWindow *parent)
References channel, inPanel, outPanel.
mutaborGUI::RoutePanel::~RoutePanel()
bool mutaborGUI::RoutePanel::GetActive()
References RoutePanelBase::active.
Referenced by mutaborGUI::MutBoxChannelShape::ReadPanel.
void mutaborGUI::RoutePanel::SetActive(bool val)
References RoutePanelBase::active, RoutePanelBase::passive.
Referenced by mutaborGUI::MutBoxChannelShape::InitializeRoute.
bool mutaborGUI::RoutePanel::GetPassive()
References RoutePanelBase::passive.
void mutaborGUI::RoutePanel::SetPassive(bool val)
References RoutePanelBase::active, RoutePanelBase::passive.
void mutaborGUI::RoutePanel::SetBox(MutBoxShape *box)
mutabor::Box mutaborGUI::RoutePanel::GetBox()
References mutaborGUI::RoutePanel::BoxShapeData::GetBox, UNREACHABLEC.
Referenced by mutaborGUI::MutBoxChannelShape::ReadPanel.
void mutaborGUI::RoutePanel::SetInput(InputFilterPanel *in)
References inPanel.
Referenced by mutaborGUI::MutBoxChannelShape::CreateRoutePanel.
InputFilterPanel* mutaborGUI::RoutePanel::GetInput() const
References inPanel.
Referenced by mutaborGUI::MutBoxChannelShape::ReadPanel.
void mutaborGUI::RoutePanel::SetOutput(OutputFilterPanel *out)
References outPanel.
Referenced by mutaborGUI::MutBoxChannelShape::CreateRoutePanel.
OutputFilterPanel* mutaborGUI::RoutePanel::GetOutput() const
References outPanel.
Referenced by mutaborGUI::MutBoxChannelShape::ReadPanel.
void mutaborGUI::RoutePanel::SetChannel(MutBoxChannelShape *ch)
References channel.
Referenced by mutaborGUI::MutBoxChannelShape::CreateRoutePanel.
MutBoxChannelShape* mutaborGUI::RoutePanel::GetChannel() const
References channel.
wxChoice* mutaborGUI::RoutePanel::GetBoxChoice()
References RoutePanelBase::box.
int mutaborGUI::RoutePanel::AddBox(mutabor::Box box, bool selected=false)
References _, DEBUGLOG.
Referenced by mutaborGUI::MutBoxChannelShape::InitializeRoute.
void mutaborGUI::RoutePanel::EnableRoute(bool enable=true)