anweisung.h
struct anweisung* get_last_anweisungs_liste(void)
Gibt Wurzelelement von #tmp_anweisungs_liste zurück.
References tmp_anweisungsliste.
Referenced by vervollstaendige_logik.
void init_anweisungs_liste(void)
Setzt globalen Anweisungs-Zwischenspeicher auf NULL.
Die Liste wird nicht gelöscht. Das muss gegebenenfalls vor der Initialiserung manuell erledigt werden.
Referenced by switch, yyparse.
void get_new_anweisung(void)
Fügt eine neue Anweisung ans Ende von tmp_anweisungsliste an.
Dabei werden der letzte eingelesene Auslöser und die letzte Aktionsliste verwendet. Es wird immer die gesamte Liste durchsucht. Effektivität?
References anweisung::aktion, get_last_aktions_liste, get_last_ausloeser, anweisung::next, xmalloc.
Referenced by switch, yyparse.
void insert_in_lokale_liste(int instrument, struct anweisung *lauf, char *name_der_logik)
Fügt die auslösende Harmonien, Taste bzw.
das Midiereignis der Logik in die entsprechenede lokale Liste eines Instrumentes ein. instrument Instrument, für das das Ereignis eingefügt werden soll. lauf Anweisung, deren Auslöser eingefügt werden soll. name_der_logik Name der Logik, zu der die Anweisung gehört.
References anweisung::ausloeser, ausloeser_harmonie, ausloeser::u, ausloeser::ausloeser_harmonie, harmonie_ereignis::next, xmalloc, harmonie_ereignis::pattern, expand_pattern, harmonie_ereignis::ist_harmonieform, harmonie_ereignis::vortaste, harmonie_ereignis::nachtaste, name, harmonie_ereignis::aktion, expand_aktions_liste, anweisung::aktion, start_parameter_liste, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_default, ausloeser_taste, keyboard_ereignis::next, keyboard_ereignis::aktion, ausloeser_midi_in, midi_ereignis::next, midi_ereignis::first_pos, midi_ereignis::scan_pos, create_midi_scan_liste, ausloeser::ausloeser_midi_in, midi_ereignis::aktion, fatal_error.
Referenced by expandiere_logik, expand_decition_tree, mutabor_tabellen_generator.