mutabor::CommonMidiOutput
bank_type
typedef T mutabor::CommonMidiOutput< T, D >::midiprovider
typedef D mutabor::CommonMidiOutput< T, D >::base
OutputParameterType
midiprovider mutabor::CommonMidiOutput< T, D >::Out
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::controller, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::key_pressure, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::note_off, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::note_on, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::pitch_bend, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::program_change, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::quarter_frame, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::song_position, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::song_select, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::system.
int mutabor::CommonMidiOutput< T, D >::bending_range
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::do_SendBendingRange, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::fix_bend, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::GetBendingRange, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::pitch_and_bend, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::SetBendingRange.
bank_type mutabor::CommonMidiOutput< T, D >::bank_mode
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::program_change.
ChannelData mutabor::CommonMidiOutput< T, D >::Cd[16][16]
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::do_SendBendingRange.
channel_queue_type mutabor::CommonMidiOutput< T, D >::channel_queue
TonAufKanal mutabor::CommonMidiOutput< T, D >::ton_auf_kanal[16][16]
int mutabor::CommonMidiOutput< T, D >::nKeyOn
void mutabor::CommonMidiOutput< T, D >::Close()
References mutabor::CurrentTime, mutASSERT, TRACEC.
Referenced by InputMidiFileTest::testBatchPlay1, InputMidiFileTest::testBug019010_2, CommonMidiInputTest::testGlobalPanic, CommonMidiOutputTest::testMoreNotesThanChannels, CommonMidiOutputTest::testNoteOnOff, CommonMidiInputTest::testPanic.
channel_queue_type::const_iterator mutabor::CommonMidiOutput< T, D >::EmergencyFindChannel(RouteClass *r)
References DRUMCHANNEL, mutabor::TRouteClass< I, O, B >::GetOutputFrom, mutabor::TRouteClass< I, O, B >::GetOutputTo, mutASSERT, mutint64, mutabor::TRouteClass< I, O, B >::OutputAvoidDrumChannel.
void mutabor::CommonMidiOutput< T, D >::UpdateControllers(int channel, const ChannelData &input_channel_data)
Update the controller data of a channel.
A smplified characterization would be: copy channnel data. channel MIDI output channel whose controller data should be updated input_channel_data reference ChannelData objecet.
void mutabor::CommonMidiOutput< T, D >::CopyProgramChange(const ChannelData &input_channel_data, ChannelData &output_data, int channel)
Copies the program change and bank data from the input channel to the output choannel and issues the corresponding bank change and prgoram change messages.
input_channel_data input to be copied from output_data output to be copied to channel MIDI channel to output the data to
References mutabor::midi::BANK_COARSE, mutabor::midi::BANK_FINE, mutabor::ChannelData::get_bank_coarse, mutabor::ChannelData::get_bank_fine, mutabor::ChannelData::get_controller, mutabor::ChannelData::get_first_changed_controller, mutabor::ChannelData::get_next_changed_controller, mutabor::ChannelData::get_program, mutabor::ChannelData::is_changed_controller, mutabor::ChannelData::program_change, mutabor::ChannelData::set_controller.
void mutabor::CommonMidiOutput< T, D >::SetBendingRange(int br)
Referenced by mutaborGUI::MutOutputMidiDeviceShape::readDialog, mutaborGUI::MutOutputMidiFileDeviceShape::readDialog, OutputMidiFileTest::setUp, InputMidiFileTest::testAfterTouch, InputMidiFileTest::testAllControllerOff, InputMidiFileTest::testBankSelect, InputMidiFileTest::testBatchPlay1, InputMidiFileTest::testBoxMidiIn, InputMidiFileTest::testBug019010, InputMidiFileTest::testBug019010_2, InputMidiFileTest::testControllerPlay, InputMidiFileTest::testRpnNrpn, InputMidiFileTest::testSysEx.
int mutabor::CommonMidiOutput< T, D >::GetBendingRange() const
Referenced by compat30::SaveRoutes.
virtual int mutabor::CommonMidiOutput< T, D >::GetMaxChannel() const =0
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::SetBendingRange.
virtual int mutabor::CommonMidiOutput< T, D >::GetMinChannel() const =0
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::SetBendingRange.
mutabor::CommonMidiOutput< T, D >::CommonMidiOutput(int b)
bool mutabor::CommonMidiOutput< T, D >::do_Open()
References mutabor::Cd, mutabor::midi::CONTROLLER_OFF, mutabor::midi::LOCAL_ON_OFF, mutASSERT, mutabor::midi::OMNI_ON, mutabor::midi::POLY_ON, mutabor::ChannelData::Reset, mutabor::ChannelData::set_controller, TRACEC.
void mutabor::CommonMidiOutput< T, D >::do_NoteOn(Box box, int inkey, int velocity, RouteClass *r, size_t id, const ChannelData &input_channel_data)
Really send the beginning of a sounding note.
box Mutabor box that contains the tuning information taste input key from file or keyboard velo key press velocity r route that has been used to transmit the note id an additional number that is used to make the note unique input_channel_data current device settings (Controllers, Sound, etc.) OutputDeviceClass::NoteOn, OutputDeviceClass::NoteOff Noch zu erledigencurrently portamento and legato switches may not work as the device does not know which notes from different channels should be combined
References mutabor::pitch_bend_type::bend, mutabor::Cd, mutabor::midi::CONTROLLER_OFF, DEBUGLOG, mutabor::ChannelData::get_bend, mutabor::ChannelData::get_controller, mutabor::midi::get_holds, mutabor::TRouteClass< I, O, B >::get_session_id, mutabor::BoxClass::tone::is_active, mutASSERT, mutabor::pitch_bend_type::pitch, mutabor::ChannelData::set_bend, mutabor::ChannelData::set_controller, UNREACHABLEC.
void mutabor::CommonMidiOutput< T, D >::do_NoteOff(Box box, int inkey, int velo, RouteClass *r, size_t id, bool is_note_on)
References mutabor::Cd, DEBUGLOG, DRUMCHANNEL, mutabor::TRouteClass< I, O, B >::get_session_id, mutabor::TRouteClass< I, O, B >::GetOutputFrom, mutabor::TRouteClass< I, O, B >::GetOutputTo, mutASSERT, mutabor::TRouteClass< I, O, B >::OutputAvoidDrumChannel, UNREACHABLEC.
void mutabor::CommonMidiOutput< T, D >::do_UpdateTones(RouteClass *route)
References mutabor::pitch_bend_type::bend, mutabor::Cd, mutabor::midi::CONTROLLER_OFF, DEBUGLOG, mutabor::ChannelData::get_bend, mutabor::midi::get_holds, mutabor::TRouteClass< I, O, B >::get_session_id, mutabor::TRouteClass< I, O, B >::GetBox, mutabor::TAK::inkey, mutASSERT, mutabor::TAK::outkey, mutabor::pitch_bend_type::pitch, mutabor::ChannelData::set_bend, TRACEC, mutabor::TAK::tuned_key, UNREACHABLEC, mutabor::TAK::velocity.
void mutabor::CommonMidiOutput< T, D >::do_Controller(int mutabor_channel, int controller, int value, size_t id)
References mutabor::Cd, mutabor::ChannelData::IGNORE_UNIQUE_ID, mutabor::midi::LOCAL_ON_OFF, mutASSERT, mutabor::midi::OMNI_ON, mutabor::midi::PITCH_BEND_SENSITIVITY, mutabor::midi::POLY_ON.
void mutabor::CommonMidiOutput< T, D >::do_Controller(ChannelData &output, int channel, int ctrl, int value)
References mutabor::midi::ALL_CONTROLLERS_OFF, mutabor::midi::ALL_NOTES_OFF, mutabor::midi::ALL_SOUND_OFF, bending_range, mutabor::midi::CONTROLLER_UNKNOWN, mutabor::midi::DATA_BUTTON_DECREMENT, mutabor::midi::DATA_BUTTON_INCREMENT, mutabor::midi::DATA_ENTRY_COARSE, mutabor::midi::DATA_ENTRY_FINE, mutabor::midi::FIRST_NRPN, mutabor::midi::FIRST_RPN, mutabor::ChannelData::get_controller, mutabor::ChannelData::get_hold, mutabor::ChannelData::get_index, mutabor::midi::is_hold, mutabor::midi::LAST_NRPN, mutabor::midi::LAST_RPN, mutabor::midi::LOCAL_ON_OFF, mutabor::ChannelData::MidiReset, mutabor::midi::MONO_ON, mutASSERT, mutabor::midi::OMNI_OFF, mutabor::midi::OMNI_ON, mutabor::midi::PITCH_BEND_SENSITIVITY, mutabor::midi::POLY_ON, mutabor::ChannelData::set_controller.
int mutabor::CommonMidiOutput< T, D >::do_GetChannel(int inkey, size_t channel, size_t id)
References mutASSERT, mutabor::midi::NO_CHANNEL, TRACEC.
void mutabor::CommonMidiOutput< T, D >::do_handle_event(event e)
Act or send data according to a given evnt type.
The event types are defined in event.h.This function acts only on those events that are handled equally in all MIDI devices. Other events (e.g. META events) should be handled in the corresponding subclass. e event to be acted on.
References mutabor::midi::ACTIVE_SENSE, mutabor::midi::CLOCK, mutabor::midi::CONTINUE_PLAY, mutabor::midi::CONTROLLER, mutabor::controller_event::get_controller, mutabor::sysex_event::get_message, mutabor::key_pressure_event::get_note, mutabor::song_position_event::get_position, mutabor::key_pressure_event::get_pressure, mutabor::quarter_frame_event::get_quarter_type, mutabor::quarter_frame_event::get_quarter_values, mutabor::event_class::get_route_channel, mutabor::song_select_event::get_song, mutabor::event_class::get_unique_id, mutabor::controller_event::get_value, mutabor::midi::KEY_PRESSURE, mutabor::midi::NO_CHANNEL, mutabor::midi::QUARTER_FRAME, mutabor::midi::REALTIME_UNDEFINED, mutabor::midi::RESET, mutabor::midi::SONG_POSITION, mutabor::midi::SONG_SELECT, mutabor::midi::START_PLAY, mutabor::midi::STOP_PLAY, mutabor::midi::SYSEX_END, mutabor::midi::SYSEX_START, mutabor::midi::SYSTEM_UNDEFINED1, mutabor::midi::SYSTEM_UNDEFINED2, mutabor::midi::TICK, mutabor::midi::TUNE_REQUEST.
void mutabor::CommonMidiOutput< T, D >::do_SplitOut(uint8_t *p, size_t n)
References mutabor::midi::ACTIVE_SENSE, mutabor::midi::AFTER_TOUCH, mutabor::midi::CHANNEL_MASK, mutabor::midi::CHANNEL_PRESSURE, mutabor::midi::CLOCK, mutabor::midi::CONTINUE_PLAY, mutabor::midi::CONTROLLER, mutASSERT, mutabor::midi::NOTE_OFF, mutabor::midi::NOTE_ON, mutabor::midi::PITCH_BEND, mutabor::midi::PROGRAM_CHANGE, mutabor::midi::QUARTER_FRAME, mutabor::midi::RESET, mutabor::midi::SONG_POSITION, mutabor::midi::SONG_SELECT, mutabor::midi::START_PLAY, mutabor::midi::STOP_PLAY, mutabor::midi::SYSEX_END, mutabor::midi::SYSEX_START, mutabor::midi::SYSTEM, mutabor::midi::TICK, mutabor::midi::TUNE_REQUEST, mutabor::midi::TYPE_MASK.
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::do_MidiOut.
void mutabor::CommonMidiOutput< T, D >::do_Quiet(Route r, int type)
References mutASSERT, TRACEC.
void mutabor::CommonMidiOutput< T, D >::do_Quiet(Route r, int type, size_t id)
References TRACEC.
void mutabor::CommonMidiOutput< T, D >::do_Panic(int type)
References mutabor::Cd, mutabor::ChannelData::Reset, TRACEC.
void mutabor::CommonMidiOutput< T, D >::do_SendBendingRange(int channel)
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::SetBendingRange.
void mutabor::CommonMidiOutput< T, D >::do_Gis(GisToken *, char)
Gis output is unimplemented.
Ignore GIS tokens.
void mutabor::CommonMidiOutput< T, D >::do_MidiOut(uint8_t *p, size_t n)
void mutabor::CommonMidiOutput< T, D >::do_MidiOut(mutabor::Box box, midi_string data)
void mutabor::CommonMidiOutput< T, D >::do_UpdateControllers(int channel, const ChannelData &input_channel_data)
References mutabor::Cd, mutabor::midi::DATA_BUTTON_DECREMENT, mutabor::midi::DATA_BUTTON_INCREMENT, mutabor::midi::DATA_ENTRY_COARSE, mutabor::midi::DATA_ENTRY_FINE, mutabor::ChannelData::get_first_changed_controller, mutabor::ChannelData::get_next_changed_controller, mutabor::ChannelData::is_changed_controller, mutabor::midi::NON_REGISTERED_PARAMETER_COARSE, mutabor::midi::NON_REGISTERED_PARAMETER_FINE, mutabor::midi::REGISTERED_PARAMETER_COARSE, mutabor::midi::REGISTERED_PARAMETER_FINE, mutabor::ChannelData::set_controller.
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::UpdateControllers.
void mutabor::CommonMidiOutput< T, D >::CopyController(const ChannelData &input, ChannelData &output, int channel, int number)
Copy a single controller value and output it apropriately.
input Source output Destination channel MIDI channel ctrl controller to be copied
References mutabor::ChannelData::get_controller.
void mutabor::CommonMidiOutput< T, D >::OutputParameter(ChannelData &data, int channel, OutputParameterType type, int value, int old_value, int ctrl)
Outputs a registered or non registered parameter according to the state of a given ChannelData object.
data cannel data holding the output mirror state channel channel the parameter shall be sent to type type: RPN or NRPN value value: The new value that shall be transmitted old_value the value that shall be considered to be the current state of the output device. This may be different from the current state of data to allow preprocessing in the calling function ctrl Controller that shall be transmitted newctrl New value of the controller for internal use.
References mutabor::midi::DATA_ENTRY_COARSE, mutabor::midi::DATA_ENTRY_FINE, mutabor::midi::FIRST_NRPN, mutabor::midi::FIRST_RPN, mutabor::ChannelData::get_controller, mutabor::ChannelData::get_index, mutabor::midi::LAST_NRPN, mutabor::midi::LAST_RPN, mutabor::midi::NON_REGISTERED_PARAMETER_COARSE, mutabor::midi::NON_REGISTERED_PARAMETER_FINE, mutabor::midi::REGISTERED_PARAMETER_COARSE, mutabor::midi::REGISTERED_PARAMETER_FINE, mutabor::ChannelData::set_controller, UNREACHABLEC.
void mutabor::CommonMidiOutput< T, D >::pitch_bend(int channel, int value)
Sends a pitchbend signal.
channel Channel on which the data shall be sent. value Data to be sent range has already been honoured Center is at 0.
void mutabor::CommonMidiOutput< T, D >::program_change(int channel, int sound, int lsb, int msb)
void mutabor::CommonMidiOutput< T, D >::controller(int channel, int controller, int value)
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::do_SendBendingRange, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::program_change.
void mutabor::CommonMidiOutput< T, D >::note_on(int channel, int pitch, int velocity)
void mutabor::CommonMidiOutput< T, D >::note_off(int channel, int pitch, int velocity)
void mutabor::CommonMidiOutput< T, D >::key_pressure(int channel, int key, int pressure)
void mutabor::CommonMidiOutput< T, D >::system(int type)
Send a single byte system message.
type Type of the message;
void mutabor::CommonMidiOutput< T, D >::quarter_frame(int type, int values)
Send a quarter frame event.
type quarter frame type (may set only the lowest 3 bits) values qarter frame value (may set only the lowest 4 bits)
void mutabor::CommonMidiOutput< T, D >::song_position(int position)
Send a song positon event.
position Position to be sent. Must be between 0x0000 and 0x3fff.
void mutabor::CommonMidiOutput< T, D >::song_select(int song)
long mutabor::CommonMidiOutput< T, D >::fix_bend(long bend)
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::pitch_and_bend.
pitch_bend_type mutabor::CommonMidiOutput< T, D >::pitch_and_bend(const BoxClass::tone &tuned_note)
Referenced by mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::pitch_and_bend.
pitch_bend_type mutabor::CommonMidiOutput< T, D >::pitch_and_bend(const BoxClass::tone &tuned_note, const pitch_bend_type &old)
mutabor::CommonMidiOutput< T, D >::CommonMidiOutput()
mutabor::CommonMidiOutput< T, D >::CommonMidiOutput(std::string name, int id=-1, int bendingRange=2)