libintl.cpp
muT
Referenced by mutaborGUI::MutFrame::RaiseLogic, wxwidgets_bindtextdomain, wxwidgets_gettext, wxwidgets_textdomain.
typedef std::map<wxwidgets_gettext_mapkey, wxwidgets_gettext_result> wxwidgets_gettext_map
wxwidgets_gettext_map cache
const char * wxwidgets_sgettext(const char *msgid)
not for headers
References wxwidgets_gettext.
const char const char * wxwidgets_dgettext(const char *domainname, const char *msgid)
References wxwidgets_gettext.
const char const char const char * wxwidgets_sngettext(const char *msgid1, const char *msgid2, unsigned long int n)
References wxwidgets_gettext.
const char * wxwidgets_dngettext(const char *domainname, const char *msgid1, const char *msgid2, unsigned long int n)
References wxwidgets_gettext.
char * wxwidgets_textdomain(const char *__domainname)
References muT, STUB.
char * wxwidgets_bindtextdomain(const char *__domainname, const char *__dirname)
References muT, STUB.
const char * wxwidgets_gettext(const std::string &msgid)
References muT.
Referenced by wxwidgets_dgettext, wxwidgets_dngettext, wxwidgets_sgettext, wxwidgets_sngettext.
const char * wxwidgets_gettext(const std::string &domainname, const std::string &msgid)
References muT.
const char * wxwidgets_gettext(const std::string &msgid1, const std::string &msgid2, unsigned long int n)
References muT.
const char * wxwidgets_gettext(const std::string &domainname, const std::string &msgid1, const std::string &msgid2, unsigned long int n)
References muT.