mutaborGUI::MutEditFile
friend class MutEditProperties
friend class MutEditPrint
wxString mutaborGUI::MutEditFile::m_filename
Referenced by CmCompile, CmFileSave, CmFileSaveAs, Compile, DoLoadFile, DoSaveFile, GetFilename, Init, LoadFile, SaveFile, SetFilename.
LanguageInfo const* mutaborGUI::MutEditFile::m_language
Referenced by GetLanguageInfo, Init, InitializePrefs, mutaborGUI::MutEditProperties::MutEditProperties.
int mutaborGUI::MutEditFile::m_LineNrID
Referenced by Init, InitializePrefs, OnLineNumber.
int mutaborGUI::MutEditFile::m_LineNrMargin
Referenced by Init, OnLineNumber, OnSize.
int mutaborGUI::MutEditFile::m_FoldingID
Referenced by Init, InitializePrefs.
int mutaborGUI::MutEditFile::m_FoldingMargin
Referenced by Init, InitializePrefs, OnSize.
int mutaborGUI::MutEditFile::m_DividerID
Referenced by Init, InitializePrefs.
MutView* mutaborGUI::MutEditFile::view
Referenced by SetView, ~MutEditFile.
muConvAuto mutaborGUI::MutEditFile::autoConverter
Referenced by DoLoadFile, DoSaveFile.
MutSTCLexer mutaborGUI::MutEditFile::lexer
Referenced by OnStyleNeeded.
mutaborGUI::MutEditFile::MutEditFile(wxWindow *parent, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, const wxString &value=wxEmptyString, const wxString &name=wxTextCtrlNameStr)
MutEditFile::MutEditFile(MutView *v, wxWindow *parent, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, const wxString &value=wxEmptyString, const wxString &name=wxTextCtrlNameStr)
References Init, mutaborGUI::StatusBar::SetInsert.
MutEditFile::~MutEditFile()
References mutaborGUI::MutView::SetTextsw, view.
void mutaborGUI::MutEditFile::SetView(MutView *v)
References view.
Referenced by END_EVENT_TABLE.
void MutEditFile::OnSize(wxSizeEvent &event)
References mutaborGUI::CommonInfo::foldEnable, mutaborGUI::g_CommonPrefs, mutaborGUI::CommonInfo::lineNumberEnable, m_FoldingMargin, m_LineNrMargin.
void MutEditFile::OnEditRedo(wxCommandEvent &event)
void MutEditFile::OnEditUndo(wxCommandEvent &event)
void MutEditFile::OnEditClear(wxCommandEvent &event)
References Clear.
void MutEditFile::OnEditCut(wxCommandEvent &event)
void MutEditFile::OnEditCopy(wxCommandEvent &event)
References Copy.
void MutEditFile::OnEditPaste(wxCommandEvent &event)
void MutEditFile::OnEditRedoUI(wxUpdateUIEvent &event)
void MutEditFile::OnEditUndoUI(wxUpdateUIEvent &event)
void MutEditFile::OnFind(wxCommandEvent &event)
References mutUnused.
void MutEditFile::OnFindNext(wxCommandEvent &event)
References DoFind, mutaborGUI::MutEditFile::FindFlags::Down.
void MutEditFile::OnFindDialog(wxFindDialogEvent &event)
References _, DEBUGLOG, DoFind, mutaborGUI::MutEditFile::FindFlags::down, mutaborGUI::MutEditFile::FindFlags::Down, SaveSearchData, mutaborGUI::MutEditFile::FindFlags::ShowNotFound, UNREACHABLEC, mutaborGUI::MutEditFile::FindFlags::UseCaret.
int MutEditFile::DoFind(const wxString &pattern, FindFlags flags)
References _, mutaborGUI::MutEditFile::FindFlags::askCircular, mutaborGUI::MutEditFile::FindFlags::down, mutaborGUI::MutEditFile::FindFlags::showNotFound, TRACEC, mutaborGUI::MutEditFile::FindFlags::useCaret.
Referenced by OnFindDialog, OnFindNext.
void MutEditFile::OnReplace(wxCommandEvent &event)
References OnReplaceNext.
void MutEditFile::OnReplaceNext(wxCommandEvent &event)
Referenced by OnReplace.
void MutEditFile::OnBraceMatch(wxCommandEvent &event)
void MutEditFile::OnGoto(wxCommandEvent &event)
References _.
void MutEditFile::OnEditIndentInc(wxCommandEvent &event)
void MutEditFile::OnEditIndentRed(wxCommandEvent &event)
void MutEditFile::OnEditSelectAll(wxCommandEvent &event)
void MutEditFile::OnEditSelectLine(wxCommandEvent &event)
void MutEditFile::OnHilightLang(wxCommandEvent &event)
view
References mutaborGUI::CM_HILIGHTFIRST, mutaborGUI::g_LanguagePrefs, InitializePrefs, mutaborGUI::LanguageInfo::name.
void MutEditFile::OnDisplayEOL(wxCommandEvent &event)
void MutEditFile::OnIndentGuide(wxCommandEvent &event)
void MutEditFile::OnLineNumber(wxCommandEvent &event)
References m_LineNrID, m_LineNrMargin.
void MutEditFile::OnLongLineOn(wxCommandEvent &event)
void MutEditFile::OnWhiteSpace(wxCommandEvent &event)
void MutEditFile::OnFoldToggle(wxCommandEvent &event)
void MutEditFile::OnSetOverType(wxCommandEvent &event)
References mutaborGUI::StatusBar::SetInsert.
void MutEditFile::OnSetReadOnly(wxCommandEvent &event)
void MutEditFile::OnWrapmodeOn(wxCommandEvent &event)
void MutEditFile::OnUseCharset(wxCommandEvent &event)
void MutEditFile::OnChangeCase(wxCommandEvent &event)
extra
void MutEditFile::OnConvertEOL(wxCommandEvent &event)
void MutEditFile::OnMarginClick(wxStyledTextEvent &event)
misc
void MutEditFile::OnCharAdded(wxStyledTextEvent &event)
References char, DEBUGLOG.
void MutEditFile::OnStyleNeeded(wxStyledTextEvent &event)
References lexer, mutaborGUI::MutSTCLexer::OnStyleNeeded.
void MutEditFile::OnUpdateStcUI(wxStyledTextEvent &event)
References mutaborGUI::StatusBar::SetPosition.
void MutEditFile::OnProperties(wxCommandEvent &WXUNUSED(event))
wxString MutEditFile::DeterminePrefs(const wxString &filename)
language/lexer
References mutaborGUI::LanguageInfo::filepattern, mutaborGUI::g_LanguagePrefs, mutaborGUI::g_LanguagePrefsSize, mutaborGUI::LanguageInfo::name.
Referenced by DoLoadFile, LoadFile.
bool MutEditFile::InitializePrefs(const wxString &filename)
References mutaborGUI::StyleInfo::background, DEBUGLOG, mutaborGUI::CommonInfo::displayEOLEnable, mutaborGUI::CommonInfo::foldEnable, mutaborGUI::LanguageInfo::folds, mutaborGUI::StyleInfo::fontname, mutaborGUI::StyleInfo::fontsize, mutaborGUI::StyleInfo::fontstyle, mutaborGUI::StyleInfo::foreground, mutaborGUI::g_CommonPrefs, mutaborGUI::g_LanguagePrefs, mutaborGUI::g_LanguagePrefsSize, mutaborGUI::g_StylePrefs, mutaborGUI::CommonInfo::indentEnable, mutaborGUI::CommonInfo::indentGuideEnable, mutaborGUI::StyleInfo::lettercase, mutaborGUI::LanguageInfo::lexer, mutaborGUI::CommonInfo::longLineOnEnable, m_DividerID, m_FoldingID, m_FoldingMargin, m_language, m_LineNrID, MutSTC_FOLD_COMMENT, MutSTC_FOLD_COMMENTPY, MutSTC_FOLD_COMPACT, MutSTC_FOLD_HTML, MutSTC_FOLD_HTMLPREP, MutSTC_FOLD_PREPROC, MutSTC_FOLD_QUOTESPY, MutSTC_STYLE_BOLD, MutSTC_STYLE_HIDDEN, MutSTC_STYLE_ITALIC, MutSTC_STYLE_UNDERL, mutaborGUI::LanguageInfo::name, mutaborGUI::CommonInfo::overTypeInitial, mutaborGUI::CommonInfo::readOnlyInitial, STYLE_TYPES_COUNT, mutaborGUI::LanguageInfo::styles, mutaborGUI::CommonInfo::syntaxEnable, mutaborGUI::LanguageInfo::type, mutaborGUI::CommonInfo::whiteSpaceEnable, mutaborGUI::LanguageInfo::wordchars, mutaborGUI::LanguageInfo::words, mutaborGUI::CommonInfo::wrapModeInitial.
Referenced by DoLoadFile, Init, LoadFile, OnHilightLang.
bool mutaborGUI::MutEditFile::UserSettings(const wxString &filename)
LanguageInfo const* mutaborGUI::MutEditFile::GetLanguageInfo()
References m_language.
bool MutEditFile::LoadFile()
load/save file
References m_filename.
Referenced by mutaborGUI::MutFrame::OpenFile.
bool MutEditFile::LoadFile(const wxString &filename)
References DeterminePrefs, DoLoadFile, InitializePrefs, m_filename.
bool MutEditFile::SaveFile()
References IsModified, m_filename.
Referenced by CmFileSave, Compile.
bool MutEditFile::SaveFile(const wxString &filename)
References DoSaveFile.
bool MutEditFile::IsModified()
Referenced by SaveFile.
wxString mutaborGUI::MutEditFile::GetFilename()
References m_filename.
Referenced by mutaborGUI::MutEditProperties::MutEditProperties.
void mutaborGUI::MutEditFile::SetFilename(const wxString &filename)
References m_filename.
virtual wxString mutaborGUI::MutEditFile::GetValue()
compatibility with wx2.8
Referenced by DoSaveFile.
void MutEditFile::Init()
References DEFAULT_LANGUAGE, mutaborGUI::CommonInfo::displayEOLEnable, mutaborGUI::g_CommonPrefs, mutaborGUI::CommonInfo::indentGuideEnable, InitializePrefs, mutaborGUI::CommonInfo::longLineOnEnable, m_DividerID, m_filename, m_FoldingID, m_FoldingMargin, m_language, m_LineNrID, m_LineNrMargin, mutaborGUI::CommonInfo::overTypeInitial, mutaborGUI::CommonInfo::readOnlyInitial, mutaborGUI::CommonInfo::whiteSpaceEnable, mutaborGUI::CommonInfo::wrapModeInitial.
Referenced by MutEditFile.
void MutEditFile::SaveSearchData()
References Write.
Referenced by OnFindDialog.
bool MutEditFile::Compile(bool activate)
References _, box, mutaborGUI::CM_DOACTIVATE, mutaborGUI::CM_STOP, mutaborGUI::CompiledFile, mutaborGUI::DebugCheckRoutes, DEBUGLOG, mutaborGUI::CompDlg::EnableButton, mutabor::BoxClass::GetBoxList, GoToErrorLine, mutaborGUI::LogicOn, m_filename, mutaborGUI::SaveEditor, SaveFile, mutaborGUI::BoxData::SetEditor, mutaborGUI::CompDlg::SetFileName, mutaborGUI::ToGUIBase.
Referenced by CmCompAct, CmCompile.
bool MutEditFile::DoLoadFile(const wxString &filename, int WXUNUSED(fileType))
References _, autoConverter, DEBUGLOG, DeterminePrefs, InitializePrefs, m_filename, TRACEC.
Referenced by LoadFile.
bool MutEditFile::DoSaveFile(const wxString &filename, int WXUNUSED(fileType))
References _, autoConverter, DEBUGLOG, GetValue, m_filename.
Referenced by SaveFile.
void MutEditFile::CmFileSave(wxCommandEvent &WXUNUSED(event))
References m_filename, SaveFile.
Referenced by CmFileSaveAs.
void MutEditFile::CmFileSaveAs(wxCommandEvent &event)
References mutaborGUI::CM_SETTITLE, CmFileSave, FileNameDialog, m_filename.
void MutEditFile::CmCompile(wxCommandEvent &WXUNUSED(event))
References Compile, DEBUGLOG, m_filename.
void MutEditFile::CmCompAct(wxCommandEvent &WXUNUSED(event))
References Compile.
void MutEditFile::CmGetLine(wxCommandEvent &WXUNUSED(event))
References STUBC.
void MutEditFile::CmHelpContext(wxCommandEvent &WXUNUSED(event))
References STUBC.
void MutEditFile::GoToErrorLine(int Line)
Referenced by Compile.