mutaborGUI::MidiInputFilterPanel
typedef mutabor::RouteType mutaborGUI::MidiInputFilterPanel::RouteType
mutaborGUI::MidiInputFilterPanel::MidiInputFilterPanel(wxWindow *parent)
void mutaborGUI::MidiInputFilterPanel::SetFromChannel(int current, int min, int max)
TODO: set limits according to changes: min.max = max.value and max.min = min.value.
References MidiInputFilterPanelBase::from_channel.
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
int mutaborGUI::MidiInputFilterPanel::GetFromChannel() const
References MidiInputFilterPanelBase::from_channel.
Referenced by mutaborGUI::MutInputMidiDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiInputFilterPanel::SetToChannel(int current, int min, int max)
References MidiInputFilterPanelBase::to_channel.
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
int mutaborGUI::MidiInputFilterPanel::GetToChannel() const
References MidiInputFilterPanelBase::to_channel.
Referenced by mutaborGUI::MutInputMidiDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiInputFilterPanel::SetFromKey(int current, int min, int max)
References MidiInputFilterPanelBase::from_key.
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
int mutaborGUI::MidiInputFilterPanel::GetFromKey() const
References MidiInputFilterPanelBase::from_key.
Referenced by mutaborGUI::MutInputMidiDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiInputFilterPanel::SetToKey(int current, int min, int max)
References MidiInputFilterPanelBase::to_key.
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
int mutaborGUI::MidiInputFilterPanel::GetToKey() const
References MidiInputFilterPanelBase::to_key.
Referenced by mutaborGUI::MutInputMidiDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiInputFilterPanel::SetRouteType(RouteType routetype)
References MidiInputFilterPanelBase::all_panel, MidiInputFilterPanelBase::channel_panel, MidiInputFilterPanelBase::else_panel, MidiInputFilterPanelBase::key_panel, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, MidiInputFilterPanelBase::type, UNREACHABLEC.
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
RouteType mutaborGUI::MidiInputFilterPanel::GetRouteType() const
References MidiInputFilterPanelBase::all_panel, MidiInputFilterPanelBase::channel_panel, MidiInputFilterPanelBase::else_panel, MidiInputFilterPanelBase::key_panel, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, MidiInputFilterPanelBase::type, UNREACHABLEC.
Referenced by mutaborGUI::MutInputMidiDeviceShape::ReadFilterPanel.