ton.c
adjazent
Zugriff auf Adjazenzmatrix.
a Zeile der Matrix b Spalte der Matrix
Referenced by berechne_toene_absolut, test_zyklen.
struct ton* list_of_toene
Wurzel der Tonliste.
struct ton* ton_ohne_namen
Frequenz=0.
int anzahl_toene
So viele Toene wurden gelesen.
Referenced by berechne_toene_absolut, test_zyklen, ton_nummer.
struct ton** toene
Feld von Toenen zum schnelleren Zugriff als ueber Listen.
Referenced by expandiere_tonsystem, get_new_tonsystem, get_new_tonsystem_negative.
char* visited
Traversierungsmerker.
Referenced by berechne_toene_absolut, test_zyklen.
char* matrix
Adjazenzmatrix (auf sie darf nur ueber das folgende Makro zugegriffen werden !
Referenced by berechne_toene_absolut.
void init_nullton(void)
References ton::name, ton::next, ton_absolut, ton::ton_absolut, ton::ton_typ, ton::u, xmalloc.
Referenced by allgemeine_initialisierungen.
int ton_list_laenge(struct ton *list)
Zählen der Elemente einer einfach verketteten Tonliste.
list Liste der Töne Anzahl der Elemente von list
References ton::next, ton_list_laenge.
Referenced by berechne_toene_absolut, mutabor::BoxClass::Compile, expandiere_tonsystem, mutabor_programm_einlesen, ton_list_laenge.
struct ton* get_ton(char *name, struct ton *liste)
Sucht einen ton aus einer Tonliste.
name Name des gesuchten Tones liste Liste der Töne, in der der Ton gesucht wird ton_ohne_namen falls name == NULL NULL falls Ton nicht in liste Ton sonst.
References get_ton, ton::name, ton::next.
Referenced by check_konsistenz, check_tonsystem_konsistenz, check_umstimmungs_konsistenz, expandiere_tonsystem, get_komplex_frequenz, get_ton.
void drucke_ton(struct ton *lauf)
Gibt einen Ton auf der Standardausgabe aus.
lauf Ton
References komplex_intervall::faktor, ton::name, komplex_intervall::name, komplex_intervall::next, ton_absolut, ton::ton_absolut, ton_komplex, ton::ton_komplex, ton::ton_typ, ton::u.
Referenced by mutabor_programm_einlesen.
void get_new_ton_absolut(char *name, double wert)
Fügt einen absoluten Ton ans Ende von list_of_toene an.
Taucht der Tonname schon einmal auf, wird ein fataler Fehler ausgegeben. name Bezeichnung des Tones, das angefügt werden soll wert Wert des Tones, der angfügt werden soll Es wird immer die gesamte Liste durchsucht. Effektivität?
References fatal_error, name, ton::next, ton_absolut, ton::u, xmalloc.
Referenced by mutabor_programm_einlesen, switch, yyparse.
void get_new_ton_komplex_positive(char *name, char *bezugston)
Fügt einen komplexen Ton ans Ende von list_of_toene an.
Dabei wird mittels get_last_komplex_intervall() die letzte eingelesene Intevallliste verwendet. Taucht der Tonname schon einmal auf, wird ein fataler Fehler ausgegeben. name Bezeichnung des Tones, das angefügt werden soll bezugston Basiston, auf den sich die Intervallliste bezieht. Es wird immer die gesamte Liste durchsucht. Effektivität?
References ton::bezugston, fatal_error, get_last_komplex_intervall, name, ton::next, ton_komplex, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_new_ton_komplex_negative(char *name, char *bezugston)
Fügt einen komplexen Ton ans Ende von list_of_toene an.
Dabei wird mittels get_last_komplex_intervall() die letzte eingelesene Intevallliste verwendet. Diese wird jedoch zunächst einmal invertiert. Taucht der Tonname schon einmal auf, wird ein fataler Fehler ausgegeben. name Bezeichnung des Tones, das angefügt werden soll bezugston Basiston, auf den sich die Intervallliste bezieht. Es wird immer die gesamte Liste durchsucht. Effektivität?
References ton::bezugston, komplex_intervall::faktor, fatal_error, get_last_komplex_intervall, name, ton::next, komplex_intervall::next, ton_komplex, ton::u, xmalloc.
Referenced by switch, yyparse.
static void belege_toene(struct ton **toene, struct ton *liste)
Erzeugt zu einer einfach verketteten Liste von Tönen ein Array mit Verweisen auf die Einträge.
toene Array für Töne liste Liste der Töne Das Array muss vor dem Funktionsaufruf genügend Platz für alle Töne der Liste bieten. In der Funktion selbst findet keinerlei Längenprüfung statt.
References mutabor_debug_level, ton::next.
Referenced by berechne_toene_absolut.
static int ton_nummer(char *name)
Sucht einen Ton in der globalen Tonliste.
name Name des zu suchenden Tones Wird der Ton nicht gefunden, wird ein fataler Fehler ausgelöst.
References anzahl_toene, fatal_error.
Referenced by berechne_toene_absolut, berechne_ton_endgueltig.
static void test_zyklen(int startknoten)
Durchsucht die Adjazenzmatrix nach Kreisen.
Wird ein Kreis gefunden, wird ein fataler Fehler ausgelöst startknoten Nummer des ersten Knoten, der getestet werden soll.
References adjazent, anzahl_toene, fatal_error, name, visited.
Referenced by berechne_toene_absolut.
static void berechne_ton_endgueltig(int k)
Rechnet komplexe Töne in absolute um.
Wird ein ungültiger Tontyp gefunden, wird ein fataler Fehler ausgelöst. k Nummer des zu bearbeitenden Tones
References fatal_error, get_wert_komplex_intervall, mutabor_debug_level, name, ton_absolut, ton::ton_absolut, ton_komplex, ton_nummer, ton::ton_typ, ton::u.
Referenced by berechne_toene_absolut.
void berechne_toene_absolut(struct ton *list_of_toene)
Berechnet die absoluten Tonwerte für eine einfach verkettete Tonliste.
Dabei werden die globalen Variablen anzahl_toene, toene, visited und die Adjazenzmatrix benutzt. Falls mit DEBUG_ANZEIGE compiliert, wird die Matrix nach der Aufstellung auf der Standardausgabe ausgegeben. list_of_toene
References adjazent, anzahl_toene, belege_toene, berechne_ton_endgueltig, fatal_error, matrix, mutabor_debug_level, name, test_zyklen, ton_absolut, ton_komplex, ton_list_laenge, ton_nummer, ton::u, visited, xalloca, xde_alloca.
Referenced by mutabor_programm_einlesen.
double get_komplex_frequenz(struct ton *dieser)
Berechnet deie Frequenz eines komplexen Tones.
dieser Ton, für den die Frequenz berechnet werden soll.
References get_komplex_faktor, get_ton, ton::ton_komplex, ton::u.
Referenced by expand_tonliste.
static int enthaelt_nur_konstante_toene(struct ton *lauf)
Testet, ob eine Liste von Tönen nue feste, konstante Töne enthält.
lauf Liste der Töne. 1 Die Liste enthält nur konstante Töne. 0 Es wurde ein relativer komplexer Ton gefunden.
References name, ton::next, ton_komplex, ton::u.