ptrlist.c
void* MUTABOR_CLASS_FUNCTION(object, constructor)
References CHK_CLASS, MUT_CLASS, MUTABOR_CLASS_FUNCTION.
static void delete_node(register struct mutabor_avl_node_ptr *node)
References mutabor_avl_node_ptr::left, mutabor_avl_node_ptr::right.
Referenced by MUTABOR_CLASS_FUNCTION.
void* MUTABOR_CLASS_FUNCTION(object, destructor)
Destructor for class object.
Does nothing than error checking.
References CHK_CLASS, delete_node, MUT_CLASS, MUTABOR_CLASS_FUNCTION, self.
static char* print_node(register struct mutabor_avl_node_ptr *node, register int depth)
References mutabor_avl_node_ptr::balance, mutabor_avl_node_ptr::data, mutabor_avl_node_ptr::left, mutabor_avl_node_ptr::right.
Referenced by insert_ptr, MUTABOR_CLASS_FUNCTION.
char* MUTABOR_CLASS_FUNCTION(ptrlist, tostring)
Formats Class content as string.
Intented exspecially for debugging.
References CHK_CLASS, mutabor_avl_node_ptr::data, MUT_VALUE, MUT_VIRTTABLE, print_node.
void* MUTABOR_CLASS_FUNCTION(ptrlist, find)
Search for an identifier in the list.
_self actual object. pointer to be checked. pointer to the first object or NULL if not found
References CHK_CLASS, mutabor_avl_node_ptr::data, mutabor_avl_node_ptr::left, MUT_CLASS, mutabor_avl_node_ptr::right.
static void do_rotations(struct mutabor_avl_node_ptr **node2)
References mutabor_avl_node_ptr::balance, mutabor_avl_node_ptr::left, mutabor_avl_node_ptr::right.
Referenced by insert_ptr.
static signed char insert_ptr(struct mutabor_avl_node_ptr **_node, const void *ptr)
References mutabor_avl_node_ptr::data, do_rotations, print_node.
Referenced by MUTABOR_CLASS_FUNCTION.
int MUTABOR_CLASS_FUNCTION(ptrlist, insert)
Insert an identifier in the list.
_self actual object. identifier Identifier to be inserted. !=0 insert succeded 0 insert failed
References insert_ptr, MUT_CLASS, self.