mis.cpp
ADDPITCH
Referenced by MisTrack::AddNoteOn.
int bending_range
Referenced by mutabor::OutputMidiFile::Load, mutabor::OutputMidiFile::Save, mutabor::OutputMidiFile::TowxString.
int lMidiCode[8][8]
Referenced by MisTrack::AddMidi, MisTrack::ReadMidi, MisTrack::WriteMis.
DWORD ReadLength(istream &is)
References BYTE, DWORD.
Referenced by MisFile::Load, MisTrack::Load.
void WriteLength(ostream &os, DWORD l)
References BYTE.
Referenced by MisFile::Save, MisTrack::Save, mutabor::Track::Save.
void MisReadDummy(MisTrack *, DWORD)
Instrument* GetInstrument(Instrument *root, int id)
References Instrument::Id, Instrument::Next.
Referenced by MisFile::GetChannel, MisFile::NoteOff, MisFile::NoteOn.