mutDebugFlags.h
DEBUGFLAG(other, N_("Unspecified debug information")) DEBUGFLAG(kernel_exec
N_("Debug Execute.cpp")) DEBUGFLAG(kernel_tabgen
Referenced by mutabor::CommonFileOutputDevice::GetTypeName, mutabor::OutputGis::GetTypeName, mutabor::CommonFileInputDevice::GetTypeName, mutabor::InputGis::GetTypeName, mutabor::OutputMidiPort::GetTypeName, mutabor::InputMidiPort::GetTypeName, mutabor::Device::GetTypeName, mutabor::OutputMidiFile::GetTypeName, mutabor::InputMidiFile::GetTypeName, mutabor::OutputDeviceClass::GetTypeName, mutabor::InputDeviceClass::GetTypeName.
N_("Debug table generator")) DEBUGFLAG(kernel_runtime
N_T("Debug other runtime functions of the kernel")) DEBUGFLAG(kernel_parser
N_("Debug the parser of the Mutabor kernel")) DEBUGFLAG(kernel_box
N_("Debug the GUIDO file devices")) DEBUGFLAG(gui
N_("Other gui related debug information")) DEBUGFLAG(dialog
N_("Debug configuration and postprocessing of dialogs")) DEBUGFLAG(routing
N_("Debug the routing system")) DEBUGFLAG(routinggui
N_("Debug the routing system GUI")) DEBUGFLAG(menu
N_("Debug the menu handling and updating")) DEBUGFLAG(midiio
N_("Debug the MIDI input/output system")) DEBUGFLAG(midifile
N_("Debug the MIDI file devices")) DEBUGFLAG(mutparser
N_("Debug the Mutabor file parser")) DEBUGFLAG(config
N_("Debug the config file parser")) DEBUGFLAG(docview
N_("Debug the Document/View framework")) DEBUGFLAG(eventqueue
N_("Print unhandled events in the queue")) DEBUGFLAG(editor
N_("Debug editor related functionality")) DEBUGFLAG(editlexer
N_("Debug editor language lexer related functionality")) DEBUGFLAG(smartptr
N_("Debug smart pointer related functionality")) DEBUGFLAG(trace
N_("Output some tracepoints")) DEBUGFLAG(timer
N_("Trace thread timer problems")) DEBUGFLAG(thread
N_("Trace thread problems")) DEBUGFLAG(always