midicmnInputDevice
typedef mutabor::CommonMidiInput<mutabor::InputDeviceClass> midicmnInputDevice::base
midicmnInputDevice::midicmnInputDevice(std::string name="")
References mutabor::CommonMidiInput< mutabor::InputDeviceClass >::channel_data, mutabor::InputDeviceClass::current_keys, mutabor::InputDeviceClass::current_keys_type::rehash.
midicmnInputDevice::~midicmnInputDevice()
void midicmnInputDevice::Save(mutabor::tree_storage &)
Save current device settings in a tree storage.
config (tree_storage) storage class, where the data will be saved.
void midicmnInputDevice::Save(mutabor::tree_storage &, const mutabor::RouteClass *)
Save route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route) Route whos data shall be saved.
void midicmnInputDevice::Load(mutabor::tree_storage &)
Load current device settings from a tree storage.
config (tree_storage) storage class, where the data will be loaded from.
void midicmnInputDevice::Load(mutabor::tree_storage &, mutabor::RouteClass *)
Load route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route) Route whos data shall be loaded.
bool midicmnInputDevice::Open()
References mutabor::Device::isOpen.
Referenced by CommonMidiInputTest::testGlobalPanic, CommonMidiInputTest::testPanic.
proceed_bool midicmnInputDevice::shouldProceed(mutabor::Route R, uint32_t midiCode, int data=0)
References mutabor::CommonMidiInput< mutabor::InputDeviceClass >::ProceedYes.
proceed_bool midicmnInputDevice::shouldProceed(mutabor::Route R, const std::vector< unsigned char > *midiCode, int data=0)
References mutabor::CommonMidiInput< mutabor::InputDeviceClass >::ProceedYes.
void midicmnInputDevice::NoteOn(int channel, int inkey, int velocity)
References mutabor::midi::NOTE_ON, mutabor::CommonMidiInput< mutabor::InputDeviceClass >::Proceed.
Referenced by CommonMidiInputTest::testGlobalPanic, CommonMidiInputTest::testPanic.
void midicmnInputDevice::NoteOff(int channel, int inkey, int velocity)
References mutabor::midi::NOTE_OFF, mutabor::CommonMidiInput< mutabor::InputDeviceClass >::Proceed.
Referenced by CommonMidiInputTest::testGlobalPanic, CommonMidiInputTest::testPanic.