kernel
@0
mutabor_changed_flags
mutabor_error_type
argument_typ
intervall_typ
ton_typ
umstimmung_typ
ausloeser_typ
aktions_typ
ton_einstell_typ
interpreter_parameter_indices
aufruf_typ
is_harmonic_form_collection
umst_oder_logik_typ
typedef struct mutabor_key_index_type mutabor_key_index_type
typedef struct mutabor_box_type mutabor_box_type
typedef struct mutabor_box_type mutabor_box_type
typedef void mutabor_callback_update_type(mutabor_box_type *box, unsigned int flags)(mutabor_box_type *box, unsigned int flags)
typedef void mutabor_callback_midi_out_type(mutabor_box_type *box, struct midiliste *outliste)(mutabor_box_type *box, struct midiliste *outliste)
typedef void mutabor_callback_error_message_type(mutabor_box_type *box, mutabor_error_type type, const char *message)(mutabor_box_type *box, mutabor_error_type type, const char *message)
typedef void mutabor_callback_update_display(mutabor_box_type *box, int line_number)(mutabor_box_type *box, int line_number)
typedef void mutabor_callback_log_action(mutabor_box_type *box, const char *action)(mutabor_box_type *box, const char *action)
typedef void mutabor_callback_lock_logic(mutabor_logic_parsed *logic)(mutabor_logic_parsed *logic)
typedef long mutabor_interval
typedef mutabor_interval mutabor_tone
typedef struct TSYS tone_system
typedef struct PTRN PATTERNN
typedef int* intptr
typedef std::map<wxwidgets_gettext_mapkey, wxwidgets_gettext_result> wxwidgets_gettext_map
int laufzeit_meldungen_erlaubt
int aktuelles_midi_instrument
size_t minimal_box_used
Referenced by mutaborGUI::CheckBoxesUsed, mutaborGUI::MutFrame::CloseAll, mutaborGUI::MutFrame::CmDoActivate.
int keys_changed_sum
int laufzeit_meldungen_erlaubt
int aktuelles_midi_instrument
size_t minimal_box_used
Referenced by mutaborGUI::CheckBoxesUsed, mutaborGUI::MutFrame::CloseAll, mutaborGUI::MutFrame::CmDoActivate.
int keys_changed_sum
const mutTranslationChar* Error_text[][]
const mutTranslationChar* Warning_text[][]
const mutTranslationChar* Error_text[][]
const mutTranslationChar* Warning_text[][]
struct mutabor_callback_type default_callbacks
mutabor_callback_type* mutabor_callbacks
Referenced by mutabor_get_callbacks, mutabor_set_callbacks.
int protokollfunktionen_aktiv
int protokollfunktion_aktionsausgabe
int zeige_aktuelles_tonsystem
struct mutabor_callback_type* mutabor_callbacks
Referenced by mutabor_get_callbacks, mutabor_set_callbacks.
int laufzeit_meldungen_erlaubt
int anzahl_intervalle
Referenced by berechne_intervalle_absolut, intervall_nummer, test_zyklen.
struct intervall** intervalle
char* visited
char* matrix
long anzahl_eingelesene_zeichen
Referenced by init_yylex, yylex.
wxwidgets_gettext_map cache
Referenced by wxwidgets_gettext.
size_t intrusive_ptr_get_refcount(intrusive_ptr_T *obj)
Referenced by mutaborGUI::GUIRouteBase::Add, mutaborGUI::GUIOutputDeviceBase::Add, mutaborGUI::GUIInputDeviceBase::Add, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::ClearRouteList, mutabor::TRouteClass< I, O, B >::Create, mutabor::RouteFactory::Create, mutaborGUI::GUIRouteBase::Destroy, mutaborGUI::GUIfiedRoute< T >::Destroy, mutaborGUI::disconnect, mutaborGUI::GUIRouteFactory::DoCreateBoxChannelShape, mutaborGUI::MutBoxChannelShape::InitializeInputFilter, intrusive_ptr_add_ref, intrusive_ptr_release, mutabor::TRouteClass< I, O, B >::LoadRoutes, mutaborGUI::GUIRouteBase::Remove, mutabor::BoxClass::Remove, mutaborGUI::GUIOutputDeviceBase::Remove, mutaborGUI::GUIInputDeviceBase::Remove, mutabor::CommonTypedDeviceAPI< T, P, L >::Remove, mutaborGUI::GUIRouteBase::Replace.
void intrusive_ptr_add_ref(intrusive_ptr_T *obj)
References DEBUGLOGTYPE, intrusive_ptr_get_refcount.
void intrusive_ptr_release(intrusive_ptr_T *obj)
References DEBUGLOGTYPE, intrusive_ptr_get_refcount.
void mutabor_set_logic(struct mutabor_box_type *box, struct mutabor_logic_parsed *logic)
References mutabor_box_type::file, loesche_syntax_speicher, mutabor_lock_logic, mutabor_unlock_logic, mutabor_logic_parsed::refcount.
Referenced by mutabor::BoxClass::SetLogic.
void mutabor_reset_keys(struct mutabor_box_type *box)
References mutabor_box_type::current_keys, mutabor_key_index_type::key, mutabor_box_type::key_count, mutabor_delete_key_in_box, mutabor_find_key_in_box, MUTABOR_KEYRANGE_MAX_WIDTH, MUTABOR_NO_NEXT, mutabor_note_type::next, mutabor_box_type::pattern, PTRN::tonigkeit.
Referenced by mutabor_reset_box, mutabor::BoxClass::Panic.
void mutabor_reset_box(struct mutabor_box_type *box)
References TSYS::anker, mutabor_box_type::current_logic, mutabor_box_type::current_parameters, mutabor_box_type::distance, mutabor_box_type::last_tonesystem, mutabor_convert_pitch_to_interval, mutabor_convert_pitch_to_tone, MUTABOR_KEYRANGE_MAX_WIDTH, mutabor_reset_keys, TSYS::ton, mutabor_box_type::tonesystem, mutabor_box_type::tonesystem_memory.
Referenced by mutabor_initialize_box, mutabor::BoxClass::Reset.
void mutabor_initialize_box(mutabor_box_type *box, int id)
References mutabor_box_type::current_keys, mutabor_box_type::current_logic, mutabor_box_type::current_parameters, mutabor_box_type::id, mutabor_key_index_type::key, mutabor_initialize_keyplane, mutabor_reset_box, mutASSERT, mutabor_box_type::parameters, mutabor_box_type::userdata.
Referenced by mutabor::BoxClass::BoxClass, boxTest::setUp.
void mutabor_initialize_keyplane(mutabor_key_index_type *plane)
References mutabor_key_index_type::key, MUT_BOX_MAX_KEY_INDEX, MUTABOR_NO_NEXT, mutabor_note_type::next, mutabor_key_index_type::next, mutabor_note_type::userdata.
Referenced by mutabor_create_key_in_box, mutabor_initialize_box.
int mutabor_get_note_index(int note, tone_system *system)
References TSYS::anker, TSYS::breite.
Referenced by AddKey, DeleteKey, mutabor::BoxClass::get_index, local_harmony_analysis, mutabor_get_note_frequency, update_pattern.
int mutabor_get_note_distance(int note, tone_system *system)
References TSYS::anker, TSYS::breite.
Referenced by mutabor::BoxClass::get_distance, mutabor_get_note_frequency.
long mutabor_get_note_frequency(int note, tone_system *system)
References mutabor_get_note_distance, mutabor_get_note_index, TSYS::periode, TSYS::ton.
Referenced by change_anker, change_breite, mutabor::BoxClass::get_frequency.
void mutabor_initialize_boxes()
void mutabor_check_key_count(mutabor_box_type *box)
Referenced by mutabor_create_key_in_box, mutabor_delete_key_in_box, mutabor_find_key_in_box.
mutabor_note_type* mutabor_find_key_in_box(mutabor_box_type *box, size_t index)
References mutabor_box_type::current_keys, mutabor_key_index_type::key, mutabor_box_type::key_count, MUT_BOX_MAX_KEY_INDEX, MUT_BOX_MAX_KEY_INDEX_LOG, mutabor_check_key_count, MUTABOR_NO_NEXT, mutabor_key_index_type::next.
Referenced by boxTest::checkMask, DeleteKey, mutabor::BoxClass::GetCurrentTones, hoechste_taste, mutabor_create_key_in_box, mutabor_delete_key_in_box, mutabor_find_key_in_box_by_key, mutabor_reset_keys, boxTest::testFindKeyByKey, tiefste_taste, update_pattern, boxTest::verifyAddKey, boxTest::verifyLastKey.
size_t mutabor_find_key_in_box_by_key(mutabor_box_type *box, int key_number, size_t index)
Find a key in the given box.
box Box to be seached in. key Key number to be found. index Starting point. The first index to be checked is its successer. So you have to check index number 0 yourself (which should be fast enough). index of the key structure that has been found our 0 otherwise.
References mutabor_find_key_in_box, MUTABOR_NO_NEXT, mutabor_note_type::next, mutabor_note_type::number.
Referenced by boxTest::testBug1Permutation1, boxTest::testFindKeyByKey.
void mutabor_delete_key_in_box(mutabor_box_type *box, size_t index)
Delete the key with the given index from the box.
box Box where the key shall be deleted. index Index of the key in box->current_keys of the key that shall be deleted.
References DEBUGLOG2, mutabor_box_type::key_count, mutabor_box_type::last_key, mutabor_check_key_count, mutabor_find_key_in_box, MUTABOR_NO_NEXT, mutASSERT, mutabor_note_type::next, UNREACHABLE, mutabor_note_type::userdata, mutabor_box_type::userdata.
Referenced by DeleteKey, mutabor_reset_keys, boxTest::testBug1Permutation1, boxTest::testDeleteKey, boxTest::testFindKeyByKey.
mutabor_note_type* mutabor_create_key_in_box(mutabor_box_type *box)
References mutabor_box_type::current_keys, mutabor_key_index_type::key, mutabor_box_type::key_count, last, mutabor_box_type::last_key, MUT_BOX_MAX_KEY_INDEX, MUT_BOX_MAX_KEY_INDEX_LOG, mutabor_check_key_count, mutabor_find_key_in_box, mutabor_initialize_keyplane, MUTABOR_NO_NEXT, mutASSERT, mutabor_note_type::next, mutabor_key_index_type::next, UNREACHABLE, mutabor_note_type::userdata.
Referenced by AddKey, boxTest::testAddKey, boxTest::testReaddKey.
wxString getContextLocal(const wxString &s)
Referenced by IMPLEMENT_APP.
void mutabor_out_of_memory(const char *file, int line, const char *format,...)
const char * mutabor_error_type_to_string(mutabor_error_type type)
References _, compiler_error, compiler_warning, error, internal_error, runtime_error, runtime_warning, warning.
Referenced by mutabor_default_error_message, mutabor::to_string.
static void mutabor_default_update(mutabor_box_type *box, unsigned int flags)
static void mutabor_default_midi_out(mutabor_box_type *box, struct midiliste *outliste)
static void mutabor_default_error_message(mutabor_box_type *box, mutabor_error_type type, const char *message)
References mutabor_error_type_to_string.
static void mutabor_default_update_display(mutabor_box_type *box, int line_number)
static void mutabor_default_log_action(mutabor_box_type *box, const char *action)
static void mutabor_default_lock(mutabor_logic_parsed *logic)
mutabor_callback_type * mutabor_set_callbacks(mutabor_callback_type *callbacks)
Set the callbacks for the mutabor backend.
callbacks pointer to the object that holds all calbacks that are needed for the backend to run; old callback object.
References mutabor_callbacks.
Referenced by mutabor::initialize_box_data, BoxTest::setUp.
mutabor_callback_type * mutabor_get_callbacks()
Get the currently active callback object.
pointer to the currently active callback object
References mutabor_callbacks.
void update_pattern(mutabor_box_type *box)
Reset boxes.
References TSYS::breite, for, mutabor_find_key_in_box, mutabor_get_note_index, mutabor_box_type::pattern, mutabor_box_type::tonesystem, PTRN::tonigkeit, TRACE.
Referenced by execute_aktion.
void change_breite(mutabor_box_type *box, int neu)
References TSYS::anker, TSYS::breite, DEBUGLOG2, mutabor_get_note_frequency, MUTABOR_KEYRANGE_MAX_WIDTH, TSYS::periode, TSYS::ton, mutabor_box_type::tonesystem.
Referenced by execute_aktion.
void change_anker(mutabor_box_type *box, int neu)
References TSYS::anker, TSYS::breite, mutabor_box_type::distance, mutabor_get_note_frequency, MUTABOR_KEYRANGE_MAX_KEY, MUTABOR_KEYRANGE_MIN_KEY, TSYS::periode, TSYS::ton, mutabor_box_type::tonesystem, mutabor_box_type::tonesystem_memory, TRACE.
Referenced by execute_aktion.
void keyboard_analyse(int taste)
Referenced by KeyboardIn.
void HarmonyAnalysis(mutabor_box_type *box, PATTERNN *pattern)
References mutabor_box_type::current_logic, mutabor_box_type::file, mutabor_box_type::flags, mutabor_logic_parsed::global_harmonies, logik::harmony_list, local_harmony_analysis, mutabor_box_flags::local_harmony_before_global, mutASSERT, TRACE, UNREACHABLE.
Referenced by AddKey, DeleteKey, execute_aktion.
void execute_aktion(mutabor_box_type *box, struct do_aktion *aktion, struct interpreter_parameter_list *parameters)
References _, TSYS::anker, aufruf_harmony_analysis, aufruf_logik, aufruf_midi_out, do_aktion::aufruf_midi_out, aufruf_tonsystem, do_aktion::aufruf_tonsystem, do_aktion::aufruf_typ, aufruf_umst_breite_abs, aufruf_umst_breite_rel, do_aktion::aufruf_umst_breite_rel, aufruf_umst_taste_abs, aufruf_umst_taste_rel, do_aktion::aufruf_umst_taste_rel, aufruf_umst_toene_veraendert, do_aktion::aufruf_umst_toene_veraendert, aufruf_umst_umst_bund, aufruf_umst_umst_case, do_aktion::aufruf_umst_umst_case, aufruf_umst_wiederholung_abs, do_aktion::aufruf_umst_wiederholung_abs, aufruf_umst_wiederholung_rel, TSYS::breite, call_actions, do_aktion::calling, case_element::case_aktion, case_element::case_wert, change_anker, change_breite, mutabor_box_type::current_logic, interpreter_parameter_list::data, einstell_absolut, ton_einstell::einstell_absolut, einstell_gleich, einstell_relativ, ton_einstell::einstell_relativ, einstell_stumm, logik::einstimmung, HarmonyAnalysis, internal_error, case_element::is_default, do_aktion::logic, midiliste::midi_code, mutabor_box_changed, mutabor_convert_interval_to_pitch, mutabor_error_message, mutabor_keys_changed, mutabor_log_action, mutabor_midi_out, mutabor_update, mutASSERT, do_aktion::name, midiliste::next, ton_einstell::next, case_element::next, mutabor_box_type::pattern, TSYS::periode, interpreter_parameter_list::size, TSYS::ton, ton_einstell::ton_einstell_typ, mutabor_box_type::tonesystem, TRACE, ton_einstell::u, do_aktion::u, UNREACHABLE, update_pattern.
Referenced by call_actions.
static void call_actions(mutabor_box_type *box, struct do_aktion *aktion_list, struct interpreter_parameter_list *parameters)
References TSYS::anker, interpreter_argument::constant, mutabor_box_type::current_parameters, interpreter_parameter_list::data, interpreter_argument_list::data, mutabor_box_type::distance, execute_aktion, mutabor_box_type::file, interpreter_argument::index, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, mutASSERT, interpreter_parameter_list::next, mutabor_logic_parsed::parameter_count, mutabor_box_type::parameters, interpreter_parameter_list::size, interpreter_argument_list::size, mutabor_box_type::tonesystem, interpreter_argument_list::types, ycalloc, ymalloc.
Referenced by execute_aktion, local_harmony_analysis, local_keyboard_analysis, local_midi_analysis.
int tiefste_taste(mutabor_box_type *box)
return the smallest key pressed actually
References mutabor_box_type::key_count, mutabor_find_key_in_box, mutabor_note_type::next, mutabor_note_type::number, TRACE, UNREACHABLE.
Referenced by local_harmony_analysis.
int hoechste_taste(mutabor_box_type *box)
return the largest key pressed actually
References mutabor_box_type::key_count, mutabor_find_key_in_box, mutabor_note_type::next, mutabor_note_type::number, TRACE, UNREACHABLE.
Referenced by local_harmony_analysis.
int compare_harmonie(int breite, int startindex, PATTERNN *laufzeit, PATTERNN *vergleich)
References PTRN::tonigkeit, TRACE.
Referenced by local_harmony_analysis.
bool local_harmony_analysis(mutabor_box_type *box, struct harmonie_ereignis *trigger, PATTERNN *harmony)
References _, TSYS::breite, call_actions, compare_harmonie, mutabor_box_type::distance, any_trigger::harmony, any_trigger::harmony_trigger, hoechste_taste, internal_error, mutabor_box_type::last_trigger, mutabor_action_changed, mutabor_error_message, mutabor_get_note_index, MUTABOR_INVALID_KEY, mutabor_is_else_path, mutabor_is_harmonic_form, mutabor_is_no_harmonic_form, MUTABOR_NO_KEY, mutabor_update, harmonie_ereignis::next, tiefste_taste, mutabor_box_type::tonesystem, TRACE, any_trigger::type.
Referenced by HarmonyAnalysis.
void AddKey(mutabor_box_type *box, int taste, size_t id, size_t channel, void *userdata)
References mutabor_note_type::channel, HarmonyAnalysis, mutabor_note_type::id, KEY_CHANGED, mutabor_create_key_in_box, mutabor_get_note_index, mutabor_note_type::number, mutabor_box_type::pattern, mutabor_box_type::tonesystem, PTRN::tonigkeit, mutabor_note_type::userdata.
Referenced by mutabor::BoxClass::AddNote, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.
void DeleteKey(mutabor_box_type *box, int taste, size_t id, size_t channel)
References box, HarmonyAnalysis, mutabor_note_type::id, KEY_CHANGED, mutabor_box_type::last_key, mutabor_delete_key_in_box, mutabor_find_key_in_box, mutabor_get_note_index, mutabor_note_type::next, mutabor_note_type::number, mutabor_box_type::pattern, mutabor_box_type::tonesystem, PTRN::tonigkeit, TRACE.
Referenced by mutabor::BoxClass::DeleteNote, boxTest::testBug1Permutation2.
void KeyboardIn(mutabor_box_type *box, const char *keys)
References KeyboardAnalyse, KeyboardAnalyseSimple, TRACE.
static bool local_midi_analysis(mutabor_box_type *box, struct midi_ereignis *event, BYTE midiByte)
References midi_ereignis::aktion, call_actions, midi_ereignis::first_pos, mutabor_box_type::last_trigger, any_trigger::midi, any_trigger::midi_trigger, mutabor_action_changed, mutabor_update, midi_ereignis::next, midi_ereignis::scan_pos, any_trigger::type.
Referenced by MidiAnalysis.
void MidiAnalysis(mutabor_box_type *box, BYTE midiByte)
References mutabor_box_type::current_logic, mutabor_box_type::file, mutabor_box_type::flags, mutabor_logic_parsed::global_midi_inputs, local_midi_analysis, mutabor_box_flags::local_midi_before_global, logik::midi_input_list, mutASSERT, TRACE, UNREACHABLE.
Referenced by mutabor::BoxClass::MidiAnalysis.
static bool local_keyboard_analysis(mutabor_box_type *box, struct keyboard_ereignis *event, int key, char is_logic, char is_simple)
References call_actions, any_trigger::key, any_trigger::key_trigger, mutabor_box_type::last_trigger, mutabor_action_changed, mutabor_update, keyboard_ereignis::next, any_trigger::type.
Referenced by generic_keyboard_analysis.
static void generic_keyboard_analysis(mutabor_box_type *box, int taste, char isLogic, char isSimple)
References mutabor_box_type::current_logic, mutabor_box_type::file, mutabor_box_type::flags, mutabor_logic_parsed::global_keystrokes, logik::keystroke_list, local_keyboard_analysis, mutabor_box_flags::local_keyboard_before_global, mutASSERT, TRACE, UNREACHABLE.
Referenced by KeyboardAnalyse, KeyboardAnalyseSimple.
void KeyboardAnalyse(mutabor_box_type *box, int taste, char isLogic)
References generic_keyboard_analysis.
Referenced by mutabor::BoxClass::KeyboardAnalysis, KeyboardIn.
void KeyboardAnalyseSimple(mutabor_box_type *box, int taste)
References generic_keyboard_analysis.
Referenced by mutabor::BoxClass::KeyboardAnalysis, KeyboardIn.
void mutabor_update(mutabor_box_type *box, unsigned int flags)
References mutabor_callback_type::update.
Referenced by execute_aktion, local_harmony_analysis, local_keyboard_analysis, local_midi_analysis.
void mutabor_midi_out(mutabor_box_type *box, struct midiliste *outliste)
References mutabor_callback_type::midi_out.
Referenced by execute_aktion.
void mutabor_error_message(mutabor_box_type *box, enum mutabor_error_type type, const char *message,...)
References mutabor_callback_type::error_message.
Referenced by berechne_intervall_endgueltig, berechne_intervalle_absolut, berechne_toene_absolut, berechne_ton_endgueltig, check_aktionen, check_ausloeser, check_komplex_intervall, check_konsistenz, execute_aktion, expand_aktions_liste, expand_pattern, expand_tonliste, expandiere_logik, expandiere_name, expandiere_umstimmung, fprint_argument, generate_argument_list, get_ausloeser_taste, get_instrument_dekl, get_intervall_wert, get_komplex_faktor, get_logik_nummer, get_new_harmonie, get_new_intervall, get_new_intervall_komplex, get_new_logik, get_new_ton_absolut, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_umstimmung_umstimm_case, get_umstimmung_umstimmungs_bund, get_umstimmung_wiederholung_abs_negative, get_wert_komplex_intervall, init_umstimmung, insert_in_globale_liste, insert_in_lokale_liste, intervall_nummer, link_arguments_to_parameters, local_harmony_analysis, resolve_parameters, switch, test_zyklen, test_zyklen_nummer, ton_nummer, u_test_zyklen, xalloca, xcalloc, xmalloc, xrealloc, ymalloc, yyerror, yylex.
void show_line_number(mutabor_box_type *box, int line_number)
References mutabor_callback_type::update_display.
Referenced by yylex.
void mutabor_log_action(mutabor_box_type *box, const char *action)
References mutabor_callback_type::log_action.
Referenced by execute_aktion.
void mutabor_lock_logic(mutabor_logic_parsed *logic)
References mutabor_callback_type::lock_logic.
Referenced by mutabor_set_logic.
void mutabor_unlock_logic(mutabor_logic_parsed *logic)
References mutabor_callback_type::unlock_logic.
Referenced by mutabor_set_logic.
long absLong(const long x)
Referenced by frac::gcd.
void xfree(void *pointer)
Referenced by expandiere_umstimmung, yylex.
void mutabor_codegenerator(const char *filename)
void write_kompletten_code(FILE *zieldatei)
void get_new_number_in_parameterlist(double wert)
void get_new_relativ_anteil (double f, char *linke_grenze, char *rechte_grenze);
void init_umstimmungs_case_aktions_liste(void)
void get_umstimmungs_case_aktions_element(const char *aktion)
void get_aktion_midi_out(void)
void get_aktion_aufruf(const char *name)
int init_speicher_total(void)
int loesche_speicher_total(void)
void * xalloca(mutabor_box_type *box, size_t size)
References _, DEBUGLOG2, error, mutabor_error_message.
Referenced by berechne_intervalle_absolut, berechne_toene_absolut, check_konsistenz.
void xde_alloca(void *pointer)
Referenced by berechne_intervalle_absolut, berechne_toene_absolut, check_konsistenz.
void * xmalloc(mutabor_box_type *box, size_t size)
References _, heap_element::anzahl_belegt, DEBUGLOG2, error, mutabor_box_type::file, mutabor_logic_parsed::heap, HEAP_PORTION_SYNTAX, mutabor_syntax_heap::heap_to_use_syntax, heap_element::inhalt, mutabor_error_message, heap_element::next, OFFSET, mutabor_syntax_heap::syntax_heap.
Referenced by allgemeine_initialisierungen, expand_case_liste, expand_harmony_analysis, expand_pattern, expand_tonliste, expandiere_logik, expandiere_midi, expandiere_tonsystem, expandiere_umstimmung, generate_argument_list, get_ausloeser_default, get_ausloeser_harmonie, get_ausloeser_harmonie_form, get_ausloeser_midi_in, get_ausloeser_taste, get_instrument_dekl, get_new_aktion_aufruf_element, get_new_aktion_harmony_analysis, get_new_aktion_midi_out_element, get_new_anchor_in_argument_list, get_new_anweisung, get_new_distance_in_argument_list, get_new_faktor_anteil, get_new_harmonie, get_new_integer_in_integersequenz, get_new_intervall, get_new_intervall_komplex, get_new_logik, get_new_name_in_argument_list, get_new_name_in_parameterlist, get_new_number_in_argument_list, get_new_taste, get_new_ton_absolut, get_new_ton_in_tonsystem, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_new_umstimm_expression, get_new_umstimm_expression_negative, get_new_umstimm_expression_positive, get_umstimmungs_case_default_element, get_umstimmungs_case_zahl_element, init_umstimmung, insert_in_globale_liste, insert_in_lokale_liste, xcalloc, xrealloc, yylex.
void * xrealloc(mutabor_box_type *box, void *block, size_t newsize)
References _, heap_element::anzahl_belegt, DEBUGLOG2, error, mutabor_box_type::file, mutabor_logic_parsed::heap, HEAP_PORTION_SYNTAX, mutabor_syntax_heap::heap_to_use_syntax, heap_element::inhalt, mutabor_error_message, xmalloc.
Referenced by yylex.
void * xcalloc(mutabor_box_type *box, size_t anzahl, size_t size)
References _, DEBUGLOG2, error, mutabor_error_message, xmalloc.
Referenced by check_aktionen, create_midi_scan_liste, expand_decition_tree, generate_argument_list.
int loesche_syntax_speicher(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::heap, mutabor_syntax_heap::heap_to_use_syntax, heap_element::next, mutabor_syntax_heap::syntax_heap.
Referenced by mutabor::BoxClass::Compile, GMutCompile, init_syntax_speicher, mutabor_set_logic, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.
int init_syntax_speicher(mutabor_box_type *box)
References loesche_syntax_speicher.
void yfree(void *pointer)
void * ymalloc(mutabor_box_type *box, size_t size)
References _, DEBUGLOG2, error, mutabor_error_message, mini_heap::next, mini_heap::pointer, mutabor_box_type::runtime_heap.
Referenced by call_actions, ycalloc, yrealloc.
void * yrealloc(mutabor_box_type *box, void *block, size_t newsize)
References ymalloc.
void * ycalloc(mutabor_box_type *box, size_t anzahl, size_t size)
References ymalloc.
Referenced by call_actions.
int init_laufzeit_speicher(mutabor_box_type *box)
References loesche_laufzeit_speicher.
int loesche_laufzeit_speicher(mutabor_box_type *box)
References mini_heap::next, mini_heap::pointer, mutabor_box_type::runtime_heap.
Referenced by init_laufzeit_speicher.
void message_tasten_liste(void)
double mutabor_convert_interval_to_pitch(mutabor_interval interval)
Convert an interval to half tone based pitch according to MIDI pitch numbers.
The microtonal part is retained in the double return value. interval Interval in the internal representation of Mutabor. a double value that represents the interval. a half tone is represented as 1.00, and an octave as 12.00.
Referenced by execute_aktion, mutabor::BoxClass::GetToneSystem, mutabor_convert_tone_to_pitch.
mutabor_interval mutabor_convert_pitch_to_interval(double interval)
Convert an interval from half tone based pitch according to MIDI pitch numbers.
The microtonal part can be given in the double value. interval a double value that represents the interval. a semitone is represented as 1.00, and an octave as 12.00 interval in the internal representation of Mutabor.
Referenced by expand_tonliste, expandiere_tonsystem, expandiere_umstimmung, mutabor_convert_pitch_to_tone, mutabor_reset_box.
double mutabor_convert_tone_to_pitch(mutabor_tone tone)
Convert a tone to half tone based pitch according to MIDI pitch numbers.
The microtonal part is retained in the double return value. interval Interval in the internal representation of Mutabor. a double value that represents the tone a' is represented as 69.00
References mutabor_convert_interval_to_pitch.
Referenced by mutabor::BoxClass::GetCurrentTones, mutabor::BoxClass::GetToneSystem.
mutabor_tone mutabor_convert_pitch_to_tone(double tone)
Convert a tone from half tone based pitch according to MIDI pitch numbers.
The microtonal part can be given in the double value. tone a double value that represents the tone. a' is represented as 69.00 tone in the internal representation of Mutabor.
References mutabor_convert_pitch_to_interval.
Referenced by expand_tonliste, expandiere_tonsystem, mutabor_reset_box.
void HARMONIE_analyse(int instr, PATTERNN *pattern)
void MIDI_analyse(int code)
void KEYB_analyse(int key)
void MAUS_analyse(int mx, int my)
void Add_Key(int instr, int key, int velo)
void Delete_Key(int instr, int key)
tone_system* lz_get_tonsystem(int instr)
PATTERNN* get_pattern(int instr)
static double get_intervall_wert(mutabor_box_type *box, const char *name)
References _, compiler_error, get_wert_komplex_intervall, intervall_absolut, intervall::intervall_absolut, intervall_komplex, intervall::intervall_komplex, intervall::intervall_typ, mutabor_error_message, intervall::name, intervall::next, intervall::u.
Referenced by get_wert_komplex_intervall.
double get_wert_komplex_intervall(mutabor_box_type *box, struct komplex_intervall *intervall)
References _, compiler_error, get_intervall_wert, mutabor_error_message, intervall::name, intervall::next.
Referenced by berechne_intervall_endgueltig, berechne_ton_endgueltig, expandiere_tonsystem, expandiere_umstimmung, get_intervall_wert.
int intervall_list_laenge(struct intervall *list)
References intervall::next.
Referenced by berechne_intervalle_absolut, mutabor::BoxClass::Compile.
static void belege_intervalle(struct intervall **intervalle, struct intervall *liste)
References intervall::next.
Referenced by berechne_intervalle_absolut.
static int intervall_nummer(mutabor_box_type *box, const char *name)
References _, anzahl_intervalle, compiler_error, mutabor_error_message.
Referenced by berechne_intervall_endgueltig, berechne_intervalle_absolut.
static void test_zyklen(mutabor_box_type *box, int startknoten)
References _, adjazent, anzahl_intervalle, compiler_error, mutabor_error_message, intervall::name.
Referenced by berechne_intervalle_absolut.
static void berechne_intervall_endgueltig(mutabor_box_type *box, int k)
References _, get_wert_komplex_intervall, internal_error, intervall_absolut, intervall::intervall_absolut, intervall_komplex, intervall::intervall_komplex, intervall_nummer, intervall::intervall_typ, mutabor_error_message, komplex_intervall::name, komplex_intervall::next, intervall::u.
Referenced by berechne_intervalle_absolut.
void berechne_intervalle_absolut(mutabor_box_type *box, struct intervall *list_of_intervalle)
References _, adjazent, anzahl_intervalle, belege_intervalle, berechne_intervall_endgueltig, internal_error, intervall_absolut, intervall_komplex, intervall::intervall_komplex, intervall_list_laenge, intervall_nummer, mutabor_error_message, komplex_intervall::name, komplex_intervall::next, test_zyklen, xalloca, xde_alloca.
Referenced by mutabor_programm_einlesen.
void check_komplex_intervall(mutabor_box_type *box, struct komplex_intervall *liste, const char *konstrukt_name)
References _, compiler_error, get_intervall, internal_error, intervall_absolut, intervall::intervall_typ, mutabor_error_message, intervall::name, komplex_intervall::next.
Referenced by check_konsistenz.
static void berechne_toene_absolut(mutabor_box_type *box, struct ton *ton_liste)
References _, mutabor_logic_parsed::anzahl_toene, belege_toene, berechne_ton_endgueltig, mutabor_box_type::file, for, internal_error, isDebugFlag, mutabor_logic_parsed::matrix, mutabor_adjacent, mutabor_error_message, ton::name, test_zyklen, mutabor_logic_parsed::toene, ton_absolut, ton_komplex, ton::ton_komplex, ton_list_laenge, ton_nummer, ton::ton_typ, TRACE, ton::u, mutabor_logic_parsed::visited, xalloca, xde_alloca.
Referenced by mutabor_programm_einlesen.
static void check_konsistenz(mutabor_box_type *box)
References _, aktion_aufruf, aktions_liste::aktion_aufruf, allgemeine_initialisierungen, logik::anweisungsliste, mutabor_logic_parsed::anzahl_umstimmungen_und_logiken, argument_list_laenge, anweisung::ausloeser, logik::ausloeser, ausloeser_default, ausloeser::ausloeser_typ, belege_zyklenfeld, case_label_enthalten_in_case_liste, check_aktionen, check_ausloeser, check_komplex_intervall, compiler_error, compiler_warning, logik::einstimmungs_name, mutabor_box_type::file, for, get_logik, get_ton, get_umstimmung, internal_error, mutabor_logic_parsed::list_of_logiken, mutabor_logic_parsed::list_of_toene, mutabor_logic_parsed::list_of_tonsysteme, mutabor_logic_parsed::list_of_umstimmungen, umst_oder_logik::logik, logik_list_laenge, mutabor_error_message, MUTABOR_KEYRANGE_MAX_KEY, MUTABOR_KEYRANGE_MIN_KEY, mutabor_u_adjacent, ton::name, tonsystem::name, umstimmung::name, logik::name, ton::next, tonsystem::next, case_liste::next, umstimmung::next, aktions_liste::next, anweisung::next, logik::next, parameter_list_laenge, umstimmung::parameter_liste, parser_get_tonsystem, tonsystem::periode, tonsystem::taste, test_zyklen_nummer, tonsystem::toene, ton_absolut, ton::ton_komplex, TRACE, typ_logik, typ_umstimmung, umst_oder_logik::u, ton::u, umstimmung::u, aktions_liste::u, mutabor_logic_parsed::u_matrix, u_test_zyklen, mutabor_logic_parsed::u_visited, umst_oder_logik::umst_oder_logik_typ, umst_oder_logik::umstimmung, umstimmung_breite_abs, umstimmung_breite_rel, umstimmung_taste_abs, umstimmung_taste_rel, umstimmung_toene_veraendert, umstimmung::umstimmung_toene_veraendert, umstimmung::umstimmung_typ, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, umstimmung::umstimmung_wiederholung_rel, umstimmungs_list_laenge, xalloca, xde_alloca, mutabor_logic_parsed::zyklen_feld.
Referenced by mutabor_programm_einlesen.
void allgemeine_initialisierungen(mutabor_box_type *box)
References mutabor_box_type::file, ton::name, ton::next, ton_absolut, ton::ton_absolut, mutabor_logic_parsed::ton_ohne_namen, ton::ton_typ, TRACE, ton::u, xmalloc.
Referenced by check_konsistenz.
int ton_list_laenge(const struct ton *list)
References ton::next, TRACE.
Referenced by berechne_toene_absolut, mutabor::BoxClass::Compile, expandiere_tonsystem, mutabor_programm_einlesen.
int tonsystem_list_laenge(const struct tonsystem *list)
References tonsystem::next, TRACE.
Referenced by mutabor::BoxClass::Compile.
int umstimmungs_list_laenge(const struct umstimmung *list)
References umstimmung::next, TRACE.
Referenced by check_konsistenz, mutabor::BoxClass::Compile.
int logik_list_laenge(const struct logik *list)
References logik::next, TRACE.
Referenced by check_konsistenz, mutabor::BoxClass::Compile, expand_decition_tree.
int midi_list_laenge(const struct midiliste *list)
References midiliste::next, TRACE.
Referenced by create_midi_scan_liste, mutabor::BoxClass::MidiOut.
int get_logik_nummer(mutabor_box_type *box, const char *name, struct logik *liste)
References _, internal_error, mutabor_error_message, logik::name, logik::next, TRACE.
Referenced by expandiere_logik.
int parameter_list_laenge(struct parameter_list *list)
References ton::next, TRACE.
Referenced by check_aktionen, check_konsistenz.
int argument_list_laenge(struct argument_list *list)
References ton::next, TRACE.
Referenced by check_aktionen, check_konsistenz.
struct ton * get_ton(mutabor_box_type *box, const char *name, struct ton *liste)
References mutabor_box_type::file, ton::name, ton::next, mutabor_logic_parsed::ton_ohne_namen, TRACE.
Referenced by check_konsistenz, expandiere_tonsystem, get_komplex_frequenz.
struct intervall * get_intervall(const char *name, struct intervall *liste)
References intervall::name, intervall::next, TRACE.
Referenced by check_komplex_intervall, get_komplex_faktor.
struct tonsystem * parser_get_tonsystem(const char *name, struct tonsystem *liste)
References tonsystem::name, tonsystem::next, TRACE.
Referenced by check_aktionen, check_konsistenz, expandiere_logik, expandiere_name.
struct umstimmung * get_umstimmung(const char *name, struct umstimmung *liste)
References umstimmung::name, umstimmung::next, TRACE.
Referenced by check_aktionen, check_konsistenz, expandiere_logik, expandiere_name.
struct harmonie * get_harmonie(const char *name, struct harmonie *liste)
References harmonie::name, harmonie::next, TRACE.
Referenced by check_ausloeser, expand_pattern.
struct logik * get_logik(const char *name, struct logik *liste)
References logik::name, logik::next, TRACE.
Referenced by check_aktionen, check_konsistenz, expandiere_name.
void init_integersequenz(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::list_of_integers, TRACE.
Referenced by switch, yyparse.
void get_new_integer_in_integersequenz(mutabor_box_type *box, int wert)
References mutabor_box_type::file, mutabor_logic_parsed::list_of_integers, midiliste::midi_code, midiliste::next, TRACE, xmalloc.
Referenced by switch, yyparse.
static struct midiliste* get_last_integersequenz(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::list_of_integers, TRACE.
Referenced by get_ausloeser_midi_in, get_new_aktion_midi_out_element, get_umstimmung_midi_out.
void init_parameter_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::list_of_names, TRACE.
Referenced by yyparse.
struct parameter_list * get_new_name_in_parameterlist(mutabor_box_type *box, const char *name)
References parameter_list::name, parameter_list::next, TRACE, xmalloc.
Referenced by switch, yyparse.
void enumerate_parameters(mutabor_box_type *box, struct parameter_list *parameters)
References mutabor_box_type::file, parameter_list::index, parameter_list::next, mutabor_logic_parsed::parameter_count.
Referenced by switch.
static struct parameter_list* get_parameter_by_name(mutabor_box_type *box, const char *search_name, struct parameter_list *node)
References parameter_list::name, parameter_list::next, TRACE.
Referenced by get_umstimmung_umstimm_case, get_umstimmung_umstimmungs_bund, link_arguments_to_parameters.
void print_argumentliste(struct argument_list *this_)
References _, argument::argument_type, argument::integer, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_parameter, parameter_list::name, parameter_list::next, argument::parameter, TRACE, argument::u.
void init_argument_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::list_of_argumente, TRACE.
Referenced by yyparse.
struct argument_list * get_new_number_in_argument_list(mutabor_box_type *box, double number)
References argument::argument_type, argument::integer, mutabor_argument_integer, argument_list::next, TRACE, argument::u, xmalloc.
Referenced by switch, yyparse.
struct argument_list * get_new_name_in_argument_list(mutabor_box_type *box, const char *parameter_name)
References argument::argument_type, mutabor_argument_parameter, parameter_list::name, argument_list::next, argument::parameter, TRACE, argument::u, xmalloc.
Referenced by switch, yyparse.
struct argument_list * get_new_distance_in_argument_list(mutabor_box_type *box)
References argument::argument_type, mutabor_argument_distance, argument_list::next, TRACE, xmalloc.
Referenced by switch.
struct argument_list * get_new_anchor_in_argument_list(mutabor_box_type *box)
References argument::argument_type, mutabor_argument_anchor, argument_list::next, TRACE, xmalloc.
Referenced by switch.
void init_aktions_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::list_of_aktionen, TRACE.
Referenced by switch, yyparse.
void get_new_aktion_aufruf_element(mutabor_box_type *box, const char *name, struct argument_list *arguments)
References aktion_aufruf, mutabor_box_type::file, mutabor_logic_parsed::list_of_aktionen, aktions_liste::name, aktions_liste::next, TRACE, aktions_liste::u, xmalloc.
Referenced by switch, yyparse.
void get_new_aktion_midi_out_element(mutabor_box_type *box)
References aktion_midi_out, mutabor_box_type::file, get_last_integersequenz, mutabor_logic_parsed::list_of_aktionen, aktions_liste::next, TRACE, aktions_liste::u, xmalloc.
Referenced by switch, yyparse.
void get_new_aktion_harmony_analysis(mutabor_box_type *box)
References aktion_harmony_analysis, mutabor_box_type::file, mutabor_logic_parsed::list_of_aktionen, aktions_liste::next, TRACE, xmalloc.
Referenced by switch.
static struct aktions_liste* get_last_aktions_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::list_of_aktionen, TRACE.
Referenced by get_new_anweisung, get_umstimmung_umstimmungs_bund, get_umstimmungs_case_default_element, get_umstimmungs_case_zahl_element.
void init_komplex_ton_list(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::the_komplex_liste, TRACE.
Referenced by switch, yyparse.
void get_new_faktor_anteil(mutabor_box_type *box, double f, const char *name)
References komplex_intervall::faktor, mutabor_box_type::file, komplex_intervall::name, komplex_intervall::next, mutabor_logic_parsed::the_komplex_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
struct komplex_intervall* get_last_komplex_intervall(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::the_komplex_liste, TRACE.
Referenced by get_new_intervall_komplex, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_new_umstimm_expression_negative, get_new_umstimm_expression_positive, get_umstimmung_wiederholung_abs, get_umstimmung_wiederholung_abs_negative, get_umstimmung_wiederholung_rel_negative, get_umstimmung_wiederholung_rel_positive.
int yyparse(mutabor_box_type *box)
bool mutabor_programm_einlesen(mutabor_box_type *box, const char *logic)
References anweisung::aktion, logik::anweisungsliste, anweisung::ausloeser, logik::ausloeser, berechne_intervalle_absolut, berechne_toene_absolut, case_liste::case_aktion, case_liste::case_label, check_konsistenz, mutabor_scanner_data::data, DEBUGLOG2, logik::einstimmungs_name, mutabor_box_type::file, get_instrument_dekl, get_new_intervall, get_new_ton_absolut, intervall_absolut, intervall::intervall_absolut, intervall::intervall_typ, case_liste::is_default, isDebugFlag, mutabor_logic_parsed::list_of_config_instrumente, mutabor_logic_parsed::list_of_constants, mutabor_logic_parsed::list_of_harmonien, mutabor_logic_parsed::list_of_instrumente, mutabor_logic_parsed::list_of_intervalle, mutabor_logic_parsed::list_of_logiken, mutabor_logic_parsed::list_of_toene, mutabor_logic_parsed::list_of_tonsysteme, mutabor_logic_parsed::list_of_umstimmungen, instrument::midi_bis, instrument::midi_in, instrument::midi_von, parameter_list::name, intervall::name, ton::name, tonsystem::name, umstimmung::name, logik::name, parameter_list::next, intervall::next, ton::next, tonsystem::next, case_liste::next, umstimmung::next, harmonie::next, anweisung::next, logik::next, instrument::next, umstimmung::parameter_liste, tonsystem::periode, mutabor_scanner_data::pos, mutabor_box_type::scanner, STUB, tonsystem::taste, tonsystem::toene, ton_list_laenge, TRACE, intervall::u, ton::u, umstimmung::u, umstimmung_breite_abs, umstimmung_breite_rel, umstimmung::umstimmung_breite_rel, umstimmung_midi_out, umstimmung_taste_abs, umstimmung_taste_rel, umstimmung::umstimmung_taste_rel, umstimmung_toene_veraendert, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, yyparse.
Referenced by mutabor::BoxClass::Compile, GMutCompile, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.
void print_integersequenz(struct midiliste *this_)
References midiliste::midi_code, midiliste::next.
void get_new_intervall(mutabor_box_type *box, const char *name, double wert)
References _, compiler_error, mutabor_box_type::file, intervall_absolut, mutabor_logic_parsed::list_of_intervalle, mutabor_error_message, intervall::name, intervall::next, TRACE, intervall::u, xmalloc.
Referenced by mutabor_programm_einlesen, switch, yyparse.
void get_new_intervall_komplex(mutabor_box_type *box, const char *name)
References _, compiler_error, mutabor_box_type::file, get_last_komplex_intervall, intervall_komplex, mutabor_logic_parsed::list_of_intervalle, mutabor_error_message, intervall::name, intervall::next, TRACE, intervall::u, xmalloc.
Referenced by switch, yyparse.
void get_new_ton_absolut(mutabor_box_type *box, const char *name, double wert)
References _, compiler_error, mutabor_box_type::file, mutabor_logic_parsed::list_of_toene, mutabor_error_message, ton::name, ton::next, ton_absolut, TRACE, ton::u, xmalloc.
Referenced by mutabor_programm_einlesen, switch, yyparse.
void get_new_ton_komplex_positive(mutabor_box_type *box, const char *name, const char *bezugston)
References _, ton::bezugston, compiler_error, mutabor_box_type::file, get_last_komplex_intervall, mutabor_logic_parsed::list_of_toene, mutabor_error_message, ton::name, ton::next, ton_komplex, TRACE, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_new_ton_komplex_negative(mutabor_box_type *box, const char *name, const char *bezugston)
References _, ton::bezugston, compiler_error, komplex_intervall::faktor, mutabor_box_type::file, get_last_komplex_intervall, internal_error, mutabor_logic_parsed::list_of_toene, mutabor_error_message, ton::name, komplex_intervall::next, ton::next, ton_komplex, TRACE, ton::u, xmalloc.
Referenced by switch, yyparse.
void init_ton_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::ton_liste, TRACE.
Referenced by switch, yyparse.
void get_new_ton_in_tonsystem(mutabor_box_type *box, const char *name)
References mutabor_box_type::file, ton::name, ton::next, mutabor_logic_parsed::ton_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_new_tonsystem(mutabor_box_type *box, const char *name, int taste)
References _, compiler_error, mutabor_box_type::file, get_last_komplex_intervall, mutabor_logic_parsed::list_of_tonsysteme, mutabor_error_message, tonsystem::name, tonsystem::next, tonsystem::periode, tonsystem::taste, tonsystem::toene, mutabor_logic_parsed::ton_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_new_tonsystem_negative(mutabor_box_type *box, const char *name, int taste)
References _, compiler_error, komplex_intervall::faktor, mutabor_box_type::file, get_last_komplex_intervall, internal_error, mutabor_logic_parsed::list_of_tonsysteme, mutabor_error_message, tonsystem::name, komplex_intervall::next, tonsystem::next, tonsystem::taste, mutabor_logic_parsed::ton_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
void init_umstimmung(mutabor_box_type *box, const char *name)
References _, compiler_error, mutabor_box_type::file, mutabor_logic_parsed::list_of_umstimmungen, mutabor_error_message, umstimmung::name, umstimmung::next, umstimmung::parameter_liste, mutabor_logic_parsed::tmp_umstimmung, TRACE, xmalloc.
Referenced by switch, yyparse.
static void link_arguments_to_parameters(mutabor_box_type *box, struct argument_list *arguments, struct parameter_list *parameters, struct umstimmung *retuning)
References _, compiler_error, get_parameter_by_name, internal_error, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_parameter, mutabor_error_message, umstimmung::name, umstimmung::next.
Referenced by get_new_umstimmung, get_umstimmung_umstimm_case, get_umstimmung_umstimmungs_bund.
void get_new_umstimmung(mutabor_box_type *box)
References umstimmung::argument_liste, mutabor_box_type::file, link_arguments_to_parameters, mutabor_logic_parsed::list_of_umstimmungen, umstimmung::next, umstimmung::parameter_liste, mutabor_logic_parsed::tmp_umstimmung, TRACE.
Referenced by switch, yyparse.
void eintrage_parameterliste_in_umstimmung(mutabor_box_type *box, struct umstimmung *ret, parameter_list *list)
References umstimmung::parameter_liste, TRACE.
Referenced by switch, yyparse.
void get_umstimmung_taste_abs(mutabor_box_type *box, argument_list *argument)
References umstimmung::argument_liste, mutabor_box_type::file, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_taste_abs.
Referenced by switch, yyparse.
void get_umstimmung_taste_rel(mutabor_box_type *box, argument_list *argument, char vorzeichen)
References umstimmung::argument_liste, mutabor_box_type::file, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung::u, umstimmung_taste_rel.
Referenced by switch, yyparse.
void get_umstimmung_breite_abs(mutabor_box_type *box, argument_list *argument)
References umstimmung::argument_liste, mutabor_box_type::file, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_breite_abs.
Referenced by switch, yyparse.
void get_umstimmung_breite_rel(mutabor_box_type *box, argument_list *argument, char vorzeichen)
References umstimmung::argument_liste, mutabor_box_type::file, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung::u, umstimmung_breite_rel.
Referenced by switch, yyparse.
void init_umstimm_expression_list(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_tonliste, TRACE.
Referenced by switch, yyparse.
void get_new_umstimm_expression(mutabor_box_type *box, const char *bezugston)
References ton::bezugston, mutabor_box_type::file, ton::name, ton::next, mutabor_logic_parsed::tmp_tonliste, ton_komplex, TRACE, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_new_umstimm_expression_positive(mutabor_box_type *box, const char *bezugston)
References ton::bezugston, mutabor_box_type::file, get_last_komplex_intervall, ton::name, ton::next, mutabor_logic_parsed::tmp_tonliste, ton_komplex, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_new_umstimm_expression_negative(mutabor_box_type *box, const char *bezugston)
References ton::bezugston, komplex_intervall::faktor, mutabor_box_type::file, get_last_komplex_intervall, ton::name, komplex_intervall::next, ton::next, mutabor_logic_parsed::tmp_tonliste, ton_komplex, TRACE, ton::u, xmalloc.
Referenced by switch, yyparse.
void get_umstimmung_tonhoehe_veraendert(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_tonliste, mutabor_logic_parsed::tmp_umstimmung, umstimmung_toene_veraendert, umstimmung::umstimmung_toene_veraendert.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_abs(mutabor_box_type *box)
References mutabor_box_type::file, get_last_komplex_intervall, mutabor_logic_parsed::tmp_umstimmung, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_abs_negative(mutabor_box_type *box)
References _, komplex_intervall::faktor, mutabor_box_type::file, get_last_komplex_intervall, internal_error, mutabor_error_message, mutabor_logic_parsed::tmp_umstimmung, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_rel_positive(mutabor_box_type *box)
References mutabor_box_type::file, get_last_komplex_intervall, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_wiederholung_rel, umstimmung::umstimmung_wiederholung_rel.
Referenced by switch, yyparse.
void get_umstimmung_wiederholung_rel_negative(mutabor_box_type *box)
References komplex_intervall::faktor, mutabor_box_type::file, get_last_komplex_intervall, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_wiederholung_rel, umstimmung::umstimmung_wiederholung_rel.
Referenced by switch, yyparse.
void get_umstimmung_umstimmungs_bund(mutabor_box_type *box)
References _, aktion_aufruf, aktions_liste::aktion_aufruf, argument_list::argument, argument::argument_type, compiler_error, mutabor_box_type::file, get_last_aktions_liste, get_parameter_by_name, link_arguments_to_parameters, mutabor_argument_parameter, mutabor_error_message, parameter_list::name, umstimmung::name, argument_list::next, aktions_liste::next, argument::parameter, mutabor_logic_parsed::tmp_umstimmung, TRACE, argument::u, aktions_liste::u, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund.
Referenced by switch, yyparse.
void get_umstimmungs_case_zahl_element(mutabor_box_type *box, int konstante)
References case_liste::case_aktion, case_liste::case_label, mutabor_box_type::file, get_last_aktions_liste, case_liste::is_default, case_liste::next, mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_umstimmungs_case_default_element(mutabor_box_type *box)
References case_liste::case_aktion, case_liste::case_label, mutabor_box_type::file, get_last_aktions_liste, case_liste::is_default, MUTABOR_NO_CASE_LABEL, case_liste::next, mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE, xmalloc.
Referenced by switch, yyparse.
void init_umstimmungs_case_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE.
Referenced by switch, yyparse.
void get_umstimmung_umstimm_case(mutabor_box_type *box, argument_list *argument)
References _, aktion_aufruf, aktions_liste::aktion_aufruf, argument_list::argument, compiler_error, mutabor_box_type::file, get_parameter_by_name, link_arguments_to_parameters, mutabor_argument_parameter, mutabor_error_message, parameter_list::name, umstimmung::name, argument_list::next, case_liste::next, aktions_liste::next, argument::parameter, mutabor_logic_parsed::tmp_umstimmung, mutabor_logic_parsed::tmp_umstimmungs_case_liste, TRACE, argument::u, aktions_liste::u, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case.
Referenced by switch.
void get_umstimmung_midi_out(mutabor_box_type *box)
References mutabor_box_type::file, get_last_integersequenz, mutabor_logic_parsed::tmp_umstimmung, TRACE, umstimmung_midi_out, umstimmung::umstimmung_midi_out.
Referenced by switch, yyparse.
void init_tastenliste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_tastenliste, TRACE.
Referenced by switch, yyparse.
void get_new_taste(mutabor_box_type *box, int taste, char stern)
References taste::code, mutabor_box_type::file, taste::next, taste::stern, mutabor_logic_parsed::tmp_tastenliste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_new_harmonie(mutabor_box_type *box, const char *name, int bezugstaste)
References _, harmonie::bezugstaste, compiler_error, mutabor_box_type::file, mutabor_logic_parsed::list_of_harmonien, mutabor_error_message, harmonie::name, harmonie::next, harmonie::tastenliste, mutabor_logic_parsed::tmp_tastenliste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_harmoniebezeichner(mutabor_box_type *box, int vor_taste, const char *name, int nach_taste)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_nach_taste, mutabor_logic_parsed::tmp_name, mutabor_logic_parsed::tmp_vor_taste.
Referenced by switch, yyparse.
void init_ausloeser(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_ausloeser, TRACE.
Referenced by switch, yyparse.
struct ausloeser* get_last_ausloeser(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_ausloeser, TRACE.
Referenced by get_new_anweisung, get_new_logik.
void get_ausloeser_default(mutabor_box_type *box)
References ausloeser_default, mutabor_box_type::file, mutabor_logic_parsed::tmp_ausloeser, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_harmonie(mutabor_box_type *box)
References ausloeser_harmonie, mutabor_box_type::file, mutabor_logic_parsed::tmp_ausloeser, mutabor_logic_parsed::tmp_nach_taste, mutabor_logic_parsed::tmp_name, mutabor_logic_parsed::tmp_vor_taste, TRACE, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_harmonie_form(mutabor_box_type *box)
References ausloeser_harmonie_form, mutabor_box_type::file, mutabor_logic_parsed::tmp_ausloeser, mutabor_logic_parsed::tmp_nach_taste, mutabor_logic_parsed::tmp_name, mutabor_logic_parsed::tmp_vor_taste, TRACE, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_taste(mutabor_box_type *box, const char *name)
References _, ausloeser_taste, compiler_error, mutabor_box_type::file, mutabor_error_message, ausloeser::name, mutabor_logic_parsed::tmp_ausloeser, TRACE, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void get_ausloeser_midi_in(mutabor_box_type *box)
References ausloeser_midi_in, mutabor_box_type::file, get_last_integersequenz, mutabor_logic_parsed::tmp_ausloeser, TRACE, ausloeser::u, xmalloc.
Referenced by switch, yyparse.
void init_anweisungs_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_anweisungsliste, TRACE.
Referenced by switch, yyparse.
struct anweisung* get_last_anweisungs_liste(mutabor_box_type *box)
References mutabor_box_type::file, mutabor_logic_parsed::tmp_anweisungsliste, TRACE.
Referenced by vervollstaendige_logik.
void get_new_anweisung(mutabor_box_type *box)
References mutabor_box_type::file, get_last_aktions_liste, get_last_ausloeser, anweisung::next, mutabor_logic_parsed::tmp_anweisungsliste, TRACE, xmalloc.
Referenced by switch, yyparse.
void get_new_logik(mutabor_box_type *box, const char *name, const char *einstimmung)
References _, logik::anweisungsliste, compiler_error, logik::einstimmung, logik::einstimmungs_name, mutabor_box_type::file, get_last_ausloeser, logik::harmony_list, logik::keystroke_list, mutabor_logic_parsed::list_of_logiken, logik::midi_input_list, mutabor_error_message, logik::name, logik::next, TRACE, xmalloc.
Referenced by switch, yyparse.
void vervollstaendige_logik(mutabor_box_type *box)
References logik::anweisungsliste, mutabor_box_type::file, get_last_anweisungs_liste, mutabor_logic_parsed::list_of_logiken, logik::next, TRACE.
Referenced by switch, yyparse.
void get_instrument_dekl(mutabor_box_type *box, int midi_in, int midi_von, int midi_bis, int midi_umleit, struct instrument **list_to_insert)
References _, compiler_error, mutabor_error_message, logik::next, instrument::next, TRACE, xmalloc.
Referenced by mutabor_programm_einlesen, SetChannels, switch, yyparse.
static void belege_toene(struct ton **toene, struct ton *liste)
References ton::next, TRACE.
Referenced by berechne_toene_absolut.
static int ton_nummer(mutabor_box_type *box, const char *name)
References _, mutabor_logic_parsed::anzahl_toene, compiler_error, mutabor_box_type::file, mutabor_error_message, ton::name, mutabor_logic_parsed::toene, TRACE.
Referenced by berechne_toene_absolut, berechne_ton_endgueltig.
static void berechne_ton_endgueltig(mutabor_box_type *box, int k)
References _, mutabor_box_type::file, get_wert_komplex_intervall, internal_error, mutabor_error_message, mutabor_logic_parsed::toene, ton_absolut, ton::ton_absolut, ton_komplex, ton::ton_komplex, ton_nummer, ton::ton_typ, TRACE, ton::u.
Referenced by berechne_toene_absolut.
int enthalten_in_tastenliste(int taste, struct taste *lauf)
References logik::next, TRACE.
Referenced by check_ausloeser.
int case_label_enthalten_in_case_liste(double case_label, struct case_liste *lauf)
References logik::next, TRACE.
Referenced by check_konsistenz.
static void check_ausloeser(mutabor_box_type *box, struct ausloeser *ausloeser, const char *name)
References _, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser::ausloeser_typ, compiler_error, compiler_warning, enthalten_in_tastenliste, mutabor_box_type::file, get_harmonie, mutabor_logic_parsed::list_of_harmonien, midiliste::midi_code, mutabor_error_message, MUTABOR_INVALID_KEY, MUTABOR_NO_KEY, midiliste::next, harmonie::tastenliste, TRACE, ausloeser::u.
Referenced by check_konsistenz.
static void check_aktionen(mutabor_box_type *box, struct aktions_liste *aktionen, const char *name)
References _, aktion_aufruf, aktions_liste::aktion_aufruf, aktion_harmony_analysis, aktion_midi_out, aktions_liste::aktion_midi_out, aktions_liste::aktions_typ, argument_list_laenge, compiler_error, compiler_warning, mutabor_box_type::file, get_logik, get_umstimmung, internal_error, mutabor_logic_parsed::list_of_logiken, mutabor_logic_parsed::list_of_tonsysteme, mutabor_logic_parsed::list_of_umstimmungen, midiliste::midi_code, mutabor_error_message, midiliste::next, parameter_list_laenge, umstimmung::parameter_liste, parser_get_tonsystem, TRACE, aktions_liste::u, xcalloc.
Referenced by check_konsistenz.
static void belege_zyklenfeld(struct umst_oder_logik *zyklen_feld, struct umstimmung *liste1, struct logik *liste2)
References umst_oder_logik::logik, umstimmung::next, logik::next, TRACE, typ_logik, typ_umstimmung, umst_oder_logik::u, umst_oder_logik::umst_oder_logik_typ, umst_oder_logik::umstimmung.
Referenced by check_konsistenz.
static int test_zyklen_nummer(mutabor_box_type *box, const char *name)
References _, mutabor_logic_parsed::anzahl_umstimmungen_und_logiken, compiler_error, mutabor_box_type::file, umst_oder_logik::logik, mutabor_error_message, umstimmung::name, logik::name, TRACE, typ_logik, typ_umstimmung, umst_oder_logik::u, umst_oder_logik::umst_oder_logik_typ, umst_oder_logik::umstimmung, mutabor_logic_parsed::zyklen_feld.
Referenced by check_konsistenz.
static void u_test_zyklen(mutabor_box_type *box, int startknoten)
References _, mutabor_logic_parsed::anzahl_umstimmungen_und_logiken, compiler_error, mutabor_box_type::file, umst_oder_logik::logik, mutabor_error_message, mutabor_u_adjacent, umstimmung::name, logik::name, TRACE, typ_umstimmung, umst_oder_logik::u, mutabor_logic_parsed::u_matrix, mutabor_logic_parsed::u_visited, umst_oder_logik::umst_oder_logik_typ, umst_oder_logik::umstimmung, mutabor_logic_parsed::zyklen_feld.
Referenced by check_konsistenz.
static struct do_aktion * expandiere_name(mutabor_box_type *box, const char *name, struct argument_list *parameter, struct interpreter_argument_list *bezugs_liste)
References _, compiler_error, expandiere_logik, expandiere_tonsystem, expandiere_umstimmung, mutabor_box_type::file, generate_argument_list, get_logik, get_umstimmung, mutabor_logic_parsed::list_of_logiken, mutabor_logic_parsed::list_of_tonsysteme, mutabor_logic_parsed::list_of_umstimmungen, mutabor_error_message, parser_get_tonsystem, TRACE.
Referenced by expand_aktions_liste.
static struct do_aktion * expandiere_umstimmung(mutabor_box_type *box, struct umstimmung *the_umstimmung, struct interpreter_argument_list *aktuelle_parameter)
References _, umstimmung::argument_liste, do_aktion::arguments, aufruf_midi_out, aufruf_umst_breite_abs, aufruf_umst_breite_rel, aufruf_umst_taste_abs, aufruf_umst_taste_rel, aufruf_umst_toene_veraendert, aufruf_umst_umst_bund, aufruf_umst_umst_case, aufruf_umst_wiederholung_abs, aufruf_umst_wiederholung_rel, do_aktion::calling, expand_aktions_liste, expand_case_liste, expand_tonliste, generate_argument_list, get_wert_komplex_intervall, internal_error, mutabor_convert_factor_to_pitch, mutabor_convert_pitch_to_interval, mutabor_error_message, do_aktion::name, do_aktion::next, resolve_parameters, do_aktion::secondary_arguments, TRACE, umstimmung::u, do_aktion::u, umstimmung_breite_abs, umstimmung_breite_rel, umstimmung::umstimmung_breite_rel, umstimmung_midi_out, umstimmung::umstimmung_midi_out, umstimmung_taste_abs, umstimmung_taste_rel, umstimmung::umstimmung_taste_rel, umstimmung_toene_veraendert, umstimmung::umstimmung_toene_veraendert, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, xfree, xmalloc.
Referenced by expandiere_logik, expandiere_name.
static struct do_aktion * expandiere_midi(mutabor_box_type *box, struct midiliste *liste)
References _, do_aktion::arguments, aufruf_midi_out, do_aktion::name, do_aktion::next, do_aktion::secondary_arguments, TRACE, do_aktion::u, xmalloc.
Referenced by expand_aktions_liste.
static struct do_aktion * expand_harmony_analysis(mutabor_box_type *box)
References _, do_aktion::arguments, aufruf_harmony_analysis, do_aktion::name, do_aktion::next, do_aktion::secondary_arguments, TRACE, xmalloc.
Referenced by expand_aktions_liste.
void insert_in_lokale_liste(mutabor_box_type *box, struct do_aktion *action, struct anweisung *lauf, struct logik *logic)
References _, midi_ereignis::aktion, keyboard_ereignis::aktion, harmonie_ereignis::aktion, anweisung::aktion, anweisung::ausloeser, ausloeser_default, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser_taste, create_midi_scan_liste, expand_aktions_liste, expand_pattern, midi_ereignis::first_pos, logik::harmony_list, internal_error, harmonie_ereignis::ist_harmonieform, logik::keystroke_list, logik::midi_input_list, mutabor_error_message, MUTABOR_INVALID_KEY, mutabor_is_else_path, mutabor_is_harmonic_form, mutabor_is_no_harmonic_form, harmonie_ereignis::nachtaste, midi_ereignis::name, keyboard_ereignis::name, harmonie_ereignis::name, logik::name, midi_ereignis::next, keyboard_ereignis::next, harmonie_ereignis::next, harmonie_ereignis::pattern, midi_ereignis::scan_pos, TRACE, ausloeser::u, harmonie_ereignis::vortaste, xmalloc.
Referenced by expand_decition_tree, expandiere_logik.
double get_komplex_faktor(mutabor_box_type *box, struct komplex_intervall *lauf)
References _, compiler_error, komplex_intervall::faktor, mutabor_box_type::file, get_intervall, internal_error, intervall_absolut, intervall_komplex, mutabor_logic_parsed::list_of_intervalle, mutabor_error_message, komplex_intervall::name, do_aktion::next, TRACE, intervall::u.
Referenced by expand_tonliste, get_komplex_frequenz.
double get_komplex_frequenz(mutabor_box_type *box, struct ton *dieser)
References mutabor_box_type::file, get_komplex_faktor, get_ton, mutabor_logic_parsed::list_of_toene, ton::ton_komplex, intervall::u, ton::u.
Referenced by expand_tonliste.
void fprint_argument(mutabor_box_type *box, FILE *zieldatei, struct argument *argument)
References _, internal_error, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_parameter, mutabor_error_message, TRACE, intervall::u.
static void reduce_argument(mutabor_box_type *box, struct interpreter_argument_list *list, size_t index, struct interpreter_argument_list *reference)
References interpreter_argument::constant, interpreter_argument_list::data, interpreter_argument::index, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, interpreter_argument_list::types.
Referenced by generate_argument_list.
static struct interpreter_argument_list* generate_argument_list(mutabor_box_type *box, struct argument_list *element, struct interpreter_argument_list *bezugs_liste)
References _, argument_list::argument, argument::argument_type, interpreter_argument::constant, interpreter_argument_list::data, mutabor_box_type::file, if, interpreter_argument::index, internal_error, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, mutabor_error_message, argument_list::next, mutabor_logic_parsed::parameter_count, reduce_argument, interpreter_argument_list::size, TRACE, interpreter_argument_list::types, xcalloc, xmalloc.
Referenced by expandiere_name, expandiere_umstimmung.
static void resolve_parameters(mutabor_box_type *box, struct interpreter_argument_list *target, struct interpreter_argument_list *reference)
References _, interpreter_argument_list::data, interpreter_argument::index, internal_error, mutabor_argument_anchor, mutabor_argument_distance, mutabor_argument_integer, mutabor_argument_invalid, mutabor_argument_parameter, mutabor_error_message, interpreter_argument_list::size, interpreter_argument_list::types.
Referenced by expandiere_umstimmung.
static struct ton_einstell* expand_tonliste(mutabor_box_type *box, struct ton *the_tonliste)
References _, einstell_absolut, einstell_gleich, einstell_relativ, einstell_stumm, get_komplex_faktor, get_komplex_frequenz, internal_error, mutabor_convert_factor_to_pitch, mutabor_convert_frequency_to_pitch, mutabor_convert_pitch_to_interval, mutabor_convert_pitch_to_tone, mutabor_error_message, ton::name, ton_einstell::next, ton_absolut, ton::ton_absolut, ton_komplex, ton::ton_komplex, TRACE, ton_einstell::u, ton::u, xmalloc.
Referenced by expandiere_umstimmung.
static struct do_aktion* expandiere_tonsystem(mutabor_box_type *box, struct tonsystem *the_tonsystem)
References do_aktion::arguments, aufruf_tonsystem, mutabor_box_type::file, get_ton, get_wert_komplex_intervall, mutabor_logic_parsed::list_of_toene, mutabor_convert_factor_to_pitch, mutabor_convert_frequency_to_pitch, mutabor_convert_pitch_to_interval, mutabor_convert_pitch_to_tone, ton::name, do_aktion::name, ton::next, do_aktion::secondary_arguments, TSYS::ton, ton_list_laenge, TRACE, ton::u, xmalloc.
Referenced by expandiere_logik, expandiere_name.
static struct do_aktion* expandiere_logik(mutabor_box_type *box, struct logik *the_logik)
References _, logik::anweisungsliste, do_aktion::arguments, aufruf_logik, do_aktion::calling, compiler_error, logik::einstimmungs_name, expandiere_tonsystem, expandiere_umstimmung, mutabor_box_type::file, get_logik_nummer, get_umstimmung, logik::harmony_list, insert_in_lokale_liste, logik::keystroke_list, mutabor_logic_parsed::list_of_logiken, mutabor_logic_parsed::list_of_tonsysteme, mutabor_logic_parsed::list_of_umstimmungen, logik::midi_input_list, mutabor_error_message, mutASSERT, do_aktion::name, do_aktion::next, anweisung::next, parser_get_tonsystem, do_aktion::secondary_arguments, TRACE, do_aktion::u, xmalloc.
Referenced by expandiere_in_globale_liste, expandiere_name.
static struct do_aktion* expand_aktions_liste(mutabor_box_type *box, struct aktions_liste *the_liste, struct interpreter_argument_list *current_parameters)
References _, aktion_aufruf, aktion_harmony_analysis, aktion_midi_out, expand_harmony_analysis, expandiere_midi, expandiere_name, internal_error, mutabor_error_message, do_aktion::next, TRACE, do_aktion::u.
Referenced by expand_case_liste, expandiere_umstimmung, insert_in_lokale_liste.
static struct case_element* expand_case_liste(mutabor_box_type *box, struct case_liste *the_liste, struct interpreter_argument_list *aktuelle_parameter)
References case_liste::case_aktion, case_liste::case_label, expand_aktions_liste, case_liste::is_default, case_liste::next, TRACE, xmalloc.
Referenced by expandiere_umstimmung.
static int* create_midi_scan_liste(mutabor_box_type *box, struct midiliste *lauf)
References midiliste::midi_code, midi_list_laenge, midiliste::next, TRACE, xcalloc.
Referenced by insert_in_globale_liste, insert_in_lokale_liste.
PATTERNN* expand_pattern(mutabor_box_type *box, const char *harmonie_name)
References _, taste::code, compiler_error, mutabor_box_type::file, for, get_harmonie, mutabor_logic_parsed::list_of_harmonien, mutabor_error_message, MUTABOR_KEYRANGE_MAX_WIDTH, taste::next, taste::stern, harmonie::tastenliste, PTRN::tonigkeit, TRACE, xmalloc.
Referenced by insert_in_globale_liste, insert_in_lokale_liste.
void insert_in_globale_liste(mutabor_box_type *box, struct logik *lauf)
References _, midi_ereignis::aktion, keyboard_ereignis::aktion, harmonie_ereignis::aktion, logik::ausloeser, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser_taste, create_midi_scan_liste, expand_pattern, mutabor_box_type::file, midi_ereignis::first_pos, mutabor_logic_parsed::global_harmonies, mutabor_logic_parsed::global_keystrokes, mutabor_logic_parsed::global_midi_inputs, internal_error, harmonie_ereignis::ist_harmonieform, mutabor_error_message, MUTABOR_INVALID_KEY, mutabor_is_harmonic_form, mutabor_is_no_harmonic_form, mutASSERT, harmonie_ereignis::nachtaste, midi_ereignis::name, keyboard_ereignis::name, harmonie_ereignis::name, logik::name, midi_ereignis::next, keyboard_ereignis::next, harmonie_ereignis::next, harmonie_ereignis::pattern, midi_ereignis::scan_pos, midi_ereignis::the_logik_to_expand, keyboard_ereignis::the_logik_to_expand, harmonie_ereignis::the_logik_to_expand, TRACE, ausloeser::u, harmonie_ereignis::vortaste, xmalloc.
Referenced by expand_decition_tree.
static void expandiere_in_globale_liste(mutabor_box_type *box)
References midi_ereignis::aktion, DEBUGLOG2, expandiere_logik, mutabor_box_type::file, mutabor_logic_parsed::global_harmonies, mutabor_logic_parsed::global_keystrokes, mutabor_logic_parsed::global_midi_inputs, mutASSERT, midi_ereignis::next, midi_ereignis::the_logik_to_expand, TRACE.
Referenced by expand_decition_tree.
void expand_decition_tree(mutabor_box_type *box)
References logik::anweisungsliste, expandiere_in_globale_liste, mutabor_box_type::file, mutabor_logic_parsed::global_harmonies, mutabor_logic_parsed::global_keystrokes, mutabor_logic_parsed::global_midi_inputs, insert_in_globale_liste, insert_in_lokale_liste, mutabor_logic_parsed::list_of_logiken, logik_list_laenge, mutASSERT, logik::name, anweisung::next, logik::next, TRACE, xcalloc.
Referenced by mutabor::BoxClass::Compile, boxTest::testBug1Permutation1, boxTest::testBug1Permutation2, boxTest::testFindKeyByKey.
const char * wxwidgets_sgettext(const char *msgid)
not for headers
References wxwidgets_gettext.
const char * wxwidgets_dgettext(const char *domainname, const char *msgid)
References wxwidgets_gettext.
const char * wxwidgets_sngettext(const char *msgid1, const char *msgid2, unsigned long int n)
References wxwidgets_gettext.
const char * wxwidgets_dngettext(const char *domainname, const char *msgid1, const char *msgid2, unsigned long int n)
References wxwidgets_gettext.
const char* wxwidgets_gettext(const std::string &msgid)
References cache, muT.
const char* wxwidgets_gettext(const std::string &domainname, const std::string &msgid)
References cache, muT.
const char* wxwidgets_gettext(const std::string &msgid1, const std::string &msgid2, unsigned long int n)
References cache, muT.
const char* wxwidgets_gettext(const std::string &domainname, const std::string &msgid1, const std::string &msgid2, unsigned long int n)
References cache, muT.
frac & frac::operator=(const frac &f)
References frac::d, frac::n.
frac & frac::operator+=(const frac &f)
References frac::d, frac::gcd, frac::n.
frac & frac::operator-=(const frac &f)
References frac::d, frac::gcd, frac::n.
frac & frac::operator*=(const frac &f)
References frac::d, frac::gcd, frac::n.
frac & frac::operator/=(const frac &f)
References frac::d, frac::gcd, frac::n.
frac frac::operator+(const frac s)
References frac::d, frac::frac, frac::gcd, frac::n.
frac frac::operator-(const frac s)
References frac::d, frac::frac, frac::gcd, frac::n.
frac frac::operator*(const frac s)
References frac::d, frac::frac, frac::gcd, frac::n.
frac frac::operator/(const frac s)
References frac::d, frac::frac, frac::gcd, frac::n.
int frac::operator<(const frac &f)
References frac::d, frac::n.
int frac::operator<=(const frac &f)
References frac::d, frac::n.
int frac::operator==(const frac &f)
References frac::d, frac::n.
int frac::operator!=(const frac &f)
References frac::d, frac::n.
int frac::operator>=(const frac &f)
References frac::d, frac::n.
int frac::operator>(const frac &f)
References frac::d, frac::n.
frac & frac::operator=(const int &i)
References frac::d, frac::n.
mutint64 frac::gcd(mutint64 a, mutint64 b)
References absLong.
Referenced by frac::operator*, frac::operator*=, frac::operator+, frac::operator+=, frac::operator-, frac::operator-=, frac::operator/, frac::operator/=.
void boxTest::setUp()
References mutabor_initialize_box.
void boxTest::tearDown()
void boxTest::testMUT_BOX_MAX_KEY_INDEX()
References MUT_BOX_MAX_KEY_INDEX.
void boxTest::verifyLastKey(bool force=true)
References MUT_BOX_MAX_KEY_INDEX, mutabor_find_key_in_box, MUTABOR_NO_NEXT.
void boxTest::testAddKey()
References box, mutabor_note_type::id, last, MUT_BOX_MAX_KEY_INDEX, mutabor_create_key_in_box, mutabor_note_type::number.
void boxTest::verifyAddKey()
References mutabor_note_type::id, MUT_BOX_MAX_KEY_INDEX, mutabor_find_key_in_box, mutabor_note_type::number.
void boxTest::testDeleteKey()
References last, MUT_BOX_MAX_KEY_INDEX, mutabor_delete_key_in_box.
void boxTest::testReaddKey()
References DEBUGLOG, mutabor_note_type::id, MUT_BOX_MAX_KEY_INDEX, mutabor_create_key_in_box, mutabor_note_type::number.
void boxTest::checkMask()
References MUT_BOX_MAX_KEY_INDEX, mutabor_find_key_in_box, mutabor_note_type::number.
void boxTest::testAddDeleteKey()
check adding and deleting of keys.
As we must generate many pages for a sufficient check, we must add a huge number of entries.
References MUT_BOX_MAX_KEY_INDEX.
void boxTest::test_init()
References MUT_BOX_MAX_KEY_INDEX, MUTABOR_KEYRANGE_MAX_WIDTH, MUTABOR_NO_NEXT.
void boxTest::testFindKeyByKey()
References AddKey, box, mutabor_note_type::channel, expand_decition_tree, mutabor_note_type::id, loesche_syntax_speicher, mutabor_delete_key_in_box, mutabor_find_key_in_box, mutabor_find_key_in_box_by_key, MUTABOR_NO_NEXT, mutabor_programm_einlesen, mutASSERT, mutabor_note_type::next, mutabor_note_type::number.
void boxTest::testBug1Permutation1()
References AddKey, box, expand_decition_tree, loesche_syntax_speicher, mutabor_delete_key_in_box, mutabor_find_key_in_box_by_key, MUTABOR_NO_NEXT, mutabor_programm_einlesen.
void boxTest::testBug1Permutation2()
References AddKey, box, DeleteKey, expand_decition_tree, loesche_syntax_speicher, mutabor_programm_einlesen.
SRC_KERNEL_BOOST_INTERFACE_H
SRC_KERNEL_BOOST_INTERFACE_H_PRECOMPILED
REFPTR_INTERFACE
REFPTR_INTERFACE_NOLOCK
CHECK_REFPTR_NULL
MU32_BOX_H
MU32_BOX_H_PRECOMPILED
MUT_BOX_MAX_KEY_INDEX_LOG
Referenced by mutabor_create_key_in_box, mutabor_find_key_in_box.
MUT_BOX_MAX_KEY_INDEX
Referenced by boxTest::checkMask, mutabor_create_key_in_box, mutabor_find_key_in_box, mutabor_initialize_keyplane, boxTest::test_init, boxTest::testAddDeleteKey, boxTest::testAddKey, boxTest::testDeleteKey, boxTest::testMUT_BOX_MAX_KEY_INDEX, boxTest::testReaddKey, boxTest::verifyAddKey, boxTest::verifyLastKey.
MUTABOR_NO_NEXT
Referenced by mutabor_create_key_in_box, mutabor_delete_key_in_box, mutabor_find_key_in_box, mutabor_find_key_in_box_by_key, mutabor_initialize_keyplane, mutabor_reset_keys, boxTest::test_init, boxTest::testBug1Permutation1, boxTest::testFindKeyByKey, boxTest::verifyLastKey.
MUTWIN
REUSE
STD_PRE
mutT
Referenced by BeginParameter, BeginRange, ChordNote::CheckCloseTie, ChordNote::ChordNote, CloseAllSubs, GisWriteHead::CloseCurrentToken, GisWriteHead::CloseSubs, GisReadHead::CreateSegmentSubs, GisReadHead::CreateSequenzSubs, DoParse, EndParameter, GisWriteHead::GetFreeNote, GetMidiInstrument, GetSep, GetTheSpeedFactor, GisNote::GisNote, IsLetter, IsNumber, mutabor::MutaborTag, ChordNote::MutNoteOn, Name2Key, ReadLong, ReadNote, ReadParaNumber, ReadParaStr, ReadTag, switch.
mutUnused
Referenced by mutaborGUI::BoxDlg::AddButtonPressed, BEGIN_EVENT_TABLE, mutaborGUI::NewMutBoxShape::CanHandleType, mutaborGUI::MutBoxShape::CmLeftDblClick, mutaborGUI::MutFrame::CmStop, MutIconShapeClass< MutPanel >::DeleteSelfEvent, mutaborGUI::MutFrame::DoBoxWindowsOpen, mutaborGUI::MutBoxChannelShape::DrawPerimeterPoint, END_EVENT_TABLE, EVT_SIZE, mutaborGUI::InputDevDlg::GetBitmapResource, mutaborGUI::MutOutputGuidoFileDeviceShape::GetFilterPanel, mutaborGUI::InputDevDlg::GetIconResource, IMPLEMENT_APP, IMPLEMENT_DYNAMIC_CLASS, mutabor::OutputGis::Load, mutaborGUI::MutChild::OnActivate, mutaborGUI::MutLogicWnd::OnActivate, mutaborGUI::MutChild::OnAuiClose, MutPanel::OnChildFocus, MutTextBox::OnClose, mutaborGUI::MutEditFile::OnFind, MutIconShapeClass< T >::OnMouseClick, mutaborGUI::MutFrame::OnPaint, mutaborGUI::InputDevDlg::OnRemoveClick, mutaborGUI::BoxDlg::OnRemoveClick, mutaborGUI::MutFrame::OpenFile, PRINTWINDOW, mutaborGUI::NewMutBoxShape::readDialog, mutaborGUI::MutOutputGuidoFileDeviceShape::ReadFilterPanel, mutaborGUI::RouteRemoveButton::RemoveButtonPressed, mutabor::OutputGis::Save, MutIconShapeClass< T >::UpdateBorder.
mutChar
Referenced by DoParse, GetSep, GisNote::GisNote, mutabor::DeviceFactory::LoadInputDevices, mutabor::DeviceFactory::LoadOutputDevices, compat30::LoadRoutes, Name2Key, mutabor::MidiPortOutputProvider::Open, mutabor::InputMidiPort::Open, mutabor::InputMidiFile::Open, mutabor::InputGis::ProceedRoute, ReadNote, ReadParaNumber, ReadParaStr, ReadTag.
mutString
Referenced by midicmnOutputDevice::Check, ChordNote::CheckCloseAlter, ChordNote::CheckCloseTie, OutputMidiFileTest::CheckOut, GisReadHead::CreateSegmentSubs, GisReadHead::CreateSequenzSubs, mutabor::BoxClass::get_errors, GetMidiInstrument, GetTheSpeedFactor, IMPLEMENT_APP, compat30::LoadRoutes, mutabor::MutaborTag, mutabor::DebugMidiOutputProvider::RawMsg, mutabor::tree_storage::Read, ReadNote, ReadParaStr, ReadTag, mutabor::DebugMidiOutputProvider::SendSysEx, CommonMidiInputTest::testGlobalPanic, CommonMidiOutputTest::testNoteOnOff, CommonMidiInputTest::testPanic, configtree::toFirstLeaf, mutaborGUI::xmltree::toFirstLeaf, configtree::toNextLeaf, mutaborGUI::xmltree::toNextLeaf, mutabor::DebugMidiOutputProvider::WriteTime.
mutStringRef
mutEmptyString
Referenced by ChordNote::CheckCloseAlter, ChordNote::CheckCloseTie, ChordNote::ChordNote, mutabor::BoxClass::get_errors, GisWriteHead::GetFreeNote, GetSep, GetTagId, GisNote::GisNote, GisParse, GisSegment::GisSegment, GisSequenz::GisSequenz, GspParse, mutabor::CommonFileOutputDevice::Load, mutabor::OutputGis::Load, mutabor::CommonFileInputDevice::Load, mutabor::OutputMidiFile::Load, ReadNewLine.
mutFreeString
Referenced by GisReadHead::~GisReadHead, GisSegment::~GisSegment, GisSequenz::~GisSequenz, GisTag::~GisTag, GisToken::~GisToken, GisWriteHead::~GisWriteHead.
mutDelString
mutFopen
mutCopyString
Referenced by EndSegment, EndSequenz, GisReadHead::GisReadHead, Tag.
mutCopyIntoString
Referenced by SavePos.
mutStrdup
mutStrCmp
Referenced by GetMatchingHeader.
mutStrEq
Referenced by mutabor::MutaborTag.
mutStrLast
C_STR
Referenced by mutabor::InputGis::Open.
mutC_STR
Referenced by mutabor::InputGis::Open.
mutStrLen
mutStrChr
Referenced by CharIn.
mutFileName
mutOFstream
mutIFstream
mutTextStrem
mutOpenOFstream
Referenced by mutabor::OutputMidiFile::Close.
mutOpenIFstream
Referenced by mutabor::InputMidiFile::Open.
mutWriteStream
Referenced by mutabor::Track::Save, mutabor::MidiFileOutputProvider::Save.
mutReadStream
Referenced by mutabor::InputMidiFile::Open, mutabor::ReadLength.
mutCloseStream
Referenced by mutabor::InputMidiFile::Open.
mutPutC
Referenced by mutabor::Track::WriteLength.
mutGetC
Referenced by mutabor::InputMidiFile::Open.
mutStreamBad
Referenced by mutabor::InputMidiFile::Open, OpenFile, ReadNewLine.
mutStreamGood
Referenced by mutabor::InputMidiFile::Open.
mutStreamEOF
Referenced by mutabor::InputMidiFile::Open, ReadNewLine.
mutAssertMsg
mutASSERT
Referenced by mutaborGUI::GUIRouteBase::Add, mutaborGUI::MutBoxShape::Add, mutaborGUI::MutDeviceShape< T >::Add, mutabor::BoxClass::Add, mutaborGUI::GUIOutputDeviceBase::Add, mutaborGUI::GUIInputDeviceBase::Add, mutabor::CommonTypedDeviceAPI< T, P, L >::Add, mutaborGUI::MutRouteWnd::AddBox, mutaborGUI::MutBoxShape::AddChannel, mutaborGUI::MutRouteWnd::AddInputDevice, mutaborGUI::MutRouteWnd::AddOutputDevice, mutaborGUI::MutBoxShape::AddPossibleOutput, mutaborGUI::MutRouteWnd::AddRoute, mutabor::TRouteClass< I, O, B >::AppendToRouteList, mutabor::InputDeviceClass::BatchPlay, BEGIN_EVENT_TABLE, mutaborGUI::BEGIN_EVENT_TABLE, BEGIN_EVENT_TABLE_TEMPLATE1, mutabor::BoxClass::BoxLock::BoxLock, call_actions, mutabor::BoxClass::ClearBoxList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::ClearDeviceList, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::ClearRouteList, mutaborGUI::MutChild::ClientToScreen, mutabor::CommonFileOutputDevice::Close, mutabor::CommonFileInputDevice::Close, mutabor::DebugMidiOutputProvider::Close, mutabor::InputMidiPort::Close, mutabor::CommonMidiOutput< T, D >::Close, mutaborGUI::MutFrame::CloseClientWindow, mutaborGUI::MutLogicWnd::CmMutTag, mutaborGUI::MutRouteWnd::CmRouteLoad, mutaborGUI::MutLogicWnd::CmTaste, mutaborGUI::MutBoxChannelShape::Create, mutaborGUI::MutDeviceShape< T >::Create, mutabor::BoxFactory::Create, mutaborGUI::MutRouteWnd::createBoxes, mutaborGUI::GUIBoxFactory::CreateBoxShape, mutabor::DeviceFactory::CreateInput, mutaborGUI::MutRouteWnd::createInputDevices, mutabor::DeviceFactory::CreateOutput, mutaborGUI::MutDeviceShape< T >::createPauseButton, mutaborGUI::MutDeviceShape< T >::createPlayButtons, mutaborGUI::MutDeviceShape< T >::createRecordButtons, mutaborGUI::MutRouteWnd::createRoutes, mutaborGUI::GUIDeviceFactory::CreateShape, GisReadHead::CutOut, mutaborGUI::MutBoxShape::DeleteBox, mutaborGUI::MutChild::deleteFromWinAttrs, mutaborGUI::GUIfiedRoute< T >::Destroy, mutabor::CommonMidiOutput< T, D >::do_Controller, mutabor::CommonMidiOutput< T, D >::do_GetChannel, mutabor::CommonMidiOutput< T, D >::do_NoteOff, mutabor::CommonMidiOutput< T, D >::do_NoteOn, mutabor::CommonFileOutputDevice::do_Open, mutabor::CommonMidiOutput< T, D >::do_Open, mutabor::CommonMidiOutput< T, D >::do_SplitOut, mutabor::CommonMidiOutput< T, D >::do_UpdateControllers, mutabor::CommonMidiOutput< T, D >::do_UpdateTones, mutaborGUI::BoxData::DoClose, mutaborGUI::GUIRouteFactory::DoCreateBoxChannelShape, mutaborGUI::GUIMidiPortFactory::DoCreateShape, mutaborGUI::GUIMidiFileFactory::DoCreateShape, mutaborGUI::GUIGisFactory::DoCreateShape, MutIconShapeClass< T >::DoGetBestSize, mutaborGUI::MutBoxShape::DoLeftDblClick, mutaborGUI::MutDeviceShape< T >::DoLeftDblClick, mutabor::RouteFactory::DoLoadRoutes, MkIDlist::doMkIDlist, mutaborGUI::DontWant, mutaborGUI::BoxData::DoOpen, mutabor::RouteFactory::DoSaveRoutes, mutaborGUI::MutFrame::DoStop, mutaborGUI::MutBoxShape::DrawLines, mutaborGUI::MutBoxChannelShape::DrawLines, mutaborGUI::MutBoxChannelShape::DrawPerimeterPoint, mutabor::CommonMidiOutput< T, D >::EmergencyFindChannel, END_EVENT_TABLE, execute_aktion, expand_decition_tree, expandiere_in_globale_liste, expandiere_logik, mutaborGUI::MutLogicWnd::FixSizer, generic_keyboard_analysis, mutabor::ChannelData::get_next_changed_controller, mutaborGUI::MutaborBoxSettings::GetBoxNumber, mutaborGUI::BoxDlg::GetBoxNumber, mutaborGUI::MutChild::GetClientSize, mutaborGUI::MutView::GetMutFrame, mutaborGUI::MutBoxChannelShape::GetMutIcon, mutaborGUI::MutBoxIconShape::GetMutIcon, MutIconShapeClass< T >::GetPerimeterPoint, mutaborGUI::MutBoxChannelShape::GetPerimeterPoint, mutaborGUI::GetStaticBoxSize, mutabor::BoxClass::GetToneSystem, mutaborGUI::OutputDevDlg::GetType, mutaborGUI::InputDevDlg::GetType, mutabor::CommonFileOutputDevice::GetTypeName, HarmonyAnalysis, mutaborGUI::MutBoxShape::HasChannel, mutaborGUI::IMPLEMENT_CLASS, mutaborGUI::BoxDlg::InitializeBoxTypes, mutaborGUI::NewMutBoxShape::InitializeDialog, mutaborGUI::MutOutputMidiDeviceShape::InitializeDialog, mutaborGUI::MutOutputGuidoFileDeviceShape::InitializeDialog, mutaborGUI::MutOutputMidiFileDeviceShape::InitializeDialog, mutaborGUI::MutInputGuidoFileDeviceShape::InitializeDialog, mutaborGUI::MutBoxShape::InitializeDialog, mutaborGUI::MutInputMidiDeviceShape::InitializeDialog, mutaborGUI::MutInputMidiFileDeviceShape::InitializeDialog, mutaborGUI::MutBoxChannelShape::InitializeInputFilter, mutaborGUI::MutBoxChannelShape::InitializeOutputFilter, mutaborGUI::MutBoxChannelShape::InitializeRoute, mutaborGUI::initMutBitmap, mutaborGUI::MutRouteWnd::InitShapes, insert_in_globale_liste, GisReadHead::InsertInfrontOf, mutabor::ChannelData::is_changed_controller, mutaborGUI::IsOpen, mutaborGUI::IsWanted, mutabor::CommonFileOutputDevice::Load, mutabor::OutputGis::Load, mutabor::TRouteClass< I, O, B >::Load, mutabor::CommonFileInputDevice::Load, mutabor::InputGis::Load, mutabor::OutputMidiPort::Load, mutabor::InputMidiPort::Load, mutabor::OutputMidiFile::Load, mutabor::InputMidiFile::Load, mutabor::BoxFactory::LoadBoxes, mutabor::DeviceFactory::LoadInputDevices, mutabor::DeviceFactory::LoadOutputDevices, mutabor::TRouteClass< I, O, B >::LoadRoutes, MidiAnalysis, mutabor::channel_queue_template< unsigned char, 16 >::move_to_end, mutabor::channel_queue_template< unsigned char, 16 >::move_to_front, mutaborGUI::MutRouteWnd::MoveShape, mutabor_create_key_in_box, mutabor_delete_key_in_box, mutabor_initialize_box, MutTextBox::NewText, mutaborGUI::MutChild::OnActivate, mutaborGUI::MutChild::OnAuiClose, mutaborGUI::MutChild::OnChar, mutaborGUI::MutChild::OnClose, MutTextBox::OnClose, mutaborGUI::MutRouteWnd::OnDraw, mutabor::CommonFileInputDevice::FileTimer::OnExit, mutabor::CommonFileInputDevice::Open, mutabor::DebugMidiOutputProvider::Open, mutabor::InputMidiPort::Open, mutabor::InputMidiFile::Open, mutabor::MidiPortOutputProvider::operator(), mutabor::DebugMidiOutputProvider::operator(), mutabor::MidiFileOutputProvider::operator(), mutabor::CurrentTimer::operator+=, mutaborGUI::xmltree::state::operator==, mutabor::BoxClass::Panic, mutabor::Track::PassDelta, mutabor::CommonFileInputDevice::Pause, mutabor::CommonFileInputDevice::Play, mutabor::InputGis::Proceed, mutabor::InputGis::ProceedRoute, mutaborGUI::MutFrame::RaiseLogic, mutabor::MidiPortOutputProvider::RawMsg, mutabor::DebugMidiOutputProvider::RawMsg, mutaborGUI::xmltree::Read, mutabor::Track::ReadDelta, mutaborGUI::MutOutputMidiDeviceShape::readDialog, mutaborGUI::MutOutputMidiFileDeviceShape::readDialog, mutaborGUI::MutOutputGuidoFileDeviceShape::readDialog, mutaborGUI::MutInputGuidoFileDeviceShape::readDialog, mutaborGUI::MutInputMidiDeviceShape::readDialog, mutaborGUI::MutInputMidiFileDeviceShape::readDialog, mutaborGUI::MutBoxShape::readDialog, mutaborGUI::MutDeviceShape< T >::readDialog, mutaborGUI::MutOutputMidiDeviceShape::ReadFilterPanel, mutaborGUI::MutOutputMidiFileDeviceShape::ReadFilterPanel, mutabor::Track::ReadMessage, mutabor::InputMidiFile::ReadMidiProceed, mutabor::InputGis::ReadOn, mutaborGUI::MutDeviceShape< T >::ReadPanel, mutaborGUI::MutBoxChannelShape::ReadPanel, mutabor::reconnect, mutaborGUI::reconnect, mutaborGUI::GUIRouteBase::Remove, mutaborGUI::BoxData::Remove, mutabor::BoxClass::Remove, mutaborGUI::GUIOutputDeviceBase::Remove, mutaborGUI::GUIInputDeviceBase::Remove, mutabor::CommonTypedDeviceAPI< T, P, L >::Remove, mutabor::TRouteClass< I, O, B >::RemoveFromRouteList, mutaborGUI::GUIRouteBase::Replace, mutaborGUI::MutBoxChannelShape::Replace, mutaborGUI::MutDeviceShape< T >::Replace, mutabor::BoxClass::Replace, mutaborGUI::GUIOutputDeviceBase::Replace, mutaborGUI::GUIInputDeviceBase::Replace, mutabor::CommonTypedDeviceAPI< T, P, L >::Replace, mutaborGUI::NewMutBoxShape::replaceSelfBy, mutaborGUI::MutNewInputDeviceShape::replaceSelfBy, mutaborGUI::MutBoxShape::replaceSelfBy, mutaborGUI::MutDeviceShape< T >::replaceSelfBy, mutabor::channel_queue_template< unsigned char, 16 >::reserve_channel, mutabor::CommonFileOutputDevice::Save, mutabor::OutputGis::Save, mutabor::TRouteClass< I, O, B >::Save, mutabor::CommonFileInputDevice::Save, mutabor::InputGis::Save, mutabor::OutputMidiPort::Save, mutabor::InputMidiPort::Save, mutabor::OutputMidiFile::Save, mutabor::InputMidiFile::Save, mutabor::BoxFactory::SaveBoxes, mutabor::DeviceFactory::SaveInputDevices, mutabor::DeviceFactory::SaveOutputDevices, mutabor::TRouteClass< I, O, B >::SaveRoutes, mutabor::DebugMidiOutputProvider::SendSysEx, mutabor::BoxClass::set_routefile_id, mutaborGUI::MutBoxShape::SetBackgroundColour, mutaborGUI::MutaborBoxSettings::SetBoxNumber, mutaborGUI::BoxDlg::SetBoxNumber, mutaborGUI::BoxDlg::SetBoxType, mutaborGUI::MutFrame::SetClient, mutaborGUI::MutChild::SetClientSize, MutIconShapeClass< MutPanel >::SetLabel, mutaborGUI::MutSTCLexer::SetStyling, mutabor::InputMidiPort::shouldProceed, mutabor::InputMidiFile::shouldProceed, mutaborGUI::MutBoxShape::ShowBoxDialog, boxTest::testFindKeyByKey, mutaborGUI::MutFrame::TextBoxOpen, mutabor::CommonFileInputDevice::ThreadPlay, configtree::toFirstLeaf, mutaborGUI::MutFrame::ToggleTextBox, mutaborGUI::ToGUIBase, configtree::toLeaf, mutaborGUI::xmltree::toLeaf, configtree::toNextLeaf, configtree::toParent, mutaborGUI::xmltree::toParent, mutaborGUI::MutLogicWnd::UpDate, mutaborGUI::MutFrame::UpdateBoxMenu, mutabor::Track::UpdateDelta, mutabor::CommonFileInputDevice::WaitForDeviceFinish, mutabor::Track::WriteDelta, yylex, mutabor::CommonFileInputDevice::~CommonFileInputDevice, mutabor::CommonFileInputDevice::FileTimer::~FileTimer, mutaborGUI::MutChild::~MutChild, mutaborGUI::MutFrame::~MutFrame, mutaborGUI::MutLogicWnd::~MutLogicWnd, mutabor::TRouteClass< I, O, B >::~TRouteClass.
gettext_noop
Referenced by mutabor::timing_params::get_MIDI_tick_signature, mutabor::Track::ReadInt, mutabor::Track::ReadMessage, mutabor::Track::SendSysExCont, mutabor::timing_params::set_MIDI_tick_signature, mutabor::Track::WriteNumber.
MIDI_MIN_CHANNEL
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
MIDI_MAX_CHANNEL
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
MIDI_MIN_KEY
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
MIDI_MAX_KEY
Referenced by mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel.
N_
Referenced by mutabor::CommonFileOutputDevice::GetTypeName, mutabor::OutputGis::GetTypeName, mutabor::CommonFileInputDevice::GetTypeName, mutabor::InputGis::GetTypeName, mutabor::OutputMidiPort::GetTypeName, mutabor::Device::GetTypeName, mutabor::InputMidiPort::GetTypeName, mutabor::OutputMidiFile::GetTypeName, mutabor::InputMidiFile::GetTypeName, mutabor::OutputDeviceClass::GetTypeName, mutabor::InputDeviceClass::GetTypeName.
MU32_ERRORS_H
MU32_ERRORS_H_PRECOMPILED
MUT_ERR_MALLOC_FAILED
_
Referenced by mutaborGUI::RoutePanel::AddBox, BEGIN_EVENT_TABLE, mutaborGUI::BEGIN_EVENT_TABLE, berechne_intervall_endgueltig, berechne_intervalle_absolut, berechne_toene_absolut, berechne_ton_endgueltig, MutTextBox::BoxChangedAction, check_aktionen, check_ausloeser, check_komplex_intervall, check_konsistenz, OutputMidiFileTest::CheckOut, mutaborGUI::MutFrame::CloseAll, mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::CmFileOpen, mutaborGUI::MutConfigDialog::CmHelp, mutaborGUI::MutFrame::CmInDevPlay, mutaborGUI::MutRouteWnd::CmRouteLoad, mutaborGUI::MutFrame::CmRoutes, mutaborGUI::MutRouteWnd::CmRouteSave, mutaborGUI::MutRouteWnd::CmRouteSaveAs, mutaborGUI::MutFrame::CmSetTitle, mutaborGUI::MutEditFile::Compile, mutabor::BoxClass::Compile, mutaborGUI::MutNewInputDeviceShape::Create, mutaborGUI::MutNewOutputDeviceShape::Create, mutaborGUI::MutChild::deleteFromWinAttrs, mutaborGUI::MutEditFile::DoFind, mutaborGUI::MutBoxShape::DoLeftDblClick, mutaborGUI::MutEditFile::DoLoadFile, mutaborGUI::DontWant, mutaborGUI::MutEditFile::DoSaveFile, mutaborGUI::RouteRemoveButton::EnableRoute, END_EVENT_TABLE, execute_aktion, expand_aktions_liste, expand_harmony_analysis, expand_pattern, expand_tonliste, expandiere_logik, expandiere_midi, expandiere_name, expandiere_umstimmung, FileNameDialog, fprint_argument, generate_argument_list, get_ausloeser_taste, get_instrument_dekl, get_intervall_wert, get_komplex_faktor, get_logik_nummer, get_new_harmonie, get_new_intervall, get_new_intervall_komplex, get_new_logik, get_new_ton_absolut, get_new_ton_komplex_negative, get_new_ton_komplex_positive, get_new_tonsystem, get_new_tonsystem_negative, get_umstimmung_umstimm_case, get_umstimmung_umstimmungs_bund, get_umstimmung_wiederholung_abs_negative, get_wert_komplex_intervall, MutTextBox::GetKeys, mutabor::BoxClass::GetLabel, MutTextBox::GetToneSystem, mutabor::BoxClass::GetTypeName, IMPLEMENT_APP, IMPLEMENT_DYNAMIC_CLASS, init_umstimmung, mutaborGUI::BoxDlg::InitializeBoxTypes, mutaborGUI::NewMutBoxShape::InitializeDialog, mutaborGUI::MutBoxChannelShape::InitializeInputFilter, mutaborGUI::MutBoxChannelShape::InitializeOutputFilter, mutaborGUI::initMutBitmap, insert_in_globale_liste, insert_in_lokale_liste, intervall_nummer, mutaborGUI::IsOpen, mutaborGUI::IsWanted, link_arguments_to_parameters, mutabor::OutputMidiPort::Load, mutabor::InputMidiPort::Load, mutabor::OutputMidiFile::Load, mutabor::InputMidiFile::Load, local_harmony_analysis, mutaborGUI::MutFrame::LogicWinOpen, mutaborGUI::MutLogicWnd::MakeTitle, MutTextBox::MakeTitle, mutabor_error_type_to_string, mutAssertFailure, mutaborGUI::MutEditProperties::MutEditProperties, mutaborGUI::MutFrame::MutFrame, MutTextBox::OnClose, mutaborGUI::MutEditFile::OnFindDialog, mutaborGUI::MutEditFile::OnGoto, mutabor::MidiPortOutputProvider::Open, mutabor::InputGis::Open, mutabor::InputMidiPort::Open, mutabor::InputMidiFile::Open, mutabor::OpenAll, mutaborGUI::MutFrame::OpenFile, print_argumentliste, resolve_parameters, mutaborGUI::GUIRouteBase::runtime_error, mutaborGUI::BoxData::runtime_error, mutaborGUI::GUIOutputDeviceBase::runtime_error, mutaborGUI::GUIInputDeviceBase::runtime_error, compat30::SaveRoutes, mutaborGUI::MutBoxShape::SetBox, mutabor::OutputMidiPort::SetDevId, mutabor::InputMidiPort::SetDevId, mutaborGUI::StatusBar::SetInsert, switch, test_zyklen, test_zyklen_nummer, mutaborGUI::MutFrame::TextBoxOpen, mutaborGUI::MutFrame::ToggleTextBox, ton_nummer, u_test_zyklen, mutaborGUI::MutLogicWnd::UpDate, mutaborGUI::MutFrame::UpdateBoxMenu, mutaborGUI::InputDevDlg::UpdateLayout, MutTextBox::UpdateUI, xalloca, xcalloc, xmalloc, xrealloc, ymalloc, yyerror, yylex.
KEY_CHANGED
Referenced by AddKey, DeleteKey.
MU32_EXECUTE_H
MU32_EXECUTE_H_PRECOMPILED
MU32_FRAC_H
MU32_FRAC_H_PRECOMPILED
GERMAN
MU32_GLOBAL_H
MU32_GLOBAL_H_PRECOMPILED
bcopy
Referenced by yyparse.
bzero
bcmp
MUTABOR_KEYRANGE_MAX_WIDTH
Referenced by change_breite, expand_pattern, mutabor::BoxClass::GetToneSystem, mutabor_reset_box, mutabor_reset_keys, boxTest::test_init.
MUTABOR_KEYRANGE_MIN_KEY
Referenced by change_anker, check_konsistenz.
MUTABOR_KEYRANGE_MAX_KEY
Referenced by change_anker, check_konsistenz.
MAX_MIDI
MUTABOR_NO_KEY
Referenced by check_ausloeser, mutabor::BoxClass::GetCurrentTones, mutabor::BoxClass::GetToneSystem, local_harmony_analysis, switch.
MUTABOR_INVALID_KEY
Referenced by check_ausloeser, mutabor::BoxClass::GetCurrentTones, mutabor::BoxClass::GetToneSystem, insert_in_globale_liste, insert_in_lokale_liste, local_harmony_analysis.
LINE_DRAW_QUANTUM
#define MAXLINE_ton_system 18 define MAXLINE_AKTIONEN 18
Referenced by yylex.
_
OFFSET
Referenced by xmalloc.
MU32_Hilfs_H
MU32_Hilfs_H_PRECOMPILED
HEAP_PORTION_SYNTAX
Referenced by xmalloc, xrealloc.
HEAP_PORTION_LAUFZEIT
MU32_INTERPRE_H
MU32_INTERPRE_H_PRECOMPILED
SYNTHESIZER_TYP_KEINER
SYNTHESIZER_TYP_FB01
SYNTHESIZER_TYP_MULTI16
SYNTHESIZER_TYP_GIS
_
adjazent
Referenced by berechne_intervalle_absolut, test_zyklen.
MU32_INTERVAL_H
MU32_INTERVAL_H_PRECOMPILED
HEADERFILENAME
HEADERFILENAME_PRECOMPILED
yyFlexLexer
YY_DECL
_
SRC_KERNEL_PARSER_H
SRC_KERNEL_PARSER_H_PRECOMPILED
MUTABOR_NO_CASE_LABEL
Referenced by get_umstimmungs_case_default_element.
mutabor_adjacent
Referenced by berechne_toene_absolut, test_zyklen.
mutabor_u_adjacent
Referenced by check_konsistenz, u_test_zyklen.
_
SRC_KERNEL_TABGEN_H
SRC_KERNEL_TABGEN_H_PRECOMPILED
SRC_WXINTL_LIBINTL
SRC_WXINTL_LIBINTL_PRECOMPILED
wxwidgets_gettext
Referenced by wxwidgets_dgettext, wxwidgets_dngettext, wxwidgets_sgettext, wxwidgets_sngettext.
wxwidgets_ngettext