mutaborGUI::StatusBar
playstate
StatusBarSections
wxStaticText* mutaborGUI::StatusBar::insertStatus
Referenced by PositionElements, SetInsert.
wxStaticBitmap* mutaborGUI::StatusBar::active
Referenced by PositionElements, SetActive.
wxStaticBitmap * mutaborGUI::StatusBar::play
Referenced by PositionElements, SetPlaystate.
wxBitmap* mutaborGUI::StatusBar::playbmp
Referenced by SetPlaystate.
int mutaborGUI::StatusBar::line
Referenced by SetPosition.
int mutaborGUI::StatusBar::column
Referenced by SetPosition.
playstate mutaborGUI::StatusBar::lastprocessed
Referenced by HandlePlaystateChanged, SendPlaystateChanged.
mutaborGUI::StatusBar::StatusBar(wxWindow *parent, wxWindowID id=wxID_ANY, long style=wxST_SIZEGRIP, const wxString &name=_T("statusBar"))
References Create.
bool mutaborGUI::StatusBar::Create(wxWindow *parent, wxWindowID id=wxID_ANY, long style=wxST_SIZEGRIP, const wxString &name=_T("statusBar"))
References countStatusbarRegions, mutaborGUI::StatusBarBitmaps::Init.
Referenced by StatusBar.
void mutaborGUI::StatusBar::SetActive(bool act)
References mutaborGUI::StatusBarBitmaps::Active, active, PositionElements.
Referenced by AllSetActive, mutaborGUI::MutFrame::OnCreateStatusBar.
void mutaborGUI::StatusBar::HandlePlaystateChanged(wxCommandEvent &event)
References AllSetPlaystate, lastprocessed.
void mutaborGUI::StatusBar::SetPlaystate(playstate pst)
References Hide, Pause, mutaborGUI::StatusBarBitmaps::Pause, Play, mutaborGUI::StatusBarBitmaps::Play, play, playbmp, PositionElements, Stop, mutaborGUI::StatusBarBitmaps::Stop, UNREACHABLEC.
Referenced by AllDoSetPlaystate, mutaborGUI::MutFrame::OnCreateStatusBar.
static void mutaborGUI::StatusBar::SetInsert(wxWindow *win, bool status)
References _, GetStatusBar, insertStatus, PositionElements.
Referenced by mutaborGUI::MutEditFile::MutEditFile, mutaborGUI::MutEditFile::OnSetOverType.
static void mutaborGUI::StatusBar::SetPosition(wxWindow *win, int line, int column)
References column, GetStatusBar, line, StatusbarLineNo.
Referenced by mutaborGUI::MutEditFile::OnUpdateStcUI.
static void mutaborGUI::StatusBar::AllSetActive(bool active)
References SetActive.
Referenced by mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::DoStop.
static void mutaborGUI::StatusBar::SendPlaystateChanged(playstate pst=Stop)
References mutaborGUI::CM_PLAYSTATE_CHANGED, lastprocessed, Play, Stop.
static void mutaborGUI::StatusBar::AllSetPlaystate(playstate pst=Stop, bool force=false)
References AllDoSetPlaystate, GetCurrentPlayState, Hide, Pause, Play, Stop, UNREACHABLECT.
Referenced by mutaborGUI::MutFrame::CmDoActivate, mutaborGUI::MutFrame::CmInDevPause, mutaborGUI::MutFrame::CmInDevPlay, mutaborGUI::MutFrame::DoStop, HandlePlaystateChanged, mutaborGUI::MutFrame::StopInDev.
static StatusBar* mutaborGUI::StatusBar::GetStatusBar(wxWindow *win)
Referenced by SetInsert, SetPosition.
static void mutaborGUI::StatusBar::AllDoSetPlaystate(playstate pst)
References SetPlaystate.
Referenced by AllSetPlaystate.
StatusBar::playstate mutaborGUI::StatusBar::GetCurrentPlayState()
References mutabor::DeviceCompileError, mutabor::DevicePause, mutabor::DevicePlay, mutabor::DeviceStop, mutabor::DeviceTimingError, mutabor::DeviceUnregistered, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList, Pause, Play, Stop.
Referenced by AllSetPlaystate.
void mutaborGUI::StatusBar::OnSize(wxSizeEvent &event)
void mutaborGUI::StatusBar::PositionElements()
References active, countStatusbarRegions, DEBUGLOG, insertStatus, play, StatusbarInsert, StatusbarLineNo, StatusbarLogicActive, StatusbarPlayback, StatusbarSizeGrip.
Referenced by SetActive, SetInsert, SetPlaystate.