mutabor::InputMidiFile
typedef CommonMidiInput<CommonFileInputDevice> mutabor::InputMidiFile::base
friend class MidiFileFactory
int mutabor::InputMidiFile::FileType
TrackList mutabor::InputMidiFile::Tracks
mutint64 mutabor::InputMidiFile::minDelta
bool mutabor::InputMidiFile::Busy
timing_params mutabor::InputMidiFile::timing
mutabor::InputMidiFile::InputMidiFile()
mutabor::InputMidiFile::InputMidiFile(std::string name, MutaborModeType mode, int id)
mutint64 mutabor::InputMidiFile::ReadMidiProceed(size_t nr, mutint64 time)
References mutabor::create_event, DEBUGLOG, mutabor::set_tempo_event::get_tempo, mutabor::midi::META, mutabor::midi::META_END_OF_TRACK, mutabor::midi::META_SET_TEMPO, MUTABOR_NO_DELTA, mutASSERT, mutint64.
virtual mutabor::InputMidiFile::~InputMidiFile()
void mutabor::InputMidiFile::Save(tree_storage &config, const RouteClass *route)
Save route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route ) Route whos data shall be saved.Noch zu erledigen: check for array borders Some route settings (e.g. filter settings) are device type specific. This function saves them in a tree storage. config (tree_storage *) Storage class, where the data will be saved. route (Route) Route whos data shall be saved.
References mutabor::TRouteClass< I, O, B >::GetInputFrom, mutabor::TRouteClass< I, O, B >::GetInputTo, mutabor::tree_storage::GetPath, mutabor::TRouteClass< I, O, B >::GetType, mutASSERT, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent, mutabor::tree_storage::Write.
void mutabor::InputMidiFile::Load(tree_storage &config, RouteClass *route)
Loade route settings (filter settings) for a given route.
Some route settings (e.g. filter settings) are device type specific. This function loads them from a tree storage. config (tree_storage *) Storage class, where the data will be restored from. route (Route ) Route whos data shall be loaded.
References _mut, mutabor::tree_storage::GetPath, mutabor::TRouteClass< I, O, B >::GetType, mutASSERT, mutabor::tree_storage::Read, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, mutabor::hidden::runtime_error, mutabor::TRouteClass< I, O, B >::SetInputFrom, mutabor::TRouteClass< I, O, B >::SetInputTo, mutabor::str, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent, mutabor::hidden::warning.
bool mutabor::InputMidiFile::Open()
References _mut, DEBUGLOG, mutabor::DeviceCompileError, mutabor::hidden::error, mutASSERT, mutabor::ReadLength, mutabor::hidden::runtime_error, mutabor::str.
Referenced by myDevice::Open.
void mutabor::InputMidiFile::Close()
References mutabor::DeviceCompileError.
Referenced by myDevice::Close, OutputMidiFileTest::testBatchPlay1.
void mutabor::InputMidiFile::Stop()
Stop playback or recording of the device.
References mutabor::DeviceCompileError, MUTABOR_NO_DELTA.
Referenced by myDevice::Stop.
virtual frac mutabor::InputMidiFile::ReadOn(frac time)
virtual DevType mutabor::InputMidiFile::GetType() const
References mutabor::DTMidiFile.
mutint64 mutabor::InputMidiFile::PrepareNextEvent()
Go on to the next event.
This function must be provided by the device. It advices it to prepare the next event and return the time frame in milliseconds from the start of the piece.mutint64 Temporal position of the next event in the piece.
References DEBUGLOG, MUTABOR_NO_DELTA, mutint64.
virtual int mutabor::InputMidiFile::GetMaxChannel() const
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
virtual int mutabor::InputMidiFile::GetMinChannel() const
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
virtual int mutabor::InputMidiFile::GetMaxTrack() const
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
virtual int mutabor::InputMidiFile::GetMinTrack() const
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
virtual std::string mutabor::InputMidiFile::GetTypeName() const
References _mutN.
mutabor::InputMidiFile::operator std::string() const
References mutabor::str.
InputMidiFile::proceed_bool mutabor::InputMidiFile::shouldProceed(Route R, const std::vector< unsigned char > *midiCode, int data=0)
References mutASSERT, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, UNREACHABLEC.
void mutabor::InputMidiFile::Proceed(const std::vector< unsigned char > *midiCode, int data=0, int channel_offset=0)
References mutabor::midi::ACTIVE_SENSE, mutabor::OutputDeviceClass::all_handle_event, mutabor::midi::CLOCK, mutabor::midi::CONTINUE_PLAY, mutabor::create_event, DEBUGLOG, mutabor::midi::META, mutabor::midi::QUARTER_FRAME, mutabor::midi::REALTIME_UNDEFINED, mutabor::midi::SONG_POSITION, mutabor::midi::SONG_SELECT, mutabor::midi::START_PLAY, mutabor::midi::STOP_PLAY, mutabor::midi::SYSEX_END, mutabor::midi::SYSEX_START, mutabor::midi::SYSTEM_UNDEFINED1, mutabor::midi::SYSTEM_UNDEFINED2, mutabor::midi::TICK, mutabor::midi::TUNE_REQUEST.