GUIroute
typedef std::list< MutBoxShape * > mutaborGUI::MutBoxShapeList
typedef mutabor::InputDevice mutaborGUI::inputdevicetypes::Device
typedef mutabor::InputDeviceClass mutaborGUI::inputdevicetypes::DeviceClass
typedef GUIInputDeviceBase mutaborGUI::inputdevicetypes::GUIDeviceBase
typedef InputDevDlg mutaborGUI::inputdevicetypes::DeviceDialog
typedef InputFilterPanel mutaborGUI::inputdevicetypes::FilterPanel
typedef mutabor::OutputDevice mutaborGUI::outputdevicetypes::Device
typedef mutabor::OutputDeviceClass mutaborGUI::outputdevicetypes::DeviceClass
typedef GUIOutputDeviceBase mutaborGUI::outputdevicetypes::GUIDeviceBase
typedef OutputDevDlg mutaborGUI::outputdevicetypes::DeviceDialog
typedef OutputFilterPanel mutaborGUI::outputdevicetypes::FilterPanel
typedef T::Device mutaborGUI::MutDeviceShape< T >::devicetype
typedef T::DeviceClass mutaborGUI::MutDeviceShape< T >::DeviceClass
typedef T::GUIDeviceBase mutaborGUI::MutDeviceShape< T >::GUIDeviceBase
typedef T::DeviceDialog mutaborGUI::MutDeviceShape< T >::DeviceDialog
typedef T::FilterPanel mutaborGUI::MutDeviceShape< T >::FilterPanel
typedef MutDeviceShape<T> mutaborGUI::MutDeviceShape< T >::thistype
typedef std::map<wxString *, MutDeviceShape *, strptrless> mutaborGUI::MutDeviceShape< T >::stringmaptype
typedef stringmaptype::iterator mutaborGUI::MutDeviceShape< T >::stringmapiterator
typedef MutDeviceShape< inputdevicetypes > mutaborGUI::MutInputDeviceShape
typedef std::list< MutInputDeviceShape * > mutaborGUI::MutInputDeviceShapeList
typedef MutDeviceShape< outputdevicetypes > mutaborGUI::MutOutputDeviceShape
typedef std::list< MutOutputDeviceShape * > mutaborGUI::MutOutputDeviceShapeList
typedef GisOutputFilterPanelBase mutaborGUI::GisOutputFilterPanel
friend class GUIRouteFactory
friend class GUIGisFactory
friend class GUIMidiFileFactory
friend class GUIGisFactory
friend class GUIMidiPortFactory
friend class GUIMidiFileFactory
mutabor::Route mutaborGUI::MutBoxChannelShape::route
Referenced by mutaborGUI::MutBoxChannelShape::GetGUIRoute, mutaborGUI::MutBoxChannelShape::GetRoute, mutaborGUI::MutBoxChannelShape::InitializeInputFilter, mutaborGUI::MutBoxChannelShape::InitializeOutputFilter, mutaborGUI::MutBoxChannelShape::InitializeRoute.
MutInputDeviceShape* mutaborGUI::MutBoxChannelShape::input
Referenced by mutaborGUI::MutBoxChannelShape::GetInput, mutaborGUI::MutBoxChannelShape::InitializeInputFilter.
MutOutputDeviceShape* mutaborGUI::MutBoxChannelShape::output
Referenced by mutaborGUI::MutBoxChannelShape::GetOutput, mutaborGUI::MutBoxChannelShape::InitializeOutputFilter.
MutBoxIconShape* mutaborGUI::MutBoxShape::m_icon
Referenced by mutaborGUI::NewMutBoxShape::Create, mutaborGUI::MutBoxShape::Create.
wxSizer* mutaborGUI::MutBoxShape::channels
Referenced by mutaborGUI::MutBoxShape::Detach, mutaborGUI::MutBoxShape::GetChannels.
mutabor::Box mutaborGUI::MutBoxShape::box
Referenced by mutaborGUI::MutBoxShape::Add, mutaborGUI::MutBoxShape::DoLeftDblClick, mutaborGUI::MutBoxShape::GetBox, mutaborGUI::MutBoxShape::MoveBox, mutaborGUI::MutBoxShape::Remove, mutaborGUI::MutBoxShape::Replace, mutaborGUI::MutBoxShape::SetBox.
wxSizerFlags mutaborGUI::MutBoxShape::sizerFlags
Referenced by mutaborGUI::MutBoxShape::GetSizerFlags, mutaborGUI::MutBoxShape::SetSizerFlags.
mutaborGUI::MutIconShape
outputdevicetypes template class mutaborGUI::MutDeviceShape< inputdevicetypes >
MutBoxChannelShapeList mutaborGUI::MutDeviceShape< T >::routes
Referenced by mutaborGUI::MutDeviceShape< T >::GetChannels, mutaborGUI::MutDeviceShape< T >::MoveRoutes.
devicetype mutaborGUI::MutDeviceShape< T >::device
Referenced by mutaborGUI::MutDeviceShape< T >::Add, mutaborGUI::MutDeviceShape< T >::DoLeftDblClick, mutaborGUI::MutDeviceShape< T >::GetDevice, mutaborGUI::MutDeviceShape< T >::GetGUIDevice, mutaborGUI::MutDeviceShape< T >::getRoutes, mutaborGUI::MutDeviceShape< T >::MoveDevice, mutaborGUI::MutDeviceShape< T >::Remove, mutaborGUI::MutDeviceShape< T >::Replace, mutaborGUI::MutDeviceShape< T >::replaceSelfBy.
wxSizer* mutaborGUI::MutDeviceShape< T >::playbuttons
wxSizerFlags mutaborGUI::MutDeviceShape< T >::sizerFlags
Referenced by mutaborGUI::MutDeviceShape< T >::GetSizerFlags, mutaborGUI::MutDeviceShape< T >::SetSizerFlags.
wxFileName mutaborGUI::MutInputGuidoFileDeviceShape::fileName
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::SetLabel.
wxFileName mutaborGUI::MutInputMidiFileDeviceShape::fileName
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::SetLabel.
mutabor::DevType mutaborGUI::OutputDevDlg::TypeData::nr
Referenced by mutaborGUI::OutputDevDlg::TypeData::operator mutabor::DevType, mutaborGUI::OutputDevDlg::TypeData::operator==, mutaborGUI::OutputDevDlg::TypeData::TypeData.
wxFileName mutaborGUI::MutOutputGuidoFileDeviceShape::fileName
Referenced by mutaborGUI::MutOutputGuidoFileDeviceShape::SetLabel.
wxFileName mutaborGUI::MutOutputMidiFileDeviceShape::fileName
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::SetLabel.
MutIcon mutaborGUI::DevUnknownBitmap
Referenced by mutaborGUI::initMutIcon, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::MidiInputDevBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::Create, mutaborGUI::MutInputMidiDeviceShape::GetMutIcon, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::NewInputDevBitmap
Referenced by mutaborGUI::MutNewInputDeviceShape::GetMutIcon, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::MidiOutputDevBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::Create, mutaborGUI::MutOutputMidiDeviceShape::GetMutIcon, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::NewOutputDevBitmap
Referenced by mutaborGUI::MutNewOutputDeviceShape::GetMutIcon, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::MidiFileBitmap
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::GetMutIcon, mutaborGUI::MutInputMidiFileDeviceShape::GetMutIcon, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::GuidoFileBitmap
Referenced by mutaborGUI::MutOutputGuidoFileDeviceShape::GetMutIcon, mutaborGUI::MutInputGuidoFileDeviceShape::GetMutIcon, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::BoxBitmap
Referenced by mutaborGUI::MutBoxIconShape::GetMutIcon, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::NewBoxBitmap
Referenced by mutaborGUI::IMPLEMENT_CLASS, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::ActiveChannelBitmap
Referenced by mutaborGUI::MutBoxChannelShape::GetMutIcon, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::PassiveChannelBitmap
Referenced by mutaborGUI::MutBoxChannelShape::GetMutIcon, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::DevicePlayBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::createPlayButtons, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::DevicePauseBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::createPauseButton, mutaborGUI::MutDeviceShape< T >::createPlayButtons, mutaborGUI::MutDeviceShape< T >::createRecordButtons, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::DeviceStopBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::createPlayButtons, mutaborGUI::MutDeviceShape< T >::createRecordButtons, mutaborGUI::initMutIconShapes.
MutIcon mutaborGUI::DeviceRecordBitmap
Referenced by mutaborGUI::MutDeviceShape< T >::createRecordButtons, mutaborGUI::initMutIconShapes.
IMPLEMENT_DYNAMIC_CLASS(MutRouteWnd, wxScrolledWindow) BEGIN_EVENT_TABLE(MutRouteWnd
wxScrolledWindow EVT_MENU(CM_MOVE_UP, MutRouteWnd::OnMoveShape) EVT_MENU(CM_MOVE_DOWN
mutaborGUI::BEGIN_EVENT_TABLE(MutBoxChannelShape, MutIconShape) EVT_LEFT_DCLICK(MutBoxChannelShape
References DEBUGLOG, MutIconShapeClass< T >::GotFocus.
MutIcon & mutaborGUI::MutBoxChannelShape::GetMutIcon()
Calculates the Icon to be used.
References mutaborGUI::ActiveChannelBitmap, DEBUGLOG, mutASSERT, mutaborGUI::PassiveChannelBitmap.
mutaborGUI::MutBoxChannelShape::MutBoxChannelShape(wxWindow *p=NULL, wxWindowID id=wxID_ANY, mutabor::Route r=NULL)
Constructor.
Constructor for MutBoxChannelShape. This function constructs a window via Create(), which calles the corresponding attatch function.
References mutaborGUI::MutBoxChannelShape::Create.
mutaborGUI::MutBoxChannelShape::~MutBoxChannelShape()
virtual bool mutaborGUI::MutBoxChannelShape::AcceptsFocus() const
bool mutaborGUI::MutBoxChannelShape::Destroy()
References MutIconShapeClass< T >::Destroy.
bool mutaborGUI::MutBoxChannelShape::Create(wxWindow *p=NULL, wxWindowID id=wxID_ANY, mutabor::Route r=NULL)
Create the window.
This function does the work of window creation and connects to the underlying route if necessary. It will complain if a route is already attached to the channel shape. wxWindow * p parent window wxWindowId id id of the shape Route r Route of the undelying Mutabor engine. true if everything is ok false if an error has occured
References mutabor::connect, MutIconShapeClass< T >::Create, mutASSERT, UNREACHABLEC.
Referenced by mutaborGUI::MutBoxChannelShape::MutBoxChannelShape.
virtual void mutaborGUI::MutBoxChannelShape::GotFocus()
void mutaborGUI::MutBoxChannelShape::LostFocus()
void mutaborGUI::MutBoxChannelShape::LeftDblClickEvent(wxMouseEvent &event)
void mutaborGUI::MutBoxChannelShape::Add(MutOutputDeviceShape *out)
add a new output device
References UNREACHABLEC.
Referenced by mutaborGUI::MutBoxShape::Add, mutaborGUI::GUIOutputDeviceBase::Add, mutaborGUI::GUIInputDeviceBase::Add, mutaborGUI::connect, mutaborGUI::connect_device_shape, mutaborGUI::MutRouteWnd::createRoutes.
void mutaborGUI::MutBoxChannelShape::Add(MutInputDeviceShape *in)
add a new input device
References TRACEC, UNREACHABLEC.
void mutaborGUI::MutBoxChannelShape::Add(mutabor::Route &r)
add a new route
References DEBUGLOG, UNREACHABLEC.
virtual void mutaborGUI::MutBoxChannelShape::Add(MutBoxShape *box)
add a new box shape
bool mutaborGUI::MutBoxChannelShape::Replace(MutOutputDeviceShape *olddev, MutOutputDeviceShape *newdev)
replace an existing output device
References UNREACHABLEC.
bool mutaborGUI::MutBoxChannelShape::Replace(MutInputDeviceShape *olddev, MutInputDeviceShape *newdev)
replace an existing input device
References mutASSERT, TRACEC.
bool mutaborGUI::MutBoxChannelShape::Replace(mutabor::Route &oldroute, mutabor::Route &newroute)
replace an existing route
References DEBUGLOG, mutASSERT.
virtual bool mutaborGUI::MutBoxChannelShape::Replace(MutBoxShape *oldbox, MutBoxShape *newbox)
replace a box shape
bool mutaborGUI::MutBoxChannelShape::Remove(MutOutputDeviceShape *out)
replace an existing output device
remove an existing output device
References UNREACHABLEC.
Referenced by mutaborGUI::disconnect, mutaborGUI::GUIOutputDeviceBase::Remove, mutaborGUI::GUIInputDeviceBase::Remove.
bool mutaborGUI::MutBoxChannelShape::Remove(MutInputDeviceShape *in)
replace an existing input device
remove an existing input device
References TRACEC, UNREACHABLEC.
bool mutaborGUI::MutBoxChannelShape::Remove(mutabor::Route &r)
remove a Route
remove an attatched route
References DEBUGLOG, UNREACHABLEC.
virtual bool mutaborGUI::MutBoxChannelShape::Remove(MutBoxShape *box)
remove a box from the route shape
mutabor::Route& mutaborGUI::MutBoxChannelShape::GetRoute() const
References mutaborGUI::MutBoxChannelShape::route.
Referenced by mutaborGUI::MutRouteWnd::AddRoute, mutaborGUI::Check, mutaborGUI::connect, mutaborGUI::MutBoxShape::DeleteBox, mutaborGUI::disconnect, mutaborGUI::MutBoxShape::HasChannel, mutaborGUI::MutDeviceShape< T >::ReadPanel, mutaborGUI::reconnect.
const MutInputDeviceShape* mutaborGUI::MutBoxChannelShape::GetInput() const
References mutaborGUI::MutBoxChannelShape::input.
Referenced by mutaborGUI::Check.
MutInputDeviceShape* mutaborGUI::MutBoxChannelShape::GetInput()
References mutaborGUI::MutBoxChannelShape::input.
const MutOutputDeviceShape* mutaborGUI::MutBoxChannelShape::GetOutput() const
References mutaborGUI::MutBoxChannelShape::output.
Referenced by mutaborGUI::Check.
MutOutputDeviceShape* mutaborGUI::MutBoxChannelShape::GetOutput()
References mutaborGUI::MutBoxChannelShape::output.
GUIRoute* mutaborGUI::MutBoxChannelShape::GetGUIRoute() const
References mutaborGUI::MutBoxChannelShape::route.
void mutaborGUI::MutBoxChannelShape::CreateRoutePanel(MutBoxChannelShape *channel, MutRouteWnd *parentwin, wxWindow *routeWindow, const mutabor::Box &box)
References mutaborGUI::RouteRemoveButton::EnableRoute, mutaborGUI::RoutePanel::SetChannel, mutaborGUI::RoutePanel::SetInput, mutaborGUI::RoutePanel::SetOutput, UNREACHABLECT.
void mutaborGUI::MutBoxChannelShape::InitializeInputFilter(InputFilterPanel *panel, MutRouteWnd *par, MutBoxChannelShape *shape=NULL)
References _, mutaborGUI::InputFilterPanel::AddPage, DEBUGLOGTYPE, mutaborGUI::InputFilterPanel::GetInputDeviceBook, mutaborGUI::MutRouteWnd::GetInputDevices, mutaborGUI::MutBoxChannelShape::input, intrusive_ptr_get_refcount, mutASSERT, mutaborGUI::MutBoxChannelShape::route, TRACET.
void mutaborGUI::MutBoxChannelShape::InitializeRoute(RoutePanel *panel, MutRouteWnd *par, MutBoxChannelShape *shape=NULL, mutabor::Box b=NULL)
References mutaborGUI::RoutePanel::AddBox, DEBUGLOGTYPE, mutabor::BoxClass::GetBoxList, mutASSERT, mutaborGUI::MutBoxChannelShape::route, mutaborGUI::RoutePanel::SetActive.
void mutaborGUI::MutBoxChannelShape::InitializeOutputFilter(OutputFilterPanel *panel, MutRouteWnd *par, MutBoxChannelShape *shape=NULL)
References _, DEBUGLOGTYPE, mutaborGUI::OutputFilterPanel::GetOutputDeviceBook, mutaborGUI::MutRouteWnd::GetOutputDevices, mutASSERT, mutaborGUI::MutBoxChannelShape::output, mutaborGUI::MutBoxChannelShape::route.
void mutaborGUI::MutBoxChannelShape::ReadPanel(RoutePanel *panel)
References mutabor::connect, mutaborGUI::DebugCheckRoutes, DEBUGLOG, mutabor::disconnect, mutaborGUI::RoutePanel::GetActive, mutaborGUI::RoutePanel::GetBox, mutaborGUI::InputFilterPanel::GetCurrentSelection, mutaborGUI::OutputFilterPanel::GetCurrentSelection, mutaborGUI::RoutePanel::GetInput, mutaborGUI::RoutePanel::GetOutput, mutaborGUI::BoxData::GetShape, mutASSERT, mutabor::reconnect, mutaborGUI::ToGUIBase, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::MutBoxShape::AddChannel.
void mutaborGUI::MutBoxChannelShape::DrawLines(wxGraphicsContext &dc, wxWindow *paintingWindow, const wxPoint &origin) const
References mutASSERT.
Referenced by mutaborGUI::MutBoxShape::DrawLines.
wxPoint mutaborGUI::MutBoxChannelShape::GetPerimeterPoint(const wxPoint &i, const wxPoint &o, wxWindow *paintingWindow) const
References DEBUGLOG, mutASSERT.
void mutaborGUI::MutBoxChannelShape::DrawPerimeterPoint(wxDC &dc, const wxPoint &center, wxPoint p) const
References mutASSERT, mutUnused.
void mutaborGUI::MutBoxChannelShape::Refresh(bool eraseBackground=true, const wxRect *rect=NULL)
void mutaborGUI::MutBoxChannelShape::DetachChannel()
Detaches the channel from a box shape.
This function detaches a channel from its containing Box. The shape is not deteted.
References mutabor::disconnect.
void mutaborGUI::MutBoxChannelShape::DeleteRoute()
mutaborGUI::MutBoxIconShape::MutBoxIconShape()
mutaborGUI::MutBoxIconShape::MutBoxIconShape(wxWindow *parent, wxWindowID id=wxID_ANY)
References mutaborGUI::MutBoxIconShape::Create.
virtual mutaborGUI::MutBoxIconShape::~MutBoxIconShape()
bool mutaborGUI::MutBoxIconShape::Create(wxWindow *parent=NULL, wxWindowID id=wxID_ANY)
References MutIconShapeClass< T >::Create.
Referenced by mutaborGUI::MutBoxShape::Create, mutaborGUI::MutBoxIconShape::MutBoxIconShape.
virtual bool mutaborGUI::MutBoxIconShape::SetForegroundColour(const wxColour &colour)
References MutIconShapeClass< MutPanel >::staticText.
void mutaborGUI::MutBoxIconShape::GetBordersForSizer(int &borderTop, int &borderOther) const
References DEBUGLOG, MutIconShapeClass< MutPanel >::DoGetBestSize.
void mutaborGUI::MutBoxIconShape::OnDraw(wxPaintDC &dc)
References MutIconShapeClass< MutPanel >::borderOffset, DEBUGLOG, MutIconShapeClass< MutPanel >::GetIcon, mutaborGUI::MutBoxIconShape::GetMutIcon, MutIconShapeClass< MutPanel >::maxBorderSize, MutIconShapeClass< MutPanel >::SetIcon, MutIconShapeClass< MutPanel >::staticText.
bool mutaborGUI::MutBoxIconShape::Layout()
References MutIconShapeClass< MutPanel >::borderOffset, MutIconShapeClass< MutPanel >::staticText, TRACEC.
Referenced by mutaborGUI::MutRouteWnd::AddBox, mutaborGUI::MutBoxShape::DoLeftDblClick.
MutIcon& mutaborGUI::MutBoxIconShape::GetMutIcon()
Calculates the Icon to be used.
References mutaborGUI::BoxBitmap, mutASSERT.
Referenced by mutaborGUI::MutBoxIconShape::OnDraw.
static wxSize mutaborGUI::GetStaticBoxSize(MutBoxIconShape *box)
References DEBUGLOGTYPE, MutIconShapeClass< T >::DoGetBestSize, mutASSERT.
mutaborGUI::IMPLEMENT_CLASS(MutBoxShape, MutBoxIconShape) BEGIN_EVENT_TABLE(MutBoxShape
mutaborGUI::MutBoxShape::MutBoxShape()
mutaborGUI::MutBoxShape::MutBoxShape(wxWindow *parent, wxWindowID wid, mutabor::Box &b)
References mutaborGUI::MutBoxShape::Create.
virtual mutaborGUI::MutBoxShape::~MutBoxShape()
bool mutaborGUI::MutBoxShape::Create(wxWindow *parent, wxWindowID wid)
References mutaborGUI::MutBoxIconShape::Create, mutaborGUI::MutBoxShape::m_icon.
Referenced by mutaborGUI::NewMutBoxShape::Create, mutaborGUI::MutBoxShape::MutBoxShape.
bool mutaborGUI::MutBoxShape::Create(wxWindow *parent, wxWindowID wid, mutabor::Box &b)
static void mutaborGUI::MutBoxShape::SetSizerFlags(wxSizerFlags flags)
References mutaborGUI::MutBoxShape::sizerFlags.
static const wxSizerFlags& mutaborGUI::MutBoxShape::GetSizerFlags()
References mutaborGUI::MutBoxShape::sizerFlags.
void mutaborGUI::MutBoxShape::DoLeftDblClick()
References _, mutaborGUI::MutBoxShape::box, mutabor::Box0, mutabor::BoxFactory::Create, mutaborGUI::DebugCheckRoutes, MutIconShapeClass< T >::Fit, mutabor::BoxClass::GetBox, mutaborGUI::BoxDlg::GetBoxNumber, mutaborGUI::BoxDlg::GetBoxType, mutabor::BoxClass::IDTypeFile, mutaborGUI::MutBoxIconShape::Layout, mutaborGUI::LogicOn, mutASSERT, mutaborGUI::MutBoxShape::readDialog, TRACE, UNREACHABLEC.
Referenced by mutaborGUI::MutBoxShape::CmLeftDblClick.
void mutaborGUI::MutBoxShape::GotFocus()
References mutaborGUI::SetCurrentBox.
bool mutaborGUI::MutBoxShape::SetBackgroundColour(const wxColour &colour)
References mutASSERT.
void mutaborGUI::MutBoxShape::CmMoveIcon(wxCommandEvent &event)
Move the box in the box list and update the GUI according to the new order.
Move the box in the box and update the GUI according to the new order.This function provides the event handler that is called from the GUI. event wxCommandEvent containing the request event wxCommandEvent containing the request
References UNREACHABLEC.
void mutaborGUI::MutBoxShape::LeftDblClickEvent(wxMouseEvent &event)
Get a double click and prepare for execution of the command.
Since programs might produce segmentation faults when the object is deleted during processing of mouse events, we send us a new event using the event queue.
References mutaborGUI::CM_LEFT_DOUBLE_CLICK.
void mutaborGUI::MutBoxShape::CmLeftDblClick(wxCommandEvent &event)
Process a double click.
Since programs might produce segmentation faults when the object is deleted during processing of mouse events, we send us a new event using the event queue.
References mutaborGUI::MutBoxShape::DoLeftDblClick, mutUnused.
void mutaborGUI::MutBoxShape::OnKeyDown(wxKeyEvent &event)
BoxDlg * mutaborGUI::MutBoxShape::ShowBoxDialog() const
Constructs the box configuration dialog.
Noch zu erledigenuse value unknown for dynamic dialog creation
References mutaborGUI::BoxDlg::GetRouteWindow, mutASSERT.
void mutaborGUI::MutBoxShape::InitializeDialog(BoxDlg *dlg) const
References mutabor::Box0, mutabor::BoxClass::GetNextFreeBox, mutASSERT, mutabor::NoBox, mutaborGUI::BoxDlg::SetBoxNumber, mutaborGUI::BoxDlg::SetBoxType.
MutBoxChannelShape * mutaborGUI::MutBoxShape::AddChannel(RoutePanel *panel)
References mutabor::connect, mutabor::RouteFactory::Create, mutabor::hidden::GetChannels, mutASSERT, mutaborGUI::MutBoxChannelShape::ReadPanel.
virtual void mutaborGUI::MutBoxShape::Add(mutabor::Box &b)
add a box
References mutaborGUI::MutBoxShape::box, mutaborGUI::MutBoxShape::SetBox, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::GUIRouteBase::Add, mutaborGUI::MutRouteWnd::AddRoute, mutaborGUI::connect, mutaborGUI::connect_device_shape.
virtual bool mutaborGUI::MutBoxShape::Replace(mutabor::Box oldbox, mutabor::Box newbox)
replace a box
References mutaborGUI::MutBoxShape::box, mutaborGUI::MutBoxShape::SetBox, TRACEC, UNREACHABLEC.
virtual bool mutaborGUI::MutBoxShape::Remove(mutabor::Box b)
remove a box
References mutaborGUI::MutBoxShape::box, mutaborGUI::MutBoxShape::SetBox, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::disconnect.
MutBoxChannelShape * mutaborGUI::MutBoxShape::Add(MutBoxChannelShape *channel)
References mutaborGUI::MutBoxChannelShape::Add, DEBUGLOG, mutASSERT.
bool mutaborGUI::MutBoxShape::Remove(MutBoxChannelShape *shape)
bool mutaborGUI::MutBoxShape::HasChannel(const mutabor::Route &route)
References mutaborGUI::MutBoxChannelShape::GetRoute, mutASSERT.
void mutaborGUI::MutBoxShape::AddPossibleOutput(MutOutputDeviceShape *device)
References mutabor::connect, mutASSERT.
void mutaborGUI::MutBoxShape::DrawLines(wxGraphicsContext &dc, wxWindow *paintingWindow, const wxPoint &origin)
References DEBUGLOG, mutaborGUI::MutBoxChannelShape::DrawLines, mutASSERT, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::MutRouteWnd::OnDraw.
bool mutaborGUI::MutBoxShape::Detach(wxWindow *window)
References UNREACHABLEC.
Referenced by mutaborGUI::MutBoxShape::Detach.
virtual bool mutaborGUI::MutBoxShape::Detach(wxSizer *sizer)
References mutaborGUI::MutBoxShape::channels, mutaborGUI::MutBoxShape::Detach.
virtual bool mutaborGUI::MutBoxShape::Detach(int index)
References mutaborGUI::MutBoxShape::channels, mutaborGUI::MutBoxShape::Detach.
bool mutaborGUI::MutBoxShape::replaceSelfBy(MutBoxShape *newshape)
References mutASSERT, UNREACHABLEC.
bool mutaborGUI::MutBoxShape::DeleteBox()
References mutaborGUI::MutBoxChannelShape::GetRoute, mutASSERT.
bool mutaborGUI::MutBoxShape::readDialog(BoxDlg *boxdlg)
References mutabor::Box0, mutabor::connect, mutabor::BoxClass::GetBox, mutaborGUI::BoxDlg::GetBoxNumber, mutaborGUI::BoxDlg::GetBoxType, mutabor::BoxClass::GetOrCreateBox, mutaborGUI::BoxDlg::GetRouteWindow, mutabor::GmnBox, mutabor::BoxClass::IDTypeFile, mutASSERT, mutabor::NoBox, mutaborGUI::SetCurrentBox.
Referenced by mutaborGUI::MutBoxShape::DoLeftDblClick.
virtual bool mutaborGUI::MutBoxShape::CanHandleType(int type)
mutabor::Box mutaborGUI::MutBoxShape::GetBox() const
References mutaborGUI::MutBoxShape::box.
Referenced by mutaborGUI::Check, mutaborGUI::connect, mutaborGUI::disconnect, mutaborGUI::reconnect.
wxSizer* mutaborGUI::MutBoxShape::GetChannels() const
References mutaborGUI::MutBoxShape::channels.
Referenced by mutaborGUI::Check, mutaborGUI::disconnect.
void mutaborGUI::MutBoxShape::BoxChanged()
Updates the Display of the Box shape after a change of the box that must be honoured by this shape.
References _, mutaborGUI::BoxData::GetBackgroundColour, mutaborGUI::BoxData::GetTextColour, mutabor::GmnBox, mutabor::NewBox, mutabor::NoBox, mutaborGUI::ToGUIBase.
Referenced by mutaborGUI::BoxData::set_routefile_id.
virtual void mutaborGUI::MutBoxShape::MoveBox(int count)
Move the box in the box list and update the GUI according to the new order.
count number of entries the device should be moved up. Negative values indicate downwards direction.
References mutaborGUI::MutBoxShape::box.
void mutaborGUI::MutBoxShape::SetBox(bool nullify=true)
References _, mutaborGUI::MutBoxShape::box, MutIconShapeClass< MutPanel >::SetLabel.
Referenced by mutaborGUI::MutBoxShape::Add, mutaborGUI::MutBoxShape::Remove, mutaborGUI::MutBoxShape::Replace.
void mutaborGUI::MutBoxShape::SetBox(mutabor::Box &b, bool layout=true)
mutaborGUI::IMPLEMENT_ABSTRACT_CLASS_TEMPLATE1(MutDeviceShape, MutIconShape, inputdevicetypes) IMPLEMENT_ABSTRACT_CLASS_TEMPLATE1(MutDeviceShape
bool mutaborGUI::MutDeviceShape< T >::strptrless::operator()(wxString *a, wxString *b)
mutaborGUI::MutDeviceShape< T >::~MutDeviceShape()
References mutaborGUI::disconnect, TRACEC.
bool mutaborGUI::MutDeviceShape< T >::Create(wxWindow *parent, wxWindowID id, const wxString &name=wxEmptyString)
References MutIconShapeClass< T >::Create, DEBUGLOG, MutIconShapeClass< T >::SetLabel.
Referenced by mutaborGUI::MutNewInputDeviceShape::Create, mutaborGUI::MutOutputMidiFileDeviceShape::Create, mutaborGUI::MutNewOutputDeviceShape::Create, mutaborGUI::MutOutputMidiDeviceShape::Create, mutaborGUI::MutInputGuidoFileDeviceShape::Create, mutaborGUI::MutOutputGuidoFileDeviceShape::Create, mutaborGUI::MutInputMidiDeviceShape::Create, mutaborGUI::MutInputMidiFileDeviceShape::Create, mutaborGUI::MutDeviceShape< T >::MutDeviceShape.
bool mutaborGUI::MutDeviceShape< T >::Create(wxWindow *parent, wxWindowID id, devicetype &d)
References mutaborGUI::connect, DEBUGLOG, mutaborGUI::MidiInputDevBitmap, mutaborGUI::MidiOutputDevBitmap, mutASSERT, TRACEC.
const devicetype& mutaborGUI::MutDeviceShape< T >::GetDevice() const
References mutaborGUI::MutDeviceShape< T >::device.
Referenced by mutaborGUI::Check, mutaborGUI::connect, mutaborGUI::disconnect, mutaborGUI::reconnect, mutaborGUI::MutDeviceShape< T >::replaceSelfBy.
devicetype& mutaborGUI::MutDeviceShape< T >::GetDevice()
References mutaborGUI::MutDeviceShape< T >::device.
const GUIDeviceBase* mutaborGUI::MutDeviceShape< T >::GetGUIDevice() const
References mutaborGUI::MutDeviceShape< T >::device, mutaborGUI::ToGUIBase.
GUIDeviceBase* mutaborGUI::MutDeviceShape< T >::GetGUIDevice()
References mutaborGUI::MutDeviceShape< T >::device, mutaborGUI::ToGUIBase.
mutabor::routeListType& mutaborGUI::MutDeviceShape< T >::getRoutes()
References mutaborGUI::MutDeviceShape< T >::device, TRACEC, UNREACHABLEC.
const MutBoxChannelShapeList& mutaborGUI::MutDeviceShape< T >::GetChannels() const
References mutaborGUI::MutDeviceShape< T >::routes.
Referenced by mutaborGUI::Check.
static void mutaborGUI::MutDeviceShape< T >::SetSizerFlags(wxSizerFlags flags)
References mutaborGUI::MutDeviceShape< T >::sizerFlags.
static const wxSizerFlags& mutaborGUI::MutDeviceShape< T >::GetSizerFlags()
References mutaborGUI::MutDeviceShape< T >::sizerFlags.
virtual void mutaborGUI::MutDeviceShape< T >::Add(DeviceClass *dev)
add a device
References mutaborGUI::MutDeviceShape< T >::device, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::GUIRouteBase::Add, mutaborGUI::connect, mutaborGUI::MutRouteWnd::createRoutes.
virtual bool mutaborGUI::MutDeviceShape< T >::Replace(devicetype olddev, devicetype newdev)
replace a device
References mutaborGUI::MutDeviceShape< T >::device, TRACEC, UNREACHABLEC.
virtual bool mutaborGUI::MutDeviceShape< T >::Remove(devicetype dev)
remove a device
References mutaborGUI::MutDeviceShape< T >::device, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::disconnect, mutaborGUI::GUIRouteBase::Remove.
void mutaborGUI::MutDeviceShape< T >::Add(MutBoxChannelShape *route)
add a route
References mutASSERT.
bool mutaborGUI::MutDeviceShape< T >::Replace(MutBoxChannelShape *oldroute, MutBoxChannelShape *newroute)
replace a route
References mutASSERT.
bool mutaborGUI::MutDeviceShape< T >::Remove(MutBoxChannelShape *route)
remove a route
References UNREACHABLEC.
bool mutaborGUI::MutDeviceShape< T >::MoveRoutes(MutDeviceShape *newclass)
Move routes to another device.
References mutaborGUI::MutDeviceShape< T >::routes.
bool mutaborGUI::MutDeviceShape< T >::Recompute()
virtual wxPanel* mutaborGUI::MutDeviceShape< T >::GetFilterPanel(wxWindow *parent, mutabor::Route &route) const =0
virtual void mutaborGUI::MutDeviceShape< T >::ReadFilterPanel(wxWindow *panel, mutabor::Route &route)=0
Referenced by mutaborGUI::MutDeviceShape< T >::ReadPanel.
void mutaborGUI::MutDeviceShape< T >::ReadPanel(FilterPanel *panel, MutBoxChannelShape *channel)
References mutaborGUI::disconnect, mutaborGUI::MutBoxChannelShape::GetRoute, mutASSERT, mutaborGUI::MutDeviceShape< T >::ReadFilterPanel, mutaborGUI::reconnect, TRACEC, UNREACHABLEC.
void mutaborGUI::MutDeviceShape< T >::OnKeyDown(wxKeyEvent &event)
void mutaborGUI::MutDeviceShape< T >::CmMoveIcon(wxCommandEvent &event)
Move the corresponding device in the device list and update the GUI according to the new order.
event wxCommandEvent containing the request
void mutaborGUI::MutDeviceShape< T >::CmDeviceNotification(wxCommandEvent &event)
The device notifies the shape about a state change.
event wxCommandEvent containing the request
References mutaborGUI::MutDeviceShape< T >::DoDeviceNotification.
void mutaborGUI::MutDeviceShape< T >::DoDeviceNotification(wxCommandEvent &event)
The device notifies the shape about a state change.
event wxCommandEvent containing the request
References mutabor::DeviceCompileError, mutabor::DeviceInitializing, mutabor::DeviceKilled, mutabor::DevicePause, mutabor::DevicePlay, mutabor::DeviceStop, mutabor::DeviceTimingError, mutabor::DeviceUnregistered.
Referenced by mutaborGUI::MutDeviceShape< T >::CmDeviceNotification.
void mutaborGUI::MutDeviceShape< T >::LeftDblClickEvent(wxMouseEvent &event)
Get a double click and prepare for execution of the command.
Since programs might produce segmentation faults when the object is deleted during processing of mouse events, we send us a new event using the event queue.
References mutaborGUI::CM_LEFT_DOUBLE_CLICK.
void mutaborGUI::MutDeviceShape< T >::CmLeftDblClick(wxCommandEvent &event)
Process a double click.
Since programs might produce segmentation faults when the object is deleted during processing of mouse events, we send us a new event using the event queue.
References mutaborGUI::MutDeviceShape< T >::DoLeftDblClick.
mutaborGUI::MutDeviceShape< T >::MutDeviceShape()
mutaborGUI::MutDeviceShape< T >::MutDeviceShape(wxWindow *parent, wxWindowID id, const wxString &name=wxEmptyString)
References mutaborGUI::MutDeviceShape< T >::Create.
mutaborGUI::MutDeviceShape< T >::MutDeviceShape(wxWindow *parent, wxWindowID id, devicetype &d)
References mutaborGUI::MutDeviceShape< T >::Create.
virtual void mutaborGUI::MutDeviceShape< T >::MoveDevice(int count)
Move the corresponding device in the device list and update the GUI according to the new order.
count number of entries the device should be moved up. Negative values indicate downwards direction.
References mutaborGUI::MutDeviceShape< T >::device.
void mutaborGUI::MutDeviceShape< T >::DoLeftDblClick()
Execute the double click.
Despite its name this function must not be called directly from a double click event handler. Click event handlers are not proof against control deletion.
References mutaborGUI::GUIDeviceFactory::CreateShape, mutaborGUI::DebugCheckRoutes, mutaborGUI::MutDeviceShape< T >::device, mutabor::DTNotSet, mutaborGUI::LogicOn, mutASSERT, TRACE, TRACEC, UNREACHABLEC.
Referenced by mutaborGUI::MutDeviceShape< T >::CmLeftDblClick.
OutputDevDlg * mutaborGUI::MutOutputDeviceShape::ShowDeviceDialog()
References ABSTRACT_FUNCTIONC.
virtual void mutaborGUI::MutDeviceShape< T >::InitializeDialog(DeviceDialog *in) const
virtual bool mutaborGUI::MutDeviceShape< T >::readDialog(DeviceDialog *dlg)
Initialize device data from a dialog.
Transfers the data from a dialog window into the corresponding device object. dlg device dialog true if the device has changed in a way that it must be reinitialized. false otherwise
References mutASSERT.
bool mutaborGUI::MutDeviceShape< T >::DetachDevice()
detach device
Detaches the device from any route and deletes the device. true if the corresponding device has been removed and we can delete the Shape.
References TRACEC.
bool mutaborGUI::MutDeviceShape< T >::replaceSelfBy(thistype *newshape)
References mutaborGUI::MutDeviceShape< T >::device, mutaborGUI::MutDeviceShape< T >::GetDevice, mutASSERT, TRACEC, TRACET.
virtual bool mutaborGUI::MutDeviceShape< T >::CanHandleType(mutabor::DevType type)
void mutaborGUI::MutDeviceShape< T >::createPlayButtons()
References mutaborGUI::DevicePauseBitmap, mutaborGUI::DevicePlayBitmap, mutaborGUI::DeviceStopBitmap, mutASSERT.
void mutaborGUI::MutDeviceShape< T >::createPauseButton()
References mutaborGUI::DevicePauseBitmap, mutASSERT.
void mutaborGUI::MutDeviceShape< T >::createRecordButtons()
References mutaborGUI::DevicePauseBitmap, mutaborGUI::DeviceRecordBitmap, mutaborGUI::DeviceStopBitmap, mutASSERT.
void mutaborGUI::MutDeviceShape< T >::PlayButtonPressed(wxCommandEvent &event)
mutaborGUI::GisInputFilterPanel::GisInputFilterPanel(wxWindow *parent)
void mutaborGUI::GisInputFilterPanel::SetFromBox(int current, int min, int max)
TODO: set limits according to changes: min.max = max.value and max.min = min.value.
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::GetFilterPanel.
int mutaborGUI::GisInputFilterPanel::GetFromBox() const
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::ReadFilterPanel.
void mutaborGUI::GisInputFilterPanel::SetToBox(int current, int min, int max)
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::GetFilterPanel.
int mutaborGUI::GisInputFilterPanel::GetToBox() const
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::ReadFilterPanel.
void mutaborGUI::GisInputFilterPanel::SetFromStaff(int current, int min, int max)
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::GetFilterPanel.
int mutaborGUI::GisInputFilterPanel::GetFromStaff() const
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::ReadFilterPanel.
void mutaborGUI::GisInputFilterPanel::SetToStaff(int current, int min, int max)
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::GetFilterPanel.
int mutaborGUI::GisInputFilterPanel::GetToStaff() const
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::ReadFilterPanel.
void mutaborGUI::GisInputFilterPanel::SetRouteType(RouteType routetype)
References mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, UNREACHABLEC.
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::GetFilterPanel.
RouteType mutaborGUI::GisInputFilterPanel::GetRouteType()
References mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, UNREACHABLEC.
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::ReadFilterPanel.
mutaborGUI::MutInputGuidoFileDeviceShape::MutInputGuidoFileDeviceShape()
mutaborGUI::MutInputGuidoFileDeviceShape::MutInputGuidoFileDeviceShape(wxWindow *parent, wxWindowID id, mutabor::InputDevice &d)
References mutaborGUI::MutInputGuidoFileDeviceShape::Create, TRACEC.
bool mutaborGUI::MutInputGuidoFileDeviceShape::Create(wxWindow *parent, wxWindowID id, mutabor::InputDevice &d)
References mutaborGUI::MutDeviceShape< T >::Create, TRACEC.
Referenced by mutaborGUI::MutInputGuidoFileDeviceShape::MutInputGuidoFileDeviceShape.
virtual MutIcon& mutaborGUI::MutInputGuidoFileDeviceShape::GetMutIcon()
Calculates the Icon to be used.
References mutaborGUI::GuidoFileBitmap, TRACEC.
void mutaborGUI::MutInputGuidoFileDeviceShape::SetLabel(const wxString &st)
References mutaborGUI::MutInputGuidoFileDeviceShape::fileName, MutIconShapeClass< T >::SetLabel.
wxPanel * mutaborGUI::MutInputGuidoFileDeviceShape::GetFilterPanel(wxWindow *parent, mutabor::Route &route) const
References mutabor::RTall, mutaborGUI::GisInputFilterPanel::SetFromBox, mutaborGUI::GisInputFilterPanel::SetFromStaff, mutaborGUI::GisInputFilterPanel::SetRouteType, mutaborGUI::GisInputFilterPanel::SetToBox, mutaborGUI::GisInputFilterPanel::SetToStaff.
void mutaborGUI::MutInputGuidoFileDeviceShape::ReadFilterPanel(wxWindow *panel, mutabor::Route &route)
References mutaborGUI::GisInputFilterPanel::GetFromBox, mutaborGUI::GisInputFilterPanel::GetFromStaff, mutaborGUI::GisInputFilterPanel::GetRouteType, mutaborGUI::GisInputFilterPanel::GetToBox, mutaborGUI::GisInputFilterPanel::GetToStaff, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, UNREACHABLEC.
void mutaborGUI::MutInputGuidoFileDeviceShape::DoDeviceNotification(wxCommandEvent &event)
The device notifies the shape about a state change.
event wxCommandEvent containing the request
void mutaborGUI::MutInputGuidoFileDeviceShape::InitializeDialog(InputDevDlg *in) const
References mutabor::DTGis, mutASSERT.
bool mutaborGUI::MutInputGuidoFileDeviceShape::readDialog(InputDevDlg *in)
References DEBUGLOG, mutabor::DTGis, mutASSERT.
virtual bool mutaborGUI::MutInputGuidoFileDeviceShape::CanHandleType(mutabor::DevType type)
References mutabor::DTGis.
mutaborGUI::MidiFileInputFilterPanel::MidiFileInputFilterPanel(wxWindow *parent)
void mutaborGUI::MidiFileInputFilterPanel::SetFromChannel(int current, int min, int max)
TODO: set limits according to changes: min.max = max.value and max.min = min.value.
References MidiFileInputFilterPanelBase::from_channel.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileInputFilterPanel::GetFromChannel() const
References MidiFileInputFilterPanelBase::from_channel.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileInputFilterPanel::SetToChannel(int current, int min, int max)
References MidiFileInputFilterPanelBase::to_channel.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileInputFilterPanel::GetToChannel() const
References MidiFileInputFilterPanelBase::to_channel.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileInputFilterPanel::SetFromTrack(int current, int min, int max)
References MidiFileInputFilterPanelBase::from_track.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileInputFilterPanel::GetFromTrack() const
References MidiFileInputFilterPanelBase::from_track.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileInputFilterPanel::SetToTrack(int current, int min, int max)
References MidiFileInputFilterPanelBase::to_track.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileInputFilterPanel::GetToTrack() const
References MidiFileInputFilterPanelBase::to_track.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileInputFilterPanel::SetRouteType(mutabor::RouteType routetype)
References MidiFileInputFilterPanelBase::all_panel, MidiFileInputFilterPanelBase::channel_panel, MidiFileInputFilterPanelBase::else_panel, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, MidiFileInputFilterPanelBase::track_panel, MidiFileInputFilterPanelBase::type.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel.
mutabor::RouteType mutaborGUI::MidiFileInputFilterPanel::GetRouteType() const
References MidiFileInputFilterPanelBase::all_panel, MidiFileInputFilterPanelBase::channel_panel, MidiFileInputFilterPanelBase::else_panel, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, MidiFileInputFilterPanelBase::track_panel, MidiFileInputFilterPanelBase::type, UNREACHABLEC.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::ReadFilterPanel.
mutaborGUI::MutInputMidiFileDeviceShape::MutInputMidiFileDeviceShape()
mutaborGUI::MutInputMidiFileDeviceShape::MutInputMidiFileDeviceShape(wxWindow *parent, wxWindowID id, mutabor::InputDevice &d)
References mutaborGUI::MutInputMidiFileDeviceShape::Create.
bool mutaborGUI::MutInputMidiFileDeviceShape::Create(wxWindow *parent, wxWindowID id, mutabor::InputDevice &d)
References mutaborGUI::MutDeviceShape< T >::Create, TRACEC.
Referenced by mutaborGUI::MutInputMidiFileDeviceShape::MutInputMidiFileDeviceShape.
virtual MutIcon& mutaborGUI::MutInputMidiFileDeviceShape::GetMutIcon()
Calculates the Icon to be used.
References mutaborGUI::MidiFileBitmap, TRACEC.
void mutaborGUI::MutInputMidiFileDeviceShape::SetLabel(const wxString &st)
References mutaborGUI::MutInputMidiFileDeviceShape::fileName, MutIconShapeClass< T >::SetLabel.
wxPanel * mutaborGUI::MutInputMidiFileDeviceShape::GetFilterPanel(wxWindow *parent, mutabor::Route &route) const
transfers the configuration data of an input filter from a route object to a dialog panel.
Filter data is currently stored in some variables of the route class. These variables are reused for several purposes. depending on the corresponding input device..This function creates an input filter panel for a route dialog and initializes it with the appropriate values of the route as they are inerpred by a MIDI file input device class. parent Parent window of the panel (usually a dialog or panel) route Route to read the data from A panel, that is correctly initialized to communicate the filter data with the user. The calling function must take care of it's deletion (or delegate it)
References mutabor::InputMidiFile::GetMaxChannel, mutabor::InputMidiFile::GetMaxTrack, mutabor::InputMidiFile::GetMinChannel, mutabor::InputMidiFile::GetMinTrack, mutabor::RTall, mutaborGUI::MidiFileInputFilterPanel::SetFromChannel, mutaborGUI::MidiFileInputFilterPanel::SetFromTrack, mutaborGUI::MidiFileInputFilterPanel::SetRouteType, mutaborGUI::MidiFileInputFilterPanel::SetToChannel, mutaborGUI::MidiFileInputFilterPanel::SetToTrack.
void mutaborGUI::MutInputMidiFileDeviceShape::ReadFilterPanel(wxWindow *panel, mutabor::Route &route)
transfers the configuration data of an input filter from a dialog panel to the route object Filter data is currently stored in some variables of the route class.
These varibles are reused for several purposes. depending on the corresponding input device..This function reads data from an input filter panel of the route dialog and stores them in the appropriate variables as they are inerpred by a MIDI file input device class.Noch zu erledigenSeparate filters from route. panel Panel with the data the user entered route Route object
References mutaborGUI::MidiFileInputFilterPanel::GetFromChannel, mutaborGUI::MidiFileInputFilterPanel::GetFromTrack, mutaborGUI::MidiFileInputFilterPanel::GetRouteType, mutaborGUI::MidiFileInputFilterPanel::GetToChannel, mutaborGUI::MidiFileInputFilterPanel::GetToTrack, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, UNREACHABLEC.
void mutaborGUI::MutInputMidiFileDeviceShape::DoDeviceNotification(wxCommandEvent &event)
The device notifies the shape about a state change.
event wxCommandEvent containing the request
void mutaborGUI::MutInputMidiFileDeviceShape::InitializeDialog(InputDevDlg *in) const
References mutabor::DTMidiFile, mutASSERT.
bool mutaborGUI::MutInputMidiFileDeviceShape::readDialog(InputDevDlg *in)
configure device from dialog data This function reads the data from a device dialog, so that the data entered by the user can be realized.
The following paameters are read: file name Noch zu erledigenimplement return value in Device Dialog. true in case of success (currently don't rely on it)
References mutabor::DTMidiFile, mutASSERT.
virtual bool mutaborGUI::MutInputMidiFileDeviceShape::CanHandleType(mutabor::DevType type)
References mutabor::DTMidiFile.
mutaborGUI::IMPLEMENT_CLASS(NewMutBoxShape, MutBoxShape) MutIcon &NewMutBoxShape
References DEBUGLOG, mutASSERT, mutaborGUI::NewBoxBitmap.
mutaborGUI::MutNewInputDeviceShape::MutNewInputDeviceShape()
mutaborGUI::MutNewInputDeviceShape::MutNewInputDeviceShape(wxWindow *parent, wxWindowID id)
References mutaborGUI::MutNewInputDeviceShape::Create.
bool mutaborGUI::MutNewInputDeviceShape::Create(wxWindow *parent, wxWindowID id)
References _, mutaborGUI::MutDeviceShape< T >::Create.
Referenced by mutaborGUI::MutNewInputDeviceShape::MutNewInputDeviceShape.
MutIcon& mutaborGUI::MutNewInputDeviceShape::GetMutIcon()
Calculates the Icon to be used.
References mutaborGUI::NewInputDevBitmap.
virtual wxPanel* mutaborGUI::MutNewInputDeviceShape::GetFilterPanel(wxWindow *parent, mutabor::Route &route) const
References UNREACHABLEC.
virtual void mutaborGUI::MutNewInputDeviceShape::ReadFilterPanel(wxWindow *panel, mutabor::Route &route)
References UNREACHABLEC.
void mutaborGUI::MutNewInputDeviceShape::InitializeDialog(InputDevDlg *in) const
References mutabor::DTNotSet.
bool mutaborGUI::MutNewInputDeviceShape::replaceSelfBy(MutInputDeviceShape *newshape)
References mutaborGUI::MutRouteWnd::AddInputDevice, mutASSERT.
mutaborGUI::MutNewOutputDeviceShape::MutNewOutputDeviceShape()
mutaborGUI::MutNewOutputDeviceShape::MutNewOutputDeviceShape(wxWindow *parent, wxWindowID id)
References mutaborGUI::MutNewOutputDeviceShape::Create.
bool mutaborGUI::MutNewOutputDeviceShape::Create(wxWindow *parent, wxWindowID id)
References _, mutaborGUI::MutDeviceShape< T >::Create.
Referenced by mutaborGUI::MutNewOutputDeviceShape::MutNewOutputDeviceShape.
MutIcon& mutaborGUI::MutNewOutputDeviceShape::GetMutIcon()
Calculates the Icon to be used.
References mutaborGUI::NewOutputDevBitmap.
virtual wxPanel* mutaborGUI::MutNewOutputDeviceShape::GetFilterPanel(wxWindow *parent, mutabor::Route &route) const
References UNREACHABLEC.
virtual void mutaborGUI::MutNewOutputDeviceShape::ReadFilterPanel(wxWindow *panel, mutabor::Route &route)
References UNREACHABLEC.
void mutaborGUI::MutNewOutputDeviceShape::InitializeDialog(OutputDevDlg *out) const
References mutabor::DTNotSet.
bool mutaborGUI::MutNewOutputDeviceShape::replaceSelfBy(MutOutputDeviceShape *newshape)
References mutaborGUI::MutRouteWnd::AddOutputDevice, UNREACHABLEC.
IMPLEMENT_DYNAMIC_CLASS(mutaborGUI::OutputDevDlg, OutputDevDlgBase) namespace mutaborGUI
OutputDevDlg type definition
References _, mutaborGUI::BEGIN_EVENT_TABLE, DEBUGLOG, mutabor::DTGis, mutabor::DTMidiFile, mutabor::DTMidiPort, mutabor::DTNotSet, mutabor::DTUnknown, END_EVENT_TABLE, mutaborGUI::EVT_CHOICE, mutUnused.
mutaborGUI::OutputDevDlg::TypeData::TypeData(mutabor::DevType i)
References mutaborGUI::OutputDevDlg::TypeData::nr.
bool mutaborGUI::OutputDevDlg::TypeData::operator==(mutabor::DevType i)
References mutaborGUI::OutputDevDlg::TypeData::nr.
mutaborGUI::OutputDevDlg::TypeData::operator mutabor::DevType()
References mutabor::DTNotSet, mutaborGUI::OutputDevDlg::TypeData::nr.
int mutaborGUI::OutputDevDlg::FindType(mutabor::DevType t)
mutaborGUI::OutputDevDlg::OutputDevDlg(wxWindow *parent=NULL)
Constructors.
void mutaborGUI::OutputDevDlg::OnChoiceSelected(wxCommandEvent &event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE
void mutaborGUI::OutputDevDlg::OnRemoveClick(wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON
void mutaborGUI::OutputDevDlg::OnFileChanged(wxFileDirPickerEvent &event)
void mutaborGUI::OutputDevDlg::UpdateLayout(mutabor::DevType type)
Referenced by mutaborGUI::OutputDevDlg::SetType.
int mutaborGUI::OutputDevDlg::GetMidiDevice() const
References OutputDevDlgBase::PortChoice.
void mutaborGUI::OutputDevDlg::SetMidiDevice(int value)
References DEBUGLOG, OutputDevDlgBase::PortChoice.
wxString mutaborGUI::OutputDevDlg::GetMidiFile() const
References OutputDevDlgBase::MidiFilePicker.
void mutaborGUI::OutputDevDlg::SetMidiFile(wxString value)
References DEBUGLOG, OutputDevDlgBase::MidiFilePicker.
wxString mutaborGUI::OutputDevDlg::GetGUIDOFile() const
References OutputDevDlgBase::GuidoFilePicker.
void mutaborGUI::OutputDevDlg::SetGUIDOFile(wxString value)
References DEBUGLOG, OutputDevDlgBase::GuidoFilePicker.
mutabor::DevType mutaborGUI::OutputDevDlg::GetType() const
References OutputDevDlgBase::DeviceChoice, mutabor::DTNotSet, mutASSERT.
void mutaborGUI::OutputDevDlg::SetType(mutabor::DevType value)
References DEBUGLOG, mutaborGUI::OutputDevDlg::UpdateLayout.
long mutaborGUI::OutputDevDlg::GetMidiBendingRange()
References OutputDevDlgBase::MidiBendingRange.
Referenced by mutaborGUI::MutOutputMidiDeviceShape::readDialog.
void mutaborGUI::OutputDevDlg::SetMidiBendingRange(long i)
References OutputDevDlgBase::MidiBendingRange.
long mutaborGUI::OutputDevDlg::GetMidiFileBendingRange()
References OutputDevDlgBase::MidiFileBendingRange.
void mutaborGUI::OutputDevDlg::SetMidiFileBendingRange(long i)
References OutputDevDlgBase::MidiFileBendingRange.
wxString mutaborGUI::OutputDevDlg::GetPortString(int i)
References OutputDevDlgBase::PortChoice.
void mutaborGUI::OutputDevDlg::AppendPortChoice(const wxString &s)
References OutputDevDlgBase::PortChoice.
wxBitmap mutaborGUI::OutputDevDlg::GetBitmapResource(const wxString &name)
Retrieves bitmap resources.
wxIcon mutaborGUI::OutputDevDlg::GetIconResource(const wxString &name)
Retrieves icon resources.
static bool mutaborGUI::OutputDevDlg::ShowToolTips()
Should we show tooltips?
mutaborGUI::MutOutputGuidoFileDeviceShape::MutOutputGuidoFileDeviceShape()
mutaborGUI::MutOutputGuidoFileDeviceShape::MutOutputGuidoFileDeviceShape(wxWindow *parent, wxWindowID id, mutabor::OutputDevice d)
References mutaborGUI::MutOutputGuidoFileDeviceShape::Create.
bool mutaborGUI::MutOutputGuidoFileDeviceShape::Create(wxWindow *parent, wxWindowID id, mutabor::OutputDevice d)
References mutaborGUI::MutDeviceShape< T >::Create.
Referenced by mutaborGUI::MutOutputGuidoFileDeviceShape::MutOutputGuidoFileDeviceShape.
virtual MutIcon& mutaborGUI::MutOutputGuidoFileDeviceShape::GetMutIcon()
Calculates the Icon to be used.
References mutaborGUI::GuidoFileBitmap, TRACEC.
void mutaborGUI::MutOutputGuidoFileDeviceShape::SetLabel(const wxString &st)
References mutaborGUI::MutOutputGuidoFileDeviceShape::fileName, MutIconShapeClass< T >::SetLabel.
wxPanel * mutaborGUI::MutOutputGuidoFileDeviceShape::GetFilterPanel(wxWindow *parent, mutabor::Route &route) const
References mutUnused.
void mutaborGUI::MutOutputGuidoFileDeviceShape::ReadFilterPanel(wxWindow *panel, mutabor::Route &route)
References mutUnused, UNREACHABLEC.
void mutaborGUI::MutOutputGuidoFileDeviceShape::InitializeDialog(OutputDevDlg *out) const
References mutabor::DTGis, mutASSERT.
bool mutaborGUI::MutOutputGuidoFileDeviceShape::readDialog(OutputDevDlg *out)
References DEBUGLOG, mutabor::DTGis, mutASSERT.
virtual bool mutaborGUI::MutOutputGuidoFileDeviceShape::CanHandleType(mutabor::DevType type)
References mutabor::DTGis.
mutaborGUI::MidiOutputFilterPanel::MidiOutputFilterPanel(wxWindow *parent)
void mutaborGUI::MidiOutputFilterPanel::SetFromChannel(int current, int min, int max)
TODO: set limits according to changes: min.max = max.value and max.min = min.value.
Referenced by mutaborGUI::MutOutputMidiDeviceShape::GetFilterPanel.
int mutaborGUI::MidiOutputFilterPanel::GetFromChannel() const
Referenced by mutaborGUI::MutOutputMidiDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiOutputFilterPanel::SetToChannel(int current, int min, int max)
Referenced by mutaborGUI::MutOutputMidiDeviceShape::GetFilterPanel.
int mutaborGUI::MidiOutputFilterPanel::GetToChannel() const
Referenced by mutaborGUI::MutOutputMidiDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiOutputFilterPanel::SetAvoidDrumChannel(bool avoid)
Referenced by mutaborGUI::MutOutputMidiDeviceShape::GetFilterPanel.
bool mutaborGUI::MidiOutputFilterPanel::GetAvoidDrumChannel() const
Referenced by mutaborGUI::MutOutputMidiDeviceShape::ReadFilterPanel.
mutaborGUI::MutOutputMidiDeviceShape::MutOutputMidiDeviceShape()
mutaborGUI::MutOutputMidiDeviceShape::MutOutputMidiDeviceShape(wxWindow *parent, wxWindowID id, mutabor::OutputDevice d)
References mutaborGUI::MutOutputMidiDeviceShape::Create.
bool mutaborGUI::MutOutputMidiDeviceShape::Create(wxWindow *parent, wxWindowID id, mutabor::OutputDevice d)
References mutaborGUI::MutDeviceShape< T >::Create.
Referenced by mutaborGUI::MutOutputMidiDeviceShape::MutOutputMidiDeviceShape.
virtual MutIcon& mutaborGUI::MutOutputMidiDeviceShape::GetMutIcon()
Calculates the Icon to be used.
References mutaborGUI::MidiOutputDevBitmap, TRACEC.
wxPanel * mutaborGUI::MutOutputMidiDeviceShape::GetFilterPanel(wxWindow *parent, mutabor::Route &route) const
References mutabor::OutputMidiPort::GetMaxChannel, mutabor::OutputMidiPort::GetMinChannel, mutaborGUI::MidiOutputFilterPanel::SetAvoidDrumChannel, mutaborGUI::MidiOutputFilterPanel::SetFromChannel, mutaborGUI::MidiOutputFilterPanel::SetToChannel.
void mutaborGUI::MutOutputMidiDeviceShape::ReadFilterPanel(wxWindow *panel, mutabor::Route &route)
References mutaborGUI::MidiOutputFilterPanel::GetAvoidDrumChannel, mutaborGUI::MidiOutputFilterPanel::GetFromChannel, mutaborGUI::MidiOutputFilterPanel::GetToChannel, mutASSERT, UNREACHABLEC.
void mutaborGUI::MutOutputMidiDeviceShape::InitializeDialog(OutputDevDlg *out) const
References DEBUGLOG, mutabor::DTMidiPort, mutabor::OutputMidiPort::GetDevId, mutASSERT.
bool mutaborGUI::MutOutputMidiDeviceShape::readDialog(OutputDevDlg *out)
References DEBUGLOG, mutabor::DTMidiPort, mutaborGUI::OutputDevDlg::GetMidiBendingRange, mutabor::Device::GetName, mutASSERT, mutabor::CommonMidiOutput< T, D >::SetBendingRange, mutabor::OutputMidiPort::SetDevId.
virtual bool mutaborGUI::MutOutputMidiDeviceShape::CanHandleType(mutabor::DevType type)
References mutabor::DTMidiPort.
mutaborGUI::MidiFileOutputFilterPanel::MidiFileOutputFilterPanel(wxWindow *parent)
void mutaborGUI::MidiFileOutputFilterPanel::SetFromChannel(int current, int min, int max)
TODO: set limits according to changes: min.max = max.value and max.min = min.value.
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileOutputFilterPanel::GetFromChannel() const
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileOutputFilterPanel::SetToChannel(int current, int min, int max)
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::GetFilterPanel.
int mutaborGUI::MidiFileOutputFilterPanel::GetToChannel() const
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::ReadFilterPanel.
void mutaborGUI::MidiFileOutputFilterPanel::SetAvoidDrumChannel(bool avoid)
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::GetFilterPanel.
bool mutaborGUI::MidiFileOutputFilterPanel::GetAvoidDrumChannel() const
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::ReadFilterPanel.
mutaborGUI::MutOutputMidiFileDeviceShape::MutOutputMidiFileDeviceShape()
mutaborGUI::MutOutputMidiFileDeviceShape::MutOutputMidiFileDeviceShape(wxWindow *parent, wxWindowID id, mutabor::OutputDevice d)
References mutaborGUI::MutOutputMidiFileDeviceShape::Create.
bool mutaborGUI::MutOutputMidiFileDeviceShape::Create(wxWindow *parent, wxWindowID id, mutabor::OutputDevice d)
References mutaborGUI::MutDeviceShape< T >::Create, TRACEC.
Referenced by mutaborGUI::MutOutputMidiFileDeviceShape::MutOutputMidiFileDeviceShape.
virtual MutIcon& mutaborGUI::MutOutputMidiFileDeviceShape::GetMutIcon()
Calculates the Icon to be used.
References mutaborGUI::MidiFileBitmap, TRACEC.
void mutaborGUI::MutOutputMidiFileDeviceShape::SetLabel(const wxString &st)
References mutaborGUI::MutOutputMidiFileDeviceShape::fileName, MutIconShapeClass< T >::SetLabel.
wxPanel * mutaborGUI::MutOutputMidiFileDeviceShape::GetFilterPanel(wxWindow *parent, mutabor::Route &route) const
References mutabor::OutputMidiFile::GetMaxChannel, mutabor::OutputMidiFile::GetMinChannel, mutaborGUI::MidiFileOutputFilterPanel::SetAvoidDrumChannel, mutaborGUI::MidiFileOutputFilterPanel::SetFromChannel, mutaborGUI::MidiFileOutputFilterPanel::SetToChannel.
void mutaborGUI::MutOutputMidiFileDeviceShape::ReadFilterPanel(wxWindow *panel, mutabor::Route &route)
References mutaborGUI::MidiFileOutputFilterPanel::GetAvoidDrumChannel, mutaborGUI::MidiFileOutputFilterPanel::GetFromChannel, mutaborGUI::MidiFileOutputFilterPanel::GetToChannel, mutASSERT, UNREACHABLEC.
void mutaborGUI::MutOutputMidiFileDeviceShape::InitializeDialog(OutputDevDlg *out) const
References mutabor::DTMidiFile, mutabor::Device::GetName, mutASSERT.
bool mutaborGUI::MutOutputMidiFileDeviceShape::readDialog(OutputDevDlg *out)
References mutabor::DTMidiFile, mutASSERT, mutabor::CommonMidiOutput< T, D >::SetBendingRange, mutabor::OutputMidiFile::SetName.
virtual bool mutaborGUI::MutOutputMidiFileDeviceShape::CanHandleType(mutabor::DevType type)
References mutabor::DTMidiFile.
static void mutaborGUI::initMutIcon(MutIcon &icon, const wxString &filename, const wxBitmapType type)
References mutaborGUI::DevUnknownBitmap.
Referenced by mutaborGUI::initMutIconShapes.
bool mutaborGUI::initMutIconShapes()
References mutaborGUI::ActiveChannelBitmap, mutaborGUI::BoxBitmap, mutaborGUI::DevicePauseBitmap, mutaborGUI::DevicePlayBitmap, mutaborGUI::DeviceRecordBitmap, mutaborGUI::DeviceStopBitmap, mutaborGUI::DevUnknownBitmap, mutaborGUI::GuidoFileBitmap, mutaborGUI::initMutIcon, mutaborGUI::MidiFileBitmap, mutaborGUI::MidiInputDevBitmap, mutaborGUI::MidiOutputDevBitmap, MutICON, mutaborGUI::NewBoxBitmap, mutaborGUI::NewInputDevBitmap, mutaborGUI::NewOutputDevBitmap, mutaborGUI::PassiveChannelBitmap.
Referenced by IMPLEMENT_APP.
void MutRouteWnd::InitShapes()
fills the window with the corresponding shapes.
This function is used to initialize the window with the current routing information. It creates the shapes for devices, routes and new objects.
References mutaborGUI::DebugCheckRoutes, mutASSERT, PRINTSIZER.
void MutRouteWnd::InitDevices()
References mutaborGUI::DebugCheckRoutes, PRINTSIZER.
Referenced by mutaborGUI::MutRouteWnd::CmRouteLoad, IMPLEMENT_APP.
void MutRouteWnd::ClearDevices()
void MutRouteWnd::createInputDevices(wxSizerFlags flags)
References DEBUGLOG, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::GetDeviceList, mutASSERT, TRACEC.
void MutRouteWnd::ClearInputDevices()
Clears all input device shapes.
References TRACEC.
void MutRouteWnd::createBoxes(wxSizerFlags flags)
References mutabor::BoxClass::GetBoxList, mutaborGUI::BoxData::GetShape, mutASSERT, mutaborGUI::ToGUIBase, TRACEC, UNREACHABLEC.
void MutRouteWnd::createRoutes(wxSizerFlags flags)
References mutaborGUI::MutBoxChannelShape::Add, mutaborGUI::MutDeviceShape< T >::Add, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::GetRouteList, mutaborGUI::BoxData::GetShape, mutASSERT, mutaborGUI::ToGUIBase, TRACEC.
void MutRouteWnd::ClearBoxes()
Clears all box shapes.
References TRACEC.
void MutRouteWnd::createOutputDevices(wxSizerFlags flags)
References mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::GetDeviceList, TRACEC.
void MutRouteWnd::ClearOutputDevices()
Clears all output device shapes.
References TRACEC.
void MutRouteWnd::CmRouteLoad(wxCommandEvent &event)
interactive route loading
This function opens a file open dialog in order to load a route configuration from disk storage. event (wxCommandEvent) event to be processed
References _, MutFileDataType::Canceled, mutabor::BoxClass::ClearBoxList, mutabor::CommonTypedDeviceAPI< OutputDeviceClass >::ClearDeviceList, mutabor::CommonTypedDeviceAPI< InputDeviceClass >::ClearDeviceList, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::ClearRouteList, mutaborGUI::CM_ROUTES, mutaborGUI::DebugCheckRoutes, FileNameDialog, mutaborGUI::MutRouteWnd::FitInside, mutaborGUI::MutRouteWnd::InitDevices, mutaborGUI::xmltree::Load, compat30::LoadRoutes, mutabor::RouteFactory::LoadRoutes, MutFileDataType::LogicSource, mutASSERT, MutFileDataType::name, MutFileDataType::TextRoute, MutFileDataType::type, MutFileDataType::Unknown, UNREACHABLE, MutFileDataType::UTF8TextRoute, WK_ROUTE, MutFileDataType::XMLRoute1.
Referenced by mutaborGUI::MutApp::CmRouteLoad.
void MutRouteWnd::CmRouteSave(wxCommandEvent &event)
save routes to disk.
This function saves the current routing conifiguriton into a file on disk storage. event (wxCommandEvent) event to be processed
References _, MutFileDataType::Canceled, MutFileDataType::LogicSource, compat30::SaveRoutes, mutabor::RouteFactory::SaveRoutes, MutFileDataType::TextRoute, TRACET, MutFileDataType::Unknown, UNREACHABLE, MutFileDataType::UTF8TextRoute, MutFileDataType::XMLRoute1.
Referenced by mutaborGUI::MutApp::CmRouteSave.
void MutRouteWnd::CmRouteSaveAs(wxCommandEvent &event)
save routes with a new file name
This function opens a file save dialog in order to save a route configuration to disk storage. event (wxCommandEvent) event to be processed
References _, MutFileDataType::Canceled, FileNameDialog, MutFileDataType::LogicSource, MutFileDataType::name, MutFileDataType::TextRoute, TRACET, MutFileDataType::type, MutFileDataType::Unknown, UNREACHABLE, MutFileDataType::UTF8TextRoute, MutFileDataType::XMLRoute1.
Referenced by mutaborGUI::MutApp::CmRouteSaveAs.
void MutRouteWnd::FitInside()
Referenced by mutaborGUI::MutRouteWnd::AddBox, mutaborGUI::MutRouteWnd::AddInputDevice, mutaborGUI::MutRouteWnd::AddOutputDevice, mutaborGUI::MutRouteWnd::CmRouteLoad, IMPLEMENT_APP.
void MutRouteWnd::OnSize(wxSizeEvent &event)
void MutRouteWnd::OnPaint(wxPaintEvent &event)
void MutRouteWnd::OnDraw(wxPaintDC &dc)
References DEBUGLOG, mutaborGUI::MutBoxShape::DrawLines, mutASSERT, PRINTSIZER, UNREACHABLEC.
void MutRouteWnd::OnMoveShape(wxCommandEvent &event)
References DEBUGLOG.
void MutRouteWnd::MoveShape(wxWindow *shape, int newpos, wxSizer *sizer)
Rally move shape.
This function should not be called from outside the class. It's here, because C++ does not allow partial specialisation of functions. shape Shape to be moved. newpos New position where the shape shall be dropped. sizer Sizer that is responsible for the dropped window
References mutASSERT.
void mutaborGUI::MutInputMidiDeviceShape::InitializeDialog(InputDevDlg *in) const
References mutabor::DTMidiPort, mutabor::InputMidiPort::GetDevId, mutASSERT.
bool mutaborGUI::MutInputMidiDeviceShape::readDialog(InputDevDlg *in)
References mutabor::DTMidiPort, mutabor::InputMidiPort::GetName, mutASSERT, mutabor::InputMidiPort::SetDevId.
wxPanel * mutaborGUI::MutInputMidiDeviceShape::GetFilterPanel(wxWindow *parent, mutabor::Route &route) const
References mutabor::InputMidiPort::GetMaxChannel, mutabor::InputMidiPort::GetMaxKey, mutabor::InputMidiPort::GetMinChannel, mutabor::InputMidiPort::GetMinKey, MIDI_MAX_CHANNEL, MIDI_MAX_KEY, MIDI_MIN_CHANNEL, MIDI_MIN_KEY, mutabor::RTall, mutaborGUI::MidiInputFilterPanel::SetFromChannel, mutaborGUI::MidiInputFilterPanel::SetFromKey, mutaborGUI::MidiInputFilterPanel::SetRouteType, mutaborGUI::MidiInputFilterPanel::SetToChannel, mutaborGUI::MidiInputFilterPanel::SetToKey.
void mutaborGUI::MutInputMidiDeviceShape::ReadFilterPanel(wxWindow *panel, mutabor::Route &route)
References mutaborGUI::MidiInputFilterPanel::GetFromChannel, mutaborGUI::MidiInputFilterPanel::GetFromKey, mutaborGUI::MidiInputFilterPanel::GetRouteType, mutaborGUI::MidiInputFilterPanel::GetToChannel, mutaborGUI::MidiInputFilterPanel::GetToKey, mutabor::RTall, mutabor::RTchannel, mutabor::RTelse, mutabor::RTstaff, UNREACHABLEC.
void mutaborGUI::NewMutBoxShape::InitializeDialog(BoxDlg *dlg) const
References _, mutabor::Box0, mutaborGUI::BoxDlg::DisableRemove, mutabor::BoxClass::GetNextFreeBox, mutASSERT, mutaborGUI::BoxDlg::SetBoxNumber, mutaborGUI::BoxDlg::SetBoxType.
bool mutaborGUI::NewMutBoxShape::replaceSelfBy(MutBoxShape *newshape)
References mutaborGUI::MutRouteWnd::AddBox, mutASSERT.
MMSYSTEM_H
MUWX_MUTROUTEWND_H
MUWX_MUTROUTEWND_H_PRECOMPILED
MUWX_ROUTING_BOXCHANNELSHAPE_H
MUWX_ROUTING_BOXCHANNELSHAPE_H_PRECOMPILED
MUWX_ROUTING_BOXDLG_H
MUWX_ROUTING_BOXDLG_H_PRECOMPILED
MUWX_ROUTING_BOXICONSHAPE_H
MUWX_ROUTING_BOXICONSHAPE_H_PRECOMPILED
MUWX_ROUTING_BOXSHAPE_H
MUWX_ROUTING_BOXSHAPE_H_PRECOMPILED
wxIMPLEMENT_CLASS_COMMON_TEMPLATE1
wxIMPLEMENT_CLASS_COMMON1_TEMPLATE1
IMPLEMENT_ABSTRACT_CLASS_TEMPLATE1
IMPLEMENT_DYNAMIC_CLASS_TEMPLATE1
MUWX_ROUTING_DEVICESHAPE_H
MUWX_ROUTING_DEVICESHAPE_H_PRECOMPILED
MUWX_ROUTING_GUIROUTE_INLINES_H
MUWX_ROUTING_GUIROUTE_INLINES_H_PRECOMPILED
MUWX_ROUTING_GUIROUTE_H
MUWX_ROUTING_GUIROUTE_H_PRECOMPILED
MUWX_ROUTING_INPUTDEVDLG_H
MUWX_ROUTING_INPUTDEVDLG_H_PRECOMPILED
MUWX_ROUTING_INPUTGUIDOFILEDEVICESHAPE_H
MUWX_ROUTING_INPUTGUIDOFILEDEVICESHAPE_H_PRECOMPILED
MUWX_ROUTING_INPUTMIDIFILEDEVICESHAPE_H
MUWX_ROUTING_INPUTMIDIFILEDEVICESHAPE_H_PRECOMPILED
MUWX_ROUTING_NEWBOXSHAPE_H
MUWX_ROUTING_NEWBOXSHAPE_H_PRECOMPILED
MUWX_ROUTING_NEWINPUTDEVICESHAPE_H
MUWX_ROUTING_NEWINPUTDEVICESHAPE_H_PRECOMPILED
MUWX_ROUTING_NEWOITPUTDEVICESHAPE_H
MUWX_ROUTING_NEWOITPUTDEVICESHAPE_H_PRECOMPILED
MUWX_ROUTING_OUTPUTDEVDLG_H
MUWX_ROUTING_OUTPUTDEVDLG_H_PRECOMPILED
MUWX_ROUTING_OUTPUTGUIDOFILEDEVICESHAPE_H
MUWX_ROUTING_OUTPUTGUIDOFILEDEVICESHAPE_H_PRECOMPILED
MUWX_ROUTING_OUTPUTMIDIDEVICESHAPE_H
MUWX_ROUTING_OUTPUTMIDIDEVICESHAPE_H_PRECOMPILED
MUWX_ROUTING_OUTPUTMIDIFILEDEVICESHAPE_H
MUWX_ROUTING_OUTPUTMIDIFILEDEVICESHAPE_H_PRECOMPILED
MUWX_ROUTING_ROUTEICONS_H
MUWX_ROUTING_ROUTEICONS_H_PRECOMPILED
MUWX_ROUTING_ROUTELISTS_H
MUWX_ROUTING_ROUTELISTS_H_PRECOMPILED