mutabor::ChannelData
typedef std::vector<int> mutabor::ChannelData::controller_vector
const size_t mutabor::ChannelData::IGNORE_UNIQUE_ID
Referenced by mutabor::CommonMidiOutput< T, D >::do_Controller.
controller_vector mutabor::ChannelData::controller
Referenced by get_controller, get_first_changed_controller, get_index, get_next_changed_controller, is_changed_controller, is_compatible, MidiReset, program_change, Reset, set_controller.
controller_vector mutabor::ChannelData::controller_changed
Referenced by get_first_changed_controller, get_next_changed_controller, is_changed_controller, Reset, set_controller.
size_t mutabor::ChannelData::first_unchanged
Referenced by Reset, set_controller.
bool mutabor::ChannelData::looped
Referenced by Reset, set_controller.
bool mutabor::ChannelData::data_is_rpn
Referenced by get_index, set_controller.
int mutabor::ChannelData::Sound
Referenced by get_program, is_compatible, program_change, Reset.
uint8_t mutabor::ChannelData::bank_coarse
Referenced by get_bank_coarse, program_change, Reset.
uint8_t mutabor::ChannelData::bank_fine
Referenced by get_bank_fine, program_change, Reset.
int mutabor::ChannelData::bend
Referenced by get_bend, MidiReset, Reset, set_bend.
mutabor::ChannelData::ChannelData(int sound=-1)
void mutabor::ChannelData::Reset()
References bank_coarse, bank_fine, bend, controller, controller_changed, first_unchanged, looped, Sound.
Referenced by mutabor::CommonMidiOutput< T, D >::do_Open, mutabor::CommonMidiOutput< T, D >::do_Panic.
void mutabor::ChannelData::MidiReset()
Reset the controllers according to the MIDI standard.
This function resets the Midi Controllers according to RP15 from the MMA.http://www.midi.org/techspecs/rp15.php
References bend, controller, mutabor::midi::get_default_controller_value, set_controller.
Referenced by mutabor::CommonMidiOutput< T, D >::do_Controller.
int mutabor::ChannelData::set_controller(size_t number, int data)
References controller, controller_changed, mutabor::midi::DATA_BUTTON_DECREMENT, mutabor::midi::DATA_BUTTON_INCREMENT, mutabor::midi::DATA_ENTRY_COARSE, mutabor::midi::DATA_ENTRY_FINE, data_is_rpn, DEBUGLOG, mutabor::midi::FIRST_NRPN, mutabor::midi::FIRST_RPN, first_unchanged, looped, mutabor::midi::NON_REGISTERED_PARAMETER_COARSE, mutabor::midi::NON_REGISTERED_PARAMETER_FINE, mutabor::midi::REGISTERED_PARAMETER_COARSE, mutabor::midi::REGISTERED_PARAMETER_FINE.
Referenced by mutabor::CommonMidiOutput< T, D >::CopyProgramChange, mutabor::CommonMidiOutput< T, D >::do_Controller, mutabor::CommonMidiOutput< T, D >::do_NoteOn, mutabor::CommonMidiOutput< T, D >::do_Open, mutabor::CommonMidiOutput< MidiPortOutputProvider, OutputDeviceClass >::do_SendBendingRange, mutabor::CommonMidiOutput< T, D >::do_UpdateControllers, MidiReset, mutabor::CommonMidiOutput< T, D >::OutputParameter.
int mutabor::ChannelData::get_index(int message)
References controller, mutabor::midi::DATA_BUTTON_DECREMENT, mutabor::midi::DATA_BUTTON_INCREMENT, mutabor::midi::DATA_ENTRY_COARSE, mutabor::midi::DATA_ENTRY_FINE, data_is_rpn, mutabor::midi::NON_REGISTERED_PARAMETER_COARSE, mutabor::midi::NON_REGISTERED_PARAMETER_FINE, mutabor::midi::PITCH_BEND_SENSITIVITY, mutabor::midi::REGISTERED_PARAMETER_COARSE, mutabor::midi::REGISTERED_PARAMETER_FINE.
Referenced by mutabor::CommonMidiOutput< T, D >::do_Controller, mutabor::CommonMidiOutput< T, D >::OutputParameter.
int mutabor::ChannelData::get_controller(size_t number) const
References controller.
Referenced by mutabor::CommonMidiOutput< T, D >::CopyController, mutabor::CommonMidiOutput< T, D >::CopyProgramChange, mutabor::CommonMidiOutput< T, D >::do_Controller, mutabor::CommonMidiOutput< T, D >::do_NoteOn, get_hold, mutabor::CommonMidiOutput< T, D >::OutputParameter, mutabor::InputDeviceClass::ResumeKeys.
bool mutabor::ChannelData::get_hold() const
Check whether one of the hold switches is active.
true if the channel is holding notes false if the notes are expected to stop immediately midi::is_hold()
References mutabor::midi::CONTROLLER_MIN_ON, get_controller, mutabor::midi::HOLD_2_PEDAL_ON_OFF, mutabor::midi::HOLD_PEDAL_ON_OFF, mutabor::midi::LEGATO_PEDAL_ON_OFF, mutabor::midi::SOSTENUTO_ON_OFF.
Referenced by mutabor::CommonMidiOutput< T, D >::do_Controller.
controller_vector::const_iterator mutabor::ChannelData::get_first_changed_controller() const
Get the first changed controller.
Iterator to the first changed controller. Noch zu erledigenProvide changed_controller iterator type
References controller_changed, get_next_changed_controller.
Referenced by mutabor::CommonMidiOutput< T, D >::CopyProgramChange, mutabor::CommonMidiOutput< T, D >::do_UpdateControllers.
controller_vector::const_iterator mutabor::ChannelData::get_first_changed_controller(const ChannelData &other) const
Get the first changed controller that differs from the corresponding controller in another channel.
other The channel data we compare ourselves to. iterator to the first differently changed controller.
References controller, controller_changed, get_next_changed_controller.
controller_vector::const_iterator mutabor::ChannelData::get_next_changed_controller(controller_vector::const_iterator last) const
Get the first changed controller.
last last position of the iterator. Iterator to the first changed controller. Noch zu erledigenProvide changed_controller iterator type
References controller, controller_changed, mutASSERT.
Referenced by mutabor::CommonMidiOutput< T, D >::CopyProgramChange, mutabor::CommonMidiOutput< T, D >::do_UpdateControllers, get_first_changed_controller.
controller_vector::const_iterator mutabor::ChannelData::get_next_changed_controller(const ChannelData &other, controller_vector::const_iterator last) const
Get the first changed controller that differs from the corresponding controller in another channel.
other The channel data we compare ourselves to. last last position of the iterator. iterator to the first differently changed controller.
References controller, controller_changed, mutASSERT.
bool mutabor::ChannelData::is_changed_controller(controller_vector::const_iterator actual) const
References controller, controller_changed, mutASSERT.
Referenced by mutabor::CommonMidiOutput< T, D >::CopyProgramChange, mutabor::CommonMidiOutput< T, D >::do_UpdateControllers.
void mutabor::ChannelData::program_change(int program)
References mutabor::midi::BANK_COARSE, bank_coarse, mutabor::midi::BANK_FINE, bank_fine, controller, Sound.
Referenced by mutabor::CommonMidiOutput< T, D >::CopyProgramChange, mutabor::InputGis::Proceed.
void mutabor::ChannelData::program_change(const ChannelData &o)
References mutabor::midi::BANK_COARSE, bank_coarse, mutabor::midi::BANK_FINE, bank_fine, controller, Sound.
bool mutabor::ChannelData::is_compatible(const ChannelData &cd) const
References controller, Sound.
int mutabor::ChannelData::get_bend()
References bend.
Referenced by mutabor::CommonMidiOutput< T, D >::do_NoteOn, mutabor::CommonMidiOutput< T, D >::do_UpdateTones.
void mutabor::ChannelData::set_bend(int b)
References bend.
Referenced by mutabor::CommonMidiOutput< T, D >::do_NoteOn, mutabor::CommonMidiOutput< T, D >::do_UpdateTones.
int mutabor::ChannelData::get_program() const
References Sound.
Referenced by mutabor::CommonMidiOutput< T, D >::CopyProgramChange.
int mutabor::ChannelData::get_bank_coarse() const
References bank_coarse.
Referenced by mutabor::CommonMidiOutput< T, D >::CopyProgramChange.
int mutabor::ChannelData::get_bank_fine() const
References bank_fine.
Referenced by mutabor::CommonMidiOutput< T, D >::CopyProgramChange.