ChordNote
ChordNote* ChordNote::Next
Referenced by ChordNote, GisWriteHead::GetFreeNote, GisWriteHead::GetNote, GisWriteHead::WriteChord, ~ChordNote.
GisToken* ChordNote::Data
Referenced by ChordNote, GisWriteHead::WriteChord, ~ChordNote.
GisToken** ChordNote::Cursor
Referenced by ChordNote.
GisWriteHead* ChordNote::Boss
Referenced by ChordNote.
mutabor::frac ChordNote::CurrentTime
Referenced by ChordNote.
mutabor::frac ChordNote::TotalTime
Referenced by ChordNote.
GisToken** ChordNote::BossPos
Referenced by ChordNote.
int ChordNote::InstrId
Referenced by CheckId, ChordNote.
char ChordNote::Status
Referenced by ChordNote.
GisToken** ChordNote::AlterBegin
GisToken** ChordNote::TieBegin
Referenced by ChordNote.
int ChordNote::nTie
Referenced by ChordNote.
std::string* ChordNote::LastSep
Referenced by ChordNote.
int ChordNote::Taste
Referenced by CheckId, ChordNote.
int ChordNote::Key
Referenced by ChordNote, Cmp.
double ChordNote::Pitch
Referenced by ChordNote, Cmp.
ChordNote::ChordNote(GisWriteHead *boss)
References AddGis, Boss, BossPos, GisWriteHead::ChordPos, GisWriteHead::CurrentTime, CurrentTime, GisWriteHead::Cursor, Cursor, Data, GMN_NO_KEY, InstrId, Key, LastSep, Next, nTie, Pitch, Status, Taste, TieBegin, TotalTime.
ChordNote::ChordNote(ChordNote *first)
References Boss, BossPos, mutabor::CurrentTime, GMN_NO_KEY.
ChordNote::~ChordNote()
References Data, Next.
void ChordNote::CountOnTime(mutabor::frac dTime)
References mutabor::CurrentTime.
void ChordNote::SetNoteOn(GisToken *note)
References CNNoteOn, NOTE.
Referenced by GisWriteHead::ProceedGis.
int ChordNote::SetNoteOff(GisToken *note)
References CmpNote, CNNoteOn, mutabor::CurrentTime.
void ChordNote::AddGis(GisToken *token)
References mutabor::CurrentTime, GisToken::Sep.
Referenced by ChordNote, GisWriteHead::GetFreeNote.
void ChordNote::CheckCloseAlter()
References CNAlter, Sep.
Referenced by CheckClose.
void ChordNote::CheckCloseTie()
References Sep, TTtie.
Referenced by CheckClose.
void ChordNote::CheckClose()
References CheckCloseAlter, CheckCloseTie.
Referenced by GisWriteHead::WriteChord.
int ChordNote::MutNoteOn(int key, double pitch, int instrId, int taste, std::string sep)
References CNAlter, CNNoteOn, GMN_NO_KEY, Note, GisToken::Sep, TTalter.
int ChordNote::MutNoteOff()
References CNAlter, CNNoteOn, mutabor::CurrentTime, GetGisType, GTNote.
char ChordNote::CheckId(int instrId, int taste)
References InstrId, Taste.
Referenced by GisWriteHead::GetNote.
char ChordNote::Cmp(int key, double pitch)
References GMN_NO_KEY, Key, Pitch.