mutaborGUI::MutEditFile::FindFlags
bool mutaborGUI::MutEditFile::FindFlags::down
Referenced by mutaborGUI::MutEditFile::DoFind, Down, FindFlags, mutaborGUI::MutEditFile::OnFindDialog, Up.
bool mutaborGUI::MutEditFile::FindFlags::askCircular
Referenced by AskCircular, mutaborGUI::MutEditFile::DoFind, FindFlags.
bool mutaborGUI::MutEditFile::FindFlags::showNotFound
Referenced by mutaborGUI::MutEditFile::DoFind, FindFlags, ShowNotFound.
bool mutaborGUI::MutEditFile::FindFlags::useCaret
Referenced by mutaborGUI::MutEditFile::DoFind, FindFlags, UseCaret.
mutaborGUI::MutEditFile::FindFlags::FindFlags()
References askCircular, down, showNotFound, useCaret.
FindFlags& mutaborGUI::MutEditFile::FindFlags::Down(bool d=true)
References down.
Referenced by mutaborGUI::MutEditFile::OnFindDialog, mutaborGUI::MutEditFile::OnFindNext.
FindFlags& mutaborGUI::MutEditFile::FindFlags::Up(bool up=true)
References down.
FindFlags& mutaborGUI::MutEditFile::FindFlags::AskCircular(bool a=true)
References askCircular.
FindFlags& mutaborGUI::MutEditFile::FindFlags::ShowNotFound(bool s=true)
References showNotFound.
Referenced by mutaborGUI::MutEditFile::OnFindDialog.
FindFlags& mutaborGUI::MutEditFile::FindFlags::UseCaret(bool s=true)
References useCaret.
Referenced by mutaborGUI::MutEditFile::OnFindDialog.