boost-interface.h
SRC_KERNEL_BOOST_INTERFACE_H
SRC_KERNEL_BOOST_INTERFACE_H_PRECOMPILED
REFPTR_INTERFACE
REFPTR_INTERFACE_NOLOCK
CHECK_REFPTR_NULL
intrusive_ptr
size_t intrusive_ptr_get_refcount(intrusive_ptr_T *obj)
Referenced by mutaborGUI::GUIRouteBase::Add, mutaborGUI::GUIOutputDeviceBase::Add, mutaborGUI::GUIInputDeviceBase::Add, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::ClearRouteList, mutabor::TRouteClass< I, O, B >::Create, mutabor::RouteFactory::Create, mutaborGUI::GUIRouteBase::Destroy, mutaborGUI::GUIfiedRoute< T >::Destroy, mutaborGUI::disconnect, mutaborGUI::GUIRouteFactory::DoCreateBoxChannelShape, mutaborGUI::MutBoxChannelShape::InitializeInputFilter, intrusive_ptr_add_ref, intrusive_ptr_release, mutabor::TRouteClass< I, O, B >::LoadRoutes, mutabor::CommonTypedDeviceAPI< T, P, L >::operator std::string, mutaborGUI::GUIRouteBase::Remove, mutabor::BoxClass::Remove, mutaborGUI::GUIOutputDeviceBase::Remove, mutaborGUI::GUIInputDeviceBase::Remove, mutabor::CommonTypedDeviceAPI< T, P, L >::Remove, mutaborGUI::GUIRouteBase::Replace.
void intrusive_ptr_add_ref(intrusive_ptr_T *obj)
References DEBUGLOGTYPE, intrusive_ptr_get_refcount.
Referenced by mutabor::BoxClass::~BoxClass.
void intrusive_ptr_release(intrusive_ptr_T *obj)
References DEBUGLOGTYPE, intrusive_ptr_get_refcount.