mutgis.cpp
GisReadArtHead* h
Referenced by CloseAllSubs, GisWriteHead::CloseSubs, MutIconShapeClass< T >::DoGetBestSize, GetMatchingHeader, GisReadArtHeadOn, GisReadHeadOn, IMPLEMENT_APP, MutIconShapeClass< T >::Layout, mutaborGUI::MutTag::PaintCenteredText, mutabor::InputGis::ReadOn.
GTAK* Tone
GTAK* GetGTAK(GTAK *root, int instr, int taste)
References GTAK::Id, GTAK::Next.
void KillGTAK(GTAK **root, GTAK *gtag)
References GTAK::Next.
void gis_notes_correct(int instr, TONSYSTEM *tonsys)
Referenced by set_synthesizer_typ_pointers_gis.
void gis_note_on(int instr, TONSYSTEM *tonsys, int taste, int velo)
Referenced by set_synthesizer_typ_pointers_gis.
void gis_note_off(int instr, int taste, int velo)
Referenced by set_synthesizer_typ_pointers_gis.
void gis_open_synthesizer(void)
Referenced by set_synthesizer_typ_pointers_gis.
void gis_close_synthesizer(void)
Referenced by set_synthesizer_typ_pointers_gis.
void set_synthesizer_typ_pointers_gis(void)
References gis_close_synthesizer, gis_note_off, gis_note_on, gis_notes_correct, gis_open_synthesizer.