Interpreter
struct ton_einstell* expand_tonliste(struct ton *the_tonliste)
Expandiert eine Tonliste in eine einfach verkettete Liste von Einstellungen.
the_tonliste Liste von Tönen.
References DOUBLE_TO_LONG, einstell_absolut, einstell_gleich, einstell_relativ, einstell_stumm, FAKTOR_TO_MIDI, fatal_error, FREQUENZ_TO_MIDI, get_komplex_faktor, get_komplex_frequenz, ton::name, ton_einstell::next, ton_absolut, ton::ton_absolut, ton_komplex, ton::ton_komplex, ton::u, ton_einstell::u, xmalloc.
Referenced by expandiere_umstimmung.
struct do_aktion* expandiere_tonsystem(struct tonsystem *the_tonsystem)
Wandelt ein Tonsystem in eine Aktion um.
Dazu werden Tonnamen expandiert und die einzelnen Töne in MIDI-Werte umgerechnet. the_tonsystem Tonsystem.
References TSYS::anker, aufruf_tonsystem, TSYS::breite, DOUBLE_TO_LONG, FAKTOR_TO_MIDI, FREQUENZ_TO_MIDI, get_ton, get_wert_komplex_intervall, list_of_toene, name, ton::name, ton::next, TSYS::periode, toene, TSYS::ton, ton_list_laenge, ton::u, xmalloc.
Referenced by expandiere_logik, expandiere_name.
struct do_aktion* expand_aktions_liste(struct aktions_liste *the_liste, struct interpreter_parameter_liste *aktuelle_parameter)
Ersetzt Parameter in einer Aktionsliste durch ihre aktuellen Werte.
the_liste Ausgangs-Liste mit den Aktionen, deren Parameter ersetzt werden sollon. aktuelle_parameter Liste mit den Aktuellen Parametern, die ersetzt werden können. Neu hinzukommende Aktionen werden erhalten. Kann das passieren?
References aktion_aufruf, aktion_midi_out, expand_aktions_liste, expandiere_midi, expandiere_name, fatal_error, do_aktion::next, do_aktion::u.
Referenced by expand_aktions_liste, expand_case_liste, expandiere_umstimmung, insert_in_lokale_liste.
struct do_aktion* expandiere_umstimmung(struct umstimmung *the_umstimmung, struct interpreter_parameter_liste *aktuelle_parameter)
Ersetzt die Parameter einer Umstimmung durch deren Werte.
the_umstimmung Umstimmung, die bearbeitet werden soll. aktuelle_parameter Liste der Parameter, die ersetzt werden können
References aufruf_midi_out, aufruf_umst_breite_abs, aufruf_umst_breite_rel, aufruf_umst_taste_abs, aufruf_umst_taste_rel, aufruf_umst_toene_veraendert, aufruf_umst_umst_case, aufruf_umst_wiederholung_abs, aufruf_umst_wiederholung_rel, DOUBLE_TO_LONG, expand_aktions_liste, expand_case_liste, expand_tonliste, FAKTOR_TO_MIDI, fatal_error, get_wert_komplex_intervall, get_wert_of_argument, name, do_aktion::next, umstimmung::u, do_aktion::u, umstimmung_breite_abs, umstimmung::umstimmung_breite_abs, umstimmung_breite_rel, umstimmung::umstimmung_breite_rel, umstimmung_midi_out, umstimmung::umstimmung_midi_out, umstimmung_taste_abs, umstimmung::umstimmung_taste_abs, umstimmung_taste_rel, umstimmung::umstimmung_taste_rel, umstimmung_toene_veraendert, umstimmung::umstimmung_toene_veraendert, umstimmung_umstimmungs_case, umstimmung::umstimmung_umstimmungs_case, umstimmung_umstimmungsbund, umstimmung::umstimmung_umstimmungsbund, umstimmung_wiederholung_abs, umstimmung::umstimmung_wiederholung_abs, umstimmung_wiederholung_rel, xfree, xmalloc.
Referenced by expandiere_logik, expandiere_name.
struct do_aktion* expandiere_name(char *name, struct argument_liste *parameter, struct interpreter_parameter_liste *bezugs_liste)
Sucht nach einer Logik, einem Tonsystem bzw.
einer Umstimmung in dieser Reihenfolge. Wird eine Umstimmung zurückgeliefert, so werden gleich auch deren Parameter ersetzt. name Name der zu suchenden Logik, des Tonsystems oder der Umstimmung. parameter Argumente, für die Parameter-Ersetzung bezugs_liste Liste mit den Interpreter-Parametern, aus denen die aktuellen Parameter für die Expansion der Umstimmung generiert werden.
References expandiere_logik, expandiere_tonsystem, expandiere_umstimmung, fatal_error, gen_parameter_liste, get_logik, get_umstimmung, list_of_logiken, list_of_tonsysteme, list_of_umstimmungen, parser_get_tonsystem.
Referenced by expand_aktions_liste.
struct do_aktion* expandiere_midi(struct midiliste *liste)
Wandelt eine MIDI-Liste in eine MIDI-Ausgabe-Aktion um.
liste MIDI-Liste, die umgewandelt werden soll
References aufruf_midi_out, name, do_aktion::next, do_aktion::u, xmalloc.
Referenced by expand_aktions_liste.
void insert_in_globale_liste(int instrument, struct logik *lauf)
Fügt die auslösende Harmonien, Taste bzw.
das Midiereignis der Logik in die entsprechenede globale Liste eines Instrumentes ein. instrument Instrument, für das das Ereignis eingefügt werden soll. lauf Logik, deren Auslöser eingefügt werden soll.
References keyboard_ereignis::aktion, midi_ereignis::aktion, harmonie_ereignis::aktion, logik::ausloeser, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser_taste, create_midi_scan_liste, expand_pattern, fatal_error, midi_ereignis::first_pos, harmonie_ereignis::ist_harmonieform, harmonie_ereignis::nachtaste, name, logik::name, keyboard_ereignis::next, midi_ereignis::next, harmonie_ereignis::next, harmonie_ereignis::pattern, midi_ereignis::scan_pos, keyboard_ereignis::the_logik_to_expand, midi_ereignis::the_logik_to_expand, harmonie_ereignis::the_logik_to_expand, ausloeser::u, harmonie_ereignis::vortaste, xmalloc.
Referenced by expand_decition_tree, mutabor_tabellen_generator.
struct harmonie_ereignis** get_ende_harmonie(struct harmonie_ereignis **lauf)
Liefert einen Zeiger auf den Nachfolge-Zeiger des letzten Elementes einer Harmonie-Ereignis-Liste.
lauf Zeiger auf die Wurzel einer einfach verketteten Liste von Harmonieereignissen.
References get_ende_harmonie, harmonie_ereignis::next.
Referenced by expand_decition_tree, get_ende_harmonie, mutabor_tabellen_generator.
struct keyboard_ereignis** get_ende_keyboard(struct keyboard_ereignis **lauf)
Liefert einen Zeiger auf den Nachfolge-Zeiger des letzten Elementes einer Tasten-Ereignis-Liste.
lauf Zeiger auf die Wurzel einer einfach verketteten Liste von Tastenereignissen.
References get_ende_keyboard, keyboard_ereignis::next.
Referenced by expand_decition_tree, get_ende_keyboard, mutabor_tabellen_generator.
struct midi_ereignis** get_ende_midi(struct midi_ereignis **lauf)
Liefert einen Zeiger auf den Nachfolge-Zeiger des letzten Elementes einer MIDI-Ereignis-Liste.
lauf Zeiger auf die Wurzel einer einfach verketteten Liste von MIDI-Ereignissen.
References get_ende_midi, midi_ereignis::next.
Referenced by expand_decition_tree, get_ende_midi, mutabor_tabellen_generator.
void insert_in_lokale_liste(int instrument, struct anweisung *lauf, char *name_der_logik)
Fügt die auslösende Harmonien, Taste bzw.
das Midiereignis der Logik in die entsprechenede lokale Liste eines Instrumentes ein. instrument Instrument, für das das Ereignis eingefügt werden soll. lauf Anweisung, deren Auslöser eingefügt werden soll. name_der_logik Name der Logik, zu der die Anweisung gehört.
References anweisung::aktion, keyboard_ereignis::aktion, midi_ereignis::aktion, harmonie_ereignis::aktion, anweisung::ausloeser, ausloeser_default, ausloeser_harmonie, ausloeser::ausloeser_harmonie, ausloeser_harmonie_form, ausloeser::ausloeser_harmonie_form, ausloeser_midi_in, ausloeser::ausloeser_midi_in, ausloeser_taste, create_midi_scan_liste, expand_aktions_liste, expand_pattern, fatal_error, midi_ereignis::first_pos, harmonie_ereignis::ist_harmonieform, harmonie_ereignis::nachtaste, name, keyboard_ereignis::next, midi_ereignis::next, harmonie_ereignis::next, harmonie_ereignis::pattern, midi_ereignis::scan_pos, start_parameter_liste, ausloeser::u, harmonie_ereignis::vortaste, xmalloc.
Referenced by expand_decition_tree, expandiere_logik, mutabor_tabellen_generator.
void expandiere_in_globale_liste(void)
Expandiert die Auslösenden Ereignisse aller angesammeldten Logiken in die globale Liste.
References midi_ereignis::aktion, expandiere_logik, MAX_BOX, midi_ereignis::next, midi_ereignis::the_logik_to_expand.
Referenced by expand_decition_tree, mutabor_tabellen_generator.
struct case_element* expand_case_liste(struct case_liste *the_liste, struct interpreter_parameter_liste *aktuelle_parameter)
Sortiert die Default-Zweige von Case-Listen ans Ende und expandiert die Paramater der einzelnen Aktionen.
the_liste Case-Liste, die bearbeitet werden soll. aktuelle_parameter Aktuelle Parameter, die ersetzt werden können. Noch zu erledigenVereinigen beider Schleifen duch hinzufügen einer neuen temporären default-ende-liste.
References case_element::case_aktion, case_element::case_wert, expand_aktions_liste, case_liste::is_default, case_element::is_default, case_liste::next, case_element::next, xmalloc.
Referenced by expandiere_umstimmung.
PATTERNN* expand_pattern(char *harmonie_name)
Erzeugt eine Suchmaske für die Suche nach Harmonien.
harmonie_name Name der Harmonie, für die die Maske erzeugt werden soll. Ganzzahlenfeld, das die Harmonie-Suchmaske symbolisiert
References fatal_error, for, get_harmonie, MAX_BREITE, taste::stern, taste::taste, harmonie::tastenliste, PTRN::tonigkeit, xmalloc.
Referenced by insert_in_globale_liste, insert_in_lokale_liste.
int* create_midi_scan_liste(struct midiliste *lauf)
Wandelt eine einfach verkettete MIDI-Liste in ein Ganzzahlen-(int)-Feld um.
Ganzzahlenfeld. Der Letzte Eintrag enthält quasi als Wächter den Wert -1.
References midiliste::midi_code, midi_list_laenge, midiliste::next, xcalloc.
Referenced by insert_in_globale_liste, insert_in_lokale_liste.