name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Apt packages
      run: |
        sudo apt-get update
        sudo apt-get install autopoint devscripts pbuilder fakeroot debhelper autoconf libtool gettext automake flex bison libwxgtk3.0-gtk3-dev libboost-dev libboost-thread-dev libboost-locale-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libasound-dev libcppunit-dev doxygen tex4ht xvfb libjack0 libjack-dev jackd
      if: runner.os == 'Linux'
    - name: Install MacOS packages
      run: |
        brew update
        brew install wxmac gettext flex bison libtool autoconf automake jack boost
        brew link --force  flex bison libtool autoconf automake
        echo '/usr/local/opt/flex/bin' >> ${GITHUB_PATH}
        echo '/usr/local/opt/bison/bin' >> ${GITHUB_PATH}
      if: runner.os == 'macOS'
    - name: Install Windows packages
      run: echo not implemented
      if: runner.os == 'Windows'
    - name: Start JACKd
      run: jackd -d dummy &
    - name: autoreconf
      run: autoreconf -i -f
    - name: configure
      run: ./configure
    - name: make
      run: make -j4
    - name: make check
      run: make check || cat testsuite.log
    - name: make distcheck
      run: make distcheck
