name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install packages
      run: sudo apt-get install autopoint devscripts pbuilder fakeroot debhelper autoconf libtool gettext automake fleix bison libwxgtk3.0-dev libboost-dev libboost-thread-dev libboost-locale-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libasound-dev libcppunit-dev doxygen tex4ht xvfb libjack-dev jackd
    - name: Start JACKd
      run: jackd -d dummy &
    - name: autoreconf
      run: autoreconf -i -f
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
