mutabor::RouteFactory
RouteFactory * mutabor::RouteFactory::factory
Pointer to the current factory.
Referenced by Create, mutaborGUI::GUIRouteFactory::CreateBoxChannelShape, Destroy, LoadRoutes, RouteFactory, SaveRoutes.
mutabor::RouteFactory::RouteFactory()
Creates a route Factory.
Constructor. Should be overridden if classes inhert from Route.
References factory.
static Route mutabor::RouteFactory::Create()
Creates a generic route.
This functions creates a route object on the heap and returns a smart pointer to it. This route will not be preconfigured.Route smart pointer to the newly created route
References DoCreate, factory.
Referenced by mutaborGUI::MutBoxShape::AddChannel, compat30::LoadRoutes, mutabor::TRouteClass< I, O, B >::LoadRoutes, CommonMidiOutputTest::setUp, CommonMidiInputTest::setUp, OutputMidiFileTest::setUp, InputMidiFileTest::testBatchPlay1, InputMidiFileTest::testBug019010, InputMidiFileTest::testBug019010_2, GUIRouteTest::testConnect, RouteTest::testDestroyAll.
Route mutabor::RouteFactory::Create(InputDevice &in, OutputDevice &out, RouteType type=RTall, int iFrom=-1, int iTo=-1, Box box=NULL, bool active=false, int oFrom=-1, int oTo=-1, bool oNoDrum=true)
Creates a preconfigured route according to the given type.
This functions creates a route object on the heap and returns a smart pointer to it. This route will be preconfigured according the data provided in the arguments. in InputDevice& Reference to a smart pointer for the input device where the route starts. out OutputDevice& End point of the route. type RouteType Type of the input filter. See RouteType for more information. iFrom start of the range for the input filter. Its meaning depends on the input filter type. iTo end of the range for the input filter. Its meaning depends on the input filter type. box box to be used. Values less than 0 indicate a pass through route or a GMN box. active indicates whether the events on the route may change the tuning of the box. Regardless of this setting the box referenced by the box parameter will influence the tuning of the events in this route. oFrom Start of the range of the output filter (will be interpreted by the output device. oTo End of the reange of the output fileter (will be interpreted by the output device oNoDrum On MIDI like devices avoid the channel usually used for percussion. Route created by this function (smart pointer).
References DEBUGLOGTYPE, DoCreate, factory, intrusive_ptr_get_refcount.
static void mutabor::RouteFactory::Destroy()
Destroy the route factory.
Call this function instead of deleting the factory.
References factory.
static void mutabor::RouteFactory::LoadRoutes(tree_storage &config)
load the routes from a tree based configuration
config conifiguration to be read from
References DoLoadRoutes, factory.
Referenced by mutaborGUI::MutRouteWnd::CmRouteLoad, LoadRoutes.
static void mutabor::RouteFactory::SaveRoutes(tree_storage &config)
write the routes to the configuration
config configuration to be written to
References DoSaveRoutes, factory.
Referenced by mutaborGUI::MutRouteWnd::CmRouteSave, SaveRoutes.
mutabor::RouteFactory::~RouteFactory()
Destructor.
This destructor will destroy the route factory. It does not touch the route objects that are created using this class.You should not delete the factory directly as it saves a pointer to
RouteClass * mutabor::RouteFactory::DoCreate() const __attribute__((malloc))
Creates a generic route.
This functions creates a route object on the heap and returns a smart pointer to it. This route will not be preconfigured.Each RouteFactory class must override this function to return a route of its type.Route smart pointer to the newly created route
Referenced by Create.
RouteClass * mutabor::RouteFactory::DoCreate(InputDevice &in, OutputDevice &out, RouteType type, int iFrom, int iTo, Box box, bool active, int oFrom, int oTo, bool oNoDrum) const __attribute__((malloc))
Creates a preconfigured route.
This functions creates a route object on the heap and returns a smart pointer to it. This route will be preconfigured according the data provided in the arguments.Each RouteFactory class must override this function to return a route of its type. in InputDevice& Reference to a smart pointer for the input device where the route starts. out OutputDevice& End point of the route. type RouteType Type of the input filter. See RouteType for more information. iFrom start of the range for the input filter. Its meaning depends on the input filter type. iTo end of the range for the input filter. Its meaning depends on the input filter type. box box to be used. Values less than 0 indicate a pass through route or a GMN box. active indicates whether the events on the route may change the tuning of the box. Regardless of this setting the box referenced by the box parameter will influence the tuning of the events in this route. oFrom Start of the range of the output filter (will be interpreted by the output device. oTo End of the reange of the output fileter (will be interpreted by the output device oNoDrum On MIDI like devices avoid the channel usually used for percussion. Route created by this function (smart pointer).
void mutabor::RouteFactory::DoLoadRoutes(tree_storage &config) const
load the routes from a tree based configuration
config conifiguration to be read from
References mutabor::tree_storage::GetPath, mutabor::BoxFactory::LoadBoxes, mutabor::DeviceFactory::LoadInputDevices, mutabor::DeviceFactory::LoadOutputDevices, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::LoadRoutes, mutASSERT, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent.
Referenced by LoadRoutes.
void mutabor::RouteFactory::DoSaveRoutes(tree_storage &config) const
write the routes to the configuration
config configuration to be written to
References mutaborGUI::DebugCheckRoutes, mutabor::tree_storage::DeleteGroup, mutabor::tree_storage::GetPath, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::InitializeIds, mutASSERT, mutabor::BoxFactory::SaveBoxes, mutabor::DeviceFactory::SaveInputDevices, mutabor::DeviceFactory::SaveOutputDevices, mutabor::TRouteClass< InputDevice, OutputDevice, Box >::SaveRoutes, mutabor::tree_storage::toLeaf, mutabor::tree_storage::toParent.
Referenced by SaveRoutes.